### ISSUE TITLE
in zone overrides for image resizing add option to control "resize images from any origin"

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#1000]
### Current Terraform version

0.14.7

### Description

currently when running overrides, I can enable the image resizing, but I cant control "resize images from any origin". when i add this manually in the UI, it gets reset after every run to not set

### Use cases

we run the overrides few times a day as part of the zone refresh and not having this option requires manually going into UI to add this feature.

### Potential Terraform configuration

no configuration exists

**Comment by vitdolphin** [comment]
hi @jacobbednarz , any plans to get this fixed?

**Comment by jacobbednarz** [comment]
this functionality is already available (added in #639) and v2.5.1. please see documentation at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#image_resizing

**Comment by vital4ik** [comment]
@jacobbednarz I am referring to the option to "resize from any origin" which is not available, can you please reopen?
![image](https://user-images.githubusercontent.com/7430707/124530434-80e48100-ddda-11eb-9420-2704d3e542ea.png)
here is the image for the context.  I am referring to the checkmark below the on/off toggle

**Comment by jacobbednarz** [comment]
that is the option I've referenced above. see the documentation for examples and you can try it out for yourself.

**Comment by vital4ik** [comment]
I have tried and when i set this option with "on" it turns it on if it was off or unchecks this checkmark if it was on and had the 
"resize images from any origin" checked.  which option on zone overrides would keep it on? is it "open"?
