### ISSUE TITLE
Make `ownership_challenge` argument optional (or documented) for `cloudflare_logpush_job` resources

### ISSUE THREAD

**Issue by taurelius** [cloudflare/terraform-provider-cloudflare#1010]
### Current Terraform version

0.14.8

### Description

Currently the `ownership_challenge` argument is required when creating a `cloudflare_logpush_job` resource. However, it is not a required field (in the API) when creating a Logpush job with a destination of either Datadog or Splunk.

[From the docs:](https://developers.cloudflare.com/logs/logpush/datadog)
> Note: Unlike configuring Logpush jobs for AWS S3, GCS, or Azure, there is no ownership challenge when configuring Logpush to Datadog.

I can see the thinking here, the majority of destinations do require an ownership challenge, though it means when creating a Datadog job a dummy value needs to be provided e.g. `0`.

I think either the argument should be made optional and a note added that it's required for the majority of use-cases, or left as is calling out the workaround for Datadog and Splunk. I'm more than happy to raise a PR for either of these.

The Cloudflare API docs for this also [seem to be incorrect](https://api.cloudflare.com/#logpush-jobs-create-logpush-job), again calling out the `destination_challenge` field as required (I've checked and verified it isn't) not matching up with the Datadog integration guide linked above.

### Use cases

Creating a `cloudflare_logpush_job` with a destination of either Datadog or Splunk

### Potential Terraform configuration

N/A

### References

- https://developers.cloudflare.com/logs/logpush/datadog
- https://developers.cloudflare.com/logs/logpush/splunk
- https://api.cloudflare.com/#logpush-jobs-create-logpush-job

**Comment by jacobbednarz** [comment]
Sorry for the radio silence on this one @taurelius, it fell off my radar. 

I'm 👍 to making the schema attribute optional and instead enforcing the validation in the `Create`/`Update` operations themselves looking at the `destination_conf` value. Something like the following would suffice:

```go
destConf := d.Get("destination_conf").(string) 
ownershipChallenge := d.Get("ownership_challenge").(string) 
var re = regexp.MustCompile(`^(datadog|splunk)\:\/\/`)

if ownershipChallenge == "" && !re.MatchString(destConf) {
    // we will error out as the destination conf requires a value
} 
```
