### ISSUE TITLE
cloudflare_ip_ranges doesn't return up to date values

### ISSUE THREAD

**Issue by shiftie** [cloudflare/terraform-provider-cloudflare#1020]
### Confirmation

My issue isn't already found on the issue tracker.
I have replicated my issue using the latest version of the provider and it is still present.

### Terraform version

Terraform v0.14.5

### Affected resource(s)

- cloudflare_ip_ranges

### Terraform configuration files

data "cloudflare_ip_ranges" "cloudflare" {}

output "cloudflare_ips" {
  value = data.cloudflare_ip_ranges.cloudflare.ipv4_cidr_blocks
}

### Expected output

// https://www.cloudflare.com/ips-v4

173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
172.64.0.0/13
131.0.72.0/22
104.16.0.0/13
104.24.0.0/14

### Actual output

cloudflare_ips = [
      + "103.21.244.0/22",
      + "103.22.200.0/22",
      + "103.31.4.0/22",
      + "104.16.0.0/12",
      + "108.162.192.0/18",
      + "131.0.72.0/22",
      + "141.101.64.0/18",
      + "162.158.0.0/15",
      + "172.64.0.0/13",
      + "173.245.48.0/20",
      + "188.114.96.0/20",
      + "190.93.240.0/20",
      + "197.234.240.0/22",
      + "198.41.128.0/17",
    ]

### Steps to reproduce

1. Output values fetched via `cloudflare_ip_ranges` data source
2. Returned ips do not match those presented on Cloudflare's website

**Comment by markbaird** [comment]
Although the IP list URLs are defined the source code:

```
const (
	urlIPV4s = "https://www.cloudflare.com/ips-v4"
	urlIPV6s = "https://www.cloudflare.com/ips-v6"
)
```

They don't actually appear to be used. I think that's probably old code that could be removed.

The data source actually queries the CloudFlare API for the IP list, which you can see here: https://api.cloudflare.com/client/v4/ips

The CloudFlare API is still returning the old IP list at this time. I believe as soon as the CloudFlare API starts returning the updated list, this Terraform provider will also.

**Comment by jacobbednarz** [comment]
@markbaird is correct; new IPs were added to the endpoints and it hadn't refreshed yet. This isn't a bug in Terraform and the service teams have mentioned this should be rectified by now.

**Comment by markbaird** [comment]
It's not actually rectified yet in the CloudFlare API. As of this post time, the CloudFlare API is still returning the old IPs.

**Comment by shiftie** [comment]
👍 thank you

**Comment by markbaird** [comment]
The Cloudflare API, and subsequently this Terraform provider, are now returning the new IP list.
