### ISSUE TITLE
Add file support for `cloudflare_workers_kv` resource

### ISSUE THREAD

**Issue by alastair-smith** [cloudflare/terraform-provider-cloudflare#1021]
### Current Terraform version

Terraform v0.14.9

### Description

Add two new variables to the [`cloudflare_workers_kv`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/workers_kv) resource to enable uploading of a file's content to KV without putting the full contents of the file in the plan/state as KV values can be [up to 25 MB in size](https://developers.cloudflare.com/workers/platform/limits#kv).

The first variable allowing users to upload a file by referencing the path rather than using `filebase64("my-file.txt")`.

The second variable would be a hash of the contents of the file so that subsequent applies can detect if the value needs to be updated.

### Use cases

I wish to upload my static assets to Cloudflare KV so that I can serve them from a worker without my terraform state or plan becoming excessively large.

I am using terraform for the rest of the infrastructure of my application so I want to avoid having to use extra tools like [wrangler](https://github.com/cloudflare/wrangler) or direct API requests.

### Potential Terraform configuration

```hcl
resource "cloudflare_workers_kv" "example" {
  namespace_id = cloudflare_workers_kv_namespace.example_ns.id
  key          = "fun-facts"

  file {
    source = "fun-facts.txt"
    hash   = filemd5("fun-facts.txt")
  }
}
```

* The contents of the file is uploaded as the value in KV 
* `file` and `value` cannot be set at the same time
* Potentially offer a variable to base64 encode the file before setting it as the value, although this could be handled by the user outside of terraform, or using some sort of data block

**Comment by jacobbednarz** [comment]
Have you tried use [`file`](https://www.terraform.io/docs/language/functions/file.html) as the `value` value? This looks to do exactly what you're requesting without changes. 

Alternatively, there is the `local` provider which provides a [`local_file`](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) and you can reference the `body` attribute.

**Comment by alastair-smith** [comment]
The `file` value and `local_file` data block both also seem to add the entire content of the file to my plan and state file. For very small files this is ok, but for bigger files it means I have strings of lengths in the 100,000's in my state file and plans.

**Comment by jacobbednarz** [comment]
As it stands, I'm sorry but that really isn't a big enough driver for me to not use built functionality versus maintaining our own interface to the Workers API. We attempt to be a thin wrapper around the existing service APIs and this is going against that for the sake of a large state file which majority of users will not be managing manually. On top of this, other tooling that relies on this library (such as `cf-terraforming`) will have require custom code paths for handling resources that are not a 1:1 mapping which means we are creating additional work there. 

I'm closing this off for now however if we get more requests and use cases, I'm up for revisiting the decision.
