### ISSUE TITLE
provider crashes on zone overrides

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#1033]
### Confirmation

My issue isn't already found on the issue tracker.
I have replicated my issue using the latest version of the provider and it is still present.

### Terraform version

0.15.0

### Affected resource(s)

zone overrides

### Terraform configuration files

```hcl
resource "cloudflare_zone_settings_override" "overrides" {
  zone_id = data.google_secret_manager_secret_version.zoneid.secret_data
  settings {
    zero_rtt   = "on" 
    always_online = "off"
    always_use_https = "on"
    automatic_https_rewrites = "on"
    brotli = "on"
    browser_cache_ttl = 14400
    browser_check = "off"
    cache_level = "aggressive"
    challenge_ttl = 1800
    cname_flattening = "flatten_at_root"
    development_mode = "off"
    //browser_cache_ttl = 7200 - looks to be decomissioned setting - value not in UI
    email_obfuscation = "on"
    h2_prioritization = "on"
    hotlink_protection = "off"
    http2 = "on"
    http3 = "on"
    image_resizing = "on" //getting read only on this durting implementaiton TODO: check with cloudflare rep
    ip_geolocation = "on"
    ipv6 = "on"
    max_upload = 100
    min_tls_version = "1.2"
    minify {
        css = "on"
        html = "on"
        js = "on"
      }
    mirage = "on"
    mobile_redirect  {
        mobile_subdomain = ""
        status = "off"
        strip_uri = false
      }


    opportunistic_encryption = "on"
    opportunistic_onion = "on"
    origin_error_page_pass_thru = "on"
    //polish = "lossy"
    prefetch_preload = "off"
    privacy_pass = "on"
    pseudo_ipv4 = "off"
    response_buffering = "off"
    rocket_loader = "on"

    security_header {
        enabled = false
        include_subdomains = false
        max_age = 0
        nosniff = false
        preload = false
      }

    security_level = "medium"
    server_side_exclude = "on"
    sort_query_string_for_cache = "off"
    ssl = "strict"
    tls_1_3 = "on" //TODO: need to investigate why it prevent proper destroy
    tls_client_auth = "off"
    true_client_ip_header = "on"
    waf = "on"
    //webp = "on"
    websockets = "on"
  }
}
```

### Panic output

cloudflare_zone_settings_override.overrides: Destroying... [id=1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
cloudflare_zone_settings_override.overrides: Destruction complete after 4s
cloudflare_zone_settings_override.overrides: Creating...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v2.20.0 plugin:

panic: runtime error: slice bounds out of range [42:41]

goroutine 98 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.updateSingleZoneSettings(0xc000937000, 0x29, 0x40, 0xc00016a780, 0xc00037e280, 0x20, 0xc000937000, 0x2a, 0x40, 0x0, ...)
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_zone_settings_override.go:689 +0x4d8
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareZoneSettingsOverrideUpdate(0xc0001e16c0, 0x1e514a0, 0xc00016a780, 0x1, 0x1)
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_zone_settings_override.go:729 +0x308
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareZoneSettingsOverrideCreate(0xc0001e16c0, 0x1e514a0, 0xc00016a780, 0x2, 0x26f70c0)
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_zone_settings_override.go:535 +0x9c7
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001307e0, 0xc0002a3090, 0xc00079cae0, 0x1e514a0, 0xc00016a780, 0x1ce5c01, 0xc0008a86c8, 0xc0007e1080)
	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/resource.go:310 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0005a0300, 0xc000613a38, 0xc0002a3090, 0xc00079cae0, 0xc0007b41a8, 0xc0007b2020, 0x1ce8060)
	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00059a2b0, 0x2061a10, 0xc0006ece10, 0xc0001e11f0, 0xc00059a2b0, 0xc0006ece10, 0xc000670ba0)
	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1e11d40, 0xc00059a2b0, 0x2061a10, 0xc0006ece10, 0xc0004a88a0, 0x0, 0x2061a10, 0xc0006ece10, 0xc00013e400, 0x8d4)
	github.com/hashicorp/terraform-plugin-sdk@v1.16.1/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00001c1c0, 0x206beb8, 0xc00037b980, 0xc000798200, 0xc0004a7350, 0x26b4f80, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.31.1/server.go:1180 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00001c1c0, 0x206beb8, 0xc00037b980, 0xc000798200, 0x0)
	google.golang.org/grpc@v1.31.1/server.go:1503 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000038520, 0xc00001c1c0, 0x206beb8, 0xc00037b980, 0xc000798200)
	google.golang.org/grpc@v1.31.1/server.go:843 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.31.1/server.go:841 +0x1fd

Error: The terraform-provider-cloudflare_v2.20.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

ERRO[0017] Hit multiple errors:
Hit multiple errors:
exit status 1

### Expected output

zone overrides correcty applied

### Actual output

ERRO[0017] Hit multiple errors:
Hit multiple errors:
exit status 1

### Steps to reproduce

1. install tf 15 and cf provider 2.20.0
2. run the zone overrides above
3.  first  run fails with the following: Error: HTTP status 400: Unrecognized zone setting name (1006)
4. second run fails with cloudflare provider crashing

**Comment by jacobbednarz** [comment]
@vital4ik can you please provide the **full** TF_DEBUG output for this? the error suggests the configuration is getting a setting name it doesn't understand.

**Comment by jacobbednarz** [comment]
closing due to lacking information, we can revisit once we get the full debug output.
