### ISSUE TITLE
Add Transform Rule resources

### ISSUE THREAD

**Issue by quinlanj** [cloudflare/terraform-provider-cloudflare#1036]
### Current Terraform version

Terraform v0.14.3
+ provider registry.terraform.io/cloudflare/cloudflare v2.19.2

### Description

Cloudflare recently released Transform Rules, and it would be great if we could make Transform Rule resources the way we can currently make Page Rule resources in terraform.

![Screen Shot 2021-04-15 at 11 42 40 PM](https://user-images.githubusercontent.com/6380927/114986015-5375e000-9e48-11eb-9b34-1a715915349f.png)

### Use cases

Codify everything I can create in the 'Transform Rules' section of the UI into terraform 

### Potential Terraform configuration

Analogous to page rules, so something like this:
```hcl
resource "cloudflare_transform_rule" "foobar" {
  # The DNS zone ID to which the transform rule should be added.
  zone_id = var.cloudflare_zone_id

  # Whether the transform rule is active or disabled.
  status = "active" 

  # The priority of the transform rule among others for this target
  priority = 1 

  # a descriptive name
  name = 'test rule'
  
  # an expression denoting which incoming requests to target
  # An expression is either:
  #   A base expression containing field, operator and value properties
  #   A compound expression containing operator, operand_a and operand_b properties
  #       operand_a and operand_b must contain a valid expression
  target {
    operator = 'AND'
    operand_a {
      field = 'hostname'
      operator = 'equals'
      value = 'foo.bar.com'
    }
    operand_b {
      field = 'cookie'
      operator = 'contains'
      value = 'blah'
    }
  }

  # rewrite actions taken by the transform rule
  rewrite {
    path {
      preserve = true
    }
    query {
      rewrite {
        dynamic = "regex_replace(http.request.uri.path, "^/([^/]*)/(.*)$", "/${2}") "
      }
    }
  }
}
```

**Comment by MrMickS** [comment]
Is there any news on this. It is something that we are interested in using.

**Comment by jacobbednarz** [comment]
There hasn't been anything directly targeting Transformation Rules however a large part of the support for it will work by proxy very soon (`cloudflare/cloudflare-go` already has support if you want to play with the Golang SDK). We are making the move to an approach called [Rulesets](https://developers.cloudflare.com/firewall/cf-rulesets) which is a new concept that abstracts away the product configuration into a reusable syntax which can be across the board. 

I'm in the process of adding support for the V2 WAF at the moment via #1143 however once that lands, _most*_ of the functionality will be possible if you get the configuration right. For instance, merging that change will allow Magic Transit, Transformation Rules, Custom Firewall Rulesets, Managed Rulesets and Rate Limiting to largely work as is.

Word of caution though, until it's documented **please do not consider it production ready as your mileage may vary greatly** depending on your account and entitlements that are provisioned. If in doubt, trial it on a non-production domain or get in touch with your Cloudflare Account team to discuss the suitability.

---

_*where most is standard configurations. some more exotic setups definitely not covered_

**Comment by casertap** [comment]
Please @jacobbednarz can you give us an idea of the timeline to have terraform-cloudflare proxying cloudflare-go to allow creating transformation rules? 
Thanks for all the good work!
Cheers

**Comment by romaninsh** [comment]
Experiencing some issues with error:

```
│ Error: error creating ruleset artists: HTTP status 400: rewrite action parameters are required for the rewrite action
```

Reference module:
```
  # module.cloudflare.cloudflare_ruleset.static-rule["user-profiles"] will be created
  + resource "cloudflare_ruleset" "static-rule" {
      + description = "user-profiles"
      + id          = (known after apply)
      + kind        = "zone"
      + name        = "user-profiles"
      + phase       = "http_request_transform"
      + zone_id     = "e93redactedfc0"

      + rules {
          + action      = "rewrite"
          + description = "URI transformation path example"
          + expression  = "(http.host eq \"user-profiles.example.com\")"
          + id          = (known after apply)
          + ref         = (known after apply)
          + version     = (known after apply)

          + action_parameters {

              + uri {
                  + path {
                      + expression = "concat(\"/file/example-prd-user-profiles\", http.request.uri.path)"
                    }
                }
            }
        }
    }
```
