### ISSUE TITLE
Support for Cloudflare Pages

### ISSUE THREAD

**Issue by devth** [cloudflare/terraform-provider-cloudflare#1037]
### Current Terraform version

```
± terraform -v              
Terraform v0.12.26
```

### Description

https://blog.cloudflare.com/cloudflare-pages-ga/

### Use cases

Create and manage Pages

### Potential Terraform configuration

```hcl
...
```

I really don't know!

**Comment by fr3fou** [comment]
Now that https://github.com/cloudflare/cloudflare-go/pull/724 was merged in `cloudflare-go`, can we expect this functionality soon?

**Comment by marcus-sa** [comment]
Any updates?

**Comment by marcus-sa** [comment]
Any updates?

**Comment by JamesTaliaferro** [comment]
Bumping this so it doesn’t slip into obscurity…
At the very least, it seems like it’s probably no longer `pending-upstream-library` since Pages features have made it into `cloudflare-go`.

**Comment by Cyb3r-Jak3** [comment]
@jacobbednarz I call dibs
