### ISSUE TITLE
Enable mTLS for hostnames

### ISSUE THREAD

**Issue by DDuarte** [cloudflare/terraform-provider-cloudflare#1044]
### Current Terraform and Cloudflare provider version

```
Terraform v0.14.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.17.0
```

### Description

Functionality to enable mTLS for hostnames is not currently available on this provider and it is also not documented on the API v4 documentation.
The UI jorney is shown in https://developers.cloudflare.com/ssl/client-certificates/enable-mtls.

The UI is doing a PUT request to `/api/v4/zones/:zone_identifier/certificate_authorities/hostname_associations` with body:

```json
{
  "hostnames": ["host1.example.com", "host2.example.com"]
}
```

### Use cases

Manage which hosts have Mutual TLS enabled, which is part of the API Shield product (https://developers.cloudflare.com/ssl/client-certificates).

### Potential Terraform configuration

```hcl
resource "cloudflare_ca_mtls_hosts" "mtls_hosts" {
  zone_id   = "somezoneid"
  hostnames = ["host1.example.com", "host2.example.com"]
}
```

**Comment by smnalex** [comment]
@jacobbednarz why was this closed?

**Comment by yan12125** [comment]
I'm interested in this feature and I may look into code changes, but I don't have an Enterprise account. How can I test the "Bring your own CA" feature?

**Comment by ILLISIS** [comment]
+1 for this

**Comment by frvade** [comment]
+1 we faced this and have to combine terraform with api usage

**Comment by bnowak-syn** [comment]
Plus it would be nice to have support for this in worker_script resource, as per the docs:
https://developers.cloudflare.com/workers/runtime-apis/mtls/

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by pedrocunha** [comment]
Is Cloudflare going to prioritise this soon?

**Comment by ILLISIS** [comment]
@jacobbednarz hey mate, has there been any movement on this internally? I have lots of domains I need to set hosts on.

(enterprise customer)

**Comment by anuar2k** [comment]
I managed to work around this issue using the Mastercard/restapi provider v2.0.1.

This approach disables server-state synchronization, so Terraform won’t detect external changes in Cloudflare. However, if Cloudflare resources are managed exclusively through Terraform, it works reliably.

Example usage:
```tf
provider "restapi" {
  alias = "cf_zone"
  uri = "https://api.cloudflare.com/client/v4"

  headers = {
    "Authorization" = "Bearer ${var.token_zone}"
    "Content-Type"  = "application/json"
  }
}

locals {
  path_mtls_hostnames = "/zones/${local.zone_id}/certificate_authorities/hostname_associations"
}

resource "restapi_object" "mtls_hostnames" {
  provider = restapi.cf_zone
  path     = local.path_mtls_hostnames
  # force paths for following ops to not incorporate ID
  create_path = local.path_mtls_hostnames
  read_path =   local.path_mtls_hostnames
  update_path = local.path_mtls_hostnames
  destroy_path = local.path_mtls_hostnames

  create_method = "PUT"
  update_method = "PUT"
  destroy_method = "PUT"

  object_id = "dummy" # this is a singleton and there's no ID in payload
  ignore_all_server_changes = true

  data = jsonencode({
    hostnames = [
      "cf-test.${local.domain}"
    ]
  })
  
  # clears all entries upon deletion with PUT
  destroy_data = jsonencode({
    hostnames = []
  })
}
```

**Comment by paweloczadly** [comment]
Hi everyone,

I'm currently working on automating our mTLS setup and noticed that the resource for managing hostname associations (equivalent to the hostname_associations API endpoint: https://developers.cloudflare.com/api/resources/certificate_authorities/subresources/hostname_associations/methods/update/) seems to be missing in the 5.x provider.

Are there any plans to implement a dedicated resource for this in the near future?

Pinging @KaydeeDee as you've been incredibly helpful with my previous Cloudflare provider queries — would love to get your thoughts on whether this is on the roadmap or if there's a recommended workaround for v5.0+.

Thanks!
