### ISSUE TITLE
Rate limit advanced response custom HTML not working

### ISSUE THREAD

**Issue by bedge** [cloudflare/terraform-provider-cloudflare#1046]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Have not upgraded to TF 0.15 as that's a major upgrade. Plus, this is specific to the CF provider.

[I] ➜ terraform -v
Terraform v0.14.9
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.19.1

I have basic rate limiting working through terraform.

However I want to provide a custom HTML response, which is theoretically possible as documented here:
https://support.cloudflare.com/hc/en-us/articles/115001635128-Configuring-Cloudflare-Rate-Limiting#5iIwkkHwcJbNRynWjrDIGb

Specifically:

> 2. Select a Response type format. The maximum response size is 32kb.
> 
> To display a custom HTML page or more than the 32kB limit, add a meta refresh to the Rate Limiting rule via the Cloudflare API via the Response object of the Action parameter.  For example: 
> 
> "response": { "content_type": "text/html", "body": "\u003cmeta http-equiv=\"refresh\" content=\"0; url=https://www.example.com/about\" /\u003e"}

Here's the relevant section of my terraform, the `action` block:
```
  action {
    mode = "ban"
    timeout = 10
    response {
      content_type = "application/json"
      body         = "\"response\": ${data.local_file.throttled.content}"
    }
  }
```
where `data.local_file.throttled.content` is read with
```
data "local_file" "throttled" {
  filename = "${path.module}/throttled-redirect.json"
}
```
and the file contains:
```
{
  "content_type": "text/html",
  "body": "\\u003meta http-equiv=\"refresh\" content=\"0; url=https://nghc-www.s3.eu-central-1.amazonaws.com/hyperdesign/sbox/www/index.html\" /\\u003"
}
```

As expected, this results is the browser simply displaying the json contents as shown in the file above, as plain text.

I don't see how one can get the browser to interpret html, ie: the `meta http-equiv` when `text/html` is not permitted as a content type:
```
Error: expected action.0.response.0.content_type to be one of [text/plain text/xml application/json], got text/html
```
 
Is there a working example of this you could refer me to? 

The docs are a bit sparse in this area.

thanks

### Affected resource(s)

cloudflare_rate_limit

### Terraform configuration files

```hcl
data "local_file" "throttled" {
  filename = "${path.module}/throttled-redirect.json"
}



resource "cloudflare_rate_limit" "hyperdesign_limit" {
  zone_id = data.vault_generic_secret.zone_id.data["value"]
  // Testing thresholds
  threshold = 5
  period    = 10
  match {

    request {
      url_pattern = "${local.cf_url}/*"
      schemes     = ["HTTP", "HTTPS"]
      methods     = ["GET", "POST", "PUT", "DELETE", "PATCH", "HEAD"]
    }


    response {
      statuses       = [200, 201, 202, 301, 429]
      origin_traffic = false
      //      headers = [
      //        {
      //          name  = "Host"
      //          op    = "eq"
      //          value = "localhost"
      //        },
      //        {
      //          name  = "X-Example"
      //          op    = "ne"
      //          value = "my-example"
      //        }
      //      ]
    }
  }
  action {
    //    mode = "challenge"
    //    mode = "simulate"
    mode = "ban"
    // Not allowed for js_challenge mode (CAPTCHA)
    timeout = 10
//    response {
//      content_type = "application/json"
//      body         = "\"response\": ${data.local_file.throttled.content}"
//    }
    response {
        content_type = "application/json"
//      content_type = "text/html"
      body         = "\\u003meta http-equiv=\"refresh\" content=\"0; url=https://nghc-www.s3.eu-central-1.amazonaws.com/hyperdesign/sbox/www/index.html\" /\\u003"
    }
  }
  // (Optional) Determines how rate limiting is applied. By default if not specified, rate limiting applies to the clients IP address
  correlate {
    by = "nat"
  }
  description = "Limit for ${local.cf_url}/* (terraform)"
  bypass_url_patterns = [
    "${local.cf_url}/*.woff*", // fonts
    "${local.cf_url}/*.ico",   //
    "${local.cf_url}/assets/*",
    "${local.cf_url}/rest/*",
  ]
}
```

### Panic output

No errors from terraform.

### Expected output

The ban case should direct to the specified html page

### Actual output

The terraform apply works, it's just the HTML rate limit page that does not.

### Steps to reproduce

terraform apply
hit the page until banned

**Comment by bedge** [comment]
Debug output attached (with tokens stripped)
[tf.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/6370339/tf.log)

**Comment by bedge** [comment]
I've experimented with a few different encodings of the action.response payload.

Here's the latest as retrieved from the cloudflare API:
```
            "action": {
                "mode": "ban",
                "timeout": 11,
                "response": {
                    "content_type": "application/json",
                    "body": "\"response\": {\n  \"content_type\": \"text/html\",\n  \"body\": \"<meta http-equiv=\\\"refresh\\\" content=\\\"0; url=https:\/\/nghc-www.s3.eu-central-1.amazonaws.com\/hyperdesign\/sbox\/www\/index.html\\\" \/>\"\n}\n"
                }
            }
```

**Comment by jacobbednarz** [comment]
By the looks of things, there are a couple of bits of confusion here.

The first is that the support documentation is incorrect. Attempting to send a payload directly to the API for `text/html` results in a validation failure.

```
$ curl "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/rate_limits" \
  -H "Content-Type: application/json" \
  -H "X-Auth-Email: $CF_EMAIL" \
  -H "X-Auth-Key: $CF_API_KEY" \
  -d '{"description":"example rate limit","match":{"request":{"methods":["GET"],"schemes":["HTTP","HTTPS"],"url":"well-groomed-alpaca.com/html-example-upbuenloqe"},"response":{}},"threshold":2000,"period":10,"action":{"mode":"ban","timeout":3600,"response":{"content_type":"text/html","body":"<meta http-equiv=\"refresh\" content=\"0; url=https://www.example.com/\" />"}}}'
```

```json
{
  "result": null,
  "success": false,
  "errors": [
    {
      "message": "ratelimit.api.validation_error:content_type was text/html but must be one of: text/plain|text/xml|application/json"
    }
  ],
  "messages": []
}
```

As you can see, `text.html` isn't supported by the service (I've also confirmed this is intentional in the service itself). The other part of this that looks to have confused you is that your sending an API payload as a Terraform schema option. Despite the incorrect information in the support documentation, it states the example you're using is an **API call** which Terraform does on your behalf so you're kind of double handling it and it's ending up incorrect.

As for a fix to get your desired outcome, you will probably want to instead setup a [`cloudflare_custom_page`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_pages) resource at the zone level pointing to the HTML document you wish to use which will allow you to display a custom error page when users hit a rate limit threshold. Let me know if you have any further questions!

**Comment by bedge** [comment]
Yep, I realized the docs weren't helping too.

Once I realized `text/xml` was still being handled by the browser as potentially XML, I came up with this, which works:

An html file, literal, without any encoding needed:
```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <title>Hyperdesign rate limit</title>
    <meta http-equiv="refresh" content="0;URL='https:/my-www/index.html'" />
</head>
<!--Body may be used for transitional message to user before seeing ban page-->
<!--<body>-->
<!--<p>Rate limit violation <a href="https:/my-www/index.html">-->
<!--    Rate limit violation</a>.</p>-->
<!--</body>-->
</html>
```
Read the file:
```
data "local_file" "ban" {
  filename = "${path.module}/ban.html"
}
```

Then the `match.action`
```
  action {
    mode = "ban"
    timeout = 10
    response {
      content_type = "text/xml"
      body         = data.local_file.ban.content
    }
  }
```

**Comment by bedge** [comment]
I would suggest an update to the docs though, this is far from intuitive from a terraform user POV.

**Comment by bedge** [comment]
Sorry, one last clarification, are you suggesting that the `cloudflare_custom_page` option be used **_instead_** of a handling the custom rate limiting at the `cloudflare_rate_limit` level?
ie:Assuming all 10xx errors are from rate limiting(?) so if I override that I'll get the custom page, for **_all_** rate limit rules without needing to specify it at the individual `cloudflare_rate_limit` level?

Which takes precedence if I specify both? 
ie: if I do the  `cloudflare_custom_page` thing, AND add a custom match rule page, will I get a new "default" rate limit page from the `cloudflare_custom_page`, but still be able to override it for specific `cloudflare_rate_limit`s?

I would assume the `cloudflare_rate_limit` would take precedence, being the more specific configuration.
