### ISSUE TITLE
Add support for cache_key in cloudflare_page_rule

### ISSUE THREAD

**Issue by cookandy** [cloudflare/terraform-provider-cloudflare#1054]
### Current Terraform and Cloudflare provider version

Terraform:

```
Terraform v0.15.3
on darwin_amd64
```

Cloudflare:

```
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = ">= 2.20.0"
    }
```

### Description

Hello,

We have a few page rules that have a custom cache key using the `Accept` header. These were rules we had Cloudflare Support create for us, as adding this header isn't supported via the UI. 

In the API, the cache key appears as `cache_key` with a string value instead of the `cache_key_fields` object mentioned in the [API documentation](https://api.cloudflare.com/#available-page-rules-for-a-zone-list-available-page-rule-setting). 

For example:

```json
    {
      "id": "xxxxxx",
      "targets": [
        {
          "target": "url",
          "constraint": {
            "operator": "matches",
            "value": "foo.bar.com/*"
          }
        }
      ],
      "actions": [
        {
          "id": "browser_cache_ttl",
          "value": 31536000
        },
        {
          "id": "cache_level",
          "value": "cache_everything"
        },
        {
          "id": "edge_cache_ttl",
          "value": 31536000
        },
        {
          "id": "sort_query_string_for_cache",
          "value": "on"
        },
        {
          "id": "cache_key",
          "value": "${header:origin}::${scheme}://${host_header}${uri}::${header:accept}"
        }
      ],
      "priority": 87,
      "status": "active",
      "created_on": "2021-04-12T19:18:42.000000Z",
      "modified_on": "2021-04-12T21:01:05.000000Z"
    }
```

Looking at the latest [`cloudflare_page_rule` documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule) it appears there is no support for `cache_key`, only `cache_key_fields`.

Can we please have support for `cache_key` as well?

### Use cases

We're trying to Terraform _all_ of our page rules, including those with a custom cache key using the `Accept` header (or any Cloudflare Support-created page rule). 

### Potential Terraform configuration

```hcl
resource "cloudflare_page_rule" "foobar" {
  zone_id = var.cloudflare_zone_id
  target = "foo.bar.com/*"
  priority = 1

  actions {
    cache_key = "${header:origin}::${scheme}://${host_header}${uri}::${header:accept}"
  }
}
```

**Comment by jacobbednarz** [comment]
`cache_key` can only be managed by Cloudflare employees and should be replaced in favour of `cache_key_fields` if you wish to manage them yourself.

**Comment by cookandy** [comment]
Thanks for the quick reply @jacobbednarz! I didn't think to convert it. 

Can you please confirm that setting the `Accept` header is allowed via `cache_key_fields`? For example

```hcl
resource "cloudflare_page_rule" "foobar" {
  zone_id = var.cloudflare_zone_id
  target = "${var.cloudflare_zone}/app/*"
  priority = 1

  actions {
    cache_key_fields {
      header {
        include = ["Accept"]
      }
    }
  }
}
```

**Comment by jacobbednarz** [comment]
That looks correct but as with anything, YMMV so be sure to test in a
non-production like environment.
