### ISSUE TITLE
Support for Tags in cloudflare_logpush_job

### ISSUE THREAD

**Issue by dmuse89** [cloudflare/terraform-provider-cloudflare#1067]
### Current Terraform and Cloudflare provider version

terraform version: v0.15.1
provider terraform-provider-cloudflare_v2.20.0

### Description

When using an AWS S3 bucket in combination with Cloudflare's [cloudflare_logpush_job](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job), setting a lifecycle policy on the AWS S3 bucket leads to deletion of [logpush_ownership_challenge](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge) file, as the logs must be in the same folder as the ownership challenge file (as stated in #1019 and #1024).  

Currently, when setting the [AWS S3 Bucket Lifecycle Policy](https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html#intro-lifecycle-rules-filter) to automatically delete items older than N days, **it is only possible to filter items based on a Prefix (i.e., a subdirectory) or Tags.**  

Since the `destination_conf` attribute of the [logpush_ownership_challenge](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge) resource must be equal to `destination_conf` attribute of the [logpush_job](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job) (as also stated in #1019 and #1024), the challenge file is affected by the lifecycle-rule and will be deleted when the retention period is met.

**Alternative Fix:** remove the requirement that the `destination_conf` attribute of the [logpush_ownership_challenge](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge) resource must be equal to the `destination_conf` attribute of the [logpush_job](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job).  

*Components:*
* [aws_s3_bucket](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket)
* [logpush_job](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job)
* [logpush_ownership_challenge](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge)

### Use cases

By supporting tags, it is possible to adjust the lifecycle filter for AWS S3 buckets (by only deleting log files with a given tag), and to prevent the deletion of the challenge file.

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_job" "example_job" {
  enabled = true
  zone_id = "d41d8cd98f00b204e9800998ecf8427e"
  name = "My-logpush-job"
  logpull_options = "fields=RayID,ClientIP,EdgeStartTimestamp&timestamps=rfc3339"
  destination_conf = "s3://my-bucket-path?region=us-west-2"
  ownership_challenge = "0000000000000"
  dataset = "http_requests" 
  tags = {"key": "value",  "name": "log-file", "retention_period": "7days"}
}
```

### References

#1019
#954

**Comment by jacobbednarz** [comment]
This isn't the place for service requests, just the implantation of managing resources. 

I'd recommend dropping your use use into Cloudflare Support or your account representative for them to chat to the service team.

**Comment by felixfriedrich** [comment]
@dmuse89 Did you find a solution/workaround for this? I am facing the same issue. Right now I am recreating the ownership challenge on every Terraform run. That creates unnecessary noise, so I am not super happy with it.

**Comment by felixfriedrich** [comment]
Thanks for your reply. I ended up solving this a bit simpler than I expected, so I leave this here for the next person wondering how to do this.

I hard coded the value of the ownership challenge. This is documented as "Example Usage (manual inspection of S3 bucket)" on the docs: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job

**Comment by spanagiot** [comment]
What I ended up doing was to place the log files inside a prefix in the destination bucket, place my lifecycle policy in this prefix only and then, by using the `s3_object_copy`, copied the ownership file outside the directory/prefix.
Then, with a `aws_s3_object` data resource read the copied file like this
```
data "aws_s3_object" "challenge_copy_file" {
  bucket = "my_tests"
  key    = "challenge_copy.txt"
  depends_on = [ aws_s3_object_copy.challenge_copy ] # this is needed because TF will try to read this data block before applying anything and in result fail
}
```
and used it in the Cloudflare resources.

The good thing is that the `s3_object_copy` only checks if the destination exists, so the source file can be deleted without any issue.

**Comment by jmreicha** [comment]
I just ran into this, tried the suggested workaround and it did not work. After copying to a different location and removing the original challenge text file, logs are no longer being received in my bucket.
