### ISSUE TITLE
Attributes missing from documentation for cloudflare_argo_tunnel resource

### ISSUE THREAD

**Issue by phils** [cloudflare/terraform-provider-cloudflare#1068]
### Current Terraform and Cloudflare provider version

N/A

### Description

Trying to use values exposed by this resource:
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/argo_tunnel

However, the documentation is missing the 'attributes' section.

### Use cases

Use values returned by this resource in another resource or as state outputs.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
this was intentional as it didn't export any attributes. #1259 added one and this is now present so closing this one off.
