### ISSUE TITLE
Error: HTTP status 400: Only anomaly WAF packages can have their package attributes updated (1027)

### ISSUE THREAD

**Issue by alexkorotysh** [cloudflare/terraform-provider-cloudflare#1070]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
terraform -v
Terraform v0.15.4
on linux_amd64
```

```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "2.20.0"
    }
  }
}
```

### Affected resource(s)

- cloudflare_waf_package

### Terraform configuration files

```hcl
resource "cloudflare_waf_package" "cf_managed_ruleset" {
  zone_id     = cloudflare_zone.XXXXXXXXX.id
  package_id  = "1e334934fd7ae32ad705667f8c1057aa"
  action_mode = "challenge"
  sensitivity = "high"
}
```

### Expected output

I want to enable 2 WAF preset and I want to configure rules inside presets.

![image](https://user-images.githubusercontent.com/15368568/119033346-c88f8480-b9b5-11eb-890f-d4e419357f78.png)

### Actual output

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_waf_package.cf_managed_ruleset will be created
  + resource "cloudflare_waf_package" "cf_managed_ruleset" {
      + action_mode = "challenge"
      + id          = (known after apply)
      + package_id  = "1e334934fd7ae32ad705667f8c1057aa"
      + sensitivity = "high"
      + zone_id     = "a48151f1ceeb18c2ba365573178c75d4"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_waf_package.cf_managed_ruleset: Creating...
╷
│ Error: HTTP status 400: Only anomaly WAF packages can have their package attributes updated (1027)
│ 
│   with cloudflare_waf_package.cf_managed_ruleset,
│   on zone_waf.tf line 1, in resource "cloudflare_waf_package" "cf_managed_ruleset":
│    1: resource "cloudflare_waf_package" "cf_managed_ruleset" {
│ 
╵

### Steps to reproduce

1. Install the last TF
2. Use the last CF provider
3. Terrafrom apply

### Additional factoids

I've tried to work directly with API, but I've got 
```
{
    "success": false,
    "errors": [
        {
            "code": 1040,
            "message": "WAF is deprecated for this zone, Managed Rulesets should be used instead"
        }
    ],
    "messages": [],
    "result": null
}
```

**Comment by jacobbednarz** [comment]
Sorry for the issue @alexkorotysh. There is a bit of a misunderstanding here as despite that being labelled WAF in the UI, it's actually using a totally new backing service which the `cloudflare_waf_package` resource, isn't compatible with. Instead, there will be a new resource called Rulesets (https://api.cloudflare.com/#zone-rulesets-properties) which will eventually have `cloudflare-go`/Terraform support. There isn't an ETA for this however I've raised an external issue (#1071) you can watch to follow along with the progess.
