### ISSUE TITLE
Add support for device posture and teams lists

### ISSUE THREAD

**Issue by igoraj** [cloudflare/terraform-provider-cloudflare#1074]
### Current Terraform and Cloudflare provider version

2.2.20

### Description

Now that upstream has added support for device posture and Teams lists it would be awesome to add this features to terraform too.

Add support for device posture (cloudflare/cloudflare-go#625)
Add device posture rule type for Access Group (cloudflare/cloudflare-go#622)
Add Gateway Teams List (cloudflare/cloudflare-go#624)

### Use cases

- Add access rules that include device posture.
- Manage Teams lists via terraform.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
#1058 is already working on this
