### ISSUE TITLE
Error installing provider "cloudflare": openpgp: signature made by unknown entity

### ISSUE THREAD

**Issue by chaswag** [cloudflare/terraform-provider-cloudflare#1080]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v0.11.14, with the latest cloudflare provider (2.21.0).

### Affected resource(s)

The vanilla "cloudflare" provider, no arguments.

### Terraform configuration files

```hcl
provider "cloudflare" { }
```

### Debug output

Running ```terraform init```:

% terraform init     
2021/05/26 15:59:05 [INFO] Terraform version: 0.11.14  
2021/05/26 15:59:05 [INFO] Go runtime version: go1.12.4
2021/05/26 15:59:05 [INFO] CLI args: []string{"/usr/local/bin/terraform", "init"}
2021/05/26 15:59:05 [DEBUG] Attempting to open CLI config file: /Users/chasschley/.terraformrc
2021/05/26 15:59:05 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/05/26 15:59:05 [INFO] CLI command args: []string{"init"}
2021/05/26 15:59:05 [DEBUG] command: loading backend config file: /Users/chasschley/github/wag-tf-env-prod/live/prod/services/cloudflare-dns/foo
2021/05/26 15:59:05 [INFO] command: empty terraform config, returning nil
2021/05/26 15:59:05 [DEBUG] command: no data state file found for backend config
2021/05/26 15:59:05 [DEBUG] New state was assigned lineage "4b1e0ea8-6647-e034-4427-7d3bee2dbe7b"
2021/05/26 15:59:05 [INFO] command: backend initialized: <nil>
2021/05/26 15:59:05 [DEBUG] checking for provider in "."
2021/05/26 15:59:05 [DEBUG] checking for provider in "/usr/local/bin"
2021/05/26 15:59:05 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2021/05/26 15:59:05 [DEBUG] checking for provisioner in "."
2021/05/26 15:59:05 [DEBUG] checking for provisioner in "/usr/local/bin"
2021/05/26 15:59:05 [DEBUG] checking for provisioner in ".terraform/plugins/darwin_amd64"
2021/05/26 15:59:05 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2021/05/26 15:59:05 [INFO] command: backend <nil> is not enhanced, wrapping in local
2021/05/26 15:59:05 [DEBUG] checking for provider in "."
2021/05/26 15:59:05 [DEBUG] checking for provider in "/usr/local/bin"
2021/05/26 15:59:05 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2021/05/26 15:59:05 [DEBUG] plugin requirements: "cloudflare"=""

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

2021/05/26 15:59:06 [ERROR] 1 error occurred:
	* openpgp: signature made by unknown entity

2021/05/26 15:59:06 [DEBUG] plugin: waiting for all plugin processes to complete...
Error installing provider "cloudflare": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64

### Expected output

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.cloudflare: version = "~> 2.20"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

### Actual output

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "cloudflare": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64

### Steps to reproduce

1. Create a new terraform config with only the provider:
```provider "cloudflare" { }```
2. Run ```terraform init```

### Additional factoids

Pinning the provider to version "2.20.0" works. Pinning it to "2.21.0" manifests the error.

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs

**Comment by jacobbednarz** [comment]
this isn't due to the provider but the version of Terraform you are still using which will no longer have the correct GPG key following [the key revocation](https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512).

to fix, you'll need to update to one of the newer versions of Terraform listed at https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570.
