### ISSUE TITLE
Feature: add cloudflare_argo_tunnel_route resource

### ISSUE THREAD

**Issue by eidam** [cloudflare/terraform-provider-cloudflare#1086]
### Current Terraform and Cloudflare provider version

```
Terraform v0.15.4
+ provider registry.terraform.io/cloudflare/cloudflare 2.21.0
```

### Description

WARP to tunnel, it would be equivalent to `cloudflared tunnel route ip add CIDR TUNNEL_ID`
 
https://developers.cloudflare.com/cloudflare-one/tutorials/warp-to-tunnel

### Use cases

I do manage all of my tunnels with Terraform, and they are recreated sometimes. I would love to have the IP routes terraformed as well to eliminate manual steps.

### Potential Terraform configuration

```hcl
resource "cloudflare_argo_tunnel" "example" {
  account_id  = "example-acc-id" 
  name        = "example-name"
  secret      = "example-secret"
}

resource "cloudflare_argo_tunnel_route" "example" {
  cidr_block = "100.64.0.0/10" # most probably passed from other resource as well
  tunnel_id  = cloudflare_argo_tunnel.example.id
}
```

**Comment by griffinmyers** [comment]
Can this additionally apply to adding DNS routes to a tunnel? For example, the equivalent of:

```console
$ cloudflared tunnel route dns TUNNEL_ID CNAME
```

It seems like just setting up the CNAME via a `cloudflare_record` resource isn't sufficient for associating the route with the tunnel.

**Comment by tjstansell** [comment]
@griffinmyers 
> It seems like just setting up the CNAME via a cloudflare_record resource isn't sufficient for associating the route with the tunnel.

I think using `cloudflare_resource` is sufficient, but you need to wait for the next release if you're using the `cloudflare_argo_tunnel.cname` attribute or build your own with the correct domain.  See #1293 .

**Comment by griffinmyers** [comment]
@tjstansell thanks for the tip -- just confirmed that a well-formed `cloudflare_record` (assuming that's what you meant) will properly associate DNS to the tunnel. 

When I first tried this I probably used the `cname` attribute directly without looking a bit closer. Cheers!

**Comment by kkaczmarczyk** [comment]
Since there is an API in place now, is there a plan/roadmap to implement this provider?
It would be helpful in my case. We do have an Enterprise plan, if that can help somehow.
