### ISSUE TITLE
Using "@" as value on record cause resource to not be idempotent

### ISSUE THREAD

**Issue by DaazKu** [cloudflare/terraform-provider-cloudflare#1088]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/consul v2.12.0
+ provider registry.terraform.io/hashicorp/nomad v1.4.15
```

### Affected resource(s)

`cloudflare_record`

### Terraform configuration files

```hcl
resource "cloudflare_record" "resource" {
  type = "CNAME"
  name = "nomad-dashboard"
  value = "@"
  proxied = true
  zone_id = var.cloudflare_zone_id
}
```

### Expected output

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Actual output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_record.nomad-dashboard will be updated in-place
  ~ resource "cloudflare_record" "nomad-dashboard" {
        id          = "bb1fbef215844664286ee15435807f7b"
        name        = "nomad-dashboard"
      ~ value       = "daazku.com" -> "@"
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
cloudflare_record.nomad-dashboard: Modifying... [id=bb1fbef215844664286ee15435807f7b]
cloudflare_record.nomad-dashboard: Modifications complete after 0s [id=bb1fbef215844664286ee15435807f7b]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Steps to reproduce

Use "@" in value field of `cloudflare_record` for a CNAME

### References

When using "@" as the value (or name) of a `cloudflare_record` the resource is detected as changed on subsequent invocation.

![image](https://user-images.githubusercontent.com/2412909/120416173-b8b75f00-c32a-11eb-8b2c-429213fcf752.png)

If `zone_name` is the same as `name` or `value`, `@` should not be considered a change.

**Comment by jacobbednarz** [comment]
I've previously commented at https://github.com/cloudflare/terraform-provider-cloudflare/issues/738#issuecomment-765120218 why we don't do this and so far, I don't have a compelling reason to change that stance. Aliasing really isn't something worth adding at the moment.
