### ISSUE TITLE
New data resource - Origin CA certificate chain

### ISSUE THREAD

**Issue by onematchfox** [cloudflare/terraform-provider-cloudflare#1096]
### Current Terraform and Cloudflare provider version

Terraform v0.14.11
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0

### Description

Add new data resource `cloudflare_origin_ca_certificate_chain`

### Use cases

When applying certificates generated using the resource `cloudflare_origin_ca_certificate` one often needs access to the Cloudflare Origin CA Certificate Chain too. Until now I have been reading this from a link I found via the[ Cloudflare support site](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca#4-required-for-some-add-cloudflare-origin-ca-root-certificates). Unfortunately the link I was using - https://support.cloudflare.com/hc/article_attachments/360037885371/origin_ca_rsa_root.pem - now returns a `404`. The [replacement](https://developers.cloudflare.com/ssl/e2b9968022bf23b071d95229b5678452/origin_ca_rsa_root.pem) does not like programmatic access; trying to access URL this via Terraform/curl returns a `403` with a Cloudflare Captcha page. So, I'm left searching for alternatives... It would be great if this provider handled that complexity for me.

### Potential Terraform configuration

```hcl
data "cloudflare_origin_ca_certificate_chain" "cloudflare" {}
```

**Comment by aceat64** [comment]
I ran into a similar issue due to the URL returning a 404. The error message from Terraform I got just said `Error: HTTP request error. Response code: 404` with no information about the request that caused it. I had to use `TF_LOG=trace` to find the issue, which took quite a while since this particular workspace is very large and takes a long time to run a plan.

Please add this data resource.

**Comment by jacobbednarz** [comment]
Unfortunately, adding a data source isn't going to fix the issues outlined here as the Terraform resource will still need to call out to the endpoints to get this which if you can't do programmatically, won't be any better with Terraform.

I'm getting a 200 for that endpoint however I can see it does have bot management enabled which will be using various approaches to determine if the incoming request is coming from a machine or human.

```
$ curl -so /dev/null https://developers.cloudflare.com/ssl/e2b9968022bf23b071d95229b5678452/origin_ca_rsa_root.pem --write-out '%{http_code}'
200
```

Have you raised with this Cloudflare Support? If not, I can raise a ticket internally to see if we have a preferred endpoint for programmatic access.

**Comment by onematchfox** [comment]
> Unfortunately, adding a data source isn't going to fix the issues outlined here as the Terraform resource will still need to call out to the endpoints to get this which if you can't do programmatically, won't be

I sort of realised this although I hoped that given that this was a `cloudflare` repo that if there was a `data` resource påut in place then maintenance of this resources (and the link from which it pulls the cert) would thus become a "Cloudflare" problem... I.e. in some way an "official" solution rather than me scraping links from support pages. 

> Have you raised with this Cloudflare Support? If not, I can raise a ticket internally to see if we have a preferred endpoint for programmatic access.

I haven't. If you could do that that would be fantastic!

**Comment by jacobbednarz** [comment]
The bot management on this endpoint has been tuned so these paths should now be accessible. We can still look at doing a data source in the future but this will unblock you for now.

**Comment by onematchfox** [comment]
> The bot management on this endpoint has been tuned so these paths should now be accessible. We can still look at doing a data source in the future but this will unblock you for now.

Thank so much for following up! I can confirm that I no longer hit bot detection when trying to use a [`http` data source now](https://registry.terraform.io/providers/hashicorp/http/latest/docs/data-sources/http). But sadly this still isn't working. The endpoint for the (RSA) cert sets the content type returned when accessing the URL to `application/x-x509-ca-cert` whereas the `http` data source

>  can only retrieve data from URLs that respond with text/* or application/json content types, and expects the result to be UTF-8 encoded regardless of the returned content type header

I attempted to explicitly set the `accept` header via the `http` data source but this did not work either so it would seem like there is no content type negotiation in place on the resource at present. 

Not sure on how best to handle this? Options I have come up with include:
1. prioritise adding a custom `data` source as this could handle this _implementation detail_ without any trouble
2. attempt to get Cloudflare to change the content-type/implement content type negotiation on the endpoint
3. try to get `application/x-x509-ca-cert` added as an acceptable content type on the `http` data source (it is just text after all)

As I can't comment on the likelihood of 2 ever happening, I'd love to hear your thoughts @jacobbednarz?

**Comment by jacobbednarz** [comment]
Your second option seems to be trying to solve the wrong thing. Cloudflare is sending the correct content type however the tool you are using isn't compatible; that isn't a good reason to break the correct content type being sent. Option three is also viable if the maintainers are open to it but 🤷‍♂️

I'd recommend taking a pass at implementing this as a datasource if you want this now as that is the most maintainable way forward. There are plenty of past examples to get you going, and you can simplify this even more by adding it to `cloudflare-go` first and have the HTTP client in there handle this for you. IPs are a good example of this:

cloudflare-go: https://github.com/cloudflare/cloudflare-go/blob/e625e78fb682d9f46bfe5ffde938ed19a1eff3e2/ips.go 
terraform: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/data_source_ip_ranges.go
