### ISSUE TITLE
Unable to Create cloudflare_access_service_token

### ISSUE THREAD

**Issue by ahaffar** [cloudflare/terraform-provider-cloudflare#1100]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```sh
Terraform v0.14.4
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.3.1
```

### Affected resource(s)

```hcl
resource "cloudflare_access_service_token" "my_app" {
  zone_id = var.zone_id
  name       = "CI/CD app"
}
```

### Terraform configuration files

```hcl
resource "cloudflare_access_service_token" "my_app" {
  zone_id = var.zone_id
  name       = "CI/CD app"
}
```

### Debug output

error creating access service token: HTTP status 405: POST method with API Tokens is not supported by this API (10000)

  on ../../../../stacks/aws/argo-tunnel/service_token.tf line 1, in resource "cloudflare_access_service_token" "_":
   1: resource "cloudflare_access_service_token" "_"

### Expected output

service token to be created 

### Actual output

error creating access service token: HTTP status 405: POST method with API Tokens is not supported by this API (10000)

  on ../../../../stacks/aws/argo-tunnel/service_token.tf line 1, in resource "cloudflare_access_service_token" "_":
   1: resource "cloudflare_access_service_token" "_"

### Steps to reproduce

1 - create a new resource
2- terraform plan run successfullly
3- terraform plan - have error

**Comment by jacobbednarz** [comment]
The error message here is pretty self explanatory 

> POST method with API Tokens is not supported by this API

You'll need to use your API key instead.

**Comment by ahaffar** [comment]
i was using api_token to authenticate the provider but I found that my API Token was not supporting creating access tokens and access groups, once adding the required permissions.
it worked
