### ISSUE TITLE
Resource cloudflare_access_mutual_tls_certificate doesn't work with api_token authentication

### ISSUE THREAD

**Issue by latyyfa** [cloudflare/terraform-provider-cloudflare#1110]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

* Terraform version : 0.15.3
* Cloudflare provider version : 2.21.0

### Affected resource(s)

* cloudflare_access_mutual_tls_certificate

### Terraform configuration files

```hcl
provider "cloudflare" {
api_token = var.api_token
account_id = var.account_id
}

resource "cloudflare_access_mutual_tls_certificate" "ca_certificate" {
zone_id = "zone_id"
name = "Root CA certificate"
certificate = "certificate content"
associated_hostnames = ["some.hostname.com"]
}
```

### Expected output

Resource created successfully

### Actual output

```
│ Error: error creating Access Mutual TLS Certificate for zone "zone_id": HTTP status 405: POST method not allowed for the api_token authentication scheme (10000)
```

### Steps to reproduce

1. Use the code I shared above
2. Run Terraform plan then Terraform apply

### Additional factoids

The api_token used for the creation has the permission `Access: Mutual TLS Certificates:Edit` along with other permissions.

The workaround is to use the legacy `Email + API Key` for authentication, but we want to use the API token.

**Comment by jacobbednarz** [comment]
I'm afraid this isn't something we can fix in the Terraform provider as this is something we need the service team to adjust. The provider only wraps the public API with lifecycle improvements, we don't manage any of this internally. Have you raised a Cloudflare Support ticket for this that I can forward to the right place?

**Comment by latyyfa** [comment]
@jacobbednarz Yes I have raised a Cloudflare Support ticket for this, and they recommended creating an issue in this repo.

**Comment by jacobbednarz** [comment]
What is the ticket ID?

**Comment by latyyfa** [comment]
[2189409](https://support.cloudflare.com/hc/en-us/requests/2189409)

**Comment by jacobbednarz** [comment]
The Access folks have a ticket in their backlog to address this one. In
the meantime, you'll need to use API key + email for authentication.
