### ISSUE TITLE
Cannot set Max-Age (HSTS)

### ISSUE THREAD

**Issue by re-thc** [cloudflare/terraform-provider-cloudflare#1111]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

CF - 2.21.0
Terraform - 0.14.4

### Affected resource(s)

security header (HSTS)

### Terraform configuration files

```hcl
resource "cloudflare_zone_settings_override" "test" {
    zone_id = var.cloudflare_zone_id
    settings {
        security_header {
            enabled = true
            preload = true
            max_age = 63072000
            include_subdomains = true
            nosniff = true
        }
    }
}
```

### Expected output

Status: On
Max-Age: 12 months
Include subdomains: On
Preload: On

### Actual output

Status: On
Max-Age: %{time}
Include subdomains: On
Preload: On

### Steps to reproduce

Use terraform with cloudflare provider

**Comment by jacobbednarz** [comment]
Is the issue here that you can't set any arbitrary number for the max age? 63072000 isn't an available option.

**Comment by re-thc** [comment]
I tried quite a few numbers and it didn't work. What's an available option?

**Comment by jacobbednarz** [comment]
I'm sorry but what didn't work? 

The available values can either be seen in the UI or the API documentation at api.cloudflare.com.

**Comment by re-thc** [comment]
Terraform results in `Max-Age: %{time}` when applying. No errors. If the number isn't available terraform should fail? 

I went to api.cloudflare.com and can't find where it says what the range is. It gives an example: `86400` to enter and I try that number and also results in `%{time}`.

**Comment by jacobbednarz** [comment]
Can you please provide the TF_LOG=DEBUG output untruncated? I'm unsure how you're not getting a value or guidance as to the error on this.

**Comment by jacobbednarz** [comment]
Apologies, I have just realised what you meant. The _UI_ shows that output, not Terraform. I'm afraid the best course of action is to open a Cloudflare Support ticket, and it will be routed to the correct team that handles it. Once you created that drop the ticket ID here and I can make sure the team sees it.

Ignore the UI for now and just go off the Terraform/API response as that is working.
