### ISSUE TITLE
Network Error Log supports in cloudflare_logpush_job

### ISSUE THREAD

**Issue by bootswithdefer** [cloudflare/terraform-provider-cloudflare#1112]
### Current Terraform and Cloudflare provider version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0

### Description

Network Error Logging support for logpush jobs.

https://blog.cloudflare.com/logpush-ui-update/

### Use cases

Configuring logpush jobs for the network error logging type.

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_job" "job" {
...
  dataset          = "network_error_log_events"
...
}
```

**Comment by jacobbednarz** [comment]
Doesn't look like this has landed in the public API for support (https://api.cloudflare.com/#logpush-jobs-create-logpush-job) yet so we'll be pending until that is fixed.
