### ISSUE TITLE
`priority` on `cloudflare_record` shows as modified after `terraform import`

### ISSUE THREAD

**Issue by kpcyrd** [cloudflare/terraform-provider-cloudflare#1114]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

v2.22.0

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
# I don't  think this really applies to the bug but it's a mandatory field :)

resource "cloudflare_record" "dns_record" {
  for_each = var.dns_records
  zone_id  = cloudflare_zone.cf_zone.id
  name     = each.value.name
  value    = each.value.dns_value
  type     = each.value.type
  ttl      = each.value.ttl
  priority = each.value.priority
  proxied  = each.value.proxied
}
```

### Expected output

My terraform defines the priority of an MX record as 10, on cloudflare it's already set to `10`, so after running `terraform import ...` there shouldn't be any changes when running `terraform plan`.

### Actual output

`terraform plan` shows that it's going to update the priority of the record to `10`. Running `terraform apply` doesn't seem to actually change anything (it just re-sets the value from 10 to 10 I think), `terraform plan` doesn't show any changes afterwards.

### Steps to reproduce

1. Create an MX record with the web interface with a priority set to 10
2. Define this record in your terraform as well
3. Run `terraform import ...` to import the existing record in your state file
4. Run `terraform plan`

**Comment by jacobbednarz** [comment]
Thanks for raising this one @kpcyrd and I especially appreciate you filling out the required fields even though you thought they were unnecessary 😄 They help maintainers progress issues so thanks!

I took a look at this and found two issues both of which are addressed in #1116. If you'd like, pull the branch locally, [build the branch locally](https://github.com/cloudflare/terraform-provider-cloudflare#building-the-provider) and confirm the proposed changes fix your issue.
