### ISSUE TITLE
cloudflare_custom_hostname not returning ownership_verification.type /value /name

### ISSUE THREAD

**Issue by mihaiturcu** [cloudflare/terraform-provider-cloudflare#1115]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.0
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.0.1. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

cloudflare_custom_hostname

### Terraform configuration files

```hcl
resource "cloudflare_custom_hostname" "testoutput" {
  custom_origin_server = "something.test.com"
  hostname = "random.test.com"
  zone_id = var.zone_id

  ssl {
    settings {
      min_tls_version = "1.2"
    }
    certificate_authority = "digicert"
    method = "txt"
    type = "dv"
    wildcard = false
  }
}

output "ownership_verification_type" {
    value = cloudflare_custom_hostname.testoutput.ownership_verification.type
}

output "ownership_verification_value" {
    value = cloudflare_custom_hostname.testoutput.ownership_verification.value
}

output "ownership_verification_name" {
    value = cloudflare_custom_hostname.testoutput.ownership_verification.name
}
```

### Debug output

-

### Panic output

-

### Expected output

ownership_verification_name = "something_here"
ownership_verification_type = "txt"
ownership_verification_value = "somethingelse_here"

### Actual output

ownership_verification_name = ""
ownership_verification_type = ""
ownership_verification_value = ""

### Steps to reproduce

Use cloudflare_custom_hostname in your .tf and use output to print ownership_verification.(type/name/value)

### Additional factoids

-

### References

-

**Comment by jacobbednarz** [comment]
This isn't a bug but a new feature request. You also don't need to output the type as you already have that exported and set on your resource. The rest seem reasonable though.

**Comment by jacobbednarz** [comment]
looks like this has shipped in a subsequent release; https://cs.github.com/cloudflare/terraform-provider-cloudflare/blob/353c535ae25ffb6b4cd4d3b6f7ea48bf98b274b8/cloudflare/schema_cloudflare_custom_hostname.go#L123

please open a new issue if this isn't returning what you expect here.
