### ISSUE TITLE
"cannot be set as it is read only"

### ISSUE THREAD

**Issue by rightaway** [cloudflare/terraform-provider-cloudflare#1117]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0

### Affected resource(s)

cloudflare_zone_settings_override

### Terraform configuration files

```hcl
resource "cloudflare_zone_settings_override" "test" {
  zone_id = "${cloudflare_zone.test.id}"
  settings {
    # settings here
  }
}
```

### Expected output

Should update the provided settings.

### Actual output

Different errors each time. Such as

```
Error: invalid zone setting "prefetch_preload" (value: ) found - cannot be set as it is read only`
```
or
```
Error: invalid zone setting "sort_query_string_for_cache" (value: ) found - cannot be set as it is read only
```

### Steps to reproduce

Enter some settings.
If you have the free plan you get an error saying some settings are read only even though you didn't specify these settings anywhere.

**Comment by rightaway** [comment]
Also happens with latest 2.22.0.

**Comment by rightaway** [comment]
The issue happens when you use `terraform import` to import existing resource but not when you create it from scratch.

**Comment by jacobbednarz** [comment]
Please provide the settings you are attempting to update in the reproduction case. As the resource is intended to *override*, not all settings should be provided. 

This resource doesn't support import by design so I'm unsure how you're running an import command against this resource.

**Comment by rightaway** [comment]
It happens if you give even a single setting. Any setting you give has the same problem.

I didn't import this resource but I imported `cloudflare_zone` resource.

**Comment by jacobbednarz** [comment]
Please provide an example of it not working with a single setting that your zone is entitled to. Free zones do not have all settings available.

**Comment by jacobbednarz** [comment]
for anyone else hitting this and finding this issue, please see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#plan-dependent-settings

**Comment by davidvpe** [comment]
This issue is also happening to me

### Terraform and Cloudflare provider version
Terraform v1.1
on linux_amd64

provider registry.terraform.io/cloudflare/cloudflare v3.10.0

### Affected resource(s)
cloudflare_zone_settings_override

### Terraform configuration files

```hcl
data "cloudflare_zone" "zone" {
  name = "example.org"
}

resource "cloudflare_zone_settings_override" "settings" {
  zone_id  = data.cloudflare_zone.zone.id

  settings {
    ssl                                      = "full"
    always_use_https            = "on"
  }
}
```

### Debug output
No response

### Panic output
No response

### Expected output
Should update the provided settings.

### Actual output
Different errors each time. Such as

Error: invalid zone setting "prefetch_preload" (value: ) found - cannot be set as it is read only`
or

Error: invalid zone setting "sort_query_string_for_cache" (value: ) found - cannot be set as it is read only
