### ISSUE TITLE
workers.api.error.script_not_found

### ISSUE THREAD

**Issue by innovate-invent** [cloudflare/terraform-provider-cloudflare#1120]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.23.0
+ provider registry.terraform.io/hashicorp/aws v3.47.0
+ provider registry.terraform.io/louy/uptimerobot v0.5.1
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.42.0

### Affected resource(s)

- cloudflare_worker_cron_trigger

### Terraform configuration files

```hcl
resource "cloudflare_worker_cron_trigger" "logger" {
  script_name = cloudflare_worker_script.logger.name
  schedules   = [
    "* * * * *",      # every 1 minutes
  ]
}
```

### Expected output

Redeploy worker without error

### Actual output

╷
│ Error: failed to read Worker Cron Trigger: HTTP status 404: workers.api.error.script_not_found (10007)
│ 
│   with cloudflare_worker_cron_trigger.logger,
│   on cloudflare.tf line 109, in resource "cloudflare_worker_cron_trigger" "logger":
│  109: resource "cloudflare_worker_cron_trigger" "logger" {
│ 
╵

### Steps to reproduce

1.terraform apply # Deploy a worker with cron
2. Manually delete worker
3. terraform apply

**Comment by jacobbednarz** [comment]
This is working for me and the integration tests - https://github.com/cloudflare/terraform-provider-cloudflare/blob/f52ccc18d74b2dbabcb8f435e04247dae8f00d19/cloudflare/resource_cloudflare_worker_cron_trigger_test.go#L10-L29

Have you checked the resource name you're using and the account/zone identifier being used? Per the issue template, please provide the `TF_LOG=DEBUG` output if you'd like further assistance.

**Comment by jacobbednarz** [comment]
Actually, scratch that. I managed to see the missing link here. If you delete via the dashboard it wipes out the connected resources whereas the API (and Terraform) allows deleting one without the relationships and doesn't have the same issue. This means to handle changes outside of Terraform we need to check for *all* resources that could be the source holding the other resources together (here, scripts that have triggers, envirnonment variables, etc)
