### ISSUE TITLE
Use Checksum or Shorter Mechanism for Worker Output

### ISSUE THREAD

**Issue by jsievenpiper** [cloudflare/terraform-provider-cloudflare#1126]
### Current Terraform and Cloudflare provider version

Terraform `0.13.3`
Cloudflare Provider `2.11.0`

### Description

It would be great if output from `terraform plan|apply` could use some mechanism other than the worker source / web assembly base64 when describing changes that would occur when a worker will change. This would make output significantly less verbose, and I'd argue, possibly _more_ valuable, as it doesn't drown out the output with 100s of kb of text.

Currently, we've identified:
- The output from TF's perspective will show a worker script as entirely changed (reasonable), but often a small section of that actual code will be the only change. This has likely been caught in a typical code review prior to deploy anyway, so the diff at the operator level is (possibly) much less valuable.
- wasm output is written out as base64, and like a JS script (possibly even more so), will be hundreds of kb of it.

The proposal would be to use something like a file checksum or similar -- just enough to show that the content did indeed change, but not try to demonstrate those changes themselves.

### Use cases

In a plan with even a single zone, our TF output on our worker easily drowns the rest of the output, and finding the other changes can be difficult to spot. At 20+ zones, it becomes even more challenging to dive between base64 blobs to find other applied/planned changes.

### Potential Terraform configuration

If there is value in keeping the old behavior, we'd need to implement a switch of some sort. I could see it being provider-level as an enum for future expandability:

```hcl
provider "cloudflare" {
  # could make it abstract:
  worker_script_output = "verbose" # or "simple"

  # or could make it more fine-grained:
  webassembly_binding_output = "sha256" # "base64", "md5"... etc
}
...
```

**Comment by jacobbednarz** [comment]
Thanks for raising this! Some comments below.

> The output from TF's perspective will show a worker script as entirely changed (reasonable), but often a small section of that actual code will be the only change. This has likely been caught in a typical code review prior to deploy anyway, so the diff at the operator level is (possibly) much less valuable.

Terraform 0.14.x improves this situation quite a bit as the concise diffs now only show individual changes.

```
  # cloudflare_worker_script.my_script will be updated in-place
  ~ resource "cloudflare_worker_script" "my_script" {
      ~ content = <<-EOT
            const html = `<!DOCTYPE html><body>  <h1>Hello World!</h1>  <p>This markup was generated by a Cloudflare Worker.</p></body>`

            async function handleRequest(request) {
              return new Response(html, {
                headers: { "content-type": "text/html;charset=UTF-8", },
              })
            }

          + // example single line change
            addEventListener("fetch", event => {
              return event.respondWith(handleRequest(event.request))
            })
        EOT
        id      = "script_1"
        name    = "script_1"
    }
```

While the output is still there in it's entirety, it is specific about the changes.

> If there is value in keeping the old behavior, we'd need to implement a switch of some sort.

I'm afraid this isn't possible for `customizeDiff` calls. The function only has access to the current and proposed values and no other schema options so a toggle wouldn't work.

As is, my recommendation would be to update to a newer version of Terraform and see if that helps you enough to lower this to a minor pain. Longer term I've added some notes to an upstream Terraform issue (https://github.com/hashicorp/terraform-plugin-sdk/issues/704#issuecomment-875122458) as I think that is the more appropriate place to solve this, not in the provider itself. Feel free to let me know if you have any further thoughts!

**Comment by jsievenpiper** [comment]
@jacobbednarz thanks for getting back to me so quickly!

I've forwarded along your recommendation to the rest of the team, but I'm not sure it would really reduce the pain (if I'm understanding you correctly). Our workers range from several hundred to thousands of lines of code (this one is somewhat manageable, though less than ideal) -- the wasm uploads are several hundred kb of base64-encoded output.

For further context, we're also managing this via Atlantis, so each plan can be upwards of 50 email notifications, output split across several github comments, etc. (So any downstream integration exacerbates the pain.) 

If there's perceived value in the JS output (since it's arguably human-readable), can the argument be made that the base64 output for wasm isn't valuable? I will admit I have no inner-Terraform experience so I don't have any insight into the ability to customize that. 😅

**Comment by jacobbednarz** [comment]
I'm afraid there isn't a whole heap we can do here as it stands. Terraform has it's own mechanisms for displaying the diffs. We can [customize the operation to perform the compare](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff?utm_source=godoc) however we can't modify the output itself.

If you're using plaintext output, the upgrade + proposed linked issue will help however binary/base64 encoded output we just get the total change (even if we were to decode the base64 value).

Something you might want to explore is instead using [Wrangler](https://github.com/cloudflare/wrangler) for your worker scripts. Right now it doesn't have a `diff` command however it should theoretically be possible to add and have it output a traditional diff comparison which would alleviate the amount of output shown.
