### ISSUE TITLE
`cloudflare_access_application` resource lacks `logo_url` field 

### ISSUE THREAD

**Issue by danopia** [cloudflare/terraform-provider-cloudflare#1133]
### Current Terraform and Cloudflare provider version

```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.24.0
```

### Description

I'd like to attach a logo to Access applications from the Terraform resource. Logos are accepted by Cloudflare as an arbitrary public URL.

Given that updating the application in the Team Dash recreates all the access policies underneath, using the UI to attach a logo later breaks the TF State and requires a `state rm` / `import` sequence.

### Use cases

Providing a user-facing logo for an application that is created via Terraform.

### Potential Terraform configuration

A new `logo_url` field probably.

```hcl
resource "cloudflare_access_application" "my_app" {
  zone_id  = cloudflare_zone.my_zone.id
  name     = "My App"
  domain   = "my-app.${cloudflare_zone.my_zone.zone}"
  type     = "self_hosted"
  logo_url = "https://some-project-site.github.io/logo.png"
}
```

### References

I didn't see any previous comments about logo url.

I don't see `logo_url` referenced [in the API docs](https://api.cloudflare.com/#access-applications-create-access-application) however I do see the field returned in the list applications endpoint so I have to assume the modification endpoints accept the field already.

**Comment by jacobbednarz** [comment]
if this isn't yet documented publicly, we don't generally add support as it's not considered stable yet. you're welcome to open a support ticket as it may have just been missed during rollout.

once it's publicly documented, we can add it to cloudflare-go and here.

**Comment by danie1sullivan** [comment]
The parameter is still absent in provider version `3.1.0`.

If you create an Access application and attach a policy with Terraform, then change the Logo URL in the web console, Terraform loses the _policy_ and tries to recreate it. This fails because a policy with the same precedence already exists.

**Comment by danopia** [comment]
I have also seen that symptom as described in the original text. The webapp seems to do a delete and recreate of the rules any time an application is changed in any point&click operation.

> Given that updating the application in the Team Dash recreates all the access policies underneath, using the UI to attach a logo later breaks the TF State and requires a `state rm` / `import` sequence.

However I don't have established contact with Cloudflare support so I haven't asked them to update the docs
