### ISSUE TITLE
cannot import `cloudflare_argo` settings

### ISSUE THREAD

**Issue by cofyc** [cloudflare/terraform-provider-cloudflare#1135]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.24.0

### Affected resource(s)

cloudflare_argo

### Terraform configuration files

```hcl
resource "cloudflare_argo" "taptap_io" {
  id             = cloudflare_zone.taptap_io.id
  tiered_caching = "on"
  smart_routing  = "on"
}
```

### Expected output

Show my settings on cloudflare.com

resource "cloudflare_argo" "taptap_io" {
    id      = "26986eec87d322387989eec91cfcb780"
    zone_id = "zone-id-string"
    tiered_caching = "on"
    smart_routing = "on"
}

### Actual output

resource "cloudflare_argo" "taptap_io" {
    id      = "26986eec87d322387989eec91cfcb780"
    zone_id = "zone-id-string"
}

### Steps to reproduce

1. terraform import cloudflare_argo.example_com
2. terraform state show cloudflare_argo.example_com

**Comment by jacobbednarz** [comment]
i've had a look at this and there are two parts to the issue you're facing.

1. we weren't calling `Read` on the `Import` so it was a straight passthrough; and
2. your `terraform import` command is missing the zone ID per the documentaton (https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/argo#import)

i've pushed up a fix for the first one but you'll need to address the second part in your implementation.

**Comment by jacobbednarz** [comment]
side note: `id` isn't a modifiable field; you need to use `zone_id`

**Comment by cofyc** [comment]
@jacobbednarz Thanks! Will the new version 3.5.0 be released recently?

**Comment by jacobbednarz** [comment]
Releases are performed roughly fortnightly - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/release-process.md

If you want to use the provider before then you build an unreleased version and use that - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/using-non-released-versions.md
