### ISSUE TITLE
`cloudflare_rate_limit` resource always shows changes to the `bypass_url_patterns` attribute

### ISSUE THREAD

**Issue by robingoth** [cloudflare/terraform-provider-cloudflare#1141]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

The `bypass_url_patterns` attribute of the `cloudflare_rate_limit` resource is optional. If it's not defined in a rule, it will always show changes in the state:
```
# cloudflare_rate_limit.ratelimit_rule["xxx"] has been changed
  ~ resource "cloudflare_rate_limit" "ratelimit_rule" {
      + bypass_url_patterns = []
        id                  = "XXX"
```

Expected behavior – no changes are shown in the `terraform plan` output.

### Affected resource(s)

cloudflare_rate_limit

### Terraform configuration files

```hcl
resource "cloudflare_rate_limit" "ratelimit_rule" {
  for_each    = var.ratelimit_rules
  zone_id     = cloudflare_zone.cf_zone.id
  threshold   = each.value.threshold
  period      = each.value.period
  disabled    = each.value.disabled
  description = each.value.description
  match {
    request {
      url_pattern = each.value.url_pattern
      schemes     = each.value.schemes
      methods     = each.value.methods
    }
  }
  action {
    mode    = each.value.mode
    timeout = each.value.timeout
  }
  depends_on = [
    cloudflare_zone.cf_zone
  ]
}
```

### Debug output

Please let me know if you really need this to investigate the bug. It's difficult to clean up the debug output from all sensitive data.

### Expected output

No changes made to the state

### Actual output

```
# cloudflare_rate_limit.ratelimit_rule["xxx"] has been changed
  ~ resource "cloudflare_rate_limit" "ratelimit_rule" {
      + bypass_url_patterns = []
        id                  = "XXX"
```

### Steps to reproduce

1. Create a rate limit rule
2. Run `terraform apply` twice

**Comment by jacobbednarz** [comment]
closing this one out as the recommended approach is to use the newer rate limiting product as the older one will be sunset in the future in favour of it.
