### ISSUE TITLE
cloudflare_custom_hostname ssl method not changing

### ISSUE THREAD

**Issue by mihaiturcu** [cloudflare/terraform-provider-cloudflare#1144]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Hi,

I'm apparently having issues when trying to change the validation method used against a custom hostname.
When I change the method from http into TXT, the change does not reflect inside the Cloudflare dashboard and the custom hostname remains with validation method = http.

### Affected resource(s)

cloudflare_custom_hostname

### Terraform configuration files

```hcl
resource "cloudflare_custom_hostname" "example_hostname" {
  zone_id  = "d41d8cd98f00b204e9800998ecf8427e"
  hostname = "hostname.example.com"
  ssl {
    method = "http"
  }
}

then switch to

resource "cloudflare_custom_hostname" "example_hostname" {
  zone_id  = "d41d8cd98f00b204e9800998ecf8427e"
  hostname = "hostname.example.com"
  ssl {
    method = "txt"
  }
}
```

### Debug output

Terraform output, not debug:

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # cloudflare_custom_hostname.blabla will be updated in-place
~ resource "cloudflare_custom_hostname" "blabla" {
        id                          = "cb23f11f-beb6-4a1f-a674-ebd8f96ff2cd"
        # (4 unchanged attributes hidden)

      ~ ssl {
          ~ method   = "http" -> "txt"
            # (2 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Expected output

validation method should be set to TXT

### Actual output

txt validation visible in the dashboard

### Steps to reproduce

1. Provision custom hostname with validation http
2. Change validation method to txt

**Comment by jacobbednarz** [comment]
from my testing, this is already working the same as the UI in 3.4.0. can you please confirm you've tried with the latest version and still experiencing this?

**Comment by jacobbednarz** [comment]
if you're still having issues, please provide the `TF_LOG=DEBUG` output with any sensitive credentials redacted.
