### ISSUE TITLE
cloudflare_record Terraform resource

### ISSUE THREAD

**Issue by isdinAghmir** [cloudflare/terraform-provider-cloudflare#1148]
### Current Terraform and Cloudflare provider version

 2.24.0 

### Description

change the type of 'value' from string to list of string.

### Use cases

Creating one record with multiple ips

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
Not all records support this functionality so for now, I'm going to pass on implementing. If we get more requests in the future, we can revisit.
