### ISSUE TITLE
Please release a new provider version as-is

### ISSUE THREAD

**Issue by kamadorueda** [cloudflare/terraform-provider-cloudflare#1149]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

in version: 2.24.0 (latest)

### Affected resource(s)

- cloudflare_certificate_pack

### Terraform configuration files

```hcl
resource "cloudflare_certificate_pack" "main" {
  zone_id               = cloudflare_zone.fluidattacks_com.id
  type                  = "advanced"
  validation_method     = "txt"
  validity_days         = 14
  certificate_authority = "digicert"
  cloudflare_branding   = false

  hosts = [
    cloudflare_zone.fluidattacks_com.zone,
    "*.${cloudflare_zone.fluidattacks_com.zone}",
    "*.app.${cloudflare_zone.fluidattacks_com.zone}",
    "*.integrates.${cloudflare_zone.fluidattacks_com.zone}",
    "*.front.production.${cloudflare_zone.fluidattacks_com.zone}",
    "*.front.development.${cloudflare_zone.fluidattacks_com.zone}",
    "*.eph.${cloudflare_zone.fluidattacks_com.zone}",
  ]

  lifecycle {
    create_before_destroy = true
  }
}
```

### Debug output

![image](https://user-images.githubusercontent.com/47480384/128104146-196e47d4-e6fe-4279-b4e7-d2ae2a8f10ef.png)

![image](https://user-images.githubusercontent.com/47480384/128103811-f3220b7d-68e4-4ff3-90d7-21afbd544741.png)

### Expected output

it works, it used to work before cloudflare API changed

### Actual output

.

### Steps to reproduce

.

### References

The problem happens because cloudflare API changed a type: https://github.com/cloudflare/cloudflare-go/commit/b15947a8a9f8d4d0b0928cc299dd87be62b1c691

Non-latest versions of cloudflare-go are not able to unmarshall the type for the field correctly.

Cloudflare-go was updated at terraform-provider-cloudflare already.
By releasing a new provider version to the terraform registry the issue will be solved

**Comment by kamadorueda** [comment]
The issue is already solved at the last commit of https://github.com/cloudflare/terraform-provider-cloudflare
but users are not able to install such version because it has not been released to the terraform registry https://registry.terraform.io/providers/cloudflare/cloudflare/latest

**Comment by jacobbednarz** [comment]
Thanks but we don't need bug reports for this. We largely work on a monthly release cadence in order to allow downstream consumers time to rectify any issues before releasing another version on top of them.

For this particular issue, there is a release landing very soon. If you need the updated provider immediately, there are instructions in the README on [building your own version of the provider to unblock](https://github.com/cloudflare/terraform-provider-cloudflare#building-the-provider) any issues you're having.

**Comment by kamadorueda** [comment]
Thank you very much, 2.25.0 solved my problem
