### ISSUE TITLE
Unable to provide multiple common_name entries for cloudflare_access_policy

### ISSUE THREAD

**Issue by tomcart90** [cloudflare/terraform-provider-cloudflare#1156]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.2
on windows_amd64

Running with v2.25.0 of the cloudflare provider.

### Affected resource(s)

cloudflare_access_policy

### Terraform configuration files

```hcl
resource cloudflare_access_policy mtls_allow {
  zone_id        = var.zone_id
  application_id = cloudflare_access_application.app.id
  name           = "mtls-allow"
  precedence     = 1
  decision       = "non_identity"

  require {
    # Require a valid certificate.
    certificate = true
  }

  include {
    common_name = "Foo Bar, Bar Foo"
  }
}
```

### Debug output

Happy to provide this if need be though I'm not sure it's necessary for my issue.

### Expected output

Providing a string of common names separated by commas would result in multiple common name entries in the cloudflare dashboard UI.

### Actual output

When entering common names via the Cloudflare dashboard the UI allows you to enter multiple common name entries by separating them by commas. Via the terraform provider the common_name variable requires a string, entering a comma separated list of entries in this way simply produces a single entry when viewing the policy in the UI.

### Steps to reproduce

Terraform apply my example above and view the policy in the Cloudflare dashboard. You'll see that it adds a single common name rather than splitting the entries into multiple common names.

### Additional factoids

I also tried making the `include` block dynamic and creating multiple entries that way, though that just ended up creating a single entry.

**Comment by jacobbednarz** [comment]
As it stands, the service only accepts a single common name to match against certificates against. If this is something useful, I'd recommend opening a support ticket (or chat to your account team) about filing a feature request. Once the service supports it, we can look at implementing it here.
