### ISSUE TITLE
Add support SKIP rules and rulesets on WAF (ruleset)

### ISSUE THREAD

**Issue by vences** [cloudflare/terraform-provider-cloudflare#1177]
### Current Terraform and Cloudflare provider version

```
➜ terraform -v
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.26.1
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Description

Not all skip functionalities are supported yet, like `rules` and `rulesets` in `action_parameters` for a rules with an action of skip.

#### Skip

For `rules` and `rulesets` the structure described in the api doc doesn't seem to be implemented in the `cloudflare-go` [here](https://github.com/cloudflare/cloudflare-go/blob/master/rulesets.go#L170) neither in the `terraform-provider-cloudflare`.

### Use cases

The use case is a configuration of payload logging/skip directly via a terraform configuration as the same as the UI/API.

### Potential Terraform configuration

```hcl
# Zone-level WAF Managed Ruleset
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = var.cloudflare_zone_id
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "zone"
  phase       = "http_request_firewall_managed"

  rules {
    action = "skip"
    action_parameters {
        rulesets = ["efb7b8c949ac4650a09736fc376e9aee"]
    }
    expression = "(cf.zone.name eq \"domain.xyz\" and http.request.uri.query contains \"skip=rulesets\")"
    description = "skip Cloudflare Manage ruleset"
    enabled = true 
  }

  rules {
    action = "skip"
    action_parameters {
       # efb7b8c949ac4650a09736fc376e9aee is the ruleset ID of the Cloudflare Managed rules
        rules = {
          "efb7b8c949ac4650a09736fc376e9aee" = [
                        "5de7edfa648c4d6891dc3e7f84534ffa",
                        "e3a567afc347477d9702d9047e97d760"
                    ]
        }
    }
    expression = "(cf.zone.name eq \"domain.xyz\" and http.request.uri.query contains \"skip=rules\")"
    description = "skip Wordpress rule and sQLi rule"
    enabled = true 
  }

  rules {
    action = "execute"
    action_parameters {
        id = "efb7b8c949ac4650a09736fc376e9aee"
        version = "latest"
        overrides {
          rules {
                  id = "5de7edfa648c4d6891dc3e7f84534ffa"
                  action = "block"
                  enabled = true
          }
          rules {
            id = "75a0060762034a6cb663fd51a02344cb"
            action = "log"
            enabled = true
          }
          categories {
            category = "wordpress"
            action = "js_challenge"
            enabled = true
          }
        }
    }
    expression = "true"
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled = true
  }
}
```

### References

- Skip `rules` documentation [here](https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-api#skip-one-or-more-rules-of-waf-managed-rulesets)
- Skip `rulesets` documentation [here](https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-api#skip-one-or-more-waf-managed-rulesets)

**Comment by jacobbednarz** [comment]
Thanks for this @vences. Looking through the internal API schema, I'm going to have to take this up with the service team as the current field definition (`rules.action_parameter.rulesets`) is using multiple simple and complex types which isn't ideal from a typed language perspective _or_ Terraform. For this to work sensibly, I think we're going to have to change the internal API representation otherwise both clients are going to need to contain shims which I don't want to do with such a foundational API like Rulesets.

**Comment by jacobbednarz** [comment]
Confirmed this was a misunderstanding caused by the struct in `cloudflare-go` being incorrect. Once that is fixed, we should be good to land this functionality.
