### ISSUE TITLE
Please correct describe for parameter

### ISSUE THREAD

**Issue by dburianov** [cloudflare/terraform-provider-cloudflare#1195]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

any version

### Affected resource(s)

zone_settings_override

### Terraform configuration files

```hcl
resource "cloudflare_zone_settings_override" "settings" {
  zone_id = var.cloudflare_zone_id
  settings {
    browser_cache_ttl        = 0
  }
}
```

### Debug output

no output

### Expected output

correct describe in documentation

### Actual output

correct describe in documentation

### Steps to reproduce

correct describe in documentation

### Additional factoids

next option: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#browser_cache_ttl
have only in documentation:
**(default: 14400)**
Please add describe like: 
**The Time To Live for the browser cache. 0 means 'Respect Existing Headers'**
this describe similar to https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule#browser_cache_ttl
and it work correct for zone_settings_override#browser_cache_ttl

**Comment by jacobbednarz** [comment]
Please see the documentation on api.cloudflare.com for additional field information. The Terraform documentation is generally a subset pointing at other sources of information.

**Comment by jacobbednarz** [comment]
This also isn't a bug; in future documentation improvements should either be a PR or enhancement issue.

**Comment by dburianov** [comment]
Hello @jacobbednarz 
Thank you for your answer, howerver I do not found by this link: https://api.cloudflare.com/#zone-settings-get-browser-cache-ttl-setting
and by this link: https://developers.cloudflare.com/cache/about/edge-browser-cache-ttl#browser-cache-ttl
and by this link: https://developers.cloudflare.com/cache/how-to/set-browser-ttl
information about: **0 means 'Respect Existing Headers'**
