### ISSUE TITLE
Export Custom Hostname Certificate Validation TXT name/value and retain records in state

### ISSUE THREAD

**Issue by jjtroberts** [cloudflare/terraform-provider-cloudflare#1197]
### Current Terraform and Cloudflare provider version

Terraform v1.0.0
on darwin_amd64

cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.26.1"
    }

### Description

The current provider exports the ownership_verification.value but not the Certificate validation TXT name or Certificate validation TXT value.

It also appears to be the case that once the ownership record is validated, it is no longer available as part of the state which means I can no longer refer to the value as expected using `cloudflare_custom_hostname.foo. ownership_verification.value`
```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.foo.cloudflare_custom_hostname.foo_org has been changed
  ~ resource "cloudflare_custom_hostname" "foo_org" {
        id                          = "xxxxxxxxx"
      ~ ownership_verification      = {
          ~ "name"  = "_cf-custom-hostname.foo.org" -> ""
          ~ "type"  = "txt" -> ""
          ~ "value" = "xxxxxxxxx" -> ""
        }
      ~ ownership_verification_http = {
          ~ "http_body" = "xxxxxxxxx" -> ""
          ~ "http_url"  = "http://foo.org/.well-known/cf-custom-hostname-challenge/xxxxxxxxx" -> ""
```

### Use cases

For clients who manage DNS elsewhere, I need to be able to create their custom hostname at Cloudflare, retrieve the exported DCV records for both domain ownership *and* certificate validation, and then use those values in another module to fully automate DNS record management.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
does #1424 solve for you use case here?

**Comment by jjtroberts** [comment]
@jacobbednarz I no longer work at the company where I encountered this issue. I've reached out to two of my former team members asking them to respond.
