### ISSUE TITLE
Cloudflare Worker Usage Model

### ISSUE THREAD

**Issue by twmartin** [cloudflare/terraform-provider-cloudflare#1205]
### Current Terraform and Cloudflare provider version

2.26.1

### Description

Specify the paid plan usage model (bundled vs unbound) for a Cloudflare Worker via Terraform.

### Use cases

Specify the usage model for a paid plan Cloudflare Worker via Terraform in cases where the account default usage model is not desired

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "worker" {
  name        = "worker"
  content     = file("worker.js")
  usage_model = "bundled"
}
```

### References

https://developers.cloudflare.com/workers/platform/pricing

**Comment by jacobbednarz** [comment]
API documentation: https://api.cloudflare.com/#worker-account-settings-create-worker-account-settings

Requires cloudflare-go support first.

**Comment by JubbaSmail** [comment]
any update on `usage_model` ?

**Comment by troymjones** [comment]
This has been added to cloudflare-go. Can this be added to the terraform now?

**Comment by mattfysh** [comment]
The number of things added to cloudflare-go that have yet to reach the terraform provider is astounding.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
