### ISSUE TITLE
`cloudflare_ruleset ` - HTTP Rate Limit Error

### ISSUE THREAD

**Issue by grodriguezl** [cloudflare/terraform-provider-cloudflare#1210]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

provider = 2.27.0
provider = 3.0.0

### Affected resource(s)

- cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "rate_limiting_example" {
  zone_id     = var.zone_id
  name        = "restrict API requests count"
  description = "apply HTTP rate limiting for a route"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    action = "block"
    ratelimit {
      characteristics = [
        "cf.colo.id",
        "ip.src"
      ]
      period = 60
      requests_per_period = 100
      mitigation_timeout = 600
    }

    expression = "(http.request.uri.path matches \"^/api/\")"
    description = "rate limit for API"
    enabled = true
  }
}

# Also tried with default name and description for the http_ratelimit ruleset
# description = ""
# kind        = "zone"
```

### Debug output

`Error: error creating ruleset default: HTTP status 400: exceeded maximum number of zone rulesets for phase 'http_ratelimit'`

### Expected output

Resource created successfully

### Actual output

`Error: error creating ruleset default: HTTP status 400: exceeded maximum number of zone rulesets for phase 'http_ratelimit'`

### Steps to reproduce

Use `cloudflare_ruleset` resource using the code provided in documentation.

### Additional factoids

It seems that the provider is trying to create a new Ruleset instead of adding new rules to the default one. This action is not allowed by the API.
Documentation suggests that we should put new rules into the default ruleset of the `http_rate_limit` phase.
https://developers.cloudflare.com/waf/custom-rules/rate-limiting/create-api

**Comment by jacobbednarz** [comment]
This means you already have a HTTP rate limit entrypoint defined (outside of Terraform) and you shouldn't if you're planning on managing it with Terraform. Once Terraform has the phase created, it will update them in place using PUT.

You'll need to delete the existing Ruleset created in the UI and move it into Terraform and this will work as intended.

**Comment by grodriguezl** [comment]
It works now :)
I thought that the one created by the UI was a "default" one.

Thanks for the help!
