### ISSUE TITLE
Cookie Settings?

### ISSUE THREAD

**Issue by shutupflanders** [cloudflare/terraform-provider-cloudflare#1220]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

3.1.0

### Affected resource(s)

cloudflare_access_application

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "app" {
    account_id = var.account_id
    allowed_idps = var.allowed_idps
    auto_redirect_to_identity = false
    domain = var.hostname
    enable_binding_cookie = var.enable_binding_cookie
    name = var.name
    session_duration = var.session_duration
    dynamic "cors_headers" {
        for_each = length(var.cors_policy.allowed_origins) > 0 ? [{}]:[]
        content {
            allow_all_methods = var.cors_policy.allow_all_methods
            allowed_origins = var.cors_policy.allowed_origins
            allow_credentials = var.cors_policy.allow_credentials
            max_age = var.cors_policy.max_age
        }
    }

    ... cookie settings?

}
```

### Debug output

n/a

### Expected output

n/a

### Actual output

n/a

### Steps to reproduce

n/a

### Additional factoids

I'm trying to set a same-site cookie policy on my access application, but there doesn't seem to be a configuration block for it on the provider, unless I'm looking in the wrong place?

![image](https://user-images.githubusercontent.com/3372012/134824132-edef8b16-817f-4a52-8ede-43368151214d.png)

How would I go about setting this?

**Comment by jacobbednarz** [comment]
The API doesn't yet have public support for this so neither will Terraform. This won't be introduced until the public API and cloudflare-go have support.

**Comment by shutupflanders** [comment]
Fair enough, thanks for the swift reply, will close this for now.
