### ISSUE TITLE
Missing filter_id argument in cloudflare_firewall_rule docs

### ISSUE THREAD

**Issue by wi1dcard** [cloudflare/terraform-provider-cloudflare#1221]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Not relevant.

### Affected resource(s)

- `cloudflare_firewall_rule`

### Terraform configuration files

```hcl
Not relevant.
```

### Debug output

Not relevant.

### Expected output

Have the `filter_id` field in <https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/firewall_rule>.

Source: <https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/r/firewall_rule.markdown>.

### Actual output

Didn't find this field.

### Steps to reproduce

Not relevant.

**Comment by jacobbednarz** [comment]
thanks, i'm happy to review a PR for this one.
