### ISSUE TITLE
Publish v3.2.0 to registry

### ISSUE THREAD

**Issue by innovate-invent** [cloudflare/terraform-provider-cloudflare#1248]
Please publish v3.2.0 of the provider to the registry. https://registry.terraform.io/providers/cloudflare/cloudflare/latest

It looks like the release CI succeeded yet somehow the publication doesn't show. You might want to just rerun the CI?

**Comment by jacobbednarz** [comment]
This has already been raised with Hashicorp and they are working on getting the sync to complete on their side.

**Comment by innovate-invent** [comment]
Have they given you any timeline?
