### ISSUE TITLE
certificate_authority is missing from the cloudflare_custom_hostname document page

### ISSUE THREAD

**Issue by zhuyumi** [cloudflare/terraform-provider-cloudflare#1260]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Not needed.

### Affected resource(s)

Not needed.

### Terraform configuration files

```hcl
Not needed.
```

### Debug output

Not needed.

### Expected output

From the latest document page: 
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_hostname

We should expect to see an argument called `certificate_authority` inside of **ssl** block, because it is a MUST have thing to set up a custom_hostname.

**Further suggestion for doc page:**
In the doc page, it will be **very very very very** helpful to have a `example usage` which can list out EVERY SINGLE argument that possibly can be used, just like Swagger API exmaples. 

Unfortunately what we currently have now is an example with very limited arguments.
```
resource "cloudflare_custom_hostname" "example_hostname" {
  zone_id  = "d41d8cd98f00b204e9800998ecf8427e"
  hostname = "hostname.example.com"
  ssl {
    method = "txt"
  }
}
```

With the above simple example, maybe I'm not wise enough, it took me quite a while to figure out the `settings` block inside of the `ssl` block need to be 
```
  zone_id              = var.zone_id
  hostname             = var.hostname
  custom_origin_server = var.custom_origin_server
  ssl {
    method                = var.ssl.method
    type                  = var.ssl.type
    certificate_authority = var.ssl.certificate_authority
    wildcard              = var.ssl.wildcard
    settings {
      min_tls_version = var.ssl.settings.min_tls_version
    }
  }
```

rather than the follow (notice the `=` behind the `settings`)
```
  zone_id              = var.zone_id
  hostname             = var.hostname
  custom_origin_server = var.custom_origin_server
  ssl {
    method                = var.ssl.method
    type                  = var.ssl.type
    certificate_authority = var.ssl.certificate_authority
    wildcard              = var.ssl.wildcard
    settings = {
      min_tls_version = var.ssl.settings.min_tls_version
    }
  }
```

### Actual output

From the latest document page: 
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_hostname

It didn't mention `certificate_authority` at all.
But it is actually available if we add this argument, it is just invisible from the doc page, with no visibility.

### Steps to reproduce

Not needed.

**Comment by jacobbednarz** [comment]
> From the latest document page:
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_hostname
>
> It didn't mention certificate_authority at all.

this will be addressed once we move to automatic generation of schema fields in #923. if you'd like it sooner, you're welcome to send over a PR adding the field in the meantime.

> In the doc page, it will be very very very very helpful to have a example usage which can list out EVERY SINGLE argument that possibly can be used, just like Swagger API exmaples.

we intentionally don't do this at the moment as the configuration options are far too varied by use case and don't have a great way to keep on top of them; instead we use developer documentation to show the possibilities.

we may address this in the future however nothing is planned yet.
