### ISSUE TITLE
Problem with ipv6 padding

### ISSUE THREAD

**Issue by xocasdashdash** [cloudflare/terraform-provider-cloudflare#1282]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v0.14.10

### Affected resource(s)

cloudflare_access_rule

### Terraform configuration files

```hcl
resource "cloudflare_access_rule" "blocklist" {
  for_each = local.blocklist
  notes    = "A note"
  mode     = "block"
  configuration = {
    target = "ipv6"
    value  = "2601:40b:1:17c0:ad80:292b:fe1d:d849"
  }
}
```

### Debug output

Not needed.

### Expected output

No change detection.

### Actual output

Cloudflare returns this value: 

"2601:040b:0001:17c0:ad80:292b:fe1d:d849"

So terraform detects a change because both are strings and the comparator is not ignoring this difference

### Steps to reproduce

1. Apply tf config
2. Run plan 
3. Plan should not detect any change, but it does. 

### Additional factoids

It seems that cloudflare access_rule does not implement the terraform plugin [ResourceDiff](https://github.com/hashicorp/terraform-plugin-sdk/blob/9dad6ed9dc7845584ce20f1116c02a10863b1900/helper/schema/resource_diff.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L112) correctly

This [function](https://github.com/cloudflare/terraform-provider-cloudflare/blob/268ee7840dafb5fa52d11c6b729e0087a820932d/cloudflare/resource_cloudflare_access_rule.go#L259) should take into consideration that both IPs are the same and ignore it.

**Comment by jacobbednarz** [comment]
My concern isn't the validity of the value but the fact we have logic in the provider as to what is what is considered equal outside of the source of truth. This puts the provider in a position where it is carrying logic that the other clients don't have and may diverge in support. As the API (source of truth) is returning the full IPv6, the expectation is that the state file will have the full IPv6, no?

**Comment by xocasdashdash** [comment]
I'd say the idea with terraform is that the code is the actual source of truth, it's the outcome you want and the state is just a means in order to detect drift. 

The easiest way to "fix" this would be to do it in the provider level, recognizing that the API is not storing the value you send but a, still 100% valid, representation of it. 

Another option would be rejecting values and requiring that users provide the full representation, but i think this is a bad idea because of the amount of users code it could brake.

**Comment by jacobbednarz** [comment]
> I'd say the idea with terraform is that the code is the actual source of truth, it's the outcome you want and the state is just a means in order to detect drift.

Definitely not. Terraform is but a lifecycle management tool. The underlying bindings determine how to perform the operations and the remote API _is_ (and always will be) the source of truth. 

I'll chat with the DNS team internally and see why they are fully expanding it but I can't promise we'll make any changes here. My recommendation would be to use the full, padded version to match the API.

**Comment by jacobbednarz** [comment]
Chatting with the folks internally, we intentionally expand this as the downstream consumers don't know whether the value is padded or not; this leaves the presentation up to the downstream providers. I've updated the code to account for padded and unpadded values however the expanded version is still stored as that is what is coming from the API and the correct value to be comparing.
