### ISSUE TITLE
cloudflare_argo_tunnel wrong CNAME domain

### ISSUE THREAD

**Issue by cucxabong** [cloudflare/terraform-provider-cloudflare#1292]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform version: Terraform v1.0.8
Cloudflare Provider version: v3.4.0

### Affected resource(s)

`cloudflare_argo_tunnel`

### Terraform configuration files

```hcl
resource "random_id" "argo_secret" {
  byte_length = 35
}

resource "cloudflare_argo_tunnel" "tunnel" {
  account_id = local.account_id
  name       = "${local.tunnel_name}-ztna"
  secret     = random_id.argo_secret.b64_std
}


resource "cloudflare_record" "apps" {
  for_each = local.app_configs
  zone_id  = data.cloudflare_zone.this.id
  name     = each.value.hostname
  value    = cloudflare_argo_tunnel.tunnel.cname
  type     = "CNAME"
  proxied  = true
}
```

### Debug output

no need

### Expected output

CNAME should be: [TUNNEL_ID].cfargotunnel.com

### Actual output

CNAME = [TUNNEL_ID].argotunnel.com

### Steps to reproduce

* Update necessary variable for configuration above
* Run: `terraform apply`

### Additional factoids

If we update our DNS CNAME record to the output of resource `cloudflare_argo_tunnel`, we will get error
```
Error 1014 Ray ID: 6a74cc064a4c750d • 2021-11-01 11:31:28 UTC
CNAME Cross-User Banned
```

**Comment by jacobbednarz** [comment]
thanks, this has been addressed by #1293
