### ISSUE TITLE
cloudflare_device_posture_rule type "gateway" not documented

### ISSUE THREAD

**Issue by jhughes-mc** [cloudflare/terraform-provider-cloudflare#1304]
### Current Terraform and Cloudflare provider version

n/a

### Description

The "gateway" type is not documented as an option when it's supported in the code.

### Use cases

Would like all supported types to be documented.

### Potential Terraform configuration

```hcl
...
```

**Comment by nelson-vineti** [comment]
@jhughes-mc Currently dealing with a problem using tf  and gateway device_posture. Should I be adding some data around the device_posture uid? Something like device_posture = [gateway = ${uid}]?

**Comment by jhughes-mc** [comment]
> @jhughes-mc Currently dealing with a problem using tf and gateway device_posture. Should I be adding some data around the device_posture uid? Something like device_posture = [gateway = ${uid}]?

Sorry for the delayed response. I'm not actually sure, I've tried many things and I can get terraform to accept the config and run, however on the Cloudflare side it's not actually applying. There is some sort of bug here, and the function is also not documented. I suppose I could be applying this incorrectly, which is why I'm asking for docs :)

**Comment by jacobbednarz** [comment]
please see https://github.com/cloudflare/terraform-provider-cloudflare/pull/1536#issuecomment-1101448002 for a solution to WARP/gateway policies.
