### ISSUE TITLE
Ruleset - Using skip with rules raise error unknown field "version"

### ISSUE THREAD

**Issue by vences** [cloudflare/terraform-provider-cloudflare#1309]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
➜ terraform -v
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.4.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Affected resource(s)

- Ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "account_managed_waf" {
  account_id  = var.cloudflare_account_id
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "root"
  phase       = "http_request_firewall_managed"

  rules {
    action = "skip"
    action_parameters {
      rules = { 
        "4814384a9e5d4991b9815dcfc25d2f1f" = "a6be45d4905042b9964ff81dc12e41d2,fa54f3d75ed446e78c22b4ea57b90acf,ec42fac3279943388b6be5ee9182835e,37da7855d2f94f69865365d894a556a4,f2db062052cf453fbe9e93f058ecf7e7,1129dfb383bb42e48466488cf3b37cb1"
      }
    }
    expression = "(cf.zone.name eq \"vence.fun\" and cf.bot_management.score eq 1)"
    description = "Account skip rules OWASP"
    enabled = true
  }

  rules {
    action = "execute"
    action_parameters {
      id = "4814384a9e5d4991b9815dcfc25d2f1f"
      overrides {
        rules {
          id = "6179ae15870a4bb7b2d480d4843b323c"
          action = "block"
          score_threshold = 25
        }
        enabled = true
      }
      matched_data {
         public_key = "zpUlcpNtaNiSUN6LL6NiNz8XgIJZWWG3iSZDdPbMszM="
      }
    }
    expression  = "(cf.zone.name eq \"vence.fun\")"
    description = "Account OWASP vence.fun"
    enabled     = true
  }
}
```

### Debug output

[terraform.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/7521074/terraform.log)

### Expected output

I would expect my terraform configuration would works. 

### Actual output

```
╷
│ Error: error updating ruleset with ID "9ed2f9dd430e4d8186b1fa9ba9fb9e05": HTTP status 400: invalid JSON: unknown field "version"
│ 
│   with cloudflare_ruleset.account_managed_waf,
│   on rulesets.tf line 132, in resource "cloudflare_ruleset" "account_managed_waf":
│  132: resource "cloudflare_ruleset" "account_managed_waf" {
│ 
╵
```

### Steps to reproduce

1. Deploy a http_request_firewall_managed configuration without the skip rules
2. Update your configuration with the skip rules
3. You will get the error because the version latest is not expected on skip rules. 

### Additional factoids

As per the file, it seems that `"version": "latest"` is added automatically (line 346). It happens when I update the `http_request_firewall_managed`. At the creation of the phase I do not have the issue. 
I think the version here should be 1. Or it could be higher if the rules ID is updated (but I think that behaviour is not implemented yet).

**Comment by patryk** [comment]
Thanks for patience. I'm reaching out to relevant team for details.
