### ISSUE TITLE
Inconsistent Terraform state with IDN (internationalized domain name)

### ISSUE THREAD

**Issue by maddingue** [cloudflare/terraform-provider-cloudflare#1310]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.4.0

### Affected resource(s)

- cloudflare_page_rule

### Terraform configuration files

```hcl
# public variables
variable "domain_idn" {
  type = string
  default = "piecesdétachéesauto.com"
}

variable "domain_puny" {
  type = string
  default = "xn--piecesdtachesauto-htbe.com"
}


# private variables (assigned with a .tfvars file)
variable "email" {
  type = string
}

variable "api_key" {
  type = string
}

variable "account_id" {
  type = string
}


# configure Terraform
terraform {
  required_version = ">= 1.0.3"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = ">= 2.24.0"
    }
  }
}

# configure the Cloudflare provider
provider "cloudflare" {
  email      = var.email
  api_key    = var.api_key
  account_id = var.account_id
}


# zone
resource "cloudflare_zone" "example" {
  zone = var.domain_puny
  plan = "free"
}


# DNS records
resource "cloudflare_record" "root" {
  zone_id = cloudflare_zone.example.id
  name    = "@"
  type    = "A"
  proxied = "true"
  value   = "12.34.56.78"
}

resource "cloudflare_record" "www" {
  zone_id = cloudflare_zone.example.id
  name    = "www"
  type    = "A"
  proxied = "true"
  value   = "12.34.56.78"
}


# page rule
resource "cloudflare_page_rule" "page_rule_default" {
  zone_id  = cloudflare_zone.example.id

  target   = "https://*${var.domain_puny}/*"
  priority = 1
  status   = "active"

  actions {
    forwarding_url {
      status_code = 301
      url         = "https://www.cloudflare.com/"
    }
  }
}
```

### Debug output

[terraform.plan.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7528070/terraform.plan.txt)
[terraform.apply.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7528166/terraform.apply.txt)

### Expected output

After the initial `apply`, I would expect `plan` to say that everything is up to date and nothing needs to be changed.

### Actual output

`terraform plan` always indicate that it wants to perform the following change, no matter the number of times `terraform apply` is executed:
```
  # cloudflare_page_rule.page_rule_default will be updated in-place
  ~ resource "cloudflare_page_rule" "page_rule_default" {
        id       = "e9b836cabde53e029c502b64b9e4a0ef"
      ~ target   = "https://*piecesdétachéesauto.com/*" -> "https://*xn--piecesdtachesauto-htbe.com/*"
```

### Steps to reproduce

1. use the provided `terraform.tf` file
2. create a `terraform.tfvars` file with the appropriate authentication values for `email`, `api_key` and `account_id`
3. `terraform init`
4. `terraform plan -out tf.out`
5. `terraform apply tf.out`         # initial setup
6. `terraform plan -out tf.out`     # should say everything is ok, but doesn't
7. `terraform apply tf.out`         # apparently says that it applies
8. loop to step 6

### Additional factoids

My understanding is that something within Terraform core or the Cloudflare provider transforms the punycode to IDN, but fails to realize that it's the same thing. Because if you read the `terraform.tf` file, it _only_ makes use of punycode. The IDN is included as a var for human reference, but isn't used.

However, the resources in the [Terraform state](https://github.com/cloudflare/terraform-provider-cloudflare/files/7528379/terraform.tfstate.txt), especially the `cloudflare_zone` and `cloudflare_page_rule` have IDN values. A difference is that although it doesn't seem to be a problem for the `cloudflare_zone` handler, the backend behind `cloudflare_page_rule` clearly is confused, and try to propose a change that isn't.

We are managing 60 domains on Cloudflare with Terraform. The only ones with this problem are the four with IDN. The one shown in example in this ticket is another we have, but not integrated within Cloudflare, therefore that makes it five. Pretty sure I can reproduce that with the dozens of similar IDN domains we have.

**Comment by maddingue** [comment]
Reading the code, I can't see any part where it would transform between punycode and IDN. I may easily miss, not being used to Go and Terraform internals.

Looking further into the `plan` & `apply` debug logs, I see that the root cause might be the Cloudflare API. During the `apply`, we can see that the `PUT /client/v4/zones/$zone_id/pagerules/$page_rule_id` request sends the rule with the target value as punycode, but the response by the API has the target value as IDN. I guess the provider then stores the returned value as the state.

I'd dare say the reported behavior still qualifies as a bug because punycode & IDN are just two syntactic forms for what is semantically the same thing. Given not all tools or environments are able to perfectly handle Unicode, it's usually safer, user-side, to manipulate punycode. How the API and the provider should speak with each other, I leave it to you to decide, but ideally, the API could support an option to select whether we want the result formatted as IDN or punycode. This would make the change to the provide minimal, and would be useful to people directly requesting the API.

**Comment by patryk** [comment]
Hi, the Cloudflare API internally operates on Unicode representation of the IDN domain names, and this is what is being returned (it's always normalized to Unicode).

On the other hand, Terraform just compares strings, not realizing it's actually the same thing. There might be some utility module/function in the Terraform ecosystem that would make an IDN/punycode conversion for you, but I'm not aware of any.

My recommendation is to always use Unicode representation while specifying Cloudflare resources.

**Comment by maddingue** [comment]
Hello,

I feel quite dissatisfied with your closing this ticket, and wonder if you actually read my previous comment. Allow me to restate something important here: given not all tools or environments are able to perfectly handle Unicode, it's usually safer, user-side, to manipulate punycode.

> the Cloudflare API internally operates on Unicode representation of the IDN domain names, and this is what is being returned (it's always normalized to Unicode).

Whatever the API internally uses should not be concerning to the end user, especially when it's via a Terraform provider. Or, if it is (which means the abstraction somehow failed), then it should be documented. As a matter of facts, the API documentation never indicates that it will enforce Unicode representation. On the contrary, the only mention of Unicode and punycode is regarding the [DNS records](https://api.cloudflare.com/#dns-records-for-a-zone-notes):

> When using unicode characters in domain names, they will be translated to punycode and as such, the length may end up being larger than what is passed into the API 

Therefore, one part of the API _explicitly_ enforces punycode, while some other part implicitly favors Unicode.
The records show that I am not the first one to report this inconsistency, _cf._ [cloudflare-go/#688](https://github.com/cloudflare/cloudflare-go/issues/688).

> On the other hand, Terraform just compares strings, not realizing it's actually the same thing. There might be some utility module/function in the Terraform ecosystem that would make an IDN/punycode conversion for you, but I'm not aware of any.

Sorry, but that's a very lazy answer. 

I'm not a Go developer, nor a Terraform developer, yet I easily found the [idna](https://pkg.go.dev/golang.org/x/net/idna) module, which provides functions for converting between Unicode and punycode.

Minimally, the Cloudflare Terraform provider could expose functions so that one can manually convert between Unicode and punycode.

Ideally, the Cloudflare Terraform provider should do the right thing, convert between Unicode and punycode when appropriate, thus ensuring an easier life for the end user.
