### ISSUE TITLE
Durable objects?

### ISSUE THREAD

**Issue by domenkozar** [cloudflare/terraform-provider-cloudflare#1320]
### Current Terraform and Cloudflare provider version

Whatever runs on app.terraform.io

### Description

I'd like to be able to register durable object classes with terraform, mimicing the `[durable_objects]` from `wrangler.toml`.

### Use cases

Not having to use wrangler and use terraform for DO lifecycle :)

### Potential Terraform configuration

```hcl
... no idea
```

**Comment by bradworsfold-workday** [comment]
Are there plans to have terraform support Durable Objects?

**Comment by afranche** [comment]
Given https://github.com/cloudflare/cloudflare-go/pull/949, I don't know if the pending label is still fitting @jacobbednarz ?

**Comment by xtuc** [comment]
https://github.com/cloudflare/cloudflare-go/pull/949 has been merged. Can you please add Durable Object support to Terraform?

**Comment by mattfysh** [comment]
Is there a workaround?

**Comment by mattfysh** [comment]
Best workaround I could come up with was creating a Worker + Durable Object outside the managed stack, and then creating a Service Binding in the deployable WorkerScript

**Comment by skyf0l** [comment]
Any update?

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by mattfysh** [comment]
I don't get the secrecy and chaos around this feature

**Comment by skyf0l** [comment]
Hello @jacobbednarz, do you have any update concerning this feature please ?

**Comment by rayli09** [comment]
is this feature included in 5.0?
