### ISSUE TITLE
S3 compatible destination - Logpush job 

### ISSUE THREAD

**Issue by Reabaln** [cloudflare/terraform-provider-cloudflare#1323]
### Current Terraform and Cloudflare provider version

All versions 

### Description

Update Logpush job "destination_conf" parameter documentation to support S3 compatible destination for example OCI 

### Use cases

Enhance documentation for other public cloud providers 

### Potential Terraform configuration

N/A

**Comment by jacobbednarz** [comment]
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job and https://developers.cloudflare.com/logs/ have examples for achieving this. You can also look for R2 log examples since that is S3 compatible.
