### ISSUE TITLE
Support Bulk Redirects feature

### ISSUE THREAD

**Issue by ZebraFlesh** [cloudflare/terraform-provider-cloudflare#1342]
### Current Terraform and Cloudflare provider version

Terraform: 1.1.0
Cloudflare: 3.4.0

### Description

Add support for the new Bulk Redirects feature. The APIs already exist: https://developers.cloudflare.com/rules/bulk-redirects/create-api

Feature announcement: https://blog.cloudflare.com/maximum-redirects-minimum-effort-announcing-bulk-redirects/

### Use cases

This is part of zone provisioning via infrastructure as code. To use this feature today, I'd need to create a script and then some sort of build with access to the right secrets, perform error handling, etc. This should just part of the TF provider for Cloudflare.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
closed by #1700

**Comment by KevinM2k** [comment]
Hi, this is not closed by the other issue. The other issue focussed on getting the list items in, however the actual ability to create the bulk redirect and associate it to that list using terraform isn't available. The resource is, but it doesn't have the options i.e phase = redirect, list_from etc.

**Comment by MattIPv4** [comment]
👋 I've been reading through the Terraform provider but I don't see a way to create bulk redirect still. The referenced PR just added a generic concept of lists?

**Comment by fmalykh** [comment]
Would be great to have this implemented

**Comment by billinghamj** [comment]
@jacobbednarz Could you reopen this? #1700 did not resolve the issue

**Comment by MattIPv4** [comment]
👋 Checking in here @jacobbednarz to see if there's any update?

**Comment by lvets** [comment]
@KevinM2k @MattIPv4 @fmalykh @billinghamj This is working with a redirect list resource and a ruleset resource. There's an example in the ruleset documentation.

**Comment by MattIPv4** [comment]
Ahah! Indeed, looks like the ability to actually create a ruleset using the list feature that supposedly closed this issue was actually added later in #1744, which I'd completely missed.
