### ISSUE TITLE
cloudflare_argo Tiered Caching only = "HTTP status 401: invalid credentials"

### ISSUE THREAD

**Issue by re-thc** [cloudflare/terraform-provider-cloudflare#1351]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

v1.1.2 (terraform)
v3.5.0 (cloudflare)

### Affected resource(s)

cloudflare_argo

### Terraform configuration files

```hcl
resource "cloudflare_argo" "argo" {
  zone_id        = "${cloudflare_zone.zone.id}"
  tiered_caching = "on"
}
```

### Debug output

https://gist.github.com/stractenberg-newell/75c8041e83fadfdf91a2a20be60e34d4 (copied from previous issue, same issue)

### Expected output

It should enable Argo "Tiered Caching"

### Actual output

Error: failed to get smart routing setting: HTTP status 401: Not entitled to access this setting: smart_routing (1015)

### Steps to reproduce

1. `terraform apply`

### Additional factoids

Can enable in Cloudflare dashboard. Terraform only issue. Worked in 3.4.0

### References

Looks like a repeat of [701](https://github.com/cloudflare/terraform-provider-cloudflare/issues/701)

**Comment by jacobbednarz** [comment]
can you please provide a fresh debug output? this one is no longer valid per the closed issue.

**Comment by jacobbednarz** [comment]
closing due to lack of debug output; if you provide it, i'm happy to revisit this one.

**Comment by jean-mercier-hivebrite** [comment]
@jacobbednarz 

Hello i m facing the same issue

│ Error: failed to get smart routing setting: HTTP status 401: Not entitled to access this setting: smart_routing (1015)
│ 
│   with module.cloudflare_cdn.cloudflare_argo.argo_caching["XXXXXXXXXXXXX"],
│   on .terraform/modules/cloudflare_cdn/argo.tf line 1, in resource "cloudflare_argo" "argo_caching":
│    1: resource "cloudflare_argo" "argo_caching" {

it's was working in the past


the log in debug mode


`module.cloudflare_cdn.cloudflare_argo.argo_caching["XXXXXXXXXXXXXX"]: Refreshing state... [id=XXXXXXXXXXXXXX]
2022-01-28T08:06:06.971Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/01/28 08:06:06 [DEBUG] zone ID: XXXXXXXXXXXXXX: timestamp=2022-01-28T08:06:06.971Z
2022-01-28T08:06:06.975Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/01/28 08:06:06 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/zones/XXXXXXXXXXXXXX/argo/tiered_caching HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.0.4 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.8.0
Authorization: Bearer XXXXXXXXXXXXXX
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-01-28T08:06:06.973Z
2022-01-28T08:06:08.105Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/01/28 08:06:08 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6d48b836bd28ee1b-CDG
Content-Type: application/json
Date: Fri, 28 Jan 2022 08:06:08 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Sun, 25 Jan 1981 05:00:00 GMT
Pragma: no-cache
Server: cloudflare
Set-Cookie: __cflb=XXXXXXXXXXXXXX; SameSite=Lax; path=/; expires=Fri, 28-Jan-22 10:36:09 GMT; HttpOnly
Set-Cookie: __cfruid=XXXXXXXXXXXXXX-1643357168; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{
 "result": {
  "id": "tiered_caching",
  "value": "on",
  "modified_on": "2021-10-26T11:31:37.023556Z",
  "editable": false
 },
 "success": true,
 "errors": [],
 "messages": []
}
-----------------------------------------------------: timestamp=2022-01-28T08:06:08.105Z
2022-01-28T08:06:08.106Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/01/28 08:06:08 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/zones/XXXXXXXXXXXXXX/argo/smart_routing HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.0.4 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.8.0
Authorization: Bearer XXXXXXXXXXXXXX
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-01-28T08:06:08.106Z
2022-01-28T08:06:08.522Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/01/28 08:06:08 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 401 Unauthorized
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6d48b83d7fb3331d-CDG
Content-Type: application/json; charset=UTF-8
Date: Fri, 28 Jan 2022 08:06:08 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cflb=XXXXXXXXXXXXXX; SameSite=Lax; path=/; expires=Fri, 28-Jan-22 10:36:09 GMT; HttpOnly
Set-Cookie: __cfruid=XXXXXXXXXXXXXX-1643357168; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 32

{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1015,
      "message": "Not entitled to access this setting: smart_routing"
    }
  ],
  "messages": []
}
`


Thanks for your help

**Comment by jean-mercier-hivebrite** [comment]
same error with a request on API his the authent change for this ressource

**Comment by jean-mercier-hivebrite** [comment]
i think i found the why 

argo have 2 part /argo/tiered_caching and  /argo/smart_routing

The tiered_caching feature is include in our plan 
 but smart_routing is not
 but the provider make some call to both and it failed

**Comment by vences** [comment]
Can be a missing test of the value `smartRouting` and `tieredCaching` in the function `resourceCloudflareArgoRead` ?
https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_argo.go#L36

**Comment by jean-mercier-hivebrite** [comment]
> Can be a missing test of the value `smartRouting` and `tieredCaching` in the function `resourceCloudflareArgoRead` ? https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_argo.go#L36

it's test everytime the both smart_routing and tiered_caching

but we can have only one accessible on API side if we don't pay for  smart_routing

2 solution possible don't crash in case of this error 
allow read acces on API side even if we don't pay for  smart_routing

**Comment by jean-mercier-hivebrite** [comment]
```
func resourceCloudflareArgoRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*cloudflare.API)
	zoneID := d.Get("zone_id").(string)

	log.Printf("[DEBUG] zone ID: %s", zoneID)

	checksum := stringChecksum(fmt.Sprintf("%s/argo", zoneID))
	d.SetId(checksum)
	d.Set("zone_id", zoneID)

	tieredCaching, err := client.ArgoTieredCaching(context.Background(), zoneID)
	if err != nil {
		return errors.Wrap(err, "failed to get tiered caching setting")
	}

	d.Set("tiered_caching", tieredCaching.Value)

	smartRouting, err := client.ArgoSmartRouting(context.Background(), zoneID)
	if err != nil {
		return errors.Wrap(err, "failed to get smart routing setting")
	}

	d.Set("smart_routing", smartRouting.Value)

	return nil
}
```


on this code you must to add same control than for the update/delete request "if smartRouting != "" 


```
func resourceCloudflareArgoRead(d *schema.ResourceData, meta interface{}) error {
	client := meta.(*cloudflare.API)
	zoneID := d.Get("zone_id").(string)

	log.Printf("[DEBUG] zone ID: %s", zoneID)

	checksum := stringChecksum(fmt.Sprintf("%s/argo", zoneID))
	d.SetId(checksum)
	d.Set("zone_id", zoneID)

	if tieredCaching != "" {
		tieredCaching, err := client.ArgoTieredCaching(context.Background(), zoneID)
		if err != nil {
			return errors.Wrap(err, "failed to get tiered caching setting")
		}

		d.Set("tiered_caching", tieredCaching.Value)
	}
	if smartRouting != "" {
		smartRouting, err := client.ArgoSmartRouting(context.Background(), zoneID)
		if err != nil {
			return errors.Wrap(err, "failed to get smart routing setting")
		}

		d.Set("smart_routing", smartRouting.Value)
	}
	return nil
}
```

**Comment by jean-mercier-hivebrite** [comment]
i send the full debug on cloudflare ticket https://support.cloudflare.com/hc/en-us/requests/2361586?page=1

i don't want to put it in public

**Comment by jean-mercier-hivebrite** [comment]
Could you reopen this issue ? @jacobbednarz

**Comment by AlexKasaku** [comment]
Can confirm same issue when moving to v3.5.0 or later, the error does not occur in 3.4.0. 

We're not setting the `smart_routing` setting in the resource:

```
resource "cloudflare_argo" "tiered_cache" {
  zone_id = resource.cloudflare_zone.ssl_zone.id
  tiered_caching = "on"
}
```

Yet the debug shows the request is made, which won't be allowed on our account, hence the error:

```
2022-02-02T12:37:57.654Z [INFO]  provider.terraform-provider-cloudflare_v3.5.0.exe: 2022/02/02 12:37:57 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
GET /client/v4/zones/REMOVED/argo/smart_routing HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.4 terraform-plugin-sdk/2.10.0 terraform-provider-cloudflare/3.5.0
Authorization: REMOVED
Content-Type: application/json
Accept-Encoding: gzip
```

Resulting in the error from Cloudflare:

```
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 1015,
      "message": "Not entitled to access this setting: smart_routing"
    }
  ],
  "messages": []
}
```

This should work fine if the request is skipped. Looking at the debug output from 3.4.0, that never makes the request.
