### ISSUE TITLE
Terraform plan or apply results in "missing expected [" error

### ISSUE THREAD

**Issue by TheRealDwright** [cloudflare/terraform-provider-cloudflare#1367]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.6.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected resource(s)

cloudflare_record
cloudflare_access_policy

### Terraform configuration files

```hcl
resource "cloudflare_record" "example_record" {
  zone_id = module.cloudflare.zone_id
  name    = "example"
  value   = "192.1.2.3"
  type    = "A"
  ttl     = 1
  proxied = "true"
}
```

### Debug output

[Uploading debug.log…]()

### Expected output

terraform apply -target cloudflare_record.example_record                                     
Acquiring state lock. This may take a few moments...
module.cloudflare.cloudflare_zone.zone: Refreshing state... [id=sanitised_id]
cloudflare_record.example_record: Refreshing state... [id=sanitised_id]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify
│ that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

### Actual output

terraform apply -target cloudflare_record.example_record                                     
Acquiring state lock. This may take a few moments...
module.cloudflare.cloudflare_zone.zone: Refreshing state... [id=sanitised_id]
cloudflare_record.example_record: Refreshing state... [id=sanitised_id]
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests
│ to use it as part of an error message.
╵
╷
│ Error: Failed to decode resource from state
│
│ Error decoding "cloudflare_record.example_record" from previous state: missing expected [
╵
Releasing state lock. This may take a few moments...

### Steps to reproduce

1. Update terraform cloudflare to 3.6.0 from a previous version.
2. Run a target apply similar to the output
3. Observe the error

### Additional factoids

This happened after upgrading our terraform cloudflare provider to 3.6.0, previous versions worked fine.

**Comment by jacobbednarz** [comment]
This is an issue with either manually altered state, or one of your resources not the provider itself so I’m abroad there is very little we can do here.

**Comment by TheRealDwright** [comment]
it seems this is a duplicate of #1208

**Comment by TheRealDwright** [comment]
@jacobbednarz could you please elaborate? In following along with the issue previously mentioned, if I roll back the provider to `2.27.0`  things work as expected.

**Comment by jacobbednarz** [comment]
if the state migration isn’t automatically handled, you’ll need to:

- recreate the record; or
- confirm the current state and manually update it. 

also confirm this isn’t an issue with your module incorrectly referencing values.

**Comment by TheRealDwright** [comment]
I can confirm manually editing the state resolves the issue by changing data from {} to [] and manually altering the schema_version to 1.
