### ISSUE TITLE
`cloudflare_access_policy` only pick up the last access condition block

### ISSUE THREAD

**Issue by cucxabong** [cloudflare/terraform-provider-cloudflare#1372]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
on darwin_arm64

### Affected resource(s)

cloudflare_access_policy

### Terraform configuration files

```hcl
resource "cloudflare_access_policy" "test-multiple-policy-items" {
  account_id     = local.account_id
  application_id = cloudflare_access_application.apps.id
  name           = "test application policy"
  precedence     = "4"
  decision       = "allow"

  include {
    email_domain = local.policy_email_domains
  }

  include {
    device_posture = local.device_postures
  }
}
```

### Debug output

N/A

### Expected output

All access condition be created in Cloudflare

### Actual output

Only the last condition block get created

### Steps to reproduce

1. Create terraform code as above
2. Run `terraform apply`

### Additional factoids

I think the problem come from this function `https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_access_policy.go#L260`. Instead of append all configs into `policy.(Include|Require|Exclude)`, it does an assignment to the last non-nil config

I have tried to modify a little bit & it worked as expected. Will happy to contribute if this is actually a bug

**Comment by jacobbednarz** [comment]
pretty sure the issue here is that you’ve got multiple blocks of `include` but your meant to have multiple conditions inside of a single `include`.

**Comment by cucxabong** [comment]
multiple conditions inside a single `include` work but face another issue here `https://github.com/cloudflare/terraform-provider-cloudflare/issues/1215`

**Comment by cucxabong** [comment]
and from the schema I see `include` block is `schema.TypeList`. So does it should naturally support multiple `include` block?

**Comment by jacobbednarz** [comment]
> So does it should naturally support multiple include block?

it supports both but we’re using it as a single one. the schema _should_ be enforcing this with `MaxItems: 1`

closing in favour of #1215 fixing the underlying issue.
