### ISSUE TITLE
Custom Origin Trust Store

### ISSUE THREAD

**Issue by kbitr** [cloudflare/terraform-provider-cloudflare#1376]
### Current Terraform and Cloudflare provider version

Terraform v1.1.3

### Description

Please add the Custom Origin Trust Store endpoint as documented in the API.

### Use cases

Cloudflare customers like to add their Custom Origin Trust Certificate via Terraform.

### Potential Terraform configuration

```hcl
...
```

**Comment by ddanijel** [comment]
Can this be prioritized please?

**Comment by ktibi** [comment]
Hello, 

Any news about this ?

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by cicku** [comment]
We have published API calls at:

https://developers.cloudflare.com/api/resources/acm/subresources/custom_trust_store/

The TF provider should be automatically regenerated soon to support them.

**Comment by derekmurawsky** [comment]
> We have published API calls at:
> 
> https://developers.cloudflare.com/api/resources/acm/subresources/custom_trust_store/
> 
> The TF provider should be automatically regenerated soon to support them.

It doesn't appear that the provider has this? Or is it just not reflected in the docs? Or called something else?

<img width="322" height="528" alt="Image" src="https://github.com/user-attachments/assets/5906e846-4eaf-4d38-bf48-c2b685bb3e8b" />

**Comment by cicku** [comment]
> > We have published API calls at:
> > https://developers.cloudflare.com/api/resources/acm/subresources/custom_trust_store/
> > The TF provider should be automatically regenerated soon to support them.
> 
> It doesn't appear that the provider has this? Or is it just not reflected in the docs? Or called something else?
> 
> <img alt="Image" width="322" height="528" src="https://private-user-images.githubusercontent.com/3741839/546643477-5906e846-4eaf-4d38-bf48-c2b685bb3e8b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzA5NjA4NTIsIm5iZiI6MTc3MDk2MDU1MiwicGF0aCI6Ii8zNzQxODM5LzU0NjY0MzQ3Ny01OTA2ZTg0Ni00ZWFmLTRkMzgtYmY0OC1jMmI2ODViYjNlOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAyMTNUMDUyOTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk2NjkzMjE5ZjFmNDYyYjljOThhMDhjNjYyZmFiZTZiZWM2MzkyZmViZWEwYjk0ODJkMGEzZjIwYjE3NDgyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kz72Od_lwdQquuLDoCcdsHIbpZjBqLuBp3zy5eHsNAU">

We are still regenerating the SDK, actually the main work was just done yesterday. Please wait for the updates in the near future.
