### ISSUE TITLE
Endpoints for New Rule Engine

### ISSUE THREAD

**Issue by kbitr** [cloudflare/terraform-provider-cloudflare#1377]
### Current Terraform and Cloudflare provider version

Terraform v1.1.3

### Description

Please add the endpoints for the new Cloudflare Rule Engine, eg. http_request_sbfm as defined in the API.

### Use cases

Cloudflare Customers like to configure their Firewall / Rules via Terraform.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
are you able to be specific about what phases are publicly documented and missing? there are known unstable phases that have not yet reach public maturity which will be added once they stabilise.

**Comment by kbitr** [comment]
Understood. Apparently it's only https://api.cloudflare.com/#zone-rulesets-list-zone-rulesets (zones or account) for now.

`ddos_l4, ddos_l7, magic_transit, http_request_sanitize, http_request_transform, http_request_firewall_custom, http_ratelimit, http_request_firewall_managed, http_request_late_transform, http_response_firewall_managed`
