### ISSUE TITLE
cloudflare_fallback_domain docs and usage are misleading and are mis-named IMO

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/terraform-provider-cloudflare#1381]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

latest

### Affected resource(s)

cloudflare_fallback_domain

### Terraform configuration files

```hcl
none
```

### Debug output

none

### Expected output

none

### Actual output

none

### Steps to reproduce

none

### Additional factoids

The new `cloudflare_fallback_domain` resource seems backwards in the use of plural attributes and such.

The documentation has: 
```hcl
# Adding example.com to the fallback domain list
resource "cloudflare_fallback_domain" "example_fallback_domain {
  account_id = "1d5fdc9e88c8a8c4518b068cd94331fe"
  domains {
    suffix = "example.com"
    description = "Example domain"
    dns_server = ["1.1.1.1", "2.2.2.2"]
  }
}
```

This is not accurate as there is a single API endpoint where you put the *entire list of fallback domains*.  This example is not adding (appending) just a "single" domain to the list.  It's the entire set of domains.  As such, the resource should really be called `cloudflare_fallback_domains` (since it's the entire set of domains) and the blocks inside should be called `domain {}` since it specifies the config for a single domain.  The example should show multiple:

```hcl
# adding example.com along with the defaults
resource "cloudflare_fallback_domains" "example" {
  account_id = "1d5fdc9e88c8a8c4518b068cd94331fe"
  dynamic "domain" {
    for_each = toset({"intranet", "internal", "private", "localdomain", "domain", "lan", "home", "host", "corp", "local", "localhost", "home.arpa", "invalid", "test"})
    content {
      suffix = domain.value
    }
  }
  domain {
    suffix = "example.com"
    description = "Example domain"
    dns_server = ["1.1.1.1", "2.2.2.2"]
  }
}

```

**Comment by jacobbednarz** [comment]
I can see what you mean but this was the decision of the service team to model it the way they have. I’ll raise the discussion with them but closing as it was intentional and nothing to do from our side.

**Comment by tjstansell** [comment]
How is this a "decision of the service team"?  Don't you maintain cloudflare-go and the terraform provider code?

**Comment by jacobbednarz** [comment]
while I do the majority of the maintenance and herding of cats, the service teams are encouraged to own their resources in the same way they do internally as they are best placed to know what works for their endpoints.

**Comment by jacobbednarz** [comment]
while I appreciate your feedback here, we’re going to leave the resource as is. 

the resource name _should_ be a singular resource. [Terraform SDK best practice](https://www.terraform.io/plugin/sdkv2/best-practices/naming) recommend this and it gels with our current representation of the entity within the API. in the service, you’re managing a single account entity of fallback domains. 

as for the `domains` list attribute, it also follows the conventions as it is an attribute that you can repeat multiple times so it should be plural. 

thanks again for raising this and your contributions!

**Comment by tjstansell** [comment]
The first paragraph of that linked best practices document states:

> Most names in a Terraform provider will be drawn from the upstream API/SDK that the provider is using. The upstream API names will likely need to be modified for casing or changing between plural and singular to make the provider more consistent with the common Terraform practices below.

Given that the upstream API is not changing and it's api is `.../fallback_domains` (plural), that's why I suggested this should be.  I would like to see the upstream API actually support managing individual domains instead of a single "entity" that is a list of all domains.  If that support came, I would imagine it would be `.../fallback_domain/:domain` or similar.

Additionally, the guideline says

> It is preferable to use resource names that will be familiar to those with prior experience using the service in question, e.g. via a web UI it provides.

The UI, docs, and API all call this "Fallback Domains", plural.

As for the `domain {}` block name, that too doesn't follow the guideline:

> The patterns described above can also apply to such sub-blocks. Sub-blocks are usually introduced by a singular noun, even if multiple instances of the same-named block are accepted, since each distinct instance represents a single object.

So, if you were setting a list of domains like
```
domains = ["a.com", "b.com"]
```
then it would be plural, but a block that represents a single domain should be singular.
