### ISSUE TITLE
Cloudflare_workers_kv not replacing key in the kv

### ISSUE THREAD

**Issue by JonSmithBJSS** [cloudflare/terraform-provider-cloudflare#1389]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform -v
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.7.0

### Affected resource(s)

cloudflare_workers_kv

### Terraform configuration files
Initial Terraform
```hcl
resource "cloudflare_workers_kv" "value" {
  namespace_id = ${namespace_id}
  key          = "/${lookup("${local.paths}", "value")}($|/.*)"
}
```
Update Terraform
```hcl
resource "cloudflare_workers_kv" "value" {
  namespace_id = ${namespace_id}
  key          = "/${lookup("${local.paths}", "value")}($|/.*)/test"
}
```

### Debug output

 Terraform will perform the following actions:
   # cloudflare_workers_kv.book-borg will be updated in-place
   ~ resource "cloudflare_workers_kv" "value-borg" {
         id           = "/value($|/.*)"
       ~ key          = "/value($|/.*)" -> "/value($|/.*)/test"
         # (2 unchanged attributes hidden)
    }

### Expected output

Expect the key to change from `/value($|/.*)` to `/value($|/.*)/test` within cloudflare.

### Actual output

The `/value($|/.*)` key is left, and  `/value($|/.*)/test` is added as a new key, instead of replacing the key.

### Steps to reproduce

Create a key in Cloudflare_workers_kv
Once it exists change the key

### Additional factoids

As a workaround renaming the resource will remove the key and put the new key in place.

**Comment by jacobbednarz** [comment]
can you please provide the TF_LOG=DEBUG output as requested in the issue template?

**Comment by JonSmithBJSS** [comment]
Debug output attache
[debug_sanitized.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/7890221/debug_sanitized.txt)
d

**Comment by JonSmithBJSS** [comment]
I have received no update since attaching my debug logs.

**Comment by jacobbednarz** [comment]
i've tried replicating this to no avail. i'm afraid this looks like a bug in your module code as the following repro works as expected (KV `value` is updated)

initial

```hcl
resource "cloudflare_workers_kv_namespace" "example" {
  title = "test-namespace"
}

resource "cloudflare_workers_kv" "example" {
  namespace_id = cloudflare_workers_kv_namespace.example.id
  key          = "test-key"
  value        = "test value"
}
```

update 

```hcl
resource "cloudflare_workers_kv" "example" {
  namespace_id = cloudflare_workers_kv_namespace.example.id
  key          = "test-key"
  value        = "test value 1"
}
```

can you provide an example like the above to replicate the problem?

**Comment by JonSmithBJSS** [comment]
Sorry, if I use an example closer to yours:

initial:
```resource "cloudflare_workers_kv_namespace" "example" {
  title = "test-namespace"
}

resource "cloudflare_workers_kv" "example" {
  namespace_id = cloudflare_workers_kv_namespace.example.id
  key          = "test-key"
  value        = "test value"
}```

update:
```resource "cloudflare_workers_kv" "example" {
  namespace_id = cloudflare_workers_kv_namespace.example.id
  key          = "test-key-2"
  value        = "test value 1"
}```

In this scenario the resource "example" does not get fully replaced, it does not remove the original key, and adds a new key and value.

Expected behaviour would be to replace the key (removing the old one)

**Comment by jacobbednarz** [comment]
right, this is completely different to what the issue mentions. so you expect a change in the key _name_ will force a new resource to be created in Terraform? nothing to do with the value?

**Comment by JonSmithBJSS** [comment]
Sorry if it wasn't clear, but my issue only mentions the key, not the value.

But yes, I expect a change in the key name to update the name that is in the kv, so changing a name, should remove the old key, and add the new one with the correct value.

What happens is the old key is left behind, and needs to be cleaned up manually. Our current workaround is to rename the resource if we need to make a key name change
