### ISSUE TITLE
Error Destroying Enterprise Zone

### ISSUE THREAD

**Issue by brandonstrohmeyer** [cloudflare/terraform-provider-cloudflare#1407]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

❯ terraform -v
Terraform v1.1.2
on darwin_amd64

provider registry.terraform.io/cloudflare/cloudflare v3.7.0
provider registry.terraform.io/hashicorp/aws v3.73.0
provider registry.terraform.io/hashicorp/http v2.1.0
provider registry.terraform.io/hashicorp/time v0.7.2
provider registry.terraform.io/ns1-terraform/ns1 v1.12.2

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
resource "cloudflare_zone" "this" {
  zone   = "foo.example.com"
  plan   = "enterprise"
  type   = "partial"
}
```

### Debug output

```
---[ REQUEST ]---------------------------------------
DELETE /client/v4/zones/f75c7995fc0bb4cae225f9bd59a63c8a HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.2 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.7.0
Authorization: Bearer xxx
Content-Type: application/json
Accept-Encoding: gzip


-----------------------------------------------------: timestamp=2022-01-24T10:20:33.427-0500
2022-01-24T10:20:33.644-0500 [INFO]  provider.terraform-provider-cloudflare_v3.7.0: 2022/01/24 10:20:33 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Connection: close
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6d2a3f192c5463bc-ATL
Content-Type: application/json
Date: Mon, 24 Jan 2022 15:20:33 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Expires: Sun, 25 Jan 1981 05:00:00 GMT
Pragma: no-cache
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU4vq74ZFe3sNVUZcYTZ6CoPEzR; SameSite=Lax; path=/; expires=Mon, 24-Jan-22 17:50:34 GMT; HttpOnly
Set-Cookie: __cfruid=d0a22f1d77a602d86ca8739df4892a3b698a604c-1643037633; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

{
 "success": false,
 "errors": [
  {
   "code": 1314,
   "message": "Please contact Cloudflare support to perform this action"
  }
 ],
 "messages": [],
 "result": null
}
```

### Expected output

I expected the zone to be deleted

### Actual output

Received error:

```
│ Error: error deleting Cloudflare Zone: HTTP status 400: Please contact Cloudflare support to perform this action (1314)
│ 
│ 
```

### Steps to reproduce

1. Deploy `enterprise` zone. 
2. Delete zone with `terraform destroy`

### Additional factoids

After working with Cloudflare support it was confirmed the plan type must first be set to "free" (plan id: `0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee`) before a zone may be deleted.

Manually setting the zone plan via the API:

```
curl -sX PATCH "https://api.cloudflare.com/client/v4/zones/$CF_ZONE" \
     -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
     -H 'Content-Type: application/json' \
     --data '{"plan":{"id":"0feeeeeeeeeeeeeeeeeeeeeeeeeeeeee"}}'

```

and then running a `terraform destroy` operation succeeds in deleting the zone.

**Comment by jacobbednarz** [comment]
this is intentional to prevent people from accidentally or maliciously deleting enterprise zones. you can either downgrade the zone to free before deleting or contact support to perform this action and `terraform state rm` it
