### ISSUE TITLE
resource cloudflare_ruleset is not importable

### ISSUE THREAD

**Issue by marksieczkowski** [cloudflare/terraform-provider-cloudflare#1413]
### Current Terraform and Cloudflare provider version

Terraform v1.1.4
- provider registry.terraform.io/cloudflare/cloudflare v3.7.0

### Description

Allow the importing of existing rulesets into statefiles so that Cloudflare management can be migrated to Terraform more easily (verse manual ruleset delete and replacement with a ruleset created via Terraform)

### Use cases

Manage existing Cloudflare configuration with Terraform

### Potential Terraform configuration

```
terraform import cloudflare_ruleset.example 1234567890abcdefa09736fc376e9aee
```

**Comment by jacobbednarz** [comment]
Thanks for this but the decision to not make this importable is a deliberate one due to the way the resources are created and managed in the service. Terraform doesn’t quite play nicely with it so for now, we’re leaving it out requiring that resources are created from scratch. Sorry!
