### ISSUE TITLE
Allow non-authenticated consumption of cloudflare_ip_ranges data source

### ISSUE THREAD

**Issue by sawpresto** [cloudflare/terraform-provider-cloudflare#1416]
### Current Terraform and Cloudflare provider version

Terraform version = 1.1.4 (latest)
Cloudflare provider version = 3.8.0 (latest)

### Description

The cloudflare_ip_ranges data source currently pulls from the [cloudflare-go/ips.go module](https://github.com/cloudflare/cloudflare-go/blob/master/ips.go#L36), which does not require logging into the API to access the values. However, in order to use the cloudflare provider, it requires configuration/login via API token. 

Is it possible to use the just the data source and initialize an empty/null provider for this purpose? Or is there another way to input the IPs not via hardcoding or calling the Cloudflare API through Terraform?

### Use cases

Using a firewall, adding the cloudflare IPs as ingress for network firewall rules, without needing to update the IP rules manually. Safer to use the data source and pass those IPs into security rules.

### Potential Terraform configuration

```hcl

terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "3.8.0"
    }
  }
}

provider "cloudflare" {}

data "cloudflare_ip_ranges" "cloudflare" {}

```

**Comment by jacobbednarz** [comment]
see #850 for a discussion and work around on this topic. I still don’t think having a mix of unauth’d/with endpoints is a good mix from a usability standpoint point.
