### ISSUE TITLE
Preview ID for cloudflare_workers_kv_namespace

### ISSUE THREAD

**Issue by aliabbasrizvi** [cloudflare/terraform-provider-cloudflare#1426]
### Current Terraform and Cloudflare provider version

Terraform v0.15.4

### Description

Hi

I am trying to see if there is a way to create [cloudflare_workers_kv_namespace](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/workers_kv_namespace) with preview ID. I couldn't find anything. 

Please let me know how this could be done through Terraform.

For now I generated preview ID through Wrangler.

```
wrangler kv:namespace create "MY_NS" --preview
```

### Use cases

Need preview ID to be able to run `wrangler dev` locally.

### Potential Terraform configuration

```hcl
resource "cloudflare_workers_kv_namespace" "my-namespace" {
  title = "my-namespace"
  preview = true
}
```

This should also output preview ID.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
