### ISSUE TITLE
phase "http_response_headers_transform" not adressing proper transform rule

### ISSUE THREAD

**Issue by flenoir** [cloudflare/terraform-provider-cloudflare#1427]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.5
provider registry.terraform.io/cloudflare/cloudflare v3.8.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "image_link_header" {
  zone_id     = var.cf_zone_id
  name        = "image_link_header_addition"
  description = "add link header pointing to image path"
  kind        = "zone"
  phase       = "http_response_headers_transform"

  rules {
    action = "rewrite"
    action_parameters {
      headers {
        name      = "link"
        operation = "set"
        value     = "concat(\"<\", regex_replace(http.request.full_uri, \"/images-pp-m2.customerwebsite.com/cdn-cgi/image/f=auto,fit=scale-down,q=80,w=100/https://\", \"\"), \">; rel=\"canonical\"\")"
      }
    }

    expression  = "(http.host contains \"images-pp-m2\")"
    description = "add link header pointing to image url in http response"
    enabled     = true
  }
```

### Debug output

No specific output, the issue can be seen on Cloudflare interface. In fact, the new rule appear in "HTTP Request Header Modification" tab instead of "HTTP **Response** Header Modification tab"

![image](https://user-images.githubusercontent.com/3592378/152516134-f55f00f1-fe12-4d70-9ce1-e390c076bfca.png)

### Expected output

I expect that a rule in "HTTP Request Header Modification" tab appear

### Actual output

the rule appear in "HTTP Request Header Modification" tab

### Steps to reproduce

i guess simply use a similar resource code and deploy it through terraform

**Comment by jacobbednarz** [comment]
I'm afraid using your reproduction case, I cannot see this issue. This is working for me as expected.

I'd recommend you inspect the state file (which I suspect will be set to the request phase) as well as deleting this resource and starting fresh in Terraform. If you can provide a reproduction case where this issue is present on a fresh install, I'm happy to continue looking.
