### ISSUE TITLE
Error: failed to create WAF override: HTTP status 403: Authentication error (10000)

### ISSUE THREAD

**Issue by czerasz-mineiros** [cloudflare/terraform-provider-cloudflare#1430]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform version:

```bash
$ terraform --version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html
```

Cloudflare provider version:

```hcl
terraform {
  required_version = "1.0.8"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.1.0"
    }
  }
}
```

### Affected resource(s)

- cloudflare_waf_override

### Terraform configuration files

```hcl
locals {
  zone = "example.com"

  false_positive_api_rules = [
    # ID, Description, Group
    "981257", # Detects MySQL comment-/space-obfuscated injections and backtick termination, OWASP SQL Injection Attacks
    "973337", # XSS Filter - Category 2: Event Handler Vector, OWASP XSS Attacks
    "973335", # IE XSS Filters - Attack Detected, OWASP XSS Attacks
    "973333", # IE XSS Filters - Attack Detected, OWASP XSS Attacks
    "973332", # IE XSS Filters - Attack Detected, OWASP XSS Attacks
  ]
}

data "cloudflare_zones" "this" {
  filter {
    name = local.zone
  }
}

resource "cloudflare_waf_override" "some_api" {
  zone_id = data.cloudflare_zones.this.zones[0].id
  urls = [
    "some-subdomain.example.com/v1/*",
  ]

  rules = { for id in local.false_positive_api_rules : id => "disable" }
}
```

### Debug output

```
cloudflare_waf_override.some_api: Creating...
2022-02-07T09:48:07.520Z [INFO]  Starting apply for cloudflare_waf_override.some_api
2022-02-07T09:48:07.520Z [DEBUG] cloudflare_waf_override.some_api: applying the planned Create change
2022-02-07T09:48:07.520Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/02/07 09:48:07 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
POST /client/v4/zones/<SECRET>/firewall/waf/overrides HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.0.8 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.8.0
Content-Length: 233
Authorization: <SECRET>
Content-Type: application/json
Accept-Encoding: gzip

{
 "description": "",
 "urls": [
  "some-subdomain.example.com/v1/*"
 ],
 "priority": 0,
 "groups": null,
 "rewrite_action": null,
 "rules": {
  "973332": "disable",
  "973333": "disable",
  "973335": "disable",
  "973337": "disable",
  "981257": "disable"
 },
 "paused": false
}
-----------------------------------------------------: timestamp=2022-02-07T09:48:07.520Z
2022-02-07T09:48:07.846Z [INFO]  provider.terraform-provider-cloudflare_v3.8.0: 2022/02/07 09:48:07 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: <don't want to share>
Content-Type: application/json
Date: Mon, 07 Feb 2022 09:48:07 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: <SECRET>
Set-Cookie: <SECRET>
Vary: Accept-Encoding

{
 "success": false,
 "errors": [
  {
   "code": 10000,
   "message": "Authentication error"
  }
 ]
}

-----------------------------------------------------: timestamp=2022-02-07T09:48:07.846Z
╷
│ Error: failed to create WAF override: HTTP status 403: Authentication error (10000)
│ 
│   with cloudflare_waf_override.some_api,
│   on main.tf line 215, in resource "cloudflare_waf_override" "some_api":
│  215: resource "cloudflare_waf_override" "some_api" {
│ 
╵
2022-02-07T09:48:07.911Z [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-02-07T09:48:07.914Z [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.8.0/linux_amd64/terraform-provider-cloudflare_v3.8.0 pid=22202
2022-02-07T09:48:07.914Z [DEBUG] provider: plugin exited
```

### Expected output

WAF override to be created

### Actual output

```
Error: failed to create WAF override: HTTP status 403: Authentication error (10000)
```

### Steps to reproduce

1. Use configuration mentioned above
2. Run `terraform apply`

### Additional factoids

~~The [documentation mentions](https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-dashboard) that one should be able to access the "WAF exceptions" via the dashboard.~~

~~I can't find this area in my dashboard so I wonder if this feature is supported in my "Pro" plan?~~

Got an update from Cloudflare support that the [new WAF](https://blog.cloudflare.com/new-cloudflare-waf/) is **NOT** yet rolled out on all accounts. We need to wait for the migration to happen on our account

### References

I stumbled upon [this](https://community.cloudflare.com/t/waf-override-api-with-api-token/344449) community post where one can read:

> Received response from support:
>
> Currently the API Token is not supported for calling the WAF Overrides API endpoint. We have internal tickets to track this but currently there is no ETA we can share yet.

But then I wonder how this supposed to work with the `cloudflare_waf_override` Terraform resource?

---

~~A similar issue was reported [here](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1344).~~

**Comment by jacobbednarz** [comment]
> Got an update from Cloudflare support that the [new WAF](https://blog.cloudflare.com/new-cloudflare-waf/) is NOT yet rolled out on all accounts.

This resource isn't related to the new WAF. New WAF is [`cloudflare_ruleset`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset). `cloudflare_waf_override` is for the older WAF components.

> But then I wonder how this supposed to work with the `cloudflare_waf_override` Terraform resource?

You can use API key/email combination; see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#api_key for how to configure it in your provider.

> A similar issue was reported https://github.com/cloudflare/terraform-provider-cloudflare/issues/1344.

This issue is not related to authentication.

Side note: zone IDs and Ray IDs are not sensitive or can be linked back to you.

**Comment by czerasz-mineiros** [comment]
@jacobbednarz thx for the feedback! So the feature mentioned in https://developers.cloudflare.com/waf/managed-rulesets/waf-exceptions/define-dashboard does **NOT** belong to new WAF? It's strange because I can't see this interface on our dashboard...

**Comment by jacobbednarz** [comment]
the page you've linked to above _is_ WAF exceptions however, it's controlled using `cloudflare_ruleset` resource which is the overarching resource for the edge rules engine functionality.

the resource you're trying to use (`cloudflare_waf_overrides`) is for the older WAF functionality when it was a separate endpoint and system to the rules engine.
