### ISSUE TITLE
Extend resource/cloudflare_rate_limit to support managed_challenge action

### ISSUE THREAD

**Issue by duraje** [cloudflare/terraform-provider-cloudflare#1432]
### Current Terraform and Cloudflare provider version

 terraform -v    
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
+ provider registry.terraform.io/hashicorp/google v3.90.1

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html

### Description

We are still using the cloudflare_rate_limit and we would like to extend the use of managed_challange

### Use cases

cloudflare_rate_limit in UI allows the managed_challenge but not in terraform 

PR:  https://github.com/cloudflare/terraform-provider-cloudflare/pull/1431

### Potential Terraform configuration

```hcl
resource "cloudflare_rate_limit" "test_module" {
  zone_id   = module.zone-settings.cf_out_zone_id
  threshold = "1"
  period    = "600"

  match {
    request {
      url_pattern = "xyz*"

      schemes = [
        "_ALL_",
      ]

      methods = [
        "_ALL_"
      ]
    }
    response {
      origin_traffic = false
      headers = [
        {
          name  = "xyz"
          op    = "eq"
          value = "xyz"
        }
      ]
    }
  }

  action {
    mode = "managed_challenge"
  }

  description = "xyz"


  disabled = "false"

}

```

**Comment by jacobbednarz** [comment]
closed by #1431
