### ISSUE TITLE
Firewall Managed Ruleset group name needed for cloudflare_waf_group resource 

### ISSUE THREAD

**Issue by antigenius0910** [cloudflare/terraform-provider-cloudflare#1433]
### Current Terraform and Cloudflare provider version

```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
```

### Description

For official documentation https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/waf_group

Now it only offer ```[group_id](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/waf_group#group_id)```

But in reality if we need to turn our cloudflare infra all into IaC we will need to know the associate ```Group name``` as well
![Screen Shot 2022-02-07 at 12 30 56 PM](https://user-images.githubusercontent.com/5915590/152849723-8b833afc-f160-4b45-8e98-a42718d5669e.png)

or the IaC resource look something like this but we have no idea which Group Ruleset has been turn on here
```terraform
# cloudflare_waf_group.terraform_managed_resource_18ae91632f12c93ed523786a605936be:
resource "cloudflare_waf_group" "terraform_managed_resource_18ae91632f12c93ed523786a605936be" {
    count      = local.staging_only[var.environment]
    group_id   = "18ae91632f12c93ed523786a605936be"
    mode       = "on"
    package_id = "1e334934fd7ae32ad705667f8c1057aa"
    zone_id    = "3f1bc18efe333337886cd2d0f6faXXXX"
}
```

As you can see from GUI under ```package_id = "1e334934fd7ae32ad705667f8c1057aa"``` == Cloudflare Managed Ruleset. We can not tell if this ```group_id 18ae91632f12c93ed523786a605936be```  stands for ```Cloudflare Specials``` or ```Cloudflare WordPress``` 
![Screen Shot 2022-02-07 at 12 43 36 PM](https://user-images.githubusercontent.com/5915590/152851563-72c02531-7096-4777-a532-2d253b546425.png)

### Use cases

When  cloudflare_waf_group resource being imported it should has ```group_name``` 

```
ᐅ /Users/yen/repo/cf-terraforming/cf-terraforming import --resource-type $RESOURCE --zone $CLOUDFLARE_ZONE_ID --package 1e334934fd7ae32ad705667f8c1057aa
```

```terraform
# cloudflare_waf_group.terraform_managed_resource_18ae91632f12c93ed523786a605936be:
resource "cloudflare_waf_group" "terraform_managed_resource_18ae91632f12c93ed523786a605936be" {
    group_name = "Cloudflare Specials"
    group_id   = "18ae91632f12c93ed523786a605936be"
    mode       = "on"
    package_id = "1e334934fd7ae32ad705667f8c1057aa"
    zone_id    = "3f1bc18efe333337886cd2d0f6faXXXX"
}
```

### Potential Terraform configuration

```hcl
...
```

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/waf_group#group_id

**Comment by jacobbednarz** [comment]
as this version of the WAF is now considered legacy and all customers should be migrating to the rulesets engine i'm going to close this out in favour of using `cloudflare_ruleset` as it is unlikely to get any attention going forward.
