### ISSUE TITLE
Cloudflare Managed WAF ruleset - Override Enable/Disable

### ISSUE THREAD

**Issue by fabq2** [cloudflare/terraform-provider-cloudflare#1434]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

With our initial deployment of Cloudflare Managed WAF rules via terraform, we are using the override action to set rules to either “block” mode or “log”. As recommended we did not define the enable status as we wanted to continue using the “default” ruleset status. However, it looks as if this works only for initial push. Any future changes, causes ruleset status to change from “default” to “disable” w/o terraform configuration actually defining the enable status to false. In a recent terraform change of our OWSP  Paranoia levels, where we are setting paranoia-level-3 &4 to disable, it was observed that the Cloudflare manage ruleset & Credential Check ruleset “Ruleset Status” changed from “default” to “disabled” however this was not defined in the terraform.
This looks to be a bug with terraform

### Affected resource(s)

Looks to be associated with the "cloudflare_ruleset" resource

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "account_managed_waf" {
  account_id  = var.cloudflare_account_id
  name        = "Managed Cloudflare WAF via Terraform"
  description = "Managed Cloudflare WAF ruleset description via Terraform"
  kind        = "root"
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
      overrides {
        action = "block"

        # Changes default action based on category or tag name.
        dynamic "categories" {
          for_each = var.managed_category_overrides

          content {
            category = categories.value.category
            action   = categories.value.action
            enabled  = categories.value.enabled
          }
        }
      }
    }
    expression  = "(http.host in {${join(" ", [for s in var.list_waf_block : format("%q", s)])}})"
    description = "Block Mode - cloudflare-specials-blocking"
    enabled     = true
  }
```

### Debug output

N/A

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

1. deleted all managed waf ruleset. 
2. re-push terraform
3. Confirm configuration applied as expected
4. re-push terraform 
5. Notice ruleset now set to disable

**Comment by jacobbednarz** [comment]
@fabq2 can you please provide the versions you are using (`terraform -v` will give you this) and the full, untruncated TF_LOG=DEBUG output for your output?

**Comment by wjdavis5** [comment]
I was able to reproduce this as well. Unfortunately it means my production waf on hundreds of apps has been disabled for a while now. What is likely more unfortunate is that the portal shows the ruleset is enabled so we had no clue until we intentionally tried to trigger the WAF. Really need this resolved.

**Comment by jacobbednarz** [comment]
closing in favour of tracking via #1397
