### ISSUE TITLE
[ruleset] Add `managed_challenge` action

### ISSUE THREAD

**Issue by vences** [cloudflare/terraform-provider-cloudflare#1436]
### Current Terraform and Cloudflare provider version

```
➜ terraform -v
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0

Your version of Terraform is out of date! The latest version
is 1.1.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Description

Managed challenge has been added as an action recently. The Feature Request is to support managed challenge in Ruleset. Another FR has been created to support it on the Rate Limiting -> https://github.com/cloudflare/terraform-provider-cloudflare/pull/1431 
The documentation related to that action is [here](https://developers.cloudflare.com/ruleset-engine/rules-language/actions#supported-actions)

### Use cases

Support an action of `managed_challenge` in ruleset. 

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = var.cloudflare_zone_id
  name        = "managed WAF"
  description = "managed WAF ruleset description"
  kind        = "zone"
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
      overrides {
        action = "managed_challenge"
      }
    }
    expression = "true"
    description = "Execute default rules in Cloudflare Managed Ruleset in managed challenge mode on my zone-level phase entry point ruleset"
    enabled = true
  }
}
```

Current output
```hcl
╷
│ Error: expected rules.0.action_parameters.0.overrides.0.action to be one of [block challenge ddos_dynamic execute force_connection_close js_challenge log rewrite score skip], got managed_challenge
│ 
│   with cloudflare_ruleset.zone_level_managed_waf,
│   on rulesets_zone.tf line 48, in resource "cloudflare_ruleset" "zone_level_managed_waf":
│   48:         action = "managed_challenge"
│ 
╵
```

### References

- Documentation: https://developers.cloudflare.com/ruleset-engine/rules-language/actions#supported-actions
- Change need to be done on cloudflare-go: https://github.com/cloudflare/cloudflare-go/blob/master/rulesets.go#L33

**Comment by jacobbednarz** [comment]
i pulled in the latest cloudflare-go changes this morning so if you update the documentation, this should be ready to be fixed in the next release.
