### ISSUE TITLE
User Agent Blocking Rules (available in UI in Firewall - > Tools)

### ISSUE THREAD

**Issue by marinkovicpetar** [cloudflare/terraform-provider-cloudflare#1476]
### Current Terraform and Cloudflare provider version

```
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.9.1
```

### Description

Apologies from my side if I have overlooked something, but it seems I cannot find User Agent Blocking settings (UI Firewall - Tools) in the latest Terraform provider version

This is avialable via API on https://api.cloudflare.com/client/v4/zones/{zone_id}/firewall/ua_rules

### Use cases

We are now importing our CloudFlare configuration into Terraform, and since we have several User Agent Blocking rules defined, it would be good to import those into our Terraform state as well

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
we don't have support for the legacy UA rules (i probably can't see us adding the old functionality now either). if you're just getting your configuration into Terraform, i'd recommend swapping to [filter based firewall rules](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/firewall_rule) instead as they are more flexible and powerful.
