### ISSUE TITLE
Workers Script: accept config without content

### ISSUE THREAD

**Issue by jsmrcaga** [cloudflare/terraform-provider-cloudflare#1497]
### Current Terraform and Cloudflare provider version

Terraform v1.1.2
on darwin_arm64

Cloudflare Provider
3.9.1

### Description

As of today (Mar 8 2022) the `content` attribute of a `cloudflare_worker_script` cannot be empty. This means that configuring a worker via terraform will
1/ upload the first instance of the script
1/ will always check for differences between the deployed version and the "machine version"

The idea behind this issue is to allow developers to create workers with no content, avoiding the difference check from Terraform plans (and apply!).

I understand that Workers might need a default script "at creation time", which would render this issue a lot more complicated.

### Use cases

The only use-case I can think of -- but very important -- are CI/CD solutions since:
1/ I might be running terraform on a cloud computer and not have access to my worker script
2/ I might (very possibly) be deploying my worker scripts from a CI/CD solution (Travis, GitHub Actions...) using a more simple method than running my Terraform config (ie: using Wrangler)

### Potential Terraform configuration

Simply omitting the `conent` property, or:

```hcl
resource cloudflare_worker_script "my_super_script" {
    content = null
    check_content = false
}
```

**Comment by jacobbednarz** [comment]
i'm afraid the public endpoint ties the script and configuration together (https://api.cloudflare.com/#worker-script-properties) meaning that we cannot split them in the provider.

if this is something you'd like to see changed, best option a support ticket to have the feature request routed to the service team and we can incorporate it here following that.
