### ISSUE TITLE
Support cloudflare_railgun

### ISSUE THREAD

**Issue by puckey** [cloudflare/terraform-provider-cloudflare#150]
Would it be possible to support the provisioning of cloudflare railgun resources?

https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/vendor/github.com/cloudflare/cloudflare-go/railgun.go

**Comment by jacobbednarz** [comment]
It's definitely possible. Do you want to have a pass at adding the new resources? Happy to point you in the right direction if you get stuck.

**Comment by jacobbednarz** [comment]
Awesome! Thank you 🙇

**Comment by jacobbednarz** [comment]
closing this off as railgun is in maintenance only with the recommendation to migrate to a newer offering and we won't be adding this.
