### ISSUE TITLE
Document versioning strategy

### ISSUE THREAD

**Issue by gtirloni** [cloudflare/terraform-provider-cloudflare#1503]
### Current Terraform and Cloudflare provider version

Terraform 1.1.7
Cloudflare 3.10.1

### Description

Version 3.10.0 introduced a breaking change in a minor version update.

It would be nice if the maintainers would clarify if the provider follows semantic versioning or not. We were under the impression that it was safe to use "~> 3.0" or ">= 3.0, < 4.0" in version constraints to avoid breaking changes.

### Use cases

N/A

### Potential Terraform configuration

N/A

### References

https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v3.10.0

**Comment by jacobbednarz** [comment]
We follow semantic versioning. 

The 3.10.0 while breaking the schema (with a migration included), was already performed internally due to some other factors so the swap was actually handled for customers in both places.
