### ISSUE TITLE
Cloudflare KV binary value

### ISSUE THREAD

**Issue by KaziSadmanAhmed** [cloudflare/terraform-provider-cloudflare#1505]
### Current Terraform and Cloudflare provider version

Terraform v1.1.7
on linux_amd64

### Description

Cloudflare Workers KV supports uploading binary assets such as images but this plugin only supports string as the value of a KV entry. Please check the value property from the official documentation.

### Use cases

Upload images and other binary assets in KV storage.

### Potential Terraform configuration

```hcl

# Create KV namespace
resource "cloudflare_workers_kv_namespace" "example_ns" {
  title = "test-namespace"
}

# Create KV with string value
resource "cloudflare_workers_kv" "example_string" {
  namespace_id = cloudflare_workers_kv_namespace.example_ns.id
  key = "test-key-string"
  value = "test value"
}

# Create KV with binary value (solution 1 - using binary value directly)
resource "cloudflare_workers_kv" "example_binary" {
  namespace_id = cloudflare_workers_kv_namespace.example_ns.id
  key = "test-key-binary"
  value_binary = "binary value"
}

# Create KV with binary value (solution 2 - using base64 encoded binary value with the bulk update endpoint)
resource "cloudflare_workers_kv" "example_binary" {
  namespace_id = cloudflare_workers_kv_namespace.example_ns.id
  key = "test-key-binary"
  value = "base64 encoded binary value"
  base64 = true
}
```

### References

https://developers.cloudflare.com/workers/runtime-apis/kv/#parameters
https://blog.cloudflare.com/whats-new-with-workers-kv/
https://api.cloudflare.com/#workers-kv-namespace-write-key-value-pair
https://api.cloudflare.com/#workers-kv-namespace-write-multiple-key-value-pairs

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
