### ISSUE TITLE
Allow setting `request_limit_fail_open` flag

### ISSUE THREAD

**Issue by atorrescogollo** [cloudflare/terraform-provider-cloudflare#1506]
### Current Terraform and Cloudflare provider version

Terraform: v1.1.4
Cloudflare provider: 3.10.1

### Description

Allow setting `request_limit_fail_open` flag through `cloudflare_worker_route` resource. More info: https://github.com/cloudflare/cloudflare-go/issues/828

### Use cases

Allow setting `request_limit_fail_open=true`

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_route" "datadome-route" {
  zone_id                 = cloudflare_zone.my-zone.id
  pattern                 = "REDACTED"
  script_name             = cloudflare_worker_script.datadome.name
  request_limit_fail_open = true
}
```

### References

* https://github.com/cloudflare/cloudflare-go/issues/828
* I based on this: https://community.cloudflare.com/t/how-to-setting-up-failure-mode-for-route-using-api/184526/3

**Comment by elkh510** [comment]
Still missing in v5.19.0 (latest as of 2026-05-04).

The `request_limit_fail_open` flag is visible in the Cloudflare Dashboard under Zone → Workers Routes → [route] → "Failure mode", but there is no way to set it via Terraform. The current schema only exposes four attributes:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/main/internal/services/workers_route/schema.go

```hcl
resource "cloudflare_workers_route" "example" {
  zone_id = "..."
  pattern = "example.com/api/*"
  script  = "my-worker"
  # request_limit_fail_open — no such field
}
```

The underlying Cloudflare API accepts `request_limit_fail_open` on `PUT /zones/:zone_id/workers/routes/:route_id`, so there is no blocker on the API side. The only missing piece is adding the field to the provider schema.

Would appreciate a re-open or a new issue if this was intentionally excluded.
