### ISSUE TITLE
SRV records are not updating (Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for)

### ISSUE THREAD

**Issue by lifeofguenter** [cloudflare/terraform-provider-cloudflare#1510]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.10.1
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/oci v4.67.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/kreuzwerker/docker v2.16.0

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "foobar_net_srv" {
  zone_id = cloudflare_zone.foobar_net.id
  name    = "_minecraft._tcp"

  value = format(
    "%d\t%d\t%s",
    data.dns_srv_record_set.sv_mcshield.srv.0.weight,
    data.dns_srv_record_set.sv_mcshield.srv.0.port,
    trimsuffix(data.dns_srv_record_set.sv_mcshield.srv.0.target, "."),
  )

  priority = data.dns_srv_record_set.sv_mcshield.srv.0.priority
  type     = "SRV"
  ttl      = 300
}
```

### Debug output

```
2022-03-12T15:46:21.011+0100 [INFO]  provider.terraform-provider-cloudflare_v3.10.1: 2022/03/12 15:46:21 [DEBUG] Data found in config: []interface {}{}: timestamp=2022-03-12T15:46:21.011+0100
2022-03-12T15:46:21.011+0100 [INFO]  provider.terraform-provider-cloudflare_v3.10.1: 2022/03/12 15:46:21 [ERROR] setting state: data: '': source data must be an array or slice, got map: timestamp=2022-03-12T15:46:21.011+0100
2022-03-12T15:46:21.015+0100 [WARN]  Provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid plan for cloudflare_record.foobar_net_srv, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .allow_overwrite: planned value cty.False for a non-computed attribute
      - .proxied: planned value cty.False for a non-computed attribute
      - .timeouts: planned for existence but config wants absence
```

### Expected output

_no changes_

### Actual output

14:13:55    # cloudflare_record.foobar_net_srv will be updated in-place
14:13:55    ~ resource "cloudflare_record" "foobar_net_srv" {
14:13:55          id              = "aa1956eff77b37ee91629d36dd2ac812"
14:13:55          name            = "_minecraft._tcp"
14:13:55        ~ value           = "5\t22222\tservers.mcproshield.com" -> "0\t22222\tservers.mcproshield.com"
14:13:55          # (11 unchanged attributes hidden)
14:13:55  
14:13:55          # (1 unchanged block hidden)
14:13:55      }

### Steps to reproduce

-

### Additional factoids

No matter how often I run plan/apply it will always detect a change, apply the change successfully, but the changes do not seem to propagate to cloudflare.

I can verify that the changes are not made by using the webconsole and API of cloudflare.

When I update the record manually via the webconsole the changes reflect immediately. So the values are not wrong it seems.

**Comment by lifeofguenter** [comment]
Added the relevant debug output - looks indeed like a provider bug and not an issue with cloudflare's api generally :)

**Comment by jacobbednarz** [comment]
This output is still incomplete; please provide the TF_LOG output per the request.

**Comment by lifeofguenter** [comment]
Apologies @jacobbednarz not doing it on purpose, unfortunately there are a lot of sensitive resources in there - was hoping that bit was enough.

Apparently not, so will see if I can isolate it.

**Comment by lifeofguenter** [comment]
Awesome,

* https://community.cloudflare.com/t/srv-record-using-api-v4/29905
* https://github.com/cloudflare/terraform-provider-cloudflare/issues/1244

made me understand that using `value` is bugged and instead I should switch to `data{}` - works now :)

did not even have to understand the logs.
