### ISSUE TITLE
cloudflare_zone_settings_override custom default settings request

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1514]
### Current Terraform and Cloudflare provider version

Terraform v1.1.2

### Description

**Background**: 
- Currently `cloudflare_zone_settings_override` has a set of default arguments that have been pre-configured by the Terraform cloudflare team. 
- This is useful if you want to use the default resource configuration, but it makes it hard to enforce a custom baseline for all instances of the `cloudflare_zone_settings_override`.

**Request**:
- Create a `cloudflare_zone_settings_override_document` data source that allows you to define a baseline of settings for `cloudflare_zone_settings_override`.
    - This data source should output a standard JSON that defines the `cloudflare_zone_settings_override` settings.
    - Additionally it should perform logical checks to ensure that the settings are valid. Some settings in 
       `cloudflare_zone_settings_override` require a setting to be set before being able to be set.
- Update `cloudflare_zone_settings_override` to add the following optional argument `default_settings_document`. 
    -  This argument should be able to receive the JSON generated by the `cloudflare_zone_settings_override_document`
        data source.
    - Optionally the user could pass in a JSON object to this argument and bypass the
      `cloudflare_zone_settings_override_document`.
    - If a setting is defined within `cloudflare_zone_settings_override` `settings` argument, it should overwrite the
      `default_settings_document`/`cloudflare_zone_settings_override_document` setting.
    - If no setting is configured in either the `settings` argument or in the `default_settings_document` it should use the
       default setting.

This feature request is loosely based on how the hashicorp/aws provider handles IAM policies. They have an [iam_policy resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy) that takes in a JSON policy configuration and an [iam_policy_document data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document) that can generate that JSON policy configuration.

**Work around**:
- Currently there's a workaround that enables this feature but it introduces more complexity. You can add a `for_each` argument to `cloudflare_zone_settings_override` and allow you to pass in an object to configure the custom settings.

For example you could do the following:

```hcl
locals {
  cloudflare_zone_settings_override_document = {
    "<zone id>" = {
       waf = "on"
    }
    "abc-123-xyz-456" = {
      ssl = "full"
    }
  }
}

resource "cloudflare_zone_settings_override" "this" {
  for_each = local.cloudflare_zone_settings_override_document
  zone_id  = each.key
  settings {
    waf = try(each.value.waf, "on")
    ssl = try(each.value.ssl, "full")
  }
}
```

### Use cases

This resource would allow custom zone configuration baselines to be made and allow enterprises to enforce baselines across Cloudflare zone settings.

### Potential Terraform configuration

```hcl
data "cloudflare_zone_settings_override_document" "prod" {
  waf = "on"
  ssl = "full"
}

data "cloudflare_zone_settings_override_document" "dev" {
  waf = "off"
  ssl = "off"
}

resource "cloudflare_zone_settings_override" "web_app_prod_zone" {
  zone_id  = "abc-123-web-app-prod"
  settings_document = data.cloudflare_zone_settings_override_document.prod
}

resource "cloudflare_zone_settings_override" "web_app_stage_zone" {
  zone_id  = "abc-123-web-app-stage"
  settings {
    ssl = "flexible"
  }
  settings_document = data.cloudflare_zone_settings_override_document.dev
}

resource "cloudflare_zone_settings_override" "web_app_dev_zone" {
  zone_id  = "abc-123-web-app-dev"
  settings_document = data.cloudflare_zone_settings_override_document.dev
}

resource "cloudflare_zone_settings_override" "web_app_adhoc_zone" {
  zone_id  = "abc-123-web-app-adhoc"
  settings {
    waf = "on"
  }
  settings_document = jsonencode({
    ssl  = "strict"
  })
}
```

**Comment by jacobbednarz** [comment]
thanks for this but we won't be taking this on. instead, we have some plans to improve the zone settings situation but it will be more moving to dedicated endpoints and reworking the resource itself.

**Comment by jacobbednarz** [comment]
> How does cloudflare_zone_settings_override handle existing zone settings?

the intention is in the resource name; override. however, this is commonly misunderstood (and somewhat against Terraform norms) as it is only meant to be used where you want a different value to the default. unlike other resources where you define the explicit end goal and manage the full lifecycle. 

> Would the resource set all the zone settings to the default settings or would it get the settings from the existing zone?

never tried to be honest but my guess would be nothing as you're not passing in an options and it would just send a payload of the defaults. if it is important for you to know, sign up a free test zone and give it a whirl. 


> The other option I see is using cf-terraforming to generate the cloudflare_zone_settings_override resource and using it.

as mentioned above, don't do this. the resource is only intended for overriding defaults and the generated output will include all the settings.

**Comment by lmf-mx** [comment]
> ... as it is only meant to be used where you want a different value to the default. unlike other resources where you define the explicit end goal and manage the full lifecycle.

@jacobbednarz Are the defaults in this provider meant to match the defaults from Cloudflare? `ssl` doesn't default to `Off` in CF, yet that is the default per the docs for the provider.

**Comment by jacobbednarz** [comment]
they matched the defaults at one point; definitely doesn't mean it's correct now.
