### ISSUE TITLE
Some links in logpush_job document are not found

### ISSUE THREAD

**Issue by SatoruItaya** [cloudflare/terraform-provider-cloudflare#1516]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

3.10.1

### Affected resource(s)

website/docs/r/logpush_job.html.markdown

### Steps to reproduce

Click links in foloowing lines,
- https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/r/logpush_job.html.markdown?plain=1#L91
- https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/website/docs/r/logpush_job.html.markdown?plain=1#L93

**Comment by jacobbednarz** [comment]
both of the attached links work fine here; perhaps try another browser or checking that you don't have anything preventing the request locally?
