### ISSUE TITLE
cloudflare_ruleset resource: support the `http_log_custom_fields` phase

### ISSUE THREAD

**Issue by quinlanj** [cloudflare/terraform-provider-cloudflare#1534]
### Current Terraform and Cloudflare provider version

Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.10.1

### Description

Support the `http_log_custom_fields` phase on the `cloudflare_ruleset` resource. This will require the following:
- Allow `phase` field to be `http_log_custom_fields`
- In the `rules` field, allow the nested schema to:
   - let `action`  be  `log_custom_field`
   - let `action_parameters` have fields like `request_fields`, `response_fields`, `cookie_fields`

### Use cases

I want to configure Logpush custom headers in terraform instead of the api endpoint.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "custom_header_logging" {
  name        = "Logging Custom Headers"
  description = "All of the custom headers to log in the Logpush service"
  kind        = "zone"
  zone_id     = "zone-id-goes-here"
  phase       = "http_log_custom_fields"

  rules {
    description = "Logging custom headers in the Logpush service"
    enabled    = true
    action     = "log_custom_field"
    expression = "true" 
    action_parameters {
      request_fields = [
        { name = "request-header-1" },
      ]
      response_fields = [
        { name = "response-header-1" }
      ]
    }
  }
}
```

### References
https://developers.cloudflare.com/logs/reference/logpush-api-configuration/custom-fields/

**Comment by istvanfedak** [comment]
@jacobbednarz do you know if [cloudflare_logpush_job](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job) supports configuring [custom fields](https://developers.cloudflare.com/logs/reference/logpush-api-configuration/custom-fields)?

**Comment by jacobbednarz** [comment]
unsure sorry, best lodge a Cloudflare Support ticket and they will be able to route it to the logs team to answer accurately. my guess would be that once the ruleset is enabled, those fields will work being added to the logpull options attribute as the provider doesn't do any validation of that.
