### ISSUE TITLE
Retrieve ID attribute from cloudflare_healthcheck resource

### ISSUE THREAD

**Issue by nmasur** [cloudflare/terraform-provider-cloudflare#1560]
### Current Terraform and Cloudflare provider version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.8.0
```

### Description

Currently, there's no (documented) way to retrieve or reference the healthcheck ID attribute from a `cloudflare_healthcheck` resource.

### Use cases

Now that `cloudflare_healthcheck` notifications have been moved to `cloudflare_notification_policy`, it's necessary to reference the healthcheck's ID inside the notification policy filters.

### Potential Terraform configuration

As referenced inside a `cloudflare_notification_policy`:

```hcl
resource "cloudflare_notification_policy" "example" {
  account_id  = "c4a7362d577a6c3019a474fd6f485821"
  name        = "Policy for Healthcheck notification"
  description = "Notification policy to alert on unhealthy Healthcheck status"
  enabled     =  true
  alert_type  = "health_check_status_notification"

  filters {
    health_check_id = [cloudflare_healthcheck.example.id]
    status           = ["Unhealthy"]
  }
}
```

**Comment by jacobbednarz** [comment]
it looks like this is already implemented 
https://github.com/cloudflare/terraform-provider-cloudflare/blob/1d30adee0c581b89677a82b9c5dc45bab6b37500/cloudflare/schema_cloudflare_notification_policy.go#L79-L84

does this cover what you're looking to do here?

**Comment by nmasur** [comment]
This is implemented for the `cloudflare_notification_policy` resource, but I need it within the `cloudflare_healthcheck` resource. That way, I can reference it _inside_ a `cloudflare_notification_policy`.

I upgraded to 3.13.0 and tried to reference "health_check_id", for example:

```
Error: Unsupported attribute

  on notifications.tf line 13, in resource "cloudflare_notification_policy" "health_checks":
  13:     health_check_id = cloudflare_healthcheck.health_checks[*].health_check_id

This object does not have an attribute named "health_check_id".
```

**Comment by nmasur** [comment]
@jacobbednarz Hi Jacob, I'm bumping this. Not sure how to remove `pending-op-response` tag from my issue.

**Comment by jacobbednarz** [comment]
this just fell off my radar and i didn't get back to it (and why the label is still there).

in your `cloudflare_notification_policy`, i think you're after the `id` attribute - `health_check_id = cloudflare_healthcheck.health_checks[*].id`. this is exported on every resource automatically in Terraform and used as the "anchor" for operations within the CRUD lifecycle.

if this isn't what you're after, could you reframe your issue? it looks like the example you opened with is correct but your saying you want a different attribute in your latest comment which is a touch confusing.

**Comment by nmasur** [comment]
Hi @jacobbednarz, thanks again for looking into this! You actually nailed exactly what I'm after.

I should have mentioned that I first tried the `id` attribute originally (I moved to `health_check_id` after it failed).

```
Error: Unsupported attribute

  on notifications.tf line 13, in resource "cloudflare_notification_policy" "health_checks":
  13:     health_check_id = cloudflare_healthcheck.health_checks[*].id

This object does not have an attribute named "id".
```

When you say this attribute is "exported on every resource automatically", is it possible that it could fail to export? I tried looking into the provider source code, but my understanding of how providers are written is too limited to figure it out.

**Comment by jacobbednarz** [comment]
i would say highly unlikely, almost impossible without breaking the resource entirely. when we call `d.SetId` in the internals, it sets it -- we would not have been able to read the resource back into state without it.

anyway, i'm glad you got this sorted!

**Comment by mrdotkg** [comment]
@jacobbednarz I think this issue is not resolved yet.

Error with attribute `health_check_id`
```
Error: Unsupported attribute

  on notifications.tf line 13, in resource "cloudflare_notification_policy" "health_checks":
  13:     health_check_id = cloudflare_healthcheck.health_checks[*].health_check_id

This object does not have an attribute named "health_check_id".
```

Error with attribute `id`
```
Error: Unsupported attribute

  on notifications.tf line 13, in resource "cloudflare_notification_policy" "health_checks":
  13:     health_check_id = cloudflare_healthcheck.health_checks[*].id

This object does not have an attribute named "id".
```

What do you recommend to retrieve cloudflare_healthcheck `id` dynamically to attach to a cloudfalre_notification_policy.
