### ISSUE TITLE
 teams_rule identity - cannot perform this operation on type Array(Bytes)

### ISSUE THREAD

**Issue by badsector3** [cloudflare/terraform-provider-cloudflare#1562]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.8
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.12.1
+ provider registry.terraform.io/hashicorp/aws v4.9.0

### Affected resource(s)

- cloudflare_teams_rule

### Terraform configuration files

```hcl
resource "cloudflare_teams_rule" "default-rule" {

  account_id  = "60c....."
  name        = "allow-all-ipinfo-tf"
  description = "Allow all access to IPinfo.io"
  enabled     = true
  precedence  = 1
  action      = "allow"
  filters     = ["http"]
  traffic     = "http.request.uri == \"https://ipinfo.io\""
  identity    = "identity.groups.id == \"d6c.......\""
}
```

### Debug output

2022-04-12T18:45:24.045+0100 [INFO]  provider.terraform-provider-cloudflare_v3.12.1: 2022/04/12 18:45:24 [DEBUG] Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
POST /client/v4/accounts/60cf....../gateway/rules HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.1.8 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.12.1
Content-Length: 534
Authorization: Bearer m........
Content-Type: application/json
Accept-Encoding: gzip

{
 "name": "allow-all-ipinfo-tf",
 "description": "Allow all access to IPinfo.io",
 "precedence": 1,
 "enabled": true,
 "action": "allow",
 "filters": [
  "http"
 ],
 "traffic": "http.request.uri == \"https://ipinfo.io\"",
 "identity": "identity.groups.id == \"d6c.......\"",
 "device_posture": "",
 "version": 0,
 "rule_settings": {
  "override_ips": null,
  "block_reason": "",
  "override_host": "",
  "biso_admin_controls": null,
  "l4override": null,
  "add_headers": null,
  "check_session": null,
  "block_page_enabled": false,
  "insecure_disable_dnssec_validation": false
 }
}
-----------------------------------------------------: timestamp=2022-04-12T18:45:24.031+0100
2022-04-12T18:45:26.049+0100 [INFO]  provider.terraform-provider-cloudflare_v3.12.1: 2022/04/12 18:45:26 [DEBUG] Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6fadc68c8e1e3613-MAN
Content-Type: application/json; charset=UTF-8
Date: Tue, 12 Apr 2022 17:45:26 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU56Rb8iNWZVUvXhq6upceLbqCh; SameSite=Lax; path=/; expires=Tue, 12-Apr-22 20:15:27 GMT; HttpOnly
Set-Cookie: __cfruid=8bd6137ad1befce03f086bb568f30b3151beddfa-1649785526; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 1

{
  "result": null,
  "success": false,
  "errors": [
    {
      "message": "Filter parsing error (1:20):\nidentity.groups.id == \"d6c1.............\"\n                   ^^ cannot perform this operation on type Array(Bytes)\n"
    }
  ],
  "messages": []
}

-----------------------------------------------------: timestamp=2022-04-12T18:45:26.049+0100
2022-04-12T18:45:26.049+0100 [WARN]  unexpected data: registry.terraform.io/cloudflare/cloudflare:stderr="{"@caller":"github.com/hashicorp/terraform-plugin-sdk/v2@v2.13.0/internal/logging/helper_schema.go:21","@level":"trace","@message":"Called downstream","@module":"sdk.helper_schema","@timestamp":"2022-04-12T18:45:26.049443+01:00"}"
2022-04-12T18:45:26.073+0100 [ERROR] vertex "cloudflare_teams_rule.default-rule" error: error creating Teams rule for account "60cf................7": Filter parsing error (1:20):
identity.groups.id == "d6c..........."
                   ^^ cannot perform this operation on type Array(Bytes)
╷
│ Error: error creating Teams rule for account "60c............": Filter parsing error (1:20):
│ identity.groups.id == "d6c................"
│                    ^^ cannot perform this operation on type Array(Bytes)
│
│
│   with cloudflare_teams_rule.default-rule,
│   on main.tf line 1, in resource "cloudflare_teams_rule" "default-rule":
│    1: resource "cloudflare_teams_rule" "default-rule" {
│
╵
2022-04-12T18:45:26.097+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-04-12T18:45:26.099+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/cloudflare/cloudflare/3.12.1/darwin_amd64/terraform-provider-cloudflare_v3.12.1 pid=31801
2022-04-12T18:45:26.099+0100 [DEBUG] provider: plugin exited

### Expected output

So what I try to accomplish is to allow the user is particular group to have access to [ipinfo.io](http://ipinfo.io/)

### Actual output

Terraform will perform the following actions:

  # cloudflare_teams_rule.default-rule will be created
  + resource "cloudflare_teams_rule" "default-rule" {
      + account_id  = "60c...."
      + action      = "allow"
      + description = "Allow all access to IPinfo.io"
      + enabled     = true
      + filters     = [
          + "http",
        ]
      + id          = (known after apply)
      + identity    = "identity.groups.id == \"d6c......\""
      + name        = "allow-all-ipinfo-tf"
      + precedence  = 1
      + traffic     = "http.request.uri == \"https://ipinfo.io\""
      + version     = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_teams_rule.default-rule: Creating...
╷
│ Error: error creating Teams rule for account "60cf.........": Filter parsing error (1:20):
│ identity.groups.id == "d6c........"
│                    ^^ cannot perform this operation on type Array(Bytes)
│
│
│   with cloudflare_teams_rule.default-rule,
│   on main.tf line 1, in resource "cloudflare_teams_rule" "default-rule":
│    1: resource "cloudflare_teams_rule" "default-rule" {

### Steps to reproduce

You need account_id and API token and then: 
- terraform init
- terraform plan
- terraform apply

### References

Opened new ticket on community but no answer as yet.
https://community.cloudflare.com/t/terraform-teams-rule-identity/376032

**Comment by jacobbednarz** [comment]
this is an issue with the service itself, not the Terraform provider so i'm afraid i can't really help you out.

your best bet is the community forums or a support ticket to be routed to the service team to advise you on the correct syntax.
