### ISSUE TITLE
Cloudflare provider does not support keyless certificate

### ISSUE THREAD

**Issue by Ruksov-Andrey** [cloudflare/terraform-provider-cloudflare#1566]
### Current Terraform and Cloudflare provider version

-

### Description

Cloudflare provider does not support keyless certificate

### Use cases

Lets encrypt certificate installation automation

### Potential Terraform configuration

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_ssl

**Comment by jacobbednarz** [comment]
i think we're conflating two different things here. do you want Let's Encrypt certificates or keyless certificates? the former is already supported via https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack

**Comment by Ruksov-Andrey** [comment]
I mean keyless certificate

**Comment by KevinMalot** [comment]
Hello, this [PR](https://github.com/cloudflare/terraform-provider-cloudflare/pull/2779) will provide the resource
