### ISSUE TITLE
Config refers to values should be known because it is a constant, and  the data-source should not be read during apply.

### ISSUE THREAD

**Issue by feiyunzhou** [cloudflare/terraform-provider-cloudflare#1569]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: 1.1.8
 Cloudflare provider version: v3.12.0 

### Affected resource(s)

data.cloudflare_zone

### Terraform configuration files

```hcl
locals {
  cloudflare_zone_id   = "dweweweffdfdfsgbdfsffsfs" 
}

data "cloudflare_zone" "china_domain" {
  zone_id = local.cloudflare_zone_id
}
```

### Debug output

Terraform will perform the following actions:
 module.dev-feiyun420a-dns-delegation.data.cloudflare_zone.china_domain will be read during apply
 (config refers to values not yet known)
 <= data "cloudflare_zone" "china_domain"  {
      ~ account_id          = "xxxxxxxxxxxxxx" -> (known after apply)
      ~ id                  = "id_xxxxxxxxxxxxxxxxx" -> (known after apply)
      ~ name                = "xxxx.yyyy.zzzz" -> (known after apply)
      ~ name_servers        = [
          - "aaa.dns.cf-ns.com",
          - "ccc.dns.cf-ns.net",
        ] -> (known after apply)
      ~ paused              = false -> (known after apply)
      ~ plan                = "Enterprise Website" -> (known after apply)
      ~ status              = "active" -> (known after apply)
      ~ vanity_name_servers = [] -> (known after apply)
        # (1 unchanged attribute hidden)
    }

### Expected output

1. "config refers to values not yet known" is not true. config refers to values is actually a constant
2. data.cloudflare_zone.china_domain  should not be read during apply because the config refers to values is a constant 

### Actual output

1. The provider shows that "config refers to values not yet known"
2. data.cloudflare_zone.china_domain is read again during apply

### Steps to reproduce

happens from time to time
1. terraform apply successfully
2. terraform apply successfully
3. ...
4. ....
...
several times executed "terraform apply" then it happened. 

### Additional factoids

Before this happened, the firewall settings was changed.

**Comment by jacobbednarz** [comment]
i'm afraid this issue isn't reproducible in it's current state; are you able to provide the full debug logs or a reproduction case on a fresh setup?

**Comment by jacobbednarz** [comment]
closing due to lack of response; if you can provide a reproducible test case we can revisit this one.
