### ISSUE TITLE
cloudflare_filter: config duplicates an already existing config 

### ISSUE THREAD

**Issue by knyttl** [cloudflare/terraform-provider-cloudflare#1577]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

I have manually deleted all WAF records in my firewall, so  it looks like this:

<img width="1045" alt="Screenshot 2022-04-25 at 1 13 19" src="https://user-images.githubusercontent.com/401107/165000655-bc152275-c74f-4978-ba60-3a204264f642.png">

However when I try to recreate the Terraform record, I am stuck with this:

```
Error: error creating Filter for zone "9832021cd17b14a7809676410b760094": config duplicates an already existing config (10102)
│
│   with cloudflare_filter.filter_block_mj12bot,
│   on firewall.tf line 34, in resource "cloudflare_filter" "filter_block_mj12bot":
│   34: resource "cloudflare_filter" "filter_block_mj12bot" {
```

I think, this might be caused, that deleting the cloudflare_firewall_rule in the UI record does not actually delete the cloudflare_filter as the Terraform stores cloudflare_filter and cloudflare_firewall_rule for each record in the UI. 

How can I fix this?

### Affected resource(s)

- cloudflare_filter
- cloudflare_firewall_rule

### Terraform configuration files

```hcl
resource "cloudflare_filter" "filter_block_mj12bot" {
  count       = length(var.domains)
  zone_id     = var.domains[count.index].zone_id
  description = "Block MJ12bot Bot"
  expression  = "(http.user_agent contains \"MJ12bot\")"
}

resource "cloudflare_firewall_rule" "firewall_mj12bot" {
  count       = length(var.domains)
  zone_id     = var.domains[count.index].zone_id
  description = "Block MJ12bot Bot"
  filter_id   = cloudflare_filter.filter_block_mj12bot[count.index].id
  action      = "block"
}
```

### Debug output

https://gist.github.com/knyttl/74b2a4412084a4082849c5196e5c15b2

### Expected output

I should be able to delete the filters in the UI or the Terraform should be handle them.`

### Actual output

```
Error: error creating Filter for zone "61d062089a896245926e661912e4690a": config duplicates an already existing config (10102)
│
│   with cloudflare_filter.filter_block_mj12bot,
│   on firewall.tf line 34, in resource "cloudflare_filter" "filter_block_mj12bot":
│   34: resource "cloudflare_filter" "filter_block_mj12bot" {
```

### Steps to reproduce

1. Create a firewall rule via Terraform
2. Delete it in UI
3. Run Terraform to recreate the rule.

**Comment by knyttl** [comment]
This seems to be an issue with Cloudflare API rather than with Terraform provider. Clsoing.

**Comment by RafPe** [comment]
@knyttl One of the other `dirty workaround` would be to have a very much dummy condition randomly generated in every of your filters making sure then non duplicates are created i.e. 

```
(not http.cookie contains "9B32A9FA-4A00-4CD9-843B-252D64A78EBA=0FFB4425-C415-4BE4-A565-B52B892D76FA")
```

☝️  This is a quick branstorming result ;) not tested in the battlefield yet
