### ISSUE TITLE
cloudflare_notification_policy with type g6_pool_toggle_alert with switch Include future pools

### ISSUE THREAD

**Issue by tclass** [cloudflare/terraform-provider-cloudflare#1598]
### Current Terraform and Cloudflare provider version

Terraform v0.14.8
+ provider registry.terraform.io/cloudflare/cloudflare v3.14.0

### Description

for the `cloudflare_notification_policy` and the alert_type `g6_pool_toggle_alert` the option to `include future pools` doesn't exist right? I just wanted to make sure that it doesn't exist and then ask why (because it could be a bit tricky if cloudflare automatically adds pools and then terraform deletes them when it's applied?) and otherwise maybe implement it myself.

![Screenshot 2022-05-06 at 15 44 05](https://user-images.githubusercontent.com/821322/167145799-0bb73738-83c7-4670-90e2-509151255da3.png)

### Use cases

The use-case is just to mirror the cloudflare settings 1:1

### Potential Terraform configuration

```hcl
resource "cloudflare_notification_policy" "example" {
  account_id  = "467403018559428553174408"
  name        = "Policy for Healthcheck notification"
  description = "..."
  enabled     =  true
  alert_type  = "g6_pool_toggle_alert"

  email_integration {
    id   =  "myemail@example.com"
  }

  filters {
    enabled = [
      "false",
      "true",
    ]
    pool_id = ["4835301735767857826"]
}
}
```

**Comment by jacobbednarz** [comment]
this doesn't exist and depending on how it is implemented, we might not be able to include it without managing state behind the scenes.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
