### ISSUE TITLE
Feature: Support for configuring `managed_headers`

### ISSUE THREAD

**Issue by psyked** [cloudflare/terraform-provider-cloudflare#1607]
### Current Terraform and Cloudflare provider version

2.27

### Description

Managed Transforms do not appear to be a currently supported or documented item in the Terraform provider, but are generally available via the Cloudflare UI and API (https://developers.cloudflare.com/rules/transform/managed-transforms/configure/ / https://api.cloudflare.com/#managed-headers-api-change-state-of-managed-headers)

### Use cases

The ability to enabling / disable specific of Managed Transforms via Terraform would be excellent.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = "cb029e245cfdd66dc8d2e570d5dd3322"
  name        = "managed transforms"
  description = "managed transforms ruleset description"
  kind        = "zone"
  phase       = "http_request_transform_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "add_cf-bot-score_header"
    }
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled = true
  }
}
```

**Comment by jacobbednarz** [comment]
i don't think the potential configuration makes sense here as it isn't a ruleset endpoint; this would be best as a new resource (possibly a `trasform_rule` resource or similar but given the others are rulesets, 🤷 ).

**Comment by psyked** [comment]
@jacobbednarz I'm not precious in any way about the implementation / potential configuration - I am a very much a newbie to Terraform in general so I barely understand what I'm working with most of the time. 😅

**Comment by jacobbednarz** [comment]
cloudflare-go has support now via cloudflare/cloudflare-go#923
