### ISSUE TITLE
cloudflare_ruleset - overrides block can't be empty

### ISSUE THREAD

**Issue by jcolfej** [cloudflare/terraform-provider-cloudflare#1609]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.1.9 with Cloudflare provider 3.14.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
variable "cloudflare_managed_ruleset" {
  type        = any
  default     = {}
  description = <<-DOC
    action:
      The action to take when the ruleset is triggered.
    override_rules:
      A list of rules to override.
  DOC
}

resource "cloudflare_ruleset" "firewall_managed" {
  zone_id     = cloudflare_zone.this.id

  name        = "Managed WAF"
  description = "Enable managed rules"

  kind        = "zone"
  phase       = "http_request_firewall_managed"

  rules {
    description = "Cloudflare Managed Ruleset"
    enabled     = true

    expression = "true"

    action = "execute"

    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"

      overrides {
        action = try(var.cloudflare_managed_ruleset.action, null)

        dynamic "rules" {
          for_each = try(var.cloudflare_managed_ruleset.override_rules, {})

          content {
            id                = rules.key
            enabled           = try(rules.value.enabled, null)
            action            = try(rules.value.action, null)
            score_threshold   = try(rules.value.score_threshold, null)
            sensitivity_level = try(rules.value.sensitivity_level, null)
          }
        }
      }
    }
  }
}
```

### Debug output

-----------------------------------------------------
2022-05-10T11:06:09.424+0200 [DEBUG] [aws-sdk-go] {}
╷
│ Error: Plugin did not respond
│
│   with cloudflare_ruleset.firewall_managed,
│   on rulesets.tf line 17, in resource "cloudflare_ruleset" "firewall_managed":
│   17: resource "cloudflare_ruleset" "firewall_managed" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

### Panic output

-----------------------------------------------------
2022-05-10T11:06:09.994+0200 [DEBUG] [aws-sdk-go] {}

Stack trace from the terraform-provider-cloudflare_v3.14.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 115 [running]:
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.buildRulesetRulesFromResource(0x140003cabe8?)
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_ruleset.go:480 +0x22b0
github.com/cloudflare/terraform-provider-cloudflare/cloudflare.resourceCloudflareRulesetUpdate(0x140000c8300, {0x1051f55a0?, 0x140000f8540})
	github.com/cloudflare/terraform-provider-cloudflare/cloudflare/resource_cloudflare_ruleset.go:176 +0xb4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x105204030?, {0x105204030?, 0x140000b6bd0?}, 0xd?, {0x1051f55a0?, 0x140000f8540?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:729 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x140004a17a0, {0x105204030, 0x140000b6bd0}, 0x140002b2340, 0x14000660600, {0x1051f55a0, 0x140000f8540})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/resource.go:847 +0x680
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000432600, {0x105203f88?, 0x1400038de80?}, 0x14000659810)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.14.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x1400040c780, {0x105204030?, 0x140004b1f20?}, 0x140007a8310)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/tf5server/server.go:812 +0x38c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1051c7f00?, 0x1400040c780}, {0x105204030, 0x140004b1f20}, 0x140005c87e0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.9.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400033aa80, {0x105206a80, 0x1400039a1a0}, 0x1400037b8c0, 0x140004b1410, 0x1056e53c0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xb3c
google.golang.org/grpc.(*Server).handleStream(0x1400033aa80, {0x105206a80, 0x1400039a1a0}, 0x1400037b8c0, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x298

Error: The terraform-provider-cloudflare_v3.14.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

2022-05-10T11:06:09.995+0200 [DEBUG] provider: plugin exited
ERRO[0048] 1 error occurred:
	* exit status 1

### Expected output

If "overrides" block is empty, do not sent it.

### Actual output

If "overrides" block is empty, Terraform crash...

### Steps to reproduce

You can use my example code by leaving the variables by default.

**Comment by jacobbednarz** [comment]
the issue here looks to be the fact you are passing in `null` or empty `{}` for the default values whereas that isn't really what the underlying API and data type needs. 

due to the complex nature of this API and the `http_request_firewall_managed` requires `overrides` to be present this isn't really something we support right now; your best bet is to fix your usage of the resource to only establish a `overrides` block when you have overrides to send.
