### ISSUE TITLE
Tiered cache topology resource request

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1626]
### Current Terraform and Cloudflare provider version

NA

### Description

Please create a resource for managing Tiered Cache Topology in order to set either the Smart Tiered Cache Topology or the Generic Global Tiered Topology

### Use cases

We need to set the default Tiered Cache Topology via terraform.

### Potential Terraform configuration

```hcl
resource "tiered_cache_topology" "this" {
...
}
```

**Comment by jacobbednarz** [comment]
this looks to be a duplicate of #1626
