### ISSUE TITLE
cloudflare_account_member: support status option

### ISSUE THREAD

**Issue by patrobinson** [cloudflare/terraform-provider-cloudflare#1654]
### Current Terraform and Cloudflare provider version

Terraform v1.0.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.9.1

### Description

`cloudflare_account_member` resource doesn't support the `status` attribute. [This setting supports](https://api.cloudflare.com/#account-members-add-member) automatically accepting that invite,
[cloudflare-go supports this field](https://github.com/cloudflare/cloudflare-go/blob/master/account_members.go#L95)

### Use cases

When adding a user through Terraform, they have to accept that invitation via email. That email often gets missed and we need to follow up with them. The invites also expire.

### Potential Terraform configuration

```hcl
resource "cloudflare_account_member" "jane_doe" {
  email_address = "jane.doe@example.com"
  send_email_invite = false
  role_ids = [
    "deadbeef",
  ]
  lifecycle {
    create_before_destroy = true
  }
}
```

Alternatively we could use `status = "accepted"` but since that field only receives two possible values a Boolean makes more sense to me 🤷

**Comment by jacobbednarz** [comment]
heyo! 👋 there are a couple of considerations to this functionality that are kind of hidden and aren't obvious at first glance. 

the first is that you cannot direct add a user that doesn't already exist which means this isn't a silver bullet for all scenarios. the second is that (despite the documentation being unclear), this isn't available to all plans to prevent spam inviting users; enterprise + tenants should be fine though.

> Alternatively we could use `status = "accepted"` but since that field only receives two possible values a Boolean makes more sense to me 🤷

let's keep the Terraform schem matching the API response with `status = "..."` which helps automatically adding support to cf-terraforming without a field remap.

if you want to send a PR for this, i'm happy to take a look otherwise there will be a delay on adding this since it isn't a heavily requested feature for the provider.

**Comment by patrobinson** [comment]
> the first is that you cannot direct add a user that doesn't already exist which means this isn't a silver bullet for all scenarios.

Can you explain this a bit more? What happens if that user doesn't already exist and we add them with status accepted, does it fail? Do we need to make two API calls, a PUT and POST?

> the second is that (despite the documentation being unclear), this isn't available to all plans to prevent spam inviting users; enterprise + tenants should be fine though.

My assumption is we don't need to handle that in the terraform provider, the API error will just bubble up in that scenario?

> if you want to send a PR for this, i'm happy to take a look otherwise there will be a delay on adding this since it isn't a heavily requested feature for the provider.

I appreciate that and will get to this when I get some time.

**Comment by jacobbednarz** [comment]
> What happens if that user doesn't already exist and we add them with status accepted, does it fail? Do we need to make two API calls, a PUT and POST?

if you attempt to add a user that doesn't have a cloudflare account, you'll get a HTTP 400 back that will be "cannot add verified membership for non-existing user". Terraform will return an error in the `apply`/`plan` operations as the API call will fail. the number and combination of API calls aren't really relevant to the functionality here. if the user isn't verified (created account, confirmed email, etc) there isn't a way to force the status via the API or even the UI. this may make it less useful for some scenarios where you know someone should have an account but for whatever reason, doesn't already have an account.

> My assumption is we don't need to handle that in the terraform provider, the API error will just bubble up in that scenario?

correct; you don't specifically need to handle it (just like other errors from the API that terraform handles out of the box) but do need to be aware that this may not (most likely won't) work across the board without the entitlement. you'll need to factor this into the testing as i suspect testing this on free/pro/biz zones may not give you the result you are expecting.
