### ISSUE TITLE
Resources for managing R2

### ISSUE THREAD

**Issue by andyli** [cloudflare/terraform-provider-cloudflare#1664]
### Current Terraform and Cloudflare provider version

N/A

### Description

Would be nice to have resources for managing [R2](https://developers.cloudflare.com/r2/) buckets.

### Use cases

To manage everything in Terraform.

### Potential Terraform configuration

Something similar to the [aws_s3_bucket](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket) and the related resources.

**Comment by pkoch** [comment]
@jacobbednarz can you elaborate what upstream movement we're jammed on? I can programmatically manipulate buckets with `wrangler r2 bucket OPERATION`.

**Comment by jacobbednarz** [comment]
the upstream library that Terraform uses to make the API calls - cloudflare-go.

**Comment by ghuntley** [comment]
Disappointed to see there's no support for buckets w/terraform.

**Comment by yonran** [comment]
If you just want to create buckets and objects, you can use the terraform-provider-aws with the [S3 Compatibility API](https://developers.cloudflare.com/r2/platform/s3-compatibility/) and an [S3 Auth token](https://developers.cloudflare.com/r2/platform/s3-compatibility/tokens/). Example of creating an R2 bucket:

```
variable "account_id" {
  type = string
  sensitive = true
}
variable "cloudflare_s3_access_key_id" {
  type = string
}
variable "cloudflare_s3_secret_access_key" {
  type = string
  sensitive = true
}
provider "aws" {
  access_key = var.cloudflare_s3_access_key_id
  secret_key = var.cloudflare_s3_secret_access_key
   # https://developers.cloudflare.com/r2/platform/s3-compatibility/api/#bucket-region
  region = "auto"
  # fix error validating provider credentials: error calling sts:GetCallerIdentity
  # … lookup sts.auto.amazonaws.com on …: no such host
  skip_credentials_validation = true
  # fix Error: Invalid AWS Region: auto
  skip_region_validation = true
  skip_requesting_account_id = true
  endpoints {
    # https://developers.cloudflare.com/r2/platform/s3-compatibility/api/
    s3 = "https://${var.account_id}.r2.cloudflarestorage.com"
  }
  # optional: use an alias so you can also use the real aws provider
  alias = "cloudflare_r2"
}

resource "aws_s3_bucket" "terraform" {
  provider = aws.cloudflare_r2
  bucket = "my-bucket"
}
```

However, it seems that it is still not possible to bind a bucket to a [`cloudflare_worker_script`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/worker_script) from terraform, which is pretty important.

**Comment by alex8bitw** [comment]
> the upstream library that Terraform uses to make the API calls - cloudflare-go.
Looks like support was already added https://github.com/cloudflare/cloudflare-go/pull/1028

**Comment by Elycin** [comment]
Looking forward to this. +1

**Comment by fredsig** [comment]
Looking forwad as well now that R2 is GA.

**Comment by Cyb3r-Jak3** [comment]
FYI, this still isn't possible as there is no publicly documented API end to get a bucket which terraform needs to check to see if a resource exists.

**Comment by argeas** [comment]
Looking forward to this as well !

**Comment by argeas** [comment]
Looking forwad as well !

**Comment by jpalomaki** [comment]
When this does get implemented, having CORS support baked-in would be great: https://kian.org.uk/configuring-cors-on-cloudflare-r2/

**Comment by knpwrs** [comment]
@jpalomaki that may be possible using the AWS provider to configure the R2 bucket (I haven't tried yet but I plan on it): https://developers.cloudflare.com/r2/examples/terraform/

**Comment by laurencegill** [comment]
I have found the following aws resources seem to work fine:
```
aws_s3_bucket
aws_s3_bucket_acl
aws_s3_bucket_lifecycle_configuration
aws_s3_bucket_public_access_block
aws_s3_bucket_server_side_encryption_configuration
aws_s3_bucket_versioning
```

`aws_s3_bucket_public_access_block` doesn't work, and nor can you bind a CF domain using TF, which is quite annoying.

**Comment by knpwrs** [comment]
@jpalomaki I recently got configuring CORS with terraform working:

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.57.1"
    }
  }
}

provider "aws" {
  alias                       = "cloudflare"
  region                      = "us-east-1"
  access_key                  = var.cloudflare_r2_access_key
  secret_key                  = var.cloudflare_r2_secret_key
  skip_credentials_validation = true
  skip_region_validation      = true
  skip_requesting_account_id  = true

  endpoints {
    s3 = var.cloudflare_r2_endpoint
  }
}

resource "aws_s3_bucket" "public_bucket" {
  provider = aws.cloudflare
  bucket   = var.cloudflare_r2_public_bucket
}

resource "aws_s3_bucket_cors_configuration" "public_bucket_cors" {
  provider = aws.cloudflare
  bucket   = aws_s3_bucket.public_bucket.id

  cors_rule {
    allowed_methods = ["GET"]
    allowed_origins = ["*"]
  }
}
```

**Comment by MrTimscampi** [comment]
Would be great to be able to configure Domain Access as well, since it currently doesn't seem to be possible to set some required metadata with cloudflare_record, like which R2 bucket the DNS record points to (Even though importing R2 records works just fine).
