### ISSUE TITLE
cloudflare_access_group: reference ip list in include statement

### ISSUE THREAD

**Issue by fwwieffering** [cloudflare/terraform-provider-cloudflare#1665]
### Current Terraform and Cloudflare provider version

v3.16.0

### Description

`cloudflare_teams_list` now supports `IP` type https://github.com/cloudflare/terraform-provider-cloudflare/issues/1550 but it isn't possible to reference IP lists. the best I can do is reference the `items` attribute. 

In the UI there is an option to add include rules for `IP List`
<img width="864" alt="image" src="https://user-images.githubusercontent.com/8900816/171523003-bc324f62-a454-4e1f-8d47-b911110deb10.png">

### Use cases

Pass a list of items by reference instead of by value

### Potential Terraform configuration

```hcl
resource "cloudflare_teams_list" "ip_allowlist" {
  account_id = var.account_id
  name       = "ip allowlist"
  type       = "IP"
  items = [
    "1.2.3.4"
  ]
}

resource "cloudflare_access_group" "ip_group" {
  account_id     = var.account_id
  name           = "staging group"

  include {
    ip_list = resource.cloudflare_teams_list.ip_allowlist.id
  }
}
```

**Comment by keitap** [comment]
I needed this feature too, so I implemented it and am waiting for a review.
