### ISSUE TITLE
Decouple rules from cloudflare_ruleset

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1669]
### Current Terraform and Cloudflare provider version

Terraform v1.2.1
on darwin_amd64

### Description

Background:
- Currently when you want to manage a Cloudflare ruleset via terraform you have to delete the existing ruleset via the Cloudflare API and define the new ruleset (and the rules it contains) in Terraform. This grants you complete control over the ruleset and you're able to enforce the Terraform configuration. 
- My understanding is that there can only be a single ruleset per zone and deleting and recreating the ruleset in Terraform is redundant [official guide](https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/#before-you-start)

Ask:
- Decouple rules from `cloudflare_ruleset`
- Allow the default cloudflare zone ruleset to be imported as a terraform resource
- Remove the rules attribute from the `cloudflare_ruleset` resource
- Add a `cloudflare_ruleset` data source that retrieves the default ruleset configuration to be able to link the rules to it
    - This would allow someone to add rules to the default ruleset
- Add a `cloudflare_ruleset_rule` resource to manage a single rule that is part of a ruleset
    - The attributes of this resource would be the same as the nested attributes for the `cloudflare_ruleset` rules attribute

### Use cases

- We need the ability to configure a baseline for a zone's ruleset, have Terraform enforce that baseline, but allow the business to add custom rules from the Cloudflare portal that are not overwritten by Terraform and are not tracked by Terraform

### Use case 1 - deleting default ruleset and creating the ruleset with terraform
```hcl
# Zone-level WAF Managed Ruleset
resource "cloudflare_ruleset" "this" {
  zone_id     = var.zone_id
  name        = "zone"
  description = ""
  kind        = "zone"
  phase       = "http_request_firewall_managed"
}

# Cloudflare Leaked Credentials Check
resource "cloudflare_ruleset_rule" "leaked" {
  ruleset_id = cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "c2e184081120413c86c3ab7e14069605"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Exposed Credentials Check Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare Managed Ruleset
resource "cloudflare_ruleset_rule" "managed" {
  ruleset_id = cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "efb7b8c949ac4650a09736fc376e9aee"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare OWASP Core Ruleset
resource "cloudflare_ruleset_rule" "owasp" {
  ruleset_id = cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "4814384a9e5d4991b9815dcfc25d2f1f"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare OWASP Core Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}
```

### Use case 2 - Using the data source to create `cloudflare_ruleset_rule` with `ruleset_id` attribute
```hcl
data "cloudflare_ruleset" "this" {
  zone_id = var.zone_id
}

# Cloudflare Leaked Credentials Check
resource "cloudflare_ruleset_rule" "leaked" {
  ruleset_id = data.cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "c2e184081120413c86c3ab7e14069605"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Exposed Credentials Check Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare Managed Ruleset
resource "cloudflare_ruleset_rule" "managed" {
  ruleset_id = data.cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "efb7b8c949ac4650a09736fc376e9aee"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare OWASP Core Ruleset
resource "cloudflare_ruleset_rule" "owasp" {
  ruleset_id = data.cloudflare_ruleset.this
  action = "execute"
  action_parameters {
    id = "4814384a9e5d4991b9815dcfc25d2f1f"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare OWASP Core Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}
```

### Use case 3 - using the default zone ruleset and using the `cloudflare_ruleset_rule` with `zone_id` attribute
```hcl
# Cloudflare Leaked Credentials Check
resource "cloudflare_ruleset_rule" "leaked" {
  zone_id = var.zone_id
  action = "execute"
  action_parameters {
    id = "c2e184081120413c86c3ab7e14069605"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Exposed Credentials Check Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare Managed Ruleset
resource "cloudflare_ruleset_rule" "managed" {
  zone_id = var.zone_id
  action = "execute"
  action_parameters {
    id = "efb7b8c949ac4650a09736fc376e9aee"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}

# Execute Cloudflare OWASP Core Ruleset
resource "cloudflare_ruleset_rule" "owasp" {
  zone_id = var.zone_id
  action = "execute"
  action_parameters {
    id = "4814384a9e5d4991b9815dcfc25d2f1f"
    version = "latest"
  }
  expression = "true"
  description = "Execute Cloudflare OWASP Core Ruleset on my zone-level phase entry point ruleset"
  enabled = true
}
```

**Comment by jacobbednarz** [comment]
appreciate the time you've taken to raise this proposal @istvanfedak, i've added some notes for you below.

> My understanding is that there can only be a single ruleset per zone and deleting and recreating the ruleset in Terraform is redundant [official guide](https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/#before-you-start)

a small clarification here, you can only have a single ruleset per phase (of which there are [many](https://github.com/cloudflare/cloudflare-go/blob/master/rulesets.go#L20-L34)). this is the current state however, this may not always be the case going forward.

> Decouple rules from `cloudflare_ruleset`

i'm sorry, but we won't be doing this in the foreseeable future. the resources align with the API response representation of the resource and the API provides this as a single resource. splitting this into two resources would go against the conventions of the current provider and Terraform as a whole. i've seen some other providers attempt this with varying degrees of success and right now, there is very little benefit for us to be gained from it.

> We need the ability to configure a baseline for a zone's ruleset, have Terraform enforce that baseline, but allow the business to add custom rules from the Cloudflare portal that are not overwritten by Terraform and are not tracked by Terraform

i don't recommend taking this approach. if you're managing resources with Terraform, the expectation from Terraform is that it will be managing the entire resource, not part of it. you'll encounter some very annoying workflow quirks and bugs taking this approach.

**Comment by istvanfedak** [comment]
@jacobbednarz Thanks for the fast response

**Comment by istvanfedak** [comment]
@jacobbednarz I did some research and the Cloudflare API does support adding rules to an existing ruleset:

- `resource "cloudflare_ruleset_rule"` would map to https://developers.cloudflare.com/ruleset-engine/rulesets-api/add-rule/
- `data "cloudflare_ruleset"` would map to https://api.cloudflare.com/#zone-rulesets-get-entrypoint-ruleset

This would allow you to pull the existing ruleset via its phase and add a rule to it

**Comment by jacobbednarz** [comment]
you're correct, the API supports this however, that isn't the entirety of the issue. 

the ruleset rules API is more if you know exactly what rule you want to change and how it impacts the surrounding conditions which would be lost here (most people don't actually need to manage the resources in this much detail). taking the approach where we separate the two would also introduce the following hurdles:

- it would break assumptions in `cf-terraforming` for managing the resources as the fields wouldn't be a 1:1 to the API response provided. we attempt to do as little remapping of fields and manual work in `cf-terraforming` as possible.
- the proposal for splitting would need to find a good way of communicating priority/ordering of multiple rules. right now, in the single resource, it is explicit whereas multiple resources would require more custom fields (such as priority) for Terraform to orchestrate the ordering. this then introduces the bigger issue of us doing part of the lifecycle management ourselves (when we delete/create/modify a rule, ensuring we gather them in the correct order) creating Terraform specific functionality which we don't really like doing seeing how we maintain the API endpoints.

as i mentioned, i've also seen this approach in various states of success (we even have one for access policies that i'm not entirely happy with past jacob's implementation due the remote API and dependency relationships). 

hope this sheds some more light on the scenario and if you've got a strong proposal for these issues, i'm all ears but it is unlikely to happen in the short term.

**Comment by nightpool** [comment]
This restriction makes it impossible to define rules inside of modules. For example, in our Terraform configuration we have a `s3_bucket` module that defines the s3 bucket, the Cloudflare record, and a page rule to rewrite the Host header. We use this module all over the place to define new ready-to-go S3 buckets with all of the right caching configurations. This would be impossible to replicate using origin rulesets due to the restriction on having only 1 ruleset per phase per zone and no ability to define a rule referencing an existing ruleset..

**Comment by acdha** [comment]
Is there any plan to fix the Cloudflare API to make management less all-or-nothing? I recently wanted to manage some redirect rules for a single project in a zone which is used by multiple applications (our enterprise's top-level domain) and hit the roadblock that this is not possible unless we migrate all of the rules into the same Terraform project, which isn't possible for us. I could do what I need by calling the API directly, or possibly doing something gross with `data` lookups to supply the other project's rules verbatim while adding my own but that seems like a lot more work than it should take.

This would also improve the current confusion between the Cloudflare API docs using “rules” to mean a list of multiple rules and the `cloudflare_ruleset` provider using “rules” to refer to a single rule which will transparently be merged into that larger set of rules.

**Comment by nightpool** [comment]
@acdha We worked around the situation by continuing to use Page Rules for now, since those aren't going anywhere. It's a shame that modern rulesets are effectively impossible to use with Terraform though
