### ISSUE TITLE
Log/Simulate Rate limiting rules in RuleSets 

### ISSUE THREAD

**Issue by FStephenQuaratiello** [cloudflare/terraform-provider-cloudflare#1671]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Running on Terraform Cloud, Terraform v0.13.2

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "rate_limiting_rules" {
  zone_id  = var.zone_id
  name     = "Rate limiting for zone ${var.zone_name}"
  kind     = "zone"
  phase    = "http_ratelimit"

  rules {
    action = "log"

    ratelimit {
      characteristics     = ["cf.colo.id", "ip.src"]
      period              = 600
      requests_per_period = 2
      mitigation_timeout  = 600
    }

    expression = "(http.request.uri.path matches \"^/user_referrals/*\")"
    enabled    = true
  }
}
```

### Debug output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.rate_limiting_rules.cloudflare_ruleset.rate_limiting_rules["(http.request.uri.path matches \"^/user_referrals/*\")"] will be created
  + resource "cloudflare_ruleset" "rate_limiting_rules" {
      + id      = (known after apply)
      + kind    = "zone"
      + name    = "Rate limiting for zone REDACTED"
      + phase   = "http_ratelimit"
      + zone_id = "REDACTED"

      + rules {
          + action     = "log"
          + enabled    = true
          + expression = "(http.request.uri.path matches \"^/user_referrals/*\")"
          + id         = (known after apply)
          + ref        = (known after apply)
          + version    = (known after apply)

          + ratelimit {
              + characteristics     = [
                  + "cf.colo.id",
                  + "ip.src",
                ]
              + mitigation_timeout  = 600
              + period              = 600
              + requests_per_period = 2
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "cloudflare-zone-dev-workrise-com"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 

Error: error creating ruleset Rate limiting for zone REDACTED: not entitled to use the log action, exceeded the maximum number of ratelimiting rules: 1 out of 0

  on ../../../modules/rate-limiting-rules/main.tf line 1, in resource "cloudflare_ruleset" "rate_limiting_rules":
   1: resource "cloudflare_ruleset" "rate_limiting_rules" {
```

### Expected output

The ruleset to be created, with a single rate limiting rule with the `log` action being created in the appropriate zone.

### Actual output

`Error: error creating ruleset Rate limiting for zone REDACTED: not entitled to use the log action, exceeded the maximum number of ratelimiting rules: 1 out of 0`, and the apply failing

### Steps to reproduce

1. Attmept to create a ruleset with a rate limiting rule and the `log` action
2. Observe that the apply will fail with an error

### Additional factoids

The zone in question does have the rate limiting rule entitlement, and we are able to create functional logging rules from the web console. 

Attempting to replace the `log` action with `simulate` (as the API seems to require) instead yields a `Error: expected rules.0.action to be one of [block challenge ddos_dynamic execute force_connection_close js_challenge managed_challenge log log_custom_field rewrite score skip route], got simulate` error

### References

[api.cloudflare.com](https://api.cloudflare.com/#rate-limits-for-a-zone-update-rate-limit) and the API response has it as "simulate", while [developers.cloudflare.com](http://developers.cloudflare.com/)  and the [terraform module reference](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#ratelimit) has it as "log". There is an older resource that's rate-limit-specific and does support "simulate", but[ the documentation refers to it as the "previous version"](https://developers.cloudflare.com/terraform/additional-configurations/rate-limiting-rules/) and implies it is deprecated in favor of the cloudflare_ruleset resource.

**Comment by FStephenQuaratiello** [comment]
I've added the requested information

**Comment by jacobbednarz** [comment]
couple of things here:

1. terraform 0.13 is no longer supported by this provider, I recommend you upgrade as we won't be fixing any issues that occur on old versions. 
2. you're using a module for the code and error is related to lacking an entitlement. neither of these things are something we debug/handle in the provider. this functionality definitely works as I used it two days ago in this exact configuration. I'd recommend checking with the account team and/or use it without a module to confirm you don't have a bug there picking up the wrong zone.
