### ISSUE TITLE
support for cloudflare_teams_location as a data source to obtain uuid

### ISSUE THREAD

**Issue by swies0wl** [cloudflare/terraform-provider-cloudflare#1692]
### Current Terraform and Cloudflare provider version

Terraform v1.2.2
provider registry.terraform.io/cloudflare/cloudflare v3.16.0

### Description

would like to obtain cloudflare_teams_location from a data source to support creation of policies based on location id.
i can statically define the uuid but would be nice to have the ability to programmatically lookup in terraform.

### Use cases

the request would allow the programmatic capability to retrieve the location uuid for use in other areas of code.
the specific use case would be to enable the creation of a policy to include a location within a DNS policy.
see:  https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/#location
_Use this selector to apply DNS policies to a specific Gateway location or set of locations.
UI name	API example
Location	dns.location in {"location_uuid_1" "location_uuid_2"}_

### Potential Terraform configuration

```hcl

data "cloudflare_teams_location" "office" {
    name = "mylocation"
}

resource "cloudflare_teams_rule" "this" {
  name        = "Block example.com for locaiton(s)"
  account_id  = var.myaccount_id
  description = "Block exmple.com for location(s) listed"
  enabled     = true
  precedence  = 2
  action      = "block"
  filters     = ["dns"]
  traffic     = "any(dns.domains[*] == \"example.com\") && dns.location in {\"${data.cloudflare_teams_location.office.id}\"}"
  rule_settings {
    block_page_enabled = true
    block_page_reason = "access not permitted"
  }
}
```

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_location
https://developers.cloudflare.com/cloudflare-one/policies/filtering/dns-policies/#location

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
