### ISSUE TITLE
Create Workers with service bindings

### ISSUE THREAD

**Issue by taliaferro** [cloudflare/terraform-provider-cloudflare#1696]
### Current Terraform and Cloudflare provider version

```
Terraform v1.2.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.16.0
```

### Description

Workers can be bound to other workers using the [service binding](https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/) mechanism. Terraform ought to be able to create Workers with these bindings too. 

### Use cases

The end goal would be to use Terraform to orchestrate a sort of service mesh architecture, made up of small, composable microservices.

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "auth" {
  name    = auth
  content = file("auth_service.js")
}

resource "cloudflare_worker_script" "api" {
  name    = "api"
  content = file("api.js")
  service_binding {
    name            = "AUTH_SERVICE"
    bound_worker_id = cloudflare_worker_script.auth.id
  }
}
```

### References

I'm sure this'll get tagged with `pending-upstream-library`, since this functionality doesn't exist in `cloudflare-go` yet, so I've created [an issue in the cloudflare-go project](https://github.com/cloudflare/cloudflare-go/issues/929) too.

**Comment by sodabrew** [comment]
Begins to be unblocked by #1728!
