### ISSUE TITLE
resource_cloudflare_record search mismatch when allow_overwrite=true

### ISSUE THREAD

**Issue by 1oglop1** [cloudflare/terraform-provider-cloudflare#1710]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

cloudflare 3.15.0

### Affected resource(s)

* resource_cloudflare_record

### Terraform configuration files

```hcl
locals {
  fqdn = "value.domain.com."
}

# the first record is created
resource "record" resource_cloudflare_record {
  name=local.fqdn
  allow_overwrite=true
  type="A"
}

# the second record fails with the message
# attempted to override existing record however didn't find an exact match
resource "record" resource_cloudflare_record {
  name=local.fqdn
  allow_overwrite=true
  type="A"
}
```

### Debug output

See line 5629:   
* original certificate requested: `*.testtest.perium.nl`  
* domain created by ACM certificate resource `_795c354dbbac980dbca68aae23851205.testtest.perium.nl.`
* domain lookup by Clouldflare provider: `_795c354dbbac980dbca68aae23851205.testtest.perium.nl..perium.nl`

```
I0714 08:36:46.389837   31336 eventsink.go:59] GET /client/v4/zones/5cca90f59df588c7b60c9c30009e668c/dns_records?name=_795c354dbbac980dbca68aae23851205.testtest.perium.nl..perium.nl&page=1&type=CNAME HTTP/1.1
```

[tflog.Debug](https://github.com/cloudflare/terraform-provider-cloudflare/files/9109270/out.txt)

https://github.com/cloudflare/terraform-provider-cloudflare/blob/390201e830bc6b4a9ab41210a87734464ff3dbc1/internal/provider/resource_cloudflare_record.go#L140-L143

### Expected output

both resources created

### Actual output

error message: `attempted to override existing record however didn't find an exact match`

### Steps to reproduce

1. Create 2 Record resources and use `FQDN` as a name
2. add `allow_overwrite` flag
3. terraform apply 
4. observe that the 1st record is created while the 2nd one produces an error

### Additional factoids

I'm using pulumi bridge provider https://github.com/pulumi/pulumi-cloudflare version 4.7.0 with TF provider version 3.15.0 however the bug is present in current `master` branch.

I believe that this piece of code is responsible for the problem.

https://github.com/cloudflare/terraform-provider-cloudflare/blob/390201e830bc6b4a9ab41210a87734464ff3dbc1/internal/provider/resource_cloudflare_record.go#L134-L136

Namely line 135 `Name: d.Get("name").(string) + "." + zone.Name` which appends `zone.Name` to the `name` argument.
Given:
zone: `example.com`
record: `www.example.com`
The code will produce a malformed string `example.com.www.example.com` causing the mismatch.

I found out about this problem when creating ACM certificate resource.
ACM Certificate resource outputs a `CertificateOptions` which contains the attribute 'resource_record_name', that is FQDN eg. '_ca595e19a694c3bf2dfa20123456.example.com.' 

### References

#pulumi/pulumi-cloudflare/issues/264

**Comment by 1oglop1** [comment]
@jacobbednarz Could you please remove the `needs-information` label - I believe I provided enough information in case there is anything missing, please let me know.

**Comment by jacobbednarz** [comment]
looks like we're still missing the `TF_LOG=DEBUG` output from the command. irrespective of what you think is enough context, it is requested to confirm the internals and API calls so if you can provide that, we can have a look into the issue.

**Comment by 1oglop1** [comment]
@jacobbednarz I updated the issue and attached the TF log file.

**Comment by jacobbednarz** [comment]
is the trailing period for the domain variable intentional? a cursory look at the debug logs suggests you're hitting this because the values (name and API zone name) don't match resulting in this code path. removing the trailing period should address this (also, you can use `@` instead here too).

**Comment by si-c613** [comment]
Had a look at this cause I was having the same issue and I believe this should be a bug rather than support.
The issue lies in https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_record.go#L132-L142
It detects if the `name` is either `@` or matches the `zone.name`, if so then it uses the `zone.name` which is all fine.
If the above is not true then the request is made using `d.Get("name").(string) + "." + zone.Name` but `name` could be partial (i.e. `subdomain`) in which case this makes sense, or it could contain the `zone.Name` (i.e. `subdomain.example.com`).

I think there needs to be an `else if` in that block to detect if the `zone.name` is contained in the `name` and possibly also remove any trailing `.`

**Comment by jacobbednarz** [comment]
i don't want to extend the allow overwrite functionality any further as it is already a pretty decent sized foot gun. 

if you're attempting to use a subdomain in DNS records, you want to only include the subdomain as part of the `name` value. i.e. `name = "www`". this should make the functionality here work as expected without yet another code path to evaluate.
