### ISSUE TITLE
Why deprecating `account_id` on the provider?

### ISSUE THREAD

**Issue by lra** [cloudflare/terraform-provider-cloudflare#1716]
### Current Terraform and Cloudflare provider version

Terraform v1.2.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.17.0

### Description

In a recent version, the provider marked `account_id` as being deprecated:
> `[account_id](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#account_id) (String, Deprecated) Configure API client to always use a specific account. Alternatively, can be configured using the CLOUDFLARE_ACCOUNT_ID environment variable.`

But when I remove it from the provider, my resources (e.g. `cloudflare_account_member`) is complaining that no account id is set:
```
│ Error: account ID is empty and must be provided
│ 
│   with cloudflare_account_member.platform_infra_team_members["XXXXXX"],
│   on users.tf line 158, in resource "cloudflare_account_member" "platform_infra_team_members":
│  158: resource "cloudflare_account_member" "platform_infra_team_members" {
│ 
```

And there is no way to set the account id on the `cloudflare_account_member` resource:

```
╷
│ Error: Unsupported argument
│ 
│   on users.tf line 135, in resource "cloudflare_account_member" "owners":
│  135:   account_id    = local.account_id
│ 
│ An argument named "account_id" is not expected here.
```

### Use cases

Enforce the account ID of the cloudflare provider in a terraform workspace.

### Potential Terraform configuration

```hcl
provider "cloudflare" {
  account_id = "XXX"
}

resource "cloudflare_account_member" "example_user" {
  email_address = "user@example.com"
  role_ids = [
    "68b329da9893e34099c7d8ad5cb9c940",
    "d784fa8b6d98d27699781bd9a7cf19f0"
  ]
}
```

**Comment by jacobbednarz** [comment]
this configuration sets the account value for all API calls and breaks partners and tentant usage. 

resources will be adding more support the closer we get to 4.x

**Comment by lra** [comment]
I don't understand. How are we supposed to remove the deprecated warning?

**Comment by javierlopez-itech** [comment]
Plus one to adding `account_id` to `cloudflare_account_member`, there is no way to get around this deprecation. Also, seems like most resources are has an `account_id` attribute, so would be more consistent with the rest of the API.

**Comment by jcolfej** [comment]
The problem also occurs for `cloudflare_access_rule` when you want to make a rule that applies to the account.

**Comment by peterh-lon** [comment]
yeah cloudflare_load_balancer_monitor is the same, documentation is not updated either anywhere

**Comment by morey-tech** [comment]
> The problem also occurs for `cloudflare_access_rule` when you want to make a rule that applies to the account.

I am also affected by this. I was looking to transition from using `account_id` on the provider to on the `cloudflare_access_rules` but there isn't support for it yet.

This deprecation notice was implemented way too early. There should be an upgrade path in place if warnings are thrown for it.

**Comment by avaranze** [comment]
Also getting a warning for `cloudflare_argo_tunnel`.  Both issues related to this are closed without being fixed.

**Comment by matt-byrne** [comment]
Why would you ever mark a feature as deprecated without first providing an alternative? Baffling.

**Comment by gtirloni** [comment]
Hopefully a useful link for anyone searching for the deprecation warning on Google, check this issue instead: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1646

**Comment by lra** [comment]
3 months later, we still have no way to get rid of the warning on every plan and apply.
