### ISSUE TITLE
cloudflare_record values as array, not as string

### ISSUE THREAD

**Issue by Savemech** [cloudflare/terraform-provider-cloudflare#1741]
### Current Terraform and Cloudflare provider version

latest

### Description

Right now there is now convenient way to add multiple values in one resource

### Use cases

you're not multiplying resources like doing right now to work with this provider

notice that  `  name    = "resource-name"` are same
```hcl
resource "cloudflare_record" "resource-name-01" {
  zone_id = var.cloudflare_zone_id
  name    = "resource-name"
  value   = 127.0.0.1
  proxied = false
  type    = "A"
  ttl     = 120
} 

resource "cloudflare_record" "resource-name-02" {
  zone_id = var.cloudflare_zone_id
  name    = "resource-name"
  value   = 127.0.0.2
  proxied = false
  type    = "A"
  ttl     = 120
} 
```

### Potential Terraform configuration

```hcl
resource "cloudflare_record" "resource-name" {
  zone_id = var.cloudflare_zone_id
  name    = "resource-name"
  value   = ["127.0.0.1", "127.0.0.2"]
  proxied = false
  type    = "A"
  ttl     = 120
} 

```

### References

there is little to none how achieve multiple ip's for same A record 😿 
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record

**Comment by jacobbednarz** [comment]
thanks for the request! however, as this isn't supported in our API, we won't be able to add it here. 

if you have an account team, i'd recommend opening a feature request to have this tracked with the service team for consideration.
