### ISSUE TITLE
Allow configuring Splunk index

### ISSUE THREAD

**Issue by marcuscraske** [cloudflare/terraform-provider-cloudflare#1751]
### Current Terraform and Cloudflare provider version

Terraform v1.2.4

### Description

In large Enterprise/corporate environments, it can be desirable to use the same token for multiple indexes on Splunk.

Vendors/services typically offer the ability to specify/override the default index of a token e.g. Sysdig, Fastly (competitor) etc.

There's already an option to configure `sourcetype`, but could you provide `index` as an option in the `destination_conf`?

https://developers.cloudflare.com/logs/get-started/enable-destinations/splunk/

In the JSON event sent to the Splunk HEC, you just have to provide `index` as a field. So it would just be the case of taking the value from the `destination_conf` and putting it in the JSON event sent to Splunk.

### Use cases

* Enterprise - large-scale deployments with multiple indexes with different settings (such as data retention for legal and compliance purposes)
* Already provided by competitors (Fastly)
* Standard configuration option for Splunk on vendor products

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_job" "splunk" {
    destination_conf = "splunk://1.2.3.4:443/services/collector/raw?channel=<uuid>&insecure-skip-verify=true&sourcetype=cloudflare&header_Authorization=Splunk%201234&index=custom-index-here"
}

```

**Comment by jacobbednarz** [comment]
we don't do any validation on this field so your best bet is to lodge a support ticket to get this added as a feature request to the service itself and then configure it in Terraform.

**Comment by jacobbednarz** [comment]
have you tried supplying it as a parameter and seeing if it works as is? if not, it will need to be a feature request to the service team.

**Comment by marcuscraske** [comment]
Yes, unfortunately it's not working.

I will relay your message on the support ticket, cheers 👌
