### ISSUE TITLE
Plugin terraform-provider-cloudflare_v3.17.0 plugin crash

### ISSUE THREAD

**Issue by gathecageorge** [cloudflare/terraform-provider-cloudflare#1764]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.3
on darwin_amd64

terraform-provider-cloudflare_v3.17.0

### Affected resource(s)

cloudflare_access_policy
cloudflare_record
cloudflare_access_application

### Terraform configuration files

```hcl
# The random_id resource is used to generate a 35 character secret for the tunnel
resource "random_id" "tunnel_secret" {
  byte_length = 35
}

# A Named Tunnel resource called zero_trust_ssh_http
resource "cloudflare_argo_tunnel" "auto_tunnel" {
  account_id = var.cloudflare_account_id
  name       = "zero_trust_ssh_http"
  secret     = random_id.tunnel_secret.b64_std
}

# Access application to apply zero trust policy over SSH endpoint
resource "cloudflare_access_application" "ssh_app" {
  zone_id          = var.cloudflare_domain_id
  name             = "Bastion SSH TEST2"
  domain           = "${var.cloudflare_subdomain}.${var.cloudflare_domain}"
  session_duration = "1h"
}

# Access policy that the above appplication uses. (i.e. who is allowed in)
resource "cloudflare_access_policy" "ssh_policy" {
  application_id = cloudflare_access_application.ssh_app.id
  zone_id        = var.cloudflare_domain_id
  name           = "Allow github Organization"
  precedence     = "1"
  decision       = "allow"

  include {
    github {
      name = "XXXX"
    }
  }
}

# DNS settings to CNAME to tunnel target for SSH
resource "cloudflare_record" "ssh_dns" {
  zone_id = var.cloudflare_domain_id
  name    = "${var.cloudflare_subdomain}"
  value   = "${cloudflare_argo_tunnel.auto_tunnel.id}.cfargotunnel.com"
  type    = "CNAME"
  proxied = true
}
```

### Debug output

[Error.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/9092965/Error.txt)

### Expected output

expected to modify resources correctly

### Actual output

Plugin crashed, see debug information

### Steps to reproduce

Just run terraform apply

Company project https://github.com/CryptoManufaktur-io/ssh-setup

**Comment by gathecageorge** [comment]
Have provided the log file already as attachment since its too big for pasting content

**Comment by jacobbednarz** [comment]
side note: instead of manually building the tunnel CNAME, there is an [exposed attribute](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/argo_tunnel#cname) you can use .

```diff
 resource "cloudflare_record" "ssh_dns" {
   zone_id = var.cloudflare_domain_id
   name    = "${var.cloudflare_subdomain}"
+  value   = cloudflare_argo_tunnel.auto_tunnel.cname
-  value   = "${cloudflare_argo_tunnel.auto_tunnel.id}.cfargotunnel.com"
   type    = "CNAME"
   proxied = true 
 }
```

i'll have to have a look at the crash but suspect it may be related to #1075 or one of the other Access issues with custom IdPs.

**Comment by jacobbednarz** [comment]
@gathecageorge is this still happening? there were some improvements in the last couple of releases that may have inadvertently fixed this.

**Comment by jacobbednarz** [comment]
closing due to lack of response. if this is still an issue, please open a new issue replicating on the latest version of the provider.
