### ISSUE TITLE
terraform validate should not require an api_key

### ISSUE THREAD

**Issue by lra** [cloudflare/terraform-provider-cloudflare#1769]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.19.0
```

### Affected resource(s)

the cloudflare provider

### Terraform configuration files

```hcl
provider "cloudflare" {}
```

### Debug output

n/a

### Expected output

```
Success! The configuration is valid.
```

### Actual output

```
│Error: Invalid combination of arguments
│
│  with provider["registry.terraform.io/cloudflare/cloudflare"],
│  on versions.tf line 11, in provider "cloudflare":
│  11: provider "cloudflare" {
│
│"api_key": one of `api_key,api_token` must be specified
```

### Steps to reproduce

1. Define the cloudflare provider with any env var and api key
2. Run `terraform validate`

### Additional factoids

Terraform validate is used to check the syntax of terraform files, and should not require an api key or token to run. It was not the case until v3.19.0 and it's not the case for all the other providers that we use.

**Comment by jacobbednarz** [comment]
thanks for the issue but I'm afraid the validation is here to stay for now. it is intentionally cleaning up use cases where people are providing incorrect or mismatching credentials resulting in hard to diagnose issues with their setups. 

if you'd like to noop the validate, you can provide fake credentials either in the provider block or via the environment variables for the keys.

**Comment by lra** [comment]
This is the only provider with this behavior, and we use a lot.
We had to do a special case just for cloudflare so I'm betting this behavior will lead to more new issues open than you hope to prevent.

**Comment by zmully** [comment]
:wave: So I have the same issue with `validate`, but for a different reason.

Per the docs, `api_key` is deprecated, and `api_token` should be used instead (https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs), but validate fails even if I've specified the provider as documented:

```
    new cloudflare.CloudflareProvider(this, "cf", {
      email: Fn.lookup(Fn.jsondecode(cfToken.secretString), "email", ""),
      apiToken: Fn.lookup(Fn.jsondecode(cfToken.secretString), "token", "")
    });
```

When I validate this, I get:

```
Error: Missing required argument
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on cdk.tf.json line 115, in provider.cloudflare[0]:
│  115:         "email": "${lookup(jsondecode(data.aws_secretsmanager_secret_version.token.secret_string), \"email\", \"\")}"
│ 
│ "email": all of `api_key,email` must be specified

```

My TF synthesizes and applies fine, but validation is broken in 3.19

```
Initializing provider plugins...
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of hashicorp/aws from the dependency lock file
- Reusing previous version of cloudflare/cloudflare from the dependency lock file
- Using previously-installed hashicorp/random v3.3.2
- Using previously-installed hashicorp/aws v4.20.0
- Using previously-installed cloudflare/cloudflare v3.19.0
```

**Comment by jacobbednarz** [comment]
see #1768
