### ISSUE TITLE
support configurations with both "api_key" and "api_token" specified ( ideally with token having higher priority )

### ISSUE THREAD

**Issue by contil** [cloudflare/terraform-provider-cloudflare#1770]
### Current Terraform and Cloudflare provider version

tf ver 1.14
cloudflare provider 3.19

### Description

This problem is not present with tf provider 3.18.0
With cloudflare provider 3.19.0 our terraform box with both ENV vars "CLOUDFLARE_API_TOKEN" and "CLOUDFLARE_API_KEY" results in a plan error
`
provider "cloudflare" {
 "api_key": only one of "api_key,api_token" can be specified, but
 "api_key,api_token" were specified.
`

### Use cases

In our setup this is a problem because we support many combinations of provider and tf executable. Could we turn this hard error in a behaviour where if the token is specified and the key is present we get a warning but the token will only be considered?

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
duplicates #1769
