### ISSUE TITLE
Not able to use ENV VAR credentials anymore

### ISSUE THREAD

**Issue by dersoi** [cloudflare/terraform-provider-cloudflare#1774]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ terraform --version
Terraform v1.1.4
on linux_amd64

### Affected resource(s)

All resources 

### Terraform configuration files

```hcl
locals {
  dns_entries = csvdecode(file(var.dns_file))
}

resource "cloudflare_record" "dns_entry" {

  for_each = { for r in local.dns_entries : format("%s%s%s", r.name, r.type, r.content) => r }
  name     = each.value.name
  type     = each.value.type
  value    = each.value.content
  priority = each.value.type == "MX" ? 0 : null
  proxied  = each.value.proxied
  ttl      = each.value.ttl
  zone_id  = var.zone_id
}


Csv: 
name,type,content,ttl,proxied
```

### Debug output

2022-07-15T11:13:15.972+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-07-15T11:13:15.978+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/aws/3.75.2/darwin_arm64/terraform-provider-aws_v3.75.2_x5 pid=54452
2022-07-15T11:13:15.978+0200 [DEBUG] provider: plugin exited
2022-07-15T11:13:16.192+0200 [INFO]  backend/local: plan operation completed
╷
│ Warning: Argument is deprecated
│ 
│   with aws_s3_bucket.terraform_state,
│   on backend.tf line 5, in resource "aws_s3_bucket" "terraform_state":
│    5: resource "aws_s3_bucket" "terraform_state" {
│ 
│ Use the aws_s3_bucket_server_side_encryption_configuration resource instead
│ 
│ (and 3 more similar warnings elsewhere)
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on backend.tf line 64, in provider "cloudflare":
│   64: provider "cloudflare" {
│ 
│ "email": all of `api_key,email` must be specified
╵

### Expected output

Plan: 10 to add, 0 to change, 0 to destroy.

### Actual output

│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on backend.tf line 64, in provider "cloudflare":
│   64: provider "cloudflare" {
│ 
│ "email": all of `api_key,email` must be specified

### Steps to reproduce

1. Set credentials with env var (CLOUDFLARE_API_TOKEN, CLOUDFLARE_EMAIL)
2. Terraform init
3. Terraform plan

### Additional factoids

Happens only on the latest version (3.19). Works fine on 3.18

**Comment by dersoi** [comment]
Updated Debug output

**Comment by jacobbednarz** [comment]
see #1768

**Comment by dersoi** [comment]
Thanks @jacobbednarz Forgot to check on the closed issues... Sorry about that
