### ISSUE TITLE
Support for wasm attachments to Cloudflare Workers

### ISSUE THREAD

**Issue by chrisdickinson** [cloudflare/terraform-provider-cloudflare#178]
Hi! I'm looking into attaching a WASM module to my Cloudflare Worker, but I don't see support for it in the documentation. It looks like the functionality piggybacks on the [script upload](https://developers.cloudflare.com/workers/api/resource-bindings/webassembly-modules/) API endpoint.

I was wondering: are there plans to bring this functionality into the terraform cloudflare provider? (Would it be hard to do so?) No worries at all if support isn't planned for the time being! (I'd offer to help implement, but I'm barely conversant in Go — apologies!) Thanks for your work!

**Comment by jacobbednarz** [comment]
👋 WASM modules aren't something that we're actively using so it isn't currently on any to-do list I'm looking at. In saying that though, we're almost approaching the point where we would have complete Terraform coverage for what we do need so I might have some time to take a look at it.

Before it lands in Terraform, we'd need to get it added to [`cloudflare/cloudflare-go`](https://github.com/cloudflare/cloudflare-go) which underpins the Terraform provider. Shouldn't be a huge task but just something worth noting.

**Comment by cpick** [comment]
It looks like the necessary work may be ongoing in https://github.com/cloudflare/cloudflare-go/issues/313 (and its associated [PR](https://github.com/cloudflare/cloudflare-go/issues/313)).

**Comment by adampointer-form3** [comment]
Yes as soon as that cloudflare-go PR is merged in I am ready to implement this. It is taking a while to get merged, however.

**Comment by cpick** [comment]
It looks like the above cloudflare-go issue was resolved!
Does it seem reasonable to add support wasm-attachment support using that functionality?

**Comment by ldesgoui** [comment]
Will look at implementing this, feel free to ping me if nothing comes of it.

**Comment by jacobbednarz** [comment]
Happy to review a PR for this if you'd like to implement.
