### ISSUE TITLE
Configure HTTP Strict Transport Security (HSTS) via terraform

### ISSUE THREAD

**Issue by timofii-orlov-swi** [cloudflare/terraform-provider-cloudflare#1782]
### Current Terraform and Cloudflare provider version

terraform -v
Terraform v1.0.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.19.0
+ provider registry.terraform.io/hashicorp/aws v4.22.0

### Description

Can you add configuration HTTP Strict Transport Security (HSTS) via terraform?

### Use cases

Use HTTP Strict Transport Security (HSTS) via terraform

### Potential Terraform configuration

...

**Comment by jacobbednarz** [comment]
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#security_header
