### ISSUE TITLE
Cloudflare provider account_id deprecation resolution

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1791]
### Current Terraform and Cloudflare provider version

Terraform v1.2.3
on darwin_amd64

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "= 3.16.0"
    }
  }
}
```

### Description

In `3.17.0` the Cloudflare provider block has an `account_id` variable that was used to limit the resources that got created to a specific account. The documentation states states that the API key / token should be used to limit resources to a single account.

**This doesn't address the use case of having a single terraform configuration configure resources to multiple accounts.**

Currently we have the following set up:
- I have a terraform Cloudflare provider block for each account with an alias
- I have a terraform module that instantiates all the resources for each of the accounts
    - I create a module for each account and pass in the provider with the alias for each of the modules. (each module corresponds to an account).

### Use cases

Have a single terraform configuration deploy resources to multiple accounts.

### Potential Terraform configuration

I don't mind if the `account_id` variable is deprecated as long as a single terraform configuration can deploy resources to multiple accounts

```hcl
provider "cloudflare" {
  alias = "dev"
  account_id = "<account-id>"
}
```

**Comment by istvanfedak** [comment]
The only workaround I see is to create an API token for each account and use the [api_token](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#api_token) Cloudflare provider variable to limit the access to a specific account.

**Comment by jacobbednarz** [comment]
that is exactly what i would recommend doing 👍 the change to remove `account_id` from the provider block should make your setup more explicit and concurrency safe. i'm not sure if you've tested it but right now, it's possible to have two configurations consistently reset the `client.AccountID` value and get unexpected results. taking the approach where you define explicit account IDs on resources fixes this.

closing off as there isn't anything to action from my side but happy to keep conversing about solutions/issues here if you need more.
