### ISSUE TITLE
`cloudflare_fallback_domain` shows perpetual changes to apply

### ISSUE THREAD

**Issue by tjstansell** [cloudflare/terraform-provider-cloudflare#1802]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform version v1.2.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.19.0
+ provider registry.terraform.io/hashicorp/aws v4.23.0
```

### Affected resource(s)

* `cloudflare_fallback_domain`

### Terraform configuration files

```hcl
locals {
  default_domains  = ["intranet", "internal", "private", "localdomain", "domain", "lan", "home", "host", "corp", "local", "localhost", "home.arpa", "invalid", "test"]
  internal_domains = ["10.in-addr.arpa", "mydomain.net", "mydomain.com"]
  dns_servers      = ["10.1.1.1", "10.1.1.2"]
}

resource "cloudflare_fallback_domain" "this" {
  account_id = local.account_id

  dynamic "domains" {
    for_each = local.default_domains
    content {
      suffix = domains.value
    }
  }
  dynamic "domains" {
    for_each = local.internal_domains
    content {
      suffix     = domains.value
      dns_server = local.dns_servers
    }
  }
}
```

### Debug output

I'm not including the full debug output here because most of it is irrelevant.
```
  # cloudflare_fallback_domain.this will be updated in-place
  ~ resource "cloudflare_fallback_domain" "this" {
        id         = "<redacted>"
        # (1 unchanged attribute hidden)

      ~ domains {
          ~ dns_server = [
              - "10.1.1.1",
              - "10.1.1.2",
            ]
          ~ suffix     = "10.in-addr.arpa" -> "intranet"
        }
      ~ domains {
          ~ dns_server = [
              - "10.1.1.1",
              - "10.1.1.2",
            ]
          ~ suffix     = "mydomain.com" -> "internal"
        }
      ~ domains {
          ~ suffix     = "home.arpa" -> "private"
            # (1 unchanged attribute hidden)
        }
      ~ domains {
          ~ dns_server = [
              - "10.1.1.1",
              - "10.1.1.2",
            ]
          ~ suffix     = "mydomain.net" -> "localdomain"
        }
      ~ domains {
          ~ suffix     = "intranet" -> "domain"
            # (1 unchanged attribute hidden)
        }
      ~ domains {
          ~ suffix     = "internal" -> "lan"
            # (1 unchanged attribute hidden)
        }
      ~ domains {
          ~ suffix     = "private" -> "home"
            # (1 unchanged attribute hidden)
        }
        ...
```
you get the idea ... basically, the response from the API is not in the exact same order as what's defined in terraform, so it thinks the whole set is changing.

### Expected output

The plan should show no changes to apply after applying changes.

### Actual output

The plan shows the `cloudflare_fallback_domain` resource still requiring changes to apply.

### Steps to reproduce

1. create a `cloudflare_fallback_domain` resource
2. apply changes
3. plan shows changes still pending

**Comment by vavsab** [comment]
A test that shows that Cloudflare API does not preserve the order. Terraform package is using [`TypeList`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/5200bb88bd2533aa6176213f7ad865447084ca27/internal/provider/schema_cloudflare_fallback_domain.go#L16) but in this case it's better to use `TypeSet`
![image](https://user-images.githubusercontent.com/10233442/183643550-16539be7-a877-4e4d-8288-b4c771b2c937.png)
