### ISSUE TITLE
Update 3.18.0 -> 3.20.0 breakes with undocumented breaking change

### ISSUE THREAD

**Issue by JanoschDeurer** [cloudflare/terraform-provider-cloudflare#1807]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

3.18.0 -> 3.20.0

### Affected resource(s)

provider configuration

### Terraform configuration files

```hcl
provider "cloudflare" {
  email     = var.cloudflare_email
  api_token = var.cloudflare_api_token
}
```

### Debug output

```shell
$ terraform validate
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on providers.tf line 30, in provider "cloudflare":
│   30:   email     = var.cloudflare_email
│ 
│ "email": all of `api_key,email` must be specified
```

### Expected output

At most a warning, that this is deprecated.

### Actual output

```shell
$ terraform validate
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on providers.tf line 30, in provider "cloudflare":
│   30:   email     = var.cloudflare_email
│ 
│ "email": all of `api_key,email` must be specified
```

### Steps to reproduce

1. Specify provider as given above
2. User provider version 3.20.0
3. Run `terraform init`
4. Run `terraform validate`

### Additional factoids

It is documented in the current docs that `api_token` conflicts with `email`. However this was only added recently and it should be part of the breaking changes in the release note.

Apart from that I think that there should be no breaking changes in minor versions. As you do not comply with semantic versioning, can anybody tell me what kind of versioning system is used? It would be also helpful to have that as part of the documentation, so people can configure there auto update tools accordingly.

**Comment by JanoschDeurer** [comment]
The debug output is so not relevant for this bug.

**Comment by jacobbednarz** [comment]
see #1768
