### ISSUE TITLE
resource/cloudflare_ruleset: consistently NOT sorting transformation headers

### ISSUE THREAD

**Issue by ddulic** [cloudflare/terraform-provider-cloudflare#1811]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Running in pipeline, always pulls the latest version.

```
Installed cloudflare/cloudflare v3.20.0 (signed by a HashiCorp partner, key ID DE413CEC881C3283)
```

### Affected resource(s)

`cloudflare_ruleset`

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "transform_uri_remove_headers" {
  zone_id     = "zone_id"
  name        = "Transform rule for removing HTTP Headers"
  description = "Remove Headers before reaching client"
  kind        = "zone"
  phase       = "http_response_headers_transform"
  rules {
    action = "rewrite"
    action_parameters {
      headers {
        name      = "header1"
        operation = "remove"
      }
      headers {
        name      = "header2"
        operation = "remove"
      }
      headers {
        name      = "header3"
        operation = "remove"
      }
      headers {
        name      = "header4"
        operation = "remove"
      }
    }

    expression  = "true"
    description = "Remove Headers"
    enabled     = true
  }
}
```

### Debug output

Have to get clearance, will provide this in a few days.

### Expected output

I expect there to be no change in the plan and apply.

### Actual output

`terraform plan`
```
  # cloudflare_ruleset.transform_uri_remove_headers will be updated in-place
  ~ resource "cloudflare_ruleset" "transform_uri_remove_headers" {
        id          = "48e991bdd540407bbaaa33352896123a"
        name        = "Transform rule for removing HTTP Headers"
        # (4 unchanged attributes hidden)

      ~ rules {
            id          = "9d895526018d4c7087d151cb166dd8a6"
            # (4 unchanged attributes hidden)

          ~ action_parameters {
                # (11 unchanged attributes hidden)

              ~ headers {
                  ~ name      = "header4" -> "header1"
                    # (1 unchanged attribute hidden)
                }
              ~ headers {
                  ~ name      = "header1" -> "header2"
                    # (1 unchanged attribute hidden)
                }
              ~ headers {
                  ~ name      = "header3" -> "header4"
                    # (1 unchanged attribute hidden)
                }
                # (1 unchanged block hidden)
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

`terraform apply`
```
cloudflare_ruleset.transform_uri_remove_headers: Modifying... [id=48e991bdd540407bbaaa33352896123a]
cloudflare_ruleset.transform_uri_remove_headers: Modifications complete after 0s [id=48e991bdd540407bbaaa33352896123a]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed
```
```

### Steps to reproduce

1. Add provider resource block
2. Run tf plan and apply
3. Subsequent tf plan shows same changes pending

### Additional factoids

_No response_

### References

_No response_

**Comment by ddulic** [comment]
Apologies, I am unable to provide a debug log. There are too many items to redact, it isn't just the auth information...

**Comment by jacobbednarz** [comment]
without debug logs, i'm afraid there is little i can do here to dig into the issue. in addition, the transform headers has test coverage which should surface this problem if it exists - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_ruleset_test.go#L1028-L1076

i would recommend either 1) digging into this further yourself and sending a PR once you can replicate and track down the issue or 2) start with a fresh example (like the one from the linked test case above) and replicate using that to not use your specific environment.

i'm closing this one off since there isn't anything for me to action here but if you manage to achieve one of the above, please feel free to raise a new issue/PR and we can go from there.
