### ISSUE TITLE
Error: error creating zone "test-abc.dev.test.com": Partial zone signup not allowed (1104)

### ISSUE THREAD

**Issue by istvanfedak** [cloudflare/terraform-provider-cloudflare#1812]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.1.7
on darwin_amd64

```hcl
cloudflare = {
  source  = "cloudflare/cloudflare"
  version = "= 3.16.0"
}
```

### Affected resource(s)

- cloudflare_zone

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "= 3.16.0"
    }
  }
}

variable "cloudflare_api_token" {
  description = "The API token for account"
  type        = string
  sensitive   = true
}

provider "cloudflare" {
  alias     = "sandbox"
  api_token = var.cloudflare_api_token
}

resource "cloudflare_zone" "example" {
    zone = "example.com"
    type = "partial"
    plan = "enterprise"
}
```

### Debug output

module.waf-terraform-core.module.cloudflare.module.zone["test-abc.dev.test.com"].cloudflare_zone.this: Creating...
╷
│ Error: error creating zone "test-abc.dev.test.com": Partial zone signup not allowed (1104)
│ 
│   with module.waf-terraform-core.module.cloudflare.module.zone["test-abc.dev.test.com"].cloudflare_zone.this,
│   on .terraform/modules/waf-terraform-core/modules/cloudflare/modules/zone/main.tf line 1, in resource "cloudflare_zone" "this":
│    1: resource "cloudflare_zone" "this" {
│ 
╵

### Expected output

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual output

module.waf-terraform-core.module.cloudflare.module.zone["test-abc.dev.test.com"].cloudflare_zone.this: Creating...
╷
│ Error: error creating zone "test-abc.dev.test.com": Partial zone signup not allowed (1104)
│ 
│   with module.waf-terraform-core.module.cloudflare.module.zone["test-abc.dev.test.com"].cloudflare_zone.this,
│   on .terraform/modules/waf-terraform-core/modules/cloudflare/modules/zone/main.tf line 1, in resource "cloudflare_zone" "this":
│    1: resource "cloudflare_zone" "this" {
│ 
╵

### Steps to reproduce

1. terraform init
2. terraform plan
3. terraform apply

**Comment by istvanfedak** [comment]
I validated that the token had enough permissions to create the zone using the API:
- POST {{base_url}}/client/v4/zones
- PATCH {{base_url}}/client/v4/zones/{{zone_id}}

**Comment by jacobbednarz** [comment]
this is an entitlement restriction and not something controlled in the provider. I'd recommend getting in touch with your account team to check the entitlement or make sure you are providing the correct account details for the zone creation.

**Comment by istvanfedak** [comment]
Its strange that I can use the token to create resources via the API but when I use it in the Terraform provider it fails.

**Comment by jacobbednarz** [comment]
you can compare the HTTP requests made by the provider to work out what differences are present. past experience would suggest missing the correct account ID on the request where the entitlement is assigned.
