### ISSUE TITLE
cloudflare_page_rule cache_ttl_by_status=-1 error

### ISSUE THREAD

**Issue by mihaiturcu** [cloudflare/terraform-provider-cloudflare#1818]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

resource "cloudflare_page_rule" "some_resource" {
  priority = 24
  target   = "something.random.com/*"
  actions {
    cache_by_device_type   = "on"
    cache_level            = "cache_everything"

    cache_ttl_by_status {
      codes = "200-299"
      ttl = 31536000
    }
    cache_ttl_by_status {
      codes = "300-399"
      ttl = -1
    }
  }
  zone_id = var.zone_id
}

### Affected resource(s)

cloudflare_page_rule

### Terraform configuration files

```hcl
resource "cloudflare_page_rule" "some_resource" {
  priority = 24
  target   = "something.random.com/*"
  actions {
    cache_by_device_type   = "on"
    cache_level            = "cache_everything"

    cache_ttl_by_status {
      codes = "200-299"
      ttl = 31536000
    }
    cache_ttl_by_status {
      codes = "300-399"
      ttl = -1
    }
  }
  zone_id = var.zone_id
}
```

### Debug output

-- can pull it if needed, looks like an inconsistency per Cloudflare developer docs 

### Expected output

rule gets created

### Actual output

```
│ Error: failed to update Cloudflare Page Rule: Page Rule validation failed: See messages for details. (1004)
│ 
│   with cloudflare_page_rule.some_resource,
│   on cloudflare_page_rule.tf line 271, in resource "cloudflare_page_rule" "some_resource":
│  271: resource "cloudflare_page_rule" "some_resource" {
```

### Steps to reproduce

sample code above

### Additional factoids

Terraform docs look inconsistent to Cloudflare docs:
https://developers.cloudflare.com/cache/how-to/configure-cache-status-code/

Per docs
TTL: An integer that defines the duration an asset is valid in seconds or one of the following strings: no-store, no-cache. Only positive integers, including 0, are accepted.

Technically there's no way to do -1 per above.

**Comment by jacobbednarz** [comment]
this isn't a bug but an enhancement; we just don't have strict validation the schema.

**Comment by jacobbednarz** [comment]
closing this one out as we're unlikely to spend any more time improving page rules given cache rules are now available that replace this functionality and already supported in the `cloudflare_rulesets` resource.
