### ISSUE TITLE
add ability in `cloudflare_access_application` to set the browser rendering setting for zero trust application settings.

### ISSUE THREAD

**Issue by g-bolmida** [cloudflare/terraform-provider-cloudflare#1833]
### Current Terraform and Cloudflare provider version

```
Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.21.0
```

### Description

Add the ability to change the browser rendering configuration in the Cloudflare Zero Trust application settings with the Terraform provider under the `cloudflare_access_application` resource.

### Use cases

It would be nice to be able to set an applications browser rendering settings via Terraform instead of doing it manually in the UI.

### Potential Terraform configuration

```hcl
resource "cloudflare_access_application" "staging_app" {
  zone_id                   = "0da42c8d2132a9ddaf714f9e7c920711"
  name                      = "staging application"
  domain                    = "staging.example.com"
  type                      = "self_hosted"
  session_duration          = "24h"
  auto_redirect_to_identity = false
  # new configuration option
  browser_rendering         = "ssh"
}



### References

_No response_

**Comment by g-bolmida** [comment]
@jacobbednarz Do you have any insight into when this could potentially be implemented into the Cloudflare API or Terraform Provider? As I can't toggle this option programmatically my project has come to a bit of a halt at the moment.

**Comment by haydndup** [comment]
Changing
```
type                      = "ssh"
```

Worked for me.

**Comment by Cyb3r-Jak3** [comment]
@jacobbednarz I'm pretty sure this is a non issue. `ssh` and `vnc` are just a type of access application and are already being validated here https://github.com/cloudflare/terraform-provider-cloudflare/blob/c9eef200b557bd1f41fb0c492bf5e2bcbad38fb2/internal/provider/schema_cloudflare_access_application.go#L49

**Comment by jacobbednarz** [comment]
cc @Justin-Holmes

**Comment by Justin-Holmes** [comment]
@haydndup is correct, set the application to `ssh` and that will create a browser rendering ssh app.

**Comment by jacobbednarz** [comment]
thanks for confirming! closing as this is already supported.
