### ISSUE TITLE
Disable universal certificates

### ISSUE THREAD

**Issue by nitrocode** [cloudflare/terraform-provider-cloudflare#1841]
### Current Terraform and Cloudflare provider version

terraform 1.2.7

cloudflare provider v3.21.0

### Description

I'm using a single advanced wildcard certificate on my partial cloudflare zone. To prevent each new record added to my zone from creating an unused universal record, I'd like to disable universal certificates using a terraform resource but one does not exist.

My current workaround is to use clickops to disable universal certificates.

### Use cases

See above

### Potential Terraform configuration

Perhaps this can be set on the zone itself?

```hcl
resource "cloudflare_zone" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  zone       = "example.com"

  universal_certificates_enabled = false
}
```

### References

- https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone
- https://developers.cloudflare.com/ssl/edge-certificates/universal-ssl/disable-universal-ssl/

**Comment by jacobbednarz** [comment]
I think you want https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#universal_ssl ?

**Comment by nitrocode** [comment]
Yes, that is exactly what I wanted. Thank you so much.
