### ISSUE TITLE
Document migration to v3.21.0

### ISSUE THREAD

**Issue by dhay** [cloudflare/terraform-provider-cloudflare#1843]
### Current Terraform and Cloudflare provider version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-providers/cloudflare v3.20.0

### Description

When upgrading to the cloudflare terraform provider version 3.21.0, support for the `terraform-providers/cloudflare` source has, apparently, been dropped.  It would have been nice if there had been something in the documentation mentioning that this was happening and steps to migrate to the new source.  For example, a pointer to the `replace-provider` command with an example of how to run the command.

### Use cases

Developers migrating to 3.21 from earlier versions and using the `terraform-providers/cloudflare` source.
```
   cloudflare = {
      version = "3.20.0"
      source = "terraform-providers/cloudflare"
    }
```

### Potential Terraform configuration

n/a

**Comment by jacobbednarz** [comment]
I'm not sure what your describing here? Can you provide a different explanation?

I see you're running an old version of Terraform CLI, make sure you're running the latest as 0.13 is no longer supported.

**Comment by dhay** [comment]
Here's what we were running into today.  We had our provider configuration that looks like this:
```
terraform {
  required_providers {
    cloudflare = {
      source = "terraform-providers/cloudflare"
    }
  }
}
```
When we went to do a terraform init, we got this error:
```
The remote registry returned warnings for
registry.terraform.io/terraform-providers/cloudflare:
- For users on Terraform 0.13 or greater, this provider has moved to
cloudflare/cloudflare. Please update your source in required_providers.


Error: Failed to install provider

Error while installing terraform-providers/cloudflare v3.21.0: could not query
provider registry for registry.terraform.io/terraform-providers/cloudflare:
registry response includes invalid version string "1; mode=block": invalid
characters "; mode=block"
```

If we pin the version of the cloudflare provider to 3.20.0, we don't get this error.  

I'm somewhat new to Terraform, so all I was suggesting is that the documenation should be updated to help those of us who weren't sure how to solve this issue.  I think, in this case, something about how version 3.21.0 no longer supports the old provider "source" and a pointer on how to update it.

**Comment by jacobbednarz** [comment]
this isn't something we're controlling in the provider; see the error message in the output above.

```
Error while installing terraform-providers/cloudflare v3.21.0: could not query
provider registry for registry.terraform.io/terraform-providers/cloudflare:
registry response includes invalid version string "1; mode=block": invalid
characters "; mode=block"
```

seems to suggest a change from the Hashicorp team on the registry side. i'd recommend updating to a supported version of `terraform` and using the newer version of the provider reference path since that is likely to solve your issue.
