### ISSUE TITLE
Default declaration for rules/groups/package in WAF

### ISSUE THREAD

**Issue by araks-hypixelstudios** [cloudflare/terraform-provider-cloudflare#1845]
### Current Terraform and Cloudflare provider version

Terraform v1.2.1
Cloudflare 3.21.0

### Description

Cloudflare WAF has the capability to manage WAF rules by managing packages, by managing groups that belong to a package and by managing each individual rule, which allow us for flexible configuration.

However, if we attempt to manage the rules by terraform, we are required to declare every rule, group and package, even if they are using the default value. Per zone, that is around 3000 terraform resources, which has an impact when refreshing the state.

The other disadvantage of being explicit in the rules is that new elements can be introduced but they are not managed by terraform until the user detects the new elements and declare them in terraform.

The purpose of this request is to have Terraform as the source of truth for any WAF configuration and detect and revert any configuration drift that is detected, without being too much declarative when using default configurations.

### Use cases

* Use Terraform as source of truth for WAF configuration so we have peer review and history
* Detect any WAF configuration drift
* Easily revert WAF configuration in case of security incident, ensuring CF default rules + our exception rules, without iterating over each individual rule.
* Easily verify the overrides done by our company to Cloudflare WAF's default rules.

### Potential Terraform configuration

```hcl
resource "cloudflare_waf_package_override" "owasp" {
  package_id = "c504870194831cd12c3fc0284f294abb" # we can use data source here
  zone_id    = var.zone_id

  sensitivity = "medium" #optional
  action_mode = "challenge" #optional
  groups_override {
     group_id = "07d700cf30fda7548be94ff01087d0c4"
     mode = "off"
  }
}

resource "cloudflare_waf_group_override" "owasp_bad_robots_group" {
  goup_id = "07d700cf30fda7548be94ff01087d0c4" # we can use data source here
  zone_id    = var.zone_id

  rules_override {
     rule_id = "2011563A"
     mode = "off"
  }
}
```

This configuration serve as an example to override the packages offered by CF. Not to manage new packages.

**Comment by jacobbednarz** [comment]
thanks for the issue but as this is related to the old WAF (now deprecated in favour of Rulesets) we are highly unlikely to add this functionality or make any changes to it in the future. 

check out the Rulesets documentation for managing overrides if you'd like to see if that suits your needs better

**Comment by araks-hypixelstudios** [comment]
Hey @jacobbednarz 

Not sure if we're talking about the same thing.  I'm referring to the capability to manage "Managed Rulesets" through terraform: https://dash.cloudflare.com/{zone_id}/{zone_name}/security/waf/managed-rules

[Cloudflare's ruleset resource](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset) only manages the creation of new rulesets, not managing the ones *created* by Cloudflare.

The current `ruleset` resource doesn't offer the capability for "Managed Rulesets" from CF UI, correct?

**Comment by jacobbednarz** [comment]
gotcha, so your issue had me confused as it mentions `cloudflare_waf_group_override` which i read as `cloudflare_waf_override` (related to the old WAF).

Ruleset based managed rules can be maintained in Terraform (see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset) and you don't have to define all of them; only the overridden ones. does that answer cover what you're after here?

**Comment by araks-hypixelstudios** [comment]
From what I understood, it doesn't cover. If someone changes in the UI a managed ruleset, I won't be able to detect or revert it using terraform.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/102150391/186435177-303d5598-aa63-4653-830d-fd0eb87edb67.png">

If someone changes a group of a package, can't be detected as well 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/102150391/186435634-f388ae80-1085-4ba9-a237-dfc6e230c906.png">


Same for a rule of a given group (seen in the Advanced UI)

<img width="646" alt="image" src="https://user-images.githubusercontent.com/102150391/186435754-4dd6dea2-debe-451c-a6e7-c7b2bc870d02.png">

Apologies in advance if I'm missing something obvious here.

**Comment by jacobbednarz** [comment]
from your screenshots, it looks like you're mixing the two versions of the WAF. the new WAF UI looks like this

![Mo7N6lQK-4XwwOFFv-uTGduVdK](https://user-images.githubusercontent.com/283234/186511127-f07a22d6-f274-478f-8b00-b901d235d57c.png)

in the newer WAF, you don't manage all rules in a ruleset, only the ones you want to override.

**Comment by araks-hypixelstudios** [comment]
Not sure, I'm not aware of any new WAF UI. I'm accessing by going to the Zone page -> Security -> WAF -> Managed Rules which redirects to `https://dash.cloudflare.com/{zone_id}/{zone_name}/security/waf/managed-rules` in the browser.

I will reach out to the account manager to understand what is the issue.

Thank you.
