### ISSUE TITLE
Cloudflare Load Balancing Health Alert

### ISSUE THREAD

**Issue by MilanDasek** [cloudflare/terraform-provider-cloudflare#1852]
### Current Terraform and Cloudflare provider version

Terraform v1.2.7

### Description

Hello,

How can I enable Load Balancing Health Alert in cloudflare_notification_policy, since CF is discontinuing old type of monitoring
https://developers.cloudflare.com/load-balancing/reference/migration-guides/health-monitor-notifications/

It seems such alert_type is missing there, or I don't know how to filter to current pool.

Can you please provide some example if I am missing it?

### Use cases

https://developers.cloudflare.com/load-balancing/reference/migration-guides/health-monitor-notifications/

### Potential Terraform configuration

I don't know.

**Comment by jacobbednarz** [comment]
the documentation for alert types was updated in #1830 to cover the newer types. check that out and you should be able to use the developer docs to translate to the required terraform configuration.

**Comment by MilanDasek** [comment]
Sorry,

so why I get 

```│ Error: Unsupported argument
│ 
│   on .terraform/modules/cloudflare-loadbalancer-he-dev/cd-lb-notification.tf line 16, in resource "cloudflare_notification_policy" "healthcheck_notification":
│   16:     event_source = [
│ 
│ An argument named "event_source" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/cloudflare-loadbalancer-he-dev/cd-lb-notification.tf line 20, in resource "cloudflare_notification_policy" "healthcheck_notification":
│   20:     new_health = [
│ 
│ An argument named "new_health" is not expected here.
```

with
```
  filters {

    event_source = [
      "pool", "origin"
    ]

    new_health = [
      "Unhealthy", "Healthy"
    ]

    pool_id = [cloudflare_load_balancer_pool.pool[count.index].id]
  }
````

with
```- Finding cloudflare/cloudflare versions matching "~> 3.0"...
- Installing cloudflare/cloudflare v3.21.0...
- Installed cloudflare/cloudflare v3.21.0 (signed by a HashiCorp partner, key ID DE413CEC881C3283)
```

Thank you

**Comment by MilanDasek** [comment]
@jacobbednarz - please ^^

**Comment by jacobbednarz** [comment]
the change isn't available in the public version yet; see https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md. if you need the change immediately, you can build a custom version locally to use https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/using-non-released-versions.md.
