### ISSUE TITLE
Improve performance of DNS record changes

### ISSUE THREAD

**Issue by sdonaghy-codat-io** [cloudflare/terraform-provider-cloudflare#1854]
### Current Terraform and Cloudflare provider version

Terraform v1.2.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.21.0

### Description

In DNS zones with hundreds of records it takes significant time to retrieve the current state of those records during a **terraform plan** 
Calls to the Cloudflare API are rate limited to 4 per second (1200 / 5 mins)  so updating even a single DNS record can take many minutes. Almost all of that time is spent retrieving records, one by one, from the Cloudflare API.  
However, the Clouflare API allows up to 5,000 records to be retreived in a single API call:  https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records (and the provider already has an implementation of this)

**Proposed change**

When the provider attempts to retrieve a single record for a zone, a call is made to the above endpoint, to retrieve all the records for that zone. These records are then cached in memory and all subsequent requests for a single record will be served from the cache - instead of making a call to the Cloudflare API. This will allow a **terraform plan** to complete in seconds, instead of minutes 
 

### Use cases

Ability to quickly deploy DNS changes

* Avoid having to re-run deployment pipelines, which have failed due to Cloudflare API rate limits being exceeded
* In certain scenarios it is critical to make DNS changes quickly. If automated pipelines are slow, it increases the likehood that manual changes will be made to 'speed things up'. That will result in inconistent terraform state, which then requires resources to be manually imported/removed

### Potential Terraform configuration

```hcl
...
```

### References

This PR has an implementation of the proposed changes: https://github.com/sean-donaghy/terraform-provider-cloudflare/pull/1
It enables **terraform plan** for a 1,000 record DNS zone to complete in less than 20 secs. The  unmodified provider takes around 4 minutes to complete the same operation.

**Comment by sdonaghy-codat-io** [comment]
Is is possible to get this issue triaged ?

It would be great to at least get some high level feedback, to decide if it is worth exploring further. 
I appreciate there may be concerns about the proposed change and/or the proposed implementation, so it would be good to understand if any of the scenario's below are accurate:  

**Proposed Change**   

  1. **The proposed change is conceptually flawed** 

       For example, it may lead to the corruption of data or terraform state   

  2. **The proposed change would cause performance issues for Cloudflare** - and therefore would not be implemented

       For example, retrieving all DNS records for a zone would cause spikes in load, and this may impact other users   


**Proposed Implementation**

 1. **The proposed implementation has major problems** 
		
       For example, cache should be cleared before any attempts to create/update/delete  

 2. **The proposed implementation does not have any major flaws, but further work needs to be done**
		
       For example, its non-idiomatic/doesn't match existing style, needs docs, more tests etc

**Comment by jacobbednarz** [comment]
thanks for the issue @sdonaghy-codat-io. i've been a bit preoccupied with other priorities so this was in a deep queue.

this at this stage, it's unlikely i'd merge an in-memory cache as Terraform core already provides a faster solution for applying changes without refreshing. see https://www.hashicorp.com/blog/new-terraform-planning-options-refresh-false-refresh-only-replace for a good overview of what is available and what suits your need. 

using this approach, applying a single change in a zone with 5k records takes ~ 3s on my connection.

```
$ time terraform apply -refresh=false -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_record.foobar4 will be updated in-place
  ~ resource "cloudflare_record" "foobar4" {
        id              = "d9c91fdd973a18d561353223aa8af049"
        name            = "example4"
      ~ value           = "192.168.4.3" -> "192.168.4.4"
        # (10 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
cloudflare_record.foobar4: Modifying... [id=d9c91fdd973a18d561353223aa8af049]
cloudflare_record.foobar4: Modifications complete after 1s [id=d9c91fdd973a18d561353223aa8af049]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

________________________________________________________
Executed in    2.83 secs    fish           external
   usr time    6.99 secs    0.56 millis    6.99 secs
   sys time    0.96 secs    1.92 millis    0.95 secs
```

and without any changes...

```
$ time terraform apply -refresh=false -auto-approve

No changes. Your infrastructure matches the configuration.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

________________________________________________________
Executed in    2.53 secs    fish           external
   usr time    6.97 secs    0.67 millis    6.97 secs
   sys time    0.98 secs    2.01 millis    0.98 secs
```

out of band, you can run the `-refresh-only` operations to keep things in sync for when you try to apply the changes next time round.

on the proposal itself, the major issue is the cache invalidation. you'd need to invalidate the records on every write operation (remote and state) when resource content changed, identifiers changed, or interrelationships were updated. these conditions are currently built into Terraform and you'd need to replicate that into the cache logic which would be a substantial undertaking but with the added risk of serving invalid data from the cache in the event an edge case was missed. 

personally, before i built anything like this into the provider, i would explore a local pass-through HTTP/HTTPS proxy with a short TTL of the remote API to speed up the round trip time. either that, or caching middleware in cloudflare-go through a custom HTTP client to avoid hitting the network for idempotent GETs.

if this is a direction you're interested in exploring, by all means, have at it but i can't see this being adopted any time soon for the mainline. if you do end up going down this path, feel free to shoot it over as you make progress and we can re-evaluate.

**Comment by sdonaghy-codat-io** [comment]
@jacobbednarz  Thanks for the comprehensive explanation and suggestions. I was not aware of the `-refresh=false` terraform option. Using that allows us to quickly deploy DNS changes. Thanks again
