### ISSUE TITLE
zone_id/account_id required for cloudflare_access_rule

### ISSUE THREAD

**Issue by heydonovan** [cloudflare/terraform-provider-cloudflare#1860]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform/1.2.2
terraform-plugin-sdk/2.10.1
terraform-provider-cloudflare/3.15.0

### Affected resource(s)

cloudflare_access_rule

### Terraform configuration files

```hcl
resource "cloudflare_access_rule" "whitelist_test" {
  count = length(var.test_ips)
  notes = "Whitelist Test IPs"
  mode  = "whitelist"
  configuration {
    target = "ip"
    value = element(var.test_ips, count.index)
  }
}
```
```


### Debug output

```
 Error: Invalid combination of arguments
│ 
│   with cloudflare_access_rule.whitelist_test,
│   on main.tf line 607, in resource "cloudflare_access_rule" "whitelist_test":
│  607: resource "cloudflare_access_rule" "whitelist_test" {
│ 
│ "zone_id": one of `account_id,zone_id` must be specified
```

### Panic output

_No response_

### Expected output

terraform validate should pass or those variables need to be listed as required

### Actual output

```
 Error: Invalid combination of arguments
│ 
│   with cloudflare_access_rule.whitelist_test,
│   on main.tf line 607, in resource "cloudflare_access_rule" "whitelist_test":
│  607: resource "cloudflare_access_rule" "whitelist_test" {
│ 
│ "zone_id": one of `account_id,zone_id` must be specified
```

### Steps to reproduce

run terraform validate

### Additional factoids

_No response_

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_rule

**Comment by jacobbednarz** [comment]
can you elaborate what the bug is here? the error message is providing feedback that either account or zone ID is required yet, you haven't supplied it in your repro example.

**Comment by heydonovan** [comment]
right! the docs needs to reflect that one of those are required (they both say optional) :v:

**Comment by jacobbednarz** [comment]
that's correct. the documentation is generated by the schema definition where these attributes are in fact optional. i can take a look at the documentation tool to see if we can make this clearer without touching all the descriptions.

**Comment by jacobbednarz** [comment]
#1862 should make this slightly clearer.
