### ISSUE TITLE
cloudflare_access_service_token option to refresh only, not recreate

### ISSUE THREAD

**Issue by t0rrant** [cloudflare/terraform-provider-cloudflare#1866]
### Current Terraform and Cloudflare provider version

cloudflare: 3.18.0
terraform: 1.2.4

### Description

Add a `refresh_only` option to `cloudflare_access_service_token` resource, to be used alongside `min_days_for_renewal` so the resource refreshes the token instead of replacing it with a new one.

### Use cases

When setting this resource with the `min_days_for_renewal` option a new token will be created which means that wherever it is used (most likely outside of the Terraform config) it will have to be replaced.

While this is good for actual rotations, users may not want an actual rotation but instead want an extension of the token's expiration date.

### Potential Terraform configuration

```hcl
resource "cloudflare_access_service_token" "my_app" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "CI/CD app refresh"

  min_days_for_renewal = 30
  refresh_only = true
}
```

**Comment by jacobbednarz** [comment]
once we get this in the public API, we can add it here.
