### ISSUE TITLE
Allow setting worker compatibility_date/flags

### ISSUE THREAD

**Issue by Qantas94Heavy** [cloudflare/terraform-provider-cloudflare#1869]
### Current Terraform and Cloudflare provider version

* Terraform 1.2.3
* Cloudflare terraform provider 3.15.0

### Description

Cloudflare allows setting a compatibility date/flags for certain Worker features/bug fixes: https://developers.cloudflare.com/workers/platform/compatibility-dates/

However, the current `cloudflare_worker_script` resource does not provide this setting.

### Use cases

Allows enabling new Cloudflare worker features and bug fixes that may change existing behaviour.

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "example" {
  ...
  compatibility_date = "2022-04-05"
  compatibility_flags = ["url_standard"]
}
```

**Comment by unstubbable** [comment]
I believe `compatibility_flags` was not covered by #2300. Can this issue be reopened to track that?

**Comment by jacobbednarz** [comment]
let's create a new issue specifically for `compatibility_flags` support seeing how they were lumped together here. 

if you'd like to add support, i'm happy to review a PR.
