### ISSUE TITLE
Add consecutive_down and consecutive_up parameters to cloudflare_load_balancer_monitor

### ISSUE THREAD

**Issue by MAN98** [cloudflare/terraform-provider-cloudflare#1876]
### Current Terraform and Cloudflare provider version

terraform {
  required_providers {
    vault = {
      source = "hashicorp/vault"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.16.0"
    }
  }
  required_version = ">= 1.0"

  backend "remote" {
    organization = "bmgf"

    workspaces {
      name = "tf_cloudflare"
    }
  }
}

### Description

Via the Cloudflare API (https://api.cloudflare.com/#account-load-balancer-monitors-create-monitor) you can set the consecutive_down and consecutive_up parameter values for the Cloudflare Load Balancer Monitor resource but not with the Terraform Provider. Can we have these added?

### Use cases

We are managing our LB Monitors via Terraform as with everything else. Having a consecutive_up and consecutive_down parameter will give us more flexibility in fine-tuning the monitors we use for our LB pools.

### Potential Terraform configuration

resource "cloudflare_load_balancer_monitor" "lb_monitor" {
  type           = "https"
  expected_body  = "Healthy"
  expected_codes = "2xx"
  method         = "GET"
  timeout        = 5
  path           = "/healthcheck"
  interval       = 10
  port           = 443
  retries        = 1
  description    = "monitor for ${var.zone_name}"
  header {
    header = "Host"
    values = [var.zone_name]
  }
  allow_insecure   = true
  follow_redirects = false
  consecutive_down = 2
}

**Comment by andmor** [comment]
+1

**Comment by pwilczynskiclearcode** [comment]
I reported a bug related to this resource https://github.com/cloudflare/terraform-provider-cloudflare/issues/5676
