### ISSUE TITLE
zone_id/account_id mandatory instead of optional as listed in documentation

### ISSUE THREAD

**Issue by thejohnrichard** [cloudflare/terraform-provider-cloudflare#1881]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

3.20.0 ... HEAD

### Affected resource(s)

cloudflare_access_rule

### Terraform configuration files

```hcl
resource "cloudflare_access_rule" "whitelist_vpn_ips" {
  for_each = zipmap(var.vpn_ips, var.vpn_ips)
  notes = "TF Whitelist traffic from VPN"
  mode  = "whitelist"
  configuration {
    target = "ip"
    value  = each.key
  }
}
```

### Link to debug output

-

### Panic output

none

### Expected output

No error

### Actual output

Error: Invalid combination of arguments

  with cloudflare_access_rule.whitelist_vpn_ips,
  on ip_access_rules.tf line 1, in resource "cloudflare_access_rule" "whitelist_vpn_ips":
   1: resource "cloudflare_access_rule" "whitelist_vpn_ips" {

"account_id": one of `account_id,zone_id` must be specified

### Steps to reproduce

1. Create a cloudflare_access_rule
2. Omit both account_id and zone_id (both should be optional)
3. Use cloudflare provider version 3.20 or later

### Additional factoids

We discovered that there is a mismatch between the schema and the code of cloudflare_access_rule. To be exact: This line ( https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/schema_cloudflare_access_rule.go#L18 ) states that there must be either an account_id present or a zone_id present. This leads to this specific line to be unreachable: https://github.com/cloudflare/terraform-provider-cloudflare/blob/v3.22.0/internal/provider/resource_cloudflare_access_rule.go#L101

Furthermore, the changes made in https://github.com/cloudflare/terraform-provider-cloudflare/pull/1862 say that there must be "only one" of account_id or zone_id whereas it has to be "exactly one" and not "only one".

### References

Similar issue but not really fixed in my opinion: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1860 - Also, additions of "Must provide only one of `zone_id`, `account_id`." to documentation is still unclear.

**Comment by jacobbednarz** [comment]
are you using user level access rules? if so, I'd recommend migrating them to the account level as user level resources are a pseudo account level resource and will likely go away in the next major release to avoid confusion and bugs. 

as for the wording, I'm not sure what else would make it clearer that you must provide one of either of those values. what would you suggest?

**Comment by thejohnrichard** [comment]
I am using user level access rules since I do not define an account_id oder zone_id.

In the changelog for v[3.20](https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v3.20.0) it is mentioned that the usage of account_id is now supported and it is suggested to switch to using this. However, it is in fact mandatory and not adapting to this when using version 3.20 or above will break the configuration if user level resources are used.

From the documentation or changelog I would not have expected this. But since this migration is necessary at the moment (regardless of the state of the documentation or changelog notes), are there any pointers on how to migrate those resources properly from user level to account level resources?

**Comment by jacobbednarz** [comment]
to migrate, the best cause of action is to create the rules with the `account_id`/`zone_id` attributes set and then remove the user level ones. it will ensure a correct setup without attempting to migrate between the scopes.

**Comment by jacobbednarz** [comment]
for now, i can remove the schema restriction though and enforce it in the next major version bump too. you'll still need to migrate, however, it can be kicked down the road a little.
