### ISSUE TITLE
Support creating HTTPS DNS records

### ISSUE THREAD

**Issue by insertjokehere** [cloudflare/terraform-provider-cloudflare#1883]
### Current Terraform and Cloudflare provider version

Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.22.0

### Description

The Cloudflare API supports creating DNS records of the `HTTPS` record type. When attempting to create a record of this type, the provider returns an error like

```
Error: expected type to be one of [A AAAA CAA CNAME TXT SRV LOC MX NS SPF CERT DNSKEY DS NAPTR SMIMEA SSHFP TLSA URI PTR], got HTTPS
```

### Use cases

Ensure the Terraform provider has feature parity with the plain API

### Potential Terraform configuration

```hcl
resource "cloudflare_record" "www-https" {
  zone_id = var.zone_id
  name    = "example.com"
  type    = "HTTPS"
  ttl     = 3600
  data {
    priority = "1"
    target   = "."
    value    = "alpn=h2"
  }
}
```

**Comment by jacobbednarz** [comment]
happy to review a PR for this one 👍 looks like we already have public documentation so this will be a straight forward update.
