### ISSUE TITLE
Missing support for Web Analytics

### ISSUE THREAD

**Issue by Hurtak** [cloudflare/terraform-provider-cloudflare#1884]
### Current Terraform and Cloudflare provider version

```
Terraform v1.2.8
on darwin_arm64
```

### Description

I have not found a way to configure Cloudflare web analytics with Terraform 

### Use cases

Our use case is that we need to disable the web analytics "automatic setup" (the way they setup their JS tracking script) and we want to have this setting synced by Terraform rather than manually in the UI

### Potential Terraform configuration

Not experienced enough with Terraform to suggest good example

**Comment by Hurtak** [comment]
@jacobbednarz hey, can you double check that the #1887 fixes this issue, it seems to be unrelated.

**Comment by jacobbednarz** [comment]
you're right, looks like the issue number was off by one.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
