### ISSUE TITLE
No way to specify account_id for cloudflare_load_balancer

### ISSUE THREAD

**Issue by baznikin** [cloudflare/terraform-provider-cloudflare#1888]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.22.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.22.2
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/helm v2.6.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.13.1

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

**cloudflare_load_balancer**

### Terraform configuration files

```hcl
provider "cloudflare" {
  api_token  = var.cf_token
  account_id = var.cf_account_id
}

# load_balancer_pool skipped, they created successfully

resource "cloudflare_load_balancer" "mydomain-lb" {
  zone_id = data.cloudflare_zone.mydomain.id
  name = "lb.${data.cloudflare_zone.mydomain.name}"
  proxied = true
  steering_policy  = "dynamic_latency"

  default_pool_ids = [
    cloudflare_load_balancer_pool.mydomain-eu.id,
    cloudflare_load_balancer_pool.mydomain-sa.id,
  ]
  fallback_pool_id = cloudflare_load_balancer_pool.mydomain-eu.id

}
```

### Link to debug output

https://gist.github.com/baznikin/e46f501b0d257f6654bc2b56ce6d587c

### Expected output

Resource expected to be created

### Actual output

error creating load balancer for zone: Authentication error (10000)

### Steps to reproduce

As we can see from debug output resources created at user level:
```
POST /client/v4/zones/7e2c7278024dc544a176072500db9fab/load_balancers HTTP/1.1
```
while there is `account_id` in provider definition.

`cloudflare_load_balancer` resource doesn't accept `account_id` parameter either.

### Additional factoids

I am not owner of account with zones so it is mandatory to pass `account_id` somehow. Looks like it is broken in current version.

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1641

**Comment by baznikin** [comment]
https://gist.github.com/baznikin/e46f501b0d257f6654bc2b56ce6d587c

**Comment by baznikin** [comment]
@jacobbednarz complete debug uploaded, dunno how to force bot to re-check it and remove `triage/needs-information` label. Please, check

**Comment by jacobbednarz** [comment]
load balancers don't exist at the account level (intentionally, only zone). load balancer pools and monitors exist at the account level though.

the authentication error looks like you might have a token that isn't sufficiently permitted to access the zone resources?

**Comment by baznikin** [comment]
You are right, I added permission 'Zone:Load Balancers' and the error
disappears! It will be nice addition to documentation - note regarding
required permissions. I searched for this permission at account level, it
was on zone level.

ср, 7 сент. 2022 г. в 03:14, Jacob Bednarz ***@***.***>:
