### ISSUE TITLE
How to disable resords scan?

### ISSUE THREAD

**Issue by kporembinski** [cloudflare/terraform-provider-cloudflare#1889]
### Current Terraform and Cloudflare provider version

I've read issue #826 that `jump_start` flag wasn't working and it will be deprecated on 2022-09-23. How to disable records scanning and adding current records?

### Description

Add some flag to disable auto records scan.

### Use cases

Add some flag to disable auto records scan.

### Potential Terraform configuration

```hcl
resource "cloudflare_zone" "viaxe_pl" {
  account_id = var.cloudflare_account_id
  zone       = "viaxe.pl"
  plan       = "free"
  jump_start = false # dont remove it
}
```

**Comment by jacobbednarz** [comment]
i wouldn't worry about this tbh; we'll just remove the attribute soon enough as it is being ignored in the remote API anyway.

**Comment by kporembinski** [comment]
Yes it was. Still how to disable adding record by Cloudflare? I can't create own records, because after creating zone, they exists.

**Comment by jacobbednarz** [comment]
the records definitely aren't from the jump start. if you delete a zone and recreate the zone within a certain timeframe, it does restore the previous zone as opposed to creating a new one. is that what you're doing here? if not, I'd suggest you paste the output from prefixing TF_LOG=DEBUG to the commands to further dig into this but it's definitely not an enhancement.
