### ISSUE TITLE
Cannot create a GitHub/GitLab Pages project

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/terraform-provider-cloudflare#1897]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.23.0

Your version of Terraform is out of date! The latest version
is 1.2.8. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
terraform {
 required_providers {
   cloudflare = {
     source = "cloudflare/cloudflare"
     version = "~> 3.23.0"
   }
 }
}

variable "cloudflare_api_token" {}
variable "cloudflare_account_id" {}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

resource "cloudflare_pages_project" "example-project" {
  account_id        = var.cloudflare_account_id
  name              = "example-project"
  production_branch = "main"

  build_config {
    build_command   = "npm run build"
    destination_dir = "build"
  }

  source {
    type = "github"
    config {
      owner             = "WalshyDev"
      repo_name         = "Test"
      production_branch = "main"
    }
  }
}
```

### Link to debug output

https://gist.github.com/WalshyDev/60b51d1bdf060cc239bb701ef30bea72

### Expected output

Pages project to be created and linked to GitHub.

### Actual output

A Direct Uploads project was created (no link to GitHub).

### Steps to reproduce

1. Copy-paste my config above
2. Change GitHub info
3. Apply with TF_VAR_cloudflare_account_id=xxxxxx TF_VAR_cloudflare_api_token=yyyyyyyy
4. Check the projects list - https://dash.cloudflare.com/4e599df4216133509abaac54b109a647/pages

### Additional factoids

You can see in the request where the problem is:
```
"source": {
   "type": "",
   "config": null
  }
```

This should instead be:
```
"source": {
  "type": "github"
  "config": {
    "owner": "WalshyDev",
    "repo_name": "Test",
    "production_branch": "main"
  }
}
```

(side note, there is a ton being sent here, this is like a project response rather than a create response)

Our internal create request only has:
* "name"
* "source,omitempty"
* "build_config,omitempty"
* "deployment_configs,omitempty"
* "production_branch,omitempty"

**Comment by WalshyDev** [comment]
cc: @Cyb3r-Jak3

**Comment by faldor20** [comment]
Would it possible for this to be released as a patch? This kind of makes one of the main 3.23 release features unusable for the next two weeks.
