### ISSUE TITLE
Add cloudflare_record data source.

### ISSUE THREAD

**Issue by MoSalah5** [cloudflare/terraform-provider-cloudflare#1904]
### Current Terraform and Cloudflare provider version

Terraform v1.1.7
on darwin_arm64

Your version of Terraform is out of date! The latest version
is 1.2.9. You can update by downloading from https://www.terraform.io/downloads.html

### Description

Add a new data source (may called cloudflare_record) to be able to retrieve a record details in case that record not created in the same terraform configuration files. 
Being able to pass the record ID or FQDN in the data source block and get all possible details for that record like record type, name, and value.

### Use cases

I need to create a new AWS ACM certificate (let's call it cert A) and associate it with a the same domain that's already associated with another AWS ACM certificate (let's call it cert B) created in another AWS region. So when trying to validate the new certificate (cert A) against that domain, I got an error stating that those validation records already exist so I can't add new ones.

I need to use "cert A" with AWS cloudfront distribution while "cert B" is already verified and used with AWS APIGW.

Why I need to create 2 different AWS ACM certificates for the same domain? Because the application is deployed in a "X" region, but the AWS Cloudfront distribution needs to be in the global AWS region

### Potential Terraform configuration

```hcl
...
```
data "cloudflare_record" "default" {
      id = "abcd123"
}

resource "aws_acm_certificate_validation" "us_east_1" {
  provider                            = aws.global_region
  certificate_arn                 = aws_acm_certificate.global_reion.arn
  validation_record_fqdns = [data.cloudflare_record.default.hostname]
}

**Comment by Cyb3r-Jak3** [comment]
@jacobbednarz I can work on this.
