### ISSUE TITLE
Error: error creating worker script: could not read response body: %!w(<nil>)

### ISSUE THREAD

**Issue by tamis-laan** [cloudflare/terraform-provider-cloudflare#1908]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
> terraform --version
Terraform v1.2.3
on linux_amd64

// Cloudflare CDN
cloudflare = {
  source  = "cloudflare/cloudflare"
  version = "3.23.0"
}
```

### Affected resource(s)

cloudflare_worker_script

### Terraform configuration files

```hcl
# Create the worker script
resource "cloudflare_worker_script" "my_worker" {
  name    = "my_worker"
  content = file("my_worker.js")

  r2_bucket_binding {
    name        = "my_bucket"
    bucket_name = "R2MYBUCKET"
  }

}
```

### Link to debug output

/dev/null

### Expected output

terraform apply should pass and return no errors

### Actual output
```
│ Warning: Argument is deprecated
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on main.tf line 32, in provider "cloudflare":
│   32:   account_id = var.CLOUDFLARE_ACCOUNT_ID
│
│ Use resource specific `account_id` attributes instead.
╵
```
```
╷
│ Error: error creating worker script: could not read response body: %!w(<nil>)
│
│   with cloudflare_worker_script.my_worker,
│   on main.tf line 367, in resource "cloudflare_worker_script" "my_worker":
│  367: resource "cloudflare_worker_script" "my_worker" {
│
╵
```
### Steps to reproduce

I can produce a full working example but this will take time. Hoping this is sufficient.

**Comment by jacobbednarz** [comment]
please provide the entire TF_DEBUG output and a repro for this to be triaged further.

**Comment by jacobbednarz** [comment]
closing to lack of response. if this is still an issue, please open a new issue filling out all the required fields for maintainers to triage.
