### ISSUE TITLE
[3.24.0] Regression - Cannot specify both api_user_service_key and api_token

### ISSUE THREAD

**Issue by uncycler** [cloudflare/terraform-provider-cloudflare#1919]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.9
Cloudflare provider v3.24.0

### Affected resource(s)

- cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
resource "cloudflare_origin_ca_certificate" "test" {}
```

### Link to debug output

N/A

### Expected output

Resource `cloudflare_origin_ca_certificate` requires `api_user_service_key` but not other resources.

### Actual output

│ Error: Invalid combination of arguments
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on <empty> line 0:
│   (source code not available)
│ 
│ "api_user_service_key": only one of
│ `api_key,api_token,api_user_service_key` can be specified, but
│ `api_token,api_user_service_key` were specified.

### Steps to reproduce

1. Try to use `cloudflare_origin_ca_certificate` and `cloudflare_record` in the same Terraform configuration.

**Comment by jacobbednarz** [comment]
this is not a regression. you only need to provide one of these auth methods when making API calls and sending both makes the internals difficult (and time consuming) to debug.

**Comment by uncycler** [comment]
Hmm, ok. Quite a breaking change. So, I guess we need to create an alias provider for `cloudflare_origin_ca_certificate`.

btw, documentation still state: `This resource requires you use your Origin CA Key as the [api_user_service_key](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/index#api_user_service_key), in conjunction with an api_token or email and api_key.`

**Comment by jacobbednarz** [comment]
an alias provider will also work with separate credentials. 

feel free to send over a PR updating the docs and I'll get it merged. check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how the documentation generation works.

**Comment by eyedvabny** [comment]
Maybe I am missing some workaround, but this change has broken the use of `cloudflare_origin_ca_certificate` resource. If the token + api_user_service_key are specified together, the provider throws an error that only one of auth methods can be specified. If only the token is used, I get `error finding OriginCACertificate "<my certificate ID>": Authentication error (10000)`. And if only api_user_service_key is specified the provider errors with `error creating new Cloudflare client: invalid credentials: key & email must not be empty`

**Comment by uncycler** [comment]
> Maybe I am missing some workaround, but this change has broken the use of `cloudflare_origin_ca_certificate` resource. If the token + api_user_service_key are specified together, the provider throws an error that only one of auth methods can be specified. If only the token is used, I get `error finding OriginCACertificate "<my certificate ID>": Authentication error (10000)`. And if only api_user_service_key is specified the provider errors with `error creating new Cloudflare client: invalid credentials: key & email must not be empty`

IMHO, this kind of breaking change should not have been included in 3.x but anyway, this is what you need to do now::

```hcl
provider "cloudflare" {
  alias  = "api_user_service_key"
  api_user_service_key = var.cloudflare_api_user_service_key
}

resource "cloudflare_origin_ca_certificate" "aks_ingress" {
  provider = cloudflare.api_user_service_key
}
```

Ref: https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations

**Comment by jacobbednarz** [comment]
@eyedvabny that is a slightly different to what is mentioned here however, that was definitely an oversight. i've pushed up #1923 which will allow setting it when it is the only provider configuration offered. otherwise, you're free to use the workaround mentioned above.

**Comment by LanceSandino** [comment]
any idea when 3.25.0 will be available? we're running into this issue

**Comment by mortengjesing** [comment]
@jacobbednarz I don't see any workaround, you ether end up with a `Authentication error (10000)` or a `key & email must not be empty`

**Comment by LanceSandino** [comment]
> @jacobbednarz I don't see any workaround, you ether end up with a `Authentication error (10000)` or a `key & email must not be empty`

Yeah I ended up having to downgrade to 3.22 I believe and reverting to key and email.

**Comment by arkoc** [comment]
Why is this closed?

**Comment by mattmichal** [comment]
> @jacobbednarz I don't see any workaround, you ether end up with a `Authentication error (10000)` or a `key & email must not be empty`

I think that the workaround that Jacob is referencing is the [one given by @uncycler](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1919#issuecomment-1254769368) in which an alias provider has to be given. _After_ 3.25 is released, you'll be able to create a provider with only `api_user_service_key` which can then be used with `cloudflare_origin_ca_certificate` resources while other resources can use a provider with `api_token`. You'll be unable to use environment variables to pass the credentials in this scenario.

**Comment by jacobbednarz** [comment]
v3.25.0 was released yesterday so updating will resolve the underlying problem here. 

you will need to still split the configuration based on the authentication mechanism (either with an alias or separate directory provider setup).

**Comment by pielgrzym** [comment]
The workaround by @uncycler does not work for me. Error is `"api_key": only one of 'api_key,api_token,api_user_service_key' can be specified, but 'api_key,api_user_service_key' were specified.`. Using v3.25.0.
I can't wrap my head around why I can't just pass both keys and have TF working. Can you please provide a **working** example how to use this monstrosity?

**Comment by pielgrzym** [comment]
Got it working. Won't run with env variables, I guess.

For all the people wasting time to get this working, here is a ready example:
```
terraform {
  required_version = ">= 1.0.2"
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 3.0"
      configuration_aliases = [ cloudflare.abomination ]
    }
  }
}
provider "cloudflare" {
  api_key = "your_api_key_here"
  email = "your@email.here"
}

provider "cloudflare" {
  alias  = "abomination"
  api_user_service_key = "origin ca key here. the one from the very bottom of api tokens page. called service key nowhere on the internet"
}

(...)

resource "cloudflare_origin_ca_certificate" "origin_cert" {
  provider = cloudflare.abomination
  csr                = tls_cert_request.testreq.cert_request_pem
  hostnames          = [ "*.mydomain.com", "mydomain.com" ]
  request_type       = "origin-rsa"
  requested_validity = 365
}
```

**Comment by orlandothoeny** [comment]
Using two separate providers is not a great solution.. since you're not able to use environment variables as already mentioned.
So you either have to commit your keys, which is not an option.
Or have a separate `.tf` file for your Cloudflare provider, and add that to your `.gitignore`.
Not great in regards to DX...

**Comment by pielgrzym** [comment]
You could use tfvars, but still this is a pain to configure. I'm struggling to pass the provider alias to a module, this change is just increasing complexity for the user without any direct benefit.

**Comment by aldoborrero** [comment]
If you're using Terragrunt, you can automate the pain points with something like in your `terragrunt.hcl` parent config:

```terraform
generate "terraform_cloudflare_provider_fix" {
  path      = "terraform_cloudflare_provider_fix.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
## TODO: See how to fix this once upstream finds a solution.
## This is a workaround for using certain resources like cloudflare_origin_ca_certificate without issues.
## See more info: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1919

variable "CF_API_TOKEN" {
  type      = string
  sensitive = true
}

variable "CF_API_USER_SERVICE_KEY" {
  type      = string
  sensitive = true
}

provider "cloudflare" {
  api_token = var.CF_API_TOKEN
}

provider "cloudflare" {
  alias                = "cf-origin-cert-workaround"
  api_user_service_key = var.CF_API_USER_SERVICE_KEY
}
EOF
}
```

**Comment by mattmichal** [comment]
@orlandothoeny you can [use env vars](https://www.terraform.io/cli/config/environment-variables#tf_var_name) to pass variable values to Terraform using the prefix `TF_VAR_`.

@pielgrzym I was able to configure two Cloudflare providers and pass them both to a local module. The local module should have the `[configuration_aliases](https://www.terraform.io/language/providers/configuration#alias-multiple-provider-configurations)` keyword.

I've created a gist to show how I am [using TF_VAR env vars and Cloudflare provider aliases in a module](https://gist.github.com/mattmichal/6c12a3b6500052052b92e6ce9a173529).

Not a great experience but it is still possible to get functionality that we had prior to version ~3.18.

**Comment by pielgrzym** [comment]
@mattmichal thanks for sharing this - I also did manage to configure this, but I passed the service token via module variable - I'll try removing this part if per your suggestion :) 

I actually migrated away from env variables thanks to this issue - `tfvars` file work better for me since I have a lot of different CF/AWS accounts to manage.

**Comment by pielgrzym** [comment]
@mattmichal ah, you pass whole providers block to the module. I just redefined them there and passed only the var with service key. I hate how hacky this looks. Why can't we just have a dedicated provider variable for the ca stuff? It's probably like 3 lines of go instead of hundreds of lines of useless boilerplate all over tf setup :angry:

**Comment by pielgrzym** [comment]
@mattmichal your approach is much better. creating a local provider declaration in a module causes issues while removing the module (one needs to manually perform a targetted destroy before removing the module from tf file).

**Comment by ruimarinho** [comment]
Here's my take on getting all resources available today (as of v3.26.0) working with vanilla terraform (I might add a few terragrunt examples later on):

```terraform
# main.tf
terraform {
  required_version = "~> 1.0"
  required_providers {
    cloudflare = {
      source                = "cloudflare/cloudflare"
      version               = "~> 3.26"
      configuration_aliases = [cloudflare.user_service_key, cloudflare.email_api_key, cloudflare.fixed_account_id]
    }
  }
}

# providers.tf
provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

provider "cloudflare" {
  alias                = "user_service_key"
  api_user_service_key = var.cloudflare_api_user_service_key
}

provider "cloudflare" {
  alias                = "email_api_key"
  api_key              = var.cloudflare_api_key
  email                = var.cloudflare_email
}

provider "cloudflare" {
  alias                = "fixed_account_id"
  account_id           = var.cloudflare_account_id
  api_token            = var.cloudflare_api_token
}

# api_tokens.tf
data "cloudflare_api_token_permission_groups" "all" {
  provider = cloudflare.email_api_key
}

# origin_ca_certificates.tf
resource "cloudflare_origin_ca_certificate" "example" {
  provider = cloudflare.user_service_key
  …
}

# worker_scripts.tf
resource "cloudflare_worker_script" "example" {
  provider = cloudflare.fixed_account_id
  …
}

# workers_kv_namespaces.tf
resource "cloudflare_workers_kv_namespace" "example" {
  provider = cloudflare.fixed_account_id
  …
}
```

Then create a `terraform.tfvars` with:

```terraform
cloudflare_account_id = ""
cloudflare_api_key = ""
cloudflare_api_token = ""
cloudflare_api_user_service_key = ""
cloudflare_email = ""
```

Everything else will use the default `cloudflare` provider configured with an API Token. Some of these resources will be fixed once v4 is released.

**Comment by adrian-gierakowski** [comment]
this is completely backwards

instead of pushing the complexity of creating separate provider (for just the one resource) on the user, the provider should be smart enough to choose which credentials to use for which resource

I'm sticking to 3.22 until this is properly fixed

**Comment by orlandothoeny** [comment]
Are you planning to fix this, or do we have to build ugly workarounds because the provider doesn't handle this properly by itself?

**Comment by petero-dk** [comment]
Looking at the code for the provider it should be possible to set one or the other to a string empty value which would eliminate it, however it does not seem like that is working.

Because the first check is a null check (https://github.com/cloudflare/terraform-provider-cloudflare/blob/eeb7b33accaa91dee5b1ce0a698ab6c47ccd0853/internal/framework/provider/provider.go#L273), and the second check is a string empty check (https://github.com/cloudflare/terraform-provider-cloudflare/blob/eeb7b33accaa91dee5b1ce0a698ab6c47ccd0853/internal/framework/provider/provider.go#L279)

However there is a regex validation for the apikey so that never gets that far. That check does not exist on the APIUserServiceKey, however even when that is set to an explicit "" in the provider config, it still picks up the environment variable.

I would be cool to allow an explicit "" for both api_token and api_user_service_key that way the providers could be configured like this:

```
provider "cloudflare" {
  alias                = "user_service_key"
  api_user_service_key = var.cloudflare_api_user_service_key
  api_token = "" #explicitly set to ""
}

provider "cloudflare" {
  alias                = "fixed_account_id"
  account_id           = var.cloudflare_account_id
  api_token            = var.cloudflare_api_token
  api_user_service_key = "" #explicitly set to ""
}

```

**Comment by adrian-gierakowski** [comment]
oh wow, years later and this has not been fixed?

give that this is an official cloudflare project, the devs are making a bad name for their employer
