### ISSUE TITLE
Support Worker Domains

### ISSUE THREAD

**Issue by davidbarratt** [cloudflare/terraform-provider-cloudflare#1921]
### Current Terraform and Cloudflare provider version

Latest

### Description

Support Worker Domains

Feature: https://developers.cloudflare.com/workers/platform/routing/custom-domains/
API: https://api.cloudflare.com/#worker-domain-properties

### Use cases

I would like to attach a domain to a worker

### Potential Terraform configuration

```hcl
...
```

**Comment by OJFord** [comment]
Also a `data "cloudflare_workers_subdomain"` resource would be good - to determine the `<subdomain>.workers.dev` when a custom domain is not in use. (I suppose also a `resource` to configure this, if it's possible over the API.)

It's currently not possible for a module to determine (programmatically/without this being supplied as a variable) the endpoint for any workers it creates.

**Comment by OJFord** [comment]
@jacobbednarz Judging from the merged PR above, I think `workflow/pending-upstream-library` can be removed?

**Comment by serhiianyline** [comment]
Are there any estimations, when this might get some attention?
