### ISSUE TITLE
Pages project should have deployments enabled by default

### ISSUE THREAD

**Issue by SebastiaanYN** [cloudflare/terraform-provider-cloudflare#1924]
### Current Terraform and Cloudflare provider version

Terraform v1.2.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.24.0
+ provider registry.terraform.io/hashicorp/vault v3.7.0

### Description

Currently the default value for `deployments_enabled` in the `pages_project` resource is `false`. This should instead be `true`.

### Use cases

Setting `deployments_enabled` to `true` by default or explicitly documenting that it's `false` by default would prevent unnecessary confusion surrounding a project being created but seeing no deployments.

### Potential Terraform configuration

```hcl
resource "cloudflare_pages_project" "example" {
  account_id        = var.account_id
  name              = "example"
  production_branch = "master"

  build_config {
    build_command   = "yarn build"
    destination_dir = "build"
  }

  source {
    type = "github"

    config {
      owner               = "cloudflare"
      repo_name           = "1.1.1.1"
      production_branch   = "master"
      pr_comments_enabled = false
    }
  }
}
```

**Comment by WalshyDev** [comment]
CC: @Cyb3r-Jak3 

we default these if not provided but Terraform provides everything and does it's own defaulting.

Few other properties that should have specific defaults too which I can grab next week

**Comment by LanceSandino** [comment]
Getting this too

``` Error: error creating new Cloudflare client: invalid credentials: key & email must not be empty
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"].global,
│   on versions.tf line 40, in provider "cloudflare":
│   40: provider "cloudflare" {
│```

**Comment by jacobbednarz** [comment]
curious, is there a use case where we don't ever want a resource to automatically deploy? seems like this is the safe guard to prevent things from accidentally being deployed if another system manages it.
