### ISSUE TITLE
Cannot specify type = drop for cloudflare_email_routing_catch_all

### ISSUE THREAD

**Issue by yan12125** [cloudflare/terraform-provider-cloudflare#1937]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
$ ./terraform -v
Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.24.0
```

### Affected resource(s)

cloudflare_email_routing_catch_all

### Terraform configuration files

```hcl
terraform {
    required_providers {
        cloudflare = {
            source = "cloudflare/cloudflare"
        }
    }
}

provider "cloudflare" {
    api_token = "0123456789012345678901234567890123456789"
}

resource "cloudflare_email_routing_catch_all" "foobar" {
    zone_id = "YYY"
    name = "Catch-all rule"
    enabled = true
    matcher {
        type = "all"
    }
    action {
        type = "drop"
        value = []
    }
}
```

### Link to debug output

https://gist.github.com/yan12125/f683cbbd61c09b8e2544c30cd6acad37

### Expected output

Catch-all rule for email routing is enabled and configured to drop all mails.

### Actual output

The provider does not like type = drop for `cloudflare_email_routing_catch_all`.

### Steps to reproduce

1. Run `terraform plan`

### Additional factoids

Per https://api.cloudflare.com/#email-routing-routing-rules-update-catch-all-rule, the catch-all rule accepts type = drop, forward or worker.

**Comment by jacobbednarz** [comment]
moving to enhancement as this is a new option. 

feel free to send over a PR if you'd it addressed immediately.

**Comment by yan12125** [comment]
Thanks! It's not urgent. I may have a look recently.
