### ISSUE TITLE
`origin_traffic` setting for rate limiting rules keep set to true always

### ISSUE THREAD

**Issue by ivanfavi** [cloudflare/terraform-provider-cloudflare#1944]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
terraform -v
Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.24.0
```

### Affected resource(s)

cloudflare_rate_limit

### Terraform configuration files

```hcl
resource "cloudflare_rate_limit" "login_users" {
  zone_id     = var.account_id
  description = "Protect login (users)"
  disabled    = false

  threshold = 10
  period    = 60

  match {
    request {
      url_pattern = "${var.domain}/login"
      schemes     = ["HTTP", "HTTPS"]
      methods     = ["POST"]
    }
    response {
      origin_traffic = false
      headers = [
        {
          name  = "Cf-Cache-Status"
          op    = "ne"
          value = "HIT"
        }
      ]
    }
  }

  action {
    mode = "managed_challenge"
  }
}
```

### Link to debug output

https://gist.github.com/ivanfavi/667d1d4cf7a52e09c62eb135b89fa34b

### Expected output

We expect no changes

### Actual output

```
Terraform will perform the following actions:

  # cloudflare_rate_limit.register_managed_challenge will be updated in-place
  ~ resource "cloudflare_rate_limit" "register_managed_challenge" {
        id                  = "ef4c146a92954c26b897af007f42be85"
        # (6 unchanged attributes hidden)

      ~ match {

          ~ response {
              ~ origin_traffic = true -> false
                # (2 unchanged attributes hidden)
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to reproduce

1. Create rate limiting rule with setting `origin_traffic` set to false
2. Apply changes
3. Plan changes again

**Comment by jacobbednarz** [comment]
closing this one out as unresolved since `cloudflare_rate_limit` has been superseded by `cloudflare_ruleset` and we are unlikely to spend any more effort on addressing these older resources in the near future.
