### ISSUE TITLE
Support for custom_metadata at Custom Hostname resource

### ISSUE THREAD

**Issue by 7jPUn4w8caDX** [cloudflare/terraform-provider-cloudflare#1949]
### Current Terraform and Cloudflare provider version

Terraform v0.14.5
+ provider registry.terraform.io/cloudflare/cloudflare v3.24.0

### Description

The custom_metadata value can be added/modified by using the API [Edit Custom Hostname](https://api.cloudflare.com/#custom-hostname-for-a-zone-edit-custom-hostname).

However, this is not available via Terraform yet at [cloudflare_custom_hostname](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_hostname)

### Use cases

By adding this functionality via Terraform, it allow us to keep the configuration at a single place. Also enable us to add this information as soon as the Certificate is created without the need of a separate external call.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
closed by #2107
