### ISSUE TITLE
Errors Creating Loadbalancer Pools  - error creating load balancer pool: Could not route to /accounts/load_balancers/pools, perhaps your object identifier is invalid? (7003), No route for that URI (7000)

### ISSUE THREAD

**Issue by beaudryj** [cloudflare/terraform-provider-cloudflare#1952]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Cloudflare v.3.25
Terraform 1.3.2

### Affected resource(s)

cloudflare_load_balancer_pool

### Terraform configuration files

```hcl
resource "cloudflare_load_balancer_pool" "foo" {
  name = "example-pool"
  origins {
    name = "example-1"
    address = "192.0.2.1"
    enabled = false
  }
  origins {
    name = "example-2"
    address = "192.0.2.2"
  }
}
```

### Link to debug output

https://gist.github.com/beaudryj/d63c5e7526e6d567a306304bec009e33

### Expected output

A loadbalancer pool is created

### Actual output

Errors above

### Steps to reproduce

Terraform init
Terraform plan
Terraform apply

### Additional factoids

I removed the tokens and cookies from the Gist

error creating load balancer pool: Could not route to /accounts/load_balancers/pools, perhaps your object identifier is invalid? (7003), No route for that URI (7000)

**Comment by jacobbednarz** [comment]
Thank you for reporting this issue! For maintainers to dig into issues it is required that all issues include the entirety of `TF_LOG=DEBUG` output to be provided. The only parts that should be redacted are your user credentials in the `X-Auth-Key`, `X-Auth-Email` and `Authorization` HTTP headers. Details such as zone or account identifiers are not considered sensitive but can be redacted if you are very cautious. This log file provides additional context from Terraform, the provider and the Cloudflare API that helps in debugging issues. Without it, maintainers are very limited in what they can do and may hamper diagnosis efforts.

This issue has been marked with `triage/needs-information` and is unlikely to receive maintainer attention until the log file is provided making this a complete bug report.

**Comment by beaudryj** [comment]
Hey @jacobbednarz i left that out on the ticket as a gist as requested - https://gist.github.com/beaudryj/d63c5e7526e6d567a306304bec009e33

**Comment by jacobbednarz** [comment]
There is client context setup missing. The only things that should be redacted are your credentials, not the log output.

**Comment by beaudryj** [comment]
@jacobbednarz let me know if this is better -https://gist.github.com/beaudryj/28a957882f8b2352bf6e77888cd24308

**Comment by beaudryj** [comment]
@jacobbednarz does it have to do with - 
```POST /client/v4/accounts//load_balancers/pools HTTP/1.1``` why is there 2x // on the post

**Comment by jacobbednarz** [comment]
that does help, thanks. from the logs, it looks like you're not setting `account_id` in your provider configuration. 

```hcl
provider "cloudflare" {
  # ...
  account_id = "<account id>"
?
```

i just went searching in the [docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/load_balancer_pool) for the note about this but could only find it on the [`cloudflare_load_balancer_monitor`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/load_balancer_monitor) documentation.

> When creating a monitor, you have to pass account_id to the provider configuration in order to create account level resources. Otherwise, by default, it will be a user level resource.

(ignore the second part, we don't do that in the provider anymore)

this will only be a short term requirement as #1646 is tracking moving this attribute directly onto the resource and removing this hurdle.

> does it have to do with -
> `POST /client/v4/accounts//load_balancers/pools HTTP/1.1` why is there 2x // on the post between accounts and load_balancers

yep, this is a symptom of the value missing but the logs confirm it. the account ID is empty and the URL is lacking the value.

**Comment by beaudryj** [comment]
awesome, thank you :)

**Comment by omarabid** [comment]
> this will only be a short term requirement as https://github.com/cloudflare/terraform-provider-cloudflare/issues/1646 is tracking moving this attribute directly onto the resource and removing this hurdle.

Maybe disable the deprecated notice?
