### ISSUE TITLE
Wrong error message with api_token shorter than expected

### ISSUE THREAD

**Issue by samuelbarata** [cloudflare/terraform-provider-cloudflare#1966]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.25.0
+ provider registry.terraform.io/hashicorp/google v4.40.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/template v2.2.0

Your version of Terraform is out of date! The latest version
is 1.3.2. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

registry.terraform.io/cloudflare/cloudflare

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.25"
    }
  }
}

provider "cloudflare" {
  api_token = "XXXXXXXXXXXXXXXXXXXXX"
}
```

### Link to debug output

https://gist.github.com/samuelbarata/c709c6d2226232adc49dfad5a02d2bbc

### Expected output

╷
│ Error: invalid value for api_token (API tokens must contain exatcly 40 characters)
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on terraform-gcp-provider.tf line 15, in provider "cloudflare":
│   15:   api_token = "XXXXXXXXXXXXXXXX"
│ 
╵

### Actual output

╷
│ Error: invalid value for api_token (API tokens must only contain characters a-z, A-Z, 0-9, hyphens and underscores)
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on terraform-gcp-provider.tf line 15, in provider "cloudflare":
│   15:   api_token = "XXXXXXXXXXXXXXXX"
│ 
╵

### Steps to reproduce

declare the terraform provider with a token shorted than expected
```tf
provider "cloudflare" {
  api_token = "XXXXXXXXXXXXXXXXXXXXXXXX"
}
```

### Additional factoids

When I copied the api token from cloudflare I accidentally missed the last caracters
The error says that `API tokens must only contain characters a-z, A-Z, 0-9, hyphens and underscores` even tho it does
The error should be that the token in incomplete

**Comment by jacobbednarz** [comment]
the validation message for this lives at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/provider.go. i'm happy to review a PR for this one.
