### ISSUE TITLE
Creating CAA records fails

### ISSUE THREAD

**Issue by roy-work** [cloudflare/terraform-provider-cloudflare#1968]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.25.0
```
(Note: running under TFE; this is local output. TFE is running v1.2.4)

### Affected resource(s)

* `cloudflare_record`

### Terraform configuration files

```hcl
resource "cloudflare_record" "caa_issue_godaddy" {
  zone_id = data.cloudflare_zones.[snip]_com.zones[0].id
  name = "[snip].com"
  value = "0 issue \"godaddy.com\""
  type = "CAA"
  ttl = 24 * 60 * 60  # 24 hr
}
```

### Link to debug output

https://example.com

### Panic output

N/A

### Expected output

The change to apply, or we get a decent error message about why they fail to apply. The UI just tells us "400 Bad Request", which isn't a usable diagnostic. Even going to the debug logs, all we get is,
```
"message": "flags is a required data field."
```
… which is useless: we are supplying `flags`. (`flags` is the `0` at the front of the record's content. The resource itself does not offer a `flags` attribute.)

### Actual output

The change errors. The debug log provides the most insight:

```
2022-10-13T17:58:40.874Z [DEBUG] provider.terraform-provider-cloudflare_v3.25.0: Cloudflare API Request Details:
---[ REQUEST ]---------------------------------------
POST /client/v4/zones/[snip]/dns_records HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.2.4 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/3.25.0
Content-Length: 201
Authorization: Bearer REDACTED
Content-Type: application/json
Accept-Encoding: gzip

{
"created_on": "0001-01-01T00:00:00Z",
"modified_on": "0001-01-01T00:00:00Z",
"type": "CAA",
"name": "[snip].com",
"content": "0 issue \"godaddy.com\"",
"zone_id": "[snip]",
"ttl": 86400
}
[snip]
2022-10-13T17:58:41.157Z [DEBUG] provider.terraform-provider-cloudflare_v3.25.0: Cloudflare API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 400 Bad Request
Cf-Cache-Status: DYNAMIC
Cf-Ray: 7599f6f9f9fc5a3f-IAD
Content-Type: application/json
Date: Thu, 13 Oct 2022 17:58:41 GMT
Server: cloudflare
Set-Cookie: __cfruid=[snip]; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 12

{
"result": null,
"success": false,
"errors": [
{
"code": 1004,
"message": "DNS Validation Error",
"error_chain": [
{
"code": 9101,
"message": "flags is a required data field."
}
]
}
],
"messages": []
}
```

### Steps to reproduce

Attempt to add a CAA `issue` record. AFAICT, CF's validation rules changed at some point in a way that the Provider can't cope with. (This would not be the first change in CF's validation logic that we've witnessed.)

### References

Additionally, the Cloudflare provider fails to report the error. The only error the UI gets is,
```
Error: failed to create DNS record: HTTP status 400: DNS Validation Error (1004)
```
… which is worthless. One has to go to the debug logs to get "more" information.

> Do not truncate or trim the output as the surrounding context is useful for debugging and without it, maintainers are restricted in what assistance and diagnosis they can provide.

The output contains credentials, which is _another_ bug in this provider.

**Comment by jacobbednarz** [comment]
the resource usage is incorrect for a CAA record. it doesn't use `value` (simple values) but the `data` block since it needs additional properties. you can see an example of this in our tests https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_record_test.go#L713-L722. i can't speak for the when/if this changed in the API (best lodge a support ticket for the DNS team if you need to know more) but the expected usage for complex records (CAA/SRV/LOC) has always been to use the `data` block to ensure we build the correct payload with the conditional fields so this may have just been working by accident.

**Comment by roy-work** [comment]
I'll look into `data`, and see if I can get it to work. But _even if_ that's the case, there's still a number of bugs present here:

* `data` is [completely undocumented](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record#data), AFAICT.
* the logs contain access credentials, yet the bug report flow wants you to post unadulterated logs. Since redacting them is some effort, and AFAICT there's no way to purge them from TFE (meaning I've leaked the cred to anyone w/ Read access to our instance…) … the provider shouldn't log them.
* the diagnostics the provider gives doesn't help the user in arriving at a solution
