### ISSUE TITLE
cloudflare_access_application missing validation for type="private_ip"

### ISSUE THREAD

**Issue by csautter** [cloudflare/terraform-provider-cloudflare#1974]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Tested with:
- Terraform v1.1.8
- Terraform v1.3.2
- cloudflare v3.25.0

### Affected resource(s)

- cloudflare_access_application 

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "test" {
  account_id       = local.cloudflare_account_id
  name             = "test"
  type             = "private_ip"
  session_duration = "24h"
}
```

### Link to debug output

https://gist.github.com/csautter/2f2bd62cd48ae5f11d51d913ba946f77

### Panic output

````
╷
│ Error: expected type to be one of [self_hosted saas ssh vnc bookmark], got private_ip
│
│   with cloudflare_access_application.test,
│   on cloudflare_access_application_prox_backup_1.tf line 11, in resource "cloudflare_access_application" "test":
│   11:   type             = "private_ip"
│
╵
````

### Expected output

Ressource **cloudflare_access_application** accepts `type  = "private_ip"`

### Actual output

Error: expected type to be one of [self_hosted saas ssh vnc bookmark], got private_ip

### Steps to reproduce

1. set `type  = "private_ip"`

### Additional factoids

It's possible to import a ressource with `type="private_ip"` but actually it isn't possible to set this value in terraform code.
````txt
$ terraform import "cloudflare_access_application"."test" .../..
$ terraform state show "cloudflare_access_application"."test"
# cloudflare_access_application.test:
resource "cloudflare_access_application" "test" {
    account_id                 = "<removed>"
    allowed_idps               = []
    app_launcher_visible       = true
    aud                        = "<removed>"
    auto_redirect_to_identity  = false
    enable_binding_cookie      = false
    http_only_cookie_attribute = false
    id                         = "<removed>"
    name                       = "test"
    service_auth_401_redirect  = false
    skip_interstitial          = false
    type                       = "private_ip"
}

````
Looking at the API Docs it seems that `type="private_ip"`  is undocumented.
https://api.cloudflare.com/#access-applications-add-the-access-app-launcher

### References

https://github.com/cloudflare/terraform-provider-cloudflare/blob/3735851da7b4597ca4c69b65e34473039235c91d/internal/provider/schema_cloudflare_access_application.go#L49

Related Pull Request: https://github.com/cloudflare/terraform-provider-cloudflare/pull/1975

**Comment by jacobbednarz** [comment]
this is intentional as the APIs are still considered unstable; see https://github.com/cloudflare/terraform-provider-cloudflare/pull/1975#issuecomment-1297136226. closing until the team decides the API is stable enough to add public API supprt.
