### ISSUE TITLE
[Terraform | Pages | Record DNS] 

### ISSUE THREAD

**Issue by rafaellucio** [cloudflare/terraform-provider-cloudflare#1976]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
➜  workspace terraform -v
Terraform v1.3.0
on darwin_arm64
```

### Affected resource(s)

* cloudflare_pages_project
* cloudflare_pages_domain
* cloudflare_record

Scenário:
cloudflare pages project: gangoffront-com
cloudflare pages domain: https://staging.gangoffront-com.pages.dev
CNAME: https://staging.gangoffront.com

**Step 1**
![Screen Shot 2022-10-13 at 16 40 21](https://user-images.githubusercontent.com/2213926/195694088-a4e76608-5379-4b00-847d-3ea86c4c4888.png)

**Step 2**
![Screen Shot 2022-10-13 at 16 38 23](https://user-images.githubusercontent.com/2213926/195694081-51799d3e-795f-4656-a3c7-bb9110809388.png)

**Step 3** I can't edit content in this page, this create an incorrect CNAME
![Screen Shot 2022-10-13 at 16 39 02](https://user-images.githubusercontent.com/2213926/195694084-cd4e8b54-e9cf-4540-b644-7f2b594ed02a.png)

**Step 4** I need edit this record to correct pages domain alias
![Screen Shot 2022-10-13 at 16 48 56](https://user-images.githubusercontent.com/2213926/195695701-52c7886f-cbd9-4314-842d-08cc31cec8d1.png)

When I finish this manually, finally works, but when I use terraform to create record type CNAME it don't resolve the staging alias
 

### Terraform configuration files

```hcl
# Production
resource "cloudflare_pages_project" "gangoffront_com" {
  account_id        = var.account_id
  name              = "gangoffront-com"
  production_branch = "main"
  build_config {
    destination_dir = "build"
    build_command   = "npm run build"
    root_dir        = "/"
  }
  source {
    type = "github"
    config {
      owner                         = "gang-of-front"
      repo_name                     = "gangoffront.com"
      production_branch             = "main"
      pr_comments_enabled           = true
      deployments_enabled           = false
      production_deployment_enabled = false
      preview_branch_includes       = ["preview"]
      preview_branch_excludes       = ["main"]
    }
  }
}

resource "cloudflare_record" "gangoffront_com_pages" {
  name    = var.domain
  proxied = true
  ttl     = 1
  type    = "CNAME"
  value   = format("%s.pages.dev", var.project_name)
  zone_id = var.zone_id
}

# Staging Environment
resource "cloudflare_pages_domain" "staging" {
  account_id   = var.account_id
  project_name = var.project_name
  domain       = format("staging.%s.pages.dev", var.project_name)
}

resource "cloudflare_record" "staging_gangoffront_com_pages" {
  name    = "staging"
  proxied = true
  ttl     = 1
  type    = "CNAME"
  value   = format("staging.%s.pages.dev", var.project_name)
  zone_id = var.zone_id
}
```

### Link to debug output

https://gist.github.com/rafaellucio/905f2d40df9e557dbc8c9a562df68fb9

### Panic output

Domain is unavailable (8000018)

### Expected output

Create domain and add record correctly

## Link

[run-GfPQDhyupUcnxoVo-apply-log.txt](https://github.com/cloudflare/terraform-provider-cloudflare/files/9780585/run-GfPQDhyupUcnxoVo-apply-log.txt)

### Steps to reproduce

1. Create cloudflare_pages_project using terraform with terraform cloud
2. Create cloudflare_pages_domain using terraform 
3. Update CNAME to your alias using a cloudflare_record using terraform 

### References

https://github.com/gang-of-front/gangoffront.com/blob/main/terraform/cloudflare.tf
https://developers.cloudflare.com/pages/platform/custom-domains/#add-a-custom-cname-record
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_domain

**Comment by Cyb3r-Jak3** [comment]
If I remember this correctly, you shouldn't need
```hcl
resource "cloudflare_record" "staging_gangoffront_com_pages" {
  name    = "staging"
  proxied = true
  ttl     = 1
  type    = "CNAME"
  value   = format("staging.%s.pages.dev", var.project_name)
  zone_id = var.zone_id
}
```
The API should create the DNS record for the custom domain.

**Comment by rafaellucio** [comment]
> ou shouldn't nee

@Cyb3r-Jak3 I only use `cloudflare_record` to fix record incorrect cname that was created by `cloudflare_pages_domain`

This terraform below create a new record
``` 
type: CNAME 
name: staging
target: project_name.pages.dev
```

```terraform
resource "cloudflare_pages_domain" "staging" {
  account_id   = var.account_id
  project_name = var.project_name
  domain       = format("staging.%s.pages.dev", var.project_name)
}
```

This are incorrect because the alias is: staging.project_name.pages.dev, it should be create like this
```
type: CNAME
name: staging
target: staging.project_name.pages.dev
```

**Comment by Cyb3r-Jak3** [comment]
I don't believe that pages domains are meant to be set to using `.pages.dev` and should be mapped to your domain instead. If you can complete the debugging step and I can look into it further.

**Comment by WalshyDev** [comment]
```
resource "cloudflare_pages_domain" "staging" {
  account_id   = var.account_id
  project_name = var.project_name
  domain       = format("staging.%s.pages.dev", var.project_name)
}
```

This is incorrect, you need to be using your custom domain here. pages.dev domains are not accepted (and would cause an infinite loop pages.dev -> pages.dev -> pages.dev -> ...)

You need to create the project, add the CNAME and add the custom domain `staging.<your-domain>` and this will be good.

**Comment by rafaellucio** [comment]
Thank you @WalshyDev 

My job is simple, but I can't do that using Terraform

Step 1: Create project `my-project.pages.dev`
Step 2: Connect a custom domain type CNAME `my-project.domain.com -> my-project.pages.dev`
Step 3: Create staging environment like `staging.my-project.domain.com`
Step 4: Connect the new environment with Cloudflare Pages alias like 
`staging.my-project.domain.com -> staging.my-project.pages.dev`

**Comment by WalshyDev** [comment]
Why doesn't it work? do you get an error? what error? what is created, what isn't?

I don't have the bandwidth to dig much into this for a few days so as much info as you can give is helpful.

**Comment by rafaellucio** [comment]
@WalshyDev sorry for my confusion, i made your change suggestion [in this comment](https://github.com/cloudflare/terraform-provider-cloudflare/issues/1976#issuecomment-1287831032) and it just works 🎉 , i was falling into the infinite loop and i was getting an error like:

```
Error: Missing required argument
on cloudflare.tf line 82, in resource "cloudflare_pages_domain" "staging":
resource "cloudflare_pages_domain" "staging" {
The argument "domain" is required, but no definition was found.
```

or

```
Error: error creating domain for project "5df477d4f9a8cf72185ef8f44fd1e144": Domain is unavailable (8000018)
with cloudflare_pages_domain.prod
on cloudflare.tf line 65, in resource "cloudflare_pages_domain" "prod":
resource "cloudflare_pages_domain" "prod" {
```

Thanks you so much for your help
