### ISSUE TITLE
Rewrite URL ruleset does not accept empty query value

### ISSUE THREAD

**Issue by menti-ashfaq** [cloudflare/terraform-provider-cloudflare#1978]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Cloudflare Provider version: `3.21.0`
Terraform `v1.2.6`
on darwin_arm64

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
{
  "resource": {
    "cloudflare_ruleset": {
      "_xxx": {
        "//": {
          "metadata": {
            "path": "_/xxx",
            "uniqueId": "_xxx_23A0D403"
          }
        },
        "description": "Strip off params from URLs unless whitelisted",
        "kind": "zone",
        "name": "Strip off params from URLs unless whitelisted",
        "phase": "http_request_transform",
        "rules": [
          {
            "action": "rewrite",
            "action_parameters": {
              "uri": {
                "query": {
                  "value": ""
                }
              }
            },
            "description": "Strip off params from URLs unless whitelisted",
            "enabled": true,
            "expression": "(http.host eq \"www.xxx.com\" and not http.request.uri.path contains \"/_next/\" and not http.request.uri.query contains \"integration=\" and not http.request.uri.path contains \"/core/\")"
          }
        ],
        "zone_id": "${data.cloudflare_zones._xxx.zones[0].id}"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/menti-ashfaq/a7b7ed5ec67e06541a92cf621a461015

### Panic output

No panic output

### Expected output

Cloudflare transform rule is created with an empty query string

### Actual output

Error: error updating ruleset with ID "bd07aa07f8004fcba1b67dd299c6da71": invalid input

### Steps to reproduce

1. Define the resource described in Terraform configuration files
2. terraform apply

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1306

**Comment by jacobbednarz** [comment]
what is the resource definition you are using here?

**Comment by menti-ashfaq** [comment]
> what is the resource definition you are using here?

We use Typescript and TF-CDK tooling to execute Terraform operations. The JSON above in the “Terraform configuration files” is the synthesized configuration. The following would be the representation of what it would look like in HCL:
```
resource "cloudflare_ruleset" "blabla" {
  zone_id     = "redacted"
  name        = "Strip off params from URLs unless whitelisted"
  description = "Strip off params from URLs unless whitelisted"
  kind        = "zone"
  phase       = "http_request_transform"

  rules {
    action = "rewrite"
    action_parameters {
      uri {
        query {
          value = ""
        }
      }
    }

    expression  = "(http.host eq \"www.xxx.com\" and not http.request.uri.path contains \"/_next/\" and not http.request.uri.query contains \"integration=\" and not http.request.uri.path contains \"/core/\")"
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled     = true
  }
}
```

**Comment by jacobbednarz** [comment]
to get this to work, i suspect you'll need to do:

```hcl
action_parameters {
  uri {
    query {
      value = " "
    }
  }
}
```

as `query { value = "" }` is a nil and zero value for the internal Terraform type. both `GetOk` and `GetOkExists` return that the value hasn't been changed from a default/zero value meaning there isn't a great way to determine if the value should be sent or not.

let me know if this works for you.

**Comment by menti-ashfaq** [comment]
```
query {
      value = " "
    }
```
Adding space in `value`, does seem to work. However, it is adding `%20` when the request is sent to the server (for ex: `/how-to?%20`), which is not the actual solution we are looking for.  It should be like this `/how-to` to avoid any issues

**Comment by jacobbednarz** [comment]
in that case, there isn't a way to do this with the current schema and internal terraform types. will need some investigation what we want to do here to allow empty strings.

**Comment by menti-ashfaq** [comment]
> will need some investigation what we want to do here to allow empty strings.

Great. Thank you so much for your time and support. Is there any estimated time you could provide when it will be resolved?

**Comment by jamielinux** [comment]
I came across this problem too. 

When creating transform rules on the Cloudflare dashboard, it's possible to add a rule to rewrite the query to an empty query. It's not currently possible to do this with the Cloudflare Terraform provider.

I assume the priority right now is 4.x, but I have my fingers crossed this might get a look at in the future!

**Comment by jamielinux** [comment]
Thank you @jacobbednarz ! :rocket:
