### ISSUE TITLE
Detect the firewall version

### ISSUE THREAD

**Issue by danielmotaleite** [cloudflare/terraform-provider-cloudflare#1980]
### Current Terraform and Cloudflare provider version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.24.0
+ provider registry.terraform.io/hashicorp/aws v4.33.0

### Description

I have several domains, ones still in the old WAF rule based config, others already upgraded to the new waf ruleset base setup. they share some modules and now i have rules that do not apply in the ruleset and ruleset that fail to apply in the rule based setup. So i'm locked, all settings from the not current firewall system will fail, so i can't test them to try to bypass their config

Is any way to detect in what firewall system i am, that doesn't fail? or the only option is to manually track them in a tfvar?  If there isn't, can you please add some way? Probably a data source with the list of available capabilities 

### Use cases

Multi domain config, slowly migrating smaller domains to the new firewall, while still supporting the bigger domains in the old firewall

I understand that most people don't have many domains, nor have mixed configs, but bigger setups can't migrate everything at same time

### Potential Terraform configuration

```
resource "cloudflare_waf_group" "common_exceptions" {
  zone_id  = var.zone_id
  group_id = "6293bbf04711b8511fc68dfd85d254b3"
  mode     = "on"
}
```
This fail in new firewall, but work in the old one, need something to enable/disable this using count

**Comment by jacobbednarz** [comment]
hi 👋 i'm afraid we don't publicly expose what version of the WAF is enabled for an account and it's not something the service team are looking to do. instead, you'll need to manually keep track of it in your module somewhere. 

i generally avoid modules to prevent this sort of coupling however, you could add a new attribute that defaults to the older WAF unless you explicitly opt-in and only apply those resources for the version of the WAF you are targeting.

**Comment by danielmotaleite** [comment]
thanks for the reply :)
i don't actually need the real version, just something that returns "ruleset: true/false" depending if it is available or not... that in the future could be used to flag other new features... but i understand
i will add a variable to each domain them... when i find a easy way to detect that using the API, i don't want to manually check and update all the domains to see in the GUI what capability i do have available  :)
Thanks for the terraform provider!
