### ISSUE TITLE
Split tunnel rewrites all records that were added manually

### ISSUE THREAD

**Issue by ivarabyeu** [cloudflare/terraform-provider-cloudflare#1982]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0

### Affected resource(s)

cloudflare_split_tunnel
cloudflare_fallback_domain

### Terraform configuration files

```hcl
resource "cloudflare_split_tunnel" "example_split_tunnel_include" {
  account_id = "8eec24742fdcde3335b4dfae9ed26f27"
  mode       = "include"
  tunnels {
    address  = "10.0.0.0/16"
    description = "example domain"
  }
}

resource "cloudflare_fallback_domain" "example" {
  account_id = "8eec24742fdcde3335b4dfae9ed26f27"
  domains {
    suffix      = "example.domain"
    description = "Example domain"
    dns_server  = ["10.84.0.2"]
  }
}
```

### Link to debug output

https://gist.github.com/ivarabyeu/69c67ad2f793c5c8528d8c60e8278ec2

### Expected output

After applying provider should merge records that were added manually with those newly added by terraform

### Actual output

Provider removes all records that were added manually and adds only new one

### Steps to reproduce

1. Add route to split tunnel and local domain to domain fallback in Zero Trust configuration manually 
2. Run terraform apply to add a new route and domain
3. Go to UI.
4. Run terraform destroy, as result empty routes and domains

**Comment by jacobbednarz** [comment]
I'm afraid this isn't how Terraform works. the expectation is that Terraform takes the configuration you have and applies it to the remote API while maintaining the lifecycle of that resource; there is no merge behaviour. if you have existing resources, they need to either be imported or added to the configuration you apply.

**Comment by astephanh** [comment]
Hi, please /reopen because this is a bug. 

Maybe "merge" is misunderstood here. It should be possible to have several cloudflare_split_tunnel Resources which don't interfere. 

The Resource cloudflare_split_tunnel should behave the same way as cloudflare_tunnel_route does. 

this is working:

```
# Create IP Cidr Routing through Tunnel if warp_routing is enabled
resource "cloudflare_tunnel_route" "zero_trust_tunnel_services_ipv4" {
  account_id = var.account_id
  tunnel_id  = cloudflare_argo_tunnel.gke_tunnel.id
  network    = var.gke_ipv4_range_services
  comment    = "Kubernetes Services (IPv4)"
}
resource "cloudflare_tunnel_route" "zero_trust_tunnel_services_ipv5" {
  account_id = var.account_id
  tunnel_id  = cloudflare_argo_tunnel.gke_tunnel.id
  network    = var.gke_ipv5_range_services
  comment    = "Kubernetes Services (IPv5)"
}
```

But this is NOT working (as _all_ entries are overwritten)

```
resource "cloudflare_split_tunnel" "idp" {
  account_id = var.account_id
  mode = "include"
  tunnels {
    host = "okta.com"
    description = "My IdP"
  }
}

resource "cloudflare_split_tunnel" "warp_routing" {
  account_id = var.account_id
  mode = "include"
  tunnels {
    host = "mydomain.cloudflareaccess.com"
    description = "Warp internal Routing"
  }
}

```

**Comment by gitHubCoCoder** [comment]
@astephanh Do you have any workaround this? I'm encountering the same issue. It's very weird that this is closed as not planned.
