### ISSUE TITLE
Resource cloudflare_certificate_pack has mandatory `certificate_authority` and `validation_method` fields

### ISSUE THREAD

**Issue by ruimarinho** [cloudflare/terraform-provider-cloudflare#1989]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0

### Affected resource(s)

`cloudflare_certificate_pack`

### Terraform configuration files

```hcl
resource "cloudflare_certificate_pack" "foobar" {
  cloudflare_branding = false
  hosts               = ["*.foobar.com", "foobar.com"]
  type                = "advanced"
  validity_days       = 365
  zone_id             = cloudflare_zone.foobar.id
 }
```

### Link to debug output

https://gist.github.com/ruimarinho/08f980893a40fe2006a4dc5908388eda

### Expected output

These arguments are optional.

### Actual output

These arguments are required.

### Steps to reproduce

Run `terraform plan` with a certificate pack issued by `CloudflareInc` (type=`advanced`).

**Comment by jacobbednarz** [comment]
these fields are optional because they are not used for all types of certificate packs. you'll need to refer to the documentation to determine what the correct combination is for your use case.

**Comment by ruimarinho** [comment]
@jacobbednarz the issue is precisely the opposite, i.e., they are mandatory but should be optional.

**Comment by jacobbednarz** [comment]
sorry, i was thinking of the previous iteration of this that supported `custom` and `advanced` certificates whereas now, we only have ACM (advanced).

these fields are required in the API (https://api.cloudflare.com/#certificate-packs-order-advanced-certificate-manager-certificate-pack) so the provider will also be enforcing this requirement too. if this is an older certificate, you may need to adjust the resource according to those updates.

**Comment by ruimarinho** [comment]
No worries. I’ll check the creation date but I believe this is quite new for Enterprise customers where `CloudflareInc` becomes the issuer.

If you look at the dashboard API requests (which I used a lot to debug these kind of issues) does not list those two fields for this certificate pack.

**Comment by ruimarinho** [comment]
The certificate pack is from 2019 so not so new after all. Here's what the UI shows:

<img width="848" alt="Screenshot 2022-10-22 at 12 50 31" src="https://user-images.githubusercontent.com/288709/197337901-22c41325-34ce-47a9-af1b-b1e2718c27a0.png">

Unlike other certificate packs, no certificate authority or validation method fields are displayed (because the API doesn't have them on the response).
