### ISSUE TITLE
invalid value for api_token

### ISSUE THREAD

**Issue by sephethus** [cloudflare/terraform-provider-cloudflare#1990]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0
+ provider registry.terraform.io/hashicorp/google v4.41.0

### Affected resource(s)

cloudflare provider
cloudflare_record

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# Create a record
resource "cloudflare_record" "admin" {
  zone_id = "mydomain.org"
  name    = local.ws_vars["admin-addr"]
  value   = google_compute_global_address.admin-lb-addr.address
  type    = "A"
  ttl     = 3600
}

resource "cloudflare_record" "center" {
  zone_id = "mydomain.org"
  name    = local.ws_vars["center-addr"]
  value   = google_compute_global_address.sc-lb-addr.address
  type    = "A"
  ttl     = 3600
}
```

### Link to debug output

https://gist.github.com/sephethus/2776039e1f05b58afe86ae4d9ad9ce21

### Expected output

successfully added 2 resources

### Actual output

error posted in the main 

Despite generating two different TOKENS in cloudflare for my account I still get the following error when trying to apply terraforms for the CloudFlare provider:

>invalid value for api_token (API tokens must be 40 characters long and only contain characters a-z, A-Z, 0-9, hyphens and underscores)
│ 
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on provider.tf line 16, in provider "cloudflare":
│   16:   api_token = var.cloudflare_api_token

Clearly the terraform version 1.3.3 is out of sync with the kinds of tokens generated in CloudFlare, this is an edit zone token so it should work, right?

### Steps to reproduce

1. Generate token in cloudflare for edit zone
2. Follow the documented steps or config above

### Additional factoids

I realize there are keys and tokens, this is a token. If terraform thinks my token format is invalid it is therefore out of touch with any tokens over the last 2 years.

### References

No

**Comment by sephethus** [comment]
Ok so I had to go find other documentation to determine where and how to locate the logs since you guys don't really provide this pertinent information in your TF_LOG documentation. I've updated the gist link it should work, I think.

**Comment by sephethus** [comment]
Added log again, realized it was a private gist and needed to make it public, I hardly use this

**Comment by sephethus** [comment]
https://gist.github.com/sephethus/2776039e1f05b58afe86ae4d9ad9ce21

**Comment by jacobbednarz** [comment]
i've confirmed API tokens are working (existing and new) so this is something local to your setup. i'd suggest going through first and making sure your API token works with an API call such as the verify API token endpoint (https://api.cloudflare.com/#user-api-tokens-verify-token) before trying to use it in Terraform.

**Comment by sephethus** [comment]
Ok but they're not even passing your validation test. They work on my end. 

{"result":{"id":"0c6c8f5fb8c6b4854d0f6c624da9457c","status":"active","expires_on":"2024-10-31T23:59:59Z"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}%   

So what is the issue? It's failing due to that error above.

**Comment by drewmercer-bl** [comment]
I seem to be having the same problem...

**Comment by bessmertnyip0ni** [comment]
I have that problem too.

**Comment by Bheinle** [comment]
In case it helps anyone, I just found my issue. I was looking at the global API key under the Token section. Once I created a token it started working.
