### ISSUE TITLE
Fail plans when API keys have insufficient permissions

### ISSUE THREAD

**Issue by Shadowfiend** [cloudflare/terraform-provider-cloudflare#1994]
### Current Terraform and Cloudflare provider version

Terraform: 1.2.9
Provider: 3.23.0

### Description

Currently, running a `terraform plan` will not check if a resource's actions are possible with the permissions from the given Cloudflare API key. It would be wonderful if `plan` could fail actions that wouldn't have permissions during an `apply`, so that a successful `plan` better predicted a successful `apply` later.

### Use cases

The use case here is when terraform is used to manage a subset of Cloudflare functionality, for example DNS, and new functionality is added (e.g., page rules). Ideally the Cloudflare API key only has the permissions needed to make the changes that are currently being managed by terraform; however, in the above scenario, a `plan` would not warn the user that running `apply` would result in a permissions error for the page rule changes.

### Potential Terraform configuration

Configuration unchanged!

**Comment by jacobbednarz** [comment]
thanks for the suggestion however, it is an intentional decision that the Terraform provider doesn't do additional permission introspection for requests; it's just far too complex to duplicate. instead, we rely on the remote systems to perform the evaluation and return messages accordingly.

**Comment by Shadowfiend** [comment]
> instead, we rely on the remote systems to perform the evaluation and return messages accordingly.

Is there a good place that I could request this behavior for the remote system so that the provider can reflect it in that case? In our specific case the key had no privileges whatsoever to page rules, but still planned a change successfully, implying it didn't attempt to hit a remote system at all.

**Comment by jacobbednarz** [comment]
resource creation via `terraform plan` doesn't hit the remote. as there is no ID matching in the state file, it only determines a resource will be created.
