### ISSUE TITLE
Default `action_mode` and `sensitivity` being set for managed WAF packages

### ISSUE THREAD

**Issue by ruimarinho** [cloudflare/terraform-provider-cloudflare#1997]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0
```

### Affected resource(s)

`cloudflare_waf_package`

### Terraform configuration files

```hcl
resource "cloudflare_waf_package" "owasp" {
  package_id = "<package_id>"
  action_mode = "simulate"
  sensitivity = "low"
  zone_id     = cloudflare_zone.myzone_com.id
}

resource "cloudflare_waf_package" "cloudflare" {
  package_id = "<package_id>"
  zone_id = cloudflare_zone.myzone_com.id
}

resource "cloudflare_waf_package" "user" {
  package_id = "<package_id>"
  zone_id = cloudflare_zone.myzone_com.id
}
```

### Link to debug output

https://gist.github.com/ruimarinho/9fc325070741c8cd8b5f065c7b05d0bf

### Expected output

No planned changes to `sensitivity` or `action_mode` settings.

### Actual output

```terraform
  # cloudflare_waf_package.cloudflare will be updated in-place
  ~ resource "cloudflare_waf_package" "cloudflare" {
      + action_mode = "challenge"
        id          = "<id>"
      + sensitivity = "high"
        # (2 unchanged attributes hidden)
    }

  # cloudflare_waf_package.user will be updated in-place
  ~ resource "cloudflare_waf_package" "user" {
      + action_mode = "challenge"
        id          = "<id>"
      + sensitivity = "high"
        # (2 unchanged attributes hidden)
    }
```

### Steps to reproduce

There are three managed WAF packages bundled by Cloudflare:

- Cloudflare Managed Ruleset (name on API: `CloudFlare`)
<img width="815" alt="image" src="https://user-images.githubusercontent.com/288709/198245998-554068ea-4b6b-4a4a-b745-55f943acd17e.png">

- Package: OWASP ModSecurity Core Rule Set (name on API: `OWASP ModSecurity Core Rule Set`)
<img width="805" alt="image" src="https://user-images.githubusercontent.com/288709/198246032-9b1528a5-e25e-4696-b738-80cf0e3ddd64.png">

- Customer Requested Rules (name on API: `USER`)
<img width="801" alt="image" src="https://user-images.githubusercontent.com/288709/198246073-49baaa38-a7ec-4804-a886-8d00cfe38c94.png">

Unlike the built-in OWASP package, both CloudFlare and USER packages don't offer sensitivity nor action settings. 

Importing these packages will result in a state representation does *not* include the `sensitivity` nor `action_mode` attributes, as expected (both via the UI and the API that powers the dashboard).

### References

Somewhat related to #1845.

**Comment by jacobbednarz** [comment]
similar to #1845, I would recommend migrating to the new WAF as these resources will be deprecated in the near future. given the resources are planned for deprecation, it's unlikely we'll spend effort on this before that happens so I'm going to close this one out.

**Comment by ruimarinho** [comment]
Understood. I think like many other folks here it's not clear on which version of WAF we are in, specially since the nomenclature is very similar between them. Thanks for the feedback.
