### ISSUE TITLE
Getting Cloudflare pages project by ID seems to be not supported anymore

### ISSUE THREAD

**Issue by stankolubomir** [cloudflare/terraform-provider-cloudflare#1998]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.3
Cloudflare provider 3.26.0

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
resource "cloudflare_pages_project" "example" {

  account_id        = "my-account-id"
  name              = "example-custom-pages-project"
  production_branch = "main"
}
```

### Link to debug output

https://gist.github.com/stankolubomir/435c37b0ee6d280a1dbc2e729eb25626

### Expected output

Terraform passes without an error, or updates cloudflare pages according to configuration.

### Actual output

Terrraform fails on project not found error. But it is not true, because the cloudflare page project exists.

### Steps to reproduce

1.  Create new cloudflare page project using terraform
2.  Rerun the terraform to check if cloudflare page project is in sync - here it fails on project not found exception.

### Additional factoids

I've tried to get the cloudflare pages project via API using the project ID and the output is in fact the error "Project not found".

```
$ curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/my-account-id/pages/projects/1cb492c0-6cb1-45e5-b07b-48385466b76a" -H "Authorization: Bearer ${CF_API_KEY}"
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 8000007,
      "message": "Project not found"
    }
  ],
  "messages": []
}
```

Although I see in the cloudflare api docu, that getting details about cloudflare pages project should not be done via project ID, but via project name.
So I've tried again to get the project via API using the project name and this works without the problem.

```
$ curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/my-account-id/pages/projects/my-example-project-1" -H "Authorization: Bearer ${CF_API_KEY}"
{
  "result": {
    "id": "1cb492c0-6cb1-45e5-b07b-48385466b76a",
    "name": "my-example-project-1",
...
```

https://api.cloudflare.com/#pages-project-get-projects
`GET accounts/:account_identifier/pages/projects/:project_name`

All in all - cloudflare pages project resource is now completely broken as Cloudflare now supports to get cloudflare pages project via API using only the project name. So the resource should be updated accordingly.

**Comment by stankolubomir** [comment]
Debug log is in the gist attached also in the first post:
https://gist.github.com/stankolubomir/68ce1f9369565a42449926cba4519840

**Comment by stankolubomir** [comment]
Updated log file in first post to: https://gist.github.com/stankolubomir/435c37b0ee6d280a1dbc2e729eb25626

**Comment by jacobbednarz** [comment]
@WalshyDev should project IDs still work? or is it only project names now?

**Comment by WalshyDev** [comment]
We have only ever accepted the name and that is what Cloudflare-go and this provider _should_ be doing too

If this has broken recently, then it seems to have been from the provider now using the ID over name... 

This should make it use the name though right?
https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_pages_project.go#L294

**Comment by stankolubomir** [comment]
@WalshyDev It seems, that this commit introduced the bug: https://github.com/cloudflare/terraform-provider-cloudflare/commit/679244042f0cdf450825b3a7278369d9d6f011f1

It seems that the create is setting projectName as ID as you wrote, but this is not the case for update and delete which are now broken.

**Comment by stankolubomir** [comment]
Although workaround is to rollback to cloudflare provider version `3.23.0`.

**Comment by jacobbednarz** [comment]
the `Update` and `Delete` don't set the resource ID, only use it in API calls. I suspect you created the resource prior to the fix to use the name for the ID so it's still attempting to use the old one. 

can you `terraform state rm` the existing resource and import your pages project? that should give it the correct ID. alternatively, manually update the state to use the name for the identifier.

**Comment by stankolubomir** [comment]
So all is working well after reimporting all cloudflare pages projects under the new provider version `3.26.0+`.

The better documentation in the changelog about breaking changes would be appreciated in the future.

**Comment by jacobbednarz** [comment]
i'd say this came about due to releasing the provider and then needing to fix it to use the name due to the API constraint. 

we can look at including that in the changelog for future changes if it happens again.
