### ISSUE TITLE
🐛 api_token and api_user_service_key is required for Origin CA certs

### ISSUE THREAD

**Issue by DevStarOps** [cloudflare/terraform-provider-cloudflare#1999]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.2
on windows_amd64

### Affected resource(s)

Initialization... although cloudflare_origin_ca_certificate doesn't work without the key and fails auth with just api token

### Terraform configuration files

```hcl
provider "cloudflare" {
  api_client_logging = false
  api_user_service_key = var.cloudflare_origin_ca_key  
  api_token = var.cloudflare_api_token
}
```

### Link to debug output

n/a

### Expected output

both service key and api token should work together

### Actual output

an error saying you can't

### Steps to reproduce

initialize provider as shown in the configuration section above

**Comment by jacobbednarz** [comment]
this is explained in more detail with options at #1919. you should not be using service keys and API tokens in the same API calls as they are two different authentication mechanisms.

**Comment by DevStarOps** [comment]
So basically version pin old version 😅... getting a certificate for an app service or vm and configuring the dns for that same hardware you've just spun up feels like a totally reasonable and normal thing to do.

Is your suggestion to build all your infra and then run a 2nd terraform configuration to apply DNS settings?

**Comment by jacobbednarz** [comment]
i wouldn't recommend staying on an old version but it's entirely up to you. 

> Is your suggestion to build all your infra and then run a 2nd terraform configuration to apply DNS settings?

no, please see the linked issue for options. there are ways available where you can keep your configuration together if you want.

**Comment by DevStarOps** [comment]
Great stuff, thank you 😊
