### ISSUE TITLE
`cloudflare_fallback_domain` does not create unique entries

### ISSUE THREAD

**Issue by nniehoff** [cloudflare/terraform-provider-cloudflare#2002]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.8
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.26.0
```

### Affected resource(s)

- cloudflare_fallback_domain

### Terraform configuration files

```hcl
resource "cloudflare_fallback_domain" "test1" {
  account_id = var.account_id
  domains {
    suffix      = "example.com"
    description = "Testing"
    dns_server  = ["192.168.1.1"]
  }
}

resource "cloudflare_fallback_domain" "test2" {
  account_id = var.account_id
  domains {
    suffix      = "somewhere.com"
    description = "Testing 2"
    dns_server  = ["192.168.2.1"]
  }
}
```

### Link to debug output

https://gist.github.com/nniehoff/4825d754a7ca28b969bfa6f1e3f36c52

### Expected output

I expect fallback domains to be created for both `example.com` and `somewhere.com` and appended to the list of existing fallback domains.

In addition after an apply of the above terraform code a plan should reveal no changes necessary.

### Actual output

All fallback domains are removed from the list of fallback domains and only 1 domain is added either `example.com` or `somewhere.com`.

In addition after an apply of the above terraform code a plan reveals the domain fallback entry which was created should be destroyed in order to create the new one.

```
Terraform will perform the following actions:

  # cloudflare_fallback_domain.test1 will be updated in-place
  ~ resource "cloudflare_fallback_domain" "test1" {
        id         = "XXX"
        # (1 unchanged attribute hidden)

      - domains {
          - description = "Testing 2" -> null
          - dns_server  = [
              - "192.168.2.1",
            ] -> null
          - suffix      = "somewhere.com" -> null
        }
      + domains {
          + description = "Testing"
          + dns_server  = [
              + "192.168.1.1",
            ]
          + suffix      = "example.com"
        }
    }

```

### Steps to reproduce

1.  Create a fresh Cloudflare zero-trust account
2. Manually add a few DNS domain fallback entries
3. Apply the provided terraform code
4. inspect the domain fallback entries

### Additional factoids

If you really need debug output I can try to dig it out of the environment but I'm hoping the description is enough to go on.  Maybe this works as designed but I feel at the very least the documentation should be updated to reflect this.  I wasn't expecting ALL of the domain fallback entries created by others for the entire account to be destroyed.

**Comment by jacobbednarz** [comment]
for multiple entries, they are defined in the one resource; see the second example at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/fallback_domain. 

it is intentional that this resource overwrites all entries. if you'd like to keep the defaults, you need to explicitly include them.
