### ISSUE TITLE
exceeded maximum number of zone rulesets for phase 'http_request_cache_settings'

### ISSUE THREAD

**Issue by huoqi** [cloudflare/terraform-provider-cloudflare#2004]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform v0.14.5
provider 3.26.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "HIDEDOMAIN_cache_rules" {
  zone_id     = cloudflare_zone.HIDEDOMAIN_zone.id
  name        = "default rule"
  description = "TF default rule"
  kind        = "zone"
  phase       = "http_request_cache_settings"

  rules {
    action = "set_cache_settings"
    expression = "(http.host contains \"HIDEDOMAIN\" and (http.request.uri.path matches \"^/([a-z]{2})(-[A-Z]{2,3})/\") or (http.request.uri matches \"^/([a-z]{2})(-[A-Z]{2,3})?/.*\") or http.request.uri.path eq \"/\")"
    description = "default fe rule"
    enabled = true
    action_parameters {
      edge_ttl {
        mode    = "override_origin"
        default = 120
        status_code_ttl {
          status_code_range {
            from = 400
            to   = 599
          }
          value = 0
        }
      }
      browser_ttl {
        mode = "respect_origin"
      }
      cache_key {
        ignore_query_strings_order = true
        cache_deception_armor      = true
        custom_key {
          query_string {
            include = ["*"]
          }
          header {
            include        = ["header1", "header2", "header3"]
            exclude_origin = false
          }
          cookie {
            include        = ["cookie1", "cookie2", "cookie3", "cookie4", "cookie5", "cookie6", "cookie7", "cookie8", "cookie9"]
          }
          host {
            resolved = false
          }
        }
      }
      origin_error_page_passthru = true
    }
  }
  rules {
    action = "set_cache_settings"
    expression = "(http.host contains \"HIDEDOMAIN\" and http.request.uri.path matches \"^/.*\")"
    description = "default be rule"
    enabled = true
    action_parameters {
      edge_ttl {
        mode    = "override_origin"
        default = -1
      }
      browser_ttl {
        mode = "respect_origin"
      }
      origin_error_page_passthru = true
    }
  }
}
```

### Link to debug output

https://gist.github.com/huoqi/d91aede255128986c8841847a0807b2f

### Expected output

To create cache rule successfully.

### Actual output

Error
{
  "result": null,
  "success": false,
  "errors": [
    {
      "message": "exceeded maximum number of zone rulesets for phase 'http_request_cache_settings'"
    }
  ],
  "messages": null
}

### Steps to reproduce

1. remove all cache rule form console
2. create cache rule terraform

**Comment by garrettgalow** [comment]
If you ever have created any cache rules in the dashboard, then what is likely happening is even if you removed the rules from the dash, the ruleset itself wasn't removed. I'm guessing you can only have one cache rule ruleset per zone. You will need to delete the ruleset via https://api.cloudflare.com/#zone-rulesets-delete-a-zone-ruleset and then create via TF

**Comment by jacobbednarz** [comment]
> BTW, is it a bug that the ruleset still needs to be deleted by API?

nope, intentional. there isn't a way to remedy the resources created by the dash and terraform so the end user needs to manually intervene.

**Comment by gyula-s** [comment]
I'd like to emphasize that this situation isn't clear-cut, and it should be viewed as a potential issue. The dashboard should provide identical data to what the API offers. 

I believe it's not reasonable for the dashboard to misrepresent the current state of the rules.

**Comment by desidotnet** [comment]
> I'd like to emphasize that this situation isn't clear-cut, and it should be viewed as a potential issue. The dashboard should provide identical data to what the API offers.
> 
> I believe it's not reasonable for the dashboard to misrepresent the current state of the rules.

I whole-heartedly agree with the above - it took me almost 2.5 hours to figure out why I kept getting an error during debugging of a script we have in place.  Dashboard did not show that there was a mistaken ruleset, had to manually query rulesets for the domain I was working on and only then I realized that an unintentional ruleset was preventing any further rulesets addition or update.

**Comment by josip-stanic** [comment]
Seems to me that the issue is that once you create a ruleset of phase `http_request_cache_settings` in the dashboard that the `cloudflare_ruleset` gets created with the rule you configure manually, once you remove the manually configured rule it gets deleted leaving you with an "empty" `cloudflare_ruleset` (effectively with: `"rules: []"`) which is definitely akward but not something that the provider should clean up, so I get @jacobbednarz's response. Probably the API should remove the ruleset automatically once the last rule gets removed.

In our scenario `https://api.cloudflare.com/client/v4/zones/x/rulesets` returns:
```json
{
	"result": [
		...
		{
			"id": "d3ec5e334af74e91ba3bc2f88262e67a",
			"name": "default",
			"description": "",
			"kind": "zone",
			"version": "4",
			"last_updated": "2023-10-27T12:11:32.820269Z",
			"phase": "http_request_cache_settings"
		}
	],
	"success": true,
	"errors": [],
	"messages": []
}
```

`https://api.cloudflare.com/client/v4/zones/x/rulesets/d3ec5e334af74e91ba3bc2f88262e67a` returns:
```json
{
	"result": {
		"id": "d3ec5e334af74e91ba3bc2f88262e67a",
		"name": "default",
		"description": "",
		"kind": "zone",
		"version": "4",
		"last_updated": "2023-10-27T12:11:32.820269Z",
		"phase": "http_request_cache_settings"
	},
	"success": true,
	"errors": [],
	"messages": []
}
```
note the missing `result.rules` key. I guess the odd thing is that the API allows you to create a ruleset without specifying any rule (maybe there is a case where this is needed).

**Comment by landsman** [comment]
I just bump to the same issue. I do not have any ruleset in the dashboard...

**Comment by landsman** [comment]
> If you ever have created any cache rules in the dashboard, then what is likely happening is even if you removed the rules from the dash, the ruleset itself wasn't removed. I'm guessing you can only have one cache rule ruleset per zone. You will need to delete the ruleset via https://api.cloudflare.com/#zone-rulesets-delete-a-zone-ruleset and then create via TF
> 
> To confirm my suspicions you can run https://api.cloudflare.com/#zone-rulesets-list-zone-rulesets to see if there is already a ruleset with the cache rule phase present

you're right, when I did api request directly I can see that there is already deleted record:

```json
    {
      "id": "3b1354cbe4a34d9296939969e23fcb7c",
      "name": "non-www to www redirect",
      "description": "Redirect non-www to www",
      "kind": "zone",
      "version": "3",
      "last_updated": "2023-10-21T21:25:21.883756Z",
      "phase": "http_request_dynamic_redirect"
    },
```

Where is the bug? On Cloudflare side?
