### ISSUE TITLE
edge_ttl default attribute should not be required when mode is "respect_origin"

### ISSUE THREAD

**Issue by pbrumblay** [cloudflare/terraform-provider-cloudflare#2007]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0

### Affected resource(s)

- cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "respect_origin_headers" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_cache_settings"
  zone_id = var.zone_id
  rules {
    action      = "set_cache_settings"
    description = "respect-origin-headers"
    enabled     = false
    expression  = "(http.request.full_uri contains \"https://api.example.io/api/\")"
    action_parameters {
      browser_ttl {
        mode = "respect_origin"
      }
      edge_ttl {
        mode = "respect_origin"
      }
      cache = true
    }
  }
}
```

### Link to debug output

https://gist.github.com/pbrumblay/d17eedf1f31d765a89c6f084384ec50b

### Expected output

I expected the provider to not require the `default` attribute when settting the edge_ttl mode to respect_origin since it is not valid in that context.

### Actual output

Error: error creating ruleset default: default is useless in respect_origin mode, default cannot be 0
│ 
│   with cloudflare_ruleset.REDACTED,
│   on main.tf line 57, in resource "cloudflare_ruleset" "REDACTED":
│   57: resource "cloudflare_ruleset" "REDACTED" {

### Steps to reproduce

1. Create a page rule as above. 
2. Make sure that edge_ttl and browser_ttl is set to respect_origin
3. Attempt to run a plan
4. Note that the provider complains that default is a required attribute for edge_ttl
5. Add default = 0
6. Note that plan succeeds
7. Attempt to apply
8. Note that Cloudflare API complains that default should not be set with edge_ttl set to respect_origin.

### Additional factoids

In my opinion, this line should be `false`: https://github.com/cloudflare/terraform-provider-cloudflare/blob/60f491cc1f66cacd1bc8fe30826370f6037108c2/internal/provider/schema_cloudflare_ruleset.go#L584.

You will want to cover this API weirdness in the documentation of this block to indicate that default is required for other modes: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#nestedblock--rules--action_parameters--edge_ttl

**Comment by amit-dube-b24** [comment]
We faced this issue today. It's kind of a deadlock.
- default value is required by provider for edge_ttl block
- but when supplied with mode = respect_zone, we get error "default is useless in respect_origin mode"

We are kind of block due to this. Is there any update on priority on this issue?

**Comment by Michael-Ohme** [comment]
Hi, 
thank you [pbrumblay](https://github.com/pbrumblay) for your well formulated bug report, it fit exactly in my problem.

I can also reproduce the issue in Cloudflare version **v3.28.0**. 

- Terraform:  v1.3.0
- Cloudflare: v3.28.0

**Comment by amit-dube-b24** [comment]
Hello @zwilias and @jacobbednarz - It seems that this doesn't fix the problem. While making this variable optional helped executing terraform plan correctly, it now fails with terraform apply. It seems the default value is set to 0 which is causing issue further in the code.

error creating ruleset <ruleset_name> : **default is useless in **respect_origin** mode, default cannot be 0**
Terraform: v1.3.0
Cloudflare: v3.32.0
