### ISSUE TITLE
An argument named "origin" is not expected here. Did you mean to define a block of type "origin"?

### ISSUE THREAD

**Issue by puzzledvacuum** [cloudflare/terraform-provider-cloudflare#2011]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```bash
$ terraform -v
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0
+ provider registry.terraform.io/datadog/datadog v2.26.1
+ provider registry.terraform.io/hashicorp/aws v3.75.2
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/http v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/integrations/github v4.31.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.4.6
```

### Affected resource(s)

Only `cloudflare_ruleset`.

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "http_origin_example" {
  zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
  name        = "Change to some origin"
  description = "Change origin for a route"
  kind        = "zone"
  phase       = "http_request_origin"

  rules {
    action = "route"
    action_parameters {
      host_header = "some.host"
      origin = {
        host = "some.host"
        port = 80
      }
    }
    expression  = "(http.request.uri.path matches \"^/api/\")"
    description = "change origin to some.host"
    enabled     = true
  }
}
# should be =>
resource "cloudflare_ruleset" "http_origin_example" {
  zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"
  name        = "Change to some origin"
  description = "Change origin for a route"
  kind        = "zone"
  phase       = "http_request_origin"

  rules {
    action = "route"
    action_parameters {
      host_header = "some.host"
      origin {
        host = "some.host"
        port = 80
      }
    }
    expression  = "(http.request.uri.path matches \"^/api/\")"
    description = "change origin to some.host"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/puzzledvacuum/c066c0b89197e938d4a974929784a5b2

### Expected output

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_ruleset.http_origin_example will be created
  + resource "cloudflare_ruleset" "http_origin_example" {
      + description = "Change origin for a route"
      + id          = (known after apply)
      + kind        = "zone"
      + name        = "Change to some origin"
      + phase       = "http_request_origin"
      + zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"

      + rules {
          + action      = "route"
          + description = "change origin to some.host"
          + enabled     = true
          + expression  = "(http.request.uri.path matches \"^/api/\")"
          + id          = (known after apply)
          + ref         = (known after apply)
          + version     = (known after apply)

          + action_parameters {
              + host_header = "some.host"
              + version     = (known after apply)

              + origin {
                  + host = "some.host"
                  + port = 80
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

### Actual output

╷
│ Error: Unsupported argument
│ 
│   on test.tf line 13, in resource "cloudflare_ruleset" "http_origin_example":
│   13:       origin = {
│ 
│ An argument named "origin" is not expected here. Did you mean to define a block of type "origin"?

### Steps to reproduce

1. Copy the documented sample: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#nestedblock--rules--action_parameters--overrides
2. Request a plan
3. Recieve an error

**Comment by jacobbednarz** [comment]
looks like we need a documentation update here. happy to review a PR addressing this one. check out https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md on how the documentation is generated if you want to pursue this one.

**Comment by tenaciousdlg** [comment]
https://github.com/cloudflare/terraform-provider-cloudflare/pull/2020

PR for doc update
