### ISSUE TITLE
Explicitly added cipher configuration is not removed when code is removed

### ISSUE THREAD

**Issue by georgekaz** [cloudflare/terraform-provider-cloudflare#2013]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.27.0

But also I've tested on earlier versions

### Affected resource(s)

cloudflare_zone_settings_override

### Terraform configuration files
Updating from
```hcl
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
    ciphers = [
      "ECDHE-ECDSA-AES128-GCM-SHA256",
      "ECDHE-ECDSA-AES256-GCM-SHA384",
      "ECDHE-ECDSA-CHACHA20-POLY1305",
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-RSA-AES256-GCM-SHA384",
      "ECDHE-RSA-CHACHA20-POLY1305",
    ]
  }
}
```
To
```hcl
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
  }
}
```

### Link to debug output

https://gist.github.com/georgekaz/f34d7a1cb8206176f0cdb37ca5672f46

### Expected output

I expect a Terraform plan that reverts zone settings to their default state when the configuration is removed

### Actual output

Terraform says there are no changes to be made

### Steps to reproduce

1. Start with a cloudflare_zone_settings_override section which has no ciphers section
```
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
  }
}
```
2. Add ciphers
```
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
    ciphers = [
      "ECDHE-ECDSA-AES128-GCM-SHA256",
      "ECDHE-ECDSA-AES256-GCM-SHA384",
      "ECDHE-ECDSA-CHACHA20-POLY1305",
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-RSA-AES256-GCM-SHA384",
      "ECDHE-RSA-CHACHA20-POLY1305",
    ]
  }
}
```
3. Create a Terraform plan. The output should include:
```
~ resource "cloudflare_zone_settings_override" "zone_settings_override" {
        id                       = "XXX"
        # (6 unchanged attributes hidden)

      ~ settings {
          ~ ciphers                     = [
              + "ECDHE-ECDSA-AES128-GCM-SHA256",
              + "ECDHE-ECDSA-AES256-GCM-SHA384",
              + "ECDHE-ECDSA-CHACHA20-POLY1305",
              + "ECDHE-RSA-AES128-GCM-SHA256",
              + "ECDHE-RSA-AES256-GCM-SHA384",
              + "ECDHE-RSA-CHACHA20-POLY1305",
            ]
```
4. Apply the plan. It should succeed
5. Remove the block like so:
```
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
  }
}
```
6. Create a Terraform plan.

At this point I expect there to be some planned changes, to set ciphers back to an empty list i.e: I expect
```
      ~ settings {
          ~ ciphers                     = [
              - "ECDHE-ECDSA-AES128-GCM-SHA256",
              - "ECDHE-ECDSA-AES256-GCM-SHA384",
              - "ECDHE-ECDSA-CHACHA20-POLY1305",
              - "ECDHE-RSA-AES128-GCM-SHA256",
              - "ECDHE-RSA-AES256-GCM-SHA384",
              - "ECDHE-RSA-CHACHA20-POLY1305",
            ]
```
but I get `No changes. Infrastructure is up-to-date.`

### Additional factoids

After removing the `ciphers` code block, running 
`curl -H"X-Auth-Email: $CLOUDFLARE_EMAIL" -H"X-Auth-Key: $CLOUDFLARE_API_KEY" https://api.cloudflare.com/client/v4/zones/xxx/settings/ciphers`
returns 
`{"result":{"id":"ciphers","value":["ECDHE-ECDSA-AES128-GCM-SHA256","ECDHE-ECDSA-AES256-GCM-SHA384","ECDHE-ECDSA-CHACHA20-POLY1305","ECDHE-RSA-AES128-GCM-SHA256","ECDHE-RSA-AES256-GCM-SHA384","ECDHE-RSA-CHACHA20-POLY1305"],"modified_on":null,"editable":true},"success":true,"errors":[],"messages":[]}`

Therefore proving that the state has not been returned to it's initial state.

WORKAROUND:
A workaround is to do this in 2 steps, but it means being aware of the problem.
1. Remove all the ciphers from the list but leave an empty list
```
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
    ciphers = [ ]
  }
}
```
2. Terraform plan and apply
3. Totally remove ciphers from the code
```
resource "cloudflare_zone_settings_override" "zone_settings_override" {
  zone_id = cloudflare_zone.myzone.id
  settings {
  }
}
```

**Comment by jacobbednarz** [comment]
this is a known bug due to the way that specific resource operates. it manages an additional layer on top of the terraform state for the "defaults" but it needs to be able to detect the changes in the resource, which when you fully remove the setting, it cannot.

there are no plans to address this in the `cloudflare_zone_setting_override` resource as the way it is built has subtle bugs like this and doesn't allow partial zone setting management. instead, we're building out a new resource that will be a simpler and specific interface for managing settings in a 1:1 fashion. i don't have an ETA on this but it will be coming in the future and the `cloudflare_zone_setting_override` resource will be marked as deprecated for removal.
