### ISSUE TITLE
Can't use cloudflare_managed_headers

### ISSUE THREAD

**Issue by gonzalob** [cloudflare/terraform-provider-cloudflare#2015]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

My project has a resource of type cloudflare_managed_headers, with which I configured managed headers some time ago.
When I execute a terraform plan now, I get the following error message:

```
╷
│ Error: error reading managed headers: missing the permissions required to list zone rulesets in the http_request_late_transform_managed phase
│ 
│   with cloudflare_managed_headers.site,
│   on rules.tf line 14, in resource "cloudflare_managed_headers" "site":
│   14: resource "cloudflare_managed_headers" "site" {
│ 
 ```

I don't have any reference to http_request_late_transform_managed on my project. I've been testing with different API tokens, even with one created with the "Read Everything" template from Cloudflare[1]. I can't get past this error.

I've upgraded the cloudflare provider to v3.27.0. Still no luck.
Any pointers as to how can I provide additional information is more than welcome.

Thanks!

[1]

```
This API token will affect the below accounts and zones, along with their respective permissions


All accounts - Magic Network Monitoring:Read, HTTP Applications:Read, D1:Read, Pub/Sub:Read, Turnstile:Read, Intel:Read, Email Routing Addresses:Read, Cloudflare Pages:Read, Bulk URL Redirects:Read, Magic Firewall:Read, L3/4 DDoS Managed Ruleset:Read, Transform Rules:Read, Select Configuration:Read, Account WAF:Read, Magic Firewall Packet Captures:Read, Workers R2 Storage:Read, Magic Transit:Read, Cloudflare Images:Read, DDoS Protection:Read, Account Rulesets:Read, IP Prefixes:Read, Workers Tail:Read, Account Analytics:Read, Cloudflare Tunnel:Read, Access: Mutual TLS Certificates:Read, Access: Device Posture:Read, Access: Service Tokens:Read, Access: Audit Logs:Read, Logs:Read, Rule Policies:Read, Account Filter Lists:Read, IP Prefixes: BGP On Demand:Read, Zero Trust:Read, Access: Organizations, Identity Providers, and Groups:Read, Workers KV Storage:Read, Workers Scripts:Read, Load Balancing: Monitors And Pools:Read, Account Firewall Access Rules:Read, DNS Firewall:Read, Stream:Read, Billing:Read, Account Settings:Read, Access: Apps and Policies:Read
All zones - Custom Pages:Read, Config Rules:Read, Dynamic Redirect:Read, API Gateway:Read, Cache Rules:Read, Custom Error Rules:Read, Zaraz:Read, Email Routing Rules:Read, Origin Rules:Read, Managed Headers:Read, Web3 Hostnames:Read, Transform Rules:Read, HTTP DDoS Managed Ruleset:Read, Sanitize:Read, Bot Management:Read, Zone WAF:Read, Health Checks:Read, Waiting Rooms:Read, Access: Apps and Policies:Read, Zone Settings:Read, Zone:Read, DNS:Read, Workers Routes:Read, SSL and Certificates:Read, Logs:Read, Page Rules:Read, Load Balancers:Read, Firewall Services:Read, Analytics:Read
All users - Memberships:Read, User Details:Read

```

### Affected resource(s)

cloudflare_managed_headers

### Terraform configuration files

```hcl
resource "cloudflare_managed_headers" "site" {
  zone_id = cloudflare_zone.site.id

  managed_request_headers {
    id      = "remove_visitor_ip_headers"
    enabled = true
  }

  managed_response_headers {
    id      = "remove_x-powered-by_header"
    enabled = true
  }

  managed_response_headers {
    id      = "add_security_headers"
    enabled = true
  }
}
```

### Link to debug output

https://gist.github.com/gonzalob/3e144fbda1e0284e0724459ee0f3aebe

### Expected output

The plan to complete.

### Actual output

Operation failed: failed running terraform plan (exit 1)

### Steps to reproduce

Apply a terraform plan, with a resource of type cloudflare_managed_headers

**Comment by jacobbednarz** [comment]
thanks for raising this but as it's not a Terraform error (the error is coming from the API about your permissions), there isn't really anything we can do here from the provider aspect. 

i would recommend you try with an API key/email combo and if that still fails, open a Cloudflare support ticket that can be triaged and routed to the service team if needed.,

**Comment by gonzalob** [comment]
In case this is useful to someone, I got this running by adding the "Managed headers Write" and "Zone Transform Rules Write" permission groups. "Read" was not enough even though Cloudflare complains about listing and getting resources.
