### ISSUE TITLE
What api token permission is required to use cloudflare_total_tls 

### ISSUE THREAD

**Issue by bitsofinfo** [cloudflare/terraform-provider-cloudflare#2019]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Using latest terraform

### Affected resource(s)

cloudflare_total_tls 

### Terraform configuration files

```hcl
resource "cloudflare_total_tls" "this" {
  zone_id = var.cloudflare_dns_zone_id
  enabled               = true
  certificate_authority = "lets_encrypt"
}
```

### Link to debug output

none

### Panic output

│ Error: error creating updating total TLS: Authentication error (10000)

### Expected output

The resource works 

│ Error: error creating updating total TLS: Authentication error (10000)

### Actual output

│ Error: error creating updating total TLS: Authentication error (10000)

### Steps to reproduce

│ Error: error creating updating total TLS: Authentication error (10000)

### Additional factoids

What specific api token permission is required to be able to use this?

**Comment by jacobbednarz** [comment]
as this isn't a Terraform issue, your best bet is to open a Cloudflare support ticket. you can also have a look at the API docs on api.cloudflare.com and see if the permissions listed under Total TLS are working here.
