### ISSUE TITLE
Cache Rules

### ISSUE THREAD

**Issue by gtirloni** [cloudflare/terraform-provider-cloudflare#2022]
### Current Terraform and Cloudflare provider version

Terraform 1.3.4
CF provider 3.27.0

### Description

Is it possible to configure Cache Rules through Terraform?

The documentation mentions Terraform explicitly but I can’t find a specific resource for that.

### Use cases

Configure Cache Rules

### Potential Terraform configuration

```hcl
...
```

### References

https://blog.cloudflare.com/introducing-cache-rules

**Comment by jacobbednarz** [comment]
you'll need to checkout the [developer docs](https://developers.cloudflare.com/cache/about/cache-rules/#create-cache-rules-via-api) and [provider docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset) to build the resource for your cache settings.

**Comment by renan** [comment]
@jacobbednarz What are the required API permissions to run this on Terraform? I don't see Rulesets under Zone, and Account Rulesets doesn't seem to give me the right permissions.
