### ISSUE TITLE
Feature request: URL normalization

### ISSUE THREAD

**Issue by vcajes** [cloudflare/terraform-provider-cloudflare#2026]
### Current Terraform and Cloudflare provider version

Terraform v1.3.4
on darwin_arm64

### Description

Cloudflare allows to configure URL normalization in zones and provides an API to configure it.

Documentation: https://developers.cloudflare.com/rules/normalization/manage/

API: https://api.cloudflare.com/#url-normalization-update-url-normalization-settings

### Use cases

Easily setup zones with terraform to enable URL normalization.

### Potential Terraform configuration

```hcl
resource "cloudflare_url_normalization" "this" {
  type = "cloudflare"
  scope = "both"
}
```

**Comment by jacobbednarz** [comment]
this work is already underway via #1878
