### ISSUE TITLE
Cannot create origin certificate with own CSR

### ISSUE THREAD

**Issue by bogdan-milescu** [cloudflare/terraform-provider-cloudflare#2029]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform {
  required_version = "~> 1.3.1"
  required_providers {
    aws = {
      version = "~> 4.34.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.28.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "4.0.4"
    }
  }
}

### Affected resource(s)

cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
resource "tls_private_key" "example" {
  algorithm = "RSA"
}

resource "tls_cert_request" "example" {
  # key_algorithm   = tls_private_key.example.algorithm
  private_key_pem = tls_private_key.example.private_key_pem

  subject {
    common_name  = ""
    organization = "Terraform Test"
  }
}

resource "cloudflare_origin_ca_certificate" "example" {
  csr                = tls_cert_request.example.cert_request_pem
  hostnames          = [ "example.com" ]
  request_type       = "origin-rsa"
  requested_validity = 7
}
```

### Link to debug output

https://gist.github.com/bogdan-milescu/5d4eb480024e9ce5edd92ce209e8bd69

### Expected output

Resource creation to succeed.

### Actual output

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_origin_ca_certificate.example will be created
  + resource "cloudflare_origin_ca_certificate" "example" {
      + certificate        = (known after apply)
      + csr                = <<-EOT
          ......................................................
        EOT
      + expires_on         = (known after apply)
      + hostnames          = [
          + "example.com",
        ]
      + id                 = (known after apply)
      + request_type       = "origin-rsa"
      + requested_validity = 7
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_origin_ca_certificate.example: Creating...
╷
│ Error: error creating origin certificate: Authentication error (10000)
│ 
│   with cloudflare_origin_ca_certificate.example,
│   on cloudflare.tf line 34, in resource "cloudflare_origin_ca_certificate" "example":
│   34: resource "cloudflare_origin_ca_certificate" "example" {

### Steps to reproduce

1. Use the example [here](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/origin_ca_certificate#example-usage) but remove the ```key_algorithm   = tls_private_key.example.algorithm``` from the resource definition.
2. terraform apply
3. Observer the error

### Additional factoids

I'm using an Cloudflare API token  with the following permissions:
![image](https://user-images.githubusercontent.com/86466683/202182446-32aa9931-4117-4323-95e8-fe15edc5ee54.png)

**Comment by jacobbednarz** [comment]
API tokens are not used for `cloudflare_origin_ca_certificate`, see the docs at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/origin_ca_certificate for the correct authentication mechanism to use.

**Comment by bogdan-milescu** [comment]
Worked ad intended! Thanks!
