### ISSUE TITLE
cloudflare_access_application doesn't allow private_dns as application type

### ISSUE THREAD

**Issue by fliphess** [cloudflare/terraform-provider-cloudflare#2030]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.28.0
+ provider registry.terraform.io/hashicorp/aws v4.17.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Affected resource(s)

- cloudflare_access_application 

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "this" {
  name   = var.name
  domain = var.application_domain
  type   = "private_dns"

  account_id           = var.account_id
  app_launcher_visible = var.show_in_app_launcher
}
```

### Link to debug output

- Related output for other type: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1358

### Panic output

-

### Expected output

As cf-terraforming already generates terraform code supporting the `private_dns` type for `cloudflare_access_application`, I'd expect the provider to support this as well, but this is not (yet) the case.

### Actual output
```
│ Error: expected type to be one of [app_launcher bookmark biso dash_sso saas self_hosted ssh vnc warp], got private_dns
│
│   with module.internal_apps.cloudflare_access_application.this,
│   on modules/internal_app/main.tf line 4, in resource "cloudflare_access_application" "this":
│    4:   type   = "private_dns"
```

### Steps to reproduce

1. Comment out `required_version` in terraform block (known bug in cf-terraforming)
2. Generate applications using: ```cf-terraforming  generate --resource-type cloudflare_access_application```
3. import access applications 
4. run terraform apply 

### Additional factoids

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application

**Comment by fliphess** [comment]
[output.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/10024518/output.log)

**Comment by fliphess** [comment]
Adding TF_LOG=DEBUG output really doesn't add any value here: The error is obvious without it.

**Comment by jacobbednarz** [comment]
we don't currently have plans to enable managing private applications via the API as their APIs are still considered unstable. once the team gives the green light, they will add public support for them.

related: https://github.com/cloudflare/terraform-provider-cloudflare/pull/1975#issuecomment-1297136226
