### ISSUE TITLE
How to deploy a Wasm worker

### ISSUE THREAD

**Issue by omarabid** [cloudflare/terraform-provider-cloudflare#2039]
### Current Terraform and Cloudflare provider version

Terraform: 1.3.5
Cloudflare: 3.28

### Description

I'm currently deploying rust-wasm workers. The workers are built with `worker-build` and published with `wrangler publish`. It seems these are multi-file workers.

I'm a bit at loss of how I can configure the Terraform resource for such a worker since I can only include one file (the entry file); whereas I have two files (the JS entry file and a WASM file)

### Use cases

rust-wasm workers

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "my_script" {
  name    = "script_1"
  content = file("../path/build/worker/shim.mjs")
}
```

### References

[Upload worker module](https://api.cloudflare.com/#worker-script-upload-worker-module)

**Comment by jacobbednarz** [comment]
this isn't supported by the Terraform provider atm. see cloudflare/cloudflare-go#1128 where we are discussing the interface and usage.

**Comment by omarabid** [comment]
> Does the [`webassembly_binding` property](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/worker_script.html#webassembly_binding) not work for this case?
> 
> Edit: It doesn't; I tried using it. I'm not sure what the use case for the `webassembly_binding` property is.

It is not clear what it does, since you should be using the service_binding to bind other services (whether wasm or javascript)

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
