### ISSUE TITLE
Error: error creating spectrum application for zone: json: unknown field "traffic_type" (10012)

### ISSUE THREAD

**Issue by KrakenMare** [cloudflare/terraform-provider-cloudflare#2040]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: 1.3.5
Cloudflare Provider: 3.28.0

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
locals {
  cloudflare_ssh_origin = join("", ["tcp://", hcloud_server.test_server.ipv4_address, ":22"])
}

//configure ssh access to the server via spectrum tunnel
resource "cloudflare_spectrum_application" "connect_ssh" {
  zone_id      = var.cloudflare_zone_id
  protocol     = "tcp/22"
  traffic_type = "direct"

  dns {
    type = "CNAME"
    name = "ssh.example.com"
  }

  origin_direct = [
    local.cloudflare_ssh_origin
  ]
}
```

### Link to debug output

https://gist.github.com/KrakenMare/70057b25b133c28478c836f7f8f6adb4

### Expected output

For a spectrum resource to be created.

### Actual output

Received Error: `Error: error creating spectrum application for zone: json: unknown field "traffic_type" (10012)`

### Steps to reproduce

1. terraform plan
2. terraform apply

### Additional factoids

The plan will map out fine, but the actual apply is where the error occurs.

### References

[Related Closed Issue](https://github.com/cloudflare/terraform-provider-cloudflare/issues/865)

**Comment by jacobbednarz** [comment]
this is a service issue as the error is coming from the API endpoint itself. i've pinged some folks internally however, i'd recommend you raise a support ticket as well if this is blocking you.

closing this off as there isn't anything we can do in the provider to address this.

**Comment by justin0mcateer** [comment]
There appear to be a couple of problems here:
1) on certain account levels/types you can't use 'tcp/22' for the protocol (as the documentation suggests), you have to use 'ssh' 
      I found this by doing an HTTP GET on the API against a Dashboard created resource
2) the API is polymorphic in what parameters it accepts, based on the value of the protocol field
      a) this behavior is completely undocumented in the API documentation
      b) the Terraform provider does not implement this polymorphism
               for example, it always sends the 'traffic_type' field, the API will _not_ accept this field with protocol set to 'ssh'
