### ISSUE TITLE
Add an option to rate limit terraform own API call

### ISSUE THREAD

**Issue by rgarrigue** [cloudflare/terraform-provider-cloudflare#2061]
### Current Terraform and Cloudflare provider version

Terraform v1.2.8
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.23.0
+ provider registry.terraform.io/hashicorp/aws v4.30.0

### Description

I'm hitting

> │ Error: exceeded available rate limit retries

I'ld like to be able to enforce a rate limit in my TF code to avoid this

### Use cases

I've one "records" module to create list of records, and one call to this module by zone. Some are a bit big, some small, total ~ 1400 records.

### Potential Terraform configuration

```hcl
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.23.0"
      rate_limiting = 100 # by second or whatever, just an example
    }
```

Or `CLOUDFLARE_API_RATE_LIMIT=100` env var

### References

There's this issue on TF core, the core team highlight there that it's better to implement this in each relevant provider https://github.com/hashicorp/terraform/issues/31094

**Comment by jacobbednarz** [comment]
this is already possible using the `rps` provider attribute - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#rps. 

you can also customise the min/max back offs, and number of retries to perform before hard failing.

**Comment by absinthetized** [comment]
👋 sorry to zombie post here but I get the same error and the provided docs link, while landing in the correct page, provides info that have no reference to such an option: is there another way to manage this?

**Comment by svenedge** [comment]
I'm running into this with the fact that in provider v5, [IP list](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/list) entries require a [cloudflare_list_item](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/list_item) resource per IP.

Looks like there's a newer issue: https://github.com/cloudflare/terraform-provider-cloudflare/issues/5505
