### ISSUE TITLE
`api_user_service_key` and `api_token` variables are mutually exclusive.

### ISSUE THREAD

**Issue by dmi-clopez** [cloudflare/terraform-provider-cloudflare#2079]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```sh
Terraform v1.3.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.29.0
```

### Affected resource(s)

Provider schema

### Terraform configuration files

```hcl
terraform {
  required_version = ">= 1.1"

  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.29.0"
    }
  }
}
```

### Link to debug output

https://gist.github.com/dmi-clopez/f077b514eaf241caf42eb882b3ea1eef

### Expected output

In previous versions, both types of keys were accepted and required to create SSL certificates alongside other types of resources.

### Actual output

We can't use both since `api_user_service_key` and `api_token` are mutually exclusive. It is not clear what's the upgrade path for this use case.

### Steps to reproduce

On any Terraform with Cloudflare provider configured run:

```bash
export CLOUDFLARE_API_TOKEN=ABC-xxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxx
export CLOUDFLARE_API_USER_SERVICE_KEY=v1.0-aaaaaaaaaaaaaaaaaaaaaaaaaa
terraform plan
```

### Additional factoids

If this is now the expected behavior, which keys do we need to configure?

### References

It was configured that all types of keys were mutually exclusive on [this](https://github.com/cloudflare/terraform-provider-cloudflare/pull/1907/files#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22R104) commit.

**Comment by jacobbednarz** [comment]
see #1919 where this is covered and discussed.
