### ISSUE TITLE
Resource of type `cloudflare_notification_policy` with alert_type "http_alert_origin_error" can't be imported

### ISSUE THREAD

**Issue by nimda7** [cloudflare/terraform-provider-cloudflare#2082]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.29.0
+ provider registry.terraform.io/hashicorp/aws v4.46.0

### Affected resource(s)

**cloudflare_notification_policy** filter schema

### Terraform configuration files

```hcl
resource "cloudflare_notification_policy" "origin_error_rate_alert" {
  account_id  = var.cf_account_id
  name        = "Origin Error Rate Alert"
  description = ""
  enabled     = true
  alert_type  = "http_alert_origin_error"

  email_integration { id = "user@example.com" }

 filters {
   slo = ["99.7"]
   zones = [
     "111111",
     "222222"
   ]
 }
}
```

### Link to debug output

https://gist.github.com/nimda7/f4942fbb9ff47a7eb4d48aefca4f2748

### Expected output

A resource should be imported.

### Actual output

 Error: failed to set filters: Invalid address to set: []string{"filters", "0", "alert_trigger_preferences"}
 
Import failed because of unknown optional field in ColudFlare API

### Steps to reproduce

terraform import cloudflare_notification_policy.passive_origin_monitoring  AAAAA/BBBBBBB

### Additional factoids

Actual Cloudflare schema for the alert `http_alert_origin_error` is that
```
    "Origin Monitoring": [
      {
        "display_name": "Passive Origin Monitoring",
        "type": "real_origin_monitoring",
        "description": "Cloudflare is unable to reach your origin",
        "filter_options": []
      },
      {
        "display_name": "Origin Error Rate Alert",
        "type": "http_alert_origin_error",
        "description": "High levels of 5xx HTTP errors at your origin",
        "filter_options": [
          {
            "Key": "zones",
            "ComparisonOperator": "==",
            "Optional": false
          },
          {
            "Key": "slo",
            "ComparisonOperator": "==",
            "Optional": false
          },
          {
            "Key": "alert_trigger_preferences",
            "ComparisonOperator": "==",
            "Optional": true
          }
        ]
      }
    ],
```
It has an optional field `alert_trigger_preferences` which is caused issue on import.

**Comment by jacobbednarz** [comment]
Thank you for reporting this issue! For maintainers to dig into issues it is required that all issues include the entirety of `TF_LOG=DEBUG` output to be provided. The only parts that should be redacted are your user credentials in the `X-Auth-Key`, `X-Auth-Email` and `Authorization` HTTP headers. Details such as zone or account identifiers are not considered sensitive but can be redacted if you are very cautious. This log file provides additional context from Terraform, the provider and the Cloudflare API that helps in debugging issues. Without it, maintainers are very limited in what they can do and may hamper diagnosis efforts.\n\nThis issue has been marked with `triage/needs-information` and is unlikely to receive maintainer attention until the log file is provided making this a complete bug report.

**Comment by jacobbednarz** [comment]
`http_alert_origin_error` is [not an allowed `filter` for the schema](https://github.com/cloudflare/terraform-provider-cloudflare/blob/7b9490a8a8dd0cb189865204ad69f88178de0a94/internal/sdkv2provider/schema_cloudflare_notification_policy.go#L178) so it won't be able to import it.
