### ISSUE TITLE
cloudflare_teams_rule without rule_settings create a diff on every apply

### ISSUE THREAD

**Issue by wind0r** [cloudflare/terraform-provider-cloudflare#2085]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version
```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.29.0
```
### Affected resource(s)

```
cloudflare_teams_rule
```
### Terraform configuration files

```hcl
resource "cloudflare_teams_rule" "allow_admin_all" {
  account_id  = var.account_id
  name        = "AllowAdminAll"
  description = "Allow VIN Team OpsNet Access"
  precedence  = 1000
  enabled     = true
  action      = "allow"
  filters     = ["l4"]
  identity    = "any(identity.groups.name[*] in {\"Admin\"})"
}
```

### Link to debug output

https://gist.github.com/wind0r/8eb1290b04f07e026dfd85bcd4b8ee10

### Panic output

No Panic

### Expected output

No Diff when the same config is applied again

### Actual output

  ```
  # cloudflare_teams_rule.allow_vin_opsnet will be updated in-place
  ~ resource "cloudflare_teams_rule" "allow_admin_all" {
        id          = "$ID"
        name        = "AllowAdminAll"
        # (8 unchanged attributes hidden)

      - rule_settings {
          - add_headers                        = {} -> null
          - block_page_enabled                 = false -> null
          - insecure_disable_dnssec_validation = false -> null
          - override_ips                       = [] -> null
        }
    }
   ```

### Steps to reproduce

1. Create Example Teams rule
2. Plan and Apply
3. Plan again.

### Additional factoids

IMO: Applying the same Input again should not result in a diff.

Looks like CF API return a rule_settings object which doesn't match the state of not having a rule_settings object.
Since rule_settings is optional I would like to not add it to all team rules, just for having a clean diff.

**Comment by wind0r** [comment]
added some log lines

**Comment by jacobbednarz** [comment]
the debug log is missing the API calls for the Cloudflare API. can you please paste the output untruncated and unmodified as requested to dig into this one?

**Comment by jacobbednarz** [comment]
looks like you've got an API token in the debug output. you should revoke/rotate that. there is also https://jacobbednarz.com/tf-log-redactor/ which will automatically redact these types of fields for you in the future.

**Comment by wind0r** [comment]
I revoked the token after creating the dump. 
I hope this helps to reproduce and maybe solve the issue.

**Comment by wind0r** [comment]
Can I somehow further support with this issue or can you give me a tip on where to look so I can solve this problem myself? Unfortunately, this makes our Terraform diff very unreadable and cluttered, making it easy to overlook an important change.

**Comment by lilHermit** [comment]
I also had this issue today with 4.5.0 and  `cloudflare_teams_rule` resource, I had to add the following

``` 
  rule_settings {
  }
```
