### ISSUE TITLE
cloudflare_origin_ca_certificate resource creation fails due to Error: error creating origin certificate: Authentication error (10000)

### ISSUE THREAD

**Issue by Akshaya-T** [cloudflare/terraform-provider-cloudflare#2092]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.30.0
+ provider registry.terraform.io/hashicorp/google v4.44.0
+ provider registry.terraform.io/hashicorp/google-beta v4.44.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

### Affected resource(s)

cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
provider "cloudflare" {
}

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.30.0"
    }
    google = {
      version = "4.44.0"
    }
    google-beta = {
      version = "4.44.0"
    }
  }
}


resource "tls_private_key" "api-cert-private-key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "api-cert-request" {
  private_key_pem = tls_private_key.api-cert-private-key.private_key_pem
}

resource "cloudflare_origin_ca_certificate" "api-cert" {
  csr                  = tls_cert_request.api-cert-request.cert_request_pem
  hostnames            = ["example.com"]
  request_type         = "origin-rsa"
  requested_validity   = 365
  min_days_for_renewal = 10
}
```

### Link to debug output

https://gist.github.com/Akshaya-T/19404c6fddcca1d9f0c439e0114dee3d

### Panic output

│ Error: error creating origin certificate: Authentication error (10000)
│
│   with cloudflare_origin_ca_certificate.api-cert,
│   on certificate.tf line 9, in resource "cloudflare_origin_ca_certificate" "api-cert":
│    9: resource "cloudflare_origin_ca_certificate" "api-cert" {
│
╵
Operation failed: failed running terraform apply (exit 1)

### Expected output

Cloud flare ssl certificate should be provisioned.

### Actual output

│ Error: error creating origin certificate: Authentication error (10000)
│
│   with cloudflare_origin_ca_certificate.api-cert,
│   on certificate.tf line 9, in resource "cloudflare_origin_ca_certificate" "api-cert":
│    9: resource "cloudflare_origin_ca_certificate" "api-cert" {
│
╵
Operation failed: failed running terraform apply (exit 1)

### Steps to reproduce

1. Create API Token from cloudflare with ssl certificate write permission
2. Use the token in the provider and run the code mentioned in the Terraform configuration files.

### Additional factoids

Using terraform cloud and have created the variable set **CLOUDFLARE_API_TOKEN** with the cloudflare API token with the ssl certificate write permission. But still facing error while provisioning the certificate.
Tried passing the token directly in the provider block as well but still not working.

eg:
`
provider "cloudflare" {
  api_token = "1244"
}`

**Comment by jacobbednarz** [comment]
you cannot use API tokens for the origin CA resource; see the documentation for details on this - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/origin_ca_certificate

**Comment by Firfi** [comment]
Stumbled upon it looking for which permissions are needed for this action. The latter message from @jacobbednarz is valid for older provider versions, but the newer ones accept all authentication schemas:

(from the link https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/origin_ca_certificate)
```
Since [v3.32.0](https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v3.32.0) all authentication schemes are supported for managing Origin CA certificates. Versions prior to v3.32.0 will still need to use [api_user_service_key](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/index#api_user_service_key).
```

Leaving for anyone who'll encounter this issue.

**Comment by Pasukaru** [comment]
I'm having he same issue, getting a 10000 when trying to create a certificate.

I tried with the latest terraform provider 4.22 as well as the suggested 3.32, both with the same error message:
```
Error: error creating origin certificate: Authentication error (10000)
(...) in resource "cloudflare_origin_ca_certificate" (...)
```

Permissions on the user api token are:
* Account: SSL and Certificates:Edit, Access: Mutual TLS Certificates:Edit
* Domain:  SSL and Certificates:Edit, Page Rules:Edit, DNS:Edit

Creating the resources `tls_private_key` and `tls_cert_request` worked without issues.

Does it require anything else?

**Comment by augustfengd** [comment]
I encountered the issue even when I had configured `Zone > SSL and Certificates > Edit`, but rolling my API Token seemed to have fixed it.
