### ISSUE TITLE
Add support for record attributes

### ISSUE THREAD

**Issue by alex-feel** [cloudflare/terraform-provider-cloudflare#2108]
### Current Terraform and Cloudflare provider version

Terraform v1.3.5
on windows_amd64
plus provider registry.terraform.io/cloudflare/cloudflare v3.30.0

### Description

It would be nice to have support for record attributes, which are described [here](https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/) and which are currently not supported:

```hcl
╷                                                                
│ Error: Unsupported argument                                    
│                                                                
│   on main.tf line 25, in resource "cloudflare_record" "foobar":
│   25:   comment = "Example comment."                           
│                                                                
│ An argument named "comment" is not expected here.              
╵                                                                
╷                                                                
│ Error: Unsupported argument                                    
│                                                                
│   on main.tf line 26, in resource "cloudflare_record" "foobar":
│   26:   tags    = ["foobar", "test"]                           
│                                                                
│ An argument named "tags" is not expected here.                 
╵                                                                
```

### Use cases

These attributes are particularly useful when:

- Multiple teams are managing DNS records within the same zone.
- Your zone contains a large number of DNS records.
- You want to filter your DNS records based on matching attributes (for example, when they are managed by the same team or used for the same application).

### Potential Terraform configuration

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = ">= 3.30.0"
    }
  }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

resource "cloudflare_zone" "example_edu" {
  account_id = "c62f02fa59b0569455a91a86a3aba321"
  zone       = "example.edu"
}

resource "cloudflare_record" "foobar" {
  zone_id = cloudflare_zone.example_edu.id
  name    = "terraform"
  value   = "192.168.0.11"
  type    = "A"
  ttl     = 3600
  comment = "Example comment."
  tags    = ["foobar", "test"]
}

```

### References

- https://developers.cloudflare.com/dns/manage-dns-records/reference/record-attributes/
- https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-create-dns-record

**Comment by jacobbednarz** [comment]
this is already under way how #2105
