### ISSUE TITLE
provider returned a resource missing an identifier during ImportResourceState (cloudflare_access_rule); bug in an api call 

### ISSUE THREAD

**Issue by surajthapa12** [cloudflare/terraform-provider-cloudflare#2114]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.6
cloudflare v3.31.0

### Affected resource(s)

terraform import

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
  required_version = ">= 0.13"
}

provider "cloudflare" {
  api_token = "######"
}

resource "cloudflare_access_rule" "terraform_managed_resource_example" {
  mode    = "block"
  notes   = ""
  zone_id = zone_id
  configuration {
    target = "ip"
    value  = "10.0.0.0" #this is an example
  }
}
```

### Link to debug output

https://gist.github.com/surajthapa12/d8b7e2cff4db87945f29d6a1e55e8e80

### Expected output

Import successful.

### Actual output

Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.

### Steps to reproduce

1. Method 1
2. Ensure that your cloudflare site has a rule for blocking specific ip address.
3. In a new folder, create  a file, main.tf .
4. Copy terraform config file. Update api key and ip address that you want to import
5. Run: terraform import cloudflare_access_rule.terraform_managed_resource_example zone/$zoneid/$rule_id

6. Method 2
7. The bug is that terraform code uses zone in path rather than using for an accounts. The endpoint with ".../zone/..." in path does not exist.
8. Error: curl -X GET "https://api.cloudflare.com/client/v4/**zones**/$ZONE_ID/firewall/access_rules/rules/$rule_id" -H "Content-Type:application/json" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"
9. But no error (see path): Error: curl -X GET "https://api.cloudflare.com/client/v4/**accounts**/$ZONE_ID/firewall/access_rules/rules/$rule_id" -H "Content-Type:application/json" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"

### Additional factoids

The api request has a bug. It requires you to provide account_id and not zone_id.

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_rule
I am using (and this does not work): 
# Zone level access rule import.
$ terraform import cloudflare_access_rule.default zone/<zone_id>/<rule_id>

However, using account level import works
# Account level access rule import.
$ terraform import cloudflare_access_rule.default account/<account_id>/<rule_id>

_No response_

**Comment by surajthapa12** [comment]
I have a link to debug.log. I am not sure where else to put my output. Please let me know.

**Comment by jacobbednarz** [comment]
the gist is missing the entirety of `TF_LOG=DEBUG` output. if you can provide it, this will be triaged.

**Comment by surajthapa12** [comment]
Thank you @jacobbednarz . I updated the entirety of log. Please let me know if it does not look right.

**Comment by jacobbednarz** [comment]
i think there is some confusion here as the routes exist at the zone *and* account level routes. you are providing `zone/<zone_id>/...` which is informing Terraform you'd like to import a *zone* level rule. if you want to import an account level access rule, you need to provide `account/<account_id/...` instead.

**Comment by surajthapa12** [comment]
@jacobbednarz , yes, what I am saying is that the zone level route is a bug and we cannot import via zone, i.e. using _zone/<zone_id>/<rule_id>_. The api endpoint for zone level route does not exist. So, the zone level route must be deleted from terraform documentation (https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_rule).

**Comment by jacobbednarz** [comment]
the zone level route exists and works. if you are not seeing a rule there, it isn't a zone level rule but an account level rule. either that or you have an incorrect ID.

**Comment by surajthapa12** [comment]
Thank you for your response. To your point "it isn't a zone level rule", yes. So, I am suggesting that we should remove it (_terraform import cloudflare_access_rule.default zone/<zone_id>/<rule_id>_) from terraform documentation. I already have had this conversation with a cloudflare online help. I am more than happy connect and explain more if needed.

**Comment by jacobbednarz** [comment]
we won't be removing it as this is working as expected; both zone and account imports are supported. see my earlier comment at https://github.com/cloudflare/terraform-provider-cloudflare/issues/2114#issuecomment-1369390323 for an explanation of how the importer decides on which to use.

**Comment by surajthapa12** [comment]
cool, no worries.

**Comment by surajthapa12** [comment]
Thank you for your patience. You are correct in that if its a zone rule, then it should work. Thank you again.

**Comment by cron410** [comment]
I had the same issue, but ONLY with the first `cloudflare_access_rule` in the console/code. I had to import the first rule with `terraform import cloudflare_access_rule.default account/<account_id>/<rule_id>` Rules 2-13 imported just fine with the commands generated by `cf-terraforming`

I changed all `cloudflare_access_rule` resources to use account_id instead of zone_id
```
resource "cloudflare_access_rule" "ip_access_rule_1" {
  mode    = "whitelist"
  notes   = "Corp IP"
  account_id = var.account_id
  configuration {
    target = "ip"
    value  = "1.2.3.4"
  }
}
```
