### ISSUE TITLE
Failing to provision cloudflare_logpush_job

### ISSUE THREAD

**Issue by ramunas-omnisend** [cloudflare/terraform-provider-cloudflare#2118]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

1.2.6

### Affected resource(s)

cloudflare_logpush_job

### Terraform configuration files

```hcl
data "cloudflare_zones" "all_active_zones" {
filter {
account_id = var.CLOUDFLARE_ACCOUNT_ID
status = "active"
}
}

resource "cloudflare_logpush_ownership_challenge" "ownership_challenge" {
account_id = var.CLOUDFLARE_ACCOUNT_ID
destination_conf = "gs://omnisend-cf-logs"
}

data "google_storage_bucket_object_content" "challenge_file" {
bucket = "omnisend-cf-logs"
name = cloudflare_logpush_ownership_challenge.ownership_challenge.ownership_challenge_filename
}

resource "cloudflare_logpush_job" "logs" {
for_each = { for zone_id in data.cloudflare_zones.all_active_zones.zones : zone_id.id => zone_id.name }
dataset = "http_requests"
destination_conf = "gs://omnisend-cf-logs/${each.value}/{DATE}"
enabled = true
frequency = "high"
ownership_challenge = data.google_storage_bucket_object_content.challenge_file.content
logpull_options = "fields=ClientRequestHost,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,ZoneName&timestamps=rfc3339"
zone_id = each.key
}
```

### Link to debug output

https://gist.github.com/ramunas-omnisend/71795297657ce759f1d582295b43b8f2

### Expected output

Resource applied for cloudflare_logpush_job and other resources

### Actual output

# cloudflare_logpush_job.logs["01843d5d516bee3c5992befd424b96c8"] will be created
+ resource "cloudflare_logpush_job" "logs" {
+ dataset = "http_requests"
+ destination_conf = "gs://omnisend-cf-logs/soundest.email/{DATE}"
+ enabled = true
+ frequency = "high"
+ id = (known after apply)
+ logpull_options = "fields=ClientRequestHost,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,ZoneName&timestamps=rfc3339"
+ ownership_challenge = "xxx"
+ zone_id = "01843d5d516bee3c5992befd424b96c8"
}
...
# cloudflare_logpush_job.logs["fd6f59ac14e731a3b765257ccb11c5c3"] will be created
+ resource "cloudflare_logpush_job" "logs" {
+ dataset = "http_requests"
+ destination_conf = "gs://omnisend-cf-logs/[soundest.lt/{DATE}](http://soundest.lt/%7BDATE%7D)"
+ enabled = true
+ frequency = "high"
+ id = (known after apply)
+ logpull_options = "fields=ClientRequestHost,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,ZoneName&timestamps=rfc3339"
+ ownership_challenge = "xxx"
+ zone_id = "fd6f59ac14e731a3b765257ccb11c5c3"
}

Plan: 85 to add, 0 to change, 0 to destroy.

and then 
╷
│ Error: error creating logpush job for zone (681876907dd84300f2927851134b64ea): incorrect ownership challenge (1002)
│
│ with cloudflare_logpush_job.logs["681876907dd84300f2927851134b64ea"],
│ on [logpush.tf](http://logpush.tf/) line 26, in resource "cloudflare_logpush_job" "logs":
│ 26: resource "cloudflare_logpush_job" "logs" {

### Steps to reproduce

1. Create GCP cloud storage bucket
2. Copy and paste tf script
3. Change bucket name
4. Apply tf

### Additional factoids

This case also was registered to Cloudflare enterprise support as an incident: 2654022. They asked to register an issue here.

**Comment by jacobbednarz** [comment]
the error here states it is related to an invalid ownership challenge. have you confirmed the ownership challenge is the correct value? what happens if you apply the challenge + job separately as mentioned in the docs?

**Comment by jacobbednarz** [comment]
removed the bug label as this isn't a provider bug but a configuration issue.

**Comment by Kaitou786** [comment]
@ramunas-omnisend were you able to resolve this?
I am hitting the exact same problem. I verified that the data from the challenge file is getting fetched correctly without any problem too.

**Comment by bergemalm** [comment]
I was able to successfully set up a job using the same path in the `destination_conf` for the `cloudflare_logpush_ownership_challange` and `cloudflare_logpush_job` resources.

```
.
.
destination_conf = "gs://${module.log_bucket.name}/logs/{DATE}"
.
```
