### ISSUE TITLE
Perma diff with cloudflare_ruleset

### ISSUE THREAD

**Issue by urbantz-technical-support** [cloudflare/terraform-provider-cloudflare#2127]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on linux_amd64

### Affected resource(s)

 * cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id = data.cloudflare_zone.urbantzdotcom.id
  kind    = "zone"
  name    = "Cloudflare Managed WAF"
  phase   = "http_request_firewall_managed"

  rules {
    action = "skip"
    action_parameters {
      rules = {
        # Cloudflare Managed Ruleset :  SQLi - String Concatenation
        "efb7b8c949ac4650a09736fc376e9aee" : "3b0c61407d0b4f7d87e516472116d2fe"
      }
    }
    expression  = "REDACTED"
    description = "REDACTED"
    enabled     = true
  }

  rules {
    action = "execute"
    action_parameters {
      # TODO unable to get the value from api yet
      id      = "efb7b8c949ac4650a09736fc376e9aee"
      version = "latest"
    }
    expression = "true"
    enabled    = true
  }
}
```

### Link to debug output

Not applicable

### Expected output

I expect an empty diff every time I run a plan

### Actual output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudflare_ruleset.zone_level_managed_waf will be updated in-place
  ~ resource "cloudflare_ruleset" "zone_level_managed_waf" {
        id      = "REDACTED"
        name    = "Cloudflare Managed WAF"
        # (3 unchanged attributes hidden)

      ~ rules {
            id          = "********************776a0"
            # (4 unchanged attributes hidden)

          - logging {
              - enabled = false -> null
              - status  = "enabled" -> null
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

### Steps to reproduce

1. terraform init
2. terraform apply
3. terraform plan

### Additional factoids

The cloudflare_ruleset was created from terraform from the get go.

We migrated from the old system using https://support.cloudflare.com/hc/en-us/articles/5995821690637-Migrating-from-WAF-managed-rules-to-WAF-Managed-Rulesets

**Comment by LanceSandino** [comment]
I'm affected by this, and updating to the latest has not fixed it.

**Comment by jacobbednarz** [comment]
please see the note at the top of the docs - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset

`enabled = true` is no longer valid. it should be `status = "enabled"`

**Comment by urbantz-technical-support** [comment]
Hey @jacobbednarz feel free to ignore this comment.

In our case we simply added the block:
```tf
logging {
      status = "enabled"
}
```

manually since it was indeed the wanted behaviour but I think there might still be an issue here.

We initially created these rules without any `logging` block since we wanted the default behaviour (not really obvious which is but it was fine). That is the behaviour we wanted, not needing to specify a logging block. I think the problem is that the field `status` defaults to the empty string instead of to `enabled`.

Cloudflare reports the logging to be enabled and the terraform module "sort of tries to remove that" by setting the empty string as the default. I believe this is the source of the perma-diff. Maybe the solution is to switch the default to `"enable"` or mark this field as computed if not specified.

But like I said this is no longer an issue for us.

Thanks in advance
