### ISSUE TITLE
Terraform for Device enrollement permissions setting

### ISSUE THREAD

**Issue by fxlequere** [cloudflare/terraform-provider-cloudflare#2144]
### Current Terraform and Cloudflare provider version

Terraform v1.3.7

### Description

We would like to terraform the Device enrollement rules settings 

### Use cases

To be sure that the WARP device enrollement rules is not deleted, and can be modified by a PR review, we would like to terraform this setting.

On Zero trust cloudflare portal / warp client / Device enrollement / Manage in the WebUI
It seems that this setting related to the WARP client is an Access policy. It's not correctly configured.
Please provide a clear documentation for that.

### Potential Terraform configuration

```hcl
resource "cloudflare_access_policy" "WARP_Login_App" {
  application_id = "" -> Seems require on the Terraform provide documentation, but this field is not available on the API V4 extract.
  account_id     = "xxxx"
  name           = "WARP-device-enrollment"
  precedence     = "1"
  decision       = "allow"

  include {
    azure {
      identity_provider_id = "<id>"
    }
    group {
      id = "<id of the Azure group>" -> This setting is not available. Only group list.
    }
  }

  require {
    email_domain = "domain.com"
    login_method {
      id = "<Login method id>" ->  This setting is not available. (Azure missing) Only cloudflare list.
    }
  }
}
```

### References
The device enrollment setting seems to be an Access policy.
`curl 'https://api.cloudflare.com/client/v4/accounts/<account_id>/access/warp`
'https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_policy'

**Comment by dsalaza4** [comment]
Any updates regarding this? We would also like to be able to declare our enrollment policies as code!

**Comment by david157** [comment]
warp uses an access policy same as the other apps
whenever warp routing is enabled an app is created for warp using the domain `<team_name>.cloudflareaccess.com/warp` so it's possible to read the app id and associate it with a `cloudflare_access_policy` resulting in the creation of the warp enrollment settings.
e.g.
```
data "cloudflare_access_application" "warp" {
  account_id = <account_id>
  domain     = "<team_name>.cloudflareaccess.com/warp"
} 

resource "cloudflare_access_policy" "warp" {
  account_id     = <account_id>
  application_id = data.cloudflare_access_application.warp.id
  name           = "warp enrollment policy"
  precedence     = "1"
  decision       = "allow"

  include {
    group = [<group_id>]
  }
}
```

`group_id`  is a reference to a `cloudflare_access_group`

**Comment by dsalaza4** [comment]
> warp uses an access policy same as the other apps whenever warp routing is enabled an app is created for warp using the domain `<team_name>.cloudflareaccess.com/warp` so it's possible to read the app id and associate it with a `cloudflare_access_policy` resulting in the creation of the warp enrollment settings. e.g.
> 
> ```
> data "cloudflare_access_application" "warp" {
>   account_id = <account_id>
>   domain     = "<team_name>.cloudflareaccess.com/warp"
> } 
> 
> resource "cloudflare_access_policy" "warp" {
>   account_id     = <account_id>
>   application_id = data.cloudflare_access_application.warp.id
>   name           = "warp enrollment policy"
>   precedence     = "1"
>   decision       = "allow"
> 
>   include {
>     group = [<group_id>]
>   }
> }
> ```
> 
> `group_id` is a reference to a `cloudflare_access_group`

I can confirm this works!

**Comment by jacobbednarz** [comment]
@jroyal are you able to confirm if this is the preferred approach or if there is another improvement for us to make here?

**Comment by jroyal** [comment]
Thats the approach we should use. There are a few things we could probably fix ergonomically (ie the name and domain are set by us on the app), but that is how it will work in general.

**Comment by jacobbednarz** [comment]
thanks @jroyal! I'll close this off and in the future if the team decides to improve those ergonomics, we can have a dedicated PR for it.

**Comment by Rutvij-Brahmbhatt** [comment]
> warp uses an access policy same as the other apps whenever warp routing is enabled an app is created for warp using the domain `<team_name>.cloudflareaccess.com/warp` so it's possible to read the app id and associate it with a `cloudflare_access_policy` resulting in the creation of the warp enrollment settings. e.g.
> 
> ```
> data "cloudflare_access_application" "warp" {
>   account_id = <account_id>
>   domain     = "<team_name>.cloudflareaccess.com/warp"
> } 
> 
> resource "cloudflare_access_policy" "warp" {
>   account_id     = <account_id>
>   application_id = data.cloudflare_access_application.warp.id
>   name           = "warp enrollment policy"
>   precedence     = "1"
>   decision       = "allow"
> 
>   include {
>     group = [<group_id>]
>   }
> }
> ```
> 
> `group_id` is a reference to a `cloudflare_access_group`

where do i get the "account_id" from?? i got everything else.

**Comment by rwojsznis** [comment]
Hey folks! With `application_id` being deprecated in `cloudflare_access_policy` how do you nowadays define warp app? `data "cloudflare_access_application" "warp"` works, but as it's a data source, not a resource - how do you define `policies` on it? 🤔 (as per [latest example](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application#example-usage))

Do you define your own warp app somehow with `cloudflare_access_application` resource? I feel like I _don't get_ how WARP app is supposed to be referenced nowadays 🙈

**Comment by stankolubomir** [comment]
@rwojsznis
Hey! I have imported the system-generated resources, such as warp (`type = "warp"`) and app launcher (`type = "app_launcher"`), into the `cloudflare_access_application` resource. Then, I was able to update it with policies using the new reusable policies approach.

**Comment by stankolubomir** [comment]
First, I used the `cloudflare_access_application` data source to list the IDs of the `warp` and `app_launcher` applications. Then, I imported them (using `terraform import` command) as `cloudflare_access_application` resources. However, you definitely can get the IDs of auto-generated applications via Cloudflare's API.
