### ISSUE TITLE
docs: explain how to associate a cloudflare_ip_list to a firewall rule

### ISSUE THREAD

**Issue by nitrocode** [cloudflare/terraform-provider-cloudflare#2161]
### Current Terraform and Cloudflare provider version

tf 1.3.7
cloudflare provider 3.32.0

### Description

I'm trying to understand how to associate the cloudflare_ip_list with a firewall rule and the documentation isn't clear to me. I'd like it to be clearer.

### Use cases

I'd like to set a list of IPs to block somewhere as a source of truth, pull that data down, create a [cloudflare_ip_list](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ip_list) resource and associate it with a firewall rule.

The docs of the ip list resource state

> Once created, IP Lists can be used in Firewall Rules across all zones within the same account.

The firewall rules I see are

- Managed rules ? - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/firewall_rule
- Custom rules - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset
    - https://developers.cloudflare.com/ruleset-engine/rules-language/values/

### Potential Terraform configuration

```hcl
locals {
  account_id = "<snip>"

  deny_ips = {
    "1.2.3.4" = "bad ip 1"
    "5.6.7.8" = "i dont like this one either"
  }
}

resource "cloudflare_ip_list" "default" {
  account_id  = local.account_id
  name        = "denylist"
  kind        = "ip"
  description = "IP deny list"

  dynamic "item" {
    for_each = local.deny_ips

    content {
      value   = each.key
      comment = each.value
    }
  }
}

resource "cloudflare_ruleset" "default" {
  account_id  = local.account_id
  name        = "denylist"
  description = "IP deny rule"
  kind        = "root"                         # perhaps ?
  phase       = "http_request_firewall_custom" # perhaps?

  rules {
    action      = "deny"
    expression  = "(ip.src in $denylist)"
    description = "Deny IPs"
  }
}
```

### References

- https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ip_list
- https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset
- https://developers.cloudflare.com/firewall/cf-firewall-rules/rules-lists/

**Comment by jacobbednarz** [comment]
this isn't something that we'll expand upon in the terraform documentation. 

the correct place for this is the documentation at https://developers.cloudflare.com/ruleset-engine/rules-language/values/ and https://developers.cloudflare.com/firewall/cf-dashboard/rules-lists/use-lists-in-expressions/

**Comment by jacobbednarz** [comment]
side note: I recommend swapping to `cloudflare_list` as `cloudflare_ip_list` is deprecated and will be removed in 4.x
