### ISSUE TITLE
DNS comments & tags not sticking?

### ISSUE THREAD

**Issue by lvets** [cloudflare/terraform-provider-cloudflare#2162]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.3.6 (Terragrunt 0.42.5)
Cloudflare provider: 3.32.0

### Affected resource(s)

`cloudflare_record` comment & tags attribute.

### Terraform configuration files

```hcl
Something like `comment = "This is a comment."` or `tags = (["test1", "test2", "test3"])` in `cloudflare_record`.
```

### Link to debug output

https://gist.github.com/lvets/6c22c148a7d0e5f97d6c0142f736f02f

### Panic output

N/A

### Expected output

N/A

### Actual output

Comments and tags are not applied.

### Steps to reproduce

1. Add comment and/or tags to `cloudflare_record`.
2. Plan: Terraform shows it wants to add the comments and/or tags to `cloudflare_record`.
3. Apply: Apply the plan from step 2. This is applied successfully. No errors are shown.
4. Plan again: Same output as step 2.
5. Rinse & repeat.

I ran with debugging output as well, but couldn't find any errors.

### References

See last comment on https://github.com/cloudflare/terraform-provider-cloudflare/pull/2105. Someone else might be having the same issue?

**Comment by jacobbednarz** [comment]
duplicate #2160

**Comment by lvets** [comment]
@jacobbednarz I didn't find #2160 initially because I was searching for dns. Sorry about that.
