### ISSUE TITLE
RBI settings

### ISSUE THREAD

**Issue by fxlequere** [cloudflare/terraform-provider-cloudflare#2163]
### Current Terraform and Cloudflare provider version

Terraform v1.3.7

### Description

I would like to configure Remote Browser Isolation settings with Terraform

### Use cases

I would like to configure Remote Browser Isolation settings with Terraform

### Potential Terraform configuration

```hcl
No API V4 related to this settings.
```

**Comment by jacobbednarz** [comment]
can you be more specific of what you expect here? RBI is already configurable https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule#biso_admin_controls

**Comment by fxlequere** [comment]
@jacobbednarz My comment is related to the **clientless Web Isolation** and **Non-identity on-ramp support** settings. (available on **Settings / Browser Isolation** on the WebUI )

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
