### ISSUE TITLE
Cache Rule API don't work with cache = false 

### ISSUE THREAD

**Issue by hotrungnhan** [cloudflare/terraform-provider-cloudflare#2164]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

+ provider registry.terraform.io/cloudflare/cloudflare v3.32.0

### Affected resource(s)

- cache_rule 

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "cache_rule" {
  zone_id = "some zone id"
  name    = "cache_rule"
  kind    = "zone"
  phase   = "http_request_cache_settings"
  rules {
    action_parameters {
      # issue with cloudfare api
      cache = false
    }
    action      = "set_cache_settings"
    expression  = "(http.host eq \"xxxx.com\")"
    description = "Some role cache"
    enabled     = true
  }
}
```

### Link to debug output

same as configuring file

### Expected output

Set cloud fare cache rule as by pass mode

### Actual output

action parameters are required for the set_cache_settings action

### Steps to reproduce

1. provision a cache rule as example.

**Comment by tmloberon** [comment]
We have the same problem.
action_parameters { cache = true } it works but not with false

**Comment by tmloberon** [comment]
We have the same problem.
action_parameters { cache = true } it works but not with false
[Terraform Log](https://gist.github.com/tmloberon/20373a112fe7dafa944c8386a42323cb#file-terraformlog-txt)

**Comment by Homoliber** [comment]
Same for bic and email_obfuscation:

action_parameters {
      email_obfuscation = false
      bic               = false
    }
