### ISSUE TITLE
Cloudflare_ruleset: edge_ttl block sets default field to 0 and is incompatible with mode="respect_origin"

### ISSUE THREAD

**Issue by mshi-sq** [cloudflare/terraform-provider-cloudflare#2165]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.0
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.32.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "respect_origin_headers" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_cache_settings"
  zone_id = var.zone_id
  rules {
    action      = "set_cache_settings"
    description = "respect-origin-headers"
    enabled     = false
    expression  = "(http.request.full_uri contains \"https://api.example.io/api/\")"
    action_parameters {
      browser_ttl {
        mode = "respect_origin"
      }
      edge_ttl {
        mode = "respect_origin"
      }
      cache = true
    }
  }
}
```

### Link to debug output

https://gist.github.com/mshi-sq/62ff156c515dcdd1e031a6af684a4288

### Expected output

successful terraform apply with

```
edge_ttl {
    mode = "respect_origin"
}
```

### Actual output

│ Error: error updating ruleset with ID "": default is useless in respect_origin mode, default cannot be 0
│
│ with module.cloudflare_v0[0].module.rules.cloudflare_ruleset.ruleset_request_cache_settings[0],
│ on modules/cloudflare/v0/rules/rules.tf line 294, in resource "cloudflare_ruleset" "ruleset_request_cache_settings":
│ 294: resource "cloudflare_ruleset" "ruleset_request_cache_settings" {

### Steps to reproduce

1. Create a page rule as above.
2. Make sure that edge_ttl and browser_ttl is set to respect_origin
3. Attempt to apply
4. Error: default is useless in respect_origin mode, default cannot be 0

### References

Follow up on https://github.com/cloudflare/terraform-provider-cloudflare/issues/2007 and outlined by https://github.com/cloudflare/terraform-provider-cloudflare/issues/2007#issuecomment-1384022836. The issue now seems to be that the optional default value gets set to 0 which is not compatible with edge_ttl `mode="respect_origin"`.

**Comment by mshi-sq** [comment]
https://gist.github.com/mshi-sq/2590ba1a31749e99df821cdd35dc5b2a

**Comment by mshi-sq** [comment]
updated debug log: https://gist.github.com/mshi-sq/62ff156c515dcdd1e031a6af684a4288

**Comment by jacobbednarz** [comment]
moved the debug into the issue body (as that is the only place the validator checks).

this is likely apart of a larger effort we're taking internally against zero values and the terraform internals providing incorrect API requests. there is no ETA i can share on this but it's in the backlog as a part of some larger initiatives.
