### ISSUE TITLE
CloudQuery source plugin

### ISSUE THREAD

**Issue by yevgenypats** [cloudflare/terraform-provider-cloudflare#2168]
### Current Terraform and Cloudflare provider version

-

### Description

Hi Team, hopefully this is right place to ask (wasn't sure if here or https://github.com/cloudflare/cloudflare-go), if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are asked for a [Cloudflare source plugin](https://www.cloudquery.io/docs/plugins/sources/cloudflare/overview), and we already shipped a first version.

As we have limited capacity to maintain all plugins we are usually looking for the official vendor to help maintain it (similar to terraform provider).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync Cloudflare APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

### Use cases

ELT

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
hi @yevgenypats 👋 i can't see a time in the near future where this is something we'd take on however, i'll pass this onto the product team who will reach out if anything changes.
