### ISSUE TITLE
Tags and comments do not update on cloudflare

### ISSUE THREAD

**Issue by simonweil** [cloudflare/terraform-provider-cloudflare#2169]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.32.0
+ provider registry.terraform.io/hashicorp/aws v4.46.0
+ provider registry.terraform.io/hashicorp/external v2.2.3
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.1

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
I can't share the config but this is the plan:


Terraform will perform the following actions:

  # module.records["key"].cloudflare_record.this will be updated in-place
  ~ resource "cloudflare_record" "this" {
      + comment         = "some comment"
        id              = "adsfsadf789sdf78df87df"
        name            = "subdomain"
        tags            = []
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Link to debug output

Can't share it, there are too many secrets in it

### Expected output

The comment and/or tags get updated

### Actual output

A related warning from the log:

```
2023-01-18T17:23:04.971+0200 [WARN]  Provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value for module.records["key"].cloudflare_record.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .comment: was cty.StringVal("some comment"), but now cty.StringVal("")
```

### Steps to reproduce

1. set the comment or tag in the cloudflare_record resource
2. apply

**Comment by ahrenstein** [comment]
I'm also experiencing this issue, although without the error. Everything completes as expected in Terraform but the record itself does not get tags or a comment on `v3.32.0`. This is when updating records or creating new records.

Example resource:
```hcl
resource "cloudflare_record" "module_record" {
  zone_id = var.module_zone
  name    = var.module_name
  type    = "CNAME"
  value   = "${cloudflare_argo_tunnel.module_tunnel.id}.cfargotunnel.com"
  ttl     = 1
  proxied = true
  comment = "tunnel record for ${var.module_name}"
  tags = [var.module_name, "zta-tunnels", "security-team"]
  allow_overwrite = true
}
```

**Comment by jacobbednarz** [comment]
this is already fixed by #2148

**Comment by ahrenstein** [comment]
Sound like we just need to wait for the patch release then. Thanks @jacobbednarz

**Comment by simonweil** [comment]
Thank you for the update @jacobbednarz 
When is it expected to be released?

**Comment by jacobbednarz** [comment]
the release process is documented at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/release-process.md

you can run your own version of the provider by following https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/using-non-released-versions.md

**Comment by simonweil** [comment]
Thank you @jacobbednarz
