### ISSUE TITLE
Resource cloudflare_certificate_pack wants to recreate certificate if base domain (zone name) is not added explicit in configuration

### ISSUE THREAD

**Issue by stivi21** [cloudflare/terraform-provider-cloudflare#2171]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.32.0
+ provider registry.terraform.io/hashicorp/aws v4.50.0
+ provider registry.terraform.io/hashicorp/local v2.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected resource(s)

- cloudflare_certificate_pack

### Terraform configuration files

```hcl
resource "cloudflare_certificate_pack" "env" {
  zone_id               = data.cloudflare_zone.this.id
  type                  = "advanced"
  hosts                 = ["*.sub.example.com", "sub.example.com"]
  validation_method     = "txt"
  validity_days         = 365
  certificate_authority = "digicert"
  wait_for_active_status = true

  lifecycle {
    create_before_destroy = true
  }
}
```

### Link to debug output

no debug

### Expected output

No changes. Your infrastructure matches the configuration.

### Actual output

Terraform will perform the following actions:
```
  # cloudflare_certificate_pack.env must be replaced
+/- resource "cloudflare_certificate_pack" "env" {
      ~ hosts                  = [ # forces replacement
          - "example.com",
            # (2 unchanged elements hidden)
        ]
      ~ id                     = "fae7c083-0f95-4533-a339-83eb73ff6c23" -> (known after apply)
        # (6 unchanged attributes hidden)

      + validation_errors {
          + message = (known after apply)
        }

      + validation_records {
          + cname_name   = (known after apply)
          + cname_target = (known after apply)
          + emails       = (known after apply)
          + http_body    = (known after apply)
          + http_url     = (known after apply)
          + txt_name     = (known after apply)
          + txt_value    = (known after apply)
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to reproduce

1. Create a resource cloudflare_certificate_pack with subdomains but without base domain (zone name)
2. terraform apply
3. Certificate will create with all subdomains + base domain
4. terraform apply - terraform wants to recreate certificate, because in current one is additional hostname (base domain)
5. terraform created new certificate also with base domain, because by default base domain will always include to certificate
6. back to point 4 (will be all time the same)

### Additional factoids

Any certificate in Cloudflare should always include base domain (zone name), but in resource there is possible configure without it (parameter **hosts**), i.e.
hosts = ["*.sub.example.com", "sub.example.com"]
resource with above configuration in fact create certificate with below configuration (will add base domain on the CF side):
["*.sub.example.com", "sub.example.com", "example.com"]
Resource can see all hostnames included in certificate, but configuration is without base domain, so terraform wants to recreate certificate.

I think that are 2 ways to fix it:
1. Module should reply error, if base domain is not added explicit in hosts parameter
2. Module should be added by default base domain, even if is not added in hosts parameter.

**Comment by jacobbednarz** [comment]
this is working as intended; we don't add additional validation here as there are use cases where it doesn't make sense for all customers.
