### ISSUE TITLE
Unable to use provider with CLOUDFLARE_API_TOKEN environment variable

### ISSUE THREAD

**Issue by iainbeeston** [cloudflare/terraform-provider-cloudflare#2179]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.32.0

### Affected resource(s)

* cloudflare_record

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 3.32"
    }
  }
}

provider "cloudflare" {}

resource "cloudflare_record" "root" {
  zone_id = "iainbeeston.com"
  name    = "iainbeeston.com"
  value   = "iainbeeston.github.io"
  type    = "CNAME"
}
```

### Link to debug output

https://gist.github.com/iainbeeston/1f2669c450351027f20b90356dac9327

### Expected output

It successfully shows me the plan, with a diff between my live infrastructure and my local code.

### Actual output

The cloudflare provider cannot find my API token:

```
╷
│ Error: Invalid combination of arguments
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on main.tf line 10, in provider "cloudflare":
│   10: provider "cloudflare" {}
│
│ "api_key": one of `api_key,api_token,api_user_service_key` must be specified
╵
╷
│ Error: Invalid combination of arguments
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on main.tf line 10, in provider "cloudflare":
│   10: provider "cloudflare" {}
│
│ "api_token": one of `api_key,api_token,api_user_service_key` must be specified
╵
╷
│ Error: Invalid combination of arguments
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on main.tf line 10, in provider "cloudflare":
│   10: provider "cloudflare" {}
│
│ "api_user_service_key": one of `api_key,api_token,api_user_service_key` must be specified
╵
```

### Steps to reproduce

1. Set the `CLOUDFLARE_API_TOKEN` env var to a valid API token
2. Add an empty cloudflare provider
3. run `terraform plan`

### Additional factoids

If I set up a variable, get it from user input and pass it to cloudflare like below, it does not show the error and produces a valid plan:

```
variable "token" {
  sensitive = true
}

provider "cloudflare" {
  api_token = var.token
}
```

Here's the output:

```
var.token
  Enter a value: <token>


Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_record.root will be created
  + resource "cloudflare_record" "root" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "iainbeeston.com"
      + proxiable       = (known after apply)
      + ttl             = (known after apply)
      + type            = "CNAME"
      + value           = "iainbeeston.github.io"
      + zone_id         = "iainbeeston.com"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### References

This looks similar: https://github.com/cloudflare/terraform-provider-cloudflare/issues/1939

**Comment by iainbeeston** [comment]
I've figured it out: my environment variables weren't being set correctly in my shell. Now I've set that correctly it's working.

**Comment by duceduc** [comment]
> I've figured it out: my environment variables weren't being set correctly in my shell. Now I've set that correctly it's working.

Hello. I am running into similar issue. How did you not set the environment variables incorrectly??

**Comment by iainbeeston** [comment]
@duceduc That will depend on what shell you are using, but try using `export CLOUDFLARE_API_TOKEN=<token>` (that will work for most shells I think?)

**Comment by duceduc** [comment]
Yea, that is what I tried and am using .bashrc

**Comment by alephnull** [comment]
export is key. Just setting it on the tf command line is insufficient.
