### ISSUE TITLE
[CONFIG] Cloudflare -> Datadog Logpush job fails with "Key is Missing" error

### ISSUE THREAD

**Issue by samvanryssegem-qz** [cloudflare/terraform-provider-cloudflare#2181]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.31.0

### Affected resource(s)

cloudflare_logpush_job

### Terraform configuration files

```hcl
resource "cloudflare_logpush_job" "datadog_http_requests" {
  enabled          = true
  zone_id          = var.zone_id
  name             = "datadog-http-requests"
  logpull_options  = "fields=BotScore,CacheCacheStatus,ClientCountry,ClientDeviceType,ClientIP,ClientRegionCode,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestURI,ClientRequestUserAgent,EdgeResponseStatus,EdgeStartTimestamp&timestamps=rfc3339,EdgeTimeToFirstByteMs,OriginResponseDurationMs,OriginResponseStatus,ZoneName"
  destination_conf = "datadog://http-intake.logs.us5.datadoghq.com/api/v2/logs?header_DD-API-KEY=${var.dd_api_key}&ddsource=cloudflare&service=cloudflare&ddtags=env:prod"
  dataset          = "http_requests"
  filter           = "{\"key\":\"ClientCountry\",\"operator\":\"!eq\",\"value\":\"us\"}"
}
```

### Link to debug output

https://gist.github.com/samvanryssegem-qz/961e442c6907096595fe8af5df41a877

### Expected output

The logpush job to be created

### Actual output

My terraform cloud run ended with the following error.

`Error: error parsing logpush job from resource: Key is missing
`

### Steps to reproduce

1.) Create terraform and run in tf cloud

### Additional factoids

I've double-checked and my api key variable is set. Maybe I'm setting up the destination incorrectly?

**Comment by lra** [comment]
This just happened to us with Terraform v1.4.6 and cloudflare/cloudflare v4.6.0.
