### ISSUE TITLE
Cloudflare provider v3.33 invalid provider configuration regression

### ISSUE THREAD

**Issue by Hasgaroth** [cloudflare/terraform-provider-cloudflare#2184]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.0
+ provider registry.terraform.io/hashicorp/aws v4.51.0

### Affected resource(s)

Cloudflare provider v3.33 failing after being released at approx 23:00 UTC 2023-01-24

### Terraform configuration files

```hcl
terraform {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.33.0"
    }
}
```

### Link to debug output

https://gist.github.com/Hasgaroth/1504bf79b752c5db90f3bc7f5908da2d

### Expected output

Successful plan / apply

### Actual output

Failure to complete the plan

```

│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: Invalid Attribute Combination
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on <empty> line 0:
│   (source code not available)
│
│ No attribute specified when one (and only one) of
│ [api_key,api_token,api_user_service_key] is required
╵

```

### Steps to reproduce

Using v3.32 of Cloudflare provider and all works ok
Update to v3.33 of Cloudflare provider plans consistently fail
Revert to v3.32 of Cloudflare provider and all works ok

**Comment by jacobbednarz** [comment]
please paste your minimal reproduction case. as is, this isn't enough for anyone to debug if this is an issue or intentional.

**Comment by Hasgaroth** [comment]
I'm afraid I don't have time to do that tonight, it's already 01:15am.
But with provider v3.32 m code works, and with v3.33 it fails.
v3.33 was released 1 hour before my code started to fail, and my code only started to fail after running a `terraform init -upgrade`

**Comment by jacobbednarz** [comment]
if you can't provide a reproduction case, there is very little I can do here. 

this is working on two test installations I have access to so the next step here is to identify what is different in your particular case.

**Comment by jacobbednarz** [comment]
i had another person provide a minimal reproduction test case for this. it only happens with empty provider blocks where the credentials are supplied via environment variables.

```hcl

provider {}

resource "foo" "bar" {
...
}
```

**Comment by JDKnobloch** [comment]
We also are experiencing this issue - we provide token via environment variable, same tf state was manipulated minutes prior to the release, now no-op changes are broken.

**Comment by jstewart612** [comment]
Why was this closed?  It's not fixed?

**Comment by Hasgaroth** [comment]
Thanks for the quick resolution on this one, really helpful!
Great stuff ❤️
