### ISSUE TITLE
Terraform 0.13 compatibility dropped with 3.33.1

### ISSUE THREAD

**Issue by kap-jonnyl** [cloudflare/terraform-provider-cloudflare#2188]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF 0.13.7
Provider 3.33.1

### Affected resource(s)

Not a resource issue

### Terraform configuration files

```hcl
terraform {
  required_version = ">= 0.13"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}
```
```


### Link to debug output

see output below

### Panic output

Error: Incompatible provider version

Provider "cloudflare/cloudflare" v3.33.1 is not compatible with Terraform
0.13.7.
You need to downgrade to v3.33.0 or earlier. Select it with the following
constraint:
	version = "3.33.0"

Terraform checked all of the plugin versions matching the given constraint:
	~> 3.0, ~> 3.0, ~> 3.0

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.
Alternatively, upgrade to the latest version of Terraform for compatibility
with newer provider releases.


### Expected output

No error

### Actual output

See error output from above

### Steps to reproduce

Run terraform init with the version config listed above



### Additional factoids

Resolved by dropping back to 3.32.0:
```
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "3.32.0"
    }
  }
  required_version = ">= 0.13"
}
```

### References

_No response_

**Comment by jacobbednarz** [comment]
0.13 support officially ended in this provider when [3.x was released](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-3-upgrade#terraform-013-and-older-versions-no-longer-supported). the fact it has worked with 0.13 up until this point was a happy accident and not something we made any guarantees on.

**Comment by the-middle** [comment]
Hi, on 0.15.3 it is not working as well. Couldn't find any information about the end of support for this version.

**Comment by jacobbednarz** [comment]
confusingly, 0.15 wasn't out when the 1.x compatibility promise was announced and we migrated with it.  

you need 1.x to use this provider as the link above mentions.

**Comment by the-middle** [comment]
Thanks for clarifying this for us. Should you change the text at the link above, it will become clearer.

> Please be aware, should you raise an issue with the Cloudflare provider using Terraform core < 0.14, you will be asked to replicate on a newer version before the issue is triaged by maintainers.

**Comment by et304383** [comment]
@jacobbednarz absolutely unacceptable that you broke all TF installations < 1.x.

**Comment by bruddy-lively** [comment]
You should also change the description for the Terraform Registry as well.  HIGHLY misleading.
<img width="372" alt="Screen Shot 2023-01-31 at 5 25 56 PM" src="https://user-images.githubusercontent.com/60671139/215922274-3dbdec59-9213-42f6-a884-deec61f9b059.png">

**Comment by advissor** [comment]
And if you ping to a version lower 

```
    cloudflare = {
        source = "cloudflare/cloudflare"
        version = "3.33.0"
    }	
```
    
Error : 
```
Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/cloudflare/cloudflare"
to obtain schema: Incompatible API version with plugin. Plugin version: 6,
Client versions: [5]
```

And terraform init passed with no issue. But plan says about 

```
Failed to instantiate provider "registry.terraform.io/cloudflare/cloudflare"
to obtain schema: Incompatible API version with plugin. Plugin version: 6,
Client versions: [5]
```
