### ISSUE TITLE
Provider v3.33.0+ produces invalid plan with Terraform 1.1.4 and below

### ISSUE THREAD

**Issue by rocko-n** [cloudflare/terraform-provider-cloudflare#2193]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform version 1.1.4
Cloudflare provider version 3.33.1

### Affected resource(s)

To my knowledge - Any

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
  required_version = ">= 0.15"
}

provider "cloudflare" {
  api_token = "<api-token>"
}

resource "cloudflare_record" "test" {
  zone_id = "<zone-id>"

  name     = "test"
  value    = "10.10.10.10"
  type     = "A"
  proxied  = true
  ttl      = 1
}
```

### Link to debug output

https://gist.github.com/rocko-n/eb8c49c7632c44d410aee9882ca26728#file-plan

### Expected output

```
Terraform will perform the following actions:

  # cloudflare_record.test will be created
  + resource "cloudflare_record" "test" {
      + allow_overwrite = false
      + created_on      = (known after apply)
      + hostname        = (known after apply)
      + id              = (known after apply)
      + metadata        = (known after apply)
      + modified_on     = (known after apply)
      + name            = "test"
      + proxiable       = (known after apply)
      + proxied         = true
      + ttl             = 1
      + type            = "A"
      + value           = "10.10.10.10"
      + zone_id         = "<zone-id>"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Actual output

```
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for cloudflare_record.test.allow_overwrite: planned value cty.False for
│ a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Steps to reproduce

1. Run `terraform init`
2. Run `terraform plan`

### Additional factoids

Terraform 1.1.5+ fixes the problem with invalid plan, but I think such incompatibility issue better suits for major version upgrade.

**Comment by jacobbednarz** [comment]
thanks for raising this one @rocko-n and pointing to the 1.1.4 specific issue that was addressed in terraform.

we have been on the terraform 1.x compatibility promise since the 3.x provider release however, we only recently added newer things which is why this bug triggered on terraform 1.1.5.

**Comment by rocko-n** [comment]
I think it would be great to add the information about minimal required terraform version into release notes (as this is the first place to search for answers).
