### ISSUE TITLE
resource "cloudflare_record" does not validate comment length

### ISSUE THREAD

**Issue by dsmello** [cloudflare/terraform-provider-cloudflare#2194]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

To report a bug at the resource "cloudflare_record". If the comment field was bigger the 50 chars will return a error without a clear motive about it.

Error : failed to create DNS record: DNS Validation Error (1004)
Must be something like: failed to create DNS record: DNS Validation Error (1004): {The validation what goes wrong} or at the plan phase block inputs bigger than 50 chars.

Terraform -v :
```bash
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.1
+ provider registry.terraform.io/hashicorp/google v4.50.0

Your version of Terraform needs to be updated! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "cc_dns_entry" {
    # allow_overwrite = false
    comment = "DNS created by terraform to VPN server ${var.env} with more than 50 chars"
    name = "cc"
    value = "${google_compute_address.public_ip_external_vpn.address}"
    type = "A"
    zone_id = data.cloudflare_zone.cc.id
    proxied = true
}
```

### Link to debug output

not_required

### Expected output

failed to create DNS record: DNS Validation Error (1004): {The validation what goes wrong} or at the plan phase block inputs bigger than 50 chars.

### Actual output

failed to create DNS record: DNS Validation Error (1004)

### Steps to reproduce

Just to create a cloudflare_record with a comment bigger than 50 chars

**Comment by dsmello** [comment]
I reduced my comment so that it won't be an issue. But can help someone else.

**Comment by jacobbednarz** [comment]
this isn't a bug as we generally keep the deeper validation like this in the API service, not the schema.

moving this to an enhancement if the service team wants to add it.

**Comment by jacobbednarz** [comment]
closing as we're going to leave this at the API service level for now.

**Comment by AndrewUnderwoodAtFanatics** [comment]
I would love it if you guys reconsidered this for inclusion, it's currently a pretty vague experience when you try to create a record with a comment and it doesn't fail until apply time, and then only with a non-specific error.
