### ISSUE TITLE
Provider produced invalid plan

### ISSUE THREAD

**Issue by alexthemonk** [cloudflare/terraform-provider-cloudflare#2195]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.1

### Affected resource(s)

module.dns-zones.cloudflare_zone

### Terraform configuration files

```hcl
resource "cloudflare_zone" "my-domain-com" {
    zone = "my.domain.com"
    type = "partial"
}
```

### Link to debug output

https://gist.github.com/alexthemonk/22c2315f16511196da38e31ca7e7854c

### Expected output

No error

### Actual output

```
╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for
│ module.dns-zones.cloudflare_zone.my-domain-com.paused: planned value cty.False for a non-computed attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Steps to reproduce

1. terraform init
2. terraform plan

**Comment by jacobbednarz** [comment]
this is an issue with terraform itself and has been addressed via https://github.com/hashicorp/terraform/pull/30330. backports have been provided to the 1.1.x branch and released as 1.1.5.
