### ISSUE TITLE
Can't adopt MX records into Terraform

### ISSUE THREAD

**Issue by arricc** [cloudflare/terraform-provider-cloudflare#2196]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.1

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "terraform_managed_resource_55a00009eb46e38e0bb13f144bed9427" {
  name     = "mydomain.com"
  priority = 20
  proxied  = false
  ttl      = 1
  type     = "MX"
  value    = "mx1.provider.co.uk"
  zone_id  = "<ZONEID>"
}

resource "cloudflare_record" "terraform_managed_resource_f38fa8db0dba5220f05e8d7130d90ce5" {
  name     = "mydomain.com"
  priority = 10
  proxied  = false
  ttl      = 1
  type     = "MX"
  value    = "mx0.provider.co.uk"
  zone_id  = "<ZONEID>"
  allow_overwrite = true
}
```

### Link to debug output

https://gist.github.com/arricc/49c20f48c347b5e7e92a99b660e32f68

### Expected output

MX records adopted by Terraform

### Actual output

If I add allow_overwrite = true, then I get the error 
"Error: attempted to override existing record however didn't find an exact match"

If I don't add allow_overwrite, I get 
"Error: expected DNS record to not already be present but already exists"

Included both in the example TF and log.

### Steps to reproduce

Created a zone.tf file with code generated by cf-terraforming
Add allow-overwrite = true to the records.
Plan run ok
Apply fails

### Additional factoids

No issues with A, CNAME, SRV or TXT records.

Have also tried using a data stanza with priority and target, but get a different error: failed to create DNS record: DNS Validation Error (1004)

**Comment by jacobbednarz** [comment]
why are you trying to overwrite and not import the resources?

**Comment by jacobbednarz** [comment]
you should take a look at https://blog.cloudflare.com/cloudflares-partnership-with-hashicorp-and-bootstrapping-terraform-with-cf-terraforming/ as it seems like you're attempting to create/overwrite resources when you actually want to be importing them.
