### ISSUE TITLE
Missing CASB terraform integration and API documentation

### ISSUE THREAD

**Issue by fxlequere** [cloudflare/terraform-provider-cloudflare#2207]
### Current Terraform and Cloudflare provider version

Terraform v1.3.7

### Description

I would like terrafom CASB Integrations.
We don't find any documentation to implement it, and API documentation is not available for CASB integrations.
In // it miss API documentation to extract the findings list.

### Use cases

I would like terrafom CASB Integrations.
We don't find any documentation to implement it, and API documentation is not available for CASB integrations.
In // it miss API documentation to extract the findings list.

### Potential Terraform configuration

```hcl
No idea. CASB part is not documented.
```

### References

No references, CASB part is not covered by API documentation.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
