### ISSUE TITLE
Zone Details data provider returning "Go struct field ZoneResponse.result of type cloudflare" 

### ISSUE THREAD

**Issue by seanmmitchell** [cloudflare/terraform-provider-cloudflare#2212]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.1

### Affected resource(s)

Appears to be an issue with data source "cloudflare_zone"

### Terraform configuration files

```hcl
//// Cloudflare Account Information
variable "cloudflare_account_id" {
  description = "Cloudflare Account ID"
  type = string
}

//// Cloudflare Global API Credentials
variable "cloudflare_user_email" {
  description = "Cloudflare User Email"
  type = string
}
variable "cloudflare_global_api_token" {
  description = "Cloudflare User Global API Key"
  type = string
  sensitive = true
}

//// Cloudflare Interface
provider "cloudflare" {
  email = var.cloudflare_user_email
  api_key = var.cloudflare_global_api_token
}

//// Target Zone
variable "cloudflare_zone_id" {
  description = "Cloudflare Zone (ID) to Target"
  type = string
  default = ""
}

data "cloudflare_zone" "target" {
    account_id = var.cloudflare_account_id
    zone_id = var.cloudflare_zone_id
}

locals {
    zoneHasPro = (data.cloudflare_zone.target.plan == "PRO" || data.cloudflare_zone.target.plan == "BIZ" || data.cloudflare_zone.target.plan == "ENT") ? true : false
}
```

### Link to debug output

https://gist.github.com/seanmmitchell/6279b30cfeb77140153bb605b81642a5

### Expected output

I expected to recieved the Zone ID and the Zone Plan so I can apply settings based on whether or not the plan is availilbe.

### Actual output

`╷
│ Error: error getting zone details: error unmarshalling the JSON response: json: cannot unmarshal array into Go struct field ZoneResponse.result of type cloudflare.Zone
│ 
│   with data.cloudflare_zone.target,
│   on variables.tf line 40, in data "cloudflare_zone" "target":
│   40: data "cloudflare_zone" "target" {
│ 
╵`

### Steps to reproduce

Run the code above and attempt to pull your Zone ID, has yet to function correctly for me.

**Comment by jacobbednarz** [comment]
this doesn't appear to be an issue with the provider. given the following case, it is working as expected

```
data "cloudflare_zone" "target" {
  account_id = var.cloudflare_account_id
  zone_id = var.cloudflare_zone_id
}

output "zone_status" {
  value = data.cloudflare_zone.target.plan
}
```

```
$ terraform apply -auto-approve
data.cloudflare_zone.target: Reading...
data.cloudflare_zone.target: Read complete after 1s [id=0da42c8d2132a9ddaf714f9e7c920711]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

zone_status = "Enterprise Website"
```

you'll notice `plan` will not contain the values you are looking for given the comparison you are running ("Enterprise Website" vs "ENT"). running your entire repro also doesn't show any issues on my end. c

> **Note**: you don't need `account_id` and `zone_id` for the data source. zone IDs are unique so if you have that, you can query directly using it.

**Comment by seanmmitchell** [comment]
The issue appears to have been due to a bad state. I exited the Terraform workspace, deleted it, re-created it, and then applied the state which succeeded. Closing this issue as the error appears to have been a red-herring.
