### ISSUE TITLE
cloudflare_worker_script requires setting of deprecated account_id on provider

### ISSUE THREAD

**Issue by cablespaghetti** [cloudflare/terraform-provider-cloudflare#2221]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.33.1
```

### Affected resource(s)

cloudflare_worker_script

### Terraform configuration files

```hcl
resource "cloudflare_worker_script" "optimizely_republicofcats" {
  name       = "republicofcats"
  content    = file("republicofcats_com_optimizely.js")
  account_id = "redacted"
}
```

### Link to debug output

N/A - I don't think this is needed in this case

### Expected output

If `account_id` is set on the worker script resource it should not require it to be set on the provider as well, which causes a deprecation warning.

### Actual output

```
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:republicofcats}: required missing account ID
│ 
│   with cloudflare_worker_script.optimizely_republicofcats,
│   on republicofcats_com.tf line 482, in resource "cloudflare_worker_script" "optimizely_republicofcats":
│  482: resource "cloudflare_worker_script" "optimizely_republicofcats" {
│ 
╵
```

### Steps to reproduce

1. Create a cloudflare_worker_script resource with account_id set
2. Do not set account_id on the provider (as deprecation warnings instruct you to)

**Comment by jacobbednarz** [comment]
`cloudflare_worker_script` has not used the provider attribute since v3.31.0 - see https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#3310-december-28th-2022. the provider attribute is being removed in 4.x so you should follow the deprecation warning and move the value to the resource as soon as you can.

**Comment by cablespaghetti** [comment]
I was able to overcome this by removing the script from my state and importing again. Without this I continued to get the error about missing account id shown above, even after upgrading to v4.0.0.

**Comment by JDKnobloch** [comment]
@jacobbednarz @cablespaghetti we are experiencing this issue as well on the latest version - 4.1.0
Account ID is being supplied as documented.
