### ISSUE TITLE
Pages "Direct Upload" Source Type

### ISSUE THREAD

**Issue by moranbw** [cloudflare/terraform-provider-cloudflare#2223]
### Current Terraform and Cloudflare provider version

- Terraform: `v1.3.7` 
- Cloudflare Provider: `v3.34.0`

### Description

It appears that the only `source.type` valid in `source_config` is GitHub.  At least that is all that is documented.  Is there any way to support Direct Upload from a build output directory with Terraform?

If directory is not possible, maybe it makes sense to point towards a zip generated with `hashicorp/archive`.

### Use cases

- Not everyone uses GitHub
- Some organizations may not want to link their GitHub
- Direct Upload is simple
- Yes, it is easy to do this via Wrangler.  But if an organization already is standardized on Terraform, would be nice to not have to install another tool.

### Potential Terraform configuration

```hcl
resource "cloudflare_pages_project" "source_config" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
  source {
    type = "direct"
    config {
      source_dir = "../client/dist"
    }
  }
}
```

### References

- https://github.com/cloudflare/terraform-provider-cloudflare/issues/2084

**Comment by lyc8503** [comment]
I think this feature is useful, hope it will be added in the future.
