### ISSUE TITLE
error creating cloudflare pages project, could not read response body: %!w(<nil>)

### ISSUE THREAD

**Issue by kdpuvvadi** [cloudflare/terraform-provider-cloudflare#2232]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.8
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.0.0-rc2

### Affected resource(s)

`cloudflare_pages_project`

### Terraform configuration files

```hcl
resource "cloudflare_pages_project" "hugo_deploy" {
  account_id        = var.cloudflare_account_id
  name              = "hugo-test-1"
  production_branch = "main"
  build_config {
    build_command   = "hugo"
    destination_dir = "public"
    root_dir        = "/"
  }
  source {
    type = "github"
    
    config {
      owner                         = "kdpuvvadi"
      repo_name                     = "hugo-test-cf"
      production_branch             = "main"
      deployments_enabled           = true
      production_deployment_enabled = true
      pr_comments_enabled           = false
      preview_branch_excludes       = ["main"]
    }
  }
  deployment_configs {
    production {
      environment_variables = {
        ENVIRONMENT  = "production"
        HUGO_VERSION = "v0.109.0"
      }
    }
    preview {
      environment_variables = {
        ENVIRONMENT  = "preview"
        HUGO_VERSION = "v0.110.0"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/kdpuvvadi/52a78ed5480e3d4e4f11c1df89eccdbf

### Expected output

Deploy a page project

### Actual output

Plan: 1 to add, 0 to change, 0 to destroy.
cloudflare_pages_project.hugo_deploy: Creating...
cloudflare_pages_project.hugo_deploy: Still creating... [10s elapsed]
cloudflare_pages_project.hugo_deploy: Still creating... [20s elapsed]
cloudflare_pages_project.hugo_deploy: Still creating... [30s elapsed]
╷
│ Error: error creating cloudflare pages project "hugo-test-1": could not read response body: %!w(<nil>)
│
│   with cloudflare_pages_project.hugo_deploy,
│   on pages.tf line 1, in resource "cloudflare_pages_project" "hugo_deploy":
│    1: resource "cloudflare_pages_project" "hugo_deploy" {
│
╵

### Steps to reproduce

1. terraform init
2. terraform plan
3. terraform apply

### Additional factoids

Initial version: `3.33.1`
failing on `4.0.0.rc2`

And Also checked the API Token with env var ` $ENV:TF_VAR_cloudflare_api_token` and in var file.

**Comment by jacobbednarz** [comment]
thanks for trying out the RC! we appreciate it. 

this looks to be an internal server error on the service. can you try again in a little while and if the issue persists, post back here?

**Comment by kdpuvvadi** [comment]
> this looks to be an internal server error on the service. can you try again in a little while and if the issue persists, post back here?

getting same error from yesterday. After internal error, waited few hours. tried same error. 

> thanks for trying out the RC! we appreciate it.

Getting same error on stable version. I can switch and get back with debug log.

**Comment by jacobbednarz** [comment]
this isn't related to the Terraform Provider version; the service is returning a 5xx error either due to a configuration issue or an unhandled server side issue. 

@WalshyDev do you mind having a poke around and letting me know if you need anything here?

**Comment by WalshyDev** [comment]
I'm not seeing any errors for your account in our service, if this is persisting could you join the community Discord (https://discord.gg/cloudflaredev) and tag me over there (Walshy#9709)?

Thanks!

**Comment by jacobbednarz** [comment]
closing this off as there isn't anything for the provider to do here.

**Comment by kdpuvvadi** [comment]
only facing this issue if we use `cloudflare_pages_project`. Other services are working fine.

**Comment by tcrst** [comment]
getting this on `cloudflare_notification_policy` tried providers versions from `3.33` to `4.0.0-rc`, anyone else ?

**Comment by kdpuvvadi** [comment]
working fine from `4.5.0`. Closing this.
