### ISSUE TITLE
upgraded provider version can not detect remote resource cloudflare_load_balancer_monitor and cloudflare_load_balancer_pool

### ISSUE THREAD

**Issue by lovegehlin** [cloudflare/terraform-provider-cloudflare#2237]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.8
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.16.0 (**initial setup and then upgrading to v3.34.0**)

### Affected resource(s)

- cloudflare_load_balancer_monitor
- cloudflare_load_balancer_pool

### Terraform configuration files

```hcl
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.16.0"
    }
  }
}

variable "cloudflare_api_token" {
  type = string
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

resource "cloudflare_load_balancer_monitor" "http_monitor" {
  type           = "http"
  expected_body  = "alive"
  expected_codes = "2xx"
  method         = "GET"
  timeout        = 7
  path           = "/"
  interval       = 60
  retries        = 5
  description    = "example http load balancer"
  header {
    header = "Host"
    values = ["example.com"]
  }
  allow_insecure   = false
  follow_redirects = true
}

resource "cloudflare_load_balancer_pool" "foo" {
  name = "example-pool"
  origins {
    name    = "example-1"
    address = "192.0.2.1"
    enabled = false
    header {
      header = "Host"
      values = ["example-1"]
    }
  }
  description     = "example load balancer pool"
  enabled         = false
  minimum_origins = 1
  origin_steering {
    policy = "random"
  }
}
```

### Link to debug output

https://gist.github.com/lovegehlin/63f0cc8c8c35e332b2c85724140f2c6a

### Expected output

Since the two resources already exist in the state (and remote), it should not create new resources

### Actual output

It could not detect remote resources and because of this want to create new resources.

### Steps to reproduce

1. Use above terraform config
2. Run `terraform apply -var="cloudflare_api_token=xxx"`
3. Upgrade cloudflare provider version in terraform config to `3.34.0`
4. Run `terraform init -upgrade`
5. Run `terraform plan`

**Comment by jacobbednarz** [comment]
for these resources you need to provide an `account_id` attribute at the resource level.

you'll notice it is missing from this URL.

```
2023-02-15T12:59:38.114+0100 [DEBUG] provider.terraform-provider-cloudflare_v3.34.0: GET /client/v4/accounts//load_balancers/pools/116fb9422c194c9afbd76720b83aea32 HTTP/1.1
```

prior to 4.x, it required an account ID at the provider level or resource level. after 4.x it will be a required field for these resources.

**Comment by lovegehlin** [comment]
I've tried adding account_id at the resource level but the issue still exists. [Here's the log output using account_id](https://gist.github.com/lovegehlin/aa8ed5050898db19a02dfdd2eb8ec3a9)

**Comment by jacobbednarz** [comment]
it looks like the bad state has already been persisted with it missing so you'll either need to import the resources or manually add the account ID to the resources with the state itself.

**Comment by lovegehlin** [comment]
Manually updating the state worked. 🚀 Many thanks @jacobbednarz.

**Comment by vicmunoz** [comment]
Found the same issue, just saving here another solution to not manually update the state.
Tested with v3.34.0.
Add `account_id` argument into definition of resource `cloud_load_balancer_monitor` (tested with `cloudflare_load_balancer_pool` too) whitout removing `account_id` argument from provider cloudflare defintion. 
Plan and apply. It will do an update in-place adding the `account_id` to the resources.
Now you can remove safely `account_id` argument from provider cloudflare defintion.
