### ISSUE TITLE
Recent releases are missing from Terraform registry

### ISSUE THREAD

**Issue by andrewkrain** [cloudflare/terraform-provider-cloudflare#2249]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

n/a

### Affected resource(s)

n/a

### Terraform configuration files

```hcl
n/a
```

### Link to debug output

n/a

### Expected output

expect to see v3.33.0 and newer

### Actual output

[../](https://releases.hashicorp.com/)
[terraform-provider-cloudflare_3.32.0](https://releases.hashicorp.com/terraform-provider-cloudflare/3.32.0/)
[terraform-provider-cloudflare_3.31.0](https://releases.hashicorp.com/terraform-provider-cloudflare/3.31.0/)
[terraform-provider-cloudflare_3.30.0](https://releases.hashicorp.com/terraform-provider-cloudflare/3.30.0/)
[terraform-provider-cloudflare_3.29.0](https://releases.hashicorp.com/terraform-provider-cloudflare/3.29.0/)

### Steps to reproduce

n/a

### Additional factoids

Recent releases are missing from Terraform registry https://releases.hashicorp.com/terraform-provider-cloudflare

**Comment by jacobbednarz** [comment]
https://releases.hashicorp.com/terraform-provider-cloudflare is only used for older versions of Terraform that support v5 of the protocol (which we no longer do) so newer versions won't be present. https://developer.hashicorp.com/terraform/internals/module-registry-protocol is the replacement and what all the Terraform ecosystem tooling uses.
