### ISSUE TITLE
Terraform ZeroTrust Egress Policies

### ISSUE THREAD

**Issue by fxlequere** [cloudflare/terraform-provider-cloudflare#2251]
### Current Terraform and Cloudflare provider version

Terraform v1.3.9
on darwin_arm64

### Description

Hey Team,

I would like to terraform the egress policies on Cloudflare ZeroTrust Board.

Could you provide this options ? 

Thanks,

FX

### Use cases

Hey Team,

I would like to terraform the egress policies on Cloudflare ZeroTrust Board.

Could you provide this options ? 

Thanks,

FX

### Potential Terraform configuration

```hcl
No API option, so I'm not able to offer a terraform coding example.
```

### References

Related to this option : https://developers.cloudflare.com/cloudflare-one/policies/filtering/egress-policies/

**Comment by MAN98** [comment]
I would definitely like to get this resource since we are using the Egress Policies on our organization.
