### ISSUE TITLE
Support for the Zero Trust Gateway: Network Firewall Policy

### ISSUE THREAD

**Issue by ripta** [cloudflare/terraform-provider-cloudflare#2259]
### Current Terraform and Cloudflare provider version

Terraform v1.3.9 with the cloudflare provider v3.35.0.
(I also double-checked the docs for the new cloudflare provider v4.0.0.)

### Description

I'd like the ability to manage network firewall policies through terraform. The feature is available on the Zero Trust dashboard under the Gateway > Firewall Policies > Network tab.

### Use cases

With multiple virtual networks and many cloudflare tunnel instances to manage, we'd appreciate being able to also capture our gateway policies in terraform.

### Potential Terraform configuration

The cloudflare API seems to treat gateway rule policies as a string expression:
https://api.cloudflare.com/#zero-trust-gateway-rules-create-zero-trust-gateway-rule

**The bare minimum** might look like:

```hcl
resource "cloudflare_zero_trust_gateway_rule" "allow_to_prod" {
  account_id = var.cloudflare_account_id
  name = "Allow access to prod tier"

  action = "allow"
  enabled = true
  precedence = 3000

  filters = ["l4"]
  traffic = "net.vmnet_id == \"3a87c214-FAKE-FAKE-FAKE-1b87d1d845b5\"" # not a real virtual network ID
  identity = "any(identity.groups.name[*] in {\"Foo Group\"})"

  rule_settings {
    check_session {
      enforce = true
      duration = "12h"
    }
  }
}
```

**This is a bigger ask:** it would be nice to be able to express these in a more terraform way, such that, for example, I could use references to other objects. I'm not sure if there's already a standard you all adopt for these expressions, but modeling it off AWS IAM policy documents, it might look something like:

```hcl
data "cloudflare_zero_trust_gateway_rule_expression" "in_prod" {
  property = "net.vmnet_id"
  value = cloudflare_tunnel_virtual_network.prod, # be able to refer to them as objects instead of hard-coding network IDs
}

data "cloudflare_zero_trust_gateway_rule_expression" "foo_users" {
  property = "identity.groups.id[*]"
  values = [
    cloudflare_access_group.foo.id,
  ]    
}

resource "cloudflare_zero_trust_gateway_rule" "allow_to_prod" {
  account_id = var.cloudflare_account_id
  name = "Allow access to prod tier"

  action = "allow"
  enabled = true
  precedence = 3000

  filters = ["l4"]
  traffic = data.cloudflare_zero_trust_gateway_rule_expression.in_prod.expression # and use the expression here as an object
  identity = data.cloudflare_zero_trust_gateway_rule_expression.foo_users.expression # same here

  rule_settings {
    check_session {
      enforce = true
      duration = "12h"
    }
  }
}
```

**Comment by nessadc** [comment]
Does this not already work with `cloudflare_teams_rule`?  I've created Network Policies like so:
```terraform
resource "cloudflare_teams_rule" "allow_contractors" {
  enabled     = true
  name        = "Allow Contractors"
  account_id  = "foobaraccount"
  description = "Allow Contractors access to Foobar"
  precedence  = 1
  action      = "allow"
  filters     = ["l4"]
  traffic     = "net.sni.host in {\"example.com\" \"bar.example2.com\"}"
  identity    = "any(identity.groups.name[*] in {\"Contractors\"})"

  rule_settings {
    block_page_enabled = false
  }
}
```

**Comment by nessadc** [comment]
Yup, the documentation is confusing. I guess Zero Trust was once named "Teams".

**Comment by ripta** [comment]
Thank you for pointing this out! Gonna close this now. 

Out of pure curiosity, I looked through the source code that `cloudflare_teams_rule` calls the `TeamsRule` Go API:

https://github.com/cloudflare/terraform-provider-cloudflare/blob/1ff904481eb07b84e58a548fd68bf3ba4af4a339/internal/sdkv2provider/resource_cloudflare_teams_rules.go#L33-L37

which ends up doing an HTTP call to `/accounts/{accountID}/gateway/rules/{ruleID}` at:

https://github.com/cloudflare/cloudflare-go/blob/d3fcc6c0396ae4c039ec30a3c699e62d1fec73a8/teams_rules.go#L184-L185

which matches the URL in the API docs for ["Zero Trust Gateway Rule Details"](https://api.cloudflare.com/#zero-trust-gateway-rules-zero-trust-gateway-rule-details).
