### ISSUE TITLE
Support schedules for zero-trust gateway DNS rules (cloudflare_teams_rule)

### ISSUE THREAD

**Issue by wayfrro** [cloudflare/terraform-provider-cloudflare#2261]
### Current Terraform and Cloudflare provider version

terraform v1.3.9
cloudflare provider 4.0.0

### Description

There's a `schedule` object in [Zero Trust Gateway Rule](https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule), which allows for scheduling activating DNS policies. It would be very well to have this supported in cloudflare provider, and this seems to be really not much work. Seems unsupported in current version of [cloudflare provider](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule). 

### Use cases

This would be very useful to create Gateway DNS policies, which are activated based on schedule, as supported by API.

### Potential Terraform configuration

```hcl
...
```

### References

Cloudflare API with schedule object: https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule
cloudflare_teams_rule docs: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule

**Comment by devinbfergy** [comment]
I am interested in working on this feature.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
