### ISSUE TITLE
Support Page Shield and notification

### ISSUE THREAD

**Issue by chadismoving** [cloudflare/terraform-provider-cloudflare#2264]
### Current Terraform and Cloudflare provider version

Terraform v1.3.8

### Description

Support Page Shield and notification to apply from Terraform

### Use cases

Easier to integrate Cloudflare security and notification service during zone initial setup

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by raidlman** [comment]
Latest Cloudflare provider version still doesn't allow to enable page_shield via Terraform. This doesn't seem to be too complicated since this is already possible via the API and it's already available in the go library. Are there any updates on this topic?

**Comment by stantonk** [comment]
Is there any update?
