### ISSUE TITLE
managed_challenge action not being applied to Cloudflare OWASP Core Ruleset

### ISSUE THREAD

**Issue by t0t4lly-l3g1t** [cloudflare/terraform-provider-cloudflare#2287]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
esource "cloudflare_ruleset" "deploy_cf_managed_rulesets" {
  account_id  = var.account_id
  name        = "Cloudflare_Managed_Rulesets"
  description = "Account level Cloudflare Managed Rulesets that are applied to all zones."
  kind        = "root" # "root" == Account level WAF 
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = data.cloudflare_rulesets.owasp_ruleset_id.rulesets[0].id # ID for the Cloudflare OWASP Core Ruleset
      overrides {
        action = "managed_challenge" 
        categories {
          category = "paranoia-level-3"
          status   = "disabled"
        }

        categories {
          category = "paranoia-level-4"
          status   = "disabled"
        }
      }
    }
    expression  = "(cf.zone.plan eq \"ENT\")" # WAF rules are applied to all zones as (http.host eq \"<ZONE NAME HERE>\") is not set.
    description = "Cloudflare OWASP Core Ruleset"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/t0t4lly-l3g1t/b1875e718f8c48cc2fd880f44dd5b1b6

### Expected output

Please note I am attempting to apply this at the Account WAF level. By setting `action = "managed_challenge"` I expected that when the resource was applied at the account level that the OWASP Action would be updated to Managed Challenge as opposed to the default of Block. 
There is no error or feedback to indicate that  `action = "managed_challenge"` is in the wrong place. 
I have tried  `action = "managed_challenge"` as part of the overrides as well as adding it within the categories section. For example: 

`categories {
          category = "paranoia-level-3"
          action = "managed_challenge
          status   = "disabled"
        }`
However as before there are no errors or indication of an issue other than the OWASP Action remaining as Block in the dashboard. 

### Actual output

I expected the Cloudflare OWASP Core Ruleset to be updated from Block to Managed Challenge. 

### Steps to reproduce

1. Terraform apply the above main.tf
2. Log into the cloudflare dashboard and navigate to https://dash.cloudflare.com/<account_id>/application-security/waf/managed/entrypoint/<Cloudflare_OWASP_Core_Ruleset_ID>.
3. Observe that the Cloudflare OWASP Core Ruleset is still set to Block. 

### Additional factoids

I have been doing my best to work through this on my own by making use of the Cloudflare API docs however at this point I am stuck, and quite unsure what I am doing wrong.

**Comment by jacobbednarz** [comment]
looking at the API request and responses, this looks to be sending the correct payloads so I don't think this is an issue in the provider. do you happen to have an account team you can raise this with to debug? if not, i can poke the service team but there are no guarantees on an ETA here.

**Comment by vences** [comment]
Hey @t0t4lly-l3g1t,
You need to check how the OWASP is working, we have some explanation [here](https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/#configure-the-owasp-paranoia-level-score-threshold-and-action). 
The OWASP is a score base system, it means that each rule has a score and the last rule is enforcing the behaviour. Here the exact wording from the doc:
> Set the action to perform when the calculated threat score is greater than the score threshold by creating a rule override for the last rule in the Cloudflare OWASP Core Ruleset (rule with ID 6179ae15870a4bb7b2d480d4843b323c), and including the action property.

For your example is means you should use the following configuration:

```tf
resource "cloudflare_ruleset" "deploy_cf_managed_rulesets" {
  account_id  = var.account_id
  name        = "Cloudflare_Managed_Rulesets"
  description = "Account level Cloudflare Managed Rulesets that are applied to all zones."
  kind        = "root" # "root" == Account level WAF 
  phase       = "http_request_firewall_managed"

  rules {
    action = "execute"
    action_parameters {
      id = data.cloudflare_rulesets.owasp_ruleset_id.rulesets[0].id # ID for the Cloudflare OWASP Core Ruleset
      overrides {
        categories {
          category = "paranoia-level-3"
          status   = "disabled"
        }

        categories {
          category = "paranoia-level-4"
          status   = "disabled"
        }

       rules {
          id = "6179ae15870a4bb7b2d480d4843b323c"
          action = "managed_challenge"
        }
      }
    }
    expression  = "(cf.zone.plan eq \"ENT\")" # WAF rules are applied to all zones as (http.host eq \"<ZONE NAME HERE>\") is not set.
    description = "Cloudflare OWASP Core Ruleset"
    enabled     = true
  }
}
```
The result on the dash should be:
<img width="583" alt="image" src="https://user-images.githubusercontent.com/3678374/226345750-98f23fbc-43a6-4210-9fbe-bc8420406aea.png">

Hope that help to understand better,

**Comment by t0t4lly-l3g1t** [comment]
Hi @vences, 

Thank you very much for the explanation.
