### ISSUE TITLE
Bad rule ID management with format function

### ISSUE THREAD

**Issue by mxmcmd** [cloudflare/terraform-provider-cloudflare#2293]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.3.2
Cloudflare provider 3.35.0

### Affected resource(s)

cloudflare_teams_list
cloudflare_teams_rule

### Terraform configuration files

```hcl
resource "cloudflare_teams_list" "tf_list_noisolate_domains" {
  account_id  = var.account_id
  name        = "tf_list_noisolate_domains"
  type        = "DOMAIN"
  description = "Not isolated domains by gateway"
  items = [
    "example.com",
    "cloudflare.com"
  ]
}

resource "cloudflare_teams_rule" "tf_http_noisolate" {
  account_id  = var.account_id
  name        = "tf_http_noisolate"
  description = "HTTP traffic not isolated in remote browser"
  enabled     = true
  precedence  = 3
  action      = "noisolate"
  filters     = ["http"]
  traffic     = format("any(http.request.domains[*] in $%s)", cloudflare_teams_list.tf_list_noisolate_domains.id)
  rule_settings {
    block_page_enabled = false
  }
}
```

### Link to debug output

 "any(http.request.domains[*] in $55c93e1e61c84813bdd8068e54113ac6)" change to "any(http.request.domains[*] in $55c93e1e-61c8-4813-bdd8-068e54113ac6)

### Expected output

cloudflare_teams_rule.tf_http_noisolate should not have a change in terraform plan

### Actual output

 "any(http.request.domains[*] in $55c93e1e61c84813bdd8068e54113ac6)" change to "any(http.request.domains[*] in $55c93e1e-61c8-4813-bdd8-068e54113ac6)

### Steps to reproduce

1. terraform plan
2. terraform apply
3. terraform plan

**Comment by jacobbednarz** [comment]
the root cause here is that the identifiers of `cloudflare_teams_list` have changed between you creating the resource (no hyphens) and you attempting to reference it here (with hyphens). this isn't a provider bug but something the remote service has changed so i'm afraid there is nothing we can do at the provider level for this sort of thing.

to rectify this, you can `terraform state rm ...` the resource and reimport to get the correct identifier to reference in your `cloudflare_teams_rule`.

**Comment by DamienDelporte** [comment]
Hi @jacobbednarz, i've done a:
```
terraform taint cloudflare_teams_list.tf_list_noisolate_domains
terraform taint cloudflare_teams_rule.tf_http_noisolate
```
To be sure to have a clean ressource, but still plan changes.

I think it's because of dashes in id with format fonction, but not sure :/

The dirty fix we now have is this:
```
resource "cloudflare_teams_rule" "tf_http_noisolate" {
  account_id  = var.account_id
  name        = "tf_http_noisolate"
  description = "HTTP traffic not isolated in remote browser"
  enabled     = true
  precedence  = 3
  action      = "noisolate"
  filters     = ["http"]
  traffic = format(
    "any(http.request.domains[*] in $%s)",
    replace(cloudflare_teams_list.tf_list_noisolate_domains.id, "-", "")
  )
  rule_settings {
    block_page_enabled = false
  }
}
```
With this no changes anymore, idempotent again !

**Comment by jacobbednarz** [comment]
I don't think taint will do the right thing here. I think you need to explicitly remove it and import to get the right ID. it would be great if you can provide the requested TF_LOG output as well to see what the API is giving you back.
