### ISSUE TITLE
`cloudflare_list` inline item

### ISSUE THREAD

**Issue by rwhelan** [cloudflare/terraform-provider-cloudflare#2294]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.0
cloudflare provider v4.1.0

### Affected resource(s)

`cloudflare_list`

### Terraform configuration files

```hcl
resource "cloudflare_list" "list_name" {
  account_id  = "01234567890123456789012345678901"
  name        = "test_list"
  kind        = "ip"

// item {
//   value {
//     ip = "192.0.2.1"
//   }
//   comment = "A list item comment"
// }
}
```

### Link to debug output

N/A

### Expected output

The list get updated to have zero items

### Actual output

Any items on the list remain.

### Steps to reproduce

1. Create a list resource with in-line `item {`s
2. Apply the terraform
3. Comment out or remove the all the in-line `item` attributes
4. Apply the terraform

### Additional factoids

Terraform will correctly detect the change and plan to remove the items from the list.  However, on the cloudflare dashboard, the items will remain on the list.

Having zero item attributes will _not_ result in an empty list.  The list will retain however many items it contained prior to being configured with none. 

Subsequent  runs of terraform will continue to detect the drift, but will not clear the list content out.

**Comment by jacobbednarz** [comment]
closed by #2304
