### ISSUE TITLE
`service_auth_401_redirect` cannot be set to true in any way by the provider

### ISSUE THREAD

**Issue by tooboredtocode** [cloudflare/terraform-provider-cloudflare#2306]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0
```

### Affected resource(s)

- `cloudflare_access_application`

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "app" {
  account_id                 = var.account_id
  domain                     = cloudflare_record.app.hostname
  name                       = "App"
  service_auth_401_redirect  = true
  type                       = "self_hosted"
}

resource "cloudflare_access_policy" "app-service-token" {
  account_id     = var.account_id
  application_id = cloudflare_access_application.app.id
  decision       = "non_identity"
  name           = "Allow Service Token"
  precedence     = 1
  include {
    service_token = [
      var.service_token
    ]
  }
}
```

### Link to debug output

https://gist.github.com/tooboredtocode/2b7014027d42ddc888d710936a6cc044

### Expected output

The provider should've been able to create/modify the resource

### Actual output

The following error:
````
access.api.error.invalid_request: service_auth_401_redirect cannot be true when there is no service auth policy on app
````
is returned every time, even when a service auth policy is defined 

### Steps to reproduce

1. Create a `cloudflare_access_application` with a service auth policy and ` service_auth_401_redirect` set to true
2. Try to apply the resource

**Comment by jroyal** [comment]
This should be fixed now. Can you try again, and let me know if you think otherwise?
