### ISSUE TITLE
Cannot import cloudflare_access_rule

### ISSUE THREAD

**Issue by vanmash** [cloudflare/terraform-provider-cloudflare#2312]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.1.0
+ provider registry.terraform.io/hashicorp/azurerm v3.47.0

### Affected resource(s)

cloudflare_access_rule

### Terraform configuration files

```hcl
resource "cloudflare_access_rule" "terraform_managed_resource_REDACTED" {
  mode    = "whitelist"
  zone_id = var.zone_id
  configuration {
    target = "ip"
    value  = "81.x.x.x"
  }
}
```

### Link to debug output

https://gist.github.com/vanmash/0839638f14fcb7974fe95d8e93e34fd4

### Expected output

successful import

### Actual output

 Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.

### Steps to reproduce

1. `terraform init`
2. `cf-terraforming generate`
3. `cf-terraforming import`
4. `terraform import`

### Additional factoids

configuration created with `cf-terraforming`

**Comment by jacobbednarz** [comment]
without debug logs, i suspect your `zone_id` is empty as we don't call `d.SetId("")` in the create so you'll need to address that to use this correctly.

if you can provide a reproduction test case without variables and a full debug log, i'm happy to dig deeper.

**Comment by vanmash** [comment]
Hey Jacob,

I think the `zone_id` was OK, the rest got imported with the same variable.
To be sure I referenced it directly. Also the debug output is provided this time.

Perhaps you could check that? Thank you

**Comment by jacobbednarz** [comment]
here is the issue, the rule doesn't exist

```
2023/03/29 07:04:12 
GET /client/v4/zones/e8e26b1003a14699ddbba6837211b5ca/firewall/access_rules/rules/de98e41252e3131f9e5691f943cbab44 HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform/1.4.2 terraform-plugin-sdk/2.10.1 terraform-provider-cloudflare/4.2.0
Authorization: Bearer [redacted]
Content-Type: application/json
Accept-Encoding: gzip

2023/03/29 07:04:13 
HTTP/2.0 404 Not Found
Cf-Cache-Status: DYNAMIC
Cf-Ray: 7af5921cec4c34b8-WAW
Content-Type: application/json; charset=UTF-8
Date: Wed, 29 Mar 2023 05:04:13 GMT
Server: cloudflare
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGU56Rb8iNWZVUvXhtxwReGLArAZ; SameSite=Lax; path=/; expires=Wed, 29-Mar-23 07:34:14 GMT; HttpOnly
Set-Cookie: __cfruid=3604b57e0b764d121623a63a0ffc8296f6b6322c-1680066253; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 1

{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 10001,
      "message": "firewallaccessrules.api.not_found"
    }
  ],
  "messages": []
}
```

if you're certain the rule exists, your API token may not allow permission to it.

**Comment by EngZaz** [comment]
I had a similar error and found a solution:
I used cf-terraforming to generate the terraform resources for cloudflare_access_rule. And the output was similar to the output in this issue. 
But when I changed the resources to use account_id=123 rather than zone_id=123. Then run the import command
`terraform import cloudflare_access_rule.default account/<account_id>/<rule_id>`
it worked fine. So I wonder if this is a bug, and cf-terraforming should generate cloudflare_access_rule with account_id, not zone_id.

**Comment by uzziaheyee** [comment]
> I had a similar error and found a solution: I used cf-terraforming to generate the terraform resources for cloudflare_access_rule. And the output was similar to the output in this issue. But when I changed the resources to use account_id=123 rather than zone_id=123. Then run the import command `terraform import cloudflare_access_rule.default account/<account_id>/<rule_id>` it worked fine. So I wonder if this is a bug, and cf-terraforming should generate cloudflare_access_rule with account_id, not zone_id.

This solved my issue. In my case, I also had to replace `zone_id=...` with `account_id=...` in the generated `cloudflare_access_rule` resource.

**Comment by cron410** [comment]
I had the same issue, but ONLY with the first `cloudflare_access_rule` in the console/code. I had to import the first rule with `terraform import cloudflare_access_rule.default account/<account_id>/<rule_id>` Rules 2-13 imported just fine with the commands generated by `cf-terraforming`

I changed all `cloudflare_access_rule` resources to use account_id instead of zone_id
```
resource "cloudflare_access_rule" "ip_access_rule_1" {
  mode    = "whitelist"
  notes   = "Corp IP"
  account_id = var.account_id
  configuration {
    target = "ip"
    value  = "1.2.3.4"
  }
}
```
