### ISSUE TITLE
`cloudflare_teams_rule` the behaviour change since the version 4.2.0

### ISSUE THREAD

**Issue by Dudesons** [cloudflare/terraform-provider-cloudflare#2316]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform: `1.3.9`
cloudflare provider: `4.2.0`

### Affected resource(s)

* cloudflare_teams_rule

### Terraform configuration files

```hcl
resource "cloudflare_teams_list" "k8s_apiserver_ips" {
  account_id = local.account_id
  name       = "Kubernetes API IPs"
  type       = "IP"
  items      = [for i in data.terraform_remote_state.kubernetes : "${i.outputs.endpoint}/32"]
}

resource "cloudflare_teams_rule" "k8s_apiserver_zero_trust_http" {
  account_id  = local.account_id
  name        = "Don't inspect Kubernetes API"
  description = "Allow connections from kubectl to API"
  precedence  = 10000
  action      = "off"
  enabled     = true
  filters     = ["http"]
  traffic     = format("any(http.conn.dst_ip[*] in $%s)", replace(cloudflare_teams_list.k8s_apiserver_ips.id, "-", ""))
}
```

### Link to debug output

https://gist.github.com/Dudesons/53c930a9badab5af8fbec3bd6ac40657

### Panic output

N/A

### Expected output

```
cloudflare_teams_rule.k8s_apiserver_zero_trust_http: Creating...
cloudflare_teams_rule.k8s_apiserver_zero_trust_http: Creation complete after 2s [id=5bf1ecd0-2e30-47c6-8c50-27db87579c1e]
```

### Actual output

```
╷
│ Error: error creating Teams rule for account "2b24a4de343774b88053d174895695ad": Bypass settings cannot be set for non-tenant accounts (2020)
│ 
│   with cloudflare_teams_rule.k8s_apiserver_zero_trust_http,
│   on teams.tf line 8, in resource "cloudflare_teams_rule" "k8s_apiserver_zero_trust_http":
│    8: resource "cloudflare_teams_rule" "k8s_apiserver_zero_trust_http" {
│ 
╵
```

### Steps to reproduce

I was following information from this post: https://blog.cloudflare.com/kubectl-with-zero-trust/

### Additional factoids

The code from the blog post and my code is working with version `4.1.0` and I can't find changes related to this resource in the change log

**Comment by jacobbednarz** [comment]
this is being discussed at https://github.com/cloudflare/terraform-provider-cloudflare/pull/2303#issuecomment-1480220867 since the payload is always sending `false` values but the service is erroring despite not actually trying to enable anything.

**Comment by wayfrro** [comment]
Same here. Creating `cloudflare_teams_rules` was working just fine in 4.1.0 (I had to downgrade provider back to this version), does not work in 4.2.0 with `Bypass settings cannot be set for non-tenant accounts (2020)` error. Nothing fancy, just broke on provider upgrade, no code changes. Is there any  workaround for  this?
