### ISSUE TITLE
empty geo_restrictions string sent to cloudflare api, instead of omitted object

### ISSUE THREAD

**Issue by nickysemenza** [cloudflare/terraform-provider-cloudflare#2318]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

latest

### Affected resource(s)

cloudflare_custom_ssl

### Terraform configuration files

```hcl
resource "cloudflare_custom_ssl" "example" {
  zone_id = "0da42c8d2132a9ddaf714f9e7c920711"
  custom_ssl_options {
    certificate      = "-----INSERT CERTIFICATE-----"
    private_key      = "-----INSERT PRIVATE KEY-----"
    type             = "legacy_custom"
  }
}
```

### Link to debug output

n/a

### Expected output

cert uploaded without geo restrictions

### Actual output

`geo_restrictions":{"label":""}` appears in the marshaled json

### Steps to reproduce

geo_restrictions is not expected to be sent to the API

**Comment by jacobbednarz** [comment]
#1472 also mentions this issue
