### ISSUE TITLE
Import cloudflare_spectrum_application "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by psytyo** [cloudflare/terraform-provider-cloudflare#2334]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.2.0

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
resource "cloudflare_spectrum_application" "ssh" {
  zone_id      = cloudflare_zone.this.id
  protocol     = "tcp/22"
  traffic_type = "direct"

  dns {
    type = "CNAME"
    name = "ssh.example.com"
  }

  origin_direct = [
    "tcp://1.1.1.1:22"
  ]

  edge_ips {
    type = "static"
    ips  = ["203.0.113.1", "203.0.113.2"]
  }
}
```

### Link to debug output

https://gist.github.com/psytyo/4753ba9ea053f6f354096abfa8807068

### Panic output

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb0ba00]

goroutine 103 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.flattenEdgeIPs(0x0)
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_spectrum_application.go:226 +0x40
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareSpectrumApplicationRead({0x118cf80, 0xc0007819e0}, 0xc000532980, {0xfd4fa0?, 0xc00031da40})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_spectrum_application.go:121 +0xf3b
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareSpectrumApplicationImport({0x118cf80, 0xc0007819e0}, 0xc000532980, {0xfd4fa0, 0xc00031da40})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_spectrum_application.go:164 +0x269
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).ImportState(0xc000120fc0, {0x118cf80, 0xc0007819e0}, 0xc0006af388, {0xc0000f40f0, 0x41})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/provider.go:385 +0x1ac
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ImportResourceState(0xc00011d230, {0x118cf80?, 0xc0007818c0?}, 0xc0000b0620)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1088 +0xf4
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ImportResourceState({{0x1192c70?, 0xc00011d230?}}, {0x118cf80?, 0xc0007818c0?}, 0xc0000b0600?)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5to6server/tf5to6server.go:67 +0xd0
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ImportResourceState({0xc0003e26c0, 0xc0003e2720, {0xc000605140, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf6muxserver/mux_server_ImportResourceState.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc000644f00, {0x118cf80?, 0xc000780c90?}, 0xc00065e5a0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:846 +0x1f6
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0xfa5ac0?, 0xc000644f00}, {0x118cf80, 0xc000780c90}, 0xc00018c310, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:403 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0006061e0, {0x1191c18, 0xc0005824e0}, 0xc0007725a0, 0xc000471320, 0x177fe78, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0006061e0, {0x1191c18, 0xc0005824e0}, 0xc0007725a0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v4.2.0 plugin crashed!

### Expected output

import the resource to the state

### Actual output

Error: Request cancelled
The plugin6.(*GRPCProvider).ImportResourceState request was cancelled.

### Steps to reproduce

1. add resource cloudflare_spectrum_application in terraform
2. try to import the existing spectrum app resource in cloudflare

**Comment by jacobbednarz** [comment]
can you provide the debug log without using the module? this import is working for my static edge IP setup so curious if this is a module related bug.

**Comment by psytyo** [comment]
> can you provide the debug log without using the module? this import is working for my static edge IP setup so curious if this is a module related bug.

Yes sure. Here is the same import without module.
https://gist.github.com/psytyo/77f9e798ec37aa4d0315188eb20f048d

**Comment by jacobbednarz** [comment]
sorry, i'm really confused -- your repro doesn't match what you're attempting to import. the repro you have provided works fine here in the acceptance test suite.

are you able to refine this for a reproduction case i can run to debug?
