### ISSUE TITLE
Provider "cloudflare/cloudflare" v3.35.0 is not compatible with Terraform 1.0.1.

### ISSUE THREAD

**Issue by nuno-silva** [cloudflare/terraform-provider-cloudflare#2340]
### Current Terraform and Cloudflare provider version

Terraform v1.0.1
on linux_amd64

### Description

I'm getting the following message from terraform when I tried to upgrade cloudflare/cloudflare version from 2.x to 3.x:

```
Error: Incompatible provider version

Provider "cloudflare/cloudflare" v3.35.0 is not compatible with Terraform
1.0.1.
You need to downgrade to v3.33.0 or earlier. Select it with the following
constraint:
	version = "3.33.0"

Terraform checked all of the plugin versions matching the given constraint:
	~> 3.29

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.
Alternatively, upgrade to the latest version of Terraform for compatibility
with newer provider releases.
```

This message seems to imply that starting from v3.33.1 or v3.34.0, this provider no longer supports terraform 1.0, but I can't find anything about this in the [CHANGELOG](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md).

The only thing I found is [this](https://github.com/cloudflare/terraform-provider-cloudflare/blob/9fb877391f48025e13e4cdc40a27ad845df8b4bd/CHANGELOG.md#300-september-20th-2021:~:text=provider%3A%20Minimum%20Terraform%20core%20version%20is%20now%200.14%20(%231188)):
> 3.0.0 (September 20th, 2021)
> provider: Minimum Terraform core version is now 0.14 (https://github.com/cloudflare/terraform-provider-cloudflare/issues/1188)

With this in mind, I would expect cloudflare v3.x to support terraform >= 0.14, including 1.0.

So my questions are:
1. was support for 1.0.x indeed dropped after v3.33.0?
2. if so:
    1.  should this be in the CHANGELOG given it's a breaking change?
    4. does this project follow [semver.org](https://semver.org/)?

Thanks in advance

### Use cases

I'm trying to upgrade from "cloudflare/cloudflare" 2.x to 3.x (and possibly 4.x) without having to upgrade terraform as well at the same time.

### Potential Terraform configuration

```hcl
...
```

### References

may be related to [Terraform 0.13 compatibility dropped with 3.33.1](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2188#top) #2188

**Comment by nuno-silva** [comment]
no another note, examples still mention terraform 0.13 as of master (9fb877391):

https://github.com/cloudflare/terraform-provider-cloudflare/blob/9fb877391f48025e13e4cdc40a27ad845df8b4bd/examples/provider/provider.tf#L2

same in the [terraform registry docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs):

![image](https://user-images.githubusercontent.com/6935057/228518305-004e3003-c9a9-4d77-8ff3-db2a8dff6c8c.png)

**Comment by jacobbednarz** [comment]
this is already covered in #2188. the "how to use this provider" is not something we control, it's provided by the registry.

**Comment by nuno-silva** [comment]
Hi @jacobbednarz , thanks for your answer.
That covers my last comment. But what about the issue itself (i.e. support for terraform 1.x being dropped)?

> This message seems to imply that starting from v3.33.1 ~~or v3.34.0~~, this provider no longer supports terraform 1.0, but I can't find anything about this in the [CHANGELOG](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md).
> 
> The only thing I found is [this](https://github.com/cloudflare/terraform-provider-cloudflare/blob/9fb877391f48025e13e4cdc40a27ad845df8b4bd/CHANGELOG.md#300-september-20th-2021:~:text=provider%3A%20Minimum%20Terraform%20core%20version%20is%20now%200.14%20(%231188)):
> > 3.0.0 (September 20th, 2021)
> > provider: Minimum Terraform core version is now 0.14 (https://github.com/cloudflare/terraform-provider-cloudflare/issues/1188)
> 
> With this in mind, I would expect cloudflare v3.x to support terraform >= 0.14, including 1.0.
> 
> So my questions are:
> 1. was support for 1.0.x indeed dropped after v3.33.0?
> 2. if so:
>     1.  should this be in the CHANGELOG given it's a breaking change?
>     4. does this project follow [semver.org](https://semver.org/)?

Thanks in advance

**Comment by jacobbednarz** [comment]
as for terraform < 1.1.5 not working correctly, that isn't anything to do with the provider, that is a core issue that we encountered - https://github.com/hashicorp/terraform/pull/30330.

**Comment by nuno-silva** [comment]
Thanks for the clarification.

The fact is the provider stops working with terraform 1.0.1 starting from v3.33.1. Even if that "isn't anything to do with the provider", I think it's something worth mentioning in the CHANGELOG :slightly_smiling_face:  It may not be a result of some direct change in the provider code but something must have changed such as a dependency bump.

**Comment by jacobbednarz** [comment]
> something must have changed such as a dependency bump

Nope, that's not required at all. Terraform and providers operate in a client/server model so one can cause impact without the other changing.
