### ISSUE TITLE
State errors related to account ID upgrading from 3.13 to 4.2.0

### ISSUE THREAD

**Issue by ewhite62** [cloudflare/terraform-provider-cloudflare#2342]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.2.0
+ provider registry.terraform.io/hashicorp/aws v3.75.1

### Affected resource(s)

worker_scripts

### Terraform configuration files

```hcl
resource "cloudflare_worker_script" "resizer" {
  name       = "resizer_${replace(var.zone_name, "/[^A-Za-z0-9_-]/", "_")}"
  content    = file("${path.module}/resizer.js")
  account_id = var.account_id
}

resource "cloudflare_worker_route" "resizer" {
  zone_id     = var.zone_id
  pattern     = "https://*.${var.zone_name}/gn-resizer"
  script_name = cloudflare_worker_script.resizer.name
}
```

### Link to debug output

https://gist.github.com/ewhite62/c9dd88e025822b44014146a89a26b57b

### Expected output

successful plan without errors, states do not seem to match

### Actual output

Plan: 1 to add, 1 to change, 0 to destroy.
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:wmc_worker_megaleocdn_stg_com}: required missing account ID
│ 
│   with module.media.cloudflare_worker_script.worker,
│   on ../../cloudflare-media/workers.tf line 20, in resource "cloudflare_worker_script" "worker":
│   20: resource "cloudflare_worker_script" "worker" {
│ 
╵
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:wmc_ready_worker_megaleocdn_stg_com}: required missing account ID
│ 
│   with module.media.cloudflare_worker_script.ready_worker[0],
│   on ../../cloudflare-media/workers.tf line 153, in resource "cloudflare_worker_script" "ready_worker":
│  153: resource "cloudflare_worker_script" "ready_worker" {
│ 
╵
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:lcp_worker_megaleocdn_stg_com}: required missing account ID
│ 
│   with module.lcp.cloudflare_worker_script.worker,
│   on ../../cloudflare-packaged-content/workers.tf line 9, in resource "cloudflare_worker_script" "worker":
│    9: resource "cloudflare_worker_script" "worker" {
│ 
╵
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:lcp_suv_worker_megaleocdn_stg_com}: required missing account ID
│ 
│   with module.lcp.cloudflare_worker_script.suv_worker[0],
│   on ../../cloudflare-packaged-content/workers.tf line 129, in resource "cloudflare_worker_script" "suv_worker":
│  129: resource "cloudflare_worker_script" "suv_worker" {
│ 
╵
╷
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:uiplat_document_worker_megaleocdn-stg_com}: required missing account ID
│ 
│   with module.uiplat.cloudflare_worker_script.uiplat_document_worker,
│   on ../../cloudflare-ui-platform/workers.tf line 9, in resource "cloudflare_worker_script" "uiplat_document_worker":
│    9: resource "cloudflare_worker_script" "uiplat_document_worker" {

### Steps to reproduce

1. upgrade cloudflare provider from 3.13 to 4.2.0
2. remove account_id from provider.tf
3. add account_id to appropriate resources
4. terraform init -upgrade
5. terraform plan

**Comment by jacobbednarz** [comment]
you cannot upgrade from 3.13.0 straight to 4.x. you need to use a version where the `account_id` is present at both the provider and resource level, make the move and then go to 4.x for it to work seemlessly (same goes for all other resources that made this move). if you want to make the direct jump, you'll need manually modify your terraform state to include it.

**Comment by ewhite62** [comment]
Thanks Jacob - what interim version do you recommend?

**Comment by jacobbednarz** [comment]
it was added in [v3.31.0](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#3310-december-28th-2022) so any version between that and 4.x should be fine.

**Comment by bradworsfold-workday** [comment]
Hi @jacobbednarz .  We have tried upgrading from v3.13.0 to v3.31.0 as suggested.  However, we are still getting the same error as when we upgraded to v4.2.0.  We are using terraform 1.3.5 when doing the plans.  It seems that when we add the account_id to the cloudflare_worker_script, the cloudflare provider is looking for the account_id in the terraform state file.  The terraform state file definitely doesn't have the account_id in it for our resources.

The only way we've been able to upgrade this provider for those resources is to do a terraform state rm and a subsequent terraform import.

We have dozens of zones and dozens of worker scripts and an automated process that would make this extremely difficult to do.  Looking for a better way to seamlessly handle the upgrade.

**Comment by ewhite62** [comment]
Turns out it looks like this was the culprit - providers.tf
`provider "cloudflare" {
  account_id = var.cf_account_id
  api_token  = var.cf_api_token
}`
we had removed "account_id", but apparently this is still required.  adding it back in appears to have resolved the issue.

**Comment by jacobbednarz** [comment]
> It seems that when we add the account_id to the cloudflare_worker_script, the cloudflare provider is looking for the account_id in the terraform state file.

can you please link me to where you think this is happening? given that it's pretty hard to access the state directly in SDKv2, i suspect you're referring to `d.Get` which is for accessing user provided configuration, not the state.

> we had removed "account_id", but apparently this is still required

the `account_id` at the provider level *is not required* if it is defined at the resource level. this is part of the transitional support that was baked in when the resource got support for explicitly defining the `account_id`. you can see this at https://github.com/cloudflare/terraform-provider-cloudflare/blob/v3.31.0/internal/provider/resource_cloudflare_workers_script.go#L126-L138 (similarly for the `Read` and `Update` methods) where we perform a lookup for the `account_id` in the user provided config using `d.Get(...)` and if that isn't provided, fallback to the provider level `account_id` for the API request. 

as an aside, i see you're using modules. are you able to reproduce this outside of using your module? i suspect that the resource level definition is missing from your module or it isn't getting passed through correctly, which means you won't be getting the automatic benefits here.

**Comment by jacobbednarz** [comment]
if you're unable to track this down, the fastest way to move forward is to manually update the state file with the value you're expecting here and then `terraform apply` should show no diff.

**Comment by ewhite62** [comment]
in 3.35, the account ID indeed does seem to still be required in providers.tf - without it, we get the API errors previously posted.  Yes, we are using sub-modules, and those modules are populated with account_id, but if I remove the account_id from the cloudflare provider block in providers.tf, I get the error. If I put it back, I do not, and everything works fine.

**Comment by jacobbednarz** [comment]
as i mentioned, if you can't track this down, i'd recommend updating it directly in your state file to unblock yourself. using `sed` (or it's modern equivalent `sd`) will allow you to set it in your state file and have it operate as expected.
