### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by urbantz-technical-support** [cloudflare/terraform-provider-cloudflare#2349]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.4
on linux_amd64

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id = data.cloudflare_zone.XXXXXX.id
  kind    = "zone"
  name    = "Cloudflare Managed WAF"
  phase   = "http_request_firewall_managed"

  rules {
    action = "skip"
    action_parameters {
      rules = {
        "XXXX" : "XXXX"
      }
    }

    expression  = "(ip.src eq XXX.XXX.XXX.XXX)"
    description = "XXX"
    enabled     = true
  }

  rules {
    action = "skip"
    action_parameters {
      rules = {
        "XXXX" : "XXXX"
      }
    }
    expression  = "XXX"
    description = "XXX"
    enabled     = true
  }

  rules {
    action = "execute"
    action_parameters {
      id      = "efb7b8c949ac4650a09736fc376e9aee"
      version = "latest"
    }
    expression = "true"
    enabled    = true
  }
}
```

### Link to debug output

https://gist.github.com/urbantz-technical-support/df06886215d449c22ae3b8e7cd1637db

### Expected output

The apply should continue creating resources in cloudflare but it should not error out

### Actual output

It creates the cloudflare resources but fails

### Steps to reproduce

1. terraform init
2. terraform apply

### Additional factoids

Related to the recent migration https://github.com/cloudflare/terraform-provider-cloudflare/pull/2271

I had previously created the resources with the old version (see https://github.com/cloudflare/terraform-provider-cloudflare/issues/2127) but I removed the state and manually deleted the resources so that terraform creates them from sratch.

**Comment by JustJordanT** [comment]
Same issue after importing `ruleset` resources; when moving from `4.1` to `~>4.2`. Now infra is in a bad state and can't delete, same error even when trying to delete by removing code. 

errors are all simular to this.

```
Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.cloudflare_zone_level_rulesets.cloudflare_ruleset.transform_modify_response_headers,
│ provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]"
│ produced an unexpected new value:
│ .rules[2].action_parameters[0].headers[4].value: was
│ cty.StringVal("nosniff"), but now cty.StringVal("1; mode=block").
```

**Comment by jacobbednarz** [comment]
this is expected for some `skip` rules. you can see the details in https://github.com/cloudflare/terraform-provider-cloudflare/issues/2418#issuecomment-1541505398.
