### ISSUE TITLE
Pagerduty Integration Resource

### ISSUE THREAD

**Issue by jordanfelle** [cloudflare/terraform-provider-cloudflare#2350]
### Current Terraform and Cloudflare provider version

Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.2.0
+ provider registry.terraform.io/hashicorp/aws v4.60.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Description

For the Pagerduty notification integration we would like a terraform resource to create and manage that resource

### Use cases

We want to be able to manage all parts of Cloudflare in IAC and this is currently one we have to create manually.

### Potential Terraform configuration

Similar to the notification_policy_webhooks resource

```hcl
resource "cloudflare_notification_policy_integration" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "Pagerduty destination"
  kind        = "pageduty"
  secret     = "my-secret"
}
```

**Comment by jacobbednarz** [comment]
is https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/notification_policy what you are looking for?

**Comment by jordanfelle** [comment]
My understanding that lets you utilize a pagerduty integration, but we want to make the integration in TF to then be able to use in that resource

**Comment by adjavaherian** [comment]
could be related, we're seeing a similar issue with the provider and a pagerduty integration

`received internal server error response (HTTP 500), please try again later`

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

resource "cloudflare_notification_policy" "my_notification" {
 account_id  = var.account_id
 name        = "Health Alert"
 description = "Notification policy"
 enabled     = true

 alert_type = "load_balancing_health_alert"

 pagerduty_integration {
   id = "integration id from pagerduty service"
 }

}
```

using Terraform v1.3.2

No other logs output from TF_DEBUG either

Is there something special about the id / setup in cloudlare or pagerduty before using it in notification?
Email provider appears to work as expected.

Thanks!

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
