### ISSUE TITLE
cloudflare_list_item drift on every run

### ISSUE THREAD

**Issue by filipprosovsky** [cloudflare/terraform-provider-cloudflare#2352]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF: 1.4.2
Provider: 4.2.0

### Affected resource(s)

cloudflare_list_item

### Terraform configuration files

```hcl
resource "cloudflare_list_item" "sample" {
  count = length(local.list_of_ips)

  account_id = <account_id>
  list_id    = <list_id>
  comment    = <comment>

  ip = sort(local.list_of_ips)[count.index]
}
```

### Link to debug output

```
Waiting for the plan to start...

Terraform v1.4.4
on linux_amd64
Initializing plugins and modules...
[1mdata.aws_availability_zones.available: Refreshing...[0m[0m
[1mmodule.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-0b2196d57ff397f16][0m[0m
[1mdata.aws_availability_zones.available: Refresh complete after 1s [id=eu-central-1][0m[0m
[1mmodule.vpc.aws_eip.nat[0]: Refreshing state... [id=eipalloc-044ade2d81ed4d3f9][0m[0m
[1mmodule.vpc.aws_eip.nat[1]: Refreshing state... [id=eipalloc-089b1cab0ccf64621][0m[0m
[1mmodule.vpc.aws_eip.nat[2]: Refreshing state... [id=eipalloc-07e1dccaa868d6e2d][0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[2]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mmodule.vpc.aws_route_table.private[0]: Refreshing state... [id=rtb-0898214f98a3fcc4d][0m[0m
[1mmodule.vpc.aws_route_table.private[2]: Refreshing state... [id=rtb-0d2b903f41c7d8ce7][0m[0m
[1mmodule.vpc.aws_route_table.private[1]: Refreshing state... [id=rtb-079f538ab01e9ce97][0m[0m
[1mmodule.vpc.aws_subnet.private[2]: Refreshing state... [id=subnet-093b03558b5228c73][0m[0m
[1mmodule.vpc.aws_subnet.private[0]: Refreshing state... [id=subnet-0a22b2d166a0cddca][0m[0m
[1mmodule.vpc.aws_subnet.private[1]: Refreshing state... [id=subnet-0efcc71654b38b2e4][0m[0m
[1mmodule.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-0e1508db694703128][0m[0m
[1mmodule.vpc.aws_subnet.public[2]: Refreshing state... [id=subnet-05e7ba4788bdb4948][0m[0m
[1mmodule.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-0d623b6949a1d5290][0m[0m
[1mmodule.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-09db020ea0057a2dd][0m[0m
[1mdata.aws_subnets.private: Refreshing...[0m[0m
[1mmodule.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-0c25cb7b8c5b3b1f9][0m[0m
[1mmodule.vpc.aws_route_table_association.private[0]: Refreshing state... [id=rtbassoc-021aca6fa84a37983][0m[0m
[1mmodule.vpc.aws_route_table_association.private[2]: Refreshing state... [id=rtbassoc-0402818b1cf87c60d][0m[0m
[1mmodule.vpc.aws_route_table_association.private[1]: Refreshing state... [id=rtbassoc-0bab4b2c74ae09d2d][0m[0m
[1mmodule.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-0d623b6949a1d52901080289494][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[2]: Refreshing state... [id=nat-095501ff495900170][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[0]: Refreshing state... [id=nat-0fa22b0e8cc74473a][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[1]: Refreshing state... [id=nat-0b353b10bd5ae8ff9][0m[0m
[1mmodule.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-038946d46229fc18d][0m[0m
[1mmodule.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-08afbc0b1ed0a12a2][0m[0m
[1mmodule.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-0047ca5b283354c65][0m[0m
[1mdata.aws_subnets.private: Refresh complete after 0s [id=eu-central-1][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[0]: Refreshing state... [id=r-rtb-0898214f98a3fcc4d1080289494][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[1]: Refreshing state... [id=r-rtb-079f538ab01e9ce971080289494][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[2]: Refreshing state... [id=r-rtb-0d2b903f41c7d8ce71080289494][0m[0m
[1maws_route53_zone_association.vpc_to_private_hosted_zone: Refreshing state... [id=Z06456102ZLSFJMH9ROPI:vpc-0b2196d57ff397f16:eu-central-1][0m[0m
cloudflare_list_item.allowed_ips[0]: Drift detected (update)
cloudflare_list_item.allowed_ips[1]: Drift detected (update)


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
[31m-[0m/[32m+[0m destroy and then create replacement[0m

Terraform will perform the following actions:

[1m  # cloudflare_list_item.allowed_ips[0][0m must be [1m[31mreplaced[0m
[0m[31m-[0m/[32m+[0m[0m resource "cloudflare_list_item" "allowed_ips" {
      [33m~[0m[0m id         = "4aeee91a7a1248259564432c3e10d171" -> (known after apply)
      [33m~[0m[0m ip         = "<hidden>" [33m->[0m[0m "<hidden>" [31m# forces replacement[0m[0m
        [90m# (3 unchanged attributes hidden)[0m[0m
    }

[1m  # cloudflare_list_item.allowed_ips[1][0m must be [1m[31mreplaced[0m
[0m[31m-[0m/[32m+[0m[0m resource "cloudflare_list_item" "allowed_ips" {
      [33m~[0m[0m id         = "4aeee91a7a1248259564432c3e10d171" -> (known after apply)
      [33m~[0m[0m ip         = "<hidden>" [33m->[0m[0m "<hidden>" [31m# forces replacement[0m[0m
        [90m# (3 unchanged attributes hidden)[0m[0m
    }

[1mPlan:[0m 2 to add, 0 to change, 2 to destroy.
[0m[0m[1m
Do you want to perform these actions in workspace "<hidden>"?[0m
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  [1mEnter a value:[0m [0m[0m[33mapproved using the UI or API[0m[0m

[1mcloudflare_list_item.allowed_ips[1]: Destroying... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Destroying... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Destruction complete after 2s[0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Creating...[0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Destruction complete after 3s[0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Creating...[0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Creation complete after 2s [id=8b7a1406a61f46d0a2215d756cb7eb56][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Creation complete after 2s [id=8b7a1406a61f46d0a2215d756cb7eb56][0m[0m

[1m[32mApply complete! Resources: 2 added, 0 changed, 2 destroyed.[0m[0m

```

### Expected output

No changes. Your infrastructure matches the configuration.

### Actual output

  # cloudflare_list_item.allowed_ips[1] must be replaced
-/+ resource "cloudflare_list_item" "allowed_ips" {
      ~ id         = "<hidden>" -> (known after apply)
      ~ ip         = "<hidden>" -> "<hidden>" # forces replacement
        # (3 unchanged attributes hidden)
    }

  # cloudflare_list_item.allowed_ips[2] must be replaced
-/+ resource "cloudflare_list_item" "allowed_ips" {
      ~ id         = "<hidden>" -> (known after apply)
      ~ ip         = "<hidden>" -> "<hidden>" # forces replacement
        # (3 unchanged attributes hidden)
    }

### Steps to reproduce

1. Fill the list using cloudflare_list_item
2. Sorted or not sorted list (sort function) does the same

### Additional factoids

Tried with count, for_each toset(), for_each with nested for, problem is not the index

**Comment by filipprosovsky** [comment]
`Waiting for the plan to start...

Terraform v1.4.4
on linux_amd64
Initializing plugins and modules...
[1mdata.aws_availability_zones.available: Refreshing...[0m[0m
[1mmodule.vpc.aws_vpc.this[0]: Refreshing state... [id=vpc-0b2196d57ff397f16][0m[0m
[1mdata.aws_availability_zones.available: Refresh complete after 1s [id=eu-central-1][0m[0m
[1mmodule.vpc.aws_eip.nat[0]: Refreshing state... [id=eipalloc-044ade2d81ed4d3f9][0m[0m
[1mmodule.vpc.aws_eip.nat[1]: Refreshing state... [id=eipalloc-089b1cab0ccf64621][0m[0m
[1mmodule.vpc.aws_eip.nat[2]: Refreshing state... [id=eipalloc-07e1dccaa868d6e2d][0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[2]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Refreshing state... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mmodule.vpc.aws_route_table.private[0]: Refreshing state... [id=rtb-0898214f98a3fcc4d][0m[0m
[1mmodule.vpc.aws_route_table.private[2]: Refreshing state... [id=rtb-0d2b903f41c7d8ce7][0m[0m
[1mmodule.vpc.aws_route_table.private[1]: Refreshing state... [id=rtb-079f538ab01e9ce97][0m[0m
[1mmodule.vpc.aws_subnet.private[2]: Refreshing state... [id=subnet-093b03558b5228c73][0m[0m
[1mmodule.vpc.aws_subnet.private[0]: Refreshing state... [id=subnet-0a22b2d166a0cddca][0m[0m
[1mmodule.vpc.aws_subnet.private[1]: Refreshing state... [id=subnet-0efcc71654b38b2e4][0m[0m
[1mmodule.vpc.aws_subnet.public[1]: Refreshing state... [id=subnet-0e1508db694703128][0m[0m
[1mmodule.vpc.aws_subnet.public[2]: Refreshing state... [id=subnet-05e7ba4788bdb4948][0m[0m
[1mmodule.vpc.aws_route_table.public[0]: Refreshing state... [id=rtb-0d623b6949a1d5290][0m[0m
[1mmodule.vpc.aws_subnet.public[0]: Refreshing state... [id=subnet-09db020ea0057a2dd][0m[0m
[1mdata.aws_subnets.private: Refreshing...[0m[0m
[1mmodule.vpc.aws_internet_gateway.this[0]: Refreshing state... [id=igw-0c25cb7b8c5b3b1f9][0m[0m
[1mmodule.vpc.aws_route_table_association.private[0]: Refreshing state... [id=rtbassoc-021aca6fa84a37983][0m[0m
[1mmodule.vpc.aws_route_table_association.private[2]: Refreshing state... [id=rtbassoc-0402818b1cf87c60d][0m[0m
[1mmodule.vpc.aws_route_table_association.private[1]: Refreshing state... [id=rtbassoc-0bab4b2c74ae09d2d][0m[0m
[1mmodule.vpc.aws_route.public_internet_gateway[0]: Refreshing state... [id=r-rtb-0d623b6949a1d52901080289494][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[2]: Refreshing state... [id=nat-095501ff495900170][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[0]: Refreshing state... [id=nat-0fa22b0e8cc74473a][0m[0m
[1mmodule.vpc.aws_nat_gateway.this[1]: Refreshing state... [id=nat-0b353b10bd5ae8ff9][0m[0m
[1mmodule.vpc.aws_route_table_association.public[2]: Refreshing state... [id=rtbassoc-038946d46229fc18d][0m[0m
[1mmodule.vpc.aws_route_table_association.public[0]: Refreshing state... [id=rtbassoc-08afbc0b1ed0a12a2][0m[0m
[1mmodule.vpc.aws_route_table_association.public[1]: Refreshing state... [id=rtbassoc-0047ca5b283354c65][0m[0m
[1mdata.aws_subnets.private: Refresh complete after 0s [id=eu-central-1][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[0]: Refreshing state... [id=r-rtb-0898214f98a3fcc4d1080289494][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[1]: Refreshing state... [id=r-rtb-079f538ab01e9ce971080289494][0m[0m
[1mmodule.vpc.aws_route.private_nat_gateway[2]: Refreshing state... [id=r-rtb-0d2b903f41c7d8ce71080289494][0m[0m
[1maws_route53_zone_association.vpc_to_private_hosted_zone: Refreshing state... [id=Z06456102ZLSFJMH9ROPI:vpc-0b2196d57ff397f16:eu-central-1][0m[0m
cloudflare_list_item.allowed_ips[0]: Drift detected (update)
cloudflare_list_item.allowed_ips[1]: Drift detected (update)


Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
[31m-[0m/[32m+[0m destroy and then create replacement[0m

Terraform will perform the following actions:

[1m  # cloudflare_list_item.allowed_ips[0][0m must be [1m[31mreplaced[0m
[0m[31m-[0m/[32m+[0m[0m resource "cloudflare_list_item" "allowed_ips" {
      [33m~[0m[0m id         = "4aeee91a7a1248259564432c3e10d171" -> (known after apply)
      [33m~[0m[0m ip         = "<hidden>" [33m->[0m[0m "<hidden>" [31m# forces replacement[0m[0m
        [90m# (3 unchanged attributes hidden)[0m[0m
    }

[1m  # cloudflare_list_item.allowed_ips[1][0m must be [1m[31mreplaced[0m
[0m[31m-[0m/[32m+[0m[0m resource "cloudflare_list_item" "allowed_ips" {
      [33m~[0m[0m id         = "4aeee91a7a1248259564432c3e10d171" -> (known after apply)
      [33m~[0m[0m ip         = "<hidden>" [33m->[0m[0m "<hidden>" [31m# forces replacement[0m[0m
        [90m# (3 unchanged attributes hidden)[0m[0m
    }

[1mPlan:[0m 2 to add, 0 to change, 2 to destroy.
[0m[0m[1m
Do you want to perform these actions in workspace "<hidden>"?[0m
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  [1mEnter a value:[0m [0m[0m[33mapproved using the UI or API[0m[0m

[1mcloudflare_list_item.allowed_ips[1]: Destroying... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Destroying... [id=4aeee91a7a1248259564432c3e10d171][0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Destruction complete after 2s[0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Creating...[0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Destruction complete after 3s[0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Creating...[0m[0m
[1mcloudflare_list_item.allowed_ips[1]: Creation complete after 2s [id=8b7a1406a61f46d0a2215d756cb7eb56][0m[0m
[1mcloudflare_list_item.allowed_ips[0]: Creation complete after 2s [id=8b7a1406a61f46d0a2215d756cb7eb56][0m[0m

[1m[32mApply complete! Resources: 2 added, 0 changed, 2 destroyed.[0m[0m
`

**Comment by Cyb3r-Jak3** [comment]
I am able to recreate this

Example
```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.3.0"
    }
  }
}


provider "cloudflare" {
  api_token = var.api_token
}

variable "account_id" {
  type    = string
  default = ""
}

variable "api_token" {
  type = string
  default = ""
}

resource "cloudflare_list" "account_redirects" {
  account_id  = var.account_id
  name        = "debugging"
  description = "Example account list for debugging"
  kind        = "redirect"

  item {
    value {
      redirect {
        source_url            = "example.terraform.cyberjake.xyz"
        target_url            = "https://cyberjake.xyz"
        include_subdomains    = "disabled"
        status_code           = 301
        preserve_path_suffix  = "enabled"
        preserve_query_string = "enabled"
        subpath_matching      = "enabled"
      }
    }
    comment = "Test redirect"
  }
}
```
Gist for apply then subsequent plan
https://gist.github.com/Cyb3r-Jak3/56f8986cedb3b96a9409196a77e502c7

**Comment by oli-sanders** [comment]
i get the following plan with IPs every time after initial apply 
```
  # cloudflare_list.my_ip_list will be updated in-place
  ~ resource "cloudflare_list" "my_ip_list" {
        id          = "f33e0c13c8ca47b6994d8ebb729f3829"
        name        = "my_ips"
        # (3 unchanged attributes hidden)

      - item {
          - value {
              - ip = "192.0.2.1" -> null
            }
        }
      - item {
          - value {
              - ip = "192.0.2.2" -> null
            }
        }
      - item {
          - value {
              - ip = "192.0.2.3" -> null
            }
        }
      + item {
          + value {
              + ip = "192.0.2.1/32"
            }
        }
      + item {
          + value {
              + ip = "192.0.2.2/32"
            }
        }
      + item {
          + value {
              + ip = "192.0.2.3/32"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If i attempt to include cidr notation then the plan looks like

```
  # cloudflare_list.my_ip_list will be updated in-place
  ~ resource "cloudflare_list" "my_ip_list" {
        id          = "f33e0c13c8ca47b6994d8ebb729f3829"
        name        = "my_ips"
        # (3 unchanged attributes hidden)

      - item {
          - value {
              - ip = "192.0.2.1" -> null
            }
        }
      - item {
          - value {
              - ip = "192.0.2.2" -> null
            }
        }
      - item {
          - value {
              - ip = "192.0.2.3" -> null
            }
        }
      + item {
          + value {
              + ip = "192.0.2.1/32/32"
            }
        }
      + item {
          + value {
              + ip = "192.0.2.2/32/32"
            }
        }
      + item {
          + value {
              + ip = "192.0.2.3/32/32"
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by larivierec** [comment]
> i'm sorry but we don't accept reproduction cases with modules or dynamic expressions (like loops). can you please reproduce this without those? if you're still hitting a bug then we can investigate. 

Hello, I'm curious but why?

I'm getting a similar issue with modules and loops if a zone doesn't exist and it has to create it. It inconsistentently deletes and recreates all the firewall rules and zone settings even if the zone id stays the same.

**Comment by jacobbednarz** [comment]
modules and dynamic expressions themselves can contain logic bugs that are not caused by the provider but the operator and are not fixable or reproducible in an isolated environment.

**Comment by Cyb3r-Jak3** [comment]
@jacobbednarz Can this be reopened I am still able to recreate in 4.8.0

**Comment by jacobbednarz** [comment]
let's open a new, specific issue for this since there are multiple things mentioned in this one and the original is lacking.
