### ISSUE TITLE
Cloudflare load balancer regions Data Source

### ISSUE THREAD

**Issue by jordanfelle** [cloudflare/terraform-provider-cloudflare#2362]
### Current Terraform and Cloudflare provider version

Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.3.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Description

We would like to able to use a data source in terraform to hit the cloudflare regions API.

### Use cases

This would let us get a list of all cloudflare geos and then iterate over them

### Potential Terraform configuration

```hcl
data "cloudflare_regions" "example" {
  account_id  = "blah"
  typo = "subdivision_code_a2"
}
```

### References

https://developers.cloudflare.com/api/operations/load-balancer-regions-list-regions

**Comment by jacobbednarz** [comment]
this is not Cloudflare wide; it is a load balancing only feature. the data source would need to be scoped as such for the LB products only.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
