### ISSUE TITLE
Cloudflare Pages Object Upload

### ISSUE THREAD

**Issue by jordanfelle** [cloudflare/terraform-provider-cloudflare#2363]
### Current Terraform and Cloudflare provider version

Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.3.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Description

Similar to how the aws provider lets you upload s3 objects https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_object we want to be able to upload objects to our cloudflare pages projects in terraform

### Use cases

This would be useful for small static sites we want to to host on cloudflare pages

### Potential Terraform configuration

```hcl
resource "cloudflare_pages_project" "basic_project" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
  source {
    type = "zip"
    source = "path/to/file"
  }
}
...
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
