### ISSUE TITLE
cloudflare_load_balancer, missing expected [ when upgrading to 4.0.0

### ISSUE THREAD

**Issue by 7jPUn4w8caDX** [cloudflare/terraform-provider-cloudflare#2373]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.6
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.3.0

### Affected resource(s)

cloudflare_load_balancer
cloudflare_load_balancer.rules
cloudflare_load_balancer.rules.overrides

### Terraform configuration files

```hcl
resource "cloudflare_load_balancer" "cloudflare-test" {
  zone_id          = var.zone_id
  name             = "cloudflare.zone.cloud"
  fallback_pool_id = cloudflare_load_balancer_pool.cloudflare-web-test.id
  default_pool_ids = [cloudflare_load_balancer_pool.cloudflare-web-test.id]
  proxied          = true
  steering_policy  = "off"
  rules {
    name      = "cloudflare-test-rule-1"
    condition = "(http.request.uri.path contains \"/cloudflare-app/\")"
    overrides {
      default_pools = [cloudflare_load_balancer_pool.cloudflare-mobile-test.id]
    }
  }
}
```

### Link to debug output

https://gist.github.com/7jPUn4w8caDX/6de8c34c60eeafbffd62b59378e93bc6

### Expected output

No changes. Your infrastructure matches the configuration.

### Actual output

╷
│ Error: missing expected [
│ 
│   with cloudflare_load_balancer.cloudflare-test,
│   on main.tf line 74, in resource "cloudflare_load_balancer" "cloudflare-test":
│   74:     overrides {
│ 
╵

### Steps to reproduce

1. Create a load balancer using v3.35.0
2. Run terraform init
3. Run terraform apply
4. Update terraform files to use version 4.0 or above
5. Run terraform init -upgrade
6. Run terraform plan

**Comment by jacobbednarz** [comment]
thanks for the issue! i've given this a go with static values instead of the references and i'm afraid I'm not seeing this issue. 

are you able to try the same thing with a minimal reproduction case and let me know how you go?

**Comment by 7jPUn4w8caDX** [comment]
Hello, the problem continues even with static values. i cannot upgrade from version 3 to version 4. 
If i compare a terraform state out of a version 3, against a fresh version 4 the states are the same. So this only happens when doing the upgrade of an existing resource.

`resource "cloudflare_load_balancer" "cloudflare-test" {
  zone_id = var.zone_id
  name    = "cloudflare.q2edge.cloud"
  #  fallback_pool_id = cloudflare_load_balancer_pool.cloudflare-web-test.id
  fallback_pool_id = "9c6f9f83bcb0f24d39ea265d5c8eeec5"
  #  default_pool_ids = [cloudflare_load_balancer_pool.cloudflare-web-test.id]
  default_pool_ids = ["9c6f9f83bcb0f24d39ea265d5c8eeec5"]
  proxied          = true
  steering_policy  = "off"

  rules {
    name      = "cloudflare-test-rule-1"
    condition = "(http.request.uri.path contains \"/cloudflare-app/\")"
    overrides {
      #    default_pools = [cloudflare_load_balancer_pool.cloudflare-mobile-test.id]
      default_pools = ["bf5c64b1f9810204f610f2041d5f27bd"]
    }
  }
}`

It appears to be related to the rules section only. As the upgrade runs when the load balancers rules are removed prior the upgrade.

**Comment by jacobbednarz** [comment]
the only change for `cloudflare_load_balancer` in 4.x is the addition of the resource specific `account_id`. 

does this work for you if you remove the resource from state and import it?

**Comment by 7jPUn4w8caDX** [comment]
I don't see a change in the terraform documentation for "cloudflare_load_balancer", it keeps using the zone id.

Removing and importing the resource at version 4 works, but it wont be functional to me.

Additionally, when deploying the resource under version 4 i get this warning. could it be related?

`2023-04-13T15:36:54.660-0500 [WARN]  Provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value for cloudflare_load_balancer.cloudflare-test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .description: was null, but now cty.StringVal("")
      - .rules[0].disabled: was null, but now cty.False
      - .rules[0].overrides[0].session_affinity: was null, but now cty.StringVal("")
      - .rules[0].overrides[0].session_affinity_ttl: was null, but now cty.NumberIntVal(0)
      - .rules[0].overrides[0].ttl: was null, but now cty.NumberIntVal(0)
      - .rules[0].overrides[0].fallback_pool: was null, but now cty.StringVal("")
`

**Comment by 7jPUn4w8caDX** [comment]
If the load balancer was created on version 3.35, there are no issues upgrading into version 4.0.0.
However, if the load balancer was created on version 3.34 or earlier, and there is an override rule, the upgrade 3.34 to 3.35 to 4.0 will fail.

So any existing loadbalancer older than that is failing.

╷
│ Error: missing expected [
│ 
│   with cloudflare_load_balancer.cloudflare-test,
│   on main.tf line 78, in resource "cloudflare_load_balancer" "cloudflare-test":
│   78:     overrides {
│ 
╵

Could this be related to fix no longer available? https://github.com/cloudflare/terraform-provider-cloudflare/pull/1257

**Comment by 7jPUn4w8caDX** [comment]
@sbfaulkner , I never saw a fix for this. So I had to delete the load balancer state and import the resources using version 4 to get them working again.

**Comment by sbfaulkner** [comment]
when I try to import, it doesn't import the "overrides" - only the rule... so then a plan indicates it's going to add the overrides (which makes me uneasy for our production load balancers)

**Comment by tsunamaru** [comment]
Stumbled upon this as well trying to upgrade from 3.35.0 to 4.x

The solution is to find your load balancer in tfstate, add missing `[]` to `session_affinity_attributes` and change `drain_duration` to int:
```
# Before
            "session_affinity_attributes": {
              "drain_duration": "0",
              "samesite": "Auto",
              "secure": "Auto",
              "zero_downtime_failover": "none"
            },

# After
            "session_affinity_attributes": [{
              "drain_duration": 0,
              "samesite": "Auto",
              "secure": "Auto",
              "zero_downtime_failover": "none"
            }],
```

Hope this helps!
