### ISSUE TITLE
add body_scanning option to cloudflare_teams_account (Resource)

### ISSUE THREAD

**Issue by mxmcmd** [cloudflare/terraform-provider-cloudflare#2374]
### Current Terraform and Cloudflare provider version

Terraform 1.3.2
Cloudflare provider 3.35.0

### Description

Hello, 
Is it possible to add body_scanning option to cloudflare_teams_account (Resource) ?
API call:
"body_scanning": {
                "inspection_mode": "deep"
            }

In dashboard webUI: Zero Trust > Settings > Network > Enable enhanced file detection.

Kind regards

### Use cases

Terraform the conf to allows inspection and extraction of file information from our traffic.
https://developers.cloudflare.com/cloudflare-one/analytics/logs/gateway-logs/#enhanced-file-detection.

### Potential Terraform configuration

body_scanning {
                inspection_mode = true
            }

**Comment by webbgeorge** [comment]
Also looking for the same functionality - have raised a PR in the Go SDK to add this there, and also happy to make a PR for the change in this repo if/when it is released on the SDK. 
https://github.com/cloudflare/cloudflare-go/pull/1423
