### ISSUE TITLE
add support for nel zone setting

### ISSUE THREAD

**Issue by sbfaulkner** [cloudflare/terraform-provider-cloudflare#2377]
### Current Terraform and Cloudflare provider version

latest

### Description

the zone settings api supports enabling or disabling `nel` - please update the terraform provider to support it as well

eg.
```
curl -X PATCH "https://api.cloudflare.com/client/v4/zones/ZONE_ID/settings/nel" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: API_KEY" \
     -H "Content-Type: application/json" \
     --data '{"value":{"enabled":true}}'
```

### Use cases

to enable full configuration of zone via terraform instead of having to turn on some settings manually via UI

### Potential Terraform configuration

as for other zone settings...

```hcl
resource "cloudflare_zone_settings_override" "settings" {
  zone_id = local.zone_id

  settings {
    ...
    nel = "on" # or "off"
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
