### ISSUE TITLE
cloudflare_notification_policy does not support Megabit per Second filters

### ISSUE THREAD

**Issue by DDuarte** [cloudflare/terraform-provider-cloudflare#2384]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.34.0

### Affected resource(s)

- cloudflare_notification_policy

### Terraform configuration files

```hcl
resource "cloudflare_notification_policy" "advanced_ddos_attack_l4_alert" {
  account_id  = local.account_id
  name        = "Advanced Layer 3/4 DDoS Attack Alert"
  enabled     = true
  alert_type  = "advanced_ddos_attack_l4_alert"

  filters {
    megabits_per_second = ["50"]
    packets_per_second = ["50000"]
  }
}
```

### Link to debug output

N/A

### Expected output

Resource is managed properly

### Actual output

```
│ Error: failed to set filters: Invalid address to set: []string{"filters", "0", "megabits_per_second"}
```

### Steps to reproduce

1. Create resource has exemplified above

**Comment by jacobbednarz** [comment]
megabits_per_second is not a support field so it won't work here. moving to an enhancement issue.
