### ISSUE TITLE
Missing support for Automatic Signed Exchanges (SXGs)

### ISSUE THREAD

**Issue by azuretek** [cloudflare/terraform-provider-cloudflare#2387]
### Current Terraform and Cloudflare provider version

Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.3.0

### Description

Support for the Automatic Signed Exchanges setting, we should be able to enable or disable this setting using the `cloudflare_zone_settings_override` resource.

### Use cases

* Enable SXG
* Disable SXG

### Potential Terraform configuration

```hcl
resource "cloudflare_zone_settings_override" "setting" {
  zone_id = data.cloudflare_zone.zone.id

  settings {
    sxg = "on"
  }
}
```

### References

I was unable to find another issue or PR mentioning this setting.

**Comment by azuretek** [comment]
It looks like the endpoint for this setting is as follows but I'm not finding it in the API docs

```
/api/v4/zones/<zone id>/amp/sxg
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
