### ISSUE TITLE
Error updating waf ruleset

### ISSUE THREAD

**Issue by greatseb** [cloudflare/terraform-provider-cloudflare#2389]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.4.0
+ provider registry.terraform.io/hashicorp/aws v4.63.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "waf_rule" {
  name    = "default"
  kind    = "zone"
  zone_id = ""
  phase   = "http_request_firewall_managed"
  rules {
    description = "exampleruletoskip"
    expression  = "(http.host eq \"")"
    action      = "skip"
    enabled     = true
    logging {
      enabled = true
    }
    action_parameters {
      rules = {
        "4814384a9e5d4991b9815dcfc25d2f1f" = "6179ae15870a4bb7b2d480d4843b323c",
        "efb7b8c949ac4650a09736fc376e9aee" = "23548ee2b36547a1be09bb2c0550c529,4465544932e14c36961be65e12d77f44,e7e4b386797e417c998d872956c390a1,e35c9a670b864a3ba0203ffb1bc977d1"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/greatseb/d68e729bc18548f41c2ece531458d12a

### Expected output

Standard apply output

### Actual output

cloudflare_ruleset.waf_rule: Modifying... [id=0f9b2d89167947328d80f3f335e17df5]
╷
│ Error: error updating ruleset with ID "0f9b2d89167947328d80f3f335e17df5"
│ 
│   with cloudflare_ruleset.waf_rule,
│   on rulesets.tf line 1, in resource "cloudflare_ruleset" "waf_rule":
│    1: resource "cloudflare_ruleset" "waf_rule" {
│ 
│ there are invalid configured rules to skip
╵

### Steps to reproduce

1. terraform import
2. change
3. terraform apply

**Comment by jacobbednarz** [comment]
the debug log provided is for a plan and not showing what HTTP interactions are made for the Cloudflare API. can you please attach an apply operation that includes those too?

i think this is a misunderstanding of the IDs to use here from the error message though;

> there are invalid configured rules to skip

**Comment by greatseb** [comment]
the ruleset id that we used is:

```
{
    "result": {
        "id": "0f9b2d89167947328d80f3f335e17df5",
        "name": "default",
        "description": "",
        "source": "firewall_managed",
        "kind": "zone",
        "version": "66",
        "rules": [
            {
```

The command we used in postman to retrieve this ID was:

[https://api.cloudflare.com/client/v4/zones/8b277f4d20fbf51106963e6b6350d36e/rulesets/phases/http_request_firewall_managed/entrypoint](url)

Below is the debug log for an apply operation

[https://gist.github.com/greatseb/fdd93945371dc253603248211fd0915c](url)

**Comment by jacobbednarz** [comment]
confirmed with the logs, those are invalid rule IDs and the API is responding as suvh. you need to find the ruleset _rules_ that you want to skip and are able to be skipped.

you can alternatively try the `cloudflare_rulesets` data source to see if that yields you a better ID mapping but YMMV depending on your experience - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/rulesets.

**Comment by greatseb** [comment]
followed your advice and used this to retrieve the ID:
```
data "cloudflare_rulesets" "example" {
  zone_id = "8b277f4d20fbf51106963e6b6350d36e"
  filter{
    kind = "zone"
    phase = "http_request_firewall_managed"
  }
}
output "cloudflare_data_output" {
  description = "mon gros penis"
  value = data.cloudflare_rulesets.example
}
```
and got this (snippet) at the apply

```
cloudflare_data_output = {
  "account_id" = tostring(null)
  "filter" = tolist([
    {
      "id" = ""
      "kind" = "zone"
      "name" = ""
      "phase" = "http_request_firewall_managed"
      "version" = ""
    },
  ])
  "id" = "3c7d194b91776e2e28d5fc6b688d36b3"
  "include_rules" = tobool(null)
  "rulesets" = tolist([
    {
      "description" = ""
      "id" = "0f9b2d89167947328d80f3f335e17df5"
      "kind" = "zone"
      "name" = "default"
      "phase" = "http_request_firewall_managed"
      "rules" = tolist([])
      "version" = "66"
    },
  ])
  "zone_id" = "8b277f4d20fbf51106963e6b6350d36e"
}
```
When using the ID retrieved above, got another error message:
```
$ terraform import cloudflare_ruleset.waf_rule zone/8b277f4d20fbf51106963e6b6350d36e/3c7d194b91776e2e28d5fc6b688d36b3
cloudflare_ruleset.waf_rule: Importing from ID "zone/8b277f4d20fbf51106963e6b6350d36e/3c7d194b91776e2e28d5fc6b688d36b3"...
data.cloudflare_rulesets.example: Reading...
cloudflare_ruleset.waf_rule: Import prepared!
  Prepared cloudflare_ruleset for import
cloudflare_ruleset.waf_rule: Refreshing state... [id=3c7d194b91776e2e28d5fc6b688d36b3]
data.cloudflare_rulesets.example: Read complete after 1s [id=3c7d194b91776e2e28d5fc6b688d36b3]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "cloudflare_ruleset.waf_rule", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it
│ is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
╵

Releasing state lock. This may take a few moments...
$
```
Not sure which ID to use then as both return different errors

**Comment by jacobbednarz** [comment]
you're trying to do two different things hence the different errors for different IDs. in the first example, you're operating on rules within a ruleset however the second is importing a ruleset resource. they are expected to be different resources. i'd recommend taking a look at https://developers.cloudflare.com/ruleset-engine/ and the WAF examples at https://developers.cloudflare.com/waf/ to get an understanding of how these two concepts fit together as it isn't a terraform specific issue here.
