### ISSUE TITLE
cloudflare_record attempted to override existing record however didn't find an exact match

### ISSUE THREAD

**Issue by ajax-mykhailo-oleksiuk** [cloudflare/terraform-provider-cloudflare#2407]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
+ provider registry.terraform.io/hashicorp/aws v4.59.0
```

### Affected resource(s)

`cloudflare_record`

### Terraform configuration files

```hcl
terraform {
  required_version = "1.3.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.59.0"
    }

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

provider "cloudflare" {
  api_token = ""
}

locals {
  domain = "*.ajax.systems"
}

data "cloudflare_zone" "this" {
  name = trimprefix(local.domain, "*.")
}

module "this" {
  source  = "terraform-aws-modules/acm/aws"
  version = "4.3.2"

  zone_id     = data.cloudflare_zone.this.id
  domain_name = local.domain

  create_route53_records  = false
  validation_record_fqdns = cloudflare_record.this[*].hostname

  validation_method    = "DNS"
  wait_for_validation  = true
  validate_certificate = true
}

# -------------------------------------
# Certificate validation via Cloudflare
# -------------------------------------
resource "cloudflare_record" "this" {
  count = length(module.this.distinct_domain_names)

  zone_id = data.cloudflare_zone.this.id
  name    = element(module.this.validation_domains, count.index)["resource_record_name"]
  type    = element(module.this.validation_domains, count.index)["resource_record_type"]
  value   = trimsuffix(element(module.this.validation_domains, count.index)["resource_record_value"], ".")
  ttl     = 60
  proxied = false

  allow_overwrite = true
}
```

### Link to debug output

https://gist.github.com/ajax-mykhailo-oleksiuk/36b1b8b106a365b03e0dabd8146f6f45

### Expected output

```
records is overridden
```

### Actual output

```
╷
│ Error: attempted to override existing record however didn't find an exact match
│ 
│   with cloudflare_record.this[0],
│   on certificate.tf line 19, in resource "cloudflare_record" "this":
│   19: resource "cloudflare_record" "this" {
│ 
╵

```

### Steps to reproduce

1. Request a new certificate from Amazon with auto-renew and validation from Cloudflare. (For example region `eu-west-1`) This step completes successfully because Cloudflare doesn't have cname record for a new certificate.
2. Request a new certificate for the same domain from Amazon but in another region (for example `us-east-1`). This step fails with the error above. (Difference between codebase for different region in aws provider only)

### Additional factoids

1. I tried to import the existing record created by codebase in `eu-west-1` to codebase in `us-east-1` and hoped to have a workaround for this but getting "recreate" stage in codebase for `us-east-1`:

```
-/+ resource "cloudflare_record" "this" {
      + allow_overwrite = true
      ~ created_on      = "2023-05-02T07:57:20.150533Z" -> (known after apply)
      ~ hostname        = "_c5ff38ec8554d7a1bfb88decc1f2440c.ajax.systems" -> (known after apply)
      ~ id              = "7d0451da4cf5eca917e6aeddd9193467" -> (known after apply)
      ~ metadata        = {
          - "auto_added"             = "false"
          - "managed_by_apps"        = "false"
          - "managed_by_argo_tunnel" = "false"
          - "source"                 = "primary"
        } -> (known after apply)
      ~ modified_on     = "2023-05-02T07:57:20.150533Z" -> (known after apply)
      ~ name            = "_c5ff38ec8554d7a1bfb88decc1f2440c" -> "_c5ff38ec8554d7a1bfb88decc1f2440c.ajax.systems." # forces replacement
      ~ proxiable       = false -> (known after apply)
      - tags            = [] -> null
        # (5 unchanged attributes hidden)
    }
```

2. In terraform debug logs I see that it finds existing record but then says `attempted to override existing record however didn't find an exact match`. But when I set (for test purposes) `allow_overwrite = false` I'm getting error showing that match was successful:

![Screenshot 2023-05-03 at 09 39 44](https://user-images.githubusercontent.com/110532903/235856922-1e30f470-d944-41b3-939f-b01c291f2887.png)

**Comment by jacobbednarz** [comment]
that still relies on loops and accessing indexes directly. you should be able to build a reproduction case with just two `cloudflare_record` resources with static values. the first without a `allow_overwrite`, the second with it and a `depends_on` to ensure correct ordering.

**Comment by joshuanave** [comment]
I can verify this behavior as well. However if you import the record into tfstate it will work just fine. At least for me.

**Comment by jacobbednarz** [comment]
the value you are using won't work as if the value isn't `@` or the root domain, we combine the `name` with the zone name to build the value - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/resource_cloudflare_record.go#L144-L154. 

to make this work, the `name` value should only be `_c5ff38ec8554d7a1bfb88decc1f2440c`.

**Comment by rusachello** [comment]
I'm facing a same issue. 
I've added two records in CF,  name: _"example"_,  ip addresses _"1.2.3.4"_ and _"4.3.2.1"_  (for test purposes)

```
terraform {
  required_version = "1.5.2"
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 4.10"
    }
  }
}

resource "cloudflare_record" "example1" {
  zone_id = data.cloudflare_zone.default.id
  name    = "example"
  type    = "A"
  value   = "1.2.3.4"
  ttl     = 1
  proxied = true
  allow_overwrite = true
}

resource "cloudflare_record" "example2" {
  zone_id = data.cloudflare_zone.default.id
  name    = "example"
  type    = "A"
  value   = "4.3.2.1"
  ttl     = 1
  proxied = true
  allow_overwrite = true
}

data "cloudflare_zone" "default" {
  name = var.zone
}
```

After `terraform apply` i get error:

```
cloudflare_record.example2: Creating...
cloudflare_record.example1: Creating...
cloudflare_record.example2: Still creating... [10s elapsed]
cloudflare_record.example1: Still creating... [10s elapsed]
cloudflare_record.example1: Still creating... [20s elapsed]
cloudflare_record.example2: Still creating... [20s elapsed]
cloudflare_record.example1: Still creating... [30s elapsed]
cloudflare_record.example2: Still creating... [30s elapsed]
╷
│ Error: attempted to override existing record however didn't find an exact match
│
│   with cloudflare_record.example1,
│   on test.tf line 11, in resource "cloudflare_record" "example1":
│   11: resource "cloudflare_record" "example1" {
│
╵
╷
│ Error: attempted to override existing record however didn't find an exact match
│
│   with cloudflare_record.example2,
│   on test.tf line 21, in resource "cloudflare_record" "example2":
│   21: resource "cloudflare_record" "example2" {
│
╵
```
And if I change `allow_overwrite = false` I'm getting error:

```
cloudflare_record.example1: Creating...
cloudflare_record.example2: Creating...
cloudflare_record.example1: Still creating... [10s elapsed]
cloudflare_record.example2: Still creating... [10s elapsed]
cloudflare_record.example2: Still creating... [20s elapsed]
cloudflare_record.example1: Still creating... [20s elapsed]
cloudflare_record.example2: Still creating... [30s elapsed]
cloudflare_record.example1: Still creating... [30s elapsed]
╷
│ Error: expected DNS record to not already be present but already exists
│
│   with cloudflare_record.example1,
│   on test.tf line 11, in resource "cloudflare_record" "example1":
│   11: resource "cloudflare_record" "example1" {
│
╵
╷
│ Error: expected DNS record to not already be present but already exists
│
│   with cloudflare_record.example2,
│   on test.tf line 21, in resource "cloudflare_record" "example2":
│   21: resource "cloudflare_record" "example2" {
│
╵
```
Help me please @jacobbednarz @ajax-mykhailo-oleksiuk 
What is the problem in my case?

**Comment by scott-doyland-burrows** [comment]
I have the same issue as the OP.

In my case I create a certificate in AWS that allows:

```example.com```
```*.example.com```

AWS creates validation records that need to be inserted into Cloudflare.  However both validation records are exactly the same and I cannot define two exact same records, so I need to use ```allow_overwrite = true```.

However, in terraform I then receive ```Error: attempted to override existing record however didn't find an exact match``` for the second validation record.

The reason is that Cloudflare strips off the ```.``` from the ends of the name and value of the validation records, so terrafom (Cloudflare??) cannot find the record to overwrite.

So to workaround this I trim off the ```.``` before writing the record, this then results in a different error ```Error: error deleting Cloudflare Record: Record does not exist. (81044)``` when deleting the record.  Terraform says it cannot find the record, but still deletes it on the first apply, and a second apply then runs with any error.

I appreciate the Cloudflare provider cannot account for all types of input coming from other resources, however this seems to be a specific issue in the Cloudflare provider.  It should handle the above scenario in some shape or form, either allowing the overwrite to work, or allowing the delete the work.

**Comment by scott-doyland-burrows** [comment]
> I'm facing a same issue. I've added two records in CF, name: _"example"_, ip addresses _"1.2.3.4"_ and _"4.3.2.1"_ (for test purposes)
> 
> ```
> terraform {
>   required_version = "1.5.2"
>   required_providers {
>     cloudflare = {
>       source = "cloudflare/cloudflare"
>       version = "~> 4.10"
>     }
>   }
> }
> 
> resource "cloudflare_record" "example1" {
>   zone_id = data.cloudflare_zone.default.id
>   name    = "example"
>   type    = "A"
>   value   = "1.2.3.4"
>   ttl     = 1
>   proxied = true
>   allow_overwrite = true
> }
> 
> resource "cloudflare_record" "example2" {
>   zone_id = data.cloudflare_zone.default.id
>   name    = "example"
>   type    = "A"
>   value   = "4.3.2.1"
>   ttl     = 1
>   proxied = true
>   allow_overwrite = true
> }
> 
> data "cloudflare_zone" "default" {
>   name = var.zone
> }
> ```
> 
> After `terraform apply` i get error:
> 
> ```
> cloudflare_record.example2: Creating...
> cloudflare_record.example1: Creating...
> cloudflare_record.example2: Still creating... [10s elapsed]
> cloudflare_record.example1: Still creating... [10s elapsed]
> cloudflare_record.example1: Still creating... [20s elapsed]
> cloudflare_record.example2: Still creating... [20s elapsed]
> cloudflare_record.example1: Still creating... [30s elapsed]
> cloudflare_record.example2: Still creating... [30s elapsed]
> ╷
> │ Error: attempted to override existing record however didn't find an exact match
> │
> │   with cloudflare_record.example1,
> │   on test.tf line 11, in resource "cloudflare_record" "example1":
> │   11: resource "cloudflare_record" "example1" {
> │
> ╵
> ╷
> │ Error: attempted to override existing record however didn't find an exact match
> │
> │   with cloudflare_record.example2,
> │   on test.tf line 21, in resource "cloudflare_record" "example2":
> │   21: resource "cloudflare_record" "example2" {
> │
> ╵
> ```
> 
> And if I change `allow_overwrite = false` I'm getting error:
> 
> ```
> cloudflare_record.example1: Creating...
> cloudflare_record.example2: Creating...
> cloudflare_record.example1: Still creating... [10s elapsed]
> cloudflare_record.example2: Still creating... [10s elapsed]
> cloudflare_record.example2: Still creating... [20s elapsed]
> cloudflare_record.example1: Still creating... [20s elapsed]
> cloudflare_record.example2: Still creating... [30s elapsed]
> cloudflare_record.example1: Still creating... [30s elapsed]
> ╷
> │ Error: expected DNS record to not already be present but already exists
> │
> │   with cloudflare_record.example1,
> │   on test.tf line 11, in resource "cloudflare_record" "example1":
> │   11: resource "cloudflare_record" "example1" {
> │
> ╵
> ╷
> │ Error: expected DNS record to not already be present but already exists
> │
> │   with cloudflare_record.example2,
> │   on test.tf line 21, in resource "cloudflare_record" "example2":
> │   21: resource "cloudflare_record" "example2" {
> │
> ╵
> ```
> 
> Help me please @jacobbednarz @ajax-mykhailo-oleksiuk What is the problem in my case?

Your example is _wrong_ ```allow_overwrite``` allows you to overwrite a record that is exactly the same as a current record.  In your example the value is different so it is not supposed to overwrite it.

All you need to do is remove the second resource and just update the first resource with the value you want.

```allow_overwrite``` is designed to be used where another resource is creating duplicate records, such as AWS certificate validation records, and those duplicate records are being passed to Cloudflare.

**Comment by waddles** [comment]
As @jacobbednarz alluded to in https://github.com/cloudflare/terraform-provider-cloudflare/issues/2407#issuecomment-1537593487, if you trim the zone's name from the record's `name` it does work, so the correct workaround for making domain validation records from an AWS certificate request is:
```hcl
data "cloudflare_zone" "default" {
  name = var.zone
}

resource "cloudflare_record" "cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.this.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  zone_id         = data.cloudflare_zone.default.zone_id
  name            = trimsuffix(each.value.name, ".${data.cloudflare_zone.default.name}.")
  value           = each.value.record
  type            = each.value.type
  allow_overwrite = true
}
```

**Comment by infowolfe** [comment]
If you're reading this because you're using cdktf and tried to `Token.as_list(records_iterator.pluck_property("name"))` use the `hostname` property instead and `aws_acm_certificate_validation` won't complain anymore, since cloudflare_record's `hostname` == route53_record's `fqdn`.

**Comment by mattbrandman** [comment]
@waddles this thread just saved me another 8 hours of debugging thank you (was unfortunately 8 in when I found it!)
