### ISSUE TITLE
cloudflare_custom_hostname resources constantly apply custom certificates if supplied regardless of changes

### ISSUE THREAD

**Issue by cdloh** [cloudflare/terraform-provider-cloudflare#2411]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.9
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0

### Affected resource(s)

cloudflare_custom_hostname

### Terraform configuration files

```hcl
resource "cloudflare_custom_hostname" "customHostname" {
  hostname             = "custom-hostname-with-certificate.test.com"
  zone_id              = "1234"
  ssl {
    method             = "http"
    type               = "dv"
    custom_certificate = file("test.crt")
    custom_key         = file("test.key")
  }
}
```

### Link to debug output

https://gist.github.com/cdloh/bf2797592b11c8fe7671b62944e52a42

### Expected output

Terraform doesn't re-apply a certificate changes if not necessary 

### Actual output

Terraform constantly re-applies

### Steps to reproduce

1. Create a custom hostname with a custom certificate
2. Apply and let it create
3. Do a plan or apply afterwards

### Additional factoids

So looks like the Cloudflare API doesn't return any of those details.

We do get the certificate serial_number could use that for drift detection?

**Comment by jacobbednarz** [comment]
it looks like the issue here is that the certificate doesn't move from pending which differs from our desired state 🤔 what does the UI look like?

**Comment by cdloh** [comment]
In the UI it's all green for the certificate. It is moving to active state in the API as well. You can see that on this debug line

https://gist.github.com/cdloh/bf2797592b11c8fe7671b62944e52a42#file-tfplan-output-txt-L130

In the debug output the entire custom domain is not active as I haven't done the verification domain stuff yet. But the SSL is all fine.

Note that this also happens on fully validated domains

**Comment by jacobbednarz** [comment]
after a bit of fluffing about today with TLS certificates, i've managed to find the cause here and it's actually a two part thing. the first (and most confusing) is that the output here isn't quite the full story and it is a side effect of the newer diff executor in Terraform core. the short version is that because one inner value is changing and the others are not explicitly computed, it is showing them as "added" when in reality, it's not. the second bit (the actual bug in the provider) is that the API response changed and the key that used to be used as a "is this nested field available" check, is no longer so all the sub keys are not getting explicitly added -- even when it is allowing empty strings.

hopefully i'll a PR up in the next day or so after i tidy a few things up. the bit you care about is the following if you'd like to fork it and run a custom version locally.

```diff
diff --git internal/sdkv2provider/resource_cloudflare_custom_hostname.go internal/sdkv2provider/resource_cloudflare_custom_hostname.go
index 8be990a2..3ef026a2 100644
--- internal/sdkv2provider/resource_cloudflare_custom_hostname.go
+++ internal/sdkv2provider/resource_cloudflare_custom_hostname.go
@@ -50,13 +50,9 @@ func resourceCloudflareCustomHostnameRead(ctx context.Context, d *schema.Resourc
 
        if !reflect.ValueOf(customHostname.SSL).IsNil() {
                ssl := map[string]interface{}{
-                       "type":                  customHostname.SSL.Type,
-                       "method":                customHostname.SSL.Method,
                        "wildcard":              customHostname.SSL.Wildcard,
                        "status":                customHostname.SSL.Status,
                        "certificate_authority": customHostname.SSL.CertificateAuthority,
-                       "custom_certificate":    customHostname.SSL.CustomCertificate,
-                       "custom_key":            customHostname.SSL.CustomKey,
                        "settings": []map[string]interface{}{{
                                "http2":           customHostname.SSL.Settings.HTTP2,
                                "tls13":           customHostname.SSL.Settings.TLS13,
@@ -65,6 +61,23 @@ func resourceCloudflareCustomHostnameRead(ctx context.Context, d *schema.Resourc
                                "early_hints":     customHostname.SSL.Settings.EarlyHints,
                        }},
                }
+
+               if val, ok := d.GetOk("ssl.0.method"); ok {
+                       ssl["method"] = val.(string)
+               }
+
+               if val, ok := d.GetOk("ssl.0.type"); ok {
+                       ssl["type"] = val.(string)
+               }
+
+               if val, ok := d.GetOk("ssl.0.custom_certificate"); ok {
+                       ssl["custom_certificate"] = val.(string)
+               }
+
+               if val, ok := d.GetOk("ssl.0.custom_key"); ok {
+                       ssl["custom_key"] = val.(string)
+               }
+
```
