### ISSUE TITLE
Turnstile `mode` valid values not documented

### ISSUE THREAD

**Issue by LinusU** [cloudflare/terraform-provider-cloudflare#2417]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```text
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
+ provider registry.terraform.io/hashicorp/aws v4.62.0
```

### Affected resource(s)

- `cloudflare_turnstile_widget`

### Terraform configuration files

```hcl
resource "cloudflare_turnstile_widget" "loco_client" {
  account_id = "xxxxxxxxxxxxx"
  name       = "My thing"
  domains    = ["example.com"]

  mode = ?????
}
```

### Link to debug output

n/a

### Expected output

I expected to be able to read in the documentation which values are supported for the `mode` value.

### Actual output

It's not documented.

### Steps to reproduce

1. https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/turnstile_widget#mode
2. Observe missing documentation

### References

https://developers.cloudflare.com/api/operations/accounts-turnstile-widget-create#request-body

Seems like the valid values are:

- `non-interactive`
- `invisible`
- `managed`

**Comment by LinusU** [comment]
Here is some documentation of the different modes: https://developers.cloudflare.com/turnstile/reference/widget-types/

**Comment by jacobbednarz** [comment]
already addressed via #2413

**Comment by LinusU** [comment]
@jacobbednarz are you sure about that? I cannot see any mention of the different modes in the updated `docs/resources/turnstile_widget.md`

**Comment by jacobbednarz** [comment]
we don't force validation of what is availability so we defer it to the backing service and developer documentation and do not document it specifically for the provider. the only times we add it is for stricter validation rules we apply client side.

**Comment by LinusU** [comment]
https://github.com/cloudflare/terraform-provider-cloudflare/pull/2424 🚀
