### ISSUE TITLE
Error importing cloudflare_access_application resource

### ISSUE THREAD

**Issue by edg4rgarci4** [cloudflare/terraform-provider-cloudflare#2422]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
+ provider registry.terraform.io/hashicorp/aws v4.66.1
+ provider registry.terraform.io/hashicorp/random v3.5.1```

### Affected resource(s)

cloudflare_access_application resource

### Terraform configuration files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.66.1"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.5.0"
    }
  }
  required_version = ">= 1.3"
}

resource "cloudflare_access_application" "tableau_dev_app" {
  account_id                 = local.account_id
  allowed_idps               = ["REDACTED"]
  app_launcher_visible       = true
  auto_redirect_to_identity  = false
  domain                     = "test.org.biz"
  enable_binding_cookie      = false
  http_only_cookie_attribute = true
  logo_url                   = "https://help.tableau.com/current/pro/desktop/en-us/Resources/tableau-logo.png"
  name                       = "Tableau Dev"
  session_duration           = "24h"
  type                       = "self_hosted"
}
```

### Link to debug output

https://gist.github.com/edg4rgarci4/3ecabd1a9ace33b9b63b52fbd17ea167

### Expected output

For the resource to the imported

### Actual output

╷
│ Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.
│ 
│ 
╵

### Steps to reproduce

1. Create Self Hosted Application in UI
2. Define Terraform Configuration
3. Attempt to import resource. 

### Additional factoids

Successfully imported other resources with current configuration.

**Comment by jacobbednarz** [comment]
from the debug logs

> access.api.error.unknown_application

it looks like the ID you've provided is invalid and it cannot find it subsequently meaning it cannot import it.

**Comment by edg4rgarci4** [comment]
🤦‍♂️

**Comment by uhthomas** [comment]
@jacobbednarz Could we reopen this please? We should return an error instead of failing in an obscure way.

**Comment by jacobbednarz** [comment]
there is definitely some room to improve catching the specific missing identifiers for importing here but i wouldn't say this is obsecure or buries the problem given the error handler from Terraform calls out specifically that the resource ID is missing.

> The provider returned a resource missing an identifier during ImportResourceState

happy to review a PR for this but i'll also add something internally to track applying some more error handling across the board the import method here is pretty standard to our provider (and others in the ecosystem).
