### ISSUE TITLE
cloudflare_ruleset_rule resource

### ISSUE THREAD

**Issue by eidam** [cloudflare/terraform-provider-cloudflare#2423]
### Current Terraform and Cloudflare provider version

Terraform v1.4.6
on darwin_arm64

### Description

Currently, all rules (in our case http_ratelimit) needs to be managed within a single **cloudflare_ruleset** resource per zone. However, we are managing rate limit policies from our Terraform modules, and not always from the same codebase. 

Introducing `cloudflare_ruleset_rule` would help to decouple rules. Once a single ruleset is created, it would be referenced by its ID from all `cloudflare_ruleset_rule` resources.

### Use cases

decouple the config/state, our stack does not allow to manage rate limit rules from a single place per zone

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "ruleset" {
  zone_id     = var.zone_id
  name        = "rate limit ruleset"
  kind        = "zone"
  phase       = "http_ratelimit"

  # rules are empty, managed by individual cloudflare_ruleset_rule resources
  # rules {}
}

resource "cloudflare_ruleset_rule" "example" {
  zone_id     = var.zone_id
  ruleset_id = cloudflare_ruleset.ruleset.id
  name        = "one of the rate limit rules"

  action = "block"
  ratelimit {
    requests_to_origin = true # dont count cache HITs

    characteristics = [
      "cf.colo.id",
      "ip.src"
    ]
    period              = 60
    requests_per_period = 180
    mitigation_timeout  = 600
  }

  expression  = "http.host eq \"${var.examplecom}\""
  description = "rate limit for ${var.examplecom}"
  enabled     = true
}
```

**Comment by jacobbednarz** [comment]
👋 @eidam this is explicitly not supported as there isn't a way within the service to denote priority/ordering outside of providing the ruleset rules in the one payload. we've spoke about it in the past but never progressed due to the addition complexity in management that it introduces to an already complex resource. 

i'm going to close this off as won't do for now as there isn't a way of supporting it within the service. if there is ever supported added there, we can revisit the provider supporting it too.

**Comment by eidam** [comment]
Oh that's unfortunate as its currently blocking us to migrate to the new ruleset engine. I would expect `cloudflare_ruleset_rule` would just follow the "[new placed at the top](https://developers.cloudflare.com/api/operations/createZoneRulesetRule )" ordering/priority, and this could be a warning on the resource documentation.

<img width="921" alt="Screenshot 2023-05-09 at 11 47 13" src="https://github.com/cloudflare/terraform-provider-cloudflare/assets/3592620/2427485c-d5b6-4959-b5cd-0d3cbcd1b46d">

**Comment by jacobbednarz** [comment]
we'd also need to consider the ramifications if we have conflicting sort orders between the API and Terraform (see #187 where this bug still exists in page rules today and requires a workaround).

**Comment by tejado** [comment]
+1 
At least one large CF customer asked for this. In emergency cases, they need to add rules over the dashboard.
We pointed out the workaround to import rules, e.g. over cf-terraforming. I guess its okay but a clear way to have rules as a resource would be better.

**Comment by eidam** [comment]
if it helps, we are also ent and still need this

**Comment by will-schneble** [comment]
We have a use case where we are managing a set of security rules in the ruleset with Terraform but also need to allow customers to CRUD their own rules outside of our Terraform config files. In other words, we want to manage a few rules of the ruleset while leaving the remaining rules in the set unmanaged. Currently the provider is all-or-nothing with regards to managing the rules within a ruleset.

**Comment by rickradinger** [comment]
Bringing this thread to the attention of Cloudflare.  This ability is needed by ent customers.

**Comment by rickradinger** [comment]
> we'd also need to consider the ramifications if we have conflicting sort orders between the API and Terraform (see #187 where this bug still exists in page rules today and requires a workaround).

I would vote to always have TF win in this case.  TF templates MUST always apply, even in the case of the on off application of a rule that conflicts with TF.

**Comment by afoley-st** [comment]
Definitely a bummer that this isn't planned. We are also ent customers looking for this.

**Comment by nagydaoudt** [comment]
For my use case order doesn't matter, But still I can't create rules in different terraform states because ruleset is one resource and it's owned by only one state, This is as @afoley-st described it "Definitely a bummer"

**Comment by auberta2** [comment]
I confirm this is definitely a bummer for us (large ent) as well as we cannot split rules management in multiple states like we used to do up to now
