### ISSUE TITLE
cloudflare_ruleset : An argument named "status" is not expected here

### ISSUE THREAD

**Issue by BarnumD** [cloudflare/terraform-provider-cloudflare#2428]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

When attempting to follow the terraform [documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#categories) as well as cloudflare [documentation](https://developers.cloudflare.com/terraform/additional-configurations/waf-managed-rulesets/#deploy-managed-rulesets), both of which include categories with status defined, I'm attempting the code below and getting `An argument named "status" is not expected here.` error.

I'm using cloudflare provider 4.5.0.

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "zone_level_managed_waf" {
  zone_id     = var.cloudflare_zone_id
  name        = "Managed WAF entry point ruleset for wycliffe.org Zone"
  description = "Zone-level WAF Managed Rules config"
  kind        = "zone"
  phase       = "http_request_firewall_managed"

  # Execute Cloudflare Managed Ruleset
  rules {
    expression  = "(http.host eq \"www.example.com\")"
    description = "Execute Cloudflare Managed Ruleset on my zone-level phase entry point ruleset"
    enabled     = true
    action      = "execute"

    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
      version = "latest"
      overrides {
        action  = "log"

        categories {
          category = "code-injection"
          action   = "log"
          status   = "enabled"
        }
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/BarnumD/7ab3967e44e1a07148380c8d80448e98

### Expected output

Set the tags code-injection to enabled

### Actual output

│ Error: Unsupported argument
│
│   on waf_managed_rulesets.tf line 28, in resource "cloudflare_ruleset" "zone_level_managed_waf":
│   28:           status   = "enabled"
│
│ An argument named "status" is not expected here.

### Steps to reproduce

Add the cloudflare_ruleset above, run terraform apply.

**Comment by jacobbednarz** [comment]
`status` was deprecated immediately in 4.2 after the migration to the plugin framework and we could differentiate zero values - https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#420-22nd-march-2023

the example there needs to be updated if you'd like to send over a PR addressing it.
