### ISSUE TITLE
cloudflare_worker_script is unable to upgrade to 4.x due to account_id

### ISSUE THREAD

**Issue by daraghlowe** [cloudflare/terraform-provider-cloudflare#2430]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.2.4
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0

### Affected resource(s)

cloudflare_worker_script

### Terraform configuration files

```hcl
resource "cloudflare_worker_script" "example_script" {
  account_id = var.cloudflare_account_id
  name       = "example_script"
  content    = file("example.js")


  plain_text_binding {
    name = "EXAMPLE"
    text = var.example
  }
}
```

### Link to debug output

https://gist.github.com/daraghlowe/41fad7740192415124951d32cd681fed

### Expected output

terraform plan should work

### Actual output

```
│ Error: Error reading worker script from API for resource &{ZoneID: ScriptName:example}: required missing account ID

│ 

│   with module.example_zone.cloudflare_worker_script.example_script

│   on ../modules/example/main.tf line 111, in resource "cloudflare_worker_script" "example_script":

│  111: resource "cloudflare_worker_script" "example_script" {
```

### Steps to reproduce

1. Using cloudflare provider version 3.x, the cloudflare account_id is configured in the provider
2. You have configured a cloudflare_worker_script resource
3. Update the cloudflare provider version to 4.5.0
4. Remove the account_id from the provider as its no longer a valid field
5. Add the account_id to the cloudflare_worker_script resource as its now required
6. Terraform plan fails

### Additional factoids

We are blocked on upgrading the cloudflare provider version due to this issue. 

This happens when you have already have a cloudflare_worker_script configured in 3.x and then update the cloudflare provider version to 4.x. You can create new cloudflare_worker_script in version 4.x.

### References

Related similar issues unresolved:
https://github.com/cloudflare/terraform-provider-cloudflare/issues/2286
https://github.com/cloudflare/terraform-provider-cloudflare/issues/2221

**Comment by jacobbednarz** [comment]
this is covered in #2342 -- the specific comment from that thread that is relevant here.

> you cannot upgrade from 3.13.0 straight to 4.x. you need to use a version where the `account_id` is present at both the provider and resource level, make the move and then go to 4.x for it to work seemlessly (same goes for all other resources that made this move). if you want to make the direct jump, you'll need manually modify your terraform state to include it.

**Comment by daraghlowe** [comment]
> this is covered in #2342 -- the specific comment from that thread that is relevant here.
> 
> > you cannot upgrade from 3.13.0 straight to 4.x. you need to use a version where the `account_id` is present at both the provider and resource level, make the move and then go to 4.x for it to work seemlessly (same goes for all other resources that made this move). if you want to make the direct jump, you'll need manually modify your terraform state to include it.

Thanks Jacob, will try that 👍🏻

**Comment by jacobbednarz** [comment]
if that doesn't work (or you can't go back to an older version), you can manually modify your state file to include the value which will allow you to use the correct values here.
