### ISSUE TITLE
cloudflare_pages_project: Add support for setting Build system version

### ISSUE THREAD

**Issue by jamielinux** [cloudflare/terraform-provider-cloudflare#2438]
### Current Terraform and Cloudflare provider version

```console
$ terraform -v
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0
```

### Description

There are currently two possible options for **Build system version**:

- Version 1
- Version 2 (Beta)

It's not currently possible to specify which to use in the `cloudflare_pages_project` resource.

### Use cases

Be able to specify **Build system version** from Terraform code, rather than having to manually change it in the Cloudflare Dashboard.

### Potential Terraform configuration

```hcl
  build_config {
    build_command        = "mkdocs build"
    destination_dir      = "site"
    root_dir             = ""
    build_system_version = 2
  }
```

**Comment by WalshyDev** [comment]
Will get the API docs up for this next week and will handle adding to cloudflare-go. Myself or Jake will add to the Terraform provider :)

**Comment by karolba** [comment]
@WalshyDev Could you share any news? Was this idea scrapped? Can't find `build_image_major_version` in the docs anywhere

**Comment by kdpuvvadi** [comment]
any update regarding this

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
