### ISSUE TITLE
cloudflare_ruleset resource is not working as expected when migration from cloudflare provider 3.0 to 4.5.0

### ISSUE THREAD

**Issue by AnuSelvara** [cloudflare/terraform-provider-cloudflare#2445]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource cloudflare_ruleset challenge_massive_requesters {
  zone_id     = XXXXXX
  name        = "Challenge Massive Error Requesters"
  description = "Challenge Massive Error Requesters"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    enabled = true
    action = "block"
    ratelimit {
      characteristics = [
        "cf.colo.id",
        "ip.src"
      ]
      requests_to_origin = true
      period              = var.rate_limit_errors_period
      requests_per_period = var.rate_limit_errors_threshold
      mitigation_timeout  = 60
      counting_expression = "(http.response.code in {401 403 404 500 501})"
    }

    expression  = "(http.request.uri matches \"%\")"
    description = "Challenge Massive Error Requesters"
  }

  rules {
    enabled = true
    action = "js_challenge"
    ratelimit {
      characteristics = [
        "cf.colo.id",
        "ip.src"
      ]
      requests_to_origin = true
      period              = var.rate_limit_period
      requests_per_period = var.rate_limit_threshold
      mitigation_timeout  = 0
      counting_expression = "(http.request.uri matches \"%\")"
    }
    expression  = "(http.request.uri matches \"%\")"
    description         = "Block Massive Request"
  }
}
```

### Link to debug output

https://github.com/

### Panic output

2023-05-17T20:06:07.914+0200 [INFO]  Terraform version: 1.3.2
2023-05-17T20:06:07.915+0200 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/hcl/v2 v2.14.1
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-05-17T20:06:07.917+0200 [DEBUG] using github.com/zclconf/go-cty v1.11.0
2023-05-17T20:06:07.917+0200 [INFO]  Go runtime version: go1.19.1
2023-05-17T20:06:07.917+0200 [INFO]  CLI args: []string{"C:\\WINDOWS\\system32\\terraform.exe", "apply", "-target", "module.zone_us.cloudflare_ruleset.challenge_massive_requesters"}
2023-05-17T20:06:07.921+0200 [DEBUG] Attempting to open CLI config file: C:\Users\xxxx\AppData\Roaming\terraform.rc
2023-05-17T20:06:07.921+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-05-17T20:06:07.921+0200 [INFO]  Loading CLI configuration from C:\Users\xxxx\AppData\Roaming\terraform.d\credentials.tfrc.json
2023-05-17T20:06:07.922+0200 [DEBUG] checking for credentials in "C:\\Users\\xxxx\\AppData\\Roaming\\terraform.d\\plugins"
2023-05-17T20:06:07.923+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-05-17T20:06:07.923+0200 [DEBUG] will search for provider plugins in C:\Users\xxxx\AppData\Roaming\terraform.d\plugins
2023-05-17T20:06:07.926+0200 [DEBUG] ignoring non-existing provider search directory C:\Users\xxxx\AppData\Roaming\HashiCorp\Terraform\plugins      
2023-05-17T20:06:07.926+0200 [INFO]  CLI command args: []string{"apply", "-target", "module.zone_us.cloudflare_ruleset.challenge_massive_requesters"}   
2023-05-17T20:06:07.950+0200 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2023-05-17T20:06:29.064+0200 [DEBUG] checking for provisioner in "."
2023-05-17T20:06:29.071+0200 [DEBUG] checking for provisioner in "C:\\WINDOWS\\system32"
2023-05-17T20:06:29.072+0200 [DEBUG] checking for provisioner in "C:\\Users\\xxxx\\AppData\\Roaming\\terraform.d\\plugins"
2023-05-17T20:06:29.425+0200 [INFO]  cloud: starting Apply operation
Running apply in Terraform Cloud. Output will stream here. Pressing Ctrl-C 
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.cloudflare_zone.parent_zone: Reading...
data.cloudflare_zone.parent_zone: Read complete after 0s [id=6a9405431ea35ce0b9b48539784a0cf3]
module.zone_us.cloudflare_zone.zone: Refreshing state... [id=e7827a55d9259c4f8a5c11d236ba53c1]
module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Refreshing state... [id=31e10c53399848fbb2550f674d3e63f3]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.zone_us.cloudflare_ruleset.challenge_massive_requesters is tainted, so must be replaced
-/+ resource "cloudflare_ruleset" "challenge_massive_requesters" {
      ~ id          = "31e10c53399848fbb2550f674d3e63f3" -> (known after apply)
        name        = "Challenge Massive Error Requesters"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ id           = "5d26e54c566d43c290fd2071e5297a24" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "6d4f20bb06ea4ce6b2c4c1bf6d3153f7" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ ratelimit {
              + mitigation_timeout  = 0
                # (5 unchanged attributes hidden)
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the
│ result of this plan may not represent all of the changes requested by the
│ current configuration.
│
│ The -target option is not for routine use, and is provided only for
│ exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
╵

  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Destruction complete after 1s
module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Creating...
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.zone_us.cloudflare_ruleset.challenge_massive_requesters, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[1].ratelimit[0].mitigation_timeout: was
│ cty.NumberIntVal(0), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)

### Expected output

Creation of cloudflare_ruleset without any issues

### Actual output

2023-05-17T20:06:07.914+0200 [INFO]  Terraform version: 1.3.2
2023-05-17T20:06:07.915+0200 [DEBUG] using github.com/hashicorp/go-tfe v1.9.0
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/hcl/v2 v2.14.1
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/terraform-config-inspect v0.0.0-20210209133302-4fd17a0faac2
2023-05-17T20:06:07.916+0200 [DEBUG] using github.com/hashicorp/terraform-svchost v0.0.0-20200729002733-f050f53b9734
2023-05-17T20:06:07.917+0200 [DEBUG] using github.com/zclconf/go-cty v1.11.0
2023-05-17T20:06:07.917+0200 [INFO]  Go runtime version: go1.19.1
2023-05-17T20:06:07.917+0200 [INFO]  CLI args: []string{"C:\\WINDOWS\\system32\\terraform.exe", "apply", "-target", "module.zone_us.cloudflare_ruleset.challenge_massive_requesters"}
2023-05-17T20:06:07.921+0200 [DEBUG] Attempting to open CLI config file: C:\Users\xxxx\AppData\Roaming\terraform.rc
2023-05-17T20:06:07.921+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-05-17T20:06:07.921+0200 [INFO]  Loading CLI configuration from C:\Users\xxxx\AppData\Roaming\terraform.d\credentials.tfrc.json
2023-05-17T20:06:07.922+0200 [DEBUG] checking for credentials in "C:\\Users\\xxxx\\AppData\\Roaming\\terraform.d\\plugins"
2023-05-17T20:06:07.923+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-05-17T20:06:07.923+0200 [DEBUG] will search for provider plugins in C:\Users\xxxx\AppData\Roaming\terraform.d\plugins
2023-05-17T20:06:07.926+0200 [DEBUG] ignoring non-existing provider search directory C:\Users\xxxx\AppData\Roaming\HashiCorp\Terraform\plugins      
2023-05-17T20:06:07.926+0200 [INFO]  CLI command args: []string{"apply", "-target", "module.zone_us.cloudflare_ruleset.challenge_massive_requesters"}   
2023-05-17T20:06:07.950+0200 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2023-05-17T20:06:29.064+0200 [DEBUG] checking for provisioner in "."
2023-05-17T20:06:29.071+0200 [DEBUG] checking for provisioner in "C:\\WINDOWS\\system32"
2023-05-17T20:06:29.072+0200 [DEBUG] checking for provisioner in "C:\\Users\\xxxx\\AppData\\Roaming\\terraform.d\\plugins"
2023-05-17T20:06:29.425+0200 [INFO]  cloud: starting Apply operation
Running apply in Terraform Cloud. Output will stream here. Pressing Ctrl-C 
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.

Preparing the remote apply...

Waiting for the plan to start...

Terraform v1.4.6
on linux_amd64
Initializing plugins and modules...
data.cloudflare_zone.parent_zone: Reading...
data.cloudflare_zone.parent_zone: Read complete after 0s [id=6a9405431ea35ce0b9b48539784a0cf3]
module.zone_us.cloudflare_zone.zone: Refreshing state... [id=e7827a55d9259c4f8a5c11d236ba53c1]
module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Refreshing state... [id=31e10c53399848fbb2550f674d3e63f3]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.zone_us.cloudflare_ruleset.challenge_massive_requesters is tainted, so must be replaced
-/+ resource "cloudflare_ruleset" "challenge_massive_requesters" {
      ~ id          = "31e10c53399848fbb2550f674d3e63f3" -> (known after apply)
        name        = "Challenge Massive Error Requesters"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ id           = "5d26e54c566d43c290fd2071e5297a24" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "6d4f20bb06ea4ce6b2c4c1bf6d3153f7" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ ratelimit {
              + mitigation_timeout  = 0
                # (5 unchanged attributes hidden)
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the
│ result of this plan may not represent all of the changes requested by the
│ current configuration.
│
│ The -target option is not for routine use, and is provided only for
│ exceptional situations such as recovering from errors or mistakes, or when
│ Terraform specifically suggests to use it as part of an error message.
╵

  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Destruction complete after 1s
module.zone_us.cloudflare_ruleset.challenge_massive_requesters: Creating...
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes
│ requested in the configuration may have been ignored and the output values
│ may not be fully updated. Run the following command to verify that no other
│ changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is
│ provided only for exceptional situations such as recovering from errors or
│ mistakes, or when Terraform specifically suggests to use it as part of an
│ error message.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.zone_us.cloudflare_ruleset.challenge_massive_requesters, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[1].ratelimit[0].mitigation_timeout: was
│ cty.NumberIntVal(0), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)

### Steps to reproduce

Use cloudflare_ruleset resource using provider version 4.5.0
There should to 2 action rules (1. action=block and 2. action=js_challenge)
Use mitigation_timeout variable for 1st rule block and remove for second one

### Additional factoids

Please help us to fix this issue as soon as possible

### References

https://github.com/search?q=repo%3AAnuSelvara%2FAnuSelvara+https%3A%2F%2Fgithub.com%2Fcloudflare%2Fterraform-provider-cloudflare&type=pullrequests

**Comment by marcel-puchol-jt** [comment]
Not sure if it's exactly the same case, but when we try to upgrade a rule present in a ruleset, seems that all rule IDs are going to change. As example:
```
  # cloudflare_ruleset.test will be updated in-place
  ~ resource "cloudflare_ruleset" "managed_rules" {
        id          = "[redacted]"
        name        = "[redacted]"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ id           = "ecf3ce8914ad45d982454d36c9d3f5a4" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "03950e57a3f5460ca068521f091f902b" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "19bb0e2cf48b4e61b0762a224ab3789d" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "33410ab1ff394b65ac66107a076aec4d" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "b0920b97bb6647cb9567b77309e06987" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "2" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "f251f3c522734ec68ece824d48dda01b" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "1ed6a4ebc27b4801a54aa8bbb70b5ce6" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ expression   = "[redacted]" -> "[redacted-change]"
          ~ id           = "72aab41300674161a3ef7ec5864ab5ef" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "7" -> (known after apply)
            # (3 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "c96e1fc906814a3eb306c925782a4e27" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "0464152c4c874972a6141dfd97b584ff" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
      ~ rules {
          ~ id           = "8f6790c8cc4e4deb9e773e1804d3d817" -> (known after apply)
          + last_updated = (known after apply)
          ~ version      = "3" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

which seems a regression of #2172

**Comment by KarlParkinson** [comment]
@jacobbednarz I am experiencing this issue as well on the latest provider version. Doesn't seem like it has been fixed.

```
resource "cloudflare_ruleset" "zone_level_rate_limiting" {
  zone_id         = data.cloudflare_zone.current.id
  name             = "rate limiting"
  description   = "Rate Limiting Rules for ${var.domain}"
  kind               = "zone"
  phase            = "http_ratelimit"
  
  rules {
    action          = "managed_challenge"
    description  = "Ratelimit /signup"
    enabled        = true
    expression   = "(http.host eq \"secure.getjobber.com\" and http.request.uri.path eq \"/signup\")"

    ratelimit {
      characteristics     = [
        "cf.colo.id",
        "ip.src",
      ]
      period                         = 3600
      requests_per_period = 10
      requests_to_origin     = false
      mitigation_timeout     = 0
    }
  }
}
```

This seems to especially be an issue around rules with a `mitigation_timeout` of 0. I import the existing rule, but then when I run `terraform state show cloudflare_ruleset.zone_level_rate_limiting` the `mitigation_timeout` of 0 is not present in the state.

```
resource "cloudflare_ruleset" "zone_level_rate_limiting" {
    description = "Rate Limiting Rules for getjobber.com"
    id          = "xxxx"
    kind        = "zone"
    name        = "rate limiting"
    phase       = "http_ratelimit"
    zone_id     = "xxxx"

    rules {
        action       = "managed_challenge"
        description  = "Ratelimit /signup"
        enabled      = true
        expression   = "(http.host eq \"secure.getjobber.com\" and http.request.uri.path eq \"/signup\")"
        id           = "xxxx"
        last_updated = "2023-09-21 21:55:47.218282 +0000 UTC"
        ref          = "xxxx"
        version      = "1"

        ratelimit {
            characteristics     = [
                "cf.colo.id",
                "ip.src",
            ]
            period              = 3600
            requests_per_period = 10
            requests_to_origin  = false
        }
    }
}
```

Then `terraform plan` wants to add the `mitigation_timeout`

```

Terraform will perform the following actions:


  # cloudflare_ruleset.zone_level_rate_limiting will be updated in-place
  ~ resource "cloudflare_ruleset" "zone_level_rate_limiting" {
        id          = "cb569331511d46ec8ac1de079b1ec7dc"
        name        = "rate limiting"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ id           = "9eaef890f13547e3a386ef6080d3f7c1" -> (known after apply)
          ~ last_updated = "2023-09-21 21:55:47.218282 +0000 UTC" -> (known after apply)
          ~ ref          = "9eaef890f13547e3a386ef6080d3f7c1" -> (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ ratelimit {
              + mitigation_timeout  = 0
                # (4 unchanged attributes hidden)
            }
        }
    }
```

But `terraform apply` fails with this same error

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/5447860/b0312db6-d3fe-4053-bd2e-827dd1e199bd)

**Comment by DamienDelporte** [comment]
Same error here, after having followed the migration guide from latest 3.x.x to 4.17.0 ...
