### ISSUE TITLE
cloudflare_pages_project.deployment_configs.production.secrets does not seem correct in document.

### ISSUE THREAD

**Issue by Magicloud** [cloudflare/terraform-provider-cloudflare#2451]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: v1.4.6
Cloudflare provider: v3.35.0

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
resource "cloudflare_pages_project" "test" {
  account_id        = local.account_id
  name              = "test"
  production_branch = "develop"

  deployment_configs {
    production {
      secrets = {
        PAT = var.pat
      }
    }
    preview {
      secrets = {
        PAT = var.pat
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/Magicloud/3fbcf651ffa2f4f64b123fe4adc0ff92

### Panic output

N/A

### Expected output

Proper plan output.

### Actual output

╷│ Error: Unsupported argument
│ 
│   on pages.tf line 274, in resource "cloudflare_pages_project" "test":
│  274:       secrets = {
│ 
│ An argument named "secrets" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on pages.tf line 283, in resource "cloudflare_pages_project" "test":
│  283:       secrets = {
│ 
│ An argument named "secrets" is not expected here.

### Steps to reproduce

$ terraform init
$ terraform plan

**Comment by jacobbednarz** [comment]
`secrets` support was added in v4.5.0 (https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#450-3rd-may-2023) however you are using v3.35.0. in order to use this attribute you will need to upgrade to at least v4.5.0
