### ISSUE TITLE
3.18.0 -> 4.6.0 upgrade, plan fails with "The current state of cloudflare_ruleset.<name> was created by a newer provider version than is currently selected."

### ISSUE THREAD

**Issue by NovemberZulu** [cloudflare/terraform-provider-cloudflare#2452]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Currently we are using `cloudflare/cloudflare`@3.18.0 I am upgrading to latest, i.e. `cloudflare/cloudflare`@4.6.0

### Affected resource(s)

* cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "<name>" {

  zone_id = ...
  name    = ...
  kind    = "zone"
  phase   = "http_request_transform"

  rules {
    action = "rewrite"
    action_parameters {
      uri {
        path {
          value = "/404"
        }
      }
    }
  
    expression  = ...
    description = ...
    enabled     = ...
  }
}
```

### Link to debug output

I believe it is not relevant here

### Expected output

Ideally, an empty plan, or at least a successful plan  

### Actual output

╷
│ Warning: Failed to decode resource from state
│
│ Error decoding "cloudflare_ruleset.<name>" from prior state: unsupported attribute "bypass_cache"
╵
...
╷
│ Error: Resource instance managed by newer provider version
│ 
│ The current state of cloudflare_ruleset.<name> was created by a newer provider version than is currently selected. Upgrade the cloudflare provider to work with this state.
╵

### Steps to reproduce

1. Create `cloudflare_ruleset` @ provider version 3.18.0
2. Upgrade provider version to v4.6.0

### References

I believe it is related to #1785, I see `bypass_cache` key in Terraform state on affected objects

**Comment by NovemberZulu** [comment]
The log file is pretty huge and contains quite a lot of information about our internal infrastructure. I am reasonably sure about the root cause, the real question is how to fix the state now with minimal risk

**Comment by tutunak** [comment]
Faced with the same problem during upgrade provider. Followed https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade no changes were made excpet adding accound_id to one resource `cloudflare_worker_script`. After that, has the same error.
