### ISSUE TITLE
When apply ruleset, provider produced an expected news value: .rules[0].last_updated: was cty.String(..) but now null

### ISSUE THREAD

**Issue by owengo** [cloudflare/terraform-provider-cloudflare#2458]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0

### Affected resource(s)

The affected resource is a cloudflare_ruleset , which was generated by cf-terraforming v0.12.0 after upgrading the managed rule in the interface ( thank you cloudflare to require enterprise user to manually generated the rules for all our zones !).
The import was successful , but then when I plan I have this output:

`Terraform will perform the following actions:

  # module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d will be updated in-place
  ~ resource "cloudflare_ruleset" "terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d" {
        id      = "4718cb949ac64f46b69c5ea938f2314d"
        name    = "default"
        # (3 unchanged attributes hidden)

      ~ rules {
            id           = "332f0d60d2f041219c0bd51d76153c42"
          + last_updated = "2023-05-19T09:25:47.862397Z"
          + ref          = "332f0d60d2f041219c0bd51d76153c42"
            # (5 unchanged attributes hidden)

          ~ action_parameters {
              + version = (known after apply)
                # (1 unchanged attribute hidden)
            }

            # (1 unchanged block hidden)
        }
      ~ rules {
          + description  = (known after apply)
            id           = "727360ec30c247c5bedacaf3e9508328"
          + last_updated = "2023-05-19T09:25:47.862397Z"
          + ref          = "727360ec30c247c5bedacaf3e9508328"
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
      ~ rules {
          + description  = (known after apply)
            id           = "2deb9cf07a20409db413bd191f52e25d"
          + last_updated = "2023-05-19T09:25:47.862397Z"
          + ref          = "2deb9cf07a20409db413bd191f52e25d"
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
`
 And then when I apply I have:

`╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].last_updated: was cty.StringVal("2023-05-19T09:25:47.862397Z"), but now
│ null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].ref: was cty.StringVal("332f0d60d2f041219c0bd51d76153c42"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[1].last_updated: was cty.StringVal("2023-05-19T09:25:47.862397Z"), but now
│ null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[1].ref: was cty.StringVal("727360ec30c247c5bedacaf3e9508328"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[2].last_updated: was cty.StringVal("2023-05-19T09:25:47.862397Z"), but now
│ null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.xxxx.cloudflare_ruleset.terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[2].ref: was cty.StringVal("2deb9cf07a20409db413bd191f52e25d"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
`

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "terraform_managed_resource_4718cb949ac64f46b69c5ea938f2314d" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_managed"
  zone_id = var.cloudflare_zoneid
  rules {
    action = "skip"
    action_parameters {
      ruleset = "current"
    }
    description  = "Rule migrated from Firewall Rules: bypass: [d857de93984b49859ad2205f40380616]"
    enabled      = true
    expression   = "((( ip.src in {xxxxxx}) or ( ip.geoip.asnum in {xxxxxxx})))"
    id           = "332f0d60d2f041219c0bd51d76153c42"
    last_updated = "2023-05-19T09:25:47.862397Z"
    logging {
      enabled = true
    }
    ref     = "332f0d60d2f041219c0bd51d76153c42"
    version = "1"
  }
  rules {
    action = "execute"
    action_parameters {
      id = "efb7b8c949ac4650a09736fc376e9aee"
      overrides {
        rules {
          action  = "block"
          enabled = false
          id      = "ae20608d93b94e97988db1bbc12cf9c8"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "7aeb2faf29284398aeb782e54875e938"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "7babab188b3c40ae87b93ec451f4fd5b"
        }
        rules {
          action  = "log"
          enabled = false
          id      = "23ee7cebe6e8443e99ecf932ab579455"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "76f9871c8e88445b807c9ebcd440c742"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "cd7bd3dbe8fd4add9926ad50068b2a17"
        }
        rules {
          action  = "block"
          enabled = false
          id      = "34da2a5e0a95425d9b0e44f07c641d63"
        }
( many more rules )
      }
      version = "latest"
    }
    enabled      = true
    expression   = "true"
    id           = "727360ec30c247c5bedacaf3e9508328"
    last_updated = "2023-05-19T09:25:47.862397Z"
    ref          = "727360ec30c247c5bedacaf3e9508328"
    version      = "1"
  }
  rules {
    action = "execute"
    action_parameters {
      id = "4814384a9e5d4991b9815dcfc25d2f1f"
      overrides {
        categories {
          category = "paranoia-level-3"
          enabled  = false
        }
        categories {
          category = "paranoia-level-4"
          enabled  = false
        }
        rules {
          action          = "log"
          id              = "6179ae15870a4bb7b2d480d4843b323c"
          score_threshold = 25
        }
      }
      version = "latest"
    }
    enabled      = true
    expression   = "true"
    id           = "2deb9cf07a20409db413bd191f52e25d"
    last_updated = "2023-05-19T09:25:47.862397Z"
    ref          = "2deb9cf07a20409db413bd191f52e25d"
    version      = "1"
  }
}
```

### Link to debug output

https://gist.github.com/owengo/a57e45318de3154fb1b4262b98fcf00e

### Expected output

I expect the provider to not crash and actually update the state so that it matches the configuration.

### Actual output

As explained earlier, the provider did not behave correctly

### Steps to reproduce

terraform plan -out plan.save
terraform apply plan.save

### Additional factoids

The issue is blocking the migration from provider ~3 to provider ~4

**Comment by owengo** [comment]
the log file is provided, whatever the bot says.

**Comment by jacobbednarz** [comment]
the debug log file is incomplete which is why it is failing. in order for it to pass, it expects  number of different checkpoints to be included as that gives the full context of what is happening.

you shouldn't need to commit the `last_updated`, `id` or `ref` fields since they are computed so i suspect that is why you are seeing a drift here. you should also try this without using a module since that will throw a spanner in the works while debugging (one of the reasons we don't accept them as reproduction cases).

> I expect the provider to not crash 

to clarify nomenclature here as well, the provider does not crash. it returns a warning however, the operation still completes.

**Comment by owengo** [comment]
Ok so since you say this is normal behavior I close the issue
