### ISSUE TITLE
`cloudflare_origin_ca_certificate` resource seems to require `csr` to be nonempty

### ISSUE THREAD

**Issue by mattmelgard** [cloudflare/terraform-provider-cloudflare#2465]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.7.2
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4
```

### Affected resource(s)

* cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
terraform {
  required_providers {
    sops = {
      source  = "carlpett/sops"
      version = "~> 0.6"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

provider "sops" {}

data "sops_file" "secrets" {
  source_file = "secrets/sops.secrets.yaml"
}

provider "cloudflare" {
  api_token = data.sops_file.secrets.data["cloudflare_api_token"]
}

resource "cloudflare_zone" "myzone" {
  account_id = var.cloudflare_account_id
  zone       = "myzone.com"
}

resource "tls_private_key" "origin_cert" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "origin_cert" {
  private_key_pem = tls_private_key.origin_cert.private_key_pem
}

resource "cloudflare_origin_ca_certificate" "origin_cert" {
  # csr                = tls_cert_request.origin_cert.cert_request_pem
  hostnames          = ["test.myzone.com"]
  request_type       = "origin-rsa"
  requested_validity = 7
}
```

### Link to debug output

https://gist.github.com/mattmelgard/0e35c1b84770d0f666084094163173e4

### Panic output

N/a

### Expected output

The `csr` argument is documented as optional in the [provider documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/4.6.0/docs/resources/origin_ca_certificate), so I would expect that this resource would be created without issue and that I can (assumedly) access the private and public key via the state attributes of the resource.

I realize the API may be designed to require a CSR, however, so if that's the case and a private key does need to be generated on the client side, I would expect the `csr` argument to be required, or at least for there to be some added documentation to highlight when and where it is necessary to generate your own CSR.

Please help me understand if I'm just missing some documented context somewhere on how this all should work, but I wasn't able to easily find any.

Side note: I'm also curious why the official documentation for this resource seems to be utilizing the `tls_private_key` resource and if that's recommended for production use cases if you use an encrypted state backend. I noticed this warning on the [official docs for that resource](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key):

> "The private key generated by this resource will be stored unencrypted in your Terraform state file. Use of this resource for production deployments is not recommended. Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run."

### Actual output

When I comment out the CSR value on the `cloudflare_origin_ca_certificate` resource, I get this error:

```
╷
│ Error: error creating origin certificate: CSR parsed as empty (1007)
│
│   with cloudflare_origin_ca_certificate.origin_certificates,
│   on main.tf line 51, in resource "cloudflare_origin_ca_certificate" "origin_certificates":
│   51: resource "cloudflare_origin_ca_certificate" "origin_certificates" {
│
╵
```

### Steps to reproduce

1. Create a Cloudflare tenant
2. Add a managed zone
3. Create an API token with Zone SSL and Certificates R/W permissions
4. Set up the Terraform like the snippet I provided above
5. Plan/apply with the `csr` attribute commented out and see error as a result

**Comment by jacobbednarz** [comment]
> Side note: I'm also curious why the official documentation for this resource seems to be utilizing the `tls_private_key` resource and if that's recommended for production use cases if you use an encrypted state backend. I noticed this warning on the [official docs for that resource](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key):
> 
> > "The private key generated by this resource will be stored unencrypted in your Terraform state file. Use of this resource for production deployments is not recommended. Instead, generate a private key file outside of Terraform and distribute it securely to the system where Terraform will be run."

the examples used in the documentation *are not* intended as drop in examples for all scenarios. they are intended to demonstrate how to use the resource. you should always read and understand the resource in question and evaluate them against your specific situation.

**Comment by jacobbednarz** [comment]
there is a bit of disconnect here with our docs + implementation as the CSR is required, however, in the dash the application handles creating this for you whereas in terraform, you must provide it.

for the next steps here, i think we'll likely mark it as required (breaking change) and perhaps down the track look at handling the conditional in the backend service to handle this for you.

i'm going to close this one out for now and add it to the list of breaking changes for the next major release.

**Comment by jacobbednarz** [comment]
spoke to some folks about this and given you can't create a certificate without the CSR, marking it as `Required` isn't really a breaking change so i'll put up a PR to enforce this.
