### ISSUE TITLE
Please add support for `environment` to `cloudflare_worker_route`

### ISSUE THREAD

**Issue by akaltar** [cloudflare/terraform-provider-cloudflare#2471]
### Current Terraform and Cloudflare provider version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0

### Description

Please add support for selecting worker `environment` to `cloudflare_worker_route`

### Use cases

We have one domain with one zone, but it serves 2 environments, so testing workers separately would be nice.
Eg. www.staging.domain.com and www.domain.com

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_route" "staging_route" {
  zone_id = var.cloudflare_zone_id
  pattern = "www.staging.domain.com/*"
  environment = "staging"
  script_name = var.script_name
}

resource "cloudflare_worker_route" "prod_route" {
  zone_id = var.cloudflare_zone_id
  pattern = "www.domain.com/*"
  environment = "production"
  script_name = var.script_name
}
```

**Comment by WalshyDev** [comment]
Service environments were deprecated a long time ago and basically removed at this point. Environments in Workers are back to appending the env on to the Worker name

Are you talking about the service environments or the Worker name ones?

I'd personally be hesitant to add an environment field until we properly reimplement actual environments.

**Comment by akaltar** [comment]
I think I mean Environments in Workers. The one you can specify in the Dashboard when adding a Worker Route.
Can that be done by adding a special suffix to the worker name?

**Comment by WalshyDev** [comment]
Yeah, that's service environments, you aren't actually able to create new environments anymore and they're being removed (slowly).

**Comment by akaltar** [comment]
I see, that explains it, thank you
