### ISSUE TITLE
[Ruleset] One rule override in managed ruleset remove all other rules

### ISSUE THREAD

**Issue by guillaume-bauchart** [cloudflare/terraform-provider-cloudflare#2488]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
$ terraform -v
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
+ provider registry.terraform.io/hashicorp/vault v3.15.2
```

### Affected resource(s)

`cloudflare_ruleset`

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "waf_managed_ruleset_leaked_credentials" {
  kind    = "zone"
  name    = "Cloudflare Exposed Credentials Check Ruleset"
  phase   = "http_request_firewall_managed"
  zone_id = "XXX"
  # Leaked Credentials Check
  rules {
    action = "execute"
    action_parameters {
      id = "c2e184081120413c86c3ab7e14069605"
      overrides {
        action  = "log"
        enabled = true
      }
      version = "latest"
    }
    enabled    = true
    expression = "true"
  }
}
```

### Link to debug output

https://gist.github.com/guillaume-bauchart/267e2f1cc202e674496774d90da784b7

### Expected output

I want this ruleset to be enabled and all the rules in it set to `action : log`.

I don't get why the override does not seem to be planned to be applied (as you can see at the end of the gist debug output), and that terraform plans to remove al the other rules. 

When I try to apply, I get an error : 

```
Error: error updating ruleset with ID "c2e184081120413c86c3ab7e14069605"
could not find ruleset c2e184081120413c86c3ab7e14069605
```

Even though I am convinced the ID is correct, according to the cloudflare web interface, and also according to the `terraform state show` command output.

### Actual output

c.f the gist linked

### Steps to reproduce

1. Add a new override to an existing cloudflare managed ruleset rule
2. Terraform apply or plan
3. All rules in the ruleset will get disabled

### Additional factoids

I cannot use the `status` field added by PR 1689, the field is not recognized by the terraform provider

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1397
https://github.com/cloudflare/terraform-provider-cloudflare/pull/1689

**Comment by jacobbednarz** [comment]
can you please provide the TF_LOG output where this isn't reliant on a module? the reproduction test case here doesn't match the output which will make diagnosing this much harder.

**Comment by guillaume-bauchart** [comment]
Hello @jacobbednarz ,

I am very sorry for the delay in my response.

I recreated the problem in a smaller environment, with no module, and a terraform state with less managed resources.

Here is a gist of the output of this command : 

`TF_LOG=DEBUG terraform apply -auto-approve -target=cloudflare_ruleset.waf_managed_ruleset_leaked_credentials`

I did not only a plan but an apply, because it seemed relevent to the situation.  

https://gist.github.com/guillaume-bauchart/fba1788494f152c6f35fa552e3b0ca52

As you can see, the `terraform plan` still tries to remove rules from the ruleset, even though I only wish to overrides the default action of the whole ruleset.

Then, when I try to apply this to see what happend, it fails and I get the error `could not find ruleset c2e184081120413c86c3ab7e14069605`. Even though I am pretty sure it is the correct ruleset id.

According to my tests, it does not change the command's outcome if the rulesets is already manually created by the web interface or not.

**Comment by jacobbednarz** [comment]
something is off there because the API response shows exactly what you are using. 

> According to my tests, it does not change the command's outcome if the rulesets is already manually created by the web interface or not.

have you touched the UI for these resources? that would explain why you have a drift since you should only manage those resources via terraform once they are created otherwise you'll need to remove them from state and reimport them.

**Comment by beaudryj** [comment]
Could this because there is no input for `order` I see that `configuration rules` have an `order` column, yet I am failing to see a way to set a rule to an order number. so it feels as though all rules try to run against rule in position #1. It would be nice to be able to set an order. 

Currently I am trying to create a rule per "environment" i.e. *.${environment}.api.mydomain.com and my rules per environment all try to write to rule #1 and conflict

**Comment by jacobbednarz** [comment]
ordering is explicit based on the configuration you provide so you cannot have rules (via terraform) all at position 1. have you got a reproduction test case for this issue? the one in your original description works as expected on my side.

**Comment by beaudryj** [comment]
> ordering is explicit based on the configuration you provide so you cannot have rules (via terraform) all at position 1. have you got a reproduction test case for this issue? the one in your original description works as expected on my side.

I understand you cannot have rules all at position 1. https://registry.terraform.io/providers/cloudflare/cloudflare/4.3.0/docs/resources/ruleset

However the ruleset resource is not smart enough to autoincrement to next available position, and there is no parameter to allow you to assign one

**Comment by jacobbednarz** [comment]
> However the ruleset resource is not smart enough to autoincrement to next available position

it doesn't need to; it sends them in the order provided. you don't need to provide the order, just the order you wish to have them in.

**Comment by jacobbednarz** [comment]
due to the lack of reproduction case here, I'm going to mark this as needs information until that is provided. the current one works as expected and the information here doesn't suggest something else is happening.

**Comment by beaudryj** [comment]
@jacobbednarz - 

For Example: 
I have 4 Terraform Workspaces. One for Sandbox, Dev, Stage, Production. And I want to isolate the code and have 1 Applied to each workspace and step through flow through environments. 

It would be nice if I could fetch the existing Configs and then append to next available number, or manually apply my desired order. 

```resource "cloudflare_ruleset" "http_config_rules" {
  zone_id     = var.cloudflare_zone_id
  name        = "mtls-config-${var.environment}"
  description = "Set configuration rules for incoming requests"
  kind        = "zone"
  phase       = "http_config_settings"

  rules {
    action = "set_config"
    action_parameters {
      ssl = "origin_pull"
    }
    expression  = var.environment == "PROD" || var.environment == "DEV" ? local.expressions[var.environment].expression : "(http.host matches \".*.api.${lower(var.environment)}.example.com\")"
    description = "Settings Applied for ${var.environment}"
    enabled     = true
  }
}
```


If I cannot do the desired flow above, do I have to now manually delete all of the built by hand rules and then have a single state file and foreach over the config per hostname?

**Comment by LennyCastaneda** [comment]
Hi @jacobbednarz, just wanted to follow up on this one as well. Looking forward to any guidance base what @beaudryj proposed in the above comment.  Thanks again for your help.

**Comment by jacobbednarz** [comment]
> It would be nice if I could fetch the existing Configs and then append to next available number, or manually apply my desired order.

i'm afraid i can't reiterate it any more clearly -- you don't need ordering; it is already inbuilt just by supplying the rule it handles the rest internally. 

the issue you are having here is that you are trying to apply configuration across environments in the same zone in which *you need to have duplicate rules* or update the expression to match all the hostnames you are covering. if you have separate zones, you won't have this as you will be able to apply it individually.
