### ISSUE TITLE
Delete non-empty r2 bucket

### ISSUE THREAD

**Issue by baszalmstra** [cloudflare/terraform-provider-cloudflare#2498]
### Current Terraform and Cloudflare provider version

Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.7.1

### Description

Im very happy with the new resource to manage r2 buckets however, I cannot delete the bucket if it contains data. There is the `force_destroy` option in the aws provider but that doesn't work with cloudflare buckets because the provider expects buckets to also be versioned.

### Use cases

Creating a bucket with for instance 

```hcl
resource "cloudflare_r2_bucket" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "terraform-bucket"
  location   = "enam"
}
```

adding a file to the bucket,
destroying the terraform resource should work.

### Potential Terraform configuration

```hcl
resource "cloudflare_r2_bucket" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "terraform-bucket"
  location   = "enam"
}
```

**Comment by jacobbednarz** [comment]
this is not supported in the API and I'm not sure if the team have plans on adding it so closing this out until such a time when the team adds support first.

**Comment by lbb00** [comment]
The same issue.

**Comment by Visible-Radio** [comment]
Bit by this today. Invested a lot of time setting up terraform to spin up and burn ephemeral environments. Looping through all the objects in the bucket to delete them doesn't seem like it would scale well at all when there are a lot of objects - and it's frankly functionality that shouldn't have to be implemented in userland.
