### ISSUE TITLE
Redirect Rules beta - can create rule without name via terraform

### ISSUE THREAD

**Issue by amitblumshtien** [cloudflare/terraform-provider-cloudflare#2499]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 3.0"
    }
  }
}

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
locals {
  rule_set = var.rule_set != null ? {
    for rs in flatten(var.rule_set) :
    rs.name => rs
  } : {}
}

resource "cloudflare_ruleset" "default" {
  for_each                   = local.rule_set
  name                       = each.value.name
  zone_id                    = var.zone_id
  kind                       = each.value.kind
  phase                      = each.value.phase
  account_id                 = lookup(each.value, "account_id", null)
  description                = lookup(each.value, "description", null)
  shareable_entitlement_name = lookup(each.value, "shareable_entitlement_name", null)

...
}
```

### Link to debug output

no link

### Expected output

a redirect rule with a name

### Actual output

a new redirect rule without name

### Steps to reproduce

try to create a redirect rule using the ruleset resource

**Comment by amitblumshtien** [comment]
`resource "cloudflare_ruleset" "single_redirects_example" {
  zone_id     = var.zone_id
  name        = "redirects"
  description = "Redirects ruleset"
  kind        = "zone"
  phase       = "http_request_dynamic_redirect"

  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 301
        target_url {
          value = "/console/"
        }
        preserve_query_string = false
      }
    }
    expression = "(http.request.uri.path eq \"/login\")"
    # description = "Redirect visitors still using old URL"
    enabled = true
  }
}`

this is the resource i am using when the description field is the filed that is in charge of the required name field via the UI.

**Comment by amitblumshtien** [comment]
The probelmatic file is internal/sdkv2provider/data_source_rulesets.go line 95. 
Would it be possible to change the description field name to name? Alternatively, set the description property to Required:    true.

Afterward, documentation needs to be updated.

**Comment by jacobbednarz** [comment]
i'm sorry; i'm not following what your actual issue is here. your example is for a resource but you mention the issue is in the data source code?

can you please update the issue here to reflect the requested information so we can debug what the issue is here?

**Comment by amitblumshtien** [comment]
@jacobbednarz ok sorry i will be more informative:
1. the code that create a single redirect rule which is a beta feature , is using the following resource for example:
```
resource "cloudflare_ruleset" "single_redirects_example" {
  zone_id     = "<ZONE_ID>"
  name        = "redirects"
  description = "Redirects ruleset"
  kind        = "zone"
  phase       = "http_request_dynamic_redirect"

  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 301
        target_url {
          value = "/contacts/"
        }
        preserve_query_string = false
      }
    }
    expression  = "(http.request.uri.path matches \"^/contact-us/\")"
    description = "Redirect visitors still using old URL"
    enabled     = true
  }
}
```
in case you are not passing the second description property the redirect rule is created with successfully , but with no name , which is a required field via the UI.
see my photo:
 
![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/111686129/e131501c-7c06-4798-b292-77dc33087c5c)
![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/111686129/2e7c7ed8-cc2d-44c5-a35f-636d629bdad3)
