### ISSUE TITLE
provider crashes when importing cloudflare_ruleset

### ISSUE THREAD

**Issue by chris-martinelli** [cloudflare/terraform-provider-cloudflare#2502]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
Provider v3.35.0 to v4.7.1

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
terraform { 
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

provider "cloudflare" {
  # token pulled from $CLOUDFLARE_API_TOKEN
}

resource "cloudflare_ruleset" "transform_rules" {
  kind    = "zone"
  name    = "transform rule to add a request header"
  phase   = "http_request_late_transform"
  zone_id = "64cbd9e9124a7e8a20bddc8365bfd3b9"

rules {
    action = "rewrite"
    action_parameters {
      headers {
        expression = "ip.src"
        name       = "X-test-Forwarded-For"
        operation  = "set"
      }
    }
      expression  = "true"
      description = "replication"
      enabled     = true
    }
  }
```

### Link to debug output

https://gist.github.com/chris-martinelli/dfb181e0d04b12e084673ca6384332e2

### Panic output

[debug.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/11658542/debug.log)

### Expected output

Following the steps outlined in https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade#cloudflare_ruleset, the expectation is to be able to import this resource after upgrading from v3.35.0 to v4.7.1.

### Actual output

```
cloudflare_ruleset.transform_rules: Importing from ID "cd72d32b51904560b408a7d720df15a3"...
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-cloudflare_v4.7.1 plugin:

panic: runtime error: index out of range [1] with length 1
```

### Steps to reproduce

1) Having a cloudflare_ruleset rule in working order using provider v3.35.0

```
cloudflare_ruleset.transform_rules: Creation complete after 1s [id=cd72d32b51904560b408a7d720df15a3]
```

2) Remove the resource

```
terraform state rm cloudflare_ruleset.transform_rules
```

3) Upgrade to v4.7.1
(Updated to version = "~> 4.0" in .tf file)

```
terraform init -upgrade
```

4) Import previously removed resource

```
terraform import cloudflare_ruleset.transform_rules cd72d32b51904560b408a7d720df15a3
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/2501

**Comment by jacobbednarz** [comment]
the issue here is that malformed import string 

```
terraform import cloudflare_ruleset.transform_rules cd72d32b51904560b408a7d720df15a3
```

vs what the provider is expecting (ref: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#import)

```
# Import an account scoped Ruleset configuration.
$ terraform import cloudflare_ruleset.example account/<account_id>/<ruleset_id>

# Import a zone scoped Ruleset configuration.
$ terraform import cloudflare_ruleset.example zone/<zone_id>/<ruleset_id>
```

the crash is from the provider trying to assign them to variables right before the values check which would have given a nicer error message here.

**Comment by chris-martinelli** [comment]
That works, thank you!

```
⭆ ~/ terraform import cloudflare_ruleset.inf_request_header_transforms_dyn zone/64cbd9e9124a7e8a20bddc8365bfd3b9/666be600fba64623997d5083e5d1e459
cloudflare_ruleset.inf_request_header_transforms_dyn: Importing from ID "zone/64cbd9e9124a7e8a20bddc8365bfd3b9/666be600fba64623997d5083e5d1e459"...
cloudflare_ruleset.inf_request_header_transforms_dyn: Import prepared!
  Prepared cloudflare_ruleset for import
cloudflare_ruleset.inf_request_header_transforms_dyn: Refreshing state... [id=666be600fba64623997d5083e5d1e459]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
