### ISSUE TITLE
Provider 4.7.1 Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by ewhite62** [cloudflare/terraform-provider-cloudflare#2506]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.7.1
+ provider registry.terraform.io/hashicorp/aws v3.75.1

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "inf_request_header_transforms" {
  zone_id = var.zone_id
  name    = "transform rule to add a request header"
  kind    = "zone"
  phase   = "http_request_late_transform"

  dynamic "rules" {
    for_each = toset(var.inf_request_header_transforms)
    content {
      action = "rewrite"
      action_parameters {
        headers {
          name      = rules.value.name
          value     = rules.value.value
          operation = "set"
        }
        headers {
          name       = rules.value.name
          expression = rules.value.expression
          operation  = "set"
        }

      }
      expression  = "true"
      description = rules.value.description
      enabled     = true
    }
  }
}
```

### Link to debug output

https://gist.github.com/ewhite62/f8d80bbbffa4bf56a971e9becd9d6376

### Expected output

apply success, creation of transform rules

### Actual output

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.inf.cloudflare_ruleset.inf_request_header_transforms, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected
│ new value: .rules[0].action_parameters[0].headers: block count changed from 2 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.inf.cloudflare_ruleset.inf_request_header_transforms, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected
│ new value: .rules[1].action_parameters[0].headers: block count changed from 2 to 1.

### Steps to reproduce

1. upgrade to provider 4.7.1
2. terraform plan -out plan
3. terraform apply plan

**Comment by chris-martinelli** [comment]
In my testing I am not able to replicate this with the dynamic expressions removed.

**Comment by ewhite62** [comment]
You can ignore the errors in the debug log around load balancer pools, that's been worked out, but the cloudflare_ruleset issue persists.

**Comment by ewhite62** [comment]
Updated debug log - this is after fixing those pool errors, and includes only 'terraform apply'

https://gist.github.com/ewhite62/d306bbd4332a97a74efbe917a0d083eb

**Comment by jacobbednarz** [comment]
the reproduction case here is demonstrating https://github.com/cloudflare/terraform-provider-cloudflare/issues/2343#issuecomment-1489581993. the `headers` values are alphabetically sorted by the Cloudflare service and you will need to supply them in that order to prevent a permadiff.

i assume you're using local maps in your module which does not have guaranteed ordering so you'll need to either use static values in your module or extract this out of the module for it to consistently work.
