### ISSUE TITLE
Constant Diff for CNAME Record pointing to Root Domain.

### ISSUE THREAD

**Issue by RedlineTriad** [cloudflare/terraform-provider-cloudflare#2515]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.7.1
+ provider registry.terraform.io/hetznercloud/hcloud v1.39.0
```

### Affected resource(s)

`cloudflare_record` using `CNAME` type

### Terraform configuration files

```hcl
This is my exact configuration.
https://github.com/RedlineTriad/private_server/blob/e0447ed012faa68a8f4bb7260335958f15c7d9ec/infra/dns.tf#L33
```

### Link to debug output

https://gist.github.com/RedlineTriad/c5890da93c0743011dd7beb92c5bb5ca

### Expected output

I would expect there to be no resource diff since I have made no changes to my terraform files since last apply.

### Actual output

For all `CNAME` records there is a change in the target from `pascal.build`, to `@`.

### Steps to reproduce

1. Create `CNAME` pointing to `@`
2. Apply
3. Plan
4. Observe diff in Plan immediately after Apply

I have also tested pointing to the full name of the root domain instead: `pascal.build`
But it has the exact same diff issue, including the `@`.

### Additional factoids

The plan output can also be observed here:
https://github.com/RedlineTriad/private_server/pull/65#issuecomment-1585818087

In general the whole repo is open source so you can see all the details.

**Comment by jacobbednarz** [comment]
`@` is not available as an alias for the top level domain in the `content`/`value` field. you'll need to use the full value.

**Comment by RedlineTriad** [comment]
I mentioned that I tried the full name as well:
> I have also tested pointing to the full name of the root domain instead: pascal.build
But it has the exact same diff issue, including the @.

**Comment by jacobbednarz** [comment]
the provider doesn't set the `@` alias unless it is provided in the configuration (and only then, it is available as a `name`, not value). if you send it to the API, it may be aliased for you, however, I wouldn't recommend that as it will differ from the user configuration (like here) and you will end up with a permadiff. 

to continue debugging, I would recommend removing the dynamic expressions and coming up with a minimal reproduction case to demonstrate the issue you're seeing without and rule out your setup, variables or the dynamic iteration.

**Comment by RedlineTriad** [comment]
It seems like I forgot to set `var.server_domain_name` to my own domain, so it had the default value of `@`, so thats why it always showed that diff.
But I think `@` doesn't work well with terraform, but works in cloudflare, then it should either be supported completely, or there should be validation that prohibits `@` in CNAME values.

But I guess for my usecase it's working now by always setting a fully qualified value.

**Comment by jacobbednarz** [comment]
glad you found the issue. it's surprising that is the default but 🤷‍♂️

`@` is supported however only for `name` values. supporting it in `value`/`content` is a bit more difficult in the provider given it is used by other provider resources to manage DNS records and subtle differences like trailing periods matter. this isn't the case with the Cloudflare dashboard which only needs to handle it for Cloudflare owned records.
