### ISSUE TITLE
cloudflare_spectrum_application nested syntax for edge_ips "Error: missing expected {"

### ISSUE THREAD

**Issue by andrewkrain** [cloudflare/terraform-provider-cloudflare#2516]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.0
Provider plugins:
- hashicorp/aws v5.2.0
- cloudflare/cloudflare v4.7.1

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
resource "cloudflare_spectrum_application" "endpoint" {
  zone_id      = cloudflare_zone.main.id
  traffic_type = "direct"

  dns {
    type = "ADDRESS"
    name = [redacted]
  }

  edge_ips {
    type = "static"
    ips  = [redacted]
  }
  protocol = "tcp/80"

  origin_dns {
    name = cloudflare_load_balancer.main.name
  }
  origin_port    = [redacted]
  tls            = "off"
  ip_firewall    = false
  proxy_protocol = "v2"
}
```
### Link to debug output

n/a

### Panic output

n/a

### Expected output

Successful `terraform plan` run 

### Actual output

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: missing expected {
│ 
│   with module.nessy.cloudflare_spectrum_application.endpoint,
│   on ../../modules/proxy/main.tf line 147, in resource "cloudflare_spectrum_application" "endpoint":
│  147: resource "cloudflare_spectrum_application" "endpoint" {
│ 
╵

### Steps to reproduce

1. Upgrade Cloudflare provider to v4.x 
2. Update `cloudflare_spectrum_application` to use nested syntax for `edge_ips` per https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/spectrum_application
i.e. replace
```
edge_ips = [redacted]
```
with
```
edge_ips {
    type  = "static"
    ips   = [redacted]
}
```
4. Run `terraform plan`

### Additional factoids

Works fine when
```
edge_ips {
    connectivity = "all"
    type         = "dynamic"
}
```

### References

Introduced in https://github.com/cloudflare/terraform-provider-cloudflare/pull/2219

**Comment by jacobbednarz** [comment]
you'll need to remove the resource from state and reimport it to get the structure correct. there wasn't an automatic migration for this due to the resource previously allowing invalid configurations that we weren't comfortable copying forward or breaking the upgrade path.
