### ISSUE TITLE
Pages projects docs are confusing

### ISSUE THREAD

**Issue by WalshyDev** [cloudflare/terraform-provider-cloudflare#2517]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

N/A

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
# Basic project
resource "cloudflare_pages_project" "basic_project" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
}

# Manage build config
resource "cloudflare_pages_project" "build_config" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
  build_config {
    build_command       = "npm run build"
    destination_dir     = "build"
    root_dir            = ""
    web_analytics_tag   = "cee1c73f6e4743d0b5e6bb1a0bcaabcc"
    web_analytics_token = "021e1057c18547eca7b79f2516f06o7x"
  }
}

# Manage project source
resource "cloudflare_pages_project" "source_config" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
  source {
    type = "github"
    config {
      owner                         = "cloudflare"
      repo_name                     = "ninjakittens"
      production_branch             = "main"
      pr_comments_enabled           = true
      deployments_enabled           = true
      production_deployment_enabled = true
      preview_deployment_setting    = "custom"
      preview_branch_includes       = ["dev", "preview"]
      preview_branch_excludes       = ["main", "prod"]
    }
  }
}

# Manage deployment configs
resource "cloudflare_pages_project" "deployment_configs" {
  account_id        = "f037e56e89293a057740de681ac9abbe"
  name              = "this-is-my-project-01"
  production_branch = "main"
  deployment_configs {
    preview {
      environment_variables = {
        ENVIRONMENT = "preview"
      }
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["preview_flag"]
    }
    production {
      environment_variables = {
        ENVIRONMENT = "production"
        OTHER_VALUE = "other value"
      }
      compatibility_date  = "2022-08-16"
      compatibility_flags = ["production_flag", "second flag"]
    }
  }
}
```

### Link to debug output

N/A

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

N/A

### Additional factoids

The docs for [Pages projects](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/pages_project.md) are quite confusing. It looks like you need to use a bunch of different project blocks in order to fully manage the project. Obviously, this isn't how Terraform works but for people not super experienced, it's definitely confusing.

I intend to add some proper dev docs on this soon but still, we should update this to be easier to understand (since this is shown on the Terraform provider page - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_project)

### References

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/pages_project.md
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_project
User hitting this recently: https://discord.com/channels/595317990191398933/789155108529111069/1117920700737527919

---

Also not super related but a template for docs issues would be nice :)

**Comment by kdpuvvadi** [comment]
And there is no way to enable analytics from terraform. Enabling from UI and garbing those keys with refresh is not the way terraform should work. 

Or do i generate random number and add those? documentation very sparse or don't exist with this. Even the API documentation is very confusing with this.
