### ISSUE TITLE
cloudflare_teams_rule with empty `rule_settings` crashes provider

### ISSUE THREAD

**Issue by xarses** [cloudflare/terraform-provider-cloudflare#2518]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

% terraform -v      
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/hashicorp/aws v4.20.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

% terraform -v
Terraform v1.3.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.7.1
+ provider registry.terraform.io/hashicorp/aws v4.20.1

Your version of Terraform is out of date! The latest version
is 1.5.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

cloudflare_teams_rule

### Terraform configuration files

```hcl
locals {
  fqdn        = "" 
  account_id  = ""
  precendence = 2600
  cidr_blocks = ["10.255.255.0/24"]

  saml_group_name = ""
}

resource "cloudflare_teams_rule" "rule" {

  name        = local.fqdn
  enabled     = true
  account_id  = local.account_id
  description = "Routes for ${local.fqdn}"
  action      = "allow"
  filters     = ["l4"]
  precedence  = local.precendence
  traffic     = "net.dst.ip in {${join(" ", local.cidr_blocks)}}"
  identity    = "any(identity.saml_attributes[*] == \"groups=${local.saml_group_name}\")"
  rule_settings { # https://github.com/cloudflare/terraform-provider-cloudflare/issues/2085
  }
}
```

### Link to debug output

https://gist.github.com/xarses/f20979ff191c9fe42c7abce11f9326cd

### Panic output

```
Stack trace from the terraform-provider-cloudflare_v3.35.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.inflateTeamsRuleSettings({0xe2edc0?, 0xc0002ed638?})
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:218 +0xb94
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTeamsRuleCreate({0x1152d48, 0xc0004cb320}, 0x0?, {0xfb81a0?, 0xc000656d80?})
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_teams_rules.go:86 +0xde
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00041fea0, {0x1152d80, 0xc0005a54d0}, 0xd?, {0xfb81a0, 0xc000656d80})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00041fea0, {0x1152d80, 0xc0005a54d0}, 0xc0000b9520, 0xc000532480, {0xfb81a0, 0xc000656d80})
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000011290, {0x1152d80?, 0xc0005a52f0?}, 0xc0005925f0)
github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x11583f0?, 0xc000011290?}}, {0x1152d80, 0xc0005a52f0}, 0x0?)
github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc000428de0, 0xc000428e40, {0xc000531d60, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0005426e0, {0x1152d80?, 0xc0005a47b0?}, 0xc00053e2a0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:816 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xf89a80?, 0xc0005426e0}, {0x1152d80, 0xc0005a47b0}, 0xc00053e070, 0x0)
github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004ae3c0, {0x11577b8, 0xc000007a00}, 0xc0000c39e0, 0xc0003184b0, 0x173af40, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0004ae3c0, {0x11577b8, 0xc000007a00}, 0xc0000c39e0, 0x0)
google.golang.org/grpc@v1.51.0/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-cloudflare_v3.35.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected output

resource was created

### Actual output

provider crashed

### Steps to reproduce

trigger the creation of a new cloudflare_teams_rule, with a `rule_settings = {}`

### Additional factoids

This does not occur when the empty `rule_settings` is not present, however this is necessary to squelch the drift seen #2085

This also doe not occur if the object is more built out. the drift identifies 

```hcl
rule_settings {
    add_headers = {}
    block_page_enabled = false
    block_page_reason = ""
    insecure_disable_dnssec_validation = false
    override_host = ""
    override_ips = []
  }
```

if either `block_page_enabled` or `insecure_disable_dnssec_validation` is specified, both the drift and the error do not occur, the other attributes do not stop the behavior.

additionally doesn't occur when comparing state to an existing resource(no-op), I haven't tested actually modifying an existing resource  (changed) works or not

### References

#2085 relates, in that the [proposed work around](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2085#issuecomment-1540505933) causes the problem on create.

There is also a [comment from the same commentor](https://github.com/cloudflare/terraform-provider-cloudflare/issues/2335#issuecomment-1540502278) (off-topic), showing the same issue on 4.5.0

**Comment by jacobbednarz** [comment]
> This does not occur when the empty `rule_settings` is not present, however this is necessary to squelch the drift seen #2085

you should not be doing things like `attribute {}` since that ends up essentially as a null internally; it should be omitted instead. 

as this is an unsupported workaround for an existing bug, i'm going to close this one off in favour of fixing the underlying cause (#2085) that will address the problem here once implemented.

**Comment by xarses** [comment]
While I agree with not wanting any one passing an empty attribute, but I don't think the provider should implode over it.

**Comment by jacobbednarz** [comment]
the provider implodes over it due to the underlying assumption that it cannot be `nil`, when in reality, it can be and it isn't handled as such.
