### ISSUE TITLE
Support for Logpush magic_ids_detections

### ISSUE THREAD

**Issue by ajilty** [cloudflare/terraform-provider-cloudflare#2522]
### Current Terraform and Cloudflare provider version

```bash
Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.7.1
+ provider registry.terraform.io/hashicorp/aws v4.39.0
+ provider registry.terraform.io/hashicorp/vault v3.11.0
```

### Description

Update `cloudflare_logpush_job` to support dataset `magic_ids_detections`

### Use cases

As an Magic IDS customer, I would like to set-up Log Push with Terraform, so I can codify and automate my infrastructure configuration

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_job" "network_analytics_logs" {
  dataset          = "magic_ids_detections"
...
```

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_job#dataset
https://developers.cloudflare.com/logs/reference/log-fields/account/magic_ids_detections/

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
