### ISSUE TITLE
Need a data source for `cloudflare_origin_ca_certificate`

### ISSUE THREAD

**Issue by lra** [cloudflare/terraform-provider-cloudflare#2526]
### Current Terraform and Cloudflare provider version

```
Terraform v1.5.0
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0
```

### Description

Since cloudflare v4.8.0, the `csr` is a required property of the `cloudflare_origin_ca_certificate` resource.
This is preventing us to keep track of our `cloudflare_origin_ca_certificate` with terraform as we don't have the CSR that we used to create those certs, and there is no way to recover them.
In the state, the csr property is set to null and any terraform plan leads to:
```
│ Error: Missing required argument
│ 
│   on ../../modules/seismic-global-service/cloudflare.tf line 259, in resource "cloudflare_origin_ca_certificate" "seismic_origin_server_cert":
│  259: resource "cloudflare_origin_ca_certificate" "seismic_origin_server_cert" {
│ 
│ The argument "csr" is required, but no definition was found.
```

### Use cases

To solve this issue, we would like to see a data source for `cloudflare_origin_ca_certificate` so we can keep track of and reference our `cloudflare_origin_ca_certificate` without having to state the csr. 

### Potential Terraform configuration

```hcl
data "cloudflare_origin_ca_certificate" "example" {
    id = "1234567890"
}
```

### References

The csr requirement was introduced in https://github.com/cloudflare/terraform-provider-cloudflare/pull/2496

**Comment by ruimarinho** [comment]
What I did to workaround this was to generate a dummy CSR and manually import the state so that the provider doesn't complain about a missing one. This kind of breaking change shouldn't make it to a minor release though.

**Comment by LanceSandino** [comment]
We're running into this issue as well.
Adding the CSR forces creating the cert again, which we'd prefer not to do.

We created the cert in the GUI and cloudflare manages the CSR.

**Comment by LanceSandino** [comment]
Still waiting on an update for this.

**Comment by LanceSandino** [comment]
Hi bump... any progress on this?
