### ISSUE TITLE
Feature request: Wildcard and multi-domain support in Cloudflare Access

### ISSUE THREAD

**Issue by vcajes** [cloudflare/terraform-provider-cloudflare#2527]
### Current Terraform and Cloudflare provider version

```
terraform -v
Terraform v1.5.0
on darwin_arm64
```

### Description

Wildcard and multi-domain support in Cloudflare Access (released by Cloudflare in March/2023)

https://blog.cloudflare.com/access-wildcard-and-multi-hostname/

The Cloudflare UI already allows to create multiple domains within a single Cloudflare Access application, but this is not supported yet on Terraform.

### Use cases

- Allow API and Frontend apps behind Cloudflare Access to communicate with each other (as described on your own blog post)

### Potential Terraform configuration

```hcl
resource "cloudflare_access_application" "staging_app" {
  zone_id  = "..."
  name      = "..."
  domain   = "example.com"
  self_hosted_domains = ["api.example.com", "www.example.com"]
  ...
}
```

So just add the new "self_hosted_domains" parameter (array of strings), which is the field that the current Cloudflare UI is sending to your APIs to support multiple domains.

### References

https://blog.cloudflare.com/access-wildcard-and-multi-hostname/

**Comment by jacobbednarz** [comment]
this is already available - see https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#480-14th-june-2023
