### ISSUE TITLE
Can not provision cloudflare_ruleset with http_request_firewall_custom

### ISSUE THREAD

**Issue by ArnArm** [cloudflare/terraform-provider-cloudflare#2531]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

* Terraform v1.4.5
* provider registry.terraform.io/cloudflare/cloudflare v4.7.1

### Affected resource(s)

* cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "example" {
  zone_id     = var.cloudflare_zones["zone"].id
  name        = "Allow X"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

  rules {
    action      = "allow"
    expression  = "(ip.src in {1.1.1.1})"
    enabled     = true
  }
}
```

### Link to debug output

"message": "unknown variant for action: allow"

### Expected output

Firewall created which allows IP to Cloudflare zone

### Actual output

Error: error creating ruleset example

### Steps to reproduce

terraform apply

**Comment by jacobbednarz** [comment]
`allow` is not a valid action - see https://developers.cloudflare.com/ruleset-engine/rules-language/actions/ for what is available.

**Comment by ArnArm** [comment]
@jacobbednarz I am  migrating from deprecated to `cloudflare_filter` and `cloudflare_firewall_rule` to `cloudflare_ruleset` as per 

```
│ Warning: Deprecated Resource
│
│   with cloudflare_filter.allow_gitlab_runner,
│   on main.tf line 264, in resource "cloudflare_filter" "example":
│  264: resource "cloudflare_filter" "example" {
│
│ `cloudflare_filter` resource is in a deprecation phase that will
│ last for one year (May 1st, 2024). During this time period, this
│ resource is still fully supported but you are strongly advised
│ to move to the `cloudflare_ruleset` resource. For more information, see
│ https://developers.cloudflare.com/waf/reference/migration-guides/firewall-rules-to-custom-rules/#relevant-changes-for-terraform-users.
```

Basically right now i have these resources which allows IP address to pass firewall rule. I am trying to create `cloudflare_ruleset` which would do a same thing, but i am kind a lost which phase with which action to use. In current setup action is allow and in ruleset it does not work and there are no examples for such use case.

```
resource "cloudflare_filter" "example" {
  zone_id     = var.cloudflare_zones["zone"].id
  description = "Filter IP"
  expression  = "(ip.src in {${var.ip_address}})"
}

resource "cloudflare_firewall_rule" "example" {
  zone_id     = var.cloudflare_zones["zone"].id
  description = "Allow example"
  filter_id   = cloudflare_filter.example.id
  action      = "allow"
  priority    = 1000
}
```

**Comment by jacobbednarz** [comment]
the migration guide (linked in that output) covers a section on allowing traffic - https://developers.cloudflare.com/waf/reference/migration-guides/firewall-rules-to-custom-rules/#new-skip-action-replacing-both-allow-and-bypass-actions

be sure to check out the entire guide to better understand the new system and how each bit operates within it.
