### ISSUE TITLE
cloudflare_record (Data Source) cannot find any record

### ISSUE THREAD

**Issue by mariusmanea-selfridges** [cloudflare/terraform-provider-cloudflare#2533]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform -v
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0
+ provider registry.terraform.io/hashicorp/null v3.2.1

Your version of Terraform is out of date! The latest version
is 1.5.0. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

data.cloudflare_record

### Terraform configuration files

```hcl
data "cloudflare_record" "example" {
  zone_id  = "0a87c587bd0bd3e868449694dabccf47"
  hostname = "aemcmstacka-dev.npd.selfridges.com"
}
```

### Link to debug output

https://gist.github.com/

### Expected output

it should show the record

### Actual output

terraform plan fails, it says it cannot find the record:

```
│ Error: didn't get any DNS records for hostname: aemcmstacka-dev.npd.selfridges.com
│
│   with data.cloudflare_record.example,
│   on cloudflare-dns.tf line 31, in data "cloudflare_record" "example":
│   31: data "cloudflare_record" "example" {
```

### Steps to reproduce

1. use the data source to try retrieving a record
2. run terraform plan and check the output, notice it complains about failing to find the record

The record exists in that zone, because I can find it using the Cloudflare API:

```
zone_id=0a87c587bd0bd3e868449694dabccf47 zone_name=npd.selfridges.com
	 0e404fd8bb0d0bbfdc502eee2dc6c580 aemcmstacka-dev.npd.selfridges.com CNAME dev-aem-cmstacka-alb-714352668.eu-west-1.elb.amazonaws.com
```

**Comment by ralismark** [comment]
I was having the same issue. It turns out that the `cloudflare_record` data source only looks for `A` records by default. You have a `CNAME` record instead (just as I did), which means you need to pass `type = "CNAME"` to the data source for it to find the record.
