### ISSUE TITLE
R2 custom domain

### ISSUE THREAD

**Issue by FlorianLudwig** [cloudflare/terraform-provider-cloudflare#2537]
### Current Terraform and Cloudflare provider version

terraform: v1.4.6
provider: 4.8.0

### Description

Currently it is not possible to configure public access to a R2 bucket via the terraform provider.

### Use cases

See https://developers.cloudflare.com/r2/buckets/public-buckets/

### Potential Terraform configuration

```hcl
resource "cloudflare_r2_bucket" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "terraform-bucket"
  location   = "enam"

  public_access {
    enabled = true
    custom_domains = ["media.example.org", "media.example.com"]
  }

}
```

**Comment by leonbreedt** [comment]
Switching over to Cloudflare as a result of the Google killing off Google Domains, but the inability to automate this via Terraform is a big bummer, previously my static websites were completely Terraform-managed.

**Comment by mrmason** [comment]
We are trying to import our assets from CF into terraform, and it would be really nice if this would all hook in nicely.

**Comment by michielswaanen** [comment]
Would be cool to have a more advanced version of `cloudflare_r2_bucket`. Now I rely on the AWS resource to setup CORS etc, which isn't very stable when used by other providers.

**Comment by anentropic** [comment]
hmm, this seems a bit half-assed

is there a workaround... e.g. is there a private bucket url or something that I can use with a `Record` resource to manually set up the same thing that the custom domain feature does?

**Comment by c-ameron** [comment]
Hello, is there any update on this? Will these be implemented anytime soon? I was wanting to manage a public bucket (with the additional DNS records). I also found a similar issue on the Cloudflare boards.

https://community.cloudflare.com/t/adding-custom-domains-to-r2-buckets/504805

Thanks

**Comment by wolf-cosmose** [comment]
> is there a workaround

<details>
<summary>there's some undocumented API</summary>

```
POST  /client/v4/accounts/${account_id}/r2/buckets/${bucket}/custom_domains
{
  domain: ${domain}
  zoneId: ${zone_id}
  zoneName: ${zone_name}
}
```

```
PUT /client/v4/accounts/${account_id}/r2/buckets/${bucket}/policy?access=CnamesOnly&cname=${domain}&cname=${otherDomain}&...
```

```
DELETE /client/v4/accounts/${account_id}/r2/buckets/${bucket}/custom_domains/${domain}
```
</details>

but I'm guessing it's undocumented for a reason

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by markbaird** [comment]
@jacobbednarz  I highly disagree with you marking this issue as "completed" just because you are also tracking it in another system now. Especially since you indicate you may not even implement this.

**Comment by jakubadamw** [comment]
@markbaird very bizarre, indeed. So 2007 or something. And certainly not how GitHub issues are intended to be used.

**Comment by humphd** [comment]
I'm surprised that this a) isn't possible; but more so that b) it got removed from public view when people are actively asking for it.  I think it's great that it's being worked on internally; but surely there's a better process than asking people to work with CF support in order to track its progress.

**Comment by 9sako6** [comment]
As @wolf-cosmose mentioned, I managed to set a custom domain by using an undocumented API as a workaround. However, I'm not sure how long this solution will remain functional.

I am a fan of Cloudflare R2, so it would be great if this feature could be officially supported.

In Terraform, I'm using the API as shown below:

```tf
resource "terraform_data" "public_custom_domain" {
  triggers_replace = [
    aws_s3_bucket.public.bucket,
    var.public_bucket_custom_fqdn,
  ]

  input = {
    bucket     = aws_s3_bucket.public.bucket
    token      = var.cloudflare_r2_token
    account_id = var.cloudflare_account_id
    fqdn       = var.public_bucket_custom_fqdn
  }

  provisioner "local-exec" {
    on_failure = fail
    when       = create
    command    = <<-EOT
      curl -X POST \
        -H 'Authorization: Bearer ${var.cloudflare_r2_token}' \
        -d '{"domain":"${var.public_bucket_custom_fqdn}", "zoneId":"${var.cloudflare_zone_id}", "zoneName":"${var.domain}"}' \
        'https://api.cloudflare.com/client/v4/accounts/${var.cloudflare_account_id}/r2/buckets/${aws_s3_bucket.public.bucket}/custom_domains'

      curl -X PUT \
        -H 'Authorization: Bearer ${var.cloudflare_r2_token}' \
        'https://api.cloudflare.com/client/v4/accounts/${var.cloudflare_account_id}/r2/buckets/${aws_s3_bucket.public.bucket}/policy?cname=${var.public_bucket_custom_fqdn}&access=CnamesOnly'
    EOT
  }

  provisioner "local-exec" {
    on_failure = fail
    when       = destroy
    command    = <<-EOT
      curl -X DELETE \
        -H 'Authorization: Bearer ${self.input.token}' \
        'https://api.cloudflare.com/client/v4/accounts/${self.input.account_id}/r2/buckets/${self.input.bucket}/custom_domains/${self.input.fqdn}'

      curl -X PUT \
        -H 'Authorization: Bearer ${self.input.token}' \
        'https://api.cloudflare.com/client/v4/accounts/${self.input.account_id}/r2/buckets/${self.input.bucket}/policy?cname=&access=CnamesOnly'
    EOT
  }
}

```
<img width="1076" alt="screenshot" src="https://github.com/cloudflare/terraform-provider-cloudflare/assets/31821663/c335d5a1-8863-4dcf-881f-7d4fc754e155">

**Comment by kozickikarol** [comment]
@jacobbednarz we are also waiting for this functionality. It blocks us from migrating to R2.

**Comment by anentropic** [comment]
Closing the issue says "this is never happening"

**Comment by SkeLLLa** [comment]
@jacobbednarz any updates?

**Comment by layertwo** [comment]
Running into this as well. This breaks customers from being able to use Terraform to easily launch static websites on R2.
