### ISSUE TITLE
Support for regional_tiered_cache

### ISSUE THREAD

**Issue by guydunton** [cloudflare/terraform-provider-cloudflare#2545]
### Current Terraform and Cloudflare provider version

```
> terraform -v
Terraform v1.5.1
on darwin_amd64
```
Cloudflare provider `4.7.0`

### Description

I'm not sure how to enable [Regional tiered cache](https://blog.cloudflare.com/introducing-regional-tiered-cache/) through Terraform. I have an Argo cache & a TieredCache configured as below:

```hcl
resource "cloudflare_argo" "argo" {
  zone_id        = "ZONE_ID"
  tiered_caching = "on"
  smart_routing  = "on"
}

resource "cloudflare_tiered_cache" "tiered-cache" {
  zone_id    = "ZONE_ID"
  cache_type = "smart"
}
```

From these docs: https://blog.cloudflare.com/introducing-regional-tiered-cache/ I would have thought there would be a resource called `regional_tiered_cache` but I can't find it in the [registry](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/argo)

### Use cases

To enable regional tiered cache through Terraform instead of through the console

### Potential Terraform configuration

```hcl
resource "cloudflare_regional_tiered_cache" "tiered-cache" {
  zone_id        = "ZONE_ID"
}
```

**Comment by Nmishin** [comment]
This issue was resolved here: https://github.com/cloudflare/terraform-provider-cloudflare/pull/2624
