### ISSUE TITLE
Provider crash 

### ISSUE THREAD

**Issue by ILLISIS** [cloudflare/terraform-provider-cloudflare#2548]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

snip@snip-desktop:~/Documents/terraform/Cloudflare$ terraform version
Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected resource(s)

cloudflare_tunnel
cloudflare_tunnel_config

### Terraform configuration files

```hcl
resource "random_id" "tunnel_secret" {
  byte_length = 35
}

resource "cloudflare_tunnel" "tunnel" {
  account_id = var.account_id
  name       = "tunnel_name"
  secret     = random_id.tunnel_secret.b64_std
  config_src = "cloudflare"
}


resource "cloudflare_tunnel_config" "tunnel_config" {
  account_id = var.account_id
  tunnel_id  = cloudflare_tunnel.tunnel.id

  config {
    warp_routing {
      enabled = true
    }
    ingress_rule {
      hostname = "derp.example.com.au"
      service  = "https://192.168.1.1"
      origin_request {
        no_tls_verify = true
        http2_origin  = true
      }
    }
    ingress_rule {
      service = "http_status:404"
    }
  }
}
```

### Link to debug output

https://gist.github.com/ILLISIS/8627808af25d75e5608b87ca1e47070f

### Panic output

╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.8.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb45249]

goroutine 526 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.parseOriginRequest({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:122 +0x49
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTunnelConfigRead({0x11cd028, 0xc000419a10}, 0xc00064ee80, {0x1009900?, 0xc0007889c0})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:233 +0xc58
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003da1c0, {0x11cd060, 0xc000410b40}, 0xd?, {0x1009900, 0xc0007889c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003da1c0, {0x11cd060, 0xc000410b40}, 0xc000a996c0, {0x1009900, 0xc0007889c0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00012f278, {0x11cd060?, 0xc000410330?}, 0xc000412340)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x11d2df0?, 0xc00012f278?}}, {0x11cd060?, 0xc000410330?}, 0xc0004121c0?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:105 +0x242
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc0003d4b10, 0xc0003d4b70, {0xc000466c20, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0000d8820, {0x11cd060?, 0xc000362c00?}, 0xc000b98540)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/tf6server/server.go:746 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xfd9d40?, 0xc0000d8820}, {0x11cd060, 0xc000362c00}, 0xc0001a0000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.15.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:383 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c25a0, {0x11d1d78, 0xc000500ea0}, 0xc000870900, 0xc000465ec0, 0x17d6530, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0000c25a0, {0x11d1d78, 0xc000500ea0}, 0xc000870900, 0x0)
        google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.54.0/server.go:964 +0x28a

Error: The terraform-provider-cloudflare_v4.8.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

Expected an error to be thrown or the configuration to be overwritten or the configuration to be destroyed

### Actual output

See panic output

### Steps to reproduce

1. Deploy a cloudflare tunnel and cloudflare_tunnel_config
2. Create configuration on public host name via webui
3. Run terraform refresh/plan/apply

**Comment by jacobbednarz** [comment]
duplicate #2487
