### ISSUE TITLE
 error creating ruleset WAF Managed rule 

### ISSUE THREAD

**Issue by dpk09** [cloudflare/terraform-provider-cloudflare#2549]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.88.1"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "3.6.0"
    }
  }
}

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "test_overrides" {
  account_id  = XXXX
  name        = "WAF Managed rule  SQL Injections"
  description = " SQL Injection attack"
  kind        = "zone"
  phase       = "http_request_firewall_managed"
  
  rules {
    action = "execute"
    action_parameters {
      id = "XXXXXXX"
      overrides {
        action = "block"
        rules {
          id = "XXXXXXXXX"   // SQLi - String Concatenation
          action = "log"
        }
        rules {
          id = "XXXXX" // SQLi - IS NULL
          action = "log"
        }
        rules {
          id = "XXXXXXXX" // SQLi - MultiLevel Function
          action = "log"
        }
      }   
    }
    expression  = "(http.request.uri.path matches  \"^/example/*\")"
    description = "TEST"
    enabled     = true
  }
}
```

### Link to debug output

 Error: error creating ruleset WAF Managed rule  │  │   with cloudflare_ruleset.test_overrides, │ │ Authentication error (10000)

### Expected output

Cloudflare managed ruleset is created

### Actual output

Failed to create ruleset due to authentication error  HTTP status 403: Authentication error (10000)

### Steps to reproduce

Create a new managed ruleset 
Deploy via Terraform 

### References

We are attempting to migrate the new WAF in cloudflare for our account , and there are two existing WAF override rules that have to be migrated. While creating these overrides in terraform we are encountering authentication issue.

**Comment by dpk09** [comment]
---[ RESPONSE ]--------------------------------------
HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: <don't want to share>
Content-Type: application/json
Date: Mon, 07 Feb 2022 09:48:07 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: <SECRET>
Set-Cookie: <SECRET>
Vary: Accept-Encoding

{
 "success": false,
 "errors": [
  {
   "code": 10000,
   "message": "Authentication error"
  }
 ]
}

-----------------------------------------------------: timestamp=2023-26-06T10:02:07.546Z
│ Error: error creating ruleset WAF Managed rule for SQL Injections
│ 
│   with cloudflare_ruleset.test_overrides,
│   on cloudflare_ruleset.tf line 48, in resource "cloudflare_ruleset" "test_overrides":
│   48: resource "cloudflare_ruleset" "test_overrides" {
│ 
│ Authentication error (10000)

**Comment by jacobbednarz** [comment]
this is not a bug in the provider but invalid or incorrect credentials being used. I suggest you debug and confirm those manually with direct API calls before trying to use the terraform provider to ensure they work for your purpose.

**Comment by dpk09** [comment]
thanks for the inputs, now i encounter "received internal server error response (HTTP 500), please try again later"

can you please help here
