### ISSUE TITLE
Support Magic Transit's Advanced TCP Protections

### ISSUE THREAD

**Issue by gsilvapt** [cloudflare/terraform-provider-cloudflare#2550]
### Current Terraform and Cloudflare provider version

```
terraform -v
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0
```

### Description

Hi all :wave:

It would be greatly appreciated if the "Advanced TCP Protections" for Magic Transit were managed through Cloudflare's Terraform Provider. By the looks of it, it seems this will probably require a new resource type, since [`cloudflare_magic_transit_ruleset`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/magic_firewall_ruleset) does not support these, nor this seems to be a [`cloudflare_ruleset`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset).

Changes on these settings perform calls to these endpoints:

```
<accId>/magic/advanced_tcp_protection
<accId>/magic/advanced_tcp_protection/configs/prefixes
<accId>/magic/advanced_tcp_protection/configs/allowlist
<accId>/magic/advanced_tcp_protection/configs/syn_protection/rules
<accId>/magic/advanced_tcp_protection/configs/tcp_flow_protection/rules
```

The idea is to have these advanced configurations under version control, as well as an audit log for changes of these options, including adding or removing exceptions (through prefixes and allow lists), or even turning syn protections and/or TCP flow protections into different states through code.

Thanks in advance for your help,

### Use cases

As someone managing an account with Magic Transit enabled, I want to run advanced configurations through Terraform for traceability, log of changes and to avoid having some settings manually configured through the UI and others in code.

### Potential Terraform configuration

```hcl
resource "cloudflare_magic_transit_advanced" "example" {
    name = "something"
    syn_flood = {
        rule = [
            {
                description = "something to describe this rule"
                burst_sensitivity = "low/medium/high"
                rate_sensitivity = "low/medium/high"
                action = "off/monitoring/mitigation"
            }
        ]
   }
   tcp_state_protection = {
         rule = [
            {
                description = "something to describe this rule"
                burst_sensitivity = "low/medium/high"
                rate_sensitivity = "low/medium/high"
                action = "off/monitoring/mitigation"
            }
        ]
    }
}
```

### References

https://developers.cloudflare.com/ddos-protection/tcp-protection/

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
