### ISSUE TITLE
Migrate existing WAF Overrides to Managed ruleset

### ISSUE THREAD

**Issue by dpk09** [cloudflare/terraform-provider-cloudflare#2551]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

required_providers {
azurerm = {
source = "hashicorp/azurerm"
version = "2.88.1"
}
cloudflare = {
source = "cloudflare/cloudflare"
version = "3.6.0"
}
}
}

### Affected resource(s)

coludflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "test_overrides" {
  zone_id     = XXXXXXX
  name        = "WAF Managed ruleSQL Injections"
  description = "TEST"
  kind        = "zone"
  phase       = "http_request_firewall_managed"
  
  rules {
    action = "execute"
    action_parameters {
      id = "8XXXXXX5"
      overrides {
        action = "block"
        rules {
          id = "3XXXXe"   // SQLi - String Concatenation
          action = "log"
        }
       
      }   
    }
    expression  = "(http.request.uri.path matches  \"^/UIDL/*\")"
    description = "TEST"
    enabled     = true
  }
}
```

### Link to debug output

received internal server error response (HTTP 500), please try again later

### Panic output

received internal server error response (HTTP 500), please try again later

### Expected output

waf overides created via terraform

### Actual output

received internal server error response (HTTP 500), please try again later

### Steps to reproduce

Create a new managed ruleset
Deploy via Terraform

### Additional factoids

I'm trying to create the WAF overrides before i proceed with WAF managed rule migrations

**Comment by dpk09** [comment]
{
    "result": null,
    "success": false,
    "errors": [
        {
            "message": "this zone uses waf uri overrides - please contact your csm for migration"
        }
    ],
    "messages": null
}

**Comment by jacobbednarz** [comment]
please follow the directions from the error message. this isn't something the provider can address.
