### ISSUE TITLE
cloudflare_workers_kv_namespace with an API token results in "Authentication error"

### ISSUE THREAD

**Issue by abbradar** [cloudflare/terraform-provider-cloudflare#2579]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0

### Affected resource(s)

cloudflare_workers_kv_namespace

### Terraform configuration files

```hcl
# I generate my Terraform configuration with Terranix, so I provide parts of the generated JSON here. It works if named `foo.tf.json` in the Terraform project directory.
{
  "provider": {
    "cloudflare": { 
      "api_token": "${var.cloudflare_api_token}"
    },
  },
  "variable": {
    "cloudflare_api_token": {
      "sensitive": true,
      "type": "string"
    },
  },
  "data": {
    "cloudflare_accounts": {
      "account": {
        "name": "foo@bar.com"
      }
    },
  },
  "resource": {
    "cloudflare_workers_kv_namespace": {
      "foo": {
        "account_id": "${data.cloudflare_accounts.account.id}",
        "title": "foo"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/abbradar/def872bd827b97c94d9e04fc92a61fc9

### Expected output

The resource is created.

### Actual output

╷
│ Error: error creating workers kv namespace: Authentication error (10000)
│ 
│   with cloudflare_workers_kv_namespace.foo,
│   on generated.tf.json line 1642, in resource.cloudflare_workers_kv_namespace.foo:
│ 1642:       }
│ 

### Steps to reproduce

1. Create a Terraform project which creates a Cloudflare KV namespace resource;
2. Try to apply.

### Additional factoids

The same token works when deploying through Wrangler with `wrangler deploy`. Other Cloudflare resources that I manage work normally.

**Comment by jacobbednarz** [comment]
this isn't something we can address in the provider as it is related to auth and the Terraform Provider is just another HTTP client. you'll need to debug why this credential isn't working for the operation you are attempting. my suggestion is to start outside of Terraform by making the API calls and confirming all the IDs and permissions directly.

**Comment by abbradar** [comment]
@jacobbednarz The important thing is that Wrangler works with the same token; that's why I expected this to be a bug as I guessed they use the same API endpoints. Should I try and compare what endpoints they use?

**Comment by jacobbednarz** [comment]
yep - compare the URLs and payloads used.

**Comment by abbradar** [comment]
mitmproxy helped greatly. Turns out it was me using `cloudflare_accounts.foo.id` instead of `cloudflare_accounts.foo.accounts[0].id`. Sorry for the noise :)

**Comment by jacobbednarz** [comment]
there are some notes at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/provider-design.md#plural-data-sources on how we handle single vs plural data sources in this provider in case it helps in the future.
