### ISSUE TITLE
cloudflare_zones data source cannot pass zone_id to cloudflare_healthcheck resource

### ISSUE THREAD

**Issue by AsapHogFtw** [cloudflare/terraform-provider-cloudflare#2581]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/hashicorp/http v3.1.0

### Affected resource(s)

cloudflare/cloudflare
  - cloudflare_healthcheack
  - cloudflare_zones

### Terraform configuration files (in main directory, calling the module)

```hcl
# Resources and data sources inside of the module
module "http_health_check" {
  source                    = "../../modules/cloudflare_healthcheck"
  cloudflare_api_account_id = var.cloudflare_api_account_id
  cloudflare_api_key        = var.cloudflare_api_key
  healthchecks = {
    "${local.check_prefix}-baz-foo-com" = {
      name                  = "${local.check_prefix}-baz-com"
      subdomain             = "baz"
      domain                = "foo.com"
      zone_id               = "123456789123456789123456789123456"
      path                  = "/"
    }
    "${local.check_prefix}foo-bar-com" = {
      name                  = "${local.check_prefix}-foo-bar-com"
      subdomain             = "foo"
      domain                = "bar.com"
      zone_id               = "98765432198765432198765432198765"
      path                  = "/"
    }
  ... more stuff...
}

# The main config in the module
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
    http = {
      source  = "hashicorp/http"
      version = "3.1.0"
    }
  }
  required_version = ">= 1.1.0"
}

provider "cloudflare" {
  email = var.cloudflare_api_account_id
  api_key = var.cloudflare_api_key
}



data "cloudflare_zones" "zones" {
  for_each = var.healthchecks
  filter {
    account_id  = var.cloudflare_api_account_id
    name        = each.value.domain
  }
}

resource "cloudflare_healthcheck" "http_health_check" {
  for_each = var.healthchecks

  name                  = each.value.name
  address               = "${each.value.subdomain}.${each.value.domain}"
  # zone_id               = each.value.zone_id
  zone_id               = data.cloudflare_zones.zones[each.value.name].id
  path                  = each.value.path
  check_regions         = ["ENAM", "WNAM"]
  type                  = "HTTP"
  port                  = 80
  method                = "GET"
  expected_codes        = ["2xx", "3xx"]

  header {
    header = "Host"
    values = ["${each.value.subdomain}.${each.value.domain}"]
  }

  interval              = 60
  timeout               = 15
  consecutive_fails     = 3
  consecutive_successes = 2
}

resource "cloudflare_notification_policy" "email_notification" {
  for_each = var.healthchecks

  account_id  = var.cloudflare_api_account_id
  name        = each.value.name
  description = "Endpoint is unhealthy"
  enabled     = true
  alert_type  = "health_check_status_notification"

  email_integration {
    id = "hoggy@foo.com"
  }
  filters {
    health_check_id = [cloudflare_healthcheck.http_health_check[each.key].id]
    status          = ["Unhealthy"]
  }
}
```

### Link to debug output

https://gist.github.com/AsapHogFtw/b92efbbfe16423d6bface11d50dedeca

### Expected output

I expected for the same thing to happen when the values were hardcoded into the `cloudflare_healthcheck` resource instead of being retrieved dynamically from the `cloudflare_zones` data source like they are in these errors. I expected to just get a bunch of `Created healthcheck`, `Created Notification` messages.

You'll notice there is a line that is commented out in that resource; when it is uncommented and the line which trying to call the `cloudflare_zones` data source is commented out then the module will run the just fine and it will create the cloudflare alerts and notifications. I am not understanding why retrieving this dynamically is making it fail, but hardcoding it in allows it to run.

I did do some testing with taking all of this out of a module to see what the data structure looks like, so I am basically certain that I am calling and indexing it correctly from within the module (is it a module specific issue)?

### Actual output

│ Error: error creating standalone healthcheck: Authentication error (10000)
│ 
│   with module.http_health_check.cloudflare_healthcheck.http_health_check["http-health-check-foo-bar-com"],
│   on ../../modules/cloudflare_healthcheck/main.tf line 30, in resource "cloudflare_healthcheck" "http_health_check":
│   30: resource "cloudflare_healthcheck" "http_health_check" {

Many entries like the above for each of the entries inside of the healthcheck map var.

### Steps to reproduce

Create a `healthchecks` map variable with at least 2 entries in the main directory, similar to how I did in the `Terraform configuration files` section. I know I was instructed not to include `for_each` section but I purposefully left in as I believe that could be a part of the reason why it is not working - that along with the fact that it is being used inside of module, which required some hoop-jumping (including the terraform `required_providers` block inside of the module rather then in the base directory).

You may include the `zone_id = $hardcoded_zone_id` inside of the variable, just as I did in the example (Terraform configuration files section). You can then use it (or not) depending on if you comment out one of these lines and uncomment the other (currently running the failing config with the hardcoded value commented out):

```
resource "cloudflare_healthcheck" "http_health_check" {
  for_each = var.healthchecks

  name                  = each.value.name
  address               = "${each.value.subdomain}.${each.value.domain}"
  # zone_id             = each.value.zone_id
  zone_id               = data.cloudflare_zones.zones[each.value.name].id
```

**Comment by Nmishin** [comment]
Hi @AsapHogFtw, I'm trying to reproduce that issue, and looks like you using data.cloudflare_zones a little bit wrong.

I prepared a config for make it a little bit clearer:
```
data "cloudflare_zones" "example" {
  for_each = var.healthchecks

  filter {
    account_id  = "masked"
    name        = each.value.domain
  }
}

output "zone_id" {
  value = data.cloudflare_zones.example[*]
}
```

Output will be:
```
 + zone_id = [
      + {
          + dev = {
              + filter = [
                  + {
                      + account_id  = "masked"
                      + lookup_type = "exact"
                      + match       = ""
                      + name        = "dev"
                      + paused      = false
                      + status      = ""
                    },
                ]
              + id     = "192956c9490bfb70bf4247376aaf2677"
              + zones  = [
                  + {
                      + id   = "masked"
                      + name = "dev"
                    },
                ]
            }
          + qa  = {
              + filter = [
                  + {
                      + account_id  = "masked"
                      + lookup_type = "exact"
                      + match       = ""
                      + name        = "qa"
                      + paused      = false
                      + status      = ""
                    },
                ]
              + id     = "2c728509f3efe9b7976b9b6b9db220ac"
              + zones  = [
                  + {
                      + id   = "masked"
                      + name = "qa"
                    },
                ]
            }
        },
    ]
```

this means you need to use construction like this for get proper zone id:
`
data.cloudflare_zones.example[each.value.name].zones[0].id
`
and it should be zones[0] because you will have exactly one zone id in that list

**Comment by AsapHogFtw** [comment]
@Nmishin 's above comment was able to get me past the issue. Thank you
