### ISSUE TITLE
Error: The terraform-provider-cloudflare_v4.9.0 plugin crashed issue while doing terraform import cloudflare_ruleset.example zone/<zone_id>/<ruleset_id>

### ISSUE THREAD

**Issue by rajendrapinnamaneni** [cloudflare/terraform-provider-cloudflare#2586]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
Cloudflare v4.9.0

### Affected resource(s)

cloudflare_ruleset.cache_everything

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "cache_everything" {
  zone_id    = [Redacted]
  kind       = "zone"
  name       = "Cache Everything"
  phase      = "http_request_cache_settings"

  rules {
    action      = "set_cache_settings"

    expression  = "[Redacted]"
    description = "Cache Everything"
    enabled     = true

    action_parameters {

      cache = true

      # Seem to need to set these otherwise every execution of the script resets the rule every time you apply it
      automatic_https_rewrites   = false
      bic                        = false
      cookie_fields              = null
      disable_apps               = false
      disable_railgun            = false
      disable_zaraz              = false
      email_obfuscation          = false
      hotlink_protection         = false
      increment                  = 0
      mirage                     = false
      opportunistic_encryption   = false
      origin_error_page_passthru = false
      phases                     = null
      products                   = null
      request_fields             = null
      respect_strong_etags       = false
      response_fields            = null
      rocket_loader              = false
      rules                      = null
      rulesets                   = null
      server_side_excludes       = false
      status_code                = 0
      sxg                        = false

      # browser_ttl {
      #   default = 0
      #   mode = "respect_origin"
      # }
      edge_ttl {
        mode    = "respect_origin"
      }
      serve_stale {
        disable_stale_while_updating = false
      }
    }
  }
}
```
The above code is just reference, which we are using currently and it used to work as expected before. But, the main problem is while importing: terraform import cloudflare_ruleset.example zone/<zone_id>/<ruleset_id> , which we are executing on individual zone id, we are not using any for loop while doing import. Below are the commands which we are using to import cloudflare_ruleset:
```
Below command to get ruleset id: 
curl "https://api.cloudflare.com/client/v4/zones/<zone id>/rulesets/phases/http_request_cache_settings/entrypoint" -H "Authorization: Bearer <token>"

Terraform import:
terraform import cloudflare_ruleset.example zone/<zone_id>/<ruleset_id>

We are getting issue while executing the above command.  
```

### Link to debug output

[terraform_log.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/12172936/terraform_log.log)

Included the entire TF_LOG=DEBUG output in above attached file. 

### Panic output

│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-cloudflare_v4.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b44a0]

goroutine 34 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.toRulesetResourceModel({0x11d91e0, 0xc0005033e0}, {0xe0?, {0xc0001f2380?, 0x0?}}, {0x80?, {0x0?, 0xc0001f2340?}}, {{0xc00056ece0, 0x20}, ...})
        github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:600 +0x3a40
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).Read(0xc000140030, {0x11d91e0, 0xc0005033e0}, {{{{0x11ddc48, 0xc0004efad0}, {0xed39e0, 0xc0004deae0}}, {0x11df268, 0xc0007baaa0}}, 0xc000140048, ...}, ...)
        github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:204 +0x5fb
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001fe160, {0x11d91e0, 0xc0005033e0}, 0xc0005034d0, 0xc0005d1430)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/fwserver/server_readresource.go:101 +0x677
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001fe160, {0x11d91e0?, 0xc000503290?}, 0xc0006ac500)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/proto6server/server_readresource.go:55 +0x41a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc000454b40, 0xc000454ba0, {0xc0000a8e80, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0002c66e0, {0x11d91e0?, 0xc000502360?}, 0xc0001442a0)        
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/tf6server/server.go:749 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xfdf2c0?, 0xc0002c66e0}, {0x11d91e0, 0xc000502360}, 0xc0003b4000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007ae5a0, {0x11ddf98, 0xc0004f6b60}, 0xc0007bcb40, 0xc0004fc5d0, 0x17e9570, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0007ae5a0, {0x11ddf98, 0xc0004f6b60}, 0xc0007bcb40, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-cloudflare_v4.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

cloudflare_ruleset.cache_everything["zone_id"]: Refreshing state... [id=a6787f81343f4f1792d77c39bd972401]
cloudflare_ruleset.cache_everything["zone_id"]: Refreshing state...

### Actual output

│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵

Stack trace from the terraform-provider-cloudflare_v4.9.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b44a0]

goroutine 34 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.toRulesetResourceModel({0x11d91e0, 0xc0005033e0}, {0xe0?, {0xc0001f2380?, 0x0?}}, {0x80?, {0x0?, 0xc0001f2340?}}, {{0xc00056ece0, 0x20}, ...})
        github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:600 +0x3a40
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).Read(0xc000140030, {0x11d91e0, 0xc0005033e0}, {{{{0x11ddc48, 0xc0004efad0}, {0xed39e0, 0xc0004deae0}}, {0x11df268, 0xc0007baaa0}}, 0xc000140048, ...}, ...)
        github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:204 +0x5fb
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc0001fe160, {0x11d91e0, 0xc0005033e0}, 0xc0005034d0, 0xc0005d1430)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/fwserver/server_readresource.go:101 +0x677
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc0001fe160, {0x11d91e0?, 0xc000503290?}, 0xc0006ac500)
        github.com/hashicorp/terraform-plugin-framework@v1.3.1/internal/proto6server/server_readresource.go:55 +0x41a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc000454b40, 0xc000454ba0, {0xc0000a8e80, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ReadResource.go:26 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0002c66e0, {0x11d91e0?, 0xc000502360?}, 0xc0001442a0)        
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/tf6server/server.go:749 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xfdf2c0?, 0xc0002c66e0}, {0x11d91e0, 0xc000502360}, 0xc0003b4000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007ae5a0, {0x11ddf98, 0xc0004f6b60}, 0xc0007bcb40, 0xc0004fc5d0, 0x17e9570, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0007ae5a0, {0x11ddf98, 0xc0004f6b60}, 0xc0007bcb40, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-cloudflare_v4.9.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to reproduce

By using cloudflare provider versions below: v4.8.0, v4.9.0 which are latest. 

### Additional factoids
We are trying import cloudflare resource with terraform import command. Below is the command for reference.
```terraform import cloudflare_ruleset.example zone/<zone_id>/<ruleset_id>```
While executing above command we facing issue with cloudflare terraform provider plugin **as crashed and panic: runtime error:** 

Please resolve or provide your inputs to resolve this issue as soon as possible. 

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1610

**Comment by rajendrapinnamaneni** [comment]
There is a new v4.10.0 of the plugin and tried using that. 
Even resulted as: Error: The terraform-provider-cloudflare_v4.10.0 plugin crashed!

Can you please provide me an update on this issue? Thanks.

**Comment by rajendrapinnamaneni** [comment]
> Thank you for opening this issue and sorry to hear you're hitting issues. Unfortunately, the reproduction case provided contains HCL dynamic expressions. Examples of these are:
> 
> * [Conditionals](https://developer.hashicorp.com/terraform/language/expressions/conditionals)
> * [For loops](https://developer.hashicorp.com/terraform/language/expressions/for)
> * [Dynamic blocks](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks)
> * [Modules](https://developer.hashicorp.com/terraform/language/modules) and module references
> 
> Maintainers don't accept these as reproduction cases since using these constructs and expressions can hold their own logic bugs which are outside of the provider and not able to be diagnosed.
> 
> For maintainers to triage this issue, we recommend providing a minimal reproduction test case that is only contains the impacted resources and can be easily reproduced in an isolated environment. Without providing this, maintainers are limited in what support they can provide.

Actioned and removed the loop.

**Comment by rajendrapinnamaneni** [comment]
> Thank you for reporting this issue! For maintainers to dig into issues it is required that all issues include the entirety of `TF_LOG=DEBUG` output to be provided. The only parts that should be redacted are your user credentials in the `X-Auth-Key`, `X-Auth-Email` and `Authorization` HTTP headers. Details such as zone or account identifiers are not considered sensitive but can be redacted if you are very cautious. This log file provides additional context from Terraform, the provider and the Cloudflare API that helps in debugging issues. Without it, maintainers are very limited in what they can do and may hamper diagnosis efforts.
> 
> This issue has been marked with `triage/needs-information` and is unlikely to receive maintainer attention until the log file is provided making this a complete bug report.

Included the entire TF_LOG=DEBUG output in attached file: terraform_log.log

**Comment by jacobbednarz** [comment]
the resource you are trying to import is invalid - most of those attributes are not related to cache. you should check out the documentation for Rulesets (https://developers.cloudflare.com/ruleset-engine/about/) and then the individual products you instead to use in the rulesets engine (such as cache).

**Comment by rajendrapinnamaneni** [comment]
> the resource you are trying to import is invalid - most of those attributes are not related to cache. you should check out the documentation for Rulesets (https://developers.cloudflare.com/ruleset-engine/about/) and then the individual products you instead to use in the rulesets engine (such as cache).

I did check the above and removed the attributes. Now the changes looks same as code under: Terraform configuration files. But still resulted in same error as: Error: The terraform-provider-cloudflare_v4.10.0 plugin crashed!
