### ISSUE TITLE
cloudflare_list : inconsistent state with invalid value for ip

### ISSUE THREAD

**Issue by Arnall** [cloudflare/terraform-provider-cloudflare#2587]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.8.0

### Affected resource(s)

cloudflare_list

### Terraform configuration files

```hcl
resource "cloudflare_list" "ip_list" {
  account_id  = <account_id>
  description = "test"
  kind        = "ip"
  name        = "test"

  item {
    value {
      ip = "127.0.0.1"
    }
    comment = "1_good"
  }
  item {
    value {
      ip = "127.0.0.257"
    }
    comment = "2_bad"
  }
}
```

### Link to debug output

https://gist.github.com/Arnall/9ee452944a36f2bb1c9714fe42fd45ec

### Expected output

State is consistent with what is in production:

```hcl
# cloudflare_list.ip_list:
resource "cloudflare_list" "ip_list" {
    account_id  = "4165346f7e54d68c8d3b9bb3321aabee"
    description = "test"
    id          = "dbcf0ac0b0aa4b2fb7b7bbcfbe9c499e"
    kind        = "ip"
    name        = "test"

    item {
        comment = "1_good"

        value {
            ip = "127.0.0.1"
        }
    }
    item {
        comment = "2_bad"

        value {
            ip = "127.0.0.2"
        }
    }
}
```

### Actual output

state:

```hcl
# cloudflare_list.ip_list:
resource "cloudflare_list" "ip_list" {
    account_id  = "4165346f7e54d68c8d3b9bb3321aabee"
    description = "test"
    id          = "dbcf0ac0b0aa4b2fb7b7bbcfbe9c499e"
    kind        = "ip"
    name        = "test"

    item {
        comment = "1_good"

        value {
            ip = "127.0.0.1"
        }
    }
    item {
        comment = "2_bad"

        value {
            ip = "127.0.0.257"
        }
    }
}
```

### Steps to reproduce

1. create a list in the interface with good IPs (eg 127.0.0.1, 127.0.0.2)
2. make a `terraform state importe cloudflare_list.ip_list <account_id>/<list_id>` of the list
3. create terraform file like above, with an error in a IP (127.0.0.257)
4. try to apply, you have an error about `filters.api.value is neither a valid IP address or CIDR (10037)`
5. make a `terraform show`, the state is not tainted but the bad IP is now in the state
6. correct the IP in the Terraform file (127.0.0.257 => 127.0.0.2)
7. make a `terraform plan`, it says that there is nothing to change, the bad IP stays in the state.

**Comment by jacobbednarz** [comment]
this is a known situation where you cannot address the individual rules by themselves. in order to update them, you need to remove them and readd them. there is working going on to find a solution however, i do not have an ETA for this to land.
