### ISSUE TITLE
Can't set default browser ttl to 0

### ISSUE THREAD

**Issue by kleinmp** [cloudflare/terraform-provider-cloudflare#2591]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "terraform_managed_resource--http_request_cache_settings" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_cache_settings"
  zone_id = var.cloudflare_zone_id
  rules {
    action = "set_cache_settings"
    action_parameters {
      browser_ttl {
        default = 0
        mode    = "override_origin"
      }
      cache = true
      cache_key {
        custom_key {
          query_string {
            include = ["*"]
          }
        }
      }
      edge_ttl {
        default = 86400
        mode    = "override_origin"
        status_code_ttl {
          status_code = 302
          value       = -1
        }
        status_code_ttl {
          status_code = 307
          value       = -1
        }
      }
    }
    description = "Default Cache"
    enabled     = true
    expression  = "(http.host eq \"test.example.com\")"
  }
  rules {
    action = "set_cache_settings"
    action_parameters {
      cache = false
    }
    description = "No Cache Paths"
    enabled     = true
    expression  = "(starts_with(http.request.uri.path, \"/123/\")) or (starts_with(http.request.uri.path, \"/234/\")) or (starts_with(http.request.uri.path, \"/345/\"))"
  }
}
```

### Link to debug output

https://gist.github.com/kleinmp/6f9af873c760e687bc717ad218a99b03

### Expected output

The configuration is expected to be valid when default value is 0 for browser ttl on a cache rule.

### Actual output

│ Error: invalid configuration
│ 
│   with cloudflare_ruleset.terraform_managed_resource--http_request_cache_settings,
│   on main.tf line 42, in resource "cloudflare_ruleset" "terraform_managed_resource--http_request_cache_settings":
│   42:       browser_ttl {
│ 
│ using mode 'override_origin' requires setting a default for ttl
╵
╷
│ Error: Invalid Attribute Value
│ 
│   with cloudflare_ruleset.terraform_managed_resource--http_request_cache_settings,
│   on main.tf line 43, in resource "cloudflare_ruleset" "terraform_managed_resource--http_request_cache_settings":
│   43:         default = 0
│ 
│ Attribute rules[0].action_parameters[0].browser_ttl[0].default value must be at least 1, got: 0

### Steps to reproduce

- Create a cache rule that overrides browser ttl and set the default to 0 ('No cache').
- Run `terraform plan`
- You'll see an error indicating the default can't be 0 but it is allowed in the interface.

### Additional factoids

If you create a cache rule in the interface with browser ttl set to 'No cache' and then generate the config using `cf-terraforming` then the default value will be 0 but you can't apply it back without changing to at least 1.

**Comment by iveelsm** [comment]
Browser TTL cannot be set to `0` for legacy reasons. A Browser TTL of `0` actually translates to "Respect Origin" instead of a `no-cache`/`no-store` like users may expect. The underlying issue is actively being worked on and should be hitting the provider and cf-terraforming soon.

**Comment by Assylbek2002** [comment]
@iveelsm I apologize for this, but is there an approximate time frame for when this problem will be resolved?

**Comment by iveelsm** [comment]
Looks like it is marked for v4.15.0: https://github.com/cloudflare/terraform-provider-cloudflare/pull/2756
