### ISSUE TITLE
Export the domain of the Cloudflare Pages project for use in cloudflare_record

### ISSUE THREAD

**Issue by dvasdekis** [cloudflare/terraform-provider-cloudflare#2596]
### Current Terraform and Cloudflare provider version

Terraform v1.5.1
on windows_amd64
+ provider registry.terraform.io/auth0/auth0 v0.45.0
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/cyrilgdn/postgresql v1.19.0
+ provider registry.terraform.io/hashicorp/aws v4.61.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Description

As per the description at the top of [cloudflare_pages_domain](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_domain), "A DNS record for the domain is not automatically created. You need to create a cloudflare_record resource for the domain you want to use.", I am trying to create the cloudflare_record in Terraform. However, there's no way to do this automatically without knowing the target domain for the CNAME record, as per below:
<img width="555" alt="image" src="https://github.com/cloudflare/terraform-provider-cloudflare/assets/19279397/c3e10c61-29d0-4860-b14f-474b5a6a0baf">

If `cloudflare_pages_project` exported the target domain as an output, I could then create a cloudflare record based on the domain, like the below example.

I can't go end-to-end on provisioning a pages site with Cloudflare until cloudflare_pages_project reports the domain that the pages site was automatically given (the CNAME record target).

### Use cases

Deploying a Pages site via Terraform including management of the DNS records for that domain.

Currently, we can't manage the DNS CNAME records of a domain with Terraform, as we do not know the site name in advance. It is sometimes, but not always, equal to "${cloudflare_pages_project.name}.pages.dev"

### Potential Terraform configuration

```hcl
data "cloudflare_zone" "site-zone" {
  name       = local.cloudflare_site_project_domain
  account_id = var.CLOUDFLARE_ACCOUNT_ID
}

resource "cloudflare_pages_domain" "site-domain" {
  account_id   = var.CLOUDFLARE_ACCOUNT_ID
  project_name = "${local.cloudflare_site_project_name}-${terraform.workspace}"
  domain       = terraform.workspace == "prd" ? "www.${local.cloudflare_site_project_domain}" : "${terraform.workspace}.${local.cloudflare_site_project_domain}"
}

# We deploy to the below with the cloudflare pages github action
resource "cloudflare_pages_project" "site-frontend" {
  account_id        = var.CLOUDFLARE_ACCOUNT_ID
  name              = "${local.cloudflare_site_project_name}-${terraform.workspace}"
  production_branch = "main"
}

# The below is impossible for now:
resource "cloudflare_record" "site-record" {
  zone_id = data.cloudflare_zone.site-zone.id
  name    = terraform.workspace == "prd" ? "@" : terraform.workspace
  type    = "CNAME"
  # The below doesn't exist as an output yet
  value   = cloudflare_pages_project.site-frontend.pages_domain
  ttl     = 1
}
```

**Comment by Cyb3r-Jak3** [comment]
There is the [subdomain attribute](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/pages_project#subdomain), which is the `pages.dev` domain. Is that what you are looking for?

**Comment by jacobbednarz** [comment]
using `subdomain` is the recommended approach here which is the CNAME value of the project.

**Comment by uceumice** [comment]
How about renaming `subdomain` to `domain`. Why does it have to be confusing `:|` ?

Assuming, I only get the subdomain part of the project, leads to following consequences:

![Screenshot 2023-08-08 021418](https://github.com/cloudflare/terraform-provider-cloudflare/assets/65486851/cfe972ff-4bf9-4bfb-a76e-bf0d5398bbfe)
 
![Screenshot 2023-08-08 021431](https://github.com/cloudflare/terraform-provider-cloudflare/assets/65486851/3f970c05-0d57-4e45-b68a-4b04fc1c5caf)

P.S.: *Not a big deal, but annoying...*
