### ISSUE TITLE
Error: "email" is not set correctly appears out of nowhere

### ISSUE THREAD

**Issue by reschex** [cloudflare/terraform-provider-cloudflare#2599]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.2
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/hashicorp/azurerm v3.64.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

### Affected resource(s)

- provider
- data "cloudflare_zone"
- resource "cloudflare_record"

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = ">=4.9.0"
    }
  }
}

provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

variable "cloudflare_api_token" {
  type        = string
  description = "For DNS records."
  default     = "TOKEN"
}

data "cloudflare_zone" "this" {
  name = "example.com"
}

resource "cloudflare_record" "this" {
  zone_id = data.cloudflare_zone.this.id
  name    = "test.example.com"
  value   = "debug.example.com"
  type    = "CNAME"
  proxied = false
}
```

### Link to debug output

https://gist.github.com/reschex/4787ba868b908a73b305f665e57c581b

### Expected output

terraform plan/apply to work - and it did to start with. 

### Actual output

│ Error: "email" is not set correctly
│
│   with provider["registry.terraform.io/cloudflare/cloudflare"],
│   on main.tf line 26, in provider "cloudflare":
│   26: provider "cloudflare" {
│

### Steps to reproduce

apply above terraform config

### Additional factoids

This used to work quite happily even a day ago or so.

It just randomly started failing today and I can still reproduce it now with a clean terraform workspace and basic resource config as above.

**Comment by jacobbednarz** [comment]
this validation has always existed when the `api_key` or `CLOUDFLARE_API_KEY` is set. I recommend auditing your environment to see why/when this was set.

**Comment by reschex** [comment]
> this validation has always existed when the `api_key` or `CLOUDFLARE_API_KEY` is set. I recommend auditing your environment to see why/when this was set.

I created a new module, in a clean workspace, using the `api_token` - getting the same error. I've always used `api_token`.

**Comment by reschex** [comment]
> > this validation has always existed when the `api_key` or `CLOUDFLARE_API_KEY` is set. I recommend auditing your environment to see why/when this was set.
> 
> I created a new module, in a clean workspace, using the `api_token` - getting the same error. I've always used `api_token`.

Ignore me - someone has created a new variable in a linked variable group in azure devops which ultimately translated to `CLOUDFLARE_API_KEY` 🤦‍♂️

**Comment by johnpitchko** [comment]
FWIW, I ran into this error setting an incorrect env var. I set `CLOUDFLARE_API_KEY` when I should have set `CLOUDFLARE_API_TOKEN`. 

Commenting for clarity in case anyone else encounters this issue.
