### ISSUE TITLE
Add support for `disable_clipboard_redirection` under `BisoAdminControls`

### ISSUE THREAD

**Issue by ruimarinho** [cloudflare/terraform-provider-cloudflare#2600]
### Current Terraform and Cloudflare provider version

```
❯ terraform -v
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.9.0
+ provider registry.terraform.io/hashicorp/http v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/vault v3.12.0
```

### Description

Zero Trust supports `disable_clipboard_redirection` but the provider does not support [this option](https://github.com/cloudflare/terraform-provider-cloudflare/blob/05718d8fa7610464f69d7db338612aa5dfe11778/internal/sdkv2provider/schema_cloudflare_teams_rules.go#L253-L279) at the moment.

It seems like the `dcr` field has not made its way to the [public API yet](https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule), so it might require an upstream change first.

### Use cases

Configuring all available isolation policies via terraform.

### Potential Terraform configuration

```hcl
resource "cloudflare_teams_rule" "isolate_foobar_access" {
  name        = "Isolate Foobar Access"
  account_id  = 123
  description = ""
  precedence  = 1
  enabled     = true
  action      = "isolate"
  filters     = ["http"]
  identity    = "any(identity.groups.name[*] in {\"foobar\"})"
  traffic     = "http.request.host in {\"foo.example.com\"}"

  rule_settings {
    add_headers                        = {}
    block_page_enabled                 = false
    insecure_disable_dnssec_validation = false
    override_ips                       = []

    biso_admin_controls{
      disable_printing = true
      disable_copy_paste = true
      disable_download = true
      disable_upload = true
      disable_keyboard = false
      disable_clipboard_redirection = false
    }

    check_session {
      duration = "0s"
      enforce  = false
    }
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
