### ISSUE TITLE
Panic and crash on specific pages project deployment

### ISSUE THREAD

**Issue by dvasdekis** [cloudflare/terraform-provider-cloudflare#2603]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.1
on windows_amd64

provider registry.terraform.io/auth0/auth0 v0.45.0
provider registry.terraform.io/cloudflare/cloudflare v4.9.0
provider registry.terraform.io/cyrilgdn/postgresql v1.19.0
provider registry.terraform.io/hashicorp/aws v4.61.0
provider registry.terraform.io/hashicorp/random v3.4.3

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
data "cloudflare_zone" "site-zone" {
  name       = mywebsite.com
  account_id = var.CLOUDFLARE_ACCOUNT_ID
}

resource "cloudflare_pages_project" "site-frontend" {
  account_id        = var.CLOUDFLARE_ACCOUNT_ID
  name              = "place-${terraform.workspace}"
  production_branch = "main"
  build_config {
    build_command   = "yarn build"
    root_dir        = "frontend_site"
    destination_dir = "build"
    # web_analytics_tag   = ""
    # web_analytics_token = ""
  }
  # Define environment variables for the preview and production environments
  deployment_configs {
    preview {
      environment_variables = {
        NODE_VERSION = "16.16"
      }
      sitement {}
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["preview_flag"]
    }
    production {
      environment_variables = {
        # Set the version of software to use for the production environment
        NODE_VERSION = "16.16"
      }
      sitement {}
      compatibility_date  = "2022-08-15"
      compatibility_flags = ["production_flag"]
    }
  }
}
```

### Link to debug output

https://gist.github.com/dvasdekis/84cbc6f13690ff21b6b0f8137dad9cce

### Expected output

Terraform apply succeeded

### Actual output

Stack trace from the terraform-provider-cloudflare_v4.9.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 39 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildDeploymentConfig({0xed42e0?, 0xc000439ec0})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:129 +0x1188
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildPagesProject(_)
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:286 +0x64e
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflarePagesProjectCreate({0x11d91a8, 0xc0004390e0}, 0x0?, {0x1013780?, 0xc00053bd90?})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_pages_project.go:359 +0xd9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000391ce0, {0x11d91e0, 0xc000496f30}, 0xd?, {0x1013780, 0xc00053bd90})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:707 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000391ce0, {0x11d91e0, 0xc000496f30}, 0xc000a9f860, 0xc000666880, {0x1013780, 0xc00053bd90})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000011308, {0x11d91e0?, 0xc000496a20?}, 0xc000ab0460)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0x11df010?, 0xc000011308?}}, {0x11d91e0, 0xc000496a20}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf5to6server/tf5to6server.go:34 +0x5a
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0xc0003c0b40, 0xc0003c0ba0, {0xc00046c760, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.10.0/tf6muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0000ac780, {0x11d91e0?, 0xc00048cf00?}, 0xc000186770)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/tf6server/server.go:819 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xfdf2c0?, 0xc0000ac780}, {0x11d91e0, 0xc00048cf00}, 0xc0001abf80, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004fe5a0, {0x11ddf98, 0xc000580340}, 0xc000aac6c0, 0xc00041d530, 0x17e95a0, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0004fe5a0, {0x11ddf98, 0xc000580340}, 0xc000aac6c0, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-cloudflare_v4.9.0 plugin crashed!

### Steps to reproduce

1. run terraform apply

### Additional factoids

cloudflare_pages_project works fine within this project for a different 'page resource', so I don't know why this one specifically crashes. If you need to dig into the internal Cloudflare logs, the pages site is called 'place-tst' (but I can't see anything about it in the Cloudflare UI).

### References

I closed this old one as this is a cleaner example: https://github.com/cloudflare/terraform-provider-cloudflare/issues/2597

**Comment by jacobbednarz** [comment]
`sitement` is not a valid key for deployment configs. have you tried it with *only* valid keys?

**Comment by dvasdekis** [comment]
Thanks @jacobbednarz - if `sitement {}` isn't a valid key, then the driver should reject it. As it is, I added it based on Terraform output to stop Terraform trying to change the resource. 

I will try it again after removing `sitement {}` shortly.

**Comment by jacobbednarz** [comment]
the provider won't reject it as the `TypeMap` has little to no ability to do additional validation on attributes using Terraform core. the underlying library also uses a `map[string]string` which this matches the interface here. it's an unfortuate but necessary use here at the moment.
