### ISSUE TITLE
cloudflare_ruleset resource doesn't create firewall rule

### ISSUE THREAD

**Issue by m4t22** [cloudflare/terraform-provider-cloudflare#2617]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform 1.3.4
provider v4.10.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "block_ips" {
  zone_id     = var.cloudflare_zone_id
  name        = "blocking_rule"
  description = "Block api access"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

  rules {
    action = "block"
    expression  = "(http.host contains \"api.example\")"
    description = "Limit IPs api access"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/m4t22/9cc011dd1eda0f76aa2541e3c6b439ce

### Expected output

Output looks good but there is no firewall rule in the UI as while using `cloudflare_filter` and `cloudflare_firewall_rule` resources.

### Actual output

Firewall rule is visible in UI.

### Steps to reproduce

1. Apply code for `cloudflare_ruleset` resource.
2. Inspect CloudFlare UI: `Security > WAF`

### Additional factoids

I've followed this guide: https://developers.cloudflare.com/terraform/additional-configurations/waf-custom-rules/#zone-level-configurations
Ruleset is visible via https://api.cloudflare.com/client/v4/zones/<zone_id>/rulesets, but not in UI

**Comment by jacobbednarz** [comment]
for some kind/phase combinations, they are not visible in the UI (today) and you must confirm them working either with WAF analytics or the API.

**Comment by m4t22** [comment]
@jacobbednarz would it be possible to get a list of supported (visible) kind/phase combination?
It is about the features' parity - I've used cloudflare_ruleset as I've seen following note: 
![Screenshot 2023-07-18 at 16 31 37](https://github.com/cloudflare/terraform-provider-cloudflare/assets/44002313/990336c1-1d30-4719-88ff-5698d2150683)
So I wanted to use recommended resources and because of `cloudflare_ruleset` did not create rules in the UI, I had to fallback to resources scheduled for deprecation: `cloudflare_filter` and `cloudflare_firewall_rule` as using these I was able to get the rule in the UI.

**Comment by jacobbednarz** [comment]
i don't have them; you will need to reach out to support/your account team.
