### ISSUE TITLE
Spectrum Example configuration is invalid

### ISSUE THREAD

**Issue by witanred** [cloudflare/terraform-provider-cloudflare#2621]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
rj@C02FTAWRMD6R terraform % terraform -v
Terraform v1.5.3
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.5.0
```

### Affected resource(s)

cloudflare_spectrum_application

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "4.5.0"
    }
  }
}

provider "cloudflare" {
  email = "..."
  api_key = "..."
}

variable "zone_id" {
  default = "86cb..."
}

variable "account_id" {
  default = "e745..."
}

variable "domain" {
  default = "tf.ross.gg"
}


# This is from https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/spectrum_application#nestedblock--origin_dns
resource "cloudflare_spectrum_application" "spectrum" {
  zone_id      = var.zone_id
  protocol     = "tcp/22"
  traffic_type = "direct"

  dns {
    type = "CNAME"
    name = "ssh.example.com"
  }

  origin_direct = [
    "tcp://192.0.2.1:22"
  ]

  edge_ips {
    type = "static"
    ips  = ["203.0.113.1", "203.0.113.2"]
  }
}
```

### Link to debug output

See panic output below

### Panic output

# When using `origin_direct = ["tcp://192.0.2.1:22"]`, we get this output because it is in the documentation reserved range
cloudflare_spectrum_application.spectrum: Creating...
╷
│ Error: error creating spectrum application for zone: One or more of the origin addresses are invalid. (11002)
│
│   with cloudflare_spectrum_application.spectrum,
│   on cloudflare.tf line 46, in resource "cloudflare_spectrum_application" "spectrum":
│   46: resource "cloudflare_spectrum_application" "spectrum" {
│
╵

# When using these edge_ips as above BYOIP, we get an error

cloudflare_spectrum_application.spectrum: Creating...
╷
│ Error: error creating spectrum application for zone: The edge_ips configuration provided has an invalid type. (11024)
│
│   with cloudflare_spectrum_application.spectrum,
│   on cloudflare.tf line 46, in resource "cloudflare_spectrum_application" "spectrum":
│   46: resource "cloudflare_spectrum_application" "spectrum" {
│
╵

### Expected output

NA

### Actual output

NA

### Steps to reproduce

Use the config as above with a DNS CNAME record that is appropriate for your zone.

### Additional factoids

I recommend changing the example to this, so that creation runs with only dns > name change.

```
resource "cloudflare_spectrum_application" "spectrum" {
  zone_id      = var.zone_id
  protocol     = "tcp/22"
  traffic_type = "direct"

  dns {
    type = "CNAME"
    name = "ssh.example.com"
  }

  origin_direct = [
    "tcp://2.2.2.2:22"
  ]

  edge_ips {
    type = "dynamic"
    connectivity = "all"
  }
}
```

Creating this in lieu of an engineering ticket. Feel free to reach out internally if you have any questions. 

### References

Source document: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/spectrum_application#nestedblock--origin_dns

**Comment by witanred** [comment]
I have recreated these broken configurations and can confirm that using `TF_LOG=DEBUG` does not change the log output.

**Comment by jacobbednarz** [comment]
we use rfc5737/rfc3849 IP ranges for our documentation and are intentionally not copy pastable (much like zone and account tags in our examples).
