### ISSUE TITLE
Docs for cloudflare_list "item" block are wrong, missing the "content" keyword

### ISSUE THREAD

**Issue by krupnikola** [cloudflare/terraform-provider-cloudflare#2633]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.10.0
```

### Affected resource(s)

cloudflare_list

### Terraform configuration files

```hcl
# as per official latest documentation for the resource

resource "cloudflare_list" "ip" {
  name        = var.name
  account_id  = var.account_id
  description = var.description
  kind        = "ip"

  item {
    value {
      ip = "192.0.2.0"
    }
    comment = "one"
  }
}
```

### Link to debug output

https://gist.github.com/

### Expected output

IP list gets created

### Actual output

```
│ Error: Unsupported block type
│
│   on ../.modules/ip_lists/main.tf line 9, in resource "cloudflare_list" "ip":
│    9:       value {
│
│ Blocks of type "value" are not expected here.
```

### Steps to reproduce

Try creating the cloudflare IP list as described in official latest documentation

<img width="1392" alt="Screenshot 2023-07-26 at 10 59 22" src="https://github.com/cloudflare/terraform-provider-cloudflare/assets/38564674/2a20fa31-528c-4ecb-9302-8fa4cba90f61">

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/list

### Additional factoids

The wrong lines seems to be here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/list.md?plain=1#L33-L39

And it should probably be 

```
  item {
      content {
        value {
          ip = "192.0.2.0"
        }
        comment = "one"
    }
  }
 ```

**Comment by jacobbednarz** [comment]
the document (and test suite) is correct. I recommend you try this without using a module to confirm the behaviour.
