### ISSUE TITLE
Access Groups support for OIDC claims

### ISSUE THREAD

**Issue by Koch** [cloudflare/terraform-provider-cloudflare#2645]
### Current Terraform and Cloudflare provider version

Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0

### Description

Support for OIDC claims in resource cloudflare_access_group. Currently, it supports just about every other method with the exception of OIDC claims.

### Use cases

It's useful to be able to use OIDC claims in access groups where required, and be able to do it using Terraform.

### Potential Terraform configuration

```hcl
resource "cloudflare_access_group" "group" {
  account_id = var.cloudflare_account_id
  name       = "application access"

  include {
    oidc_claim {
      name = "oidc claim name"
      value = "oidc claim name"
    }
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
