### ISSUE TITLE
cloudflare_access_group "require" is not expected here

### ISSUE THREAD

**Issue by verenion** [cloudflare/terraform-provider-cloudflare#2653]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform -v
Terraform v1.5.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.11.0
+ provider registry.terraform.io/digitalocean/digitalocean v2.29.0
+ provider registry.terraform.io/gavinbunney/kubectl v1.14.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/helm v2.10.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.22.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/krystal/katapult v0.0.10
+ provider registry.terraform.io/rancher/rancher2 v1.25.0
+ provider registry.terraform.io/rickardgranberg/vaultoperator v0.1.8

### Affected resource(s)

cloudflare_access_group

### Terraform configuration files

```hcl
resource "cloudflare_access_group" "example" {
  account_id = "xxx"
  name       = "staging group"

  include {
    email = ["test@example.com"]
  }

  require = {
    ip = ["1.1.1.1"]
  }
}
```

### Link to debug output

https://gist.github.com/verenion/febe6b7d784eba102f05a5bcbd989a60

### Expected output

For the group to be created, as per the documentation:

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#nested-schema-for-require

```
# Allowing `test@example.com` to access but only when coming from a
# specific IP.
resource "cloudflare_access_group" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "staging group"

  include {
    email = ["test@example.com"]
  }

  require = {
    ip = [var.office_ip]
  }
}
```

### Actual output

I get an unsupported argument error:

```
│ Error: Unsupported argument
│ 
│   on cloudflare-tunnel.tf line 35, in resource "cloudflare_access_group" "example":
│   35:   require = {
│ 
│ An argument named "require" is not expected here. Did you mean to define a block of
│ type "require"?

```

### Steps to reproduce

1. Create a cloudflare_access_group resource with both include and require arguments.
2. Error

**Comment by jacobbednarz** [comment]
`require` is a block, not an attribute so it should be `require {}` (no equals sign).

feel free to submit a PR fixing this documentation example 😄 (https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/registry-documentation.md).
