### ISSUE TITLE
Error: The terraform-provider-cloudflare_v4.11.0 plugin crashed! on [cloudflare_tunnel_config]

### ISSUE THREAD

**Issue by joaocc** [cloudflare/terraform-provider-cloudflare#2655]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform 1.5.4, arm64
cloudflare provider v4.11.0

### Affected resource(s)

cloudflare_tunnel_config

### Terraform configuration files

```hcl
# cloudflare_tunnel_config.this["all"] will be created
  + resource "cloudflare_tunnel_config" "this" {
      + account_id = "000000000"
      + id         = (known after apply)
      + tunnel_id  = "12345678-0000-0000-0000-000000000000"

      + config {
          + ingress_rule {
              + hostname = "*.some.domain.athere.net"
              + service  = "http://nginx-controller.myns.svc.cluster.local:80"
            }
          + warp_routing {}
        }
    }
```

### Link to debug output

N/A

### Panic output

│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v4.11.0 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 40 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.buildTunnelConfig(0x40000167e8?)
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:163 +0x5c4
github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider.resourceCloudflareTunnelConfigUpdate({0xcd32c8, 0x400014cb10}, 0x0?, {0xb0c240?, 0x40003108f0?})
        github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider/resource_cloudflare_tunnel_config.go:261 +0xc4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x4000448380, {0xcd3300, 0x4000527ad0}, 0xd?, {0xb0c240, 0x40003108f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x4000448380, {0xcd3300, 0x4000527ad0}, 0x4000451ba0, 0x4000362d80, {0xb0c240, 0x40003108f0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0x874
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x400019d2a8, {0xcd3300?, 0x40005278c0?}, 0x40002b6aa0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xb5c
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ApplyResourceChange({{0xcd9148?, 0x400019d2a8?}}, {0xcd3300, 0x40005278c0}, 0x0?)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf5to6server/tf5to6server.go:37 +0x58
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ApplyResourceChange({0x4000440c60, 0x4000590280, 0x4000440c90, 0x4000440cc0, {0x4000408840, 0x2, 0x2}}, {0xcd3300?, 0x4000527410?}, 0x40002b6a00)
        github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ApplyResourceChange.go:30 +0x100
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x40002b39a0, {0xcd3300?, 0x40005262d0?}, 0x4000208230)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:819 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xad6640?, 0x40002b39a0}, {0xcd3300, 0x40005262d0}, 0x4000208070, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:422 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x40002ee1e0, {0xcd8058, 0x4000003520}, 0x40006d8120, 0x40004f4ae0, 0x12e3480, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1337 +0xc28
google.golang.org/grpc.(*Server).handleStream(0x40002ee1e0, {0xcd8058, 0x4000003520}, 0x40006d8120, 0x0)
        google.golang.org/grpc@v1.56.1/server.go:1714 +0x80c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.1/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.1/server.go:957 +0x164

Error: The terraform-provider-cloudflare_v4.11.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

Should work without crashing

### Actual output

see above for panic crash

### Steps to reproduce

Nothing in particular
The same setup (quite large environment) is able to create tunnels

**Comment by joaocc** [comment]
Hi. 
Will provide the low.
However, it would be better if you guys could change the message.
The log redactor IS NOT SAFE!
Things like tunnel secrets and tokens are NOT removed from dumps of the state elements, nor are other secrets that may end up being in resources (such as secret keys to state storage, together with the URLs where they can be found).

Is there any way to send the logs in a private manner?
Thanks

**Comment by Cyb3r-Jak3** [comment]
@joaocc can you try without `warp_routing {}` as a part

**Comment by joaocc** [comment]
Hi. I can confirm that either adding the block with content to disable, or omitting the block solved the issue. Thanks!
