### ISSUE TITLE
Error: Provider produced inconsistent result after apply on `cloudflare_ruleset` resource

### ISSUE THREAD

**Issue by rayterrill** [cloudflare/terraform-provider-cloudflare#2656]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.11.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "stripsensitiveheaders" {
  zone_id     = "9f3e578c937470181bbdf0162742380e"
  name        = "stripsensitiveheaders1"
  kind        = "zone"
  phase       = "http_response_headers_transform"

  rules {
    action = "rewrite"
    action_parameters {
      headers {
        name       = "ETag"
        operation  = "remove"
      }

      /*
      headers {
        name      = "Server"
        operation = "remove"
      }
      */

      headers {
        name      = "X-Account-Id"
        operation = "remove"
      }

      headers {
        name      = "X-Application-Id"
        operation = "remove"
      }

      headers {
        name      = "X-AspNet-Duration-Ms"
        operation = "remove"
      }

      headers {
        name      = "X-Elastic-Count"
        operation = "remove"
      }

      headers {
        name      = "X-Elastic-Duration-Ms"
        operation = "remove"
      }

      headers {
        name      = "X-Flags"
        operation = "remove"
      }

      headers {
        name      = "X-Http-Count"
        operation = "remove"
      }

      headers {
        name      = "X-Http-Duration-Ms"
        operation = "remove"
      }

      headers {
        name      = "X-Is-Crawler"
        operation = "remove"
      }

      headers {
        name      = "X-Page-View"
        operation = "remove"
      }

      headers {
        name      = "X-Providence-Cookie"
        operation = "remove"
      }

      headers {
        name      = "X-Redis-Count"
        operation = "remove"
      }

      headers {
        name      = "X-Redis-Duration-Ms"
        operation = "remove"
      }

      headers {
        name      = "X-Request-Guid"
        operation = "remove"
      }

      headers {
        name      = "X-Route-Name"
        operation = "remove"
      }

      headers {
        name      = "X-Sql-Count"
        operation = "remove"
      }

      headers {
        name      = "X-Sql-Duration-Ms"
        operation = "remove"
      }

      headers {
        name      = "X-SSL"
        operation = "remove"
      }

      headers {
        name      = "X-Targeting-Cookie"
        operation = "remove"
      }

      headers {
        name      = "X-TE-Count"
        operation = "remove"
      }

      headers {
        name      = "X-TE-Duration-Ms"
        operation = "remove"
      }
    }

    expression  = "true" #apply to all requests
    description = "stripsensitiveheaders"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/rayterrill/86d876707bc150718242beaa2c6f00da

### Expected output

resource should create ruleset successfully and not fail.

### Actual output

resource fails, it looks like because it's changing the ordering of rules (it looks like it's ASCII sorting them - with case-sensitivity), which don't match the expected output.

### Steps to reproduce

1. create a ruleset with rules as described

**Comment by jacobbednarz** [comment]
hey @rayterrill 👋 you're correct about the sorting. the backing service expects them to be sorted and maintain that sorting in order to prevent a permadiff. 

the internal team already have a ticket about improving the UX but it was an intentional decision. 

i'm going to close this one off as there isn't anything for us to do at the moment and when/if the team changes the behaviour, it should automatically roll out and allow you to put the headers in any order. 

duplicates #2500 and #2343.

**Comment by rayterrill** [comment]
@jacobbednarz Shouldn't there be a note that this is a requirement in the docs at a minimum if this is the expectation? I see this came up in a previous linked ticket as well.

**Comment by rayterrill** [comment]
@jacobbednarz I did find the note in the docs for the `headers` block list: "Note: Headers are order dependent and must be provided sorted alphabetically ascending based on the name value.".

This is a pretty unfortunate way of handling things - if the block requires resource be ordered in a particular way because of backing API requirements, it would be much nicer if it enforced that up-front as opposed to blowing up/panic from a Terraform apply perspective because the applied state didn't match what was expected.
