### ISSUE TITLE
pop_pools, region_pools, and country_pools do not remove when last block is removed

### ISSUE THREAD

**Issue by troymjones** [cloudflare/terraform-provider-cloudflare#2659]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.11.0

### Affected resource(s)

cloudflare_load_balancer

### Terraform configuration files

```hcl
# Resource update
resource "cloudflare_load_balancer" "pop-cf-test" {
  name        = "my-test-lb.cf.my-test-domain.com"
  description = "my-test-lb"
  default_pool_ids = [
    cloudflare_load_balancer_pool.failover_pool_geo.id,
  ]
  fallback_pool_id = cloudflare_load_balancer_pool.fallback_pool_geo.id
  enabled          = true
  proxied          = true
  steering_policy  = "geo"
  zone_id          = data.cloudflare_zone.my_test_domain.id
}

# Resource created
resource "cloudflare_load_balancer" "pop-cf-test" {
  name        = "my-test-lb.cf.my-test-domain.com"
  description = "my-test-lb"
  default_pool_ids = [
    cloudflare_load_balancer_pool.failover_pool_geo.id,
  ]
  fallback_pool_id = cloudflare_load_balancer_pool.fallback_pool_geo.id
  enabled          = true
  proxied          = true
  steering_policy  = "geo"
  zone_id          = data.cloudflare_zone.my_test_domain.id

  pop_pools {
    pool_ids = [
      cloudflare_load_balancer_pool.pool.id,
      cloudflare_load_balancer_pool.failover_pool_geo.id,
    ]
    pop = "FSD"
  }

  region_pools {
    pool_ids = [
      cloudflare_load_balancer_pool.pool.id,
      cloudflare_load_balancer_pool.failover_pool_geo.id,
    ]
    region = "EEU"
  }
}
```

### Link to debug output

Relevant output: https://gist.github.com/troymjones/815f8f633abf9296c949dc5dc254803b
Full output: https://gist.github.com/troymjones/00ba9c87e5c1f9c260473d32ca6e1f18

### Expected output

```hcl
Terraform will perform the following actions:

  # cloudflare_load_balancer.pop-cf-test will be updated in-place
  ~ resource "cloudflare_load_balancer" "pop-cf-test" {
        id               = "<zone_id>"
        name             = "my-test-lb.cf.my-test-domain.com"
        # (11 unchanged attributes hidden)

      - pop_pools {
          - pool_ids = [
              - "<pool_id>",
              - "<pool_id>",
            ] -> null
          - pop      = "FSD" -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Actual output

```hcl
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

### Steps to reproduce

1. Create and apply load balancer resource with pop_pools, region_pools and/or country_pools blocks
2. Remove all of the remaining pop_pools, region_pools and/or country_pools blocks
3. Run terraform plan and/or terraform apply
4. No changes are shown in the plan or apply

### Additional factoids

This seems to be an issue with the fact the key does not exist and therefore the blank/null value is never set. See code here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/resource_cloudflare_load_balancer.go#L184-L190

Datadog has a similar provider with assertions under datadog_synthetics_test resource. By setting it as an empty object before checking for the key, it gets set to a blank value if the key does not exist. See code here: https://github.com/DataDog/terraform-provider-datadog/blob/master/datadog/resource_datadog_synthetics_test_.go#L1458

**Comment by jacobbednarz** [comment]
can you please provide the entirety of the debug output? i'm not seeing where the issue is here.

**Comment by troymjones** [comment]
Here's the full debug output, but there's a lot in there that isn't relevant. https://gist.github.com/troymjones/00ba9c87e5c1f9c260473d32ca6e1f18

The original gist above only shows the relevant portion.

Did you see the example given as well as the expected output? 

To summarize - when a load balancer has pop_pools set, they correctly apply. Then on an update, when all the pop_pools blocks are removed, the terraform does not show any changes when it should in fact remove the pop_pools and show an update to the load balancer. Instead it shows no changes and the apply makes no updates. This is the same situation with country_pools and region_pools.
