### ISSUE TITLE
phase "http_response_headers_transform_managed" is not accessible in this API

### ISSUE THREAD

**Issue by maccmiles** [cloudflare/terraform-provider-cloudflare#2662]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.11.0
+ provider registry.terraform.io/hashicorp/local v2.4.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "enable-managed-response-headers" {
  zone_id     = cloudflare_zone.example-root.id
  name        = "Managed Response Header Ruleset"
  description = "Managed Response Headers"
  kind        = "managed"
  phase       = "http_response_headers_transform_managed"

  rules {
    action = "execute"
    action_parameters {
      id = "remove_x-powered-by_header"
    }
    description = "Removes X-Powered By header"
    expression  = "true"
    enabled     = true
  }

  rules {
    action = "execute"
    action_parameters {
      id = "add_security_headers"
    }
    description = "Adds security headers"
    expression  = "true"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/maccmiles/b756c9975912ec61f822aabd9dc250d1

### Expected output

cloudflare_ruleset.enable-managed-response-headers: Creating...
cloudflare_ruleset.enable-managed-response-headers: Creation complete after Xs [id=################]

### Actual output

│ Error: error creating ruleset Managed Response Header Ruleset
│ 
│   with cloudflare_ruleset.enable-managed-response-headers,
│   on transforms-managed.tf line 151, in resource "cloudflare_ruleset" "enable-managed-response-headers":
│  151: resource "cloudflare_ruleset" "enable-managed-response-headers" {
│ 
│ phase "http_response_headers_transform_managed" is not accessible in this API

### Steps to reproduce

Attempt to create a cloudflare_ruleset resource with a managed response header

### Additional factoids

per https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#phase `http_response_headers_transform_managed` should be a valid entry

### References

phase support for `http_response_headers_transform_managed` mentioned by name in https://github.com/cloudflare/terraform-provider-cloudflare/pull/1757

**Comment by jacobbednarz** [comment]
for managed transforms, you need to use [`cloudflare_managed_headers`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/managed_headers) resource, not `cloudflare_ruleset`.
