### ISSUE TITLE
Declare application type "private_ip" as stable

### ISSUE THREAD

**Issue by MarcErdmann** [cloudflare/terraform-provider-cloudflare#2665]
### Current Terraform and Cloudflare provider version

-

### Description

I request private apps / type "private_ip" to be declared stable and included in the API docs as well as the terraform provider.

### Use cases

You can create Cloudflare Access Applications with application type "private_ip" via the Cloudflare web portal. However, this is not possible via tools such as Terraform until now. Maintainers of e.g. the Terraform provider require the application type to be declared stable before implementing it. I have linked issues below.

### Potential Terraform configuration

```hcl
...
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/1975
https://github.com/cloudflare/terraform-provider-cloudflare/issues/2030

**Comment by jacobbednarz** [comment]
the team will follow up with the changes when it is deemed stable and the API is ready. 

for now, this is closed and the teams have internal tracking around it.

**Comment by jacobbednarz** [comment]
afraid not. it is up to the individual teams and when they deem the service or attributes to be suitable for public consumption.

**Comment by halradaideh** [comment]
the feature is stable as far as I know

any timeframe now?

**Comment by halradaideh** [comment]
reminder

**Comment by blackjid** [comment]
Hi @jacobbednarz @Justin-Holmes it looks like the api is stable now. Are we going to be able to  create private network application with the terraform provider? Thanks!
