### ISSUE TITLE
Perma-diff on `cloudflare_record`'s `data.name` field

### ISSUE THREAD

**Issue by sybereal** [cloudflare/terraform-provider-cloudflare#2681]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.12.0

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "ts3_srv" {
  zone_id = local.cf_zone_id
  name    = "_ts3._udp.ts"
  type    = "SRV"

  data {
    service = "_ts3"
    proto   = "_udp"
    # FIXME: This perma-diffs for some reason, as the API seems to return the FQDN instead of just the label
    name     = "ts"
    target   = cloudflare_record.server["A"].hostname
    port     = 9987
    priority = 0
    weight   = 5
  }
}
```

### Link to debug output

https://gist.github.com/sybereal/d7fd18a3e1064f543b87206b22b39c31

### Expected output

No further changes after initial apply.

### Actual output

`terraform plan` wants to change the `data.name` field from FQDN to just the first label every time. Actually applying such a plan appears to be a no-op.

### Steps to reproduce

1. Define a SRV `cloudflare_record` with `data.name` not being a FQDN.
2. `terraform apply`
3. `terraform plan`

### Additional factoids

`terraform state show cloudflare_record.ts3_srv` shows that `data.name` is the FQDN from Terraform's point of view:
```hcl
resource "cloudflare_record" "ts3_srv" {
    allow_overwrite = false
    created_on      = "2023-08-12T12:23:11.307787Z"
    hostname        = "_ts3._udp.ts3.example.com"
    id              = "df096046746155b9906df1388de74e66"
    metadata        = {
        "auto_added"             = "false"
        "managed_by_apps"        = "false"
        "managed_by_argo_tunnel" = "false"
        "source"                 = "primary"
    }
    modified_on     = "2023-08-12T12:23:11.307787Z"
    name            = "_ts3._udp"
    priority        = 0
    proxiable       = false
    proxied         = false
    tags            = []
    ttl             = 1
    type            = "SRV"
    value           = "5\t9987\tfoo.example.com"
    zone_id         = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

    data {
        algorithm      = 0
        altitude       = 0
        digest_type    = 0
        key_tag        = 0
        lat_degrees    = 0
        lat_minutes    = 0
        lat_seconds    = 0
        long_degrees   = 0
        long_minutes   = 0
        long_seconds   = 0
        matching_type  = 0
        name           = "ts3.example.com"
        order          = 0
        port           = 9987
        precision_horz = 0
        precision_vert = 0
        preference     = 0
        priority       = 0
        proto          = "_udp"
        protocol       = 0
        selector       = 0
        service        = "_ts3"
        size           = 0
        target         = "foo.example.com"
        type           = 0
        usage          = 0
        weight         = 5
    }
}
```

And, indeed, if I change `data.name` to the FQDN, then there is no "drift". However, this explicitly goes against the documentation of `cloudflare_record`, which does not use a FQDN:

```hcl
resource "cloudflare_record" "_sip_tls" {
  zone_id = var.cloudflare_zone_id
  name    = "_sip._tls"
  type    = "SRV"

  data {
    service  = "_sip"
    proto    = "_tls"
    name     = "terraform-srv"
    priority = 0
    weight   = 0
    port     = 443
    target   = "example.com"
  }
}
```

**Comment by jacobbednarz** [comment]
if the API uses a FQDN, you should use it here. the registry documentation is not the source of truth for the API, only and example of how the fields should be utilised. 

if you want to send over a PR updating the documentation, we can get that updated.
