### ISSUE TITLE
Support R2 scope for token permissions in `api_token_permission_groups` datasource

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [cloudflare/terraform-provider-cloudflare#2684]
### Current Terraform and Cloudflare provider version

Terraform v1.5.0
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.12.0

### Description

Now that R2 bucket scoped tokens are out, there is a new scope of `com.cloudflare.edge.r2.bucket` and it would be nice if it was a separate scope in the [api_token_permission_groups datasource](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/data_source_api_token_permission_groups.go#L68-L77) rather than having to use the legacy `permissions` output.

I can work on this if accepted and a name chosen, maybe just `r2`.

### Use cases

Making R2 API tokens that are bucket scoped.

### Potential Terraform configuration

```hcl
data "cloudflare_api_token_permission_groups" "all" {}

# Get R2 Write permssions.
output "r2_write_permissions" {
  value = data.cloudflare_api_token_permission_groups.all.r2["Workers R2 Storage Bucket Item Write"] 
}
```

### References

Part of a custom module I wrote
https://github.com/Cyb3r-Jak3/terraform-cloudflare-api-permissions/blob/main/outputs.tf#L13-L16
Permissions
https://api.cyberjake.xyz/cloudflare_api/token_permissions?scope=r2

**Comment by jacobbednarz** [comment]
sounds good 👍 do you want to send over a PR for this?
