### ISSUE TITLE
Allows to have rules split in different repos

### ISSUE THREAD

**Issue by peruzzof** [cloudflare/terraform-provider-cloudflare#2688]
### Current Terraform and Cloudflare provider version

Terraform v1.5.5
+ provider registry.terraform.io/cloudflare/cloudflare v4.12.0

### Description

Create a flag that allows the usage of cloudflare_rulesets that are not complete. This flag will allow to merge new and existing rulesets per kind.

### Use cases

We have  a single Cloudflare zone (domain.io) that has multiple hosts (api-dev, api-test, api-uat...) that are being created together with our product, so we have one for dev, another test and so on.
As one extra resource that is being create is the WAF filter to allow some problematic traffic (graphql queries).

With the introduction of the resource "cloudflare_ruleset" we are not allowed to manage it in the same way and we will need to decouple the DNS/WAF from our product pipeline.

While I understand the issues as explained at #2423 I would prefer to assume the risk to create multiple resources, with the configuration per hots in multiple terraform states.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "zone_custom_firewall" {
  merge_existing_rulesets = enabled

  zone_id = var.cloudflare_zone_id

  name        = "Rule for ${var.project_id}"
  description = "This rule is managed by Terraform in the project XYZ"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

..
```

### References

This is similar to #2423

**Comment by jacobbednarz** [comment]
closing this off as a duplicate. 

we aren't currently tracking this externally due to some unknowns. if/when this comes to fruition, the team will add support to the provider.

**Comment by petero-dk** [comment]
I added a workaround using multiple repositories here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/3027#issuecomment-2138260815

**Comment by acdha** [comment]
I just wanted to voice support for this: like many large organizations, we have multiple parties creating rules from fully-managed DevOps projects using Terraform to security response in the console and, especially in the latter case, this spreads across applications in ways which are not trivial to model in source code structures.

Ideally, we would be able to manage individual rules similar to how the Terraform AWS provider allows you to add a single rule to a security group without taking over management of the whole group. @fholzer's data provider approach looks potentially interesting if it solves the pain-points around a workflow along the lines of “take all of the existing `http_request_firewall_custom` rules and append this one” but it still seems somewhat risky to have a potential single Terraform mistake remove a lot of WAF rules. This makes me wonder how hard it would be to have a failsafe mechanism to avoid `cloudflare_ruleset` deleting rules which it did not create (I'd prefer it throw an error in such cases).

My goal was to replace the increasingly-deprecated `cloudflare_zone_lockdown` rules which have a much better experience for management at scale.
