### ISSUE TITLE
Support `logpush` for `cloudflare_pages_project` resource

### ISSUE THREAD

**Issue by brendonmatos** [cloudflare/terraform-provider-cloudflare#2689]
### Current Terraform and Cloudflare provider version

Terraform v1.4.6
on darwin_arm64

provider registry.terraform.io/cloudflare/cloudflare v4.7.1

### Description

Currently, isn't possible to enable logpush in `cloudflare_pages_project` resource.

This parameter is only available on worker_script: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/worker_script#logpush

### Use cases

https://developers.cloudflare.com/logs/

### Potential Terraform configuration

```hcl
resource "cloudflare_pages_project" "basic_project" {
  ...
  logpush = true
  ...
}
```

```hcl
resource "cloudflare_pages_project" "basic_project" {
  ...
  deployment_configs {
    preview {
      logpush = true
    }
  }
  ...
}
```

**Comment by jacobbednarz** [comment]
logpush isn't supported for Pages. if you'd like to see it as a feature, please log a support ticket requesting it to have it considered.
