### ISSUE TITLE
Support for Creating Cloudflare Account Members with Domain-Scoped Roles

### ISSUE THREAD

**Issue by borislimgh** [cloudflare/terraform-provider-cloudflare#2712]
### Current Terraform and Cloudflare provider version

Terraform v1.5.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.12.1

### Description

Submitting this feature request to propose the addition of a new feature that allows creating Cloudflare account members with domain-scoped roles. Currently, the Terraform Cloudflare provider offers functionality to create account members and assign them roles, but this is at the account level. This feature aims to enhance the provider's capabilities by enabling users to create account members with roles scoped to specific domains within the account.

### Use cases

 For example, we want to grant some team members access only to specific domains. This helps improve security by limiting unnecessary access.

### Potential Terraform configuration

```
resource "cloudflare_account_member" "domain_member" {
  account_id    = data.cloudflare_accounts.my_account.id
  email_address = "user@example.com"
  role_ids      = [data.cloudflare_domain_role.domain_admin.id]

  domain_roles {
    domain_id  = data.cloudflare_domain.my_domain.id
    role_names = ["SSL/TLS", "Caching", "Performance", "Page Rules", "Customization"]
  }
}
```

**Comment by fingalickn** [comment]
Need, please gimmie.

**Comment by arazdolski** [comment]
Hi, I'm Interested in working on this issue but seems Cloudflare API doesn't support domain scoping for members/roles. Checked [Add Member](https://developers.cloudflare.com/api/operations/account-members-add-member) and [Update Member](https://developers.cloudflare.com/api/operations/account-members-update-member) endpoints. Correct me if I'm wrong

**Comment by jacobbednarz** [comment]
correct, the APIs are not documented or stable so we won't be accepting contributions for this at this point. 

the internal IAM team will be making a pass at this once the APIs are stable.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
