### ISSUE TITLE
Access S3 client credentials from R2 storage API token

### ISSUE THREAD

**Issue by kaufmo** [cloudflare/terraform-provider-cloudflare#2713]
### Current Terraform and Cloudflare provider version

Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.13.0

### Description

It would be really nice when the cloudflare_api_token output would be extended for the s3 credentials "Access Key ID" & "Secret Access Key"

### Use cases

Im working on an CI/CD configuration which creates an R2 Bucket with an api token which only have write access for this bucket. After that i would like to store the s3 credentials in the terraform output to reuse it for my runners configuration which can access over the native s3 api.

### Potential Terraform configuration

```hcl
output "s3_access_key_id" {
  value     = cloudflare_api_token.token.access_key_id
  sensitive = true
}
output "s3_secret_access_key" {
  value     = cloudflare_api_token.token.secret_access_key
  sensitive = true
}
```

**Comment by Cyb3r-Jak3** [comment]
You can also do this. The secret is just a SHA256 of the value.
Something like 
```hcl

output "id" {
  value       = cloudflare_api_token.token.id
  description = "API Token ID.\nUsed as the Access Key ID"
}

output "secret" {
  value       = sha256(cloudflare_api_token.token.value)
  sensitive   = true
  description = "Secret Access Key"
}
```
should work.
https://github.com/Cyb3r-Jak3/terraform-cloudflare-r2-api-token/blob/main/outputs.tf

**Comment by kaufmo** [comment]
> You can already do this. The secret is just a SHA256 of the value. Something like
> 
> ```terraform
> output "id" {
>   value       = cloudflare_api_token.token.id
>   description = "API Token ID.\nUsed as the Access Key ID"
> }
> 
> output "secret" {
>   value       = sha256(cloudflare_api_token.token.value)
>   sensitive   = true
>   description = "Secret Access Key"
> }
> ```
> 
> should work. https://github.com/Cyb3r-Jak3/terraform-cloudflare-r2-api-token/blob/main/outputs.tf

Hi @Cyb3r-Jak3,
thx for your answer but for me this is not working and when getting the following error: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

When I compare the secret you generate with sha256 and the secret mentioned in the cloudflare UI then this two are not the same maybe this is the Problem? 

FYI @jacobbednarz 

PS this is my terraform config 
```terraform
resource "cloudflare_r2_bucket" "bucket" {
  account_id = var.account_id
  name       = "foobar"
  location   = "WEUR"
}

data "cloudflare_api_token_permission_groups" "all" {}
resource "cloudflare_api_token" "token" {
  name = cloudflare_r2_bucket.bucket.name

  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.r2["Workers R2 Storage Bucket Item Write"],
    ]
    resources = {
      "com.cloudflare.edge.r2.bucket.${var.account_id}_default_${cloudflare_r2_bucket.bucket.id}" = "*"
    }
  }
}

output "id" {
  value       = cloudflare_api_token.token.id
  description = "API Token ID.\nUsed as the Access Key ID"
}

output "value" {
  value       = cloudflare_api_token.token.value
  sensitive   = true
  description = "API Token Value"
}

output "secret" {
  value       = sha256(cloudflare_api_token.token.value)
  sensitive   = true
  description = "Secret Access Key"
}

output "name" {
  value       = cloudflare_api_token.token.name
  description = "Name of the API Token"
}
```
