### ISSUE TITLE
Cloudflare WAF rules disorder with out any changes by terraform in Kubernetes clusters

### ISSUE THREAD

**Issue by ashish-dua** [cloudflare/terraform-provider-cloudflare#2715]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.5
on linux_arm64

provider cloudflare/cloudflare v4.10.0

### Affected resource(s)

cloudflare_firewall_rule that is allowed when run via Terraform shifts /reshuffles down in the order and goes below Block WAF rule that is created manually

### Terraform configuration files

```hcl
resource "cloudflare_firewall_rule" "abc" {
  count = var.create_cloudflare && length(var.nat_ips) > 0 ? 1 : 0
  zone_id = ...
  description = "..."
  filter_id = cloudflare_filter.nats[0].id
  action = "allow"
}
```

### Link to debug output

NA

### Panic output

NA

### Expected output

There is no such error reported in Terraform apply ; WAF rule reshuffles created via Terraform in priority ; It shifts to the end and Any block rule gets promoted above which causes Cloudflare traffic to be blocked

### Actual output

cloudflare_firewall_rule resource should not be shifted that is created with Terraform's order should not be shifted below Any mentioned rules ie Block rule shifts above terraform managed WAF rule

### Steps to reproduce

1) Run Terraform code for Cloudflare with cloudflare_firewall_rule resource with Terraform provider 1.5.5 and Cloudflare provider v4.10.0
2) Create rule in Cloudflare dashboard in WAF with Block action
3) Run terraform apply with configuration mentioned in Step1
4)It reshuffles WAF rule that was created by Terraform below Cloudflare WAF rule with Block action causing Cloudflare to block traffic to Domains

### Additional factoids

NA

### References

NA

**Comment by jacobbednarz** [comment]
the resource in your reproduction case isn't the same one mentioned by the error. can you please read the prior automation comments and update the reproduction case accordingly to diagnose this one?

**Comment by ashish-dua** [comment]
> the resource in your reproduction case isn't the same one mentioned by the error. can you please read the prior automation comments and update the reproduction case accordingly to diagnose this one?

Should I update the Expected Output and Actual Output?

**Comment by ashish-dua** [comment]
I have updated the bug
@jacobbednarz : Can you review now?

**Comment by ashish-dua** [comment]
@jacobbednarz : Please review this bug as It has been pending from long and There is no fix even in latest version of cloudflare provider
