### ISSUE TITLE
cloudflare_access_group (Resource) ip_list attribute results in "Unknown Type" on CloudFlare UI

### ISSUE THREAD

**Issue by fguendling** [cloudflare/terraform-provider-cloudflare#2716]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.13.0

### Affected resource(s)

cloudflare_access_group 

### Terraform configuration files

```hcl
resource "cloudflare_access_group" "allowlist" {
  zone_id = var.zone_id
  name    = "AllowlistIPs"
  include {
    ip_list  = toset(var.ip_allowlist) # it's just a list
  }
}
```

### Link to debug output

None

### Expected output

In the UI of CloudFlare Access, I expect the correct type to be shown (IP List), instead of Unknown Type

### Actual output

Unknown Type

### Steps to reproduce

Try to create a resource with the given configuration

**Comment by Nmishin** [comment]
Looks like here we have two issues:
- a little bit outdated description for `ip_list` parameter
- something with Cloudflare UI

For `ip_list` parameter, [according to API](https://developers.cloudflare.com/api/operations/zone-level-access-groups-create-an-access-group), should be used the ID of a previously created IP list (inside of Zero Trust).

For Cloudflare UI - even for properly created Access group (manually or via terraform) I also see the `Unknown Type: 8b8c13bd-7b61-4e21-893e-251c34095a11`.

Terraform configuration should looks like:
```
resource "cloudflare_access_group" "allowlist" {
  zone_id = var.zone_id
  name    = "AllowlistIPs"
  include {
    ip_list = ["8b8c13bd-7b61-4e21-893e-251c34095a11"]
  }
}
