### ISSUE TITLE
Cloudflare Ruleset Resource - Custom WAF Rule - Skip

### ISSUE THREAD

**Issue by jhough-teleflora** [cloudflare/terraform-provider-cloudflare#2724]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.5
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.12.0
+ provider registry.terraform.io/hashicorp/azurerm v3.0.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
terraform {
	required_providers {
		# Cloudflare provider
		cloudflare = {
		source  = "cloudflare/cloudflare"
		version = "~> 4.0"
		}
		# Azure rm provider
		azurerm = {
			source  = "hashicorp/azurerm"
			version = "=3.0.0"
		}
	}
	# Terraform state file backend management
	backend "azurerm" {
		subscription_id   = "REDACTED"
		resource_group_name = "REDACTED"
		storage_account_name = "REDACTED"
		container_name = "REDACTED"
		key = "REDACTED"
	}
}

# Authentication
provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

# Variables
variable "cloudflare_api_token" {
  	type = string
	sensitive   = true
}

# Add single custom rule to WEB zone
resource "cloudflare_ruleset" "zone_custom_firewall" {
  zone_id     = "REDACTED"
  name        = "Test Rule"
  kind        = "zone"
  phase       = "http_request_firewall_custom"
  rules {
    action = "skip"
    action_parameters {
        ruleset = "REDACTED"  # Current default firewall_custom ID
    }
    expression = "(not cf.edge.server_port in {80 443})"
    description = "Test"
  }
}
```

### Link to debug output

https://gist.github.com/jhough-teleflora/53ced569d8f5be375abb8748ede39d92

### Expected output

I expected that the custom WAF rule would be created with the provided configuration.
A rule with the name "Test Rule", action would be "skip". 

The end goal is to create a custom rule that skips the remaining custom rules once the expression is met.
In the web console, this would be the equivalent of selecting "Skip" as the action and checking the "All remaining custom rules" box under the "WAF components to skip" section.

### Actual output

After Terraform attempted the modification, Terraform threw an error saying that the ruleset ID given was an "unknown variant". 

### Steps to reproduce

1. Create a cloudflare_ruleset resource that has the action "skip" and attempts to skip the remaining custom WAF rules.
2. Run "terraform apply".

### Additional factoids

I have tried the above process with deleting the "firewall_custom" ruleset through the api first, then creating this rule and had the same issue.

This could be that I was missing the documentation for this but I could not find any documentation for this specific use case.

**Comment by jhough-teleflora** [comment]
Added the requested output in the "Link to debug output" section.

**Comment by jacobbednarz** [comment]
that is not the expected debug output. you will need to prefix the terraform operation with `TF_LOG=DEBUG` (from the issue template) to get the correct output.

**Comment by jhough-teleflora** [comment]
Issue#1390 references what I needed to create the skip ruleset:
https://github.com/cloudflare/terraform-provider-cloudflare/issues/1390

I will report that I ran into a bug in the provider. Here is the error I received when successfully creating the ruleset:

╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to cloudflare_ruleset.zone_custom_firewall, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[0].logging: block count changed from 0 to 1.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by zpbonjour** [comment]
@jhough-teleflora Using a combo of the Cloudflare API docs and the Terraform module docs I was also not able to create a custom rule that skips "all remaining custom rules". 

In the Cloudflare docs [the Skip action is applied to the phases and products](https://developers.cloudflare.com/waf/custom-rules/skip/options/), not a ruleset or list of rulesets.  So the action_parameters.ruleset block will not work instead it needs to be action_parameters.phases and/or action_parameters.products.

 If I try to add the custom rules phase, I get an error.  Which makes sense as I'm adding a rule to the phase and then trying to skip that same phase.  🤷‍♂️ 
`"skip action parameter phase 'http_request_firewall_custom' is not authorized (20120)"`

Here's the resource I have right now, but its just missing the custom rules bit.  I would love some input from the team here to help get that last setting applied.  It there in the Cloudflare UI, but I can't find an API option for it.

```
resource "cloudflare_ruleset" "zone_level_custom_ruleset" {
  for_each    = var.zone_ids
  zone_id     = each.value
  name        = "${each.key} Webserver Self Calls"
  kind        = "zone"
  phase       = "http_request_firewall_custom"
  rules {
    description = "${each.key} Webserver Self Calls"
    action      = "skip"
    action_parameters {
      phases = ["http_request_firewall_managed", "http_ratelimit", "http_request_sbfm"]
      products = ["bic","zoneLockdown"]
    }
    expression = "(ip.src eq ${var.aws_webserver_ip_address})"
    enabled    = true
    logging {
      enabled = true
    }
  }
}
```

**Comment by vselcuk** [comment]
atlantis unlock

**Comment by yeaminr** [comment]
I couldn't find a terraform equivalent to "Skip all remaining rules" on the CF dashboard. But below iteration code of terraform inside the `action_parameters` worked for me as an alternative:

```
action_parameters {
      rulesets = [for rule in local.waf_managed_ruleset.rules : rule.action_parameters.id]
    }
```

**Comment by devang704** [comment]
Hi, I'm working on Cloudflare WAF rules at the zone level. I've created a primary rule to "Deny All," which blocks all traffic to the zone. Now, I want to add another rule that allows requests from a specific IP range for a particular DNS record. However, when I try to create this additional custom WAF rule at the zone level, it isn't being created successfully.


`      
### This is Deny All
        resource "cloudflare_ruleset" "zone_custom_firewall" {
        zone_id     = "zone-id"
        name        = "Deny All"
        description = "Deny All"
        kind        = "zone"
        phase       = "http_request_firewall_custom"

        rules {
          action = "block"
          expression  = "(ip.src in { 0.0.0.0/0 })"
          description = "Deny All"
          enabled     = true
        }
      }
      
### This is Skip Rule
      resource "cloudflare_ruleset" "zone_custom_firewall_skip" {
        zone_id     = "zone-id"
        name        = "api.saas"
        description = ""
        kind        = "zone"
        phase       = "http_request_firewall_custom"

        rules {
          action = "skip"
          action_parameters {
              ruleset = "current"
              }
          expression = "(ip.src in {123.185.456.169} and http.host eq \"api.saas.example.com\")"
          description = ""
          enabled = true
          logging {
            enabled = true
          }          
        }
      }
      `

**Comment by jhough-teleflora** [comment]
@devang704 - If those are the exact values you are using for the rules then the issue is with your allow rule. 

**The source IP address is not a valid IP address -> "123.185.456.169"**

255 is the highest value that you can have for any of the octets of an IP address.

**Comment by devang704** [comment]
Hi This is not the real IP address I just put random IP,  The error I am getting is below.

`
Error: failed to create ruleset "http_request_firewall_custom"

  with cloudflare_ruleset.zone_custom_firewall_skip,
  on main.tf line 1, in resource "cloudflare_ruleset" "zone_custom_firewall_skip":
   1: resource "cloudflare_ruleset" "zone_custom_firewall_skip" {

A similar configuration with rules already exists and overwriting will have
unintended consequences. If you are migrating from the Dashboard, you will
need to first import the existing rules using cf-terraforming. You can find
details about how to do this at
https://developers.cloudflare.com/terraform/additional-configurations/ddos-managed-rulesets/#optional-delete-existing-rulesets-to-start-from-scratch`

**Comment by jhough-teleflora** [comment]
That error is because you are trying to create rules that already exist in Cloudflare. So you can either import the rules that already exist into your tfstates file, or you can delete the custom WAF rules and then run terraform.
