### ISSUE TITLE
`scim_config.secret` in `cloudflare_access_identity_provider` not populated correctly

### ISSUE THREAD

**Issue by F21** [cloudflare/terraform-provider-cloudflare#2743]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.14.0

### Affected resource(s)

cloudflare_access_identity_provider

### Terraform configuration files

```hcl
resource "cloudflare_access_identity_provider" "azure_ad" {
  account_id = "REDACTED"
  name       = "AzureAD"
  type       = "azureAD"

  config {
    client_id      = "test"
    client_secret  = "test"
    directory_id   = "test"
    support_groups = true
  }
  scim_config {
    enabled = true
    group_member_deprovision = true
  }
}

output "scim_secret" {
  value = cloudflare_access_identity_provider.azure_ad.scim_config[0].secret
}
```

### Link to debug output

https://gist.github.com/F21/4e163a84f284987a904153931506514c

### Expected output

Terraform should output the scim secret. If `scim_config.secret` is marked as sensitive in the resource schema, it should be displayed as `(sensitive)`, like so:

```
scim_secret =  (sensitive)
```

### Actual output

It was displayed as:
```
scim_secret = "**********************************"
```

### Steps to reproduce

1. Run terraform apply.

### Additional factoids

The reason for this bug is outlined in the API documentation: https://developers.cloudflare.com/api/operations/access-identity-providers-add-an-access-identity-provider#response-body

As stated under `result.scim_config.secret` in the response body, the `secret` parameter is only returned upon resource creation for the first time and is redacted in subsequent requests.

In the current implementation, the secret is not stored in the state after the creation of the identity provider. Rather, the resource is read back after creation, which literally reads the redacted secret: `**********************************` and then stores it in the state. This results in the actual SCIM secret being unaccessible and lost forever.

**Comment by jacobbednarz** [comment]
this isn't a bug but instead how the API performs a write only operation on the value. i've expanded on how we can handle this in https://github.com/cloudflare/terraform-provider-cloudflare/pull/2744#issuecomment-1726816439 but just for posterity, if you wish to have this value used in multiple places you should assign it to a local or fetch it from a secure backend.

**Comment by F21** [comment]
Thanks for taking a look at this, however the problem is that with the current implementation, it is impossible to get the `scim_config.secret` event after the creation of the identity provider. The secret is immediately overwritten after resource creation, leaving no opportunity to retrieve it.

**Comment by jacobbednarz** [comment]
have a look at the PR comment -- we've done this with another field and if we take that approach, you can retrieve it without manually munging the state via the schema building method.
