### ISSUE TITLE
R2: allow editing of "Object lifecycle rules"

### ISSUE THREAD

**Issue by kaufmo** [cloudflare/terraform-provider-cloudflare#2751]
### Current Terraform and Cloudflare provider version

Terraform v1.5.6
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.14.0

### Description

as for now there are multiple resources to manage rules from cloudflare it would also be nice to manage the object lifecycle rules in the r2 storage

Object lifecycle rule:
![Bildschirmfoto vom 2023-09-08 07-05-11](https://github.com/cloudflare/terraform-provider-cloudflare/assets/1416828/95d04131-0e73-4a76-8889-35d9c347f899)
![Bildschirmfoto vom 2023-09-08 07-05-38](https://github.com/cloudflare/terraform-provider-cloudflare/assets/1416828/06ec8e78-a182-4361-99bb-dff5ac3f7596)

Rules:
![Bildschirmfoto vom 2023-09-08 07-07-34](https://github.com/cloudflare/terraform-provider-cloudflare/assets/1416828/96ac3d8b-1698-4eb5-88e6-138419f6db9f)

### Use cases

One of our use cases is that we use the R2 Bucket as CI/CD Cache and therefor it would be nice to enable an object lifecycle rule where the objects gets deleted for example after 90 days

### Potential Terraform configuration

```hcl
resource "cloudflare_object_lifecycle_ruleset" "example" {
  account_id = "xxx"
  bucket_id = "xxx"

  rules = [
    {
      name = "Delete old objects"
      delete_uploaded_objects = {
        type: "days"
        value: 90
      }
      enabled = true
    }
  ]
}
```

**Comment by Cyb3r-Jak3** [comment]
You can use the AWS terraform provider to add items like lifecycle configurations
https://developers.cloudflare.com/r2/examples/terraform-aws/

**Comment by kaufmo** [comment]
> You can use the AWS terraform provider to add items like lifecycle configurations https://developers.cloudflare.com/r2/examples/terraform-aws/

ah okay good to know thx, is this the prefered way or will this also be added for the cloudflare provider?

**Comment by Cyb3r-Jak3** [comment]
Personally, I'd recommend doing all the advanced configuration stuff like CORS or lifecycle rules with the aws provider. R2 just implements the S3 API, so the provider will be able to do more and doesn't require work from Cloudflare's side.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by shufps** [comment]
Has the AWS Lifecycle example worked for anybode with R2? 

I just get an error about some malformed XML

**Comment by punya** [comment]
I'm going to try out https://search.opentofu.org/provider/opentofu/cloudflare/latest/docs/resources/r2_bucket_lifecycle
