### ISSUE TITLE
Cloudflare List import is returning all items from the API into state

### ISSUE THREAD

**Issue by watchinharrison** [cloudflare/terraform-provider-cloudflare#2787]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform: [1.4.7](https://releases.hashicorp.com/terraform/1.4.7/)
Cloudflare: [4.15.0](https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v4.15.0)

### Affected resource(s)

- cloudflare_list

### Terraform configuration files

```hcl
resource "cloudflare_list" "bulk_redirect" {
  account_id = var.account_id
  name       = "bulk_redirect"
  kind       = "redirect"

  lifecycle {
    ignore_changes = [item]
  }
}
```

### Link to debug output

https://gist.github.com/watchinharrison/e18b948e59e66558f8a9a9d690604285

### Expected output

I expect the lifecycle ignore changes for `[item]` to be respected and the list items are neither stored in state or considered changed when changes are made outside of Terraform.

### Actual output

The import retrieved all the items from the API, stored them in state and then subsequently fetched them from the API on all future plans, resulting in a 15min+ total time to plan existing changes.

### Steps to reproduce

1. Create a list in Cloudflare dashboard
2. Add 1 or more items to the list
3. Create the resource in terraform code (.tf file)
4. Use the latest Cloudflare provider version to import the resource into state `terraform import`
5. View the state file

### Additional factoids

This [change appears to have introduced the bug](https://github.com/cloudflare/terraform-provider-cloudflare/commit/a9ce5b7f7738e3fe6a4298ae47b4105c4f4700f7) which [conflicts with this line which](https://github.com/cloudflare/terraform-provider-cloudflare/blob/3892f43c69931ba0f5c88ba09f6d1949e8c706c2/internal/sdkv2provider/resource_cloudflare_list.go#L106) when respecting no changes to `item` and `item` is length 0.

Having tested both 4.15 and 4.14, I can confirm that 4.14 does not import all the items into state leaving the state with an empty `item: []` value.

**Comment by Nmishin** [comment]
Hi @watchinharrison  sorry that my change confused you :)
But it fixed behaviour that you exactly described: https://github.com/cloudflare/terraform-provider-cloudflare/issues/2573
In the versions before fix - import of `items` didn't work at all, independently from `ignore_changes` option.

Also, for `ignore_changes` - i checked behaviour for `cloudflare_list` and compared it with `cloudflare_access_application`. 
`ignore_changes` don't prevent storing something in state, it only prevent update resources if something changed manually via UI. 
@jacobbednarz correct me if i'm wrong.

**Comment by jacobbednarz** [comment]
per @Nmishin this seems correct behaviour given you are trying to import the list into Terraform.

> `ignore_changes` don't prevent storing something in state, it only prevent update resources if something changed manually via UI.

correct - it only impacts the `Update`/`Read` methods really.
