### ISSUE TITLE
Data Source for Notification Alert Types

### ISSUE THREAD

**Issue by trjstewart** [cloudflare/terraform-provider-cloudflare#2798]
### Current Terraform and Cloudflare provider version

1.5.7

### Description

It would be handy to be able to iterate over a data source when setting up notifications via Terraform.

https://developers.cloudflare.com/api/operations/notification-alert-types-get-alert-types

### Use cases

developer experience

### Potential Terraform configuration

```hcl
data "cloudflare_notification_alert_types" "default" {}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
