### ISSUE TITLE
Add support to retrieve ruleset ids to successfully import custom cloudflare_ruleset

### ISSUE THREAD

**Issue by jmartin-eezy** [cloudflare/terraform-provider-cloudflare#2804]
### Current Terraform and Cloudflare provider version

Terraform v1.4.6
Cloudflare v4.15.0

### Description

The following curl request only returns kind: managed/zone rulesets and never returns custom rulesets so it's impossible to get the ruleset id in order to import custom cloudflare_ruleset
curl --request GET \
  --url https://api.cloudflare.com/client/v4/accounts/zone_id/rulesets \
  --header 'Authorization: Bearer api_token' \
  --header 'Content-Type: application/json'

### Use cases

Unless we are able to obtain ruleset ids for kind: custom cloudflare_ruleset we are unable to import existing custom rulesets into terraform.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "videos" {
  account_id = local.account_id
  name       = "Videos"
  kind       = "custom"
  phase      = "http_request_firewall_custom"
  rules {
    action     = "log"
    expression = "(http.request.uri.path eq \"*.mov\" or http.request.uri.path eq \"*.mp4\")"
    enabled    = true
  }
}
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/2054/files this solves import for cloudflare_ruleset however it's currently not possible to retrieve ruleset ids for custom rulesets

**Comment by jacobbednarz** [comment]
have you tried using the `cloudflare_Ruleset` data source? https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/rulesets#filter

that has worked for me in the past to get any rule type.

**Comment by jmartin-eezy** [comment]
@jacobbednarz I created a few different data sources for various custom rules we have. They all return the same ruleset id and when I try to run a zone import for our cloudflare_ruleset.videos resource for example I get the following error: 
`│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "cloudflare_ruleset.videos", the provider detected that no object exists with the given id. Only pre-existing objects
│ can be imported; check that the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new
│ remote object for this resource.`

**Comment by jacobbednarz** [comment]
you don't import rules; you import the entire ruleset and the rules are a part of that.

**Comment by jacobbednarz** [comment]
closing this off as a misunderstanding of how the `cloudflare_ruleset` resource currently works. if you manage to find a bug or something missing, please open a new issue following the issue template.
