### ISSUE TITLE
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. 

### ISSUE THREAD

**Issue by rajendrapinnamaneni** [cloudflare/terraform-provider-cloudflare#2824]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.16.0
+ provider registry.terraform.io/hashicorp/azurerm v3.75.0

### Affected resource(s)

resource "cloudflare_ruleset" "cache_everything" 

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "cache_everything" {
  zone_id    = {zoneid}
  kind       = "zone"
  name       = "Cache Everything"
  phase      = "http_request_cache_settings"

  rules {
    action      = "set_cache_settings"

    expression  = "(http.host eq \"www.${domain}\" and not http.request.uri.path contains \"/web/\")"
    description = "Cache Everything"
    enabled     = true

    action_parameters {

      cache = true

      edge_ttl {
        mode    = "respect_origin"
      }
      serve_stale {
        disable_stale_while_updating = false
      }
    }
  }
}
```

### Link to debug output

Added debug output in zip file as https://gist.github.com/ is not be able to create a gist URL/unresponsive for longer times.
[debugoutput.zip](https://github.com/cloudflare/terraform-provider-cloudflare/files/12871893/debugoutput.zip)

### Panic output

Stack trace from the terraform-provider-cloudflare_v4.13.0 plugin:

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9996c0]

	goroutine 10746 [running]:
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.toRulesetResourceModel({0x130ada0, 0xc0021e5c80}, {0x80?, {0xc000946b80?, 0xc000946ac0?}}, {0x20?, {0x0?, 0x0?}}, {{0xc0005d951b, 0x20}, ...})
			github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:614 +0x3aa0
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets.(*RulesetResource).Read(0xc0004bc090, {0x130ada0, 0xc0021e5c80}, {{{{0x130f8a8, 0xc002028510}, {0xfcbf60, 0xc0011cd1a0}}, {0x13110e0, 0xc000a40e60}}, 0xc000632018, ...}, ...)
			github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/rulesets/resource.go:208 +0x57b
	github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00050e420, {0x130ada0, 0xc0021e5c80}, 0xc0021e5d10, 0xc001d35520)
			github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/fwserver/server_readresource.go:101 +0x677
	github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00050e420, {0x130ada0?, 0xc0021e5b30?}, 0xc002bd7f40)      
			github.com/hashicorp/terraform-plugin-framework@v1.3.5/internal/proto6server/server_readresource.go:55 +0x41a
	github.com/hashicorp/terraform-plugin-mux/tf6muxserver.muxServer.ReadResource({0xc0003402d0, 0xc000a1bbd0, 0xc000340300, 0xc000340330, {0xc0000abf40, 0x2, 
	0x2}}, {0x130ada0?, 0xc0021e5800?}, 0xc002bd7f40)
			github.com/hashicorp/terraform-plugin-mux@v0.11.2/tf6muxserver/mux_server_ReadResource.go:29 +0x139
	github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0003314a0, {0x130ada0?, 0xc0021e5050?}, 0xc000ba75c0)
			github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/tf6server/server.go:749 +0x4b1
	github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x10e53e0?, 0xc0003314a0}, {0x130ada0, 0xc0021e5050}, 0xc0002a4d90, 0x0)
			github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:386 +0x170
	google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000363c0, {0x130fbf8, 0xc000583ba0}, 0xc0021da6c0, 0xc0006ba150, 0x1997590, 0x0)
			google.golang.org/grpc@v1.56.1/server.go:1337 +0xdf3
	google.golang.org/grpc.(*Server).handleStream(0xc0000363c0, {0x130fbf8, 0xc000583ba0}, 0xc0021da6c0, 0x0)
			google.golang.org/grpc@v1.56.1/server.go:1714 +0xa36
	google.golang.org/grpc.(*Server).serveStreams.func1.1()
			google.golang.org/grpc@v1.56.1/server.go:959 +0x98
	created by google.golang.org/grpc.(*Server).serveStreams.func1
			google.golang.org/grpc@v1.56.1/server.go:957 +0x18c

	Error: The terraform-provider-cloudflare_v4.13.0 plugin crashed!

	This is always indicative of a bug within the plugin. It would be immensely
	helpful if you could report the crash with the plugin's maintainers so that it
	can be fixed. The output above should help diagnose the issue.

	2023-10-02T10:40:50.535+0100 [DEBUG] Azure Backend Response for https://mabgotfstateprodst001.blob.core.windows.net/mab-go-eun-prod-terraform-state/cloudflare-cdn.tfstate?comp=lease:
	HTTP/1.1 200 OK
	Content-Length: 0
	Date: Mon, 02 Oct 2023 09:40:52 GMT
	Etag: "0x8DBC32BAAE9CC73"
	Last-Modified: Mon, 02 Oct 2023 09:40:52 GMT
	Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
	X-Ms-Request-Id: 34ad54a0-701e-009b-2514-f54da7000000
	X-Ms-Version: 2018-11-09
	2023-10-02T10:40:50.535+0100 [DEBUG] provider: plugin exited

### Expected output

cloudflare_ruleset.cache_everything["<zoneid>"]: Refreshing state... [id=<id>]
cloudflare_ruleset.cache_everything["<zoneid>"]: Refreshing state... [id=<id>]

### Actual output

╷
		│ Error: Plugin did not respond
		│
		│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more        
		│ details.
		╵
		╷
		│ Error: Request cancelled
		│
		│ The plugin6.(*GRPCProvider).UpgradeResourceState request was cancelled.
	

### Steps to reproduce

We are getting issues while doing Terraform plan itself and even in Debug, couldn’t find helpful information.

### Additional factoids

we compared the current terraform state file to existing terraform configuration where I didn't find any mismatch.
Also we tried with the latest version v4.16.0 and still it didn't works.

**Comment by rajendrapinnamaneni** [comment]
> Thank you for reporting this issue! For maintainers to dig into issues it is required that all issues include the entirety of `TF_LOG=DEBUG` output to be provided. The only parts that should be redacted are your user credentials in the `X-Auth-Key`, `X-Auth-Email` and `Authorization` HTTP headers. Details such as zone or account identifiers are not considered sensitive but can be redacted if you are very cautious. This log file provides additional context from Terraform, the provider and the Cloudflare API that helps in debugging issues. Without it, maintainers are very limited in what they can do and may hamper diagnosis efforts.
> 
> This issue has been marked with `triage/needs-information` and is unlikely to receive maintainer attention until the log file is provided making this a complete bug report.

Added complete debug output in zip file without trim as https://gist.github.com/ is not able to create a gist url/unresponsive for longer times.

**Comment by jacobbednarz** [comment]
thanks for the issue! however, the reproduction case you've provided works as expected for me.

```
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_ruleset.cache_everything will be created
  + resource "cloudflare_ruleset" "cache_everything" {
      + description = (known after apply)
      + id          = (known after apply)
      + kind        = "zone"
      + name        = "Cache Everything"
      + phase       = "http_request_cache_settings"
      + zone_id     = "0da42c8d2132a9ddaf714f9e7c920711"

      + rules {
          + action       = "set_cache_settings"
          + description  = "Cache Everything"
          + enabled      = true
          + expression   = "true"
          + id           = (known after apply)
          + last_updated = (known after apply)
          + ref          = (known after apply)
          + version      = (known after apply)

          + action_parameters {
              + cache   = true
              + version = (known after apply)

              + edge_ttl {
                  + mode = "respect_origin"
                }

              + serve_stale {
                  + disable_stale_while_updating = false
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_ruleset.cache_everything: Creating...
cloudflare_ruleset.cache_everything: Creation complete after 2s [id=6814f0df637c43b5bd2372dbc68f47fb]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

have you manually modified your state file? have you made any other possibly impacting changes? have you attempted to jump back and forth between versions? if all else fails, you may need to remove the resource from your state file and reimport to get it working as it was.

**Comment by tibbing** [comment]
> hey @ tibbing, yeah i also downgraded to 4.34 in my case was the latest available patch I could get to work

Perhaps you have a different issue, but for me it worked to remove the resource from the state and recreate it in the latest version of the provider (or import it if possible, but the cloudflare_zone_settings_override can't be imported). The stack trace might give you some hints to narrow down which resource causes the problem.
