### ISSUE TITLE
Support for cloudflare_notification_policies  of type "Traffic Anomalies" and "Cloudflare Incident Alert"

### ISSUE THREAD

**Issue by r-kok** [cloudflare/terraform-provider-cloudflare#2840]
### Current Terraform and Cloudflare provider version

Terraform v1.5.7
provider 4.16

### Description

The 4.16 version of the provider supports the **cloudflare_notification_policy** resources.
However notification types **Traffic-Anomalies** and **Cloudflare Incident Alert** do not work properly, yet.
The request is to support these as well.

### Use cases

Make notifications of all types terraform-managed.

Currently, we can create and edit all notification types in the Cloudflare dashboard,
and we can import some resources into terraform but not all:

When I try to import to resources:

```
import {
  to = cloudflare_notification_policy.Traffic-Anomalies
  id = "REDACTED_ACCOUNT_ID/REDACTED_POLICY_ID"
}

import {
  to = cloudflare_notification_policy.Cloudflare-Incident-Alert
  id = "REDACTED_ACCOUNT_ID/REDACTED_POLICY_ID"
  }
  
 Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: failed to set filters: Invalid address to set: []string{"filters", "0", "incident_impact"}
│
│ Error: failed to set filters: Invalid address to set: []string{"filters", "0", "selectors"}
```

### Potential Terraform configuration

```hcl
...
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/2759

**Comment by bporter816** [comment]
To resolve this, would we also need support for `traffic_anomalies_alert` type? This still seems to be unimplemented.
