### ISSUE TITLE
Certificate Transparency Monitoring Not Available within Terraform

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [cloudflare/terraform-provider-cloudflare#2842]
### Current Terraform and Cloudflare provider version

```
Terraform v1.5.7
on darwin_arm64
```

- [CloudFlare 4.16.0](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs)

### Description

- CloudFlare [Certificate Transparency Monitoring](https://developers.cloudflare.com/ssl/edge-certificates/additional-options/certificate-transparency-monitoring/) is not currently available within Terraform and is a UI-based feature (toggle) per-top-level-domain (I.E `acme.org`/`acme.com`)

### Use cases

- When deploying a new CloudFlare zone, it is common practice to enable CT monitoring 

### Potential Terraform configuration

- `zone.tf` example:

```
resource "cloudflare_zone" "acme_org" {
  account_id = var.account_id
  paused     = "false"
  plan       = "pro"
  type       = "full"
  zone       = var.acme_org_zone_name
  ct_monitoring  = <true|false> <-------
}
```

### References

NA

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
