### ISSUE TITLE
cloudflare_custom_hostname fails plan after initial apply

### ISSUE THREAD

**Issue by ebuna** [cloudflare/terraform-provider-cloudflare#2860]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.0.11
on linux_amd64

+ provider registry.terraform.io/cloudflare/cloudflare v4.17.0
+ provider registry.terraform.io/hashicorp/azurerm v3.76.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.12.8

### Affected resource(s)

* cloudflare_custom_hostname

### Terraform configuration files

```hcl
resource "cloudflare_custom_hostname" "custom_hostname" {
    zone_id              = var.zone_id
    hostname             = "my-custom-hostname.mydomain.org"
    custom_origin_server = "my-origin-server.mydomain.org"

    # Required but listed as optional
    wait_for_ssl_pending_validation = false
    custom_origin_sni               = ""
    custom_metadata                 = null

    ssl {
        bundle_method         = "ubiquitous"
        certificate_authority = "google"
        method                = "txt"
        type                  = "dv"
        wildcard              = false

        # Required but listed as optional
        custom_certificate    = ""
        custom_key            = ""
        
        settings {
            min_tls_version = "1.2"
            early_hints     = "on"
            http2           = "on"
            tls13           = "on"
        }
    }

    lifecycle {
        ignore_changes = [
            custom_metadata,
            custom_origin_sni,
            ssl[0].settings[0].ciphers,
        ]
    }
}
```

### Link to debug output

https://gist.github.com/ebuna/5f4c9b9f23d45ca03234c84299c662b7

### Panic output

N/A

### Expected output

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

### Actual output

 Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for
│ module.test_custom_hostnames.cloudflare_custom_hostname.custom_domains["my-custom-hostname.mydomain.org"].custom_metadata: planned value cty.NullVal(cty.Map(cty.String)) does not match config value
│ cty.MapValEmpty(cty.String).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to reproduce

1. Create a cloudflare_custom_hostname resource using the example
2. terraform apply (if it didn't already exist, this will succeed)
3. terraform apply again (fails here)

### Additional factoids

This occurs when the `cloudflare_custom_hostname` resource has already been provisioned by terraform and then you try to apply/plan again. I have tried ignoring the `custom_metadata` attribute, but the issue still occurs.

**Comment by ebuna** [comment]
I should also add that I've tried omitting the `custom_metadata` attribute, setting it to `{}`, and as in the example, setting it to `null`. None of these have addressed the issue.

**Comment by jacobbednarz** [comment]
`custom_metadata = null` is not a valid value as the schema type is [`TypeMap`](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/schema_cloudflare_custom_hostname.go#L145). if you are not using value you shouldn't be setting it at all.

**Comment by ebuna** [comment]
The same error occurs even when those attributes are removed. In fact, it fails even on the first run if the `custom_certificate` and `custom_key` are not set. Not sure why this was closed, the resource does not work.

**Comment by ebuna** [comment]
@jacobbednarz you also explicitly asked for empty strings for some of the optional values... Have you tried reproducing this?

> can you provide an example of this issue (and the debug logs) without using modules and setting empty strings for some of the optional values?

**Comment by jacobbednarz** [comment]
> The same error occurs even when those attributes are removed. In fact, it fails even on the first run if the custom_certificate and custom_key are not set. Not sure why this was closed, the resource does not work. 

the error message (and logs) you've provided are related to incorrect types being set for the `custom_metadata` field. `TypeMap` from the Terraform internals is unfortunately very poor at validating keys by design. if you've reused the same state file after you've attempted this with bad values, it's not going to self resolve, you'll need to start fresh.

if you're hitting other issues, they were not mentioned here so there isn't anyway for me to know what else is broken. you've also

> @jacobbednarz you also explicitly asked for empty strings for some of the optional values... Have you tried reproducing this?

no sorry, there is a misunderstanding there -- your example had empty strings (which you shouldn't since they are values) alongside dynamics. my ask was to do it without to limit the potential issues.

yes i did run your reproduction test case. in addition to your reproduction case, i've run the [test suite for custom hostnames](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/resource_cloudflare_custom_hostname_test.go) and all of them are passing so the resource is indeed working for the majority of use cases.

**Comment by ebuna** [comment]
Which strings do you want me to omit? Here is the output using the exact example listed in the documentation for this resource: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/custom_hostname

```
Acquiring state lock. This may take a few moments...
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for cloudflare_custom_hostname.example.wait_for_ssl_pending_validation: planned value cty.False for a non-computed
│ attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for cloudflare_custom_hostname.example.ssl[0].type: planned value cty.StringVal("dv") for a non-computed attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for cloudflare_custom_hostname.example.ssl[0].settings: attribute representing nested block must not be unknown itself;
│ set nested attribute values to unknown instead.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```

and for reference, the example usage resource definition:
```hcl
resource "cloudflare_custom_hostname" "example" {
  zone_id  = "removed"
  hostname = "test15.ebuna.org"
  ssl {
    method = "txt"
  }
}
```

If there is a specific config you want me to try running I am happy to do so, but so far I have not found any variation of configuration that works for this resource on a consistent basis.

**Comment by ebuna** [comment]
And here is the same resource config that I initially submitted, with the empty strings removed:

```
Acquiring state lock. This may take a few moments...
╷
│ Error: Provider produced invalid plan
│
│ Provider "registry.terraform.io/cloudflare/cloudflare" planned an invalid value for cloudflare_custom_hostname.example2.wait_for_ssl_pending_validation: planned value cty.False for a non-computed
│ attribute.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```

and the resource:
```hcl
resource "cloudflare_custom_hostname" "example2" {

    zone_id              = "removed"
    hostname             = "test16.ebuna.org"
    custom_origin_server = "prd-tnz-web.clubspark.pro"

    ssl {
        bundle_method         = "ubiquitous"
        certificate_authority = "google"
        method                = "txt"
        type                  = "dv"
        wildcard              = false
        
        settings {
            min_tls_version = "1.2"
            early_hints     = "on"
            http2           = "on"
            tls13           = "on"
        }
    }
}
```

Both the `example` and `example2` resource were tested in a new workspace that is clean, so these errors are from the first attempt.

**Comment by ebuna** [comment]
Using `example2`, I added the `wait_for_ssl_pending_validation` config and set it to `false` (which again, it is listed as optional in the documentation and says it defaults to `false` anyway). When doing this, it will plan successfully, but then when you apply:

```
cloudflare_custom_hostname.example2: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to cloudflare_custom_hostname.example2, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .custom_origin_sni: was null, but now
│ cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to cloudflare_custom_hostname.example2, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .ssl[0].custom_certificate: was null,
│ but now cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to cloudflare_custom_hostname.example2, provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .ssl[0].custom_key: was null, but now
│ cty.StringVal("").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
Releasing state lock. This may take a few moments...
```
