### ISSUE TITLE
HTTP/2 to Origin option missing in Terraform Provider

### ISSUE THREAD

**Issue by kacper-kucharski** [cloudflare/terraform-provider-cloudflare#2861]
### Current Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.6.1
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.17.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

### Description

Hi,

I currently trying to terraform an existing cloudflare zone into terraform code. However I noticed that I couldn't find an option to turn off "HTTP/2 to Origin" through [cloudflare_zone_settings_override](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override) 

### Use cases

Every option should be available to be turned off using terraform. Perhaps I am looking in the wrong resource, but there does not seem to be an option to turn off that setting with the use of you terraform provider.

### Potential Terraform configuration

```hcl
...
resource "cloudflare_zone_settings_override" "main" {
  zone_id = var.zone_id
  settings {
    http2_to_origin = "off"
  }
}

```

**Comment by daniel-gut** [comment]
It seems this is already possible via `origin_max_http_version`.

**Comment by kacper-kucharski** [comment]
> It seems this is already possible via `origin_max_http_version` with values `1` or `2`. Naming seems a bit unfortunate. [Docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override) for reference

This seem to indeed be the attribute I needed. Thank you for pointing it out for me.

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/32353483/ee41fec8-1085-45fa-adf0-d24079b0253a)

I still feel like this could be improved on, especially since the dashboard has a toggle and "1" or "2" doesn't really explain if this option should be turned on or off. Unless is just the way I see it...

**Comment by jacobbednarz** [comment]
the background here is that UI toggle used to be a dropdown with "1" and "2" as the values which is what got added to the provider. as the UI has evolved, it hasn't considered the ramifications of the downstream consumers like terraform that have long stored states and can't quickly change these things without breaking customers.

i'll add some feedback internally but for now, the solution is to use `origin_max_http_version = "1"` to achieve the same thing as the UI does today.
