### ISSUE TITLE
cloudflare_zone_settings_override http2 = "off" says that it cannot be set as it is read only

### ISSUE THREAD

**Issue by kacper-kucharski** [cloudflare/terraform-provider-cloudflare#2862]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.6.1
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.16.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

### Affected resource(s)

cloudflare_zone_settings_override

### Terraform configuration files

```hcl
resource "cloudflare_zone_settings_override" "main" {
  zone_id = var.zone_id
  settings {
    development_mode = "on"
    always_use_https = "on"
    security_header {
      enabled            = true
      include_subdomains = true
      max_age            = 31536000
      nosniff            = true
      preload            = false
    }
    ssl = "full"
    min_tls_version = "1.2"
    opportunistic_encryption = "off"
    tls_1_3 = "on"
    automatic_https_rewrites = "on"
    security_level = "medium"
    challenge_ttl = 1800
    browser_check = "on"
    http2 = "on"
    http3 = "off"
    brotli            = "on"
    browser_cache_ttl = 0
  }
}
```

### Link to debug output

https://gist.github.com/kacper-kucharski/e66ab76e24f2821b9036ae16cb46095c

### Panic output

module.zone_settings_override.cloudflare_zone_settings_override.main: Modifying... [id=]
╷
│ Error: invalid zone setting "http2" (value: off) found - cannot be set as it is read only
│
│   with module.zone_settings_override.cloudflare_zone_settings_override.main,
│   on modules\zone_settings_override\zone_settings.tf line 1, in resource "cloudflare_zone_settings_override" "main":
│    1: resource "cloudflare_zone_settings_override" "main" {
│
╵

### Expected output

I expected the http2 to be changed, yesterday I was able to do that without any issue.

### Actual output

It now says that http2 cannot be set as it is read only. I am using the same API token that I was using yesterday that has edit right to Zone, Zone Settings and Config Rules.

### Steps to reproduce

1. Create the cloudflare_zone_settings_override resource
2. Add the http2 = "off" or "on" in the settings block
3. run terraform apply

**Comment by jacobbednarz** [comment]
👋 thanks for raising this issue!

i've attempted to reproduce this one but it is working as expected for me. are you able to provide a reproduction case without using modules? i suspect that has something to do with the difference in behaviour here.

**Comment by kacper-kucharski** [comment]
> 👋 thanks for raising this issue!
> 
> i've attempted to reproduce this one but it is working as expected for me. are you able to provide a reproduction case without using modules? i suspect that has something to do with the difference in behaviour here.

I've destroyed all other resources, took the zone_settings_override out of a module and put it in a zone_settings.tf file in root folder. When I run `terraform apply` the cloudflare_zone_settings_override is the only resource being applied and I still get the same error. I am also actively trying to figure what I am doing wrong, but like I said. The resource was in a module before and was working fine, another day I try to run apply and get this error out of nowhere. Could there be a setting that could lead to the http2 becoming read-only? Or other resources that collide with it?

I hope we can figure this out together!

**Comment by kacper-kucharski** [comment]
Sorry, I've just went to the dashboard and noticed that the HTTP/2 is now read-only on the cloudflare dashboard aswell as I cannot switch it off. I assume that is the reason for it not working? 

If that is the case when will it be available?

I am working with free plan on this zone could that be the case? My other project that is Enterprise plan does still have the toggle to switch the HTTP/2 on or off.

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/32353483/2bef4eca-0cbe-4787-9b00-5348be4b4170)
