### ISSUE TITLE
cloudflare_access_organization forces optional session_duration to be set due to default value

### ISSUE THREAD

**Issue by james-devincentis-mfp** [cloudflare/terraform-provider-cloudflare#2865]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.17.0

### Affected resource(s)

cloudflare_access_organization

### Terraform configuration files

```hcl
resource "cloudflare_access_organization" "test" {
  account_id       = "[REDACTED]"
  auth_domain      = "[REDACTED]"
  name             = "[REDACTED]"
  session_duration = null
  custom_pages {}
  login_design {
    background_color = "#0066EE"
    logo_path        = "[REDACTED]"
  }
}
```

### Link to debug output

```
Terraform will perform the following actions:

  # cloudflare_access_organization.test will be updated in-place
  ~ resource "cloudflare_access_organization" "test" {
        id                        = "[REDACTED]"
        name                      = "[REDACTED]"
      + session_duration          = "24h"
        # (4 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected output

https://developers.cloudflare.com/api/operations/zero-trust-organization-update-your-zero-trust-organization

session_duration to not be required to be set. No default is defined in CF documentation

### Actual output

session_duration is requiring to be set

### Steps to reproduce

1. set session duration in cloudflare access organization to be 'Same as application session timeout'
2. import existing cloudflare_access_organization resource
3. align terraform code with imported resource
4. run terraform plan
5. observe a requirement to always update the resource with the session_duration

**Comment by james-devincentis-mfp** [comment]
https://developers.cloudflare.com/api/operations/zero-trust-organization-update-your-zero-trust-organization shows no default

https://github.com/cloudflare/terraform-provider-cloudflare/blame/master/internal/sdkv2provider/resource_cloudflare_access_organization.go#L37

That line was likely copied from elsewhere and accidentally included the default.

**Comment by james-devincentis-mfp** [comment]
Not sure if this adds some additional context but the behavior when making requests from the UI is to omit the session_duration entirely when set to 'Same as application session timeout' at the org level.  So there is a functional difference between the 'Same as application session timeout' meaning at the org level from usages elsewhere (like access application policies where it clones the value in the API request)

**Comment by scluff** [comment]
Similar story for application policies - the default is unset and inherits the application value. After updating to v4.17.0, the provider explicitly sets the policy session_duration to 24h, which may not match what is configured for the application. There also seems to be some inconsistency in the API schema - session_duration isn't shown for zone level access policies at all.

**Comment by mshi-sq** [comment]
Hi, ditto @scluff. Seeing the same issue with `cloudflare_access_policy`. After upgrading to v4.19 from v4.11, the default session_duration is now set to `24h` instead of `Same as application session timeout`. There also does not seem to be a way for session_duration to be set to the value of `Same as application session timeout`.
