### ISSUE TITLE
Adopt import-only resources

### ISSUE THREAD

**Issue by sidekick-eimantas** [cloudflare/terraform-provider-cloudflare#2875]
### Current Terraform and Cloudflare provider version

4.17.0

### Description

Just setting up a cf deployment for the first time and some of the resources like `cloudflare_access_organization` that are import only are a bit of a PITA to deal with. It would be great if this provider could adopt the resources in question at apply time so import is not required.
See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy_default_target_group for example

### Use cases

Easier to set up initial cf deployment

### Potential Terraform configuration

```hcl
...
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_proxy_default_target_group
https://registry.terraform.io/providers/hashicorp/aws/3.9.0/docs/resources/default_network_acl
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_route_table

**Comment by jacobbednarz** [comment]
thanks for the issue! unfortunately, this isn't something we're interested in replicating or solving in the provider design itself. as an alternative, you can use cf-terraforming or manually import the resources using the inbuilt primitives.

**Comment by jacobbednarz** [comment]
interesting in what way? it has nothing to do with selling services or gauging interest. the pattern used by those "import only" resources is not something that exists in Cloudflare so there is no reason why we would replicate it or include it as part of the provider. 

all resources in the provider can be edited and maintained (including access organizations). it is up to the user to determine which resources they manage and by which integration. 

if you want to get the state of resources that were created automatically on your behalf (such as access organization), you can either manually import the resource with the default configuration from the API or use cf-terraforming to do it for you.
