### ISSUE TITLE
Add `rules` to `cloudflare_waiting_room`

### ISSUE THREAD

**Issue by vojkny** [cloudflare/terraform-provider-cloudflare#2885]
### Current Terraform and Cloudflare provider version

Terraform v1.5.2
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.17.0

### Description

`cloudflare_waiting_room` is missing `rules` section.

### Use cases

General requirement for missing feature of waiting room rules.

### Potential Terraform configuration

```hcl
resource "cloudflare_waiting_room" "main_waiting_room" {
   ...
   rules {
      …
   }
}
```

**Comment by broswen** [comment]
You can configure Cloudflare Waiting Room Rules with a separate resource and bind them to your waiting room with the ID.
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/waiting_room_rules

**Comment by vojkny** [comment]
👍 thanks, closing.
