### ISSUE TITLE
Enable the default route for cloudflare workers

### ISSUE THREAD

**Issue by pksunkara** [cloudflare/terraform-provider-cloudflare#2892]
### Current Terraform and Cloudflare provider version

Cloudflare provider: v4.4.0

### Description

When I create a worker using `cloudflare_worker_script`, the default route created at `{name}.{org}.workers.dev` is not enabled.

And there's no way of enabling that default route in terraform.

### Use cases

Would like to use that default route after enabling it. But there's no way of doing through terraform

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "my_script" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "script_1"
  content    = file("script.js")
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by pksunkara** [comment]
> This issue has been closed as we are now tracking this internally with service teams directly.

What do you mean? I thought this was a terraform issue?
