### ISSUE TITLE
Cloudflare_ruleset - http_ratelimit - mitigation_timeout missing

### ISSUE THREAD

**Issue by ThomasAusweger** [cloudflare/terraform-provider-cloudflare#2914]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

cloudflare/cloudflare v4.18.0 

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "firewall_ratelimit" {
  kind    = "zone"
  name    = "default"
  phase   = "http_ratelimit"
  zone_id = var.zone_id

  rules {
    description  = "log_adv_ratelimit"
    expression   = "***********"
    action       = "managed_challenge"
    enabled      = true
    ratelimit {
      characteristics     = ["ip.src", "cf.colo.id"]
      period              = 60
      requests_per_period = 600
      requests_to_origin  = false
    }
  }
}
```

### Link to debug output

-

### Panic output

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.****.cloudflare_ruleset.firewall_ratelimit, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[0].ratelimit[0].mitigation_timeout: was null,
│ but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Expected output

No error

### Actual output

terraform apply reported error

### Steps to reproduce

1. Update to v4.18.0
2. Add cloudflare_ruleset for http_ratelimit with managed_challenge
3. No mitigation_timeout needed for managed_challenge in v4.17.0

### References

https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#4180-1st-november-2023

**Comment by vences** [comment]
Hey @ThomasAusweger,

I think you need to explicitly set `mitigation_timeout = 0` if you want to have the throttle action (as per the doc [here](https://developers.cloudflare.com/waf/rate-limiting-rules/parameters/#for-duration)). If you do not want that behaviour you will need to select the mitigation time allow as per your plan (doc [here](https://developers.cloudflare.com/waf/rate-limiting-rules/#availability)).

Could you please let me know if having explicitly set `mitigation_timeout`, solved your issue? If so I think that field would need to be set as required. 
 
Hope that helps,
