### ISSUE TITLE
Ability to create cloudflare_tunnel_config with warp_routing enabled.

### ISSUE THREAD

**Issue by dmitriydvoryanchuk-chime** [cloudflare/terraform-provider-cloudflare#2916]
### Current Terraform and Cloudflare provider version

Terraform: 1.5.2
Provider: 4.18.0

### Description

We are attempting to create a `cloudflare_tunnel` and corresponding `cloudflare_tunnel_config` to allow our WARP clients access to private networks specified in the routes for that tunnel.  When the tunnel is created in the UI/dashboard, it is automatically configured as:

`        "config": {
            "warp-routing": {
                "enabled": true
            }
        },
        "source": "cloudflare"`

However, the provider is expecting an `ingress_rule` block as _required_ when creating a `cloudflare_tunnel_config` resource [per documentation here](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/tunnel_config#nested-schema-for-config).  Creating a tunnel config with this parameter causes `warp_routing` config to flip to false, which would break connectivity.

Running an import only imports the above config: ingress_rule is ignored.

This also means we can't create a `cloudflare_tunnel` resource, because without the accompanying `cloudflare_tunnel_config` resource, `warp_routing` is also set as false by default.

### Use cases

The use case is being able to manage WARP-enabled cloudfalred tunnel resources via TF.

### Potential Terraform configuration

```hcl
resource "cloudflare_tunnel_config" "aws_vpc_it_prod" {
  account_id = "id"
  tunnel_id  = cloudflare_tunnel.aws_vpc_it_prod.id
  config {
    warp_routing {
      enabled = true
    }
}
```

**Comment by jacobbednarz** [comment]
this seems to be a bug; can you please open a bug issue with the requested information to have this triaged by the service team?
