### ISSUE TITLE
Add resources to manage Zero Trust Connectivity Settings

### ISSUE THREAD

**Issue by F21** [cloudflare/terraform-provider-cloudflare#2932]
### Current Terraform and Cloudflare provider version

Terraform v1.6.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.18.0

### Description

Add resources to manage Zero Trust Connectivity Settingsto manage ICMP proxying and Warp-To-Warp (offramp_warp_enabled) settings

### Use cases

This resource will allow us to manage ICMP proxying and Warp-To-Warp using terraform. Not sure if this should be its own resource or be part of an existing resource. 

### Potential Terraform configuration

```hcl
resource "zero_trust_connectivity_settings" "organization" {
  icmp_proxy_enabled = true
  offram_warp_enabled = true
}
```

### References

https://developers.cloudflare.com/api/operations/zero-trust-accounts-patch-connectivity-settings

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
