### ISSUE TITLE
Resource cloudflare_ruleset can't set cache ttl to 0

### ISSUE THREAD

**Issue by avegao** [cloudflare/terraform-provider-cloudflare#2933]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.18.0
+ provider registry.terraform.io/hashicorp/tls v4.0.4

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "cache" {
  # ...

  rules {
    description = "Cache settings"
    action      = "set_cache_settings"

    expression = "..."
    
    action_parameters {
      cache = true
      origin_error_page_passthru = false
      respect_strong_etags = false
      
      browser_ttl {
        mode = "override_origin"
        default = 0 # or not set
      }
      
      edge_ttl {
        mode = "override_origin"
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/avegao/86b5497cd7dab6ed892ed14bbc197a19

### Expected output

successful exit being able to set `default = 0`

### Actual output

```
╷
│ Error: invalid configuration
│
│   with cloudflare_ruleset.cache,
│   on cache.tf line 51, in resource "cloudflare_ruleset" "cache":
│   51:       browser_ttl {
│
│ using mode 'override_origin' requires setting a default for ttl
╵
╷
│ Error: Invalid Attribute Value
│
│   with cloudflare_ruleset.cache,
│   on cache.tf line 53, in resource "cloudflare_ruleset" "cache":
│   53:         default = 0
│
│ Attribute rules[1].action_parameters[0].browser_ttl[0].default value must
│ be at least 1, got: 0
╵
```

### Steps to reproduce

1. Write a ruleset in phase `http_request_cache_settings` with `browser_ttl` or `edge_ttl` and with `default = 0` or not set 
2. Apply or plan

### References

I think that #2800 is related

**Comment by avegao** [comment]
For more information, Cloudflare API returns `"default": 0`

```json
{
    "action": "set_cache_settings",
    "action_parameters": {
        "browser_ttl": {
            "default": 0,
            "mode": "override_origin"
        },
        "cache": true,
        "edge_ttl": {
            "default": 16070400,
            "mode": "override_origin"
        },
        "origin_error_page_passthru": false,
        "respect_strong_etags": false
    },
    "description": "SDK CDN",
    "enabled": true,
    "expression": "REDACTED",
    "id": "REDACTED",
    "last_updated": "2023-10-16T16:34:36.556298Z",
    "ref": "REDACTED",
    "version": "3"
}
```

**Comment by jacobbednarz** [comment]
this is expected behavior. a `browser_ttl` value of 0 in the API is a special value that means pass through the cache control from the origin. setting the mode to "override_origin" with a default of 0 doesn't make sense because it means both override the origin and respect the origin. if the intent is to respect the origin's cache control then set mode to "respect_origin".

**Comment by avegao** [comment]
@jacobbednarz I don't agree with what you say, because then it is impossible to configure from Terraform that you don't want it to cache. Now as a patch I have to set it to cache for 1 second, but because of this problem.

In Cloudflare Dashboard you can configure it, like I say:

![CleanShot 2023-11-21 at 17 17 24](https://github.com/cloudflare/terraform-provider-cloudflare/assets/560141/04e8e294-42e6-4632-a222-84cdec60182b)

**Comment by jacobbednarz** [comment]
the UI is incorrect; "no cache" is the doing the same setting as respect origin TTL. there is an internal ticket to address this.
