### ISSUE TITLE
Add a `default_tags` map to the provider and thus not require `tags` on every resource that support tags.

### ISSUE THREAD

**Issue by rquadling** [cloudflare/terraform-provider-cloudflare#2959]
### Current Terraform and Cloudflare provider version

```
$ terraform -v
Terraform v1.6.3
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.19.0
+ provider registry.terraform.io/hashicorp/archive v2.4.0
+ provider registry.terraform.io/hashicorp/aws v4.67.0
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Description

Currently, the Cloudflare provider does not have a way to have a map of tags defined once and used many times on all the resources.

This is something the AWS provider has and makes a LOT of sense.

It means, consumers of the provider isn't needing to keep track of resources that have tags being added to by the provider.

I understand that the developers of the provider will need to know (someone does I guess), but from the consumer perspective, we just set the map once and it's done.

### Use cases

Simplify tag management across multiple resources.

### Potential Terraform configuration

```hcl
provider "cloudflare" {
  default_tags = local.map_of_tags_for_all_supporting_resources
}
```

### References

Current Cloudflare documentation on the Cloudflare provider : https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#optional (no mention of `tag`).
Current AWS documentation on the AWS provider : https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags (`default_tags`).

**Comment by jacobbednarz** [comment]
thanks but this isn't something all services have support for so it's not something we'll see in the provider. 

if this ever becomes a cloudflare wide thing, we can re-evaluate it.
