### ISSUE TITLE
Have terraform set the CPU limit for workers and pages

### ISSUE THREAD

**Issue by deadlynjdj** [cloudflare/terraform-provider-cloudflare#2965]
### Current Terraform and Cloudflare provider version

Terraform v1.2.9
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.19.0
+ provider registry.terraform.io/dopplerhq/doppler v1.3.0

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html

### Description

Add the ability for terraform to set the cpu_ms value in workers or pages that use Workers Standard Usage Model

### Use cases

To set the limit of the CPU compute time 

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "worker-test" {
  account_id = "123456789abcd"
  name       = "worker-test"
  content    = file("src/worker.js")
    cpu_ms = 10
}
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/2949
https://github.com/cloudflare/terraform-provider-cloudflare/pull/2963

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
