### ISSUE TITLE
Error: no schema available for cloudflare_ip_list while reading state

### ISSUE THREAD

**Issue by jogarao96** [cloudflare/terraform-provider-cloudflare#2979]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.3
on linux_amd64

### Affected resource(s)

cloudflare_ip_list

### Terraform configuration files

```hcl
resource "cloudflare_list" "xyz_allowlist" {
  account_id  = local.account_id
  name        = "xyz_allowlist"
  kind        = "ip"
  description = "List of ips allowed xyz sites"

  dynamic "item" {
    for_each = local.xyz_allowlist
     content {
      value {
        ip = item.key
      }
    }
  }
}
```

### Link to debug output

https://gist.github.com/jogarao96/21b24e50c3647818ef0413a919692050

### Expected output

it should read state file and according to update guide updated all cloudflare_ip_list to cloudflare_list which is not recognized by terraform in the given specific version

### Actual output

The ip lists has to be updated with new name from cloudflare_ip_list to just cloudflare_list

### Steps to reproduce

while updating from cloudflare from 3.x to 4.x version it is unable to update cloud flare ip lists

terraform init
terraform validate
terraform plan

### References

https://github.com/hashicorp/terraform/issues/34307

**Comment by Cyb3r-Jak3** [comment]
IP list was removed in favor of `cloudflare_list` (https://github.com/cloudflare/terraform-provider-cloudflare/pull/2137). You should be able to move state in the v3 provider to `cloudflare_list` then upgrade to the v4 version.
