### ISSUE TITLE
cloudflare_split_tunnel documentation for "tunnels" block is missing

### ISSUE THREAD

**Issue by ikegentz** [cloudflare/terraform-provider-cloudflare#2981]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform: 1.4.6
cloudflare:4.10.10

### Affected resource(s)

cloudflare_split_tunnel

### Terraform configuration files

```hcl
resource "cloudflare_split_tunnel" "proxy_for_private_ips" {
  account_id  = local.cloudflare_account_id
  policy_id = cloudflare_device_settings_policy.rvshare_employee_warp_policy.id
  mode = "exclude"
  tunnels {
    # only have the examples to go off of
  }
}
```

### Link to debug output

N/A

### Expected output

The link for the nested schema: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/split_tunnel#nestedblock--tunnels would show the spec

### Actual output

There's no spec, the link just goes to the bottom of the page

### Steps to reproduce

1. Go to the reference page for split tunnel: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/split_tunnel
2. Click on "see below for nested schema" for the `tunnel` attribute
3. There's no schema documented

**Comment by jacobbednarz** [comment]
registry documentation looks correct to me?

![ua398sCJ-GP2nevqM-mjqaxIJ0](https://github.com/cloudflare/terraform-provider-cloudflare/assets/283234/d8a38689-d214-47cc-8f46-24c7e8ce8d9a)

**Comment by ikegentz** [comment]
Hm, sure enough I'm seeing it now. Not sure what was up with it but glad it's resolved!
