### ISSUE TITLE
Cloudflare - Provide Log Push Ownership Challenge for other backend providers

### ISSUE THREAD

**Issue by LukeDCDS** [cloudflare/terraform-provider-cloudflare#2982]
### Current Terraform and Cloudflare provider version

4.19.0

### Description

Log Push Ownership seems to only support AWS S3 Configuration. We need use for 

### Use cases

Well it'll be the same as using it for AWS S3 but in Azure's context. Or other Cloud providers if necessary, this will provide flexibility for configuring Log Push.

We need the ability to configure log push with Terraform from cloudflare and Azure. However, this feature is only native to Amazon S3. At the moment, we have been using a workaround outside of terraform which is proving time consuming. This is also not provided in the documentation: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge

### Potential Terraform configuration

```hcl
resource "cloudflare_logpush_ownership_challenge" "example" {
  zone_id          = "your_zone_id_here"
  destination_conf = "azure://${azurerm_storage_account.example.name}.blob.core.windows.net/${azurerm_storage_container.example.name}?<your_SAS_token>"
}
...
```

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/logpush_ownership_challenge

**Comment by jacobbednarz** [comment]
azure is already supported when you use the correct destination configuration - https://developers.cloudflare.com/logs/get-started/api-configuration/#destination. the registry documentation intentionally does not include kitchen sink examples so to understand the workings of the service, you need to use the developer documentation.

**Comment by LukeDCDS** [comment]
Sorry Jacob, just saw this. This is perfect thanks!
