### ISSUE TITLE
Previously closed issue #1163 is not solved or fixed

### ISSUE THREAD

**Issue by linxcat** [cloudflare/terraform-provider-cloudflare#2985]
### Confirmation

- [ ] My issue isn't already found on the issue tracker.
- [ ] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.3.9
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "deployment_dns" {
  zone_id  = "*************"
  name     = each.key
  value    = data.kubernetes_ingress_v1.istio_gateway.status.0.load_balancer.0.ingress.0.hostname
  type     = "CNAME"
  ttl      = 1
  proxied  = false
```

### Link to debug output

https://www.youtube.com/watch?v=gvdf5n-zI14

### Panic output

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.cloudflare_dns.cloudflare_record.deployment_dns["dev-int-dashboard"] to include
│ new values learned so far during apply, provider "registry.terraform.io/cloudflare/cloudflare" produced an invalid
│ new value for .allow_overwrite: was cty.False, but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected output

There should have been no error, I didn't change any of my DNS resource definitions from a working state, the API changed underneath me.

### Actual output

no changes are performed on the resource, but every one of them fails with the above error, and new changes are not possible because the error short-circuits.

### Steps to reproduce

1. Create an arbitrary DNS resource as defined above
2. Modify a parent resource that would cause it to be modified or recreated
3. diff will show the change `      + allow_overwrite = false`

### Additional factoids

Error is only produced where there are other state changes to make. If the cloudflare error is the only resource, no error presents.
I lied about my issue not being in the tracker, because I had to. You closed it, and I have to check the box. Comments on that other issue apparently mean nothing.

### References

#1163

**Comment by jacobbednarz** [comment]
please upgrade to a supported version and if you can still replicate without dynamics (modules, expressions, loops, etc), then feel free to open an issue providing all the requested information to get the issue triaged.

**Comment by linxcat** [comment]
@jacobbednarz There are users in the issue I pointed you to telling you that the issue still exists in the latest provider versions. This ticket is not the point, use the issue that was insultingly closed months ago with no resolution.

**Comment by jacobbednarz** [comment]
none of the commenters in that issue, including yourself, have provided the necessary information to triage the potential issue. if you have a way to reproduce and can provide the requested details from the issue template on GitHub, i'll gladly take a look. until then, i'm sorry but i'm not chasing issues without the minimums to diagnose.
