### ISSUE TITLE
`cloudflare_certificate_pack` forced to be replaced without changes

### ISSUE THREAD

**Issue by VasekPurchart** [cloudflare/terraform-provider-cloudflare#2986]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```bash
$ terraform -v
Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.20.
```

### Affected resource(s)

* `cloudflare_certificate_pack`

### Terraform configuration files

```hcl
terraform {
  required_version = "~> 1.6.5"
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 4.20.0"
    }
  }
}

resource "cloudflare_certificate_pack" "certificate" {
  certificate_authority = "digicert"
  cloudflare_branding   = false
  hosts                 = ["favicdn.net", "*.favicdn.net", "img.cz.favicdn.net", "img.sk.favicdn.net", "img.pl.favicdn.net", "img.ro.favicdn.net", "img.hu.favicdn.net", "img.hr.favicdn.net", "img.it.favicdn.net", "img.se.favicdn.net", "img.uk.favicdn.net", "static.cz.favicdn.net", "static.sk.favicdn.net", "static.pl.favicdn.net", "static.ro.favicdn.net", "static.hu.favicdn.net", "static.hr.favicdn.net", "static.it.favicdn.net", "static.se.favicdn.net", "static.uk.favicdn.net"]
  type                  = "advanced"
  validation_method     = "txt"
  validity_days         = 365
  zone_id               = "8afae4c8af9834213bf3d609eedc7e8a"
}

import {
  id = "8afae4c8af9834213bf3d609eedc7e8a/732843c4-a851-47b1-85ed-99afa9f81877"
  to = cloudflare_certificate_pack.certificate
}
```

### Link to debug output

https://gist.github.com/VasekPurchart/fd773a956dbe1ec63970cc9797a31ea6

### Expected output

Import resource, plan contains no changes.

### Actual output

Plans to replace the resource although the definition has not changed. In fact for debugging purposes the current resource definition is a straight copy of what `cf-terraforming` produces for this resource. They are also correct AFAIK - match what I see in the UI.

Also it does not show any of the values marked with `# forces replacement` as changing the value somehow - only that they are "new", which does not make much sense.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # cloudflare_certificate_pack.certificate must be replaced
  # (imported from "8afae4c8af9834213bf3d609eedc7e8a/732843c4-a851-47b1-85ed-99afa9f81877")
  # Warning: this will destroy the imported resource
-/+ resource "cloudflare_certificate_pack" "certificate" {
      + certificate_authority  = "digicert" # forces replacement
      + cloudflare_branding    = false # forces replacement
        hosts                  = [
            "*.favicdn.net",
            "favicdn.net",
            "img.cz.favicdn.net",
            "img.hr.favicdn.net",
            "img.hu.favicdn.net",
            "img.it.favicdn.net",
            "img.pl.favicdn.net",
            "img.ro.favicdn.net",
            "img.se.favicdn.net",
            "img.sk.favicdn.net",
            "img.uk.favicdn.net",
            "static.cz.favicdn.net",
            "static.hr.favicdn.net",
            "static.hu.favicdn.net",
            "static.it.favicdn.net",
            "static.pl.favicdn.net",
            "static.ro.favicdn.net",
            "static.se.favicdn.net",
            "static.sk.favicdn.net",
            "static.uk.favicdn.net",
        ]
      ~ id                     = "732843c4-a851-47b1-85ed-99afa9f81877" -> (known after apply)
        type                   = "advanced"
      + validation_method      = "txt" # forces replacement
      + validity_days          = 365 # forces replacement
      + wait_for_active_status = false # forces replacement
        zone_id                = "8afae4c8af9834213bf3d609eedc7e8a"
    }

Plan: 1 to import, 1 to add, 0 to change, 1 to destroy.
```

### Steps to reproduce

1. have existing certificate to import (created via UI)
2. `terraform plan`

**Comment by jacobbednarz** [comment]
this is somewhat expected and called out in https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack#import. fields like `validity_days` aren't possible to be calculated after the resource is created so it will want to trigger a replacement due to them lacking. my recommendation here is to replace the certificate with a new one and remove the old one.

**Comment by rs-garrick** [comment]
Can we look at this again?
`validity_days` is returned by the API. The CF provider is leaving those 4 values as `null` in the state after importing the certificate pack. In fact, one can manually edit the terraform state, correct those 4 values with what was returned from the API, and it works fine.

One can find the API values from the `ssl/certificate_packs` endpoint: `https://api.cloudflare.com/client/v4/zones/${zone_ID}/ssl/certificate_packs`.
