### ISSUE TITLE
Be able to configure speed > Optimization > Protocol optimization via Terraform

### ISSUE THREAD

**Issue by fascoli** [cloudflare/terraform-provider-cloudflare#2991]
### Current Terraform and Cloudflare provider version

Terraform v1.5.5
Cloudflare v4.20

### Description

It would be nice to be able to configure speed> Optimization > Protocol optimization > HTTP/3 and other options via Terraform code. I can't find a way to do it with the current version.

### Use cases

Sometimes those settings need to be modified. It would be nice to be able to do it via code

### Potential Terraform configuration

```hcl
resource "cloudflare_speed_optimization" "this" {
  zone_id = cloudflare_zone.zone.id
  http2 = true
  http2_to_origin = true
  http3_with_quic = true
}
```

**Comment by Nmishin** [comment]
Hi @fascoli this settings already supported in [cloudflare_zone_settings_override (Resource)](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override), but named a little bit different:

http2_to_origin  - origin_max_http_version  (The highest HTTP version Cloudflare will attempt to use with your origin.)
http3_with_quic - http3

**Comment by jacobbednarz** [comment]
thanks @Nmishin 👏
