### ISSUE TITLE
logpush ownership_challenge: was null, but now has a value

### ISSUE THREAD

**Issue by aegiacometti** [cloudflare/terraform-provider-cloudflare#3001]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

1.5.7

### Affected resource(s)

resource "cloudflare_logpush_job" "job_http_requests" 

### Terraform configuration files

```hcl
This is my setup

- var.cloudflare_zones is a key:value with zone_name:zone_id

- the module construct

module "cloudflare_logpush_job" {
source = "../../../../.terraform/cs_modules/tf-cf-logpush"
for_each = jsondecode(var.cloudflare_zones)

cloudflare_zone_id = each.value
lougpush_name = "tf-logpush-${each.key}"
gcp_bucket_destination_name = module.cloudflare_logpush_gcp_bucket.name
gcp_bucket_destination_url = module.cloudflare_logpush_gcp_bucket.bucket_url
logpull_job_options = local.logpull_job_options
}

- module code

resource "cloudflare_logpush_ownership_challenge" "ownership_challenge" {
zone_id = var.cloudflare_zone_id
destination_conf = var.gcp_bucket_destination_url
}

data "google_storage_bucket_object_content" "challenge_file" {
depends_on = [cloudflare_logpush_ownership_challenge.ownership_challenge]
bucket = var.gcp_bucket_destination_name
name = cloudflare_logpush_ownership_challenge.ownership_challenge.ownership_challenge_filename
}

resource "cloudflare_logpush_job" "job_http_requests" {
depends_on = [data.google_storage_bucket_object_content.challenge_file]
enabled = true
zone_id = var.cloudflare_zone_id
name = var.lougpush_name
destination_conf = var.gcp_bucket_destination_url
logpull_options = var.logpull_job_options
ownership_challenge = data.google_storage_bucket_object_content.challenge_file.content
dataset = "http_requests"
}
```

### Link to debug output

https://gist.github.com/aegiacometti/248460cc6d7d86eece05491333b1bd65

### Expected output

There no other error, since in the 2nd run it works fine. I don't have the log for that one.

### Actual output

│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for
│ module.cloudflare_logpush_job["paack.io"].cloudflare_logpush_job.job_http_requests
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/cloudflare/cloudflare" produced an invalid new value
│ for .ownership_challenge: was null, but now
│ cty.StringVal("eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIiwidHlwIjoiSldUIn0..ZbZyyM1M-nQLZqvI.fkp9dJUuEU3w74l-ESPdXY6cJqOIOei6P3lvW9sMnBmii5H87ekUKjKNLiSvyQXCWPAyhLaIyYmFdLQguAuJy8AtOQa6NkjkBh6_ews5EawIEWshoMaE59NVsAN85vdYSs9HL21
kzqqX1LgW8cQVDUyqTE5RIwRd2Q87AmPFdtZ9T2iEaMg8btyG3I0_jFj5f0KeUOGW32hLXbV18ZRRU5-mZi3ODNgO29wgEQFQYxkhrTMHPtfCpH118mnEtiP8JWH1uYX5GzSBHvlOrrIMf7UgMLU5_c7l475_gNTcI8FS31k.9aGsx4c6hR0qLl55i2QwKw").
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to reproduce

make plan runs fine, but make apply do not

### Additional factoids

The first **make apply** will fail but the second will run fine.
This is because, in the 1st run, the challenge file gets created, in the 2nd run it just loads it.

I'm using this versions terraform 1.5.7, cloudflare 4.18, google 5.4.0

I'm creating the logpush for several zones here, but I tried for only one zone as the examples in the documentation and the problem is the same.

### References

no

**Comment by rbabyuk-vs** [comment]
we tried to add null resource and local exec with timeout as dependency to ensure that "data" has content, but it had no impact on result even "data" contained information.

**Comment by oleksandrs-adorama** [comment]
I am experiencing the same issue

**Comment by gdubicki** [comment]
I am having the same issue. Can this be please reopened?
