### ISSUE TITLE
cloudflare_zone_settings_override gives "Error: Invalid value for zone setting ciphers (1007)" for valid ciphers. 

### ISSUE THREAD

**Issue by BenCoughlan15** [cloudflare/terraform-provider-cloudflare#3003]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

│ Error: Invalid value for zone setting ciphers (1007)
│
When trying to use the ciphers "AEAD-AES128-GCM-SHA256", "AEAD-AES256-GCM-SHA384", "AEAD-CHACHA20-POLY1305-SHA256", error 1007 is returned from the API, despite the fact that the ciphers are declared to be supported.

https://developers.cloudflare.com/ssl/reference/cipher-suites/supported-cipher-suites/

There is a note on the page saying they're automatically supported, so can the provider just ignore these values if they're present? Or give some kind of useful feedback? 

### Affected resource(s)

cloudflare_zone_settings_override

### Terraform configuration files

```hcl
# cloudflare_zone_settings_override.dev-banked-com will be updated in-place
  ~ resource "cloudflare_zone_settings_override" "dev-acme-com" {
        id                       = "var.id"
        # (6 unchanged attributes hidden)

      ~ settings {
          ~ ciphers                     = [
              + "ECDHE-ECDSA-AES128-GCM-SHA256",
              + "ECDHE-ECDSA-CHACHA20-POLY1305",
              + "ECDHE-RSA-AES128-GCM-SHA256",
              + "ECDHE-RSA-CHACHA20-POLY1305",
              + "ECDHE-ECDSA-AES128-SHA256",
              + "ECDHE-RSA-AES128-SHA256",
              + "ECDHE-ECDSA-AES256-GCM-SHA384",
              + "ECDHE-ECDSA-AES256-SHA384",
              + "ECDHE-RSA-AES256-GCM-SHA384",
              + "ECDHE-RSA-AES256-SHA384",
              + "AEAD-AES128-GCM-SHA256",
              + "AEAD-AES256-GCM-SHA384",
              + "AEAD-CHACHA20-POLY1305-SHA256",
            ]
            # (50 unchanged attributes hidden)

            # (3 unchanged blocks hidden)
        }
    }
```

### Link to debug output

none required

### Expected output

Modifications complete after 9s

### Actual output

│ Error: Invalid value for zone setting ciphers (1007)

### Steps to reproduce

terraform init
terraform apply

then comment out the AHED ciphers, and try again, where it works. 

Really frustrating, some decent documentation would be useful. 

### References

[..](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_settings_override#ciphers)

**Comment by gitbugr** [comment]
Still broken, please reopen.

```
curl --request PATCH \
  --url https://api.cloudflare.com/client/v4/zones/{zone_id}/settings/ciphers \
  --header 'Authorization: Bearer {token}' \
  --header 'Content-Type: application/json' \
  --data '{
  "value": [
    "AEAD-CHACHA20-POLY1305-SHA256",
    "AEAD-AES256-GCM-SHA384",
    "AEAD-AES128-GCM-SHA256",
    "ECDHE-RSA-AES256-GCM-SHA384",
    "ECDHE-ECDSA-AES256-GCM-SHA384",
    "ECDHE-RSA-CHACHA20-POLY1305",
    "ECDHE-RSA-AES128-GCM-SHA256",
    "ECDHE-ECDSA-CHACHA20-POLY1305",
    "ECDHE-ECDSA-AES128-GCM-SHA256"
  ]
}'
```

results in:

```
{"success":false,"errors":[{"code":1007,"message":"Invalid value for zone setting ciphers"}],"messages":[],"result":null}%
```
