### ISSUE TITLE
Email Routing Subdomains

### ISSUE THREAD

**Issue by calvinbui** [cloudflare/terraform-provider-cloudflare#3004]
### Current Terraform and Cloudflare provider version

Provider 4.20.0 & Terraform 1.6.6

### Description

Support subdomains for email routing: https://blog.cloudflare.com/email-routing-subdomains/

Ideally it would also output the MX records as well.

### Use cases

Adding a subdomain for email routing as specified above. We use this feature for development.

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
