### ISSUE TITLE
Logpush configuration for Datadog exposes key in logs

### ISSUE THREAD

**Issue by fingalickn** [cloudflare/terraform-provider-cloudflare#3020]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

v4.18.0

### Affected resource(s)

cloudflare_logpush_job

### Terraform configuration files

```hcl
resource "cloudflare_logpush_job" "datadog_http_requests" {
  enabled          = true
  zone_id          = cloudflare_zone.zone.id
  name             = "datadog-http-requests-${var.cloudflare_zone}"
  logpull_options  = "fields=CacheCacheStatus,ClientCountry,ClientDeviceType,ClientIP,ClientRegionCode,ClientRequestHost,ClientRequestMethod,ClientRequestPath,ClientRequestURI,ClientRequestUserAgent,EdgeResponseStatus,EdgeStartTimestamp&timestamps=rfc3339,EdgeTimeToFirstByteMs,OriginResponseDurationMs,OriginResponseStatus,RayID,ZoneName&sample=1"
  destination_conf = "datadog://http-intake.logs.datadoghq.com/api/v2/logs?header_DD-API-KEY=${var.dd_api_key}&ddsource=cloudflare&service=cloudflare&ddtags=event_type:http_requests"
  dataset          = "http_requests"
  # filter           = "{\"key\":\"ClientCountry\",\"operator\":\"!eq\",\"value\":\"us\"}"
}
```

### Link to debug output

https://gist.github.com/nolinkneeded.com

### Expected output

# module.dev_app.cloudflare_logpush_job.datadog_dns_logs will be updated in-place
  ~ resource "cloudflare_logpush_job" "datadog_dns_logs" {
      ~ destination_conf            = "datadog://http-intake.logs.datadoghq.com/api/v2/logs?header_DD-API-KEY=<SENSITIVE>&ddsource=cloudflare&service=cloudflare&ddtags=event_type:dns_logs,env=dev" -> "datadog://http-intake.logs.datadoghq.com/api/v2/logs?header_DD-API-KEY=<SENSITIVE>&ddsource=cloudflare&service=cloudflare&ddtags=event_type:dns_logs,env=dev"
      ~ enabled                     = false -> true
        id                          = "393501"
        name                        = "datadog-dns-logs-dev.app.com"
        # (7 unchanged attributes hidden)
    }

### Actual output

The actual output is the same excep the sensitive fields I added above are actually filled out with tokens to access datadog.... 

# module.dev_app.cloudflare_logpush_job.datadog_dns_logs will be updated in-place
  ~ resource "cloudflare_logpush_job" "datadog_dns_logs" {
      ~ destination_conf            = "datadog://http-intake.logs.datadoghq.com/api/v2/logs?header_DD-API-KEY=382fcf059f4c2fd47bc7e6d3d9aefaf6&ddsource=cloudflare&service=cloudflare&ddtags=event_type:dns_logs,env=dev" -> "datadog://http-intake.logs.datadoghq.com/api/v2/logs?header_DD-API-KEY=382fcf059f4c2fd47bc7e6d3d9aefaf6&ddsource=cloudflare&service=cloudflare&ddtags=event_type:dns_logs,env=dev"
      ~ enabled                     = false -> true
        id                          = "393501"
        name                        = "datadog-dns-logs-dev.app.com"
        # (7 unchanged attributes hidden)
    }

### Steps to reproduce

Create a logpush job that points to datadog. Watch the plan expose the sensitive key in the output

### Additional factoids

Should either redact the field or allow the key to be supplied in another param and do the concatenation in the provider logic.

**Comment by jacobbednarz** [comment]
for now, this will stay as is given the entire string needs to be editable/reviewable by the end user without replacement.

we can try to address this in #2173 so i recommend you follow that issue.
