### ISSUE TITLE
Upable to manage cloudflare_ruleset in both Terraform and Web UI

### ISSUE THREAD

**Issue by altnp** [cloudflare/terraform-provider-cloudflare#3027]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.6.2
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.20.0
+ provider registry.terraform.io/hashicorp/aws v4.5.0
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.12.9

### Affected resource(s)

#Current

```
resource "cloudflare_firewall_rule" "ip_restriction" {
  zone_id     = data.cloudflare_zone.companyname_dev.id
  description = "${title(var.stack_name)} IP Whitelist"
  filter_id   = cloudflare_filter.ip_restriction.id
  action      = "block"
  priority    = 1
}

resource "cloudflare_filter" "ip_restriction" {
  zone_id     = data.cloudflare_zone.companyname_dev.id
  description = ""
  expression  = "(http.host matches \"${lower(var.stack_name)}\\.companyname\\.dev$\" and not ip.src in $companyname_office and not ip.src in $sitename_dev_aws and not ip.src in {${join(" ", var.allowed_cidr_blocks[*].cidr_block)}})"
}
```

#Post firewall_rule Migration
```
resource "cloudflare_ruleset" "ip_restriction" {
  zone_id = data.cloudflare_zone.companyname_dev.id
  name    = "${title(var.stack_name)} IP Whitelist"
  kind    = "zone"

  phase = "http_request_firewall_custom"

  rules {
    action      = "block"
    expression  = "(http.host matches \"${lower(var.stack_name)}\\.companyname\\.dev$\" and not ip.src in $companyname_office and not ip.src in $sitename_dev_aws and not ip.src in {${join(" ", var.allowed_cidr_blocks[*].cidr_block)}})"
    description = "${title(var.stack_name)} IP Whitelist"
    enabled     = false
  }
}
```

### Terraform configuration files

```hcl
#Current
resource "cloudflare_firewall_rule" "ip_restriction" {
  zone_id     = data.cloudflare_zone.companyname_dev.id
  description = "${title(var.stack_name)} IP Whitelist"
  filter_id   = cloudflare_filter.ip_restriction.id
  action      = "block"
  priority    = 1
}

resource "cloudflare_filter" "ip_restriction" {
  zone_id     = data.cloudflare_zone.companyname_dev.id
  description = ""
  expression  = "(http.host matches \"${lower(var.stack_name)}\\.companyname\\.dev$\" and not ip.src in $companyname_office and not ip.src in $sitename_dev_aws and not ip.src in {${join(" ", var.allowed_cidr_blocks[*].cidr_block)}})"
}

#Post firewall_rule Migration
resource "cloudflare_ruleset" "ip_restriction" {
  zone_id = data.cloudflare_zone.companyname_dev.id
  name    = "${title(var.stack_name)} IP Whitelist"
  kind    = "zone"

  phase = "http_request_firewall_custom"

  rules {
    action      = "block"
    expression  = "(http.host matches \"${lower(var.stack_name)}\\.companyname\\.dev$\" and not ip.src in $companyname_office and not ip.src in $sitename_dev_aws and not ip.src in {${join(" ", var.allowed_cidr_blocks[*].cidr_block)}})"
    description = "${title(var.stack_name)} IP Whitelist"
    enabled     = false
  }
}
```

### Link to debug output

https://gist.github.com/altnp/aa01e581fdbcca918d74581074a2d271

### Expected output

No error

### Actual output

Error: failed to create ruleset "http_request_firewall_custom" as a similar configuration with rules already exists and overwriting will have unintended consequences.

### Steps to reproduce

1. Run the Terraform
2. See error

### Additional factoids

I have a use case where I can not manage all my firewall rules inside of Terraform. Currently, using the firewall_ruleset I am able to mix (and even manage them across multiple TF projects). At first, I thought the error was due to me managing the rules across multiple projects; so I consolidated them. However I am still running into the issue, making me believe there is a **bug** where I can not manage them in both the Web UI and Terraform. 

With the deprecation of firewall_rules later this year, I need a solution for this ASAP.

**Comment by altnp** [comment]
Added gist

**Comment by jacobbednarz** [comment]
this is intentional and is not a bug. there is no way for terraform to know which are the ones you intend to keep when it comes to ordering or overriding so this is a manual operation. 

if you already have some rules defined and the WAF migration is performed, you can use a tool like cf-terraforming to export the entirety of the Ruleset configuration or you can individually resolve the differences.

**Comment by altnp** [comment]
The resource was a rule, not a rule set. You're moving the goal post and then claiming the approach was wrong. 

I'd be fine not using the new resource, but then don't deprecate the old. It's working just fine right now even with the new custom rule backend.

**Comment by jacobbednarz** [comment]
ruleset rules are not available as a standalone resource so we are talking about rulesets as a unified view in this context. there may be a time in the future where rules are manageable individually however, that is not in the foreseeable future so that is the only option today.

**Comment by altnp** [comment]
>ruleset rules are not available as a standalone resource

See: cloudflare_firewall_rule

**Comment by orlandothoeny** [comment]
This is also really a bummer for us. It completely breaks building decoupled modules, since you have to put all your rules into a single `cloudflare_ruleset` resource.

The new approach is way worse regarding maintainability and makes managing rules way more fragile.
Previously, you could create the firewall rules your module needs inside your module. Now, you have to remember that there's some rule - which is located inside a completely different module - that affects your module, that you need to change when you change something in your module/or change some config via a variable. Like a hostname for example.

Ref https://github.com/cloudflare/terraform-provider-cloudflare/issues/2688, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2907, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423, https://github.com/cloudflare/terraform-provider-cloudflare/issues/2634

**Comment by petero-dk** [comment]
I just wanted to add our work around, it is slightly complex but seems to work:

It consists of having a single repository called "network" that is responsible for general changes that does not naturally fit into a project repository (i.e. setting dns for Office 365) in this repository we create a data store for rules (we opted for Azure Table Storage, because it is cheap and we are on Azure and Devops anyway) 

In each repository that needs to set a rule, instead of writing to Cloudflare, instead the rule is written to the table via a `data` reference, and then in the shared repository the table storage is read an put into cloudflare. All is written in Terraform, and it is slightly verbose:

In the projects:

```terraform
resource "azurerm_storage_table_entity" "studio_path" {
  table_name           = "cloudflarerules"
  storage_account_name = data.azurerm_storage_account.infrastructure.name
  partition_key        = "http_request_transform-zone-${var.dnszone}" # phase-kind-zone_id
  row_key              = "example-rule"                         # unique identifier
  entity = {
    kind    = "zone"
    rule = jsonencode({
      action = "rewrite",
      action_parameters = {
        headers = [
          {
            name      = "my-header-1",
            operation = "set",
            value     = "Fixed value"
          },
          {
            name       = "my-header-2",
            operation  = "set",
            expression = "cf.zone.name"
          },
          {
            name      = "existing-header",
            operation = "remove"
          }
        ]
      },
      expression  = "true",
      description = "Example HTTP Response Header Modification Rule",
      enabled     = true
    })
  }
}
```

And then in the shared network repository we have this terraform

```terraform

data "azurerm_storage_table_entities" "cloudflarerules" {
  table_name           = "cloudflarerules"
  storage_account_name = data.azurerm_storage_account.infrastructure.name
  filter               = "PartitionKey ne ''" #get all items
}

locals {
  rules = { for s in data.azurerm_storage_table_entities.cloudflarerules.items : s.partition_key => {
    phase                           = split("-", s.partition_key)[0]
    kind                            = split("-", s.partition_key)[1]
    zone_id                         = length(split("-", s.partition_key)) > 2 ? split("-", s.partition_key)[2] : null
    properties : s.properties, rule = jsondecode(s.properties.rule)
  }... } #this groups items based on kind, phase and zone_id
}

resource "cloudflare_ruleset" "dynamic_rules" {
  for_each = local.rules

  phase   = each.value.0.phase
  kind    = each.value.0.kind
  zone_id = each.value.0.zone_id #can be null

  name        = "Rule for: ${each.key}"
  description = "Managed by TF"

  dynamic "rules" {
    for_each = each.value
    content {
      expression  = rules.value.rule.expression
      action      = rules.value.rule.action
      description = rules.value.rule.description
      enabled     = rules.value.rule.enabled

      action_parameters {
        dynamic "headers" {
          for_each = contains(keys(rules.value.rule.action_parameters), "headers") == true ? rules.value.rule.action_parameters.headers : []
          content {
            name       = headers.value.name
            operation  = headers.value.operation
            value      = contains(keys(headers.value), "value") == true ? headers.value.value : null
            expression = contains(keys(headers.value), "expression") == true ? headers.value.expression : null
          }
        }

        automatic_https_rewrites = contains(keys(rules.value.rule.action_parameters), "automatic_https_rewrites") == true ? rules.value.rule.action_parameters.automatic_https_rewrites : null
        disable_zaraz            = contains(keys(rules.value.rule.action_parameters), "disable_zaraz") == true ? rules.value.rule.action_parameters.disable_zaraz : null

        #origin rules
        host_header = contains(keys(rules.value.rule.action_parameters), "host_header") == true ? rules.value.rule.action_parameters.host_header : null

        dynamic "origin" {
          for_each = contains(keys(rules.value.rule.action_parameters), "origin") == true ? rules.value.origin.headers : []
          content {
            host = contains(keys(origin.value), "host") == true ? origin.value.host : null
            port = contains(keys(origin.value), "port") == true ? origin.value.port : null
          }
        }
      }
    }
  }

}
```


Please note that this code does not cover all the possible types of cloudflare rules, this is just a sample.

**Comment by auyer** [comment]
This is a bummer. 
A similar situation in the AWS provider is handled differently. We can create a security_group with all its rules, or add rules to existing SGs using the `security_group_rule` resource.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule

We will keep using and outdated version of the provider to keep using `cloudflare_filter` and `cloudflare_firewall_rule` while we can.
