### ISSUE TITLE
Broken notification policy with backward incompatible change in 4.21.0

### ISSUE THREAD

**Issue by eLco** [cloudflare/terraform-provider-cloudflare#3028]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.4
registry.terraform.io/cloudflare/cloudflare v4.21.0

### Affected resource(s)

cloudflare_notification_policy

### Terraform configuration files

```hcl
resource "cloudflare_notification_policy" "pusher" {
  account_id = ""
  name       = "rate-limit"
  enabled    = true
  alert_type = "clickhouse_alert_fw_ent_anomaly"
  filters {
    services = ["ratelimit"]
    actions  = ["log"]
  }

  email_integration {
    id = "email@example.com"
  }

  webhooks_integration {
    id   = "someid"
    name = "Slack cloudflare alerts"
  }
}
```

### Link to debug output

https://gist.github.com/eLco/465302a435a97f66f09289eb551a5555

### Expected output

No error

### Actual output

 Error: Invalid combination of arguments
│
│   with cloudflare_notification_policy.pusher,
│   on notifications.tf line 1, in resource "cloudflare_notification_policy" "pusher":
│    1: resource "cloudflare_notification_policy" "rate-limit" {
│
│ "webhooks_integration": only one of
│ `email_integration,pagerduty_integration,webhooks_integration` can be
│ specified, but `email_integration,webhooks_integration` were specified.

### Steps to reproduce

Use CF TF provider 4.21.0
Create cloudflare_notification_policy resource with multiple integrations - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/notification_policy

**Comment by lra** [comment]
The workaround is to have only 1 type of integration per notification policy.

Instead of:
```hcl
resource "cloudflare_notification_policy" "pusher" {
  account_id = ""
  name       = "rate-limit"
  enabled    = true
  alert_type = "clickhouse_alert_fw_ent_anomaly"
  filters {
    services = ["ratelimit"]
    actions  = ["log"]
  }

  email_integration {
    id = "email@example.com"
  }

  webhooks_integration {
    id   = "someid"
    name = "Slack cloudflare alerts"
  }
}
```

Do:
```
resource "cloudflare_notification_policy" "pusher_email" {
  account_id = ""
  name       = "rate-limit"
  enabled    = true
  alert_type = "clickhouse_alert_fw_ent_anomaly"
  filters {
    services = ["ratelimit"]
    actions  = ["log"]
  }

  email_integration {
    id = "email@example.com"
  }
}

resource "cloudflare_notification_policy" "pusher_webhooks" {
  account_id = ""
  name       = "rate-limit"
  enabled    = true
  alert_type = "clickhouse_alert_fw_ent_anomaly"
  filters {
    services = ["ratelimit"]
    actions  = ["log"]
  }

  webhooks_integration {
    id   = "someid"
    name = "Slack cloudflare alerts"
  }
}
```

**Comment by eLco** [comment]
@lra thank you for the workaround :)

The reason I've posted this bug report, is that:

-  the change goes against CF Web UI that supports multiple integration types for same notification policy.
-  the change goes against CF API, which support multiple integration types - https://developers.cloudflare.com/api/operations/notification-policies-create-a-notification-policy
- there is no update of provider documentation regarding this change

**Comment by jacobbednarz** [comment]
thanks for the issue here @eLco.

@Cyb3r-Jak3 you added the `ExactlyOneOf` in #2976. was the change intending to prevent multiple blocks of config? it looks like the endpoints support it.

> there is no update of provider documentation regarding this change - https://registry.terraform.io/providers/cloudflare/cloudflare/4.21.0/docs/resources/notification_policy#example-usage

we don't offer kitchen sink style examples so it's very likely not to appear here :) you should use the API and developer documentation to determine more complex examples.

**Comment by Cyb3r-Jak3** [comment]
> @Cyb3r-Jak3 you added the ExactlyOneOf in https://github.com/cloudflare/terraform-provider-cloudflare/pull/2976. was the change intending to prevent multiple blocks of config? it looks like the endpoints support it.

Thought I read somewhere that only one could be referenced. Can't seem to find the docs for it now though.

**Comment by jacobbednarz** [comment]
all good - if we can't find the reference, let's get that reverted for the next release.
