### ISSUE TITLE
Support virtual resource for Origin Pool association with Load Balancer

### ISSUE THREAD

**Issue by chrismilson** [cloudflare/terraform-provider-cloudflare#3040]
### Current Terraform and Cloudflare provider version

Terraform v1.3.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.21.0

### Description

The dependency structure between some resources (specifically `cloudflare_load_balancer_pool` and `cloudflare_load_balancer`) makes some actions difficult to perform without implementing hacky terraform or compromising on reliability.

There should be a virtual resource (perhaps `cloudflare_load_balancer_pool_association`) that encodes the relationship between the "real" resources, so that the real resources in terraform do not directly depend on each other.

### Use cases

I currently use the `cloudflare_load_balancer_pool` and `cloudflare_load_balancer` resources. My code initially looked something like this:

```hcl
resource "cloudflare_load_balancer_pool" "this" {
  ...
}

resource "cloudflare_load_balancer" "this" {
  default_pool_ids = [cloudflare_load_balancer_pool.this.id]
}
```

This was fine when creating and updating the resources, but I had issues whenever the pools needed to be destroyed. If I taint the `cloudflare_load_balancer_pool` (or change it such that it needs to be recreated), terraform will intend on applying things in this order:

1. Delete the old `cloudflare_load_balancer_pool`
2. Create the new `cloudflare_load_balancer_pool` (to determine its id - known at apply)
3. Update the `cloudflare_load_balancer` with the newly calculated value for the `default_pool_ids`.

This fails at apply time on the first step, because the old pool is still associated with the load balancer, and the CloudFlare API does not allow the deletion of a pool that is still associated with a load balancer.

My current "hack" is this:

```hcl
resource "cloudflare_load_balancer_pool" "this" {
  for_each = local.pools
  ...
}

resource "null_resource" "recreate_load_balancer_when_pool_ids_change" {
  triggers = {
    pool_id = join(", ", [for pool in cloudflare_load_balancer_pool.this : pool.id])
  }
}

resource "cloudflare_load_balancer" "this" {
  default_pool_ids = [for pool in cloudflare_load_balancer_pool.this : pool.id]

  lifecycle = {
    replace_triggered_by = [null_resource.recreate_load_balancer_when_pools_ids_change]
  }
}
```

_NB: I originally had the `replace_triggered_by` point at the pool, but this caused the load balancer to be recreated when there was any change to the pool - even updates._

The null resource will only change when pool ids are changing; pools are being created or destroyed. This is not ideal as it is difficult to read, and the load balancer would be recreated if pools are only being added.

### Potential Terraform configuration

I think there should be a virtual resource that encodes the association of a pool with a load balancer. This would remove the direct dependency of the load balancer on its pools.

```hcl
resource "cloudflare_load_balancer" "this" {
  ...
}

resource "cloudflare_load_balancer_pool" "this" {
  for_each = local.pools
  ...
}

resource "cloudflare_load_balancer_pool_association" "this" {
  for_each = cloudflare_load_balancer_pool.this

  load_balancer_id = cloudflare_load_balancer.this.id
  pool_id = cloudflare_load_balancer_pool.this.id
}
```

In the above proposed snippet, the `cloudflare_load_balancer` and `cloudflare_load_balancer_pool` are mutually exclusive. Their lifecycles would not influence the other. Instead, the `cloudflare_load_balancer_pool_association` depends on both. If a pool is scheduled for recreation, the `for_each` instance on the pool association from that pool would also cause recreation of that association. Since the association would be scheduled for destruction, and is downstream from the pool, it would be destroyed first, removing the association, and allowing the destruction of the pool.

**Comment by jacobbednarz** [comment]
thanks for the request! unfortunately, at this time we are focusing on matching the APIs 1:1 with the provider implementation and don't have any plans to add association style resources.

the way i recommend doing the swap you are attempting here without downtime is to first add your new pool to the load balancer configuration, and then remove the pool before finally deleting it. it's slightly more involved however, it does give you a rollback plan as well if something were to go wrong.

**Comment by chrismilson** [comment]
Unfortunately requiring two apply steps is not viable, as the terraform is being run in automation (and said automation is shared, so implementing hacks to this process would affect others). Terraform code run by such automation should be able to obtain its desired configuration after a single apply.

Guess I'm stuck with my hack for the time being.

**Comment by jacobbednarz** [comment]
the two steps are required because you are referencing the LB pool from inside of the LB itself (see `cloudflare_load_balancer_pool.example.id` below). when terraform transverses the resource graph, it will attempt to do the dependent resource modifications first. consider the following:

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
    }
  }
}

provider "cloudflare" {}

variable "account_id" {
  type    = string
  default = "f037e56e89293a057740de681ac9abbe"
}

variable "zone_id" {
  type    = string
  default = "0da42c8d2132a9ddaf714f9e7c920711"
}

resource "cloudflare_load_balancer" "example" {
  zone_id          = var.zone_id
  name             = "example-load-balancer.terraform.cfapi.net"
  fallback_pool_id = cloudflare_load_balancer_pool.example.id
  default_pool_ids = [cloudflare_load_balancer_pool.example.id]
  description      = "example load balancer using geo-balancing"
  proxied          = true
  steering_policy  = "geo"

  pop_pools {
    pop      = "LAX"
    pool_ids = [cloudflare_load_balancer_pool.example.id]
  }

  country_pools {
    country  = "US"
    pool_ids = [cloudflare_load_balancer_pool.example.id]
  }

  region_pools {
    region   = "WNAM"
    pool_ids = [cloudflare_load_balancer_pool.example.id]
  }
}

resource "cloudflare_load_balancer_pool" "example" {
  account_id = var.account_id
  name       = "lb-pool-1"
  origins {
    name    = "example-1"
    address = "192.0.2.1"
    enabled = false
  }
}
```

and the graph to accompany the config

![graph](https://github.com/cloudflare/terraform-provider-cloudflare/assets/283234/0d109db3-81d3-44e9-a859-b2fb753024a9)

using this visual representation, you can see that any changes in LB pool (say deleting a pool entirely) will be executed before the LB itself is updated. this means you cannot delete a pool before the LB no longer has a reference to it and why you need at a minimum two runs for it to take effect.

the way you can work around this is by not using references but instead using the IDs directly (`6ee0ea2cab118f7aafb6cee92667dfd4`).

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
    }
  }
}

provider "cloudflare" {}

variable "account_id" {
  type    = string
  default = "f037e56e89293a057740de681ac9abbe"
}

variable "zone_id" {
  type    = string
  default = "0da42c8d2132a9ddaf714f9e7c920711"
}

resource "cloudflare_load_balancer" "example" {
  zone_id          = var.zone_id
  name             = "example-load-balancer.terraform.cfapi.net"
  fallback_pool_id = "6ee0ea2cab118f7aafb6cee92667dfd4"
  default_pool_ids = ["6ee0ea2cab118f7aafb6cee92667dfd4"]
  description      = "example load balancer using geo-balancing"
  proxied          = true
  steering_policy  = "geo"

  pop_pools {
    pop      = "LAX"
    pool_ids = ["6ee0ea2cab118f7aafb6cee92667dfd4"]
  }

  country_pools {
    country  = "US"
    pool_ids = ["6ee0ea2cab118f7aafb6cee92667dfd4"]
  }

  region_pools {
    region   = "WNAM"
    pool_ids = ["6ee0ea2cab118f7aafb6cee92667dfd4"]
  }
}

# id is 6ee0ea2cab118f7aafb6cee92667dfd4 from the state or API
resource "cloudflare_load_balancer_pool" "example" {
  account_id = var.account_id
  name       = "lb-pool-1"
  origins {
    name    = "example-1"
    address = "192.0.2.1"
    enabled = false
  }
}
```

and there is no longer a direct dependency on the LB pool <> LB

![graph](https://github.com/cloudflare/terraform-provider-cloudflare/assets/283234/4aff5627-23cd-4131-8ec0-4d0ddc8fcde7)

i don't advise this (instead, do a 2 phase rollout for additions/cleanups) but it does work if needed.
