### ISSUE TITLE
Support importing cloudflare_tiered_cache

### ISSUE THREAD

**Issue by nitrocode** [cloudflare/terraform-provider-cloudflare#3051]
### Current Terraform and Cloudflare provider version

Latest

### Description

Cannot import

```
$ terraform import 'cloudflare_tiered_cache.default' <zone-id>

│ Error: resource cloudflare_tiered_cache doesn't support import
```

### Use cases

Migrating from deprecated resource argument to new resource

### Potential Terraform configuration

```hcl
resource "cloudflare_tiered_cache" "default" {
  cache_type = "generic"
  zone_id    = "<redacted>"
}
```

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/tiered_cache

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
