### ISSUE TITLE
Add Ruleset Expression Validation api endpoint / before apply failure or suggest alternative in documentation

### ISSUE THREAD

**Issue by Nathan-Yorio** [cloudflare/terraform-provider-cloudflare#3054]
### Current Terraform and Cloudflare provider version

Version: Not specifically terraform version related, but it effects validation workflow

### Description

It does not appear that the new cloudflare ruleset resource which is replacing the original filters rules has an API endpoint which can be used to validate the expression syntax as was previously available in the (now deprecated) filters. If I'm wrong about this please point me to the documentation that something roughly equivalent exists

https://developers.cloudflare.com/firewall/api/cf-filters/validation/

The cloudflare provider with terraform also does not seem to check the expression during plan phase, so it is not built into the terraform workflow without running apply and seeing a failure.

### Use cases

- Use of custom scripts to check ruleset expression syntax against the api locally before running apply. 
    - I'm aware that terraform apply can be run and the api will fail the apply, but I think that it should be possible to validate syntax _before_ apply or even just have local script to check your syntax when you're making rules
- Local development validation can happen without needing direct access to the expression builder / editor to produce an expression and see the syntax issues (an offline expression builder / editor which does not require dash access nor intimate knowledge of the ruleset engine's documentation would be cool too)
- CI / CD (or rough equivalent) can validate expression syntax without needing to have an apply failure in order to rectify the issue. Some nested expressions can get rather large and visually validating those for approval is difficult

**again: If this is already possible and I just overlooked it please point me towards docs and I'll be on my way.

### Potential Terraform configuration

In a terraform sense

If I were to write 
```hcl
expression        = "(cf.bot_management.score lo 2 and http.user_agent ne \"Something\)"
```

I would want my plan to tell me like this before I find out it is broken in apply (if this can be built into the Cloudflare provider itself, if not I would like to be pointed toward a static solution which could perform syntax validation)
```hcl
expression        = "(cf.bot_management.score {{lo}} 2 and http.user_agent ne \"Something\)"
Describe error here with lo, did I mean le?
```

But in an api sense I should be able to get the same functionality which is present here using the new ruleset engine

https://developers.cloudflare.com/firewall/api/cf-filters/validation/

**Comment by jacobbednarz** [comment]
thanks for the suggestion! unfortunately, this isn't the place to suggest new API endpoints. your best bet is to file a support ticket which will be triaged and assigned to the appropriate feature request queue for consideration.
