### ISSUE TITLE
Add support for Workers with multiple script files in the `cloudflare_worker_script` resource

### ISSUE THREAD

**Issue by gdubicki** [cloudflare/terraform-provider-cloudflare#3055]
### Current Terraform and Cloudflare provider version

Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.20.0

### Description

We are using Worker scripts split into multiple files.

However the current provider does not seem to support that as `cloudflare_worker_script` resource's `content` attribute expects the content of a single script file.

We use a workaround with a resource that runs `wrangler` locally:

```hcl
 resource "null_resource" "bundle_worker_script" {
  triggers = {
    dir_sha = sha1(join("", [for f in fileset("./src", "*"): filesha1("./src/${f}")]))
  }
  provisioner "local-exec" {
    command = "npx wrangler deploy --outdir dist --dry-run"
    working_dir = "."
  }
}

resource "cloudflare_worker_script" "web" {
  depends_on = [null_resource.bundle_worker_script]

  content    = file("./dist/index.js")
  // (...)
```

...but it's flaky and doesn't allow us to switch to Terraform Cloud.

### Use cases

Whenever you are using a Worker script split into multiple files.

### Potential Terraform configuration

```hcl
resource "cloudflare_worker_script" "my_worker" {
  // instead of "content"
  content_dir = "./src"
  (...)
```

### References

https://github.com/cloudflare/terraform-provider-cloudflare/issues/1417#issuecomment-1226791755

**Comment by jacobbednarz** [comment]
thanks for the issue! as of today, we don't have a publicly documented API that allows uploading multiple files so the provider/SDK won't support it given our requirement for stable APIs.

the best bet to get this moving is to raise a ticket with support or your account team requesting it which then can be prioritised by the service team as a feature.

**Comment by CMoore-Darwinium** [comment]
Hi @jacobbednarz ,

The Put script content API specifically uses multipart body. `https://developers.cloudflare.com/api/operations/worker-script-put-content`. This API is used by wrangler2 to upload multiple files (specifically WASM in our case), so I do feel that it's both publicly documented and well used, which implies a high degree of stability and commitment from Cloudflare.

We can't get modules + WASM working with the provider as-is, but we've got our own fork that supports adding additional files. We're currently cleaning this fork up for a pull request and hoping to start a dialogue with you before we formally create the PR to see what other concerns and considerations there are around this topic.

Thank you very much!
-Caleb

**Comment by TigerC10** [comment]
@CMoore-Darwinium did you ever get it clean enough to submit a pull request?
