### ISSUE TITLE
Support Zero Trust resolver rules

### ISSUE THREAD

**Issue by devinbfergy** [cloudflare/terraform-provider-cloudflare#3056]
### Current Terraform and Cloudflare provider version

terraform 1.6.6 and cloudflare provider 4.22.0

### Description

Support the new zero trust Resolver rules. These appear to show up in the api as zero trust gateway policies, but with action of type resolve and filters = ["dns_resolver"]

### Use cases

To manage resolver rules with terraform 

### Potential Terraform configuration

```hcl
resource "cloudflare_teams_rule" "example" {
  account_id  = "ID"
  action      = "resolve"
  description = "Route to internal.com domain "
  enabled     = true
  filters     = ["dns_resolver"]
  name        = "Resolve internal.com"
  precedence  = 16000
  traffic     = "any(dns.domains[*] == \"internal.com\")"
  rule_settings {
    block_page_enabled                 = false
    insecure_disable_dnssec_validation = false
    ip_categories                      = false
  }
  dns_resolver_ipv4 {
     ip = "10.0.0.1"
     port = 53
  }
  dns_resolver_ipv6 {
      ip = "::/0"
      port = 53
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
