### ISSUE TITLE
Resource cloudflare_zone can remove a registered domain by the cloudflare registrar from the user's account.

### ISSUE THREAD

**Issue by garis-space** [cloudflare/terraform-provider-cloudflare#3057]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

v1.6.6

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

provider "cloudflare" {
  api_token = "<YOUR_API_TOKEN>"
}

resource "cloudflare_zone" "zone" {
  account_id = "<YOUR_ACCOUNT_ID>"
  zone       = "<YOUR_DOMAIN_NAME>"
}
```

### Link to debug output

-

### Expected output

Returned error message as in dash.cloudflare.com panel:
`The zone cannot be deleted as the domain is currently registered through Cloudflare's registrar.`

### Actual output

Terraform will delete resource without return any warning.

### Steps to reproduce

1. You must have registered/transferred your domain to Cloudflare.

2. Create API token from Cloudflare account https://dash.cloudflare.com/profile/api-tokens with permissions to:
`All zones - Zone Versioning:Edit, Zone WAF:Edit, Zone Settings:Edit, Zone:Edit, Page Rules:Edit, DNS:Edit`

3. Create simple terraform file `main.tf`:
```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

provider "cloudflare" {
  api_token = "<YOUR_API_TOKEN>"
}

resource "cloudflare_zone" "zone" {
  account_id = "<YOUR_ACCOUNT_ID>"
  zone = "<YOUR_DOMAIN_NAME>"
}
```

4. Init and apply terraform
```
terraform init
...
terraform apply
```

In this step if you apply terraform you get error because the domain <YOUR_DOMAIN_NAME> is already in your account.
`Error: error creating zone "<YOUR_DOMAIN_NAME>": <YOUR_DOMAIN_NAME> already exists (1061)`

5. Check what ID your zone has for <YOUR_DOMAIN_NAME> in https://dash.cloudflare.com

6. Import your existing <ZONE_ID> to your terraform state:
`terraform import cloudflare_zone.zone <ZONE_ID>`

7. Change <YOUR_DOMAIN_NAME> to <YOUR_NEW_DOMAIN_NAME> in the terraform `main.tf` script from step one and run `terraform apply`.

As you can see, the new domain is added and the old one removed !!!

8. Restore deleted domain, change <YOUR_NEW_DOMAIN_NAME> to <YOUR_DOMAIN_NAME> and `terraform apply`.

The domain has been restored, but with new nameservers !!!

And you can not change the nameservers for a domain registered / transferred to Cloudflare.

### Additional factoids

1. From the admin panel, you can not remove the zone for a domain that is registered / transferred to Cloudflare.
You get error `The zone cannot be deleted as the domain is currently registered through Cloudflare's registrar.`

2. After deleting the zone for a domain, go to the "Domain Registration" section of the administration panel (https://dash.cloudflare.com/), click the "Manage" link next to your domain. Entering the domain settings does not work, you cannot perform a domain transfer.

3. If you try to delete the restored zone from the panel then you will get an error message "registrar.cannot_delete_zone_cloudflare_registrar" instead of "The zone cannot be deleted as the domain is currently registered through Cloudflare's registrar.".

**Comment by jacobbednarz** [comment]
this is expected behaviour. the dash has these safeguards in place whereas the API assumes you know what you are doing and will have less guardrails for things like this (terraform is just another HTTP client).

if you'd like to prevent zones from being deleted (regardless of the mechanism used) you can use zone holds or `prevent_destroy` in the resource metadata.

**Comment by garis-space** [comment]
An employee made a mistake and deleted a zone for a domain, it happens.

Where then should I report the restoration of the deleted zone with the previous nameservers, or where should I report the update of the assigned new auto generated nameservers for the deleted domain, or where should I report the restoration of the ability to look at the domain settings in the dash panel to transfer it to another registrar?

**Comment by jacobbednarz** [comment]
if you have a customer support ticket, i would definitely raise it there as it will already have support and engineering resources assigned to it and will be able to handle the restoration or move for you.

**Comment by garis-space** [comment]
@jacobbednarz I opened a support ticket (ID 3078480) and the problem was resolved. In the open ticket, I received information that an internal ticket was opened with the CF Registrar team. It took a couple of days to solve my problem.

In my opinion, the possibility of deleting zones for domains that are registered/transferred to Cloudflare should be patched.
