### ISSUE TITLE
mitigation_timeout optional value must be set

### ISSUE THREAD

**Issue by Deku-shrub** [cloudflare/terraform-provider-cloudflare#3059]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF 5.20.1
CF 4.11

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "limit_connections" {
  count       = var.environment == "dev" ? 0 : 1
  zone_id     = data.cloudflare_zone.cf_zone.id
  name        = "limit websocket connections"
  description = "limit websocket connections"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    action = "block"
    ratelimit {
      characteristics = ["ip.src","cf.colo.id"]
      period              = 10
      requests_per_period = 2
    }
    expression = "(http.host eq \"streams.fast.${var.domain_prefix}${var.domain}\" and any(lower(http.request.headers.names[*])[*] contains \"connection\") and any(lower(http.request.headers.values[*])[*] contains \"upgrade\"))"
    enabled = true
  }
}
```

### Link to debug output

did not do

### Panic output

did not do

### Expected output

Apply

### Actual output
```
Error: Provider produced inconsistent result after apply
When applying changes to cloudflare_ruleset.limit_connections[0], provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].ratelimit[0].mitigation_timeout: was null, but now cty.NumberIntVal(0).

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
### Steps to reproduce

Create a cloudflare_ruleset with phase http_ratelimit

Create a rule with ratelimit but do not set any value for mitigation_timeout

### Additional factoids

Workaround is to manually set "mitigation_timeout = 0" within "ratelimit"

**Comment by jacobbednarz** [comment]
this is already fixed in newer versions of the provider.
