### ISSUE TITLE
rulesets: Support sensitivity_level for rules.action_parameters.overrides.categories

### ISSUE THREAD

**Issue by jamesog** [cloudflare/terraform-provider-cloudflare#3063]
### Current Terraform and Cloudflare provider version

Terraform v1.4.6
Provider version 4.22.0

### Description

The [API documentation](https://developers.cloudflare.com/ddos-protection/managed-rulesets/http/configure-api/) for configuring DDoS rulesets says you can configure rulesets using `categories`:

```json
{
  "description": "Execute HTTP DDoS Attack Protection managed ruleset in the zone-level phase entry point ruleset",
  "rules": [
    {
      "action": "execute",
      "action_parameters": {
        "id": "<MANAGED_RULESET_ID>",
        "overrides": {
          "sensitivity_level": "medium",
          "action": "managed_challenge",
          "categories": [
            {
              "category": "<TAG_NAME>",
              "sensitivity_level": "low"
            }
          ],
          "rules": [
            {
              "id": "<MANAGED_RULESET_RULE_ID>",
              "action": "block"
            }
          ]
        }
      },
      "expression": "true"
    }
  ]
}
```

The current version of the provider (4.22.0 at time of writing) [does not support `sensitivity_level` in the `categories` object](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset#nested-schema-for-rulesaction_parametersoverridescategories).

Assuming the API documentation is correct, can the provider add this support?

### Use cases

Create DDoS rulesets that override the sensitivity level for an entire category of rules.

### Potential Terraform configuration

```hcl
resource "cloudflare_ruleset" "zone_level_http_ddos_config" {
  zone_id     = "zone id"
  name        = "HTTP DDoS Attack Protection entry point ruleset"
  description = ""
  kind        = "zone"
  phase       = "ddos_l7"

  rules {
    action      = "execute"
    expression  = "true"
    description = "Overrides for ..."
    enabled     = true
    expression  = "..."
    action_parameters {
      id = "id"
      overrides {
        sensitivity_level = "eoff"
        categories {
          category = "botnets"
          sensitivity_level = "low"
        }
      }
    }
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
