### ISSUE TITLE
cloudflare_tunnel data source returning inactive tunnel with same name

### ISSUE THREAD

**Issue by davidholsgrove** [cloudflare/terraform-provider-cloudflare#3069]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.20.0
+ provider registry.terraform.io/hashicorp/google v5.12.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/hashicorp/vault v3.24.0

### Affected resource(s)

data cloudflare_tunnel
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/tunnel

### Terraform configuration files

```hcl
data "cloudflare_tunnel" "example" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "my-tunnel"
}
```

### Link to debug output

None

### Expected output

The data lookup should return the active tunnel, not an older inactive and deleted tunnel

### Actual output

The API call used by the data resource returns multiple results, and a single one is selected offering no way to further filter (by status etc)

### Steps to reproduce

Create and delete a tunnel multiple times with the same name, then review the tunnel ID returned in a data resource

**Comment by jacobbednarz** [comment]
moving to an enhancement as this is working as expected. adding filters to the data source is an improvement now that they exist.

**Comment by PavelPikat** [comment]
I would argue that this is a serious bug and not an enhancement.
I have a tunnel in the account and the `cloudflare_tunnel` data source returns me wrong ID, not the one that I can see in the Web UI.
The ID that the Terraform gives me cannot be found anywhere. This is critical to us, as we are unable to hook up our automation when tunnel IDs returned by the provider don't actually exist. It's impossible to create any kind of DNS records with invalid tunnel IDs. Can this be prioritized please @jacobbednarz

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
