### ISSUE TITLE
Document default values for all optional attributes

### ISSUE THREAD

**Issue by gavinclarkeuk** [cloudflare/terraform-provider-cloudflare#3070]
### Current Terraform and Cloudflare provider version

Terraform 1.7.0, Provider 4.22.0 (latest)

### Description

The provider documentation should clearly state what the default value of any optional attributes is, in keeping with other providers.

For example I'm just in the process of migrating to the new `cloudflare_rules` and I'm wondering if I can simplify clean up the generated code, for example by removing all the `enabled = true` in the jested rules blocks. The docs just tell me that attribute is optional, but don't state what the default is.

### Use cases

All

### Potential Terraform configuration

N/A

**Comment by jacobbednarz** [comment]
the `default` values are only rendered in the documentation when the schema is the only providing the value. in most cases, the ruleset engine has hidden defaults whereby if you don't set anything, the default it used and is only shown when the value is modified. we don't have any further insight into those values until they are changed.
