### ISSUE TITLE
support virtual_network_id on cloudflare_load_balancer_pool origins

### ISSUE THREAD

**Issue by sgarlick987** [cloudflare/terraform-provider-cloudflare#3087]
### Current Terraform and Cloudflare provider version

Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.22.0

### Description

Currently if you try to use a private ip address for `cloudflare_load_balancer_pool` `origins.address` you'll get this error 

```Error: error updating load balancer pool: Origin address is invalid or is not globally routable and has health monitoring enabled: validation failed (1002)```

### Use cases

I want to use origins with the `cloudflare_load_balancer_pool` resource that are private ips and need to include `virtual_network_id` described in the api doc https://developers.cloudflare.com/api/operations/account-load-balancer-pools-create-pool

### Potential Terraform configuration

```hcl
resource "cloudflare_load_balancer_pool" "example" {
  name       = "example-pool"
  origins {
    name    = "example"
    address = "172.18.210.108"
    virtual_network_id = "xxxxxxxxxxx"
  }
}
```

**Comment by sgarlick987** [comment]
I tried out this on my dev machine which seems to work, but wasn't sure what would also need to be updated in terms of docs/tests/etc.

 https://github.com/sgarlick987/terraform-provider-cloudflare/commit/12f0c42588daf7e041b6b2061207c718595534f5

**Comment by Nmishin** [comment]
hi @sgarlick987  feel free to create the MR with your change and I can help you if you want to.
for your MR please add:
- changelog file, like described here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/changelog-process.md
- documentation update.  Documentation created/updated automatically, you only need to run `make docs` in the root of project.
- it will be perfect if you can update tests here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/resource_cloudflare_load_balancer_pool_test.go
You can run tests locally as described here: https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/development.md
But be careful - tests will create real resources in your account.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by Sceptyre** [comment]
@jacobbednarz Is there any reason we couldn't submit a PR to correct for this issue? The Cloudflare API exposes this functionality and it exists upstream in the cloudflare-go client package. Assuming there is no issue with that, I'd love to get this added in.
