### ISSUE TITLE
Add support for Hyperdrive

### ISSUE THREAD

**Issue by carlos-alberto** [cloudflare/terraform-provider-cloudflare#3092]
### Current Terraform and Cloudflare provider version

latest

### Description

Add support for managing hyperdrive resources. (https://github.com/cloudflare/cloudflare-go/issues/1491)

### Use cases

I would like to be able to manage my Hyperdrive resources using terraform.

### Potential Terraform configuration

```hcl
resource "cloudflare_hyperdrive" "example" {
  account_id = "some account id"
  name          = "example"
  origin          = {
    database      = "postgres"
    host         = "db.example.com"
    port         = 5432
  }
  caching     = {
    disabled = false
    etc...
  }
}
```

### References

https://github.com/cloudflare/cloudflare-go/issues/1491

**Comment by carlos-alberto** [comment]
Given https://github.com/cloudflare/cloudflare-go/issues/1491 is now merged I would like to take a pass at this.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
