### ISSUE TITLE
terraform cloudflare_turnstile_widget Error reading challenge widget when offlabel=true

### ISSUE THREAD

**Issue by MagonBC** [cloudflare/terraform-provider-cloudflare#3093]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform **v1.7.1**

Provider cloudflare/cloudflare **v4.16.0** and **v4.23.0**

### Affected resource(s)

cloudflare_turnstile_widget

### Terraform configuration files

```hcl
resource "cloudflare_turnstile_widget" "main" {
  account_id = "05frrr5f66s5ss5568fe"
  name       = "Example Widget"
  domains    = "[mydomain.com]"
  mode       = "non-interactive"
  offlabel   = "true"
}
```

### Link to debug output

https://gist.github.com/MagonBC/6b05a7006e792f9a59e0db31bde5da6f

### Expected output

Terraform will perform the following actions:

  # cloudflare_turnstile_widget.main will be updated in-place
  ~ resource "cloudflare_turnstile_widget" "main" {
      ~ bot_fight_mode = false -> (known after apply)
        id             = "0xthesite_key"
        name           = "Example Widget"
      ~ offlabel       = false -> true
      ~ region         = "world" -> (known after apply)
      ~ secret         = (sensitive value)
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_turnstile_widget.main: Modifying... [id=thesite_key]
cloudflare_turnstile_widget.main: Modifications complete after 1s [id=thesite_key]

### Actual output

╷
│ Error: Error reading challenge widget
│
│   with cloudflare_turnstile_widget.main,
│   on [main.tf](http://main.tf/) line 1, in resource "cloudflare_turnstile_widget" "main":
│    1: resource "cloudflare_turnstile_widget" "main" {
│
│ required site key missing
╵

### Steps to reproduce

With Turnstile Widget license free: (https://www.cloudflare.com/products/turnstile/)

1. set offlabel=true
2. terraform apply
3. reset offlabel=false
4. terraform apply

With Enterprise License:

5. terraform apply
6. set offlabel=true
7. terraform apply

**Comment by ingack99** [comment]
Can you set true instead of "true" in the terraform config?

**Comment by snstamml** [comment]
> Can you set true instead of "true" in the terraform config?

It's not related to the `"true"`. I've the same issue, but use booleans without quotes.

**Comment by JohnyGemityg** [comment]
Hello, have you find any workaround? I am getting the same error no matter what arguments I combine. I am using enterprise version.
