### ISSUE TITLE
cloudflare_ruleset wrong documentation

### ISSUE THREAD

**Issue by danieleturani** [cloudflare/terraform-provider-cloudflare#3097]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
$ terraform -v
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.23.0
+ provider registry.terraform.io/hashicorp/aws v5.33.0

Your version of Terraform is out of date! The latest version
is 1.7.2. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "test_rule" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_firewall_custom"
  zone_id = REDACTED

  rules {
    action      = "skip"
    description = "test"
    enabled     = false
    expression  = "(http.host eq \"www.example.com\")"
    action_parameters {
      phases   = [
        "http_ratelimit",
        "http_request_firewall_managed",
        "http_request_sbfm",
      ]
      products = [
        "bic",
        "hot",
        "ratelimit",
        "uablock",
        "securityLevel",
        "waf",
      ]
      ruleset  = "current"
    }
    logging {
      enabled = true
    }
  }
}
```

### Link to debug output

not relevant

### Expected output

successful terraform apply command

### Actual output

cloudflare_ruleset.test_rule: Modifying... [id=0124ba20d98242f0ae961af813b27e3d]
╷
│ Error: error updating ruleset with ID "0124ba20d98242f0ae961af813b27e3d"
│
│   with cloudflare_ruleset.test_rule,
│   on ruleset.tf line 22, in resource "cloudflare_ruleset" "test_rule":
│   22: resource "cloudflare_ruleset" "test_rule" {
│
│ skip action parameter product 'ratelimit' is invalid (20119), skip action parameter product
│ 'uablock' is invalid (20119)
╵

### Steps to reproduce

1. add a rule with `ratelimit` and `uablock` in `products`
2. apply configuration with `terraform apply`

### Additional factoids

documentation is wrong, the correct values for `products` are:

- `rateLimit` and not `ratelimit`
- `uaBlock` and not `uablock`

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/ruleset

**Comment by koshkin-ccna** [comment]
https://developers.cloudflare.com/waf/tools/user-agent-blocking/

Cloudflare recommends that you create [WAF custom rules](https://developers.cloudflare.com/waf/custom-rules/) instead of User Agent Blocking rules to block specific user agents.
