### ISSUE TITLE
Cloudflare_pages_project terraform resource deploy a page after creation

### ISSUE THREAD

**Issue by hndoss** [cloudflare/terraform-provider-cloudflare#3099]
### Current Terraform and Cloudflare provider version

Terraform v1.7.2
Cloudflare provider version 4.23.0

### Description

After creating a Page project with the cloudflare_pages_project Terraform resource, the page can’t be accessed due to the following message "This project has not been deployed" when the static HTML is hosted in a Git repository. Can the provider also manage the first deployment? 

### Use cases

- Remove human intervention when deploying Cloudflare pages

### Potential Terraform configuration

I think it should be the default behavior. I mean, after creating a Page project in Cloudflare, is understandable that the user is expecting a deployed project instead of having to click a deploy button in the Cloudflare's console.

### References

https://community.cloudflare.com/t/cloudflare-pages-project-terraform-resource-doesnt-deploy-a-page-after-creation/609016?u=hndoss

**Comment by savelichalex** [comment]
Just want to post a workaround I did in my project

```
resource "null_resource" "deploy" {
  triggers = {
    always_run = "${timestamp()}"
  }

  provisioner "local-exec" {
    command = "cd ../app && envsubst < wrangler.template.toml > wrangler.toml && yarn build && yarn deploy --project-name $PROJECT_NAME"

    environment = {
      PROJECT_NAME = local.PROJECT_NAME
      CLOUDFLARE_ACCOUNT_ID = var.cloudflare_account_id
      PROJECT_KV_ID = cloudflare_workers_kv_namespace.app-kv-ns.id
      PROJECT_D1_NAME = local.D1_NAME
      PROJECT_D1_ID = cloudflare_d1_database.app-cms-db.id
      PROJECT_R2_NAME = local.R2_NAME
    }
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by mistuttodos** [comment]
I am surprised there aren't more people posting about this... It's truly the missing piece.


@jacobbednarz any news? :)

**Comment by kornelkalnai** [comment]
Any new on it?

**Comment by discapes** [comment]
i would definitely appreciate this feature!

**Comment by discapes** [comment]
Workaround:
```terraform
resource "terraform_data" "trigger_initial_deploy" {
  for_each = cloudflare_pages_project.repos

  triggers_replace = [
    each.value.id
  ]

  provisioner "local-exec" {
    command = <<EOT
      curl -X POST "https://api.cloudflare.com/client/v4/accounts/${each.value.account_id}/pages/projects/${each.value.name}/deployments" \
           -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
           -H "Content-Type: application/json" \
           --data '{"branch":"${each.value.production_branch}"}'
    EOT
    environment = {
      CLOUDFLARE_API_TOKEN = var.cloudflare_api_token
    }
  }
}
```
