### ISSUE TITLE
Unnecessary diffs for cloudflare_record — broken escaping in API

### ISSUE THREAD

**Issue by RyanGWU82** [cloudflare/terraform-provider-cloudflare#3101]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7 (via Terraform Cloud)
Cloudflare provider v4.23.0

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "caa_google_issue" {
  zone_id = var.zone_id
  name    = var.name
  type    = "CAA"
  ttl     = 1  # automatic

  data {
    flags   = "0"
    tag     = "issue"
    value   = "pki.goog; cansignhttpexchanges=yes"
  }
}
```

### Link to debug output

https://gist.githubusercontent.com/jacobbednarz/f6dd08daeceddf8ede80bd46a1b68dd5/raw/aa019be423a69bd201303bedbd3f76bf011b7059/gistfile1.txt

### Expected output

The record is already set to `pki.goog; cansignhttpexchanges=yes`, so this resource should not change.

### Actual output

```
Terraform will perform the following actions:

  # module.ssl_readmessl_com_caa_records.cloudflare_record.caa_google_issue will be updated in-place
  ~ resource "cloudflare_record" "caa_google_issue" {
        id              = "f1e29dad7254c36efc5f3c33d0d71cb2"
        name            = "ssl"
        tags            = []
        # (11 unchanged attributes hidden)

      ~ data {
          ~ value          = "pki.goog\\; cansignhttpexchanges=yes" -> "pki.goog; cansignhttpexchanges=yes"
            # (25 unchanged attributes hidden)
        }
    }
```

### Steps to reproduce

1. Create a Terraform `cloudflare_record` with a `;` in it, like the example in the HCL above. 
2. Apply the change with Terraform, so that the record exists on Cloudflare.
3. Run a new `terraform plan` or `terraform apply`. Cloudflare reports the value is `pki.goog\; cansignhttpexchanges=yes` with a backslash in front of the semicolon. Terraform thinks it needs to fix the record even though nothing has changed.

### Additional factoids

I believe the problem is actually in the Cloudflare REST API — the API is incorrectly escaping `;` in DNS records. We can see this by issuing a `GET` to `https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID` from an HTTP client like cURL or Postman. Here's what the API returns:

```json
{
  "result": {
    "id": "9044fd4dac7a9d7836e64ffd3e740250",
    "zone_id": "abcb08f320033939f52b7577b156ac48",
    "zone_name": "readmessl.com",
    "name": "ssl.readmessl.com",
    "type": "CAA",
    "content": "0 issuewild \"pki.goog; cansignhttpexchanges=yes\"",
    "proxiable": false,
    "proxied": false,
    "ttl": 1,
    "locked": false,
    "data": {
      "flags": 0,
      "tag": "issuewild",
      "value": "pki.goog\\; cansignhttpexchanges=yes"
    },
    "meta": {
      "auto_added": false,
      "managed_by_apps": false,
      "managed_by_argo_tunnel": false,
      "source": "primary"
    },
    "comment": null,
    "tags": [],
    "created_on": "2022-07-19T23:28:33.206276Z",
    "modified_on": "2023-06-08T17:20:14.808236Z"
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

The `result.content` field shows the correct value, but `result.data.value` has a backslash before the semicolon. That backslash is not necessary for JSON escaping; semicolons aren't a special character in JSON.

`dig` also confirms that our records don't really have backslashes in them:

```
$ dig ssl.readmessl.com CAA

; <<>> DiG 9.10.6 <<>> ssl.readmessl.com CAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54017
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;ssl.readmessl.com.		IN	CAA

;; ANSWER SECTION:
ssl.readmessl.com.	300	IN	CAA	0 issuewild "letsencrypt.org"
ssl.readmessl.com.	300	IN	CAA	0 issuewild "pki.goog; cansignhttpexchanges=yes"
ssl.readmessl.com.	300	IN	CAA	0 issue "comodoca.com"
ssl.readmessl.com.	300	IN	CAA	0 issue "digicert.com"
ssl.readmessl.com.	300	IN	CAA	0 issue "letsencrypt.org"
ssl.readmessl.com.	300	IN	CAA	0 issue "pki.goog; cansignhttpexchanges=yes"
ssl.readmessl.com.	300	IN	CAA	0 issuewild "comodoca.com"
ssl.readmessl.com.	300	IN	CAA	0 issuewild "digicert.com"

;; Query time: 42 msec
;; SERVER: 2001:5a8:42a1:8100::1#53(2001:5a8:42a1:8100::1)
;; WHEN: Fri Feb 02 10:44:43 PST 2024
;; MSG SIZE  rcvd: 360
```

**Comment by RyanGWU82** [comment]
I was able to generate a debug log for Terraform Cloud by setting the workspace variable `TF_LOG` in their UI. Here is the debug log for this command:

```
TF_LOG=DEBUG terraform plan -target=module.ssl_readmessl_com_caa_records.cloudflare_record.caa_google_issue > debug.log 2>&1
```

[debug.log](https://github.com/cloudflare/terraform-provider-cloudflare/files/14144238/debug.log)

**Comment by jacobbednarz** [comment]
this has been addressed by the internal service team and should no longer be quoted.
