### ISSUE TITLE
cloudflare_custom_ssl resource times out when its zone does not have an "active" status

### ISSUE THREAD

**Issue by bbush-uthealth** [cloudflare/terraform-provider-cloudflare#3114]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ terraform -v 
Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.21.0
+ provider registry.terraform.io/hashicorp/vault v3.24.0

### Affected resource(s)

cloudflare_custom_ssl
cloudflare_zone

### Terraform configuration files

```hcl
# I made the resource names generic to protect the org but this is our exact config that is breaking
resource "cloudflare_zone" "zonename" {
  account_id = cloudflare_account.organization.id
  paused     = false
  plan       = "enterprise"
  type       = "partial"
  zone       = "valid.domain.name"
}

resource "cloudflare_custom_ssl" "zonename" {
  zone_id = cloudflare_zone.zonename.id
  custom_ssl_options {
    certificate      = data.vault_generic_secret.certificate.data["contents"]
    private_key      = data.vault_generic_secret.private-key.data["contents"]
    bundle_method    = "ubiquitous"
    geo_restrictions = "us"
    type             = "sni_custom"
  }
}
```

### Link to debug output

I'm a bit hesitant to post my debug log here as there are tons of resource names that are not anonymized. Can someone contact me for a better way to provide the debug log?

### Panic output

n/a

### Expected output

I expect the custom_ssl to create the certificate and show up in the terraform state file regardless of the cloudflare_zone.zonename.status value.  (See additional factoids.)

### Actual output

Creating the cloudflare_custom_ssl resource times out after 20 minutes leaving the terraform state mismatched with what's live in cloudflare. This is the error it provides:

│ Error: waiting for certificate to become active
│ 
│   with cloudflare_custom_ssl.zonename,
│   on cloudflare_zone_zonename.tf line 71, in resource "cloudflare_custom_ssl" "zonename":
│   71: resource "cloudflare_custom_ssl" "zonename" {
│ 

### Steps to reproduce

1. Create the two resource stanzas I defined above in the "Terraform configuration files" section for a site/zone that is not yet setup in Cloudflare.
2. Run terraform apply and say yes when prompted (or add -auto-approve).
3. Wait 20 minutes for the operation to time out.

Now your tf state will not include the certificate because terraform doesn't think it was created.

### Additional factoids

The certificate does get created despite terraform timing out in its efforts, but it's marked as "Holding Deployment", which means I also have to manually delete the certificate before I can try again (we are only allowed 1 custom SSL per site). The issue happens when the cloudflare_zone resource is new and the zone gets created with the cloudflare_zone.zonename.status not "active".  Once DNS validation is done by entering the TXT record and waiting for Cloudflare to recognize it, the zone status changes to "active" and a new custom_ssl resource works as expected.

**Comment by bbush-uthealth** [comment]
debug log was delivered out-of-band

**Comment by bbush-uthealth** [comment]
updated provider module today and it's still occurring.

$ terraform --version
Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.24.0
+ provider registry.terraform.io/hashicorp/vault v3.24.0

**Comment by cf-scott** [comment]
For the maintainers, please contact me in CSUP (U.S.) if you did not receive the debug log file.
