### ISSUE TITLE
R2 Object Lifecycle Management

### ISSUE THREAD

**Issue by missinglink** [cloudflare/terraform-provider-cloudflare#3120]
### Current Terraform and Cloudflare provider version

```
terraform -v
Terraform v1.7.3

ls .terraform/providers/registry.terraform.io/cloudflare/cloudflare/4.20.0
```

### Description

I would like to configure 'Object Lifecycle Management' as described in this post:
https://blog.cloudflare.com/introducing-object-lifecycle-management-for-cloudflare-r2

### Use cases

Configuring with terraform avoids using the cloudflare website and the mouse.

### Potential Terraform configuration

```hcl
...
```

### References

I was not able to find any references or open GH issues.

**Comment by jacobbednarz** [comment]
dupe of #2751
