### ISSUE TITLE
Provider produced inconsistent result after apply (for cloudflare_list_item)

### ISSUE THREAD

**Issue by daria-arc** [cloudflare/terraform-provider-cloudflare#3121]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

I am trying to move from 4.14 to 4.24

### Affected resource(s)

cloudflare_list_item

### Terraform configuration files

```hcl
resource "cloudflare_list_item" "redirect_community" {
  account_id = var.cloudflare_account_id
  list_id    = cloudflare_list.redirect_rule_list_site_com.id
  redirect {
    source_url           = "community.site.com"
    target_url           = "https://ask.site.com"
    status_code          = 301
    subpath_matching     = false
    preserve_path_suffix = false
  }
}
```

### Link to debug output

[Debug log](https://gist.github.com/daria-arc/39706b1bc1ef2f319bcb4cb0a2fee9dc)

### Expected output

I expected `terraform plan` to just work

### Actual output

```
Error: Provider produced inconsistent result after apply
When applying changes to cloudflare_list_item.redirect_community, provider
"provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an
unexpected new value: .redirect[0].source_url: was
cty.StringVal("community.site.com"), but now
cty.StringVal("community.site.com/").
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to reproduce

1.
```
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
-     version = "~> 4.4"
+     version = "~> 4.24"
    }
  }
  
  resource "cloudflare_list_item" "redirect_community" {
  account_id = var.cloudflare_account_id
  list_id    = cloudflare_list.redirect_rule_list_site_com.id
  redirect {
    source_url           = "community.site.com"
    target_url           = "https://ask.site.com"
    status_code          = 301
-   subpath_matching     = "disabled"
-   preserve_path_suffix = "disabled"
+   subpath_matching     = false
+   preserve_path_suffix = false
  }
}
```

**Comment by daria-arc** [comment]
Here is the debug log: https://gist.github.com/daria-arc/39706b1bc1ef2f319bcb4cb0a2fee9dc

**Comment by jacobbednarz** [comment]
the drift here is because of the `source_url` value difference. locally it has `example.com` however, the API service is returning `example.com/`. adding the trailing slash makes this reproduction case so no drift. i assume this is because the trailing slash is used as part of the URL matching mentioned at https://developers.cloudflare.com/rules/url-forwarding/bulk-redirects/reference/parameters/ ?

**Comment by daria-arc** [comment]
Thank you for the help, it fixes problem for me! Though the error message is very obscure.
