### ISSUE TITLE
cloudflare_dlp_profile entry.enabled is not resulting in a change 

### ISSUE THREAD

**Issue by mat-foreseemed** [cloudflare/terraform-provider-cloudflare#3123]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform version 
Terraform v1.6.3
on darwin_arm64
provider registry.terraform.io/cloudflare/cloudflare v4.24.0

### Affected resource(s)

cloudflare_dlp_profile

### Terraform configuration files

```hcl
resource "cloudflare_dlp_profile" "creds" {
  account_id          = var.account_id
  name                = "Credentials and Secrets"
  type                = "predefined"
  allowed_match_count = 0

  entry {
    enabled = true
    id      = "2c0e33e1-71da-40c8-aad3-32e674ad3d96"
    name    = "Amazon AWS Secret Access Key"
  }
  entry {
    enabled = false
    id      = "4e92c006-3802-4dff-bbe1-8e1513b1c92a"
    name    = "Microsoft Azure Client Secret"
  }
  entry {
    enabled = true
    id      = "5c713294-2375-4904-abcf-e4a15be4d592"
    name    = "SSH Private Key"
  }
  entry {
    enabled = false
    id      = "6c6579e4-d832-42d5-905c-8e53340930f2"
    name    = "Google GCP API Key"
  }
  entry {
    enabled = true
    id      = "d8fcfc9c-773c-405e-8426-21ecbb67ba93"
    name    = "Amazon AWS Access Key ID"
  }
}
```

### Link to debug output

https://gist.github.com/mat-foreseemed/31f64ddbfd439a3689e41b3bdac8e114

### Expected output

terraform plan should result in a change to the entry. 

### Actual output

Terraform is not detecting a change to the infrastructure when I change disabled to enabled

### Steps to reproduce

1. Create cloudflare_dlp_profile resource, match the name of the predefined profiles
2. import the resource 
3. adjust entry.enabled from false to true. 

### Additional factoids

It seems like some work was recently done on this resource it's possible this is the source of the error. No evidence though. 

https://github.com/cloudflare/terraform-provider-cloudflare/pull/3090

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/3090

**Comment by jacobbednarz** [comment]
please provide the actual debug log and this can be triaged.
