### ISSUE TITLE
ACM is already supported via [`cloudflare_certificate_pack`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack). you can check the docs for usage and examples.

### ISSUE THREAD

**Issue by quinndiggitypolymath** [cloudflare/terraform-provider-cloudflare#3126]
ACM is already supported via [`cloudflare_certificate_pack`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack). you can check the docs for usage and examples.

_Originally posted by @jacobbednarz in https://github.com/cloudflare/terraform-provider-cloudflare/issues/1867#issuecomment-1229134387_

`cloudflare_certificate_pack` ACM subscription management is broken

Affected:
- cloudflare_certificate_pack
- cloudflare_zone_settings_override

Expected output:
```
Modifications complete after Ns
```
Actual output:
```
Error: failed to create certificate pack: Access to configure this resource has not been granted for this zone. This feature is available with the Advanced Certificate Manager. (1450): Access to configure this resource has not been granted for this zone. This feature is available with the Advanced Certificate Manager. (1450)
```
Steps to repro:
- Utilize `cloudflare_certificate_pack` as [documented](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack) and described by @jacobbednarz @ https://github.com/cloudflare/terraform-provider-cloudflare/issues/1867

**Comment by Cyb3r-Jak3** [comment]
Advanced Certificate Manager is an additional add-on, If you have purchased it, and it is not enabled then you should open a billing ticket with Cloudflare support.

**Comment by quinndiggitypolymath** [comment]
> Advanced Certificate Manager is an additional add-on, If you have purchased it, and it is not enabled then you should open a billing ticket with Cloudflare support.

The issue is not whether the add-on is enabled *after* manually enabling it - the issue is having literally *one* aspect of a cloudflare account which is not managed with configuration as code/enforces auditability/facilitates change control management (per `SOC 2`, etc..).

The problem is that this shortcoming of the terraform cloudflare provider leads to the requirement of a manual change needing to be applied + monitored, and, for example, when cleaning up an add-on which has been migrated to a different account/zone/etc, having an additional manual step (which will inevitably be forgotten).

Is cloudflare's intention to bill their customers for features they no longer require/or doubly so when it is no longer required for a particular zone?

I'm not sure where the misunderstanding is coming from here - @jacobbednarz / @Cyb3r-Jak3 , are you genuinely convinced that the users of this terraform provider are half-wits who have no idea what they are requesting?

**Comment by quinndiggitypolymath** [comment]
As described *already* in https://github.com/cloudflare/terraform-provider-cloudflare/issues/1867#issue-1352779170 by @kaplanmaxe :
```
this has to be done completely manually in the UI. As you scale to 50+ ... having to do this manually through the UI forces you into access control patterns where humans still need access to the UI.
```

**Comment by jacobbednarz** [comment]
@quinndiggitypolymath i would highly recommend reevaluating your tone and approach here. regardless of if there has been the wildest of misunderstandings, your response is unwarranted. the internals of Cloudflare are not straight forward and there has obviously been some ambiguity understanding how this feature works.

the reason the issue was closed is because there is no API to swap to ACM. it's an add on subscription or a part of your enterprise contract. ability to manage your subscription is not publicly available today. the only difference (once that subscription is enabled) is that the `type` is now "advanced" instead of "dedicated". both of which are already handled by the resource with various configuration attributes.

**Comment by kaplanmaxe** [comment]
Hey @jacobbednarz - I originally opened the request months ago. I no longer work at the company where I was looking to use this. But to elaborate a bit more:

I get what you're saying that ACM is an enterprise subscription. I think the part you might be missing though is I would have liked to opt into that subscription via terraform. For example, I can change the plan of a zone via terraform. I can't however opt into ACM via terraform. If there's no API, there's no API. But I hope that makes a bit more sense.

At my previous employer, no single human had any write access to Cloudflare's dashboard. This was fantastic for security. Everyone at best was Admin - Read Only and we had 50+ zones across several accounts where literally every single resource was terraformed. It works great for audits.

However, it's annoying to have to temporarily change the permissions of a user just to opt into ACM. Your comment on the original ticket didn't solve my issue. But what I described in this comment is what I was looking for at the time.

**Comment by jacobbednarz** [comment]
@kaplanmaxe that's a great security practice! in most cases, customers have their account team handle entitling zones where that constraint or restriction is required for high security environments. 

to reiterate, ACM isn't only part of an enterprise contract; it can be added to any plan but it is an additional subscription. we don't have subscriptions exposed publicly today due to a laundry list of security and UX constraints which need to be addressed before we can even consider allowing customers to self serve.

**Comment by quinndiggitypolymath** [comment]
> there is no API to swap to ACM. it's an add on subscription

https://developers.cloudflare.com/api/operations/zone-subscription-update-zone-subscription#request-body

# Update Zone Subscription
```
component_values: array[object]
    The list of add-ons subscribed to.

name: string
    The name of the component value.
    Example: page_rules
```

> @quinndiggitypolymath i would highly recommend reevaluating your tone and approach here
![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/8d719ad4-172d-44e7-8bba-40e296bb5326)

@jacobbednarz :point_up: perhaps before you advise others to reevaluate their approach, you considering reading + understanding what shortcoming has been pointed out, prior to you writing it off/avoiding the work necessary to either work with the community to fix the problem or otherwise allocate the time to fix it yourself.

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/ca763e78-4818-4db9-8e1e-314f92a5fc8f)

:point_up: the reason why people end up being frustrated with having to repeat their explanation (which @kaplanmaxe *did* in fact explain both precisely and elegantly), is because they get responses such as this :point_down: 

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/699d8010-2d72-4268-9a31-2c516c169892)

When the community is the one providing `kind/support` to _you_ because you don't have the motivation/capability to acknowledge the shortcoming, the one needing to consider their tone/approach is @jacobbednarz

**Comment by quinndiggitypolymath** [comment]
> there is no API to swap to ACM. it's an add on subscription

https://developers.cloudflare.com/api/operations/zone-subscription-update-zone-subscription#request-body

# Update Zone Subscription
```
component_values: array[object]
    The list of add-ons subscribed to.

name: string
    The name of the component value.
    Example: page_rules
```

> @quinndiggitypolymath i would highly recommend reevaluating your tone and approach here
![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/8d719ad4-172d-44e7-8bba-40e296bb5326)

@jacobbednarz :point_up: perhaps before you advise others to reevaluate their approach, you considering reading + understanding what shortcoming has been pointed out, prior to you writing it off/avoiding the work necessary to either work with the community to fix the problem or otherwise allocate the time to fix it yourself.

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/ca763e78-4818-4db9-8e1e-314f92a5fc8f)

:point_up: the reason why people end up being frustrated with having to repeat their explanation (which @kaplanmaxe *did* in fact explain both precisely and elegantly), is because they get responses such as this :point_down: 

![image](https://github.com/cloudflare/terraform-provider-cloudflare/assets/64798147/699d8010-2d72-4268-9a31-2c516c169892)

When the community is the one providing `kind/support` because you don't have the motivation to acknowledge the shortcoming, the one needing to consider their tone/approach is @jacobbednarz

**Comment by quinndiggitypolymath** [comment]
> there is no API to swap to ACM. it's an add on subscription

https://developers.cloudflare.com/api/operations/zone-subscription-update-zone-subscription#request-body

# Update Zone Subscription
```
component_values: array[object]
    The list of add-ons subscribed to.

name: string
    The name of the component value.
    Example: page_rules
```
