### ISSUE TITLE
cloudflare_ruleset for rate_limit does not set the name right

### ISSUE THREAD

**Issue by gugdewescale** [cloudflare/terraform-provider-cloudflare#3130]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.7.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.24.0
+ provider registry.terraform.io/hashicorp/google v5.16.0

### Affected resource(s)

- cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "rate_limit" {
  zone_id     = data.cloudflare_zone.this.id
  name        = "Rate limiting to prevent DDOS"
  description = "Rate limiting to prevent DDOS"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    action = "block"
    ratelimit {
      characteristics = ["cf.colo.id", "ip.src"]
      period = 300
      requests_per_period = 10000
      mitigation_timeout = 600
    }
    expression = "cf.zone.plan eq \"ENT\""
    enabled = true
  }
}
```

### Link to debug output

https://gist.github.com/gugdewescale/067f61872494f076a56b44fb270f6410

### Expected output

The output is right in Terraform but the result is not right in Cloudflare.

The name I set is not right. Instead there is a random generated ID.

If I modify the random generated name with a new one and trigger a Terraform plan I get no modifications. For Terraform everything is all right.

### Actual output
```
  # module.cloudflare_waf["ulocation"].cloudflare_ruleset.rate_limit will be created
  + resource "cloudflare_ruleset" "rate_limit" {
      + description = "Rate limiting to prevent DDOS"
      + id          = (known after apply)
      + kind        = "zone"
      + name        = "Rate limiting to prevent DDOS"
      + phase       = "http_ratelimit"
      + zone_id     = "[REDACTED]"

      + rules {
          + action       = "block"
          + description  = (known after apply)
          + enabled      = true
          + expression   = "cf.zone.plan eq \"ENT\""
          + id           = (known after apply)
          + last_updated = (known after apply)
          + ref          = (known after apply)
          + version      = (known after apply)

          + ratelimit {
              + characteristics     = [
                  + "cf.colo.id",
                  + "ip.src",
                ]
              + mitigation_timeout  = 600
              + period              = 300
              + requests_per_period = 10000
              + requests_to_origin  = false
            }
        }
    }
```

### Steps to reproduce

1. Terraform apply
2. Check Cloudflare WAF rate limits rules

**Comment by jacobbednarz** [comment]
this isn't an issue with the terraform provider. as the HTTP interactions show, the `name` property is set correctly. if you're seeing it being represented differently in the dashboard, you should open a support ticket to have it escalated to the team to investigate or provide the reasoning.
