### ISSUE TITLE
Sippy configuration

### ISSUE THREAD

**Issue by viraptor** [cloudflare/terraform-provider-cloudflare#3153]
### Current Terraform and Cloudflare provider version

N/A

### Description

Currently it doesn't look like the [sippy](https://developers.cloudflare.com/r2/data-migration/sippy/) configuration is exposed anywhere in the `r2_bucket` or other resources.

### Use cases

It would be nice to have sippy managed without having to invoke wrangler.

### Potential Terraform configuration

?

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
