### ISSUE TITLE
Add DCV zone value to a data source

### ISSUE THREAD

**Issue by danielmotaleite** [cloudflare/terraform-provider-cloudflare#3165]
### Current Terraform and Cloudflare provider version

Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.35.0
+ provider registry.terraform.io/hashicorp/aws v5.1.0

### Description

As per https://github.com/cloudflare/terraform-provider-cloudflare/issues/1052 , the DCV is per zone and not directly from the cloudflare_certificate_pack, so the provider should add a new data source for this value, to be used when needed.

a quick script to the API can fetch the value, it may help to quickly implement  this

```
 curl -s --request GET      --header 'Content-Type: application/json'   -H "X-Auth-Email: ${CLOUDFLARE_EMAIL}" -H "X-Auth-Key: ${CLOUDFLARE_TOKEN}" --url   "https://api.cloudflare.com/client/v4/zones?per_page=50&page=1&account.id=${CLOUDFLARE_ACCOUNT}"  | \
  jq '.result[] | (.name,.id) ' | \
  sed 'N; s/\n/ /g; s/"//g'  | \
  awk '{ print "echo \\\""$1"\\\""; print "curl --request GET      --header \"Content-Type: application/json\"   -H \"X-Auth-Email: ${CLOUDFLARE_EMAIL}\"
 -H \"X-Auth-Key: ${CLOUDFLARE_TOKEN}\" --url https://api.cloudflare.com/client/v4/zones/"$2"/dcv_delegation/uuid    -s | jq \".result.uuid\" "}' | \
  bash  | \
  sed 'N; s/\n/ = /g; s/^/  /g; s/"$/.dcv.cloudflare.com"/g'
```

### Use cases

i have around 50 domains with partial DNS, so i need to use the dcv delegation to be able to generate letsencrypt or google certificates. with the digicert certs deprecation, this is now critical to work automatically

### Potential Terraform configuration

```hcl
...
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by fingalickn** [comment]
Adding support here. We need this and working around it really sucks... there is already an api for it, please prioritize.

**Comment by fingalickn** [comment]
also, closing something as completed when the "resolution" is essentially "we'll think about it, ask us some more in the least transparent way for updates"... tell people if you don't want them to make feature requests here. @jacobbednarz

**Comment by brandonstrohmeyer** [comment]
This might help somebody else in the future, so I wanted to share I was able to work around this by using [terraform-provider-restapi](https://github.com/Mastercard/terraform-provider-restapi)

I chose this versus something like the HTTP data source because I didn't want to pass credentials to my module which creates the Cloudflare resources. It's ugly because the data_source only supports arrays and the Cloudflare API returns an object so you have to trick the `restapi_object` resource into being a data source.

```
provider "restapi" {
  uri                  = "https://api.cloudflare.com/client/v4/"
  write_returns_object = true

  headers = {
    "Authorization" = "Bearer ${var.cloudflare_token}",
    "Content-Type"  = "application/json"
  }
}

resource "restapi_object" "cloudflare_dcv_uuid" {
  path           = "/zones/${var.zone_id}/dcv_delegation/uuid"
  data           = ""
  id_attribute   = "result/uuid"
  create_method  = "GET"
  read_method    = "GET"
  read_path      = "/zones/${var.zone_id}/dcv_delegation/uuid"
  update_method  = "GET"
  update_path    = "/zones/${var.zone_id}/dcv_delegation/uuid"
  destroy_method = "GET"
  destroy_path   = "/zones/${var.zone_id}/dcv_delegation/uuid"
}

output "cloudflare_dcv_uuid" {
  value = jsondecode(restapi_object.cloudflare_dcv_uuid.api_response).result.uuid
}
```

```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

cloudflare_dcv_uuid = "ff132cf6dc333f65"
```

```
❯ terraform state show 'restapi_object.cloudflare_dcv_uuid'

# restapi_object.cloudflare_dcv_uuid:
resource "restapi_object" "cloudflare_dcv_uuid" {
    api_data        = {
        "errors"   = jsonencode([])
        "messages" = jsonencode([])
        "result"   = "map[uuid:ff132cf6dc333f65]"
        "success"  = "true"
    }
    api_response    = jsonencode(
        {
            errors   = []
            messages = []
            result   = {
                uuid = "ff132cf6dc333f65"
            }
            success  = true
        }
    )
    create_method   = "GET"
    create_response = jsonencode(
        {
            errors   = []
            messages = []
            result   = {
                uuid = "ff132cf6dc333f65"
            }
            success  = true
        }
    )
    data            = null
    destroy_method  = "GET"
    destroy_path    = "/zones/<zone_id>/dcv_delegation/uuid"
    id              = "ff132cf6dc333f65"
    id_attribute    = "result/uuid"
    path            = "/zones/<zone_id>/dcv_delegation/uuid"
    read_method     = "GET"
    read_path       = "/zones/<zone_id>/dcv_delegation/uuid"
    update_method   = "GET"
    update_path     = "/zones/<zone_id>/dcv_delegation/uuid"
}

```
