### ISSUE TITLE
Unsupported argument validation_records in cloudflare_certificate_pack

### ISSUE THREAD

**Issue by EdsonLuisVieira** [cloudflare/terraform-provider-cloudflare#3166]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.5
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.26.0

### Affected resource(s)

- cloudflare_certificate_pack

### Terraform configuration files

```hcl
resource "cloudflare_certificate_pack" "example" {
  zone_id                = "0da42c8d2132a9ddaf714f9e7c920711"
  type                   = "advanced"
  hosts                  = ["www.example.com"]
  validation_method      = "txt"
  validity_days          = 90
  certificate_authority  = "google"
  cloudflare_branding    = false
  wait_for_active_status = false
  validation_records = [
    {
      txt_name = "_acme-challenge-www.example.com"
      txt_value = "fixed-value-xpto"
    }
  ]
}
```

### Link to debug output

https://gist.github.com/EdsonLuisVieira/1259dfa255dc8f32b0f6b8d51f9b9a14

### Expected output

resource created with txt values defined for validation

### Actual output

```
Releasing state lock. This may take a few moments...
╷
│ Error: Unsupported argument
│ 
│   on ../../../modules/cloudflare/site/main.tf line 125, in resource "cloudflare_certificate_pack" "this":
│  125:   validation_records = [
│ 
│ An argument named "validation_records" is not expected here. Did you mean to define a block of type "validation_records"?
╵
```

### Steps to reproduce

1. apply the resource to create a new certificate using the optional argument  `validation_records` that exists in [doc](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack)

### Additional factoids

I need to create a certificate where I can define the dns entry and the txt value in advance, looking in the documentation I saw that there was an optional argument validation_records where I imagined that they were only parameters where I could customize my type, but when running the apply I receive the error that the argument is not expected, I am using the latest version of the module and would like to understand if this option works,

**Comment by jacobbednarz** [comment]
this is working as intended; [`validation_records`](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack#validation_records) is a block (not an attribute as you've used) and is [a computed field](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/sdkv2provider/schema_cloudflare_certificate_pack.go#L57-L62). you cannot set this value, only read it once the resource is populated.

**Comment by florianmutter** [comment]
I think the misunderstanding comes from the documentation not listing [validation_records](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/certificate_pack#validation_records) in the read-only section. From the documentation it looks like it could be set on resource creation.
