### ISSUE TITLE
can't create zone with Enterprise plan

### ISSUE THREAD

**Issue by jwillker** [cloudflare/terraform-provider-cloudflare#3169]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.26.0

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
resource "cloudflare_zone" "test-new-format" {
  account_id = "XXXXXX"
  zone = "XXXXXXXX"
  plan       = "enterprise"
}
```

### Link to debug output

https://gist.github.com/jwillker/76a46382b996f4646c31ce371987b408

### Expected output

resource created

### Actual output

╷
│ Error: error setting plan enterprise for zone "4ad58bbe48707e461edc47dfcb5e2aee": Authentication error (10000)
│
│   with cloudflare_zone.teste-new-format,
│   on main.tf line 30, in resource "cloudflare_zone" "teste-new-format":
│   30: resource "cloudflare_zone" "teste-new-format" {
│
╵

### Steps to reproduce

Create a API token from the Super Administrator user, will all permissions with Edit level

Create the resource of the zone with the "Enterprise" Plan.an

### Additional factoids

I have tested manually creating the zone at the Cloudflare console with the Enterprise plan and the same user, and it works.

I can't find what is wrong; I can't find any documentation about what permission level is necessary to create a zone and set the plan.

**Comment by jacobbednarz** [comment]
creating enterprise zones is working (we also have an acceptance test for this); this looks to be an issue with the API token you're using here. you'll likely need to adjust your permissions to use the correct ones or use an API key/email combo.

**Comment by jwillker** [comment]
It only works for me using api_key:

```hcl
provider "cloudflare" {
  api_key            = "XXXXXXXXXXXXXXXX"
  email              = "jhonn.frazao@my-company.comn"
}
```

**Comment by britthouser** [comment]
@jacobbednarz  - I am also hitting this issue.  Can you elaborate more on "need to adjust your permissions to use the correct ones"?  My token has Zone Edit, Zone Settings Edit, Zone DNS Edit, Zone WAF Edit. Which one do I need to add?  Or is this an account level permission?

**Comment by pservit** [comment]
had the same issue
you need Account Billing Edit permission (need to be super-admin to add it)
