### ISSUE TITLE
Cannot add valid local IPv6 cidrs to split tunnel list

### ISSUE THREAD

**Issue by allwalte** [cloudflare/terraform-provider-cloudflare#3184]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.7.4
+ provider registry.terraform.io/cloudflare/cloudflare v4.26.0

### Affected resource(s)

cloudflare_split_tunnel

### Terraform configuration files

```hcl
resource "cloudflare_split_tunnel" "test_split_tunnel_exclude" {
  account_id = var.account_id
  policy_id  = cloudflare_device_settings_policy.test_warp_policy.id
  mode       = "exclude"
  tunnels {
    address     = "ff01::/16"
    description = "ipv6 interface local"
  }
}
```

### Link to debug output

https://gist.github.com/allwalte/b7922ae8aa2b1e66509e89faad4249b7

### Expected output

The entry to be successfully added, as happens with the API and/or with other of the default entries like "fe80::/10"

### Actual output

"Error: error updating "exclude" Split Tunnels: cannot update split tunnels: ff01::/16 is an invalid domain name (2049)"

Note: the plan passes, this only happens on the apply

### Steps to reproduce

Attempt to add ff01::/16 as an address in a split tunnel exclude list

### Additional factoids

The errors in the debug log re: the "random" resource are from a test tunnel resource a colleague created, unrelated to this change set, and other addresses work in this exact resource without making any change to that other one (i.e. that also have those "random" errors, so it seems to be unrelated to this issue).  Also, the log is from a run of the full version of the split tunnel terraform - it's got a dynamic address block so it's not an exact match for the log included above (I can't apply without an approval and there isn't anyone available at the moment to get one.  If you need to get one that more strictly matches it let me know and I can arrange that later).

**Comment by jacobbednarz** [comment]
the issue you've raised here is coming from the API itself, not Terraform.

```
PUT /client/v4/accounts/1e730f86a6b16f1ef4d341de47f6de56/devices/policy/exclude HTTP/1.1
Host: api.cloudflare.com
User-Agent: terraform-provider-cloudflare/4.26.0 terraform-plugin-sdk/2.32.0 terraform/1.7.5
Content-Length: 506
Authorization: [redacted]
Content-Type: application/json
Accept-Encoding: gzip
2024-03-14T01:20:47.892Z [DEBUG] provider.terraform-provider-cloudflare_v4.26.0
[{"host":"zoomapp.cloud"},{"host":"ff01::/16"},{"host":"fe80::/10"},{"host":"zoom.us"},{"host":"*.zoom.com"},{"host":"fd00::/8"},{"host":"ff02::/16"},{"host":"192.0.0.0/24"},{"host":"*.zoomapp.cloud"},{"host":"240.0.0.0/4"},{"host":"zoom.com"},{"host":"224.0.0.0/24"},{"host":"100.64.0.0/10"},{"host":"ff05::/16"},{"host":"192.168.0.0/16"},{"host":"172.16.0.0/12"},{"host":"ff03::/16"},{"host":"255.255.255.255/32"},{"host":"*.zoom.us"},{"host":"ff04::/16"},{"host":"10.0.0.0/8"},{"host":"169.254.0.0/16"}]


HTTP/2.0 400 Bad Request
Content-Length: 148
Cf-Cache-Status: DYNAMIC
Cf-Ray: 86407179c8203076-SEA
Content-Type: text/plain; charset=utf-8
Date: Thu, 14 Mar 2024 01:20:47 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=ZrotnGdEopa%2FIBC4Tgbxlmw3%2Fs1MhSIsBOISyAEn4jzR%2BjgFA6mNX9dCqJ2dV8h7j%2FM51A%2Fg8%2BNozEBIdCqHsKSFs3xv9oFXZpjqzfWvNnw3PEcAuSCDH%2FMMyjdu0nX03oAw1UKG1HP8UcQ%2FPp3QSY3StT41KNUrZVaUPzOC"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Set-Cookie: __cf_bm=aIkQF9qwtI_n7UGsped.H1RMS_wbbkZqtqcxX3I0hCQ-1710379247-1.0.1.1-fp0ipnWcVDBc39l_dmsQsQ0Izh.7KL72s01ihqAPEtSvAHSiICKDq._b8v0Gm5LM3fn9zxS3BFBtc6HFL4Sbpw; path=/; expires=Thu, 14-Mar-24 01:50:47 GMT; domain=.cloudflareclient.com; HttpOnly; Secure; SameSite=None
Set-Cookie: __cflb=0H28vgHxwvgAQtjUGUFqYFDiSDreGJnUnVzdTpwvvFX; SameSite=Lax; path=/; expires=Thu, 14-Mar-24 03:50:48 GMT; HttpOnly
Set-Cookie: __cfruid=97f15ee600643b2cbf97eebfe65ec2f8cfd4488e-1710379247; path=/; domain=.api.cloudflare.com; HttpOnly; Secure; SameSite=None
Vary: Accept-Encoding

{"result":null,"success":false,"errors":[{"code":2049,"message":"cannot update split tunnels: ff01::/16 is an invalid domain name"}],"messages":[]}
```

i would recommend you open a support ticket (or mention it to your account team) as this is a problem in the underlying service, not anything specific to the provider that we can address here.

**Comment by allwalte** [comment]
Interesting - doing just a put on the API endpoint works with this address, which is why I came here.  Will do; thanks!
