### ISSUE TITLE
Enhancement - cloudflare_teams_location - ecs_support option 

### ISSUE THREAD

**Issue by danielpmoss** [cloudflare/terraform-provider-cloudflare#3195]
### Current Terraform and Cloudflare provider version

Cloudflare provider - v4.26.0

### Description

Propose to add option to cloudflare_teams_location resource.

To include the ecs_support option (Enable the EDNS client subnet for the DNS location in Cloudflare)

Available on the Cloudflare API
https://developers.cloudflare.com/api/operations/zero-trust-gateway-locations-create-zero-trust-gateway-location
https://developers.cloudflare.com/api/operations/zero-trust-gateway-locations-create-zero-trust-gateway-location#:~:text=false-,ecs_support,True%20if%20the%20location%20needs%20to%20resolve%20EDNS%20queries.,-Example%3A

### Use cases

Enable the EDNS client subnet setting for a DNS location in Cloudflare Gateway

### Potential Terraform configuration

resource "cloudflare_teams_location" "name" {
  account_id     = "account id"
  name           = "name"
  client_default = true
  **_ecs_support = true / false_**
   
  networks {
    network = "network"
  }

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
