### ISSUE TITLE
Missing cloudflare_access_group data source

### ISSUE THREAD

**Issue by DamienDelporte** [cloudflare/terraform-provider-cloudflare#3203]
### Current Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.6.0
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.27.0

### Description

When creating CF access group and using on a separated tf state it would be better than to hard code the value to retrieve from a cloudflare_access_group data source.

Related Cloudflare support ticket: https://support.cloudflare.com/hc/en-us/requests/3194385

Currently this data source is missing from the provider.

### Use cases

Already described in description above.

### Potential Terraform configuration

```hcl
data "cloudflare_access_group" "device_posture_linux" {
  name = "device_posture_linux"
}

resource "cloudflare_access_application" "main" {
.. SNIP ...
}

resource "cloudflare_access_policy" "linux" {
  application_id = cloudflare_access_application.main.id
  account_id     = var.account_id
  name           = "linux"
  precedence     = "5"
  decision       = "allow"
  include {
    email = ["xxx.yyy@example.com"]
  }
  require {
    device_posture = [
      data.cloudflare_access_group.device_posture_linux.id
    ]
  }
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by landbaychrisburrell** [comment]
Do you know roughly when we might see this data source?
