### ISSUE TITLE
Missing cloudflare_teams_list data source

### ISSUE THREAD

**Issue by DamienDelporte** [cloudflare/terraform-provider-cloudflare#3204]
### Current Terraform and Cloudflare provider version

$ terraform -v
Terraform v1.6.0
on linux_amd64

provider registry.terraform.io/cloudflare/cloudflare v4.27.0

### Description

When creating CF teams lists and using on a separated tf state it would be better than to hard code the value to retrieve from a cloudflare_teams_list data source.

Cloudflare support ticket: https://support.cloudflare.com/hc/en-us/requests/3194412

Currently this data source is missing from the provider.

### Use cases

Already described in description above.

### Potential Terraform configuration

```hcl
data "cloudflare_teams_list" "some_rule" {
  account_id  = XXX
  name        = "some_rule"
}

resource "cloudflare_teams_rule" "some_rule" {
  account_id  = XXX
  name        = "YYY"
  description = "HTTP traffic not isolated in remote browser"
  enabled     = true
  precedence  = 300
  action      = "noisolate"
  filters     = ["http"]
  traffic = format(
    "any(http.request.domains[*] in $%s)",
    replace(data.cloudflare_teams_list.some_rule.id, "-", "")
  )
}
```

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
