### ISSUE TITLE
Unable to Import `page_rule` - `The provider returned a resource missing an identifier during ImportResourceState.`

### ISSUE THREAD

**Issue by GangGreenTemperTatum** [cloudflare/terraform-provider-cloudflare#3205]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```shell
Terraform v1.7.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.24.0
```

### Affected resource(s)

`page_rule`

### Terraform configuration files

```hcl
terraform {
  required_version = ">= 1.7.2"
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.24.0"
    }
  }
}

# This is the basic example for simplicity from the docs:
resource "cloudflare_page_rule" "foobar" {
  zone_id = var.cloudflare_zone_id
  target = "sub.${var.cloudflare_zone}/page"
  priority = 1

  actions {
    ssl = "flexible"
    email_obfuscation = "on"
    minify {
      html = "off"
      css  = "on"
      js   = "on"
    }
  }
}
```

### Link to debug output

NA

### Expected output

[Docs](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule) state:
> Page rules can be imported using a composite ID formed of zone ID and page rule ID, e.g.
`$ terraform import cloudflare_page_rule.default d41d8cd98f00b204e9800998ecf8427e/ch8374ftwdghsif43`

### Actual output

```shell
✗ terraform import cloudflare_page_rule.foobar <zone_id>/<rule_id>
cloudflare_page_rule.foobar: Importing from ID " <zone_id>/<rule_id>"...
╷
│ Error: The provider returned a resource missing an identifier during ImportResourceState. This is generally a bug in the resource implementation for import. Resource import code should not call d.SetId("") or create an empty ResourceData. If the resource is missing, instead return an error. Please report this to the provider developers.
```

### Steps to reproduce

Perform the import steps from the docs (**Expected output**)

### References

Thank you in advance, I could not identify any other similar reported issues
I am gathering `<rule_id>` by looking at the URL within the address bar of the UI within the CF dashboard, normally for DNS I would export the configuration and gather the ID's from there

**Comment by jacobbednarz** [comment]
the URL you are using there is incorrect; pages rules are not cache rules. 

you need to either query the API or the browser network tab to get the ID here. the error will be occurring because it is being provided an invalid identifier.
