### ISSUE TITLE
unexpected error in provider

### ISSUE THREAD

**Issue by jogarao96** [cloudflare/terraform-provider-cloudflare#3206]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

cloudflare/cloudflare versions matching "4.20.0"
terraform version : opentofu1.6.1

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "rate_limiting_wild" {
  zone_id     = 123456789
  name        = "Requests from ips that exceed requests per minute"
  description = "apply HTTP rate limiting for a route"
  kind        = "zone"
  phase       = "http_ratelimit"

  rules {
    action = "block"
    ratelimit {
      characteristics = [
        "cf.colo.id",
        "ip.src"
      ]
      period              = 60
      requests_per_period = 120
      mitigation_timeout  = 300
    }

    expression  = "all(http.request.headers[\"cf-cache-status\"][*] ne \"HIT\")"
    description = "Requests from ips that exceed 120 requests per minute"
    enabled     = true
  }
```

### Link to debug output

<script src="https://gist.github.com/jogarao96/0285901d9e0f0ef9d7dc0b8cb24fb1c7.js"></script>

### Expected output

applied new rule_set

### Actual output

 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_ruleset.rate_limiting_wild, provider
│ "provider[\"registry.opentofu.org/cloudflare/cloudflare\"]" produced an
│ unexpected new value: .rules[1].ratelimit[0].mitigation_timeout: was null,
│ but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

### Steps to reproduce

define resource as mentioned 
terraform plan 
terraform apply

**Comment by daodennis** [comment]
Have you tried to update to 4.26?
