### ISSUE TITLE
cloudflare_ruleset - split into multiple, smaller, resources

### ISSUE THREAD

**Issue by scott-doyland-burrows** [cloudflare/terraform-provider-cloudflare#3210]
### Current Terraform and Cloudflare provider version

terraform 1.7.5
provider 4.26.0

### Description

The ```cloudflare_ruleset``` resource is huge by terraform standards and is very complex/difficult to terraform, and the documentation is also very long.

I would like to see this resource split into multiple, smaller, resources.

I appreciate the API may currently prevent this?  However, if that is the case then I'd suggest the API itself needs to also allow the splitting up of API endpoints.

### Use cases

Using such a large resource is prone to coding issues and is hard to debug. It is also hard to decipher the documentation.

It is also difficult to ascertain which parameter values to use in the resource to terraform the required cloudflare configuration.

### Potential Terraform configuration

This is just one example of how we could have separate resources for the custom firewall rules.
This would allow each rule to be configured separately, and then those rules allocated to the ruleset in the correct order.

```
resource "custom_firewall_rule" "one" {
  name       = "example1"
  action     = "block"
  enabled    = true
  expression = ("my example expression")
}

resource "custom_firewall_rule" "two" {
  name       = "example2"
  action     = "block"
  enabled    = true
  expression = ("my example expression")
}

resource "custom_firewall_ruleset" "example" {
  rules = [
    custom_firewall_rule.one.id,
    custom_firewall_rule.two.id,
  ]
}
```

This simplifies the terraforming, as a lot of the config currently required is already "hardcoded" into the provider resource itself, eg there is no need to specify a ```phase``` of ```http_request_firewall_custom```.

There would need to be separate resources for each current ```phase```.

In general it is just much more terraform friendly.

**Comment by scott-doyland-burrows** [comment]
Should this be immediately closed.  How about leaving it open to be voted on by the community to help to see where this lies in the community's priority?

**Comment by jacobbednarz** [comment]
this is not the place where we track potential longer term initiatives. it is for actionable enhancements that have a clear path forward. this is something we know does not fit into that category due to past internal discussions.

fwiw, in the future, we won't be accepting feature requests via GitHub as it is not the backlog teams use for prioritising their work stream.

**Comment by petero-dk** [comment]
I added a workaround using multiple repositories here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/3027#issuecomment-2138260815

**Comment by nightpool** [comment]
@jhutchings1 Either this rule or https://github.com/cloudflare/terraform-provider-cloudflare/issues/2423 would probably be the best starting point to re-open and restart the discussion now that we're on V5

**Comment by nightpool** [comment]
https://github.com/cloudflare/terraform-provider-cloudflare/issues/3027 also has a lot of good discussion and engagement from the community, although it's not the use-case I'm personally most focused on (allowing zone rules to be handled by independent service modules).

**Comment by nightpool** [comment]
Yes, and specifically the ability to reuse rules across modules in the *same* zone (for example, we have about 10-15 service modules in Terraform for our main root zone alone, and lots more that aren't in Terraform). This setup worked fine with Page Rules and old Firewall rules, but doesn't work for the new rulesets engine.
