### ISSUE TITLE
Support DMAC enablement

### ISSUE THREAD

**Issue by DDuarte** [cloudflare/terraform-provider-cloudflare#3212]
### Current Terraform and Cloudflare provider version

```
Terraform v1.5.7
+ provider registry.terraform.io/cloudflare/cloudflare v4.22.0
```

### Description

Support enabling DMARC Management - https://developers.cloudflare.com/dmarc-management/enable/

```
curl 'https://dash.cloudflare.com/api/v4/zones/<zone_id>/email/security/dmarc-reports' \
  -X 'PATCH' \
  -H 'content-type: application/json' \
  --data-raw '{"enabled":true}'
```

### Use cases

Enable DMARC Management through Terraform instead of UI

### Potential Terraform configuration

```hcl
resource "cloudflare_dmarc_management" {
  enabled = true
}
```

### References

- https://developers.cloudflare.com/dmarc-management/
- https://developers.cloudflare.com/dmarc-management/enable/

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by petero-dk** [comment]
I just wanted to say that I would also really like this feature, we have already implemented via the local-exec provisioner. I cannot find any problems with PATCH'ing multiple times as it will just make sure it is enabled. 

However, the one caveat that I have found is that it only works with USER api tokens, not account tokens. Even when they have the same rights. (And I don't mean the master token, the normal generated api tokens)

I am using the local-exec provisioner because I don't want the cloudflare API key in my plan, and this way it can use the env variable `CLOUDFLARE_API_TOKEN`

```tf
resource "null_resource" "cloudflare_dmarc" {

  triggers = {
    zone_id      = data.cloudflare_zone.zone.id

  }

  provisioner "local-exec" {
    command = <<EOT
      CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      curl --fail -S -X PATCH "https://api.cloudflare.com/client/v4/zones/${self.triggers.zone_id}/email/security/dmarc-reports" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" -H "Content-Type: application/json" --data '{"enabled":true}'
    EOT
  }
  provisioner "local-exec" {
    on_failure = continue # Since --fail -S is not set this is redundant
    when    = destroy
    command = <<EOT
      CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
      curl -X PATCH "https://api.cloudflare.com/client/v4/zones/${self.triggers.zone_id}/email/security/dmarc-reports" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" -H "Content-Type: application/json" --data '{"enabled":false}'
    EOT
  }

  # Ensure this runs after the zone ID is fetched
  depends_on = [data.cloudflare_zone.zone]
}

```

**Comment by aaronadamsCA** [comment]
> However, the one caveat that I have found is that it only works with USER api tokens, not account tokens. Even when they have the same rights. (And I don't mean the master token, the normal generated api tokens)

@petero-dk, FYI it looks like DMARC report settings for zones can finally be managed using an account token. The permission is named "Email Security DMARC Reports Write".

The API endpoint remains undocumented.
