### ISSUE TITLE
Cache Rule API still don't work with cache = false

### ISSUE THREAD

**Issue by jwillker** [cloudflare/terraform-provider-cloudflare#3215]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.26.0

The 4.27.0 isn't available at the Registry https://registry.terraform.io/providers/cloudflare/cloudflare/latest

### Affected resource(s)

cloudflare_ruleset 

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "cache_settings_example" {
  zone_id     = "<REDACTED>"
  name        = "set cache settings"
  description = "set cache settings for the request"
  kind        = "zone"
  phase       = "http_request_cache_settings"

  rules {
    action = "set_cache_settings"
    action_parameters = {
        cache = false
    }
    expression  = "(http.host eq \"<REDACTED>\")"
    description = "set cache settings rule"
    enabled     = true
  }
}
```

### Link to debug output

https://gist.github.com/jwillker/ca633117b451a3f4029ffd3d00ddba72

### Expected output

Success applied

### Actual output

action parameters are required for the set_cache_settings action (20106)\\

### Steps to reproduce

Create the resource in a Enterprise account, and try apply.

### References

Seems like this is the exact error described here: https://github.com/cloudflare/terraform-provider-cloudflare/issues/2164

**Comment by EdsonLuisVieira** [comment]
+1

**Comment by jacobbednarz** [comment]
we have this in the acceptance test suite and it works as expected - https://github.com/cloudflare/terraform-provider-cloudflare/blob/144774a92ddd8cd7b3bb1eff41b717a29b1262bc/internal/framework/service/rulesets/resource_test.go#L4426-L4445

if you're still having issues, you'll need to provide a TF_LOG=DEBUG output (from the initial ticket request) to get this investigated further.
