### ISSUE TITLE
Unable to create new origin rule and Transform Rule using Terraform , after importing Origin rule and Transform rule using CF terraforming. 

### ISSUE THREAD

**Issue by AzureTushar** [cloudflare/terraform-provider-cloudflare#3221]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform version : v1.7.5
Cloudflare provider version : v4.26.0

### Affected resource(s)

origin rule creation using terraform fails 
and Transform rule creation using terraform fails 

### Terraform configuration files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.26"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~>4.0"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

provider "cloudflare" {
  api_token = var.api_token
}


# ##########################Test#############################
# resource "cloudflare_ruleset" "http_origin_example" {
#   zone_id     = var.zone_id
#   name        = "Change origin"
#   description = ""
#   kind        = "zone"
#   phase       = "http_request_origin"

#   rules {
#     action = "route"
#     action_parameters {
#       host_header = "example.net"
#       origin {
#         host = "example.net"
#         port = 8000
#       }
#     }
#     expression  = "(http.request.uri.path matches \"^/api/\")"
#     description = "Change origin of API requests"
#     enabled     = true
#   }
# }
```

### Link to debug output

2024-03-27T09:27:15.868Z [ERROR] provider.terraform-provider-cloudflare_v4.27.0: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/diag/diagnostics.go:62 @module=sdk.proto diagnostic_severity=ERROR tf_resource_type=cloudflare_ruleset tf_rpc=ApplyResourceChange tf_req_id=c8cdd27c-3cda-03a9-5131-e7d128d2022c diagnostic_detail="A similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first import the existing rules using cf-terraforming. You can find details about how to do this at https://developers.cloudflare.com/terraform/additional-configurations/ddos-managed-rulesets/#optional-delete-existing-rulesets-to-start-from-scratch" diagnostic_summary="failed to create ruleset \"http_request_origin\"" tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/cloudflare/cloudflare timestamp=2024-03-27T09:27:15.867Z    2024-03-27T09:27:15.894Z [DEBUG] Sta

### Expected output

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Finishing: terraform apply

### Actual output

provider registry.terraform.io/hashicorp/azurerm v3.97.1
/datadrive/vm02-agent01/_work/_tool/terraform/1.7.5/x64/terraform apply -auto-approve .tfplan
cloudflare_ruleset.http_origin_rule_ui_provider: Creating...
╷
│ Error: failed to create ruleset "http_request_origin"
│
│ with cloudflare_ruleset.http_origin_rule_ui_provider,
│ on main.tf line 48, in resource "cloudflare_ruleset" "http_origin_rule_ui_provider":
│ 48: resource "cloudflare_ruleset" "http_origin_rule_ui_provider" {
│
│ A similar configuration with rules already exists and overwriting will have
│ unintended consequences. If you are migrating from the Dashboard, you will
│ need to first import the existing rules using cf-terraforming. You can find
│ details about how to do this at
│ https://developers.cloudflare.com/terraform/additional-configurations/ddos-managed-rulesets/#optional-delete-existing-rulesets-to-start-from-scratch

### Steps to reproduce

1.Import existing rules using CF-terraforming 
2.create the origin rule using Terraform
3. it gives the error to import the existing rules

**Comment by jacobbednarz** [comment]
please don't keep opening new duplicate issues; the error message here is informing you what steps needs to be taken to use this. if you are still stuck, please reach out to support or your account team.
