### ISSUE TITLE
Plan Failed on Imported Resources

### ISSUE THREAD

**Issue by fauzan-n** [cloudflare/terraform-provider-cloudflare#3233]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

1.7.5 & 1.32

### Affected resource(s)

cloudflare_firewall_rule

### Terraform configuration files

```hcl
resource "cloudflare_firewall_rule" "terraform_managed_resource_e2787c260fe74b72932055df741fc8ac" {
  action      = "skip"
  description = "Bypass ecms"
  filter_id   = "4955f35f6c814736bdae6a7d4dfee802"
  paused      = false
  priority    = 1000
  zone_id     = "85e4a284d86efb3a53033d62a7fe2f54"
}
```

### Link to debug output

https://gist.github.com/fauzan-n/f6c2e3929c022265cbff7540ad32dbc9

### Expected output

No changes

### Actual output

│ Error: expected action to be one of ["block" "challenge" "allow" "js_challenge" "managed_challenge" "log" "bypass"], got skip

### Steps to reproduce

1. Generate resource `cf-terraforming generate --resource-type "cloudflare_firewall_rule"`
2. Import code `cf-terraforming import --resource-type "cloudflare_firewall_rule"`
3. Run terraform plan

**Comment by jacobbednarz** [comment]
the error message is correct; "skip" is not an available action per the API docs and the schema definition. as it isn't present in the schema, it definitely won't be importable. 

i'm also not sure why cf-terraforming is outputting "skip" here as the older WAF actions didn't have it. perhaps it something to do with the migration? regardless, you should check what the UI/API has and adjust this resource accordingly. if you find something odd or that you cannot explain, please open an issue in the cf-terraforming repository or drop in a support ticket to have the team look into it.

**Comment by fauzan-n** [comment]
cf-terraforming is basically just help us to generate list of terraform import command to import, which is actually have to be executed manually.
so this command `terraform import cloudflare_firewall_rule.terraform_managed_resource_e2787c260fe74b72932055df741fc8ac 85e4a284d86efb3a53033d62a7fe2f54/e2787c260fe74b72932055df741fc8ac`

would generate this state on the statefile

`    {
      "mode": "managed",
      "type": "cloudflare_firewall_rule",
      "name": "terraform_managed_resource_e2787c260fe74b72932055df741fc8ac",
      "provider": "provider[\"registry.terraform.io/cloudflare/cloudflare\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "action": "bypass",
            "description": "Bypass ecms",
            "filter_id": "4955f35f6c814736bdae6a7d4dfee802",
            "id": "e2787c260fe74b72932055df741fc8ac",
            "paused": false,
            "priority": 1000,
            "products": [],
            "zone_id": "85e4a284d86efb3a53033d62a7fe2f54"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }`
    

As you can see, **_terraform import_** command generate `skip` not `bypass`

**Comment by fauzan-n** [comment]
even when I run` terraform import` manually , it is still generate `skip` not `bypass` on the statefile

`    {
      "mode": "managed",
      "type": "cloudflare_firewall_rule",
      "name": "terraform_managed_resource_e2787c260fe74b72932055df741fc8ac",
      "provider": "provider[\"registry.terraform.io/cloudflare/cloudflare\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "action": "skip",
            "description": "Bypass ecms",
            "filter_id": "4955f35f6c814736bdae6a7d4dfee802",
            "id": "e2787c260fe74b72932055df741fc8ac",
            "paused": false,
            "priority": 1000,
            "products": [],
            "zone_id": "85e4a284d86efb3a53033d62a7fe2f54"
          },
          "sensitive_attributes": [],
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    }`

**Comment by jacobbednarz** [comment]
it won't work regardless of the tool you use; the validation is on the provider schema. however, "skip" isn't valid for this resource type.
