### ISSUE TITLE
cloudflare_web_analytics_site error 10000

### ISSUE THREAD

**Issue by jean-mercier-hivebrite** [cloudflare/terraform-provider-cloudflare#3234]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.29.0"
    }

terraform 1.7.2

### Affected resource(s)

cloudflare_web_analytics_site

### Terraform configuration files

```hcl
resource "cloudflare_web_analytics_site" "web_analytics" {
  account_id   = local.account_id
  zone_tag     = module.cloudflare.cloudflare_zones_id
  auto_install = true
}
```

### Link to debug output

sensitive

### Expected output

Ressource should be created and provider should be able to call it to get information

### Actual output

│ Error: error getting web analytics site "XXXXXXXXXX": Authentication error (10000)
│ 
│   with cloudflare_web_analytics_site.web_analytics,
│   on webanalytics.tf line 2, in resource "cloudflare_web_analytics_site" "web_analytics":
│    2: resource "cloudflare_web_analytics_site" "web_analytics" {
│ 
╵

### Steps to reproduce

terraform apply

the creation is done but the apply end with this error

also after all the plan fail with this error

### Additional factoids

My token have all the permission available through the cloudflare UI

**Comment by chrisvander** [comment]
I also have this problem. What is the required permission on the API Token?

**Comment by lukdz** [comment]
Required permission on the API Token for `resource "cloudflare_web_analytics_site"`:
- `Account / Account Settings / Read`
- `Account / Account Settings / Edit`
`Edit` is not sufficient without `Read`
