### ISSUE TITLE
Limitations of `cloudflare_access_application`: Inability to Support Multiple Domains Per Application

### ISSUE THREAD

**Issue by thefourcraft** [cloudflare/terraform-provider-cloudflare#3236]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

cloudflare v4.29.0

### Affected resource(s)

cloudflare_access_application

### Terraform configuration files

```hcl
resource "cloudflare_access_application" "example" {
    zone_id                      = var.zone_id
    name                         = "Example"
    domain                       = "https://example.com"
    type                         = "self_hosted"
    tags                         = ["Team App"]
    session_duration             = "24h"
    allowed_idps                 = ["${var.google_idp_id}"]
    app_launcher_logo_url        = "https://example.com/png.png"
    app_launcher_visible         = true
    auto_redirect_to_identity    = true
    http_only_cookie_attribute   = true
    # allow_authenticate_via_warp  = true
    custom_deny_message          = "You are not allowed to access this application"
}
```

### Link to debug output

N/A

### Panic output

N/A

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

N/A

### Additional factoids

cloudflare_access_application (Resource), specifically the domain part, 
doesn't seem to support multiple domains per application (as the web UI does). Is there a way around it?

### References

https://discord.com/channels/595317990191398933/1043025669036187678/1115610208660635648
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application#domain

**Comment by thefourcraft** [comment]
So it appears that it's [supported](https://github.com/cloudflare/terraform-provider-cloudflare/blob/587e70b4d1f9167fe3509cfeceeb9c7e290227fa/internal/sdkv2provider/schema_cloudflare_access_application.go#L47C1-L54C5), but not documented :(
```go
                "self_hosted_domains": {
                        Type:     schema.TypeSet,
                        Optional: true,
                        Elem: &schema.Schema{
                                Type: schema.TypeString,
                        },
                        Description: "List of domains that access will secure. Only present for self_hosted, vnc, and ssh applications. Always includes the value set as `domain`",
                },
```

**Comment by jacobbednarz** [comment]
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application#self_hosted_domains is what you are after.

**Comment by thefourcraft** [comment]
@jacobbednarz thanks for the help, I didn't see that 🤦🏻
