### ISSUE TITLE
cloudflare_ruleset rule action_parameters bic invalid JSON: unknown field "bic"

### ISSUE THREAD

**Issue by Ayden-Drabek** [cloudflare/terraform-provider-cloudflare#3241]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform -v
Terraform v1.7.5
on darwin_arm64

### Affected resource(s)

cloudflare_ruleset
  - rules
   - action_parameters
    - bic = false

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "qa_whitelist_ruleset" {
  zone_id     = cloudflare_zone.api_qa.id
  name        = "QA Whitelist"
  description = "QA whitelist"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

  rules {
    action      = "block"
    expression  = format("%s%s%s", "(not ip.src in $", cloudflare_list.qa_whitelist_list.name, ")")
    description = "Block all traffic not in qa whitelist list"
  }
  rules {
    action = "skip"
    action_parameters {
      bic = false
    }
    expression  = format("%s%s%s", "(ip.src in $", cloudflare_list.qa_whitelist_list.name, ")")
    description = "Skip browser integrity check for whitelisted ips"
  }
}
```

### Link to debug output

cloudflare_ruleset.qa_whitelist_ruleset: Modifying... [id=xxxxx] ╷ │ Error: error updating ruleset with ID "xxxxx" │  │   with cloudflare_ruleset.qa_whitelist_ruleset, │   on cloudflare.tf line 56, in resource "cloudflare_ruleset" "qa_whitelist_ruleset": │   56: resource "cloudflare_ruleset" "qa_whitelist_ruleset" { │  │ invalid JSON: unknown field "bic"

### Expected output

Creation of new rule with action as skip and bic turned off

### Actual output

cloudflare_ruleset.qa_whitelist_ruleset: Modifying... [id=xxxxx] ╷ │ Error: error updating ruleset with ID "xxxxx" │  │   with cloudflare_ruleset.qa_whitelist_ruleset, │   on cloudflare.tf line 56, in resource "cloudflare_ruleset" "qa_whitelist_ruleset": │   56: resource "cloudflare_ruleset" "qa_whitelist_ruleset" { │  │ invalid JSON: unknown field "bic"

### Steps to reproduce

Attempt to create new cloudflare_ruleset with action_parameters bic set to false. Plan will run fine and valid when applying will get invalid json unknown feild 

### Additional factoids

Upon creating the resource via the console and importing into terraform running plan gives this output.

`  ~ resource "cloudflare_ruleset" "qa_whitelist_ruleset" {
        id          = "xxxxxxxx"
        name        = "QA Whitelist"
        # (4 unchanged attributes hidden)

      ~ rules {
          ~ id           = "xxxxxxxx" -> (known after apply)
          ~ last_updated = "2024-04-11 20:48:30.459208 +0000 UTC" -> (known after apply)
          ~ ref          = "xxxxxxx" -> (known after apply)
          ~ version      = "2" -> (known after apply)
            # (4 unchanged attributes hidden)
        }
      ~ rules {
          ~ id           = "xxxxxxx" -> (known after apply)
          ~ last_updated = "2024-04-11 20:48:30.459208 +0000 UTC" -> (known after apply)
          ~ ref          = "xxxxxxxx" -> (known after apply)
          ~ version      = "1" -> (known after apply)
            # (4 unchanged attributes hidden)

          ~ action_parameters {
              + bic      = false
              - products = [
                  - "bic",
                ] -> null
              + version  = (known after apply)
            }

          - logging {
              - enabled = true -> null
            }
        }
    }`

### References

https://developers.cloudflare.com/rules/configuration-rules/terraform-example/.  - Cloudflare example 

https://github.com/cloudflare/terraform-provider-cloudflare/issues/3215 - similar issue

**Comment by jacobbednarz** [comment]
this is an unfortunately vague error message that the team are addressing however, it means you've used the wrong action parameter attribute for the action.
