### ISSUE TITLE
Unclear from repository/documentation that this provider does not follow semver

### ISSUE THREAD

**Issue by philipahlberg** [cloudflare/terraform-provider-cloudflare#3243]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

N/A

### Affected resource(s)

- data_source/record

### Terraform configuration files

```hcl
N/A
```

### Link to debug output

N/A

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

N/A

### Additional factoids

v4.29.0 of this provider introduced a breaking change, which is unexpected since it is a minor version bump.

Is there any chance you would consider following semver? Not following semver complicates dependency update management, since it might get confused for a backwards-compatible update or grouped together with other backwards-compatible updates (such as when using dependency management automation services such as Renovate or Dependabot), making it even likely to be confused.

**Comment by jacobbednarz** [comment]
we follow semantic versioning. the breaking change you are referring to was a field that has not been used in 5+ years, has never been configurable by an end user and has been the default value for all records for even longer. the read process for data sources should already be taking this into account. if it doesn't please file a bug with the reproduction steps to get it triaged.

**Comment by philipahlberg** [comment]
>  we follow semantic versioning. the breaking change you are referring to was a field that has not been used in 5+ years, has never been configurable by an end user and has been the default value for all records for even longer.

Either it is a breaking change or it isn't. If you don't believe it is a breaking change, then don't label it as such. If it is a breaking change, and you're following semver, then it should be a major version bump.

Semver is a tool to communicate the nature of changes in an update. You can choose to use it, or you can choose not to - either choice is valid. If you choose to use it, then you do it because you believe that your users can benefit from the information that it conveys, and that it is worth the extra effort it requires from you. 

A major version bump is not something that should be avoided at all costs; it is a way to help your users by pointing out that there are breaking changes in the update that might affect them. If the breaking changes are trivial, then that's great - it's an easy upgrade, and your users will be happy. 

Shipping a breaking change in a minor version bump is dishonest. Tools trust the information and rely on it. When you break that trust, you also break those tools, and the processes that depend on them.

I'm not asking you to stick to semver, nor that you stop using it. Simply be clear about choice, and stick to it. The worst you can do is to pretend.
