### ISSUE TITLE
cloudflare_ruleset resource does not support Cache Reserve Eligibility parameter for Cache Rules

### ISSUE THREAD

**Issue by jayktaylor** [cloudflare/terraform-provider-cloudflare#3244]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.8.0
Provider version 4.29

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "my_ruleset" {
  kind    = "zone"
  name    = "default"
  phase   = "http_request_cache_settings"
  {...}
  rules {
    action = "set_cache_settings"
    action_parameters {
      cache = true
      cache_reserve = false
    }
    description = "Default"
    enabled     = true
    expression  = "(http.host ne \"example.com\")"
  }
}
```

### Link to debug output

N/A

### Expected output

The resource should be ineligible for Cache Reserve.

### Actual output

The resource remained eligible for Cache Reserve, because the parameter is not supported by the Terraform provider. Setting the Cache Reserve Eligibility settings manually using the dashboard or API results in it being wiped out by Terraform on the next `terraform apply`.

### Steps to reproduce

N/A

### References

Support was added upstream in https://github.com/cloudflare/cloudflare-go/commit/3ef5edd03f3fc17c3b3e214e286b8957c60c81b1 but was never added to the Terraform provider.

**Comment by jacobbednarz** [comment]
as this is a feature request for addition (not a bug), can you please submit this as a regular feature request to Cloudflare Support or your account team through the usual means?

there is some work to automate this in the future but for now, we need to follow the existing product enhancement process.

**Comment by emilianoangieri** [comment]
is there any feature request opened on this to track, follow or vote?
