### ISSUE TITLE
The cloudflare_static_route resource validation checker is incorrectly flagging 169.254.245.1 and 169.254.244.1 addresses as Invalid

### ISSUE THREAD

**Issue by jeffsani** [cloudflare/terraform-provider-cloudflare#3266]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

I am using Terraform Cloud which defaults to Terraform version: 1.8.1.  

### Affected resource(s)

cloudflare_static_route

### Terraform configuration files

```hcl
resource "cloudflare_static_route" "AWS-VPN-1" {
  account_id  = "7a0c39354edd897a1a98f6c7e50c6873"
  description = "us-west-1 vpc via AWS-VPN-1"
  prefix      = "172.31.0.0/20"
  #nexthop     = "169.254.244.1"
  nexthop      = "${aws_vpn_connection.vpn-connection-transit.tunnel1_vgw_inside_address}"
  priority    = 100
  weight      = 10
  #colo_names = [
   # "den01"
  #]
  #colo_regions = [
  #  "APAC"
  #]
}

resource "cloudflare_static_route" "AWS-VPN-2" {
  account_id  = "7a0c39354edd897a1a98f6c7e50c6873"
  description = "us-west-1 vpc via AWS-VPN-2"
  prefix      = "172.31.0.0/20"
  #nexthop     = "169.254.245.1"
  nexthop     = "${aws_vpn_connection.vpn-connection-transit.tunnel2_vgw_inside_address}"
  priority    = 100
  weight      = 10
  #colo_names = [
   # "den01"
  #]172.20.17.2/31
  #colo_regions = [
  #  "APAC"
  #]

}
```

### Link to debug output

https://gist.github.com/jeffsani/f431b51f68ff8a8f4ac7640d8c2561d9

### Expected output

The static routes and next hops are valid so they should get creatd

### Actual output

Error: error creating static route for prefix 172.31.0.0/20: New config failed checkers: route with next hop (169.254.245.1) not allowed. This check can fail when adding routes or modifying a tunnel. If modifying a tunnel, first remove the route with the offending hop (1016)
with cloudflare_static_route.AWS-VPN-2
on cf_mwan_static_routes.tf line 17, in resource "cloudflare_static_route" "AWS-VPN-2":
resource "cloudflare_static_route" "AWS-VPN-2" {

### Steps to reproduce

create a static route with a next hop of 169.254.244.1 or 169.254.245.2

**Comment by jacobbednarz** [comment]
this is not a terraform specific issue; instead, you should open a support ticket or speak to your account team to get this escalated to the service team.
