### ISSUE TITLE
data source pull incorrect account id 

### ISSUE THREAD

**Issue by Nello-Angelo** [cloudflare/terraform-provider-cloudflare#3277]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

4.30.0

### Affected resource(s)

cloudflare_zone

### Terraform configuration files

```hcl
variable "cloudflare_zone" {
  type = map(object({
    jump_start = bool
    paused     = bool
    plan       = string
    type       = string
  }))
  default = {}
}

data "cloudflare_accounts" "example" {
  name = "some@gmail.com"
}

resource "cloudflare_zone" "example" {
  for_each   = { for key, value in var.cloudflare_zone : key => value }
  account_id = data.cloudflare_accounts.example.id
  zone       = each.key
  jump_start = each.value.jump_start
  paused     = each.value.paused
  plan       = each.value.plan
  type       = each.value.type
}
```

### Link to debug output

-

### Panic output

Error: error creating zone "cloud-infra.online": Permission denied (1068)
with module.cloudflare.cloudflare_zone.example["cloud-infra.online"],
on ../modules/cloudflare-module/main.tf line 11, in resource "cloudflare_zone" "example":
11: resource "cloudflare_zone" "example" {

```
  # module.cloudflare.cloudflare_zone.example["domain"] will be created
  + resource "cloudflare_zone" "example" {
      + account_id          = "d41d8cd98f00b204e9800998ecf8427e" incorrect account id but correct is 12193bcb8354ff1dfc7a771ac01ca3b3
      + id                  = (known after apply)
      + jump_start          = false
      + meta                = (known after apply)
      + name_servers        = (known after apply)
      + paused              = true
      + plan                = "free"
      + status              = (known after apply)
      + type                = "full"
      + vanity_name_servers = (known after apply)
      + verification_key    = (known after apply)
      + zone                = "domain
    }
```

### Expected output

correct pulling account id 

### Actual output

Error: error creating zone "cloud-infra.online": Permission denied (1068)
with module.cloudflare.cloudflare_zone.example["cloud-infra.online"],
on ../modules/cloudflare-module/main.tf line 11, in resource "cloudflare_zone" "example":
11: resource "cloudflare_zone" "example" {

### Steps to reproduce

standard steps

### Additional factoids

-

### References

-

**Comment by Nello-Angelo** [comment]
i also get 

```
output "account" {
  value = data.cloudflare_accounts.example.accounts[0].id
}


│ Error: Invalid index
│ 
│   on ../modules/cloudflare-module/outputs.tf line 2, in output "account":
│    2:   value = data.cloudflare_accounts.example.accounts[0].id
│     ├────────────────
│     │ data.cloudflare_accounts.example.accounts is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.

```

**Comment by jacobbednarz** [comment]
the identifier you are looking at is the resource identifier, not the account identifier. you can see more about the design at https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/contributing/provider-design.md#plural-data-sources however, in short, you need to access the index (here, `0`) for it to return the account data.
