### ISSUE TITLE
Terraform `plan` should detect invalid CNAME record values, like `https://some.domain`

### ISSUE THREAD

**Issue by o-l-a-v** [cloudflare/terraform-provider-cloudflare#3278]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

I use <https://github.com/pulumi/pulumi-cloudflare> which uses this Terraform provider behind the scenes.

I'd think Terraform `plan` would catch invalid CNAME record values, but it does not. `https://<fqdn>` went through `plan`, but fails at deploy as it's not a valid CNAME value (notice the `https://`).

### Affected resource(s)

See <https://github.com/pulumi/pulumi-cloudflare/issues/748>.

### Terraform configuration files

See <https://github.com/pulumi/pulumi-cloudflare/issues/748>.

But given example <https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/examples/resources/cloudflare_record/resource.tf>:

```hcl
resource "cloudflare_record" "example_cname" {
  zone_id = var.cloudflare_zone_id
  name    = "terraform"
  value   = "https://some.domain"
  type    = "CNAME"
  ttl     = 3600
}
```

### Link to debug output

See <https://github.com/pulumi/pulumi-cloudflare/issues/748>.

### Expected output

Invalid CNAME record value should not go through `plan`.

### Actual output

`https://<fqdn>` is a valid CNAME record value.

### Steps to reproduce

See <https://github.com/pulumi/pulumi-cloudflare/issues/748>.

**Comment by jacobbednarz** [comment]
thanks for the issue! unfortunately, we don't apply strict validation for record types as the `value` field is used for multiple types (for any operation) given it needs additional context and internal logic to determine what is an is not valid. instead, we leverage the API to perform the more stricter validation. that's all to say, we don't support this today and unlikely to add more client side logic to support it in the future. sorry!

**Comment by o-l-a-v** [comment]
What Cloudflare API endpoint is used to do "the more stricter validation" in this case?

**Comment by jacobbednarz** [comment]
we are intentionally not duplicating the server side logic (and have no intention of doing so). 

there is not dedicated validation endpoint; it is performed at creation time by the DNS endpoint.

**Comment by o-l-a-v** [comment]
Got it, output of `plan` can't be trusted.

**Comment by o-l-a-v** [comment]
The only built in way to know for sure the value you want to set is valid is to try to deploy it. Which means plan does not validate, and thus gives a invalid feedback saying it will be deployed/go through.

The setup here is a brach protected repo with checks that must go through before a reviewer can approve. The reviewer can't trust built in checks (plan), is what I'm saying.

Currently, to give the reviewer info about whether a CNAME value is valid we'd have to deploy it to a dummy domain as part of the checks. Could be doable.

What we do instead is to write a linter that checks for things terraform plan / pulumi preview won't catch. Valid CNAME value is now part of said linter.
