### ISSUE TITLE
Missing return after AddError

### ISSUE THREAD

**Issue by punkeel** [cloudflare/terraform-provider-cloudflare#3285]
### Affected resource(s)

- internal/framework/service/list_item/resource.go
- internal/framework/service/hyperdrive_config/resource.go

## Words

We found a bug in the Turnstile resource: `AddError` is called without a `return`. The State is then saved, and not properly validated by Terraform... leading to corrupted state.

I wrote a quick (and dirty) Semgrep rule to try to catch it:
```semgrep
rules:
  - id: go-resp-diagnostics-add-error-no-return
    languages:
      - go
    severity: ERROR
    message: Calls to resp.Diagnostics.AddError should be directly followed by a
      return statement
    patterns:
      - pattern: |-
          if ... {
            ...
            resp.Diagnostics.AddError(...)
            ...
          }
      - pattern-not: |-
          if ... {
            ...
            resp.Diagnostics.AddError(...)
            ...
            return
          }
```

It's not perfect, but it did find the following two files:

```
    internal/framework/service/hyperdrive_config/resource.go
   ❯❯❱ go-resp-diagnostics-add-error-no-return
          Calls to resp.Diagnostics.AddError should be directly followed by a return statement

          168┆ if err != nil {
          169┆   resp.Diagnostics.AddError("Error deleting hyperdrive config", err.Error())
          170┆ }
            ⋮┆----------------------------------------
          175┆ if len(idParts) != 2 {
          176┆   resp.Diagnostics.AddError("Error importing hyperdrive config", "Invalid ID specified.
               Please specify the ID as \"accounts_id/hyperdrive_config_id\"")
          177┆ }

    internal/framework/service/list_item/resource.go
   ❯❯❱ go-resp-diagnostics-add-error-no-return
          Calls to resp.Diagnostics.AddError should be directly followed by a return statement

           87┆ if err != nil {
           88┆   resp.Diagnostics.AddError(fmt.Sprintf("failed reading List Item with ID: %q", data.ID),
               err.Error())
           89┆ }
            ⋮┆----------------------------------------
          110┆ if err != nil {
          111┆   resp.Diagnostics.AddError(fmt.Sprintf("failed reading List Item with ID: %q", data.ID),
               err.Error())
          112┆ }
```

## Hyperdrive #1

https://github.com/cloudflare/terraform-provider-cloudflare/blob/ba46db62b1fa002362253152dc6073c7c6c237bb/internal/framework/service/hyperdrive_config/resource.go#L168-L170

This looks like a false positive to me.

## Hyperdrive #2 

https://github.com/cloudflare/terraform-provider-cloudflare/blob/ba46db62b1fa002362253152dc6073c7c6c237bb/internal/framework/service/hyperdrive_config/resource.go#L175-L177

Real finding?

## "List item??" #1

https://github.com/cloudflare/terraform-provider-cloudflare/blob/ba46db62b1fa002362253152dc6073c7c6c237bb/internal/framework/service/list_item/resource.go#L87-L90

Real finding?

## "List item??" #2

https://github.com/cloudflare/terraform-provider-cloudflare/blob/ba46db62b1fa002362253152dc6073c7c6c237bb/internal/framework/service/list_item/resource.go#L110-L112

Real finding?

I don't own these files (and I'm really no tf expert) - could someone take a look if these are worth fixing?

**Comment by jacobbednarz** [comment]
i touched on this in #3284 but i'm not sure if we want this to be universally applied. should these be somewhat recoverable, we should instead be setting the correct state values to be saved instead of halting execution. for me, it really comes down to how important these failures are and whether we can handle them more gracefully or if we need to totally just drop and bail completely.
