### ISSUE TITLE
Authentication error (10000)

### ISSUE THREAD

**Issue by der-ali** [cloudflare/terraform-provider-cloudflare#3292]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF version: 1.8.2

cloudflare provider version: 4.31.0

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "worker-nodes" {
  for_each = var.worker-nodes
  zone_id = var.cloudflare_zone_id
  name    = "${each.key}.${var.domain_tld}"
  value   = each.value
  type    = "A"
  ttl     = 3600
  proxied = false
}

provider "cloudflare" {
  api_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

### Link to debug output
TF_LOG=DEBUG logs:
https://gist.github.com/der-ali/8b4c01f59fff64c7548a58dec239f7ab

### Expected output

Authentication successfull and A records has been created

### Actual output

Error: Authentication error (10000)

### Steps to reproduce

* Create a Cloudflare API token with DNS:Edit for a specific zone
* whilelist ip address
* use the token in Terraform to create A records

### Additional factoids

Creating the A records using the API directly with `curl` and the same token does work!
Using the same token without IP whitelisting works in Terraform!

**Comment by jacobbednarz** [comment]
this error points to your API token being incorrect or an invalid format. the terraform provider is just another HTTP client and doesn't do anything special when it comes to calling the API. 

my recommendation is to use a MITM proxy to see what is differing between curl and the provider.

**Comment by der-ali** [comment]
I am not encountering the authentication issue using a http  MITM proxy!
On the other terminal where the HTTP_PROXY and HTTPS_PROXY are not set, i am still getting Authentication error.
A bit weird.

**Comment by jacobbednarz** [comment]
to me, that suggests a bad credential has made it's way into your shell.
