### ISSUE TITLE
Unable to associate Virtual Network with origin - schema_cloudflare_load_balancer_pool.go is missing virtual network association

### ISSUE THREAD

**Issue by aj-0x616a** [cloudflare/terraform-provider-cloudflare#3297]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.32.0

### Affected resource(s)

cloudflare_load_balancer_pool

### Terraform configuration files

```hcl
cloudflare_load_balancer_pool
```

### Link to debug output

n/a

### Expected output

Schema show have an option to associate a virtual network to the origin pool

### Actual output

Schema does not have any options to associate a virtual network to the origin pool

### Steps to reproduce

Schema does not have any options to associate a virtual network to the origin pool

https://github.com/cloudflare/terraform-provider-cloudflare/blob/f9a6054facf247c8f3f0519d0e42b67d99709e8d/internal/sdkv2provider/schema_cloudflare_load_balancer_pool.go#L120

### References

https://github.com/cloudflare/terraform-provider-cloudflare/blob/f9a6054facf247c8f3f0519d0e42b67d99709e8d/internal/sdkv2provider/schema_cloudflare_load_balancer_pool.go#L120

**Comment by Sceptyre** [comment]
Added comment to related issue:
https://github.com/cloudflare/terraform-provider-cloudflare/issues/3087
