### ISSUE TITLE
[cloudflare_access_policy] error creating Access Policy for ID "" when omitting application_id

### ISSUE THREAD

**Issue by cilindrox** [cloudflare/terraform-provider-cloudflare#3319]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.33.0
+ provider registry.terraform.io/hashicorp/aws v5.50.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.3.4
+ provider registry.terraform.io/hashicorp/kubernetes v2.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.1
+ provider registry.terraform.io/hashicorp/time v0.11.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5
```

### Affected resource(s)

`cloudflare_access_policy`

### Terraform configuration files

After upgrading to the latest module version, where it mentions using `cloudflare_access_application.policies` instead of linking policies by application id, I attempted a migration of an existing resource.

```hcl
resource "cloudflare_access_policy" "this" {
  # Removed both fields below, as described in the docs.
  # 
  # application_id = cloudflare_access_application.this.id
  # precedence     = try(each.value.precedence, "1")

  # ...
  zone_id          = data.cloudflare_zone.this.id

  include {
    # ...
  }
  
  require {
    # ...
  }

  lifecycle {
    create_before_destroy = true
  }
}

# then, updated the application with the reference to the policies, eg:

resource "cloudflare_access_application" "this" {
  # ...

  policies = cloudflare_access_policy.this[*].id
}
```

Creating the cloudflare_access_policy fails, since it seems the API does not allow for a `""` value on the application id field.

### Link to debug output

https://gist.github.com/cilindrox/84f369bc8a87638c724b95d98a65c156

### Expected output

Success

### Actual output

```
│ Error: error creating Access Policy for ID "": error from makeRequest: POST method not allowed for the api_token authentication scheme (10000)
│ 
│   with module.cloudflare_access.cloudflare_access_policy.this["my policy name"],
│   on ../../../modules/cloudflare-access/main.tf line 64, in resource "cloudflare_access_policy" "this":
│   64: resource "cloudflare_access_policy" "this" {
│ 
```

### Steps to reproduce

Create an cloudflare_access_policy with no `application_id` or `precedence`

The token I'm using has the folowing:

Account:

- `Access: Organizations, Identity Providers, and Groups` Edit
- `Access: Apps and Policies`  Edit

Zone:
- `Access: Apps and Policies`  Edit

### Additional factoids

Tried switching to a global access key, and got the same results, which makes me think this is an issue with the API or the client/provider setting the field to an unsupported value, rather than the permissions/scope.

### References

Change introduced in https://github.com/cloudflare/terraform-provider-cloudflare/pull/3288
and https://github.com/cloudflare/cloudflare-go/pull/1956

**Comment by cilindrox** [comment]
Thanks for the context @GreenStage - so if I'm understanding correctly, then I would need to change the reference and remove `zone_id`, keep `application_id` and `precedence` fields, and reference the policy from `cloudflare_access_application.this.policies`, correct?

```diff
resource "cloudflare_access_application" "this" {
  # ...

+  policies = [cloudflare_access_policy.this.id]
}

resource "cloudflare_access_policy" "this" {
+  application_id = cloudflare_access_application.this.id
+  precedence     = "1"

  # ...
-  zone_id          = data.cloudflare_zone.this.id
}
```

**Comment by novalagung** [comment]
@cilindrox I got the exact error today and was able to resolve it by doing @GreenStage suggestion, which is removing `zone_id` replace it with `account_id`.

```
resource "cloudflare_access_policy" "this" {
  # ...

-  zone_id    = data.cloudflare_zone.this.id
}

resource "cloudflare_access_policy" "this" {
  # ...

-  account_id = data.cloudflare_account.this.id
}
```

Also, ensure you have the necessary permission added to the API token
