### ISSUE TITLE
DNS Records: Unused/irrelevant data fields are sent to the API

### ISSUE THREAD

**Issue by janik-cloudflare** [cloudflare/terraform-provider-cloudflare#3348]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.8.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.34.0

### Affected resource(s)

* cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "example" {
  zone_id = var.zone_id
  name    = "example"
  type    = "SVCB"

  data {
    priority = 10
    target   = "example.com"
    value    = "alpn=h2"
  }
}
```

### Link to debug output

https://gist.github.com/janik-cloudflare/310eb92bb92fbd47db79fde4168a199d

### Expected output

Terraform sends only the data fields that are actually present in the resource

### Actual output

Terraform sends all data fields, including any that are not present in the resource and even data fields for completely unrelated record types, such as `lat_degrees` (which only makes sense for LOC records).

### Steps to reproduce

1. Add resource for URI record as in example above
1. Inspect request payload in output of `TF_LOG=TRACE terraform apply --auto-approve`

### Additional factoids

Sending unrelated fields or fields not present in the resource is unexpected and bad practice.

This has caused problems with a rollout related to SRV record data fields: https://community.cloudflare.com/t/eol-of-name-related-data-fields-on-srv-dns-records-is-not-applying/668360

**Comment by janik-cloudflare** [comment]
I didn't have time to review the entire log file for anything that shouldn't be published, but I believe the lines I included are sufficient :)

**Comment by sureshgurugubilli4** [comment]
Cloudflare API deprecates the service, proto and name fields within the data map in favor of the name field outside the data map, which is the same name field that’s used by all other record types. However, the terraform provider still maintains these fields in the data map.

https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records

**Comment by frankpengau** [comment]
Hi All, 

Is there any chance we can get this issue revisited, as it seems to have officially kicked in and been removed from the Cloudflare API from today onwards?

I believe that @janik-cloudflare has raised a draft PR for the potential schema changes. Any chance we can get this prioritised? 

Related to:
- https://github.com/cloudflare/terraform-provider-cloudflare/issues/1955
- https://github.com/cloudflare/terraform-provider-cloudflare/pull/3286

Ref:
- https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records

**Comment by janik-cloudflare** [comment]
Hi @frankpengau!

Could you help me understand the impact you're seeing as a result of this rollout? In theory it should be possible to simply omit the deprecated data fields without any issues!

**Comment by frankpengau** [comment]
Hi @janik-cloudflare ,

We've omitted the deprecated data fields from the SRV records and applied it to terraform state, but every time that we run our CI/CD, it is still picking up changes/drift to remove the data fields from the terraform state.

It looks like we might need to perform manual terraform state manipulation, in order to actually remove them, as it still expects them in the schema?

Otherwise, we were thinking we might need to look at moving to not using the data map entirely and just use value field/attribute to apply the port, priority, target and weight fields from the data map. 

Any suggestions?

**Comment by janik-cloudflare** [comment]
That's interesting, thanks @frankpengau. I have to admit I'm not too familiar with our Terraform provider but based on your message it sounds like the previous service/proto/name values are still cached in the tfstate file, and, because the API doesn't send them anymore, Terraform just assumes they still exist?

I'm using a `cloudflare_record` like [this one](https://community.cloudflare.com/t/eol-of-name-related-data-fields-on-srv-dns-records-is-not-applying/668360/11) and that works fine for me ("No changes. Your infrastructure matches the configuration."), even if I modify the tfstate file to add values to the old data fields (it just silently removes them again on the next `apply`).

Could you post an example of what your `cloudflare_record` looks like?

Perhaps setting the 3 deprecated fields in the data map would work to clear out any caches that are still around?

**Comment by janik-cloudflare** [comment]
Hmm, that works fine for me. On the second run:
> No changes. Your infrastructure matches the configuration.

Are you using the latest provider version?
```
% terraform --version | grep /cloudflare
+ provider registry.terraform.io/cloudflare/cloudflare v4.37.0
```

Could you share Terraform's output/diffs?

> Is there a way to find out which zones it has rolled out to
I can check if you have the zone ID, but at this point it's been rolled out to pretty much all zones. If you saw a change 2 days ago it must be because of that.

**Comment by arcnmx** [comment]
Is the deprecation a slow rollout? I was very confused why the suggested changes worked in some places but resulted in infinite applies in others. [ignore_changes](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) seems to be a valid workaround:

```terraform
lifecycle {
  ignore_changes = [data[0].name, data[0].proto, data[0].service]
}
```

**Comment by frankpengau** [comment]
@janik-cloudflare,

I won't be able to share publicly on GitHub, but happy to share more details in our Cloudflare Enterprise Support Case, if that's okay? 

Cloudflare Support Case: 3342269

**Comment by janik-cloudflare** [comment]
@arcnmx it is indeed, but it's essentially done now (finishing 08:00 UTC on Monday). Sorry for the trouble; we had missed the impact on Terraform while planning the change. In the future we'd probably choose a different rollout plan and/or roll out similar changes significantly faster. Thanks for sharing that workaround!

@frankpengau that'd be great, thank you! In particular the `TF_LOG=TRACE` output should be very helpful, I think. (P.S.: I don't think #3286 would solve the behavior you're seeing, unfortunately.)

**Comment by frankpengau** [comment]
@janik-cloudflare Seems like it has finally rolled out to the remaining zones that we had. Issue is good to resolve on our end. Thanks for your help!

**Comment by janik-cloudflare** [comment]
@frankpengau oh, interesting, based on the symptoms you saw I wouldn't have expected that to resolve it, but I'm glad it did. Apologies again for the bumpy rollout!
