### ISSUE TITLE
cloudflare_list_item fails to create if the IP Address shares a prefix with an IP that is already in the list

### ISSUE THREAD

**Issue by tpaulus** [cloudflare/terraform-provider-cloudflare#3359]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.8.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.35.0

### Affected resource(s)

cloudflare_list_item

### Terraform configuration files

```hcl
resource "cloudflare_list" "example_ip_list" {
  account_id = var.account_id
  name       = "example_ip_list"
  kind       = "ip"
}

resource "cloudflare_list_item" "example_ip_item_0" {
  account_id = var.account_id
  list_id    = cloudflare_list.example_ip_list.id
  ip         = "192.0.2.10"
}

resource "cloudflare_list_item" "example_ip_item_1" {
  account_id = var.account_id
  list_id    = cloudflare_list.example_ip_list.id
  ip         = "192.0.2.1"
}
```

### Link to debug output

https://gist.github.com/tpaulus/f3e02506f1813adf2c2f73b44ecf62c9

### Panic output

anic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100e879c4]

goroutine 25 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/list_item.createListItem({0x101ea8f28, 0x14000bda1e0}, 0x14000bbf360, 0x14000a6a9c0)
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/list_item/resource.go:311 +0x6f4
github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/list_item.(*ListItemResource).Create(0x14000a683c0, {0x101ea8f28, 0x14000bda1e0}, {{{{0x101eafe28, 0x14000bdb920}, {0x101964520, 0x14000bdb230}}, {0x101eb3458, 0x14000a9d680}}, {{{0x101eafe28, ...}, ...}, ...}, ...}, ...)
	github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/list_item/resource.go:66 +0x138
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140005ee000, {0x101ea8f28, 0x14000bda1e0}, 0x14000d1b4c0, 0x14000d1b460)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_createresource.go:101 +0x41c
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x14000baf620?, {0x101ea8f28, 0x14000bda1e0}, 0x14000bb1400, 0x14000d1b620)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140005ee000, {0x101ea8f28?, 0x14000bda0c0?}, 0x14000bb1360)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x314
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ApplyResourceChange(0x101ea8f60?, {0x101ea8f28?, 0x14000bc9da0?}, 0x14000bb1360)
	github.com/hashicorp/terraform-plugin-mux@v0.16.0/tf6muxserver/mux_server_ApplyResourceChange.go:36 +0x184
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x14000b246e0, {0x101ea8f28?, 0x14000bc93b0?}, 0x1400059c8c0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x2b0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x101dd6120?, 0x14000b246e0}, {0x101ea8f28, 0x14000bc93b0}, 0x14000a61a80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000117000, {0x101ea8f28, 0x14000c2f410}, {0x101eb0e40, 0x1400087a480}, 0x14000c42000, 0x1400089d980, 0x102bf3a38, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xba0
google.golang.org/grpc.(*Server).handleStream(0x14000117000, {0x101eb0e40, 0x1400087a480}, 0x14000c42000)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xc80
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 51
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x150

Error: The terraform-provider-cloudflare_v4.35.0 plugin crashed!

### Expected output

The resource to be created successfully.

### Actual output

Resource was created, but is not present in TF State, and apply fails with an error.

### Steps to reproduce

1. Create an IP List
2. Add an IP Address to that list, `192.0.2.10`
3. Wait a few moments...
4. Add another IP Address to that list that has the same string prefix as an IP already in the list, and watch it fail, `192.0.2.1`

### Additional factoids

The provider checks that the number of items returned is exactly one, not that the expected item is returned by name - https://github.com/cloudflare/terraform-provider-cloudflare/blob/5676a5a6c302efa74fadee33c3bbd55e46141265/internal/framework/service/list_item/resource.go#L295-L326

Appending a `/32` to the V4 addresses fixes the issue, since it is no longer a prefix of the other addresses.

**Comment by jacobbednarz** [comment]
thanks - i suspect there are two bugs here. the first whatever is causing the crash (if you get two matching, it should run out of retries, not crash) and the second is that you never get a match on overlapping prefixes. the latter was fixed for the redirects which was using a fuzzy contains via #3335 but we'll need to patch for IPs now too.
