### ISSUE TITLE
Escape capture group for redirects

### ISSUE THREAD

**Issue by mihait-wwk** [cloudflare/terraform-provider-cloudflare#3361]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 301
        target_url {
          expression = "concat(\"https://www.something.com/bla\",regex_replace(http.request.uri.path, \"^content_display/.+/(.+)/.+\", \"/${1}\"))"
        }
        preserve_query_string = false
      }
    }
    expression  = "(http.host eq \"www.something.com\" and http.request.uri.path matches \"/content_display/.+/(.+)/.+\")"
    description = "something blabla display redirect"
    enabled     = true
  }
```

### Link to debug output

none

### Expected output

redirects to path /1

### Actual output

```
│ 'concat("https://www.something.com/bla",regex_replace(http.request.uri.path,
│ "^/.+/(.+)/.+", "/\$\{1\}"))' is not a valid value for target_url because
│ the expression is invalid: Filter parsing error (1:104):
│ concat("https://www.something.com/bla",regex_replace(http.request.uri.path,
│ "^/.+/(.+)/.+", "/\$\{1\}"))
```

or

```
│ Error: Invalid escape sequence
│ 
│   on cloudflare_ruleset.tf line 1796, in resource "cloudflare_ruleset" "redirect_to_sso":
│ 1796:           expression = "concat(\"https://www.something.com/bla\",regex_replace(http.request.uri.path, \"^/.+/(.+)/.+\", \"/\\$\{1\}\"))"
│ 
│ The symbol "{" is not a valid escape sequence selector.
╵
```

or

```
│ Error: Invalid escape sequence
│ 
│   on cloudflare_ruleset.tf line 1796, in resource "cloudflare_ruleset" "redirect_to_sso":
│ 1796:           expression = "concat(\"https://www.something.com/bla\",regex_replace(http.request.uri.path, \"^/.+/(.+)/.+\", \"/\$\{1\}\"))"
│ 
│ The symbol "$" is not a valid escape sequence selector.
╵
```

```
│   with cloudflare_ruleset.redirect_to_sso,
│   on cloudflare_ruleset.tf line 502, in resource "cloudflare_ruleset" "redirect_to_sso":
│  502: resource "cloudflare_ruleset" "redirect_to_sso" {
│ 
│ 'concat("https://www.something.com/bla",regex_replace(http.request.uri.path,
│ "^/.+/(.+)/.+", '/1'))' is not a valid value for target_url because the
│ expression is invalid: Filter parsing error (1:101):
│ concat("https://www.something.com/bla",regex_replace(http.request.uri.path,
│ "^/.+/(.+)/.+", '/1'))
│                                                                                                     ^^^^^^ unrecognised input
│  (20083)
```

### Steps to reproduce

see code above

### Additional factoids

regex_replace(http.request.uri.path, \"^content_display/.+/(.+)/.+\", \"/${1}\") -> this doesn't work
regex_replace(http.request.uri.path, \"^content_display/.+/(.+)/.+\", \"/\$\{1\}\") -> this doesn't work
regex_replace(http.request.uri.path, \"^content_display/.+/(.+)/.+\", \"/\\$\\{1\\}\") -> this doesn't work

**Comment by mihait-wwk** [comment]
Managed to find a workaround by using 
          expression = "concat(\"https://www.something.com/bla\",regex_replace(http.request.uri.path, \"^/.+/(.+)/.+\", \"${local.first_capture_group}\"))"
with
locals {
    first_capture_group = "/$${1}"
}

**Comment by jacobbednarz** [comment]
thanks for the issue. this isn't a provider bug but a quirk of the escape sequences in HCL. you can check out the [documentation](https://developer.hashicorp.com/terraform/language/expressions/strings?source=post_page-----79aae78b1a60--------------------------------#escape-sequences-1) in order to get the correct expressions here.

**Comment by mihait-wwk** [comment]
noted, thanks again for the feedback!
