### ISSUE TITLE
cloudflare_email_routing_rule: Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by iwahbe** [cloudflare/terraform-provider-cloudflare#3396]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.8.3
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.35.0

Your version of Terraform is out of date! The latest version
is 1.8.5. You can update by downloading from https://www.terraform.io/downloads.html

(I don't believe that my issue was fixed; the issue itself says its a provider bug)

### Affected resource(s)

cloudflare_email_routing_rule

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.35.0"
    }
  }

  required_version = ">= 1.2.0"
}

provider "cloudflare" {}

resource "cloudflare_zone" "repro_zone" {
  account_id = "<ACCOUNT_ID>"
  zone       = "pulumi.com"
}

resource "cloudflare_email_routing_rule" "CfEmailRedirects" {
  zone_id = cloudflare_zone.repro_zone.id
  name    = "CfEmailRedirects"
  enabled = true

  matcher {
    type  = "literal"
    field = "to"
    value = "repro-1@pulumi.com"
  }

  matcher {
    type = "all"
  }

  action {
    type  = "forward"
    value = ["repro-3@pulumi.com"]
  }

  priority = 0
}
```

### Link to debug output

https://gist.github.com/iwahbe/6d2cf876d174c5827cc697b289ef7414

### Expected output

The email rules to be created.

### Actual output

```
terraform apply

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_email_routing_rule.CfEmailRedirects will be created
  + resource "cloudflare_email_routing_rule" "CfEmailRedirects" {
      + enabled  = true
      + id       = (known after apply)
      + name     = "CfEmailRedirects"
      + priority = 0
      + tag      = (known after apply)
      + zone_id  = (known after apply)

      + action {
          + type  = "forward"
          + value = [
              + "repro-3@pulumi.com",
            ]
        }

      + matcher {
          + field = "to"
          + type  = "literal"
          + value = "repro-1@pulumi.com"
        }
      + matcher {
          + type = "all"
        }
    }

  # cloudflare_zone.repro_zone will be created
  + resource "cloudflare_zone" "repro_zone" {
      + account_id          = "..."
      + id                  = (known after apply)
      + meta                = (known after apply)
      + name_servers        = (known after apply)
      + paused              = false
      + plan                = (known after apply)
      + status              = (known after apply)
      + type                = "full"
      + vanity_name_servers = (known after apply)
      + verification_key    = (known after apply)
      + zone                = "pulumi.com"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

yes
  Enter a value: 
cloudflare_zone.repro_zone: Creating...
cloudflare_zone.repro_zone: Creation complete after 1s [id=9d73e1680af07766fa34f6396847b02c]
cloudflare_email_routing_rule.CfEmailRedirects: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_email_routing_rule.CfEmailRedirects,
│ provider "provider[\"registry.terraform.io/cloudflare/cloudflare\"]"
│ produced an unexpected new value: .matcher: planned set element
│ cty.ObjectVal(map[string]cty.Value{"field":cty.NullVal(cty.String),
│ "type":cty.StringVal("all"), "value":cty.NullVal(cty.String)}) does not
│ correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Error: exit status 1
An error occurred: exit status 1
```

### Steps to reproduce

1. Run `terraform init && terraform apply` with the given code.
2. Type "yes".

### References

I actually found this issue when I was trying to reproduce https://github.com/pulumi/pulumi-cloudflare/issues/823 in terraform. For some reason, the bug does not reproduce in Pulumi.

**Comment by jacobbednarz** [comment]
thanks for the issue here. this like a misunderstanding of the resource usage and may explain why there is a problem here. the `cloudflare_email_routing_rule` is only for forwarding rules whereas `cloudflare_email_routing_catch_all` should be used for the `type = "all"` (catch all) rules. they are separate resources as they use different routes and aren't combined together in the API resources. hope that helps shed some light here!

**Comment by iwahbe** [comment]
That makes sense, and explains why the resource is misbehaving differently in Pulumi and Terraform. Thanks for pointing that out.

> │ This is a bug in the provider, which should be reported in the provider's
> │ own issue tracker.

It might make sense to add validation to the `matcher.type` attribute, since the current error message for this says it's a provider bug.

**Comment by jacobbednarz** [comment]
agree - it seems like it was assumed people would read the docs and see the difference 😂 will have a chat to the team about making this clearer.
