### ISSUE TITLE
SRV data fields 'service', 'proto' and 'name' are no longer supported

### ISSUE THREAD

**Issue by avx-rodmans** [cloudflare/terraform-provider-cloudflare#3502]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.7.0
on linux_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.38.0
+ provider registry.terraform.io/hashicorp/aws v5.59.0
```

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "cloudflare_record" {
  name            = "record_01"
  comment         = "<comment>"
  zone_id         = "<zone_id>"
  allow_overwrite = false

  data {
    service  = "_https"
    proto    = "_tcp"
    name     = "somename.domain.com"
    priority = 5
    weight   = 0
    port     = 8443
    target   = "somename.domain.com"
  }
}
```

### Link to debug output

cannot-include

### Panic output

na

### Expected output

Resource created

### Actual output

```
Error: failed to create DNS record: SRV data fields 'service', 'proto' and 'name' are no longer supported. Please see <https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records> for more information. (9000)
│ 
│   with cloudflare_record.cloudflare_record["record_01"],
│   on main.tf line 5, in resource "cloudflare_record" "cloudflare_record":
│    5: resource "cloudflare_record" "cloudflare_record" {
```

### Steps to reproduce

1. Use service, name, and proto in the data block

### Additional factoids

According to documentation [here](https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#name-related-data-fields-on-srv-dns-records), these are deprecated in the API however have not been updated in the provider.

**Comment by jacobbednarz** [comment]
this is already under way via #3286
