### ISSUE TITLE
cloudflare_ruleset redirect rules not supporting multi resources

### ISSUE THREAD

**Issue by Marcus-James-Adams** [cloudflare/terraform-provider-cloudflare#3518]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform 1.9.3
cloudflare v4.35.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
We run multiple projects and multiple layers where we wish to set redirect rules

eg 
resource "cloudflare_ruleset" "project1" {
  zone_id = data.cloudflare_zone.mine.zone_id
  name    = "project1.mydomaim.com"
  kind    = "zone"
  phase   = "http_request_dynamic_redirect"
  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 302
        target_url {
          value = "https://holding.mydomaim.com/"
        }
        preserve_query_string = true
      }
    }
    expression  = "(http.host eq \"www.project1.mydomain.com\")"
    description = "Redirect all users to www.project1.mydomain.com and forward to holding.mydomaim.com"
    enabled     = false
  }


then called from a different project

resource "cloudflare_ruleset" "project2" {
  zone_id = data.cloudflare_zone.mine.zone_id
  name    = "project2.mydomaim.com"
  kind    = "zone"
  phase   = "http_request_dynamic_redirect"
  rules {
    action = "redirect"
    action_parameters {
      from_value {
        status_code = 302
        target_url {
          value = "https://holding.mydomaim.com/"
        }
        preserve_query_string = true
      }
    }
    expression  = "(http.host eq \"www.project2.mydomain.com\")"
    description = "Redirect all users to www.project2.mydomain.com and forward to holding.mydomaim.com"
    enabled     = false
  }
```

### Link to debug output

.

### Expected output

two resources and rules page rules are created

### Actual output

The first resource creates ok

Error: failed to create ruleset "http_request_dynamic_redirect"
│
│   with cloudflare_ruleset.project2,
│   on legacy.holding.page.tf line 46, in resource "cloudflare_ruleset" "project2":
│   46: resource "cloudflare_ruleset" "project2" {
│
│ A similar configuration with rules already exists and overwriting will have unintended consequences. If you are migrating from the Dashboard, you will need to first import the existing rules using
│ cf-terraforming. You can find details about how to do this at
│ https://developers.cloudflare.com/terraform/additional-configurations/ddos-managed-rulesets/#optional-delete-existing-rulesets-to-start-from-scratch

### Steps to reproduce

apply code with two redirect page rule resources in the same layer

### Additional factoids

I am aware that you can have multiple rules in the same resource,  however, we run a module setup where each service would have its own ruleset resource as its applied at different times from different code repos

**Comment by jacobbednarz** [comment]
this is an intentional design of the Rulesets Engine and not something we drift from in the provider. you can read more about it at the [developer docs](https://developers.cloudflare.com/ruleset-engine/about/)

in this case, you would have one resource that lists multiple rules for the expressions and actions to get your desired outcome. 

we've spoke about separate rule resources in the past however, it's not something in the immediate or mid term roadmap since it's against the design of ERE and has many edge cases that don't have safe failure modes (not to mention extreme internal complexities).

**Comment by vazkarvishal** [comment]
Hey @jacobbednarz - So if we have a scenario where we have multiple environments (dev, staging, qa) and each environment has unique rules which need to be deployed (header transformations, etc). Without doing this in one bulk terraform deploy (which can break things everywhere), there is no way to deploy this in a step by step way? (dev > qa > staging). 

If a ruleset has to be unique per zone, then can we have ruleset_rules as a resource which can "patch" or "add-to" the existing rule set, then we can control this per environment? right now the all or nothing behaviour is a bit of a blocker for us.

Below is the code how we are doing the workaround:

1. Create the ruleset
```hcl
  provisioner "local-exec" {
    command = <<EOT
      response=$(curl -s https://api.cloudflare.com/client/v4/zones/$ZONE_ID/rulesets \
      --header "Authorization: Bearer $API_TOKEN" \
      --header "Content-Type: application/json" \
      --data '{
        "name": "Origin ruleset",
        "kind": "zone",
        "description": "This ruleset executes a managed ruleset.",
        "phase": "http_request_origin"
      }')
    EOT

    environment = {
      ZONE_ID   = local.zone_id
      API_TOKEN = local.cf_token
    }
  }
```

2. Patch the ruleset per environment
```hcl
provisioner "local-exec" {
    command = <<EOT
      # Check if INTERNAL_HOSTNAME and EXTERNAL_HOSTNAME are equal
      if [ "$INTERNAL_HOSTNAME" = "$EXTERNAL_HOSTNAME" ]; then
        echo "INTERNAL_HOSTNAME and EXTERNAL_HOSTNAME are equal. Skipping rule creation."
        exit 0
      fi

      # Get the ruleset entry point
      response=$(curl -s https://api.cloudflare.com/client/v4/zones/$ZONE_ID/rulesets/phases/http_request_origin/entrypoint \
        --header "Authorization: Bearer $API_TOKEN" \
        --header "Content-Type: application/json")

      # Extract the RULESET_ID from the response
      RULESET_ID=$(echo $response | jq -r '.result.id')

      # Extract the RULE_ID for the given SUBDOMAIN
      target_description=$SUBDOMAIN
      echo $response > data.json
      RULE_ID=$(cat data.json | jq -r --arg desc "$target_description" '.result.rules[] | select(.description == $desc) | .id')

      # Create the rule in the ruleset
      curl_output=$(curl --request POST https://api.cloudflare.com/client/v4/zones/$ZONE_ID/rulesets/$RULESET_ID/rules \
        --header "Authorization: Bearer $API_TOKEN" \
        --header "Content-Type: application/json" \
        --data "$(jq -n -c \
        --arg INTERNAL_HOSTNAME "$INTERNAL_HOSTNAME" \
        --arg EXTERNAL_HOSTNAME "$EXTERNAL_HOSTNAME" \
        --arg SUBDOMAIN "$SUBDOMAIN" \
        '{
            "action": "route",
            "action_parameters": {
                "host_header": $INTERNAL_HOSTNAME
            },
            "expression": "(http.host contains  \"\($EXTERNAL_HOSTNAME)\")",
            "description": $SUBDOMAIN,
            "enabled": true
        }')"
      )

      if [ $? -eq 0 ]; then
        echo "Rule created successfully: $curl_output"
      else
        echo "Failed to create rule."
        exit 1
      fi
    EOT

    environment = {
      ZONE_ID           = var.cloudflare_zone_id
      API_TOKEN         = var.cf_token
      INTERNAL_HOSTNAME = var.internal_hostname
      EXTERNAL_HOSTNAME = var.external_hostname
      SUBDOMAIN         = var.subdomain
    }
  }
```

Ideally we want to do this in a clean way so we can manage rules for each environment within a single zone using CI/CD pipelines per environment.
