### ISSUE TITLE
http.dst.ip is not recognized as a filter selector in Terraform

### ISSUE THREAD

**Issue by jeffreywongCallsign** [cloudflare/terraform-provider-cloudflare#3543]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

4.38

### Affected resource(s)

cloudflare_teams_rule

### Terraform configuration files

```hcl
resource "cloudflare_teams_rule" "gateway_rule" {
  for_each       = local.zero_trust_gateway_http_policies
  account_id     = var.cloudflare_account_id
  name           = each.value.name
  description    = each.value.description
  precedence     = 1
  action         = each.value.action
  filters        = each.value.filters
  traffic        = each.value.traffic
  device_posture = ""
  enabled        = true
  identity       = each.value.identity
}


locals {
  zero_trust_gateway_http_policies = [
      {
      name = "HTTP - Allow rule"
      enabled = true
      action = "off"
      filters  = ["http"]
      description = "Raising a ticket on GitHub"
      traffic = "http.dst.ip == \"192.168.0.1\""
    },
]
}
```

### Link to debug output

https://billing.support.cloudflare.com/support/s/case/500Nv00000C6kpGIAR/unknown-fields-terraform-new-nontsf-chat

### Expected output

Expected apply to complete

### Actual output

╷
│ Error: error creating Teams rule for account "3d9ac44b26dc14592f045450dd771bd4": Filter parsing error (1:1):
│ http.dst.ip == "192.168.0.0/28" 
│ ^^^^^^^^^^^ unknown field
│ 
│ 
│   with module.zero_trust_gateway_policies["HTTP - Allow rul"].cloudflare_teams_rule.gateway_rule,
│   on modules/zero_trust_gateway_policies/cloudflare_teams_rule.tf line 3, in resource "cloudflare_teams_rule" "gateway_rule":
│    3: resource "cloudflare_teams_rule" "gateway_rule" {
│ 
╵

### Steps to reproduce

1. terraform apply
2. yes

### References

These are the CloudFlare references that says it should work:
https://developers.cloudflare.com/cloudflare-one/policies/gateway/http-policies/#destination-ip
https://developers.cloudflare.com/api/operations/zero-trust-gateway-rules-create-zero-trust-gateway-rule
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/teams_rule#traffic

**Comment by jacobbednarz** [comment]
the value here is just passed through to the API so this is likely a service issue and nothing we can address in the provider (the error response here is from the API). you're best bet is to try it in the UI and inspect the payload it sends. from there, compare that with the documentation here and see what the differences here.
