### ISSUE TITLE
Unable to set "Allow WARP to WARP connection" from terraform

### ISSUE THREAD

**Issue by james-boydell** [cloudflare/terraform-provider-cloudflare#3723]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.40.0

### Affected resource(s)

cloudflare_zero_trust_gateway_settings (Or so I believe)

### Terraform configuration files

```hcl
resource "cloudflare_zero_trust_gateway_settings" "warp_gateway" {
  account_id = local.account_id

  proxy {
    root_ca    = false
    tcp        = true
    udp        = true
    virtual_ip = true
  }

  logging {
    redact_pii = false
    settings_by_rule_type {
      dns {
        log_all    = true
        log_blocks = false
      }
      http {
        log_all    = true
        log_blocks = false
      }
      l4 {
        log_all    = true
        log_blocks = false
      }
    }
  }
}
```

### Link to debug output

N/A

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

N/A

### Additional factoids

I'm trying to toggle the "Allow WARP to WARP connection" setting in Zero Trust -> Settings -> Network

I figured this would be the `virtual_ip` flag, but it doesn't seem to set it and I can't find anywhere in the documentation that sets this.

**Comment by josip-stanic** [comment]
pull request for this timed out: https://github.com/cloudflare/terraform-provider-cloudflare/pull/3328, I'll reopen it
