### ISSUE TITLE
Resource cloudflare_zone_settings_override not importable

### ISSUE THREAD

**Issue by pjmpsu** [cloudflare/terraform-provider-cloudflare#377]
### Terraform Version
Terraform v0.12.1
+ provider.cloudflare v1.15.0

### Affected Resource(s)
cloudflare_zone_settings_override

### Debug Output
```
terraform import -allow-missing-config cloudflare_zone_settings_override.example abc123
cloudflare_zone_settings_override.example: Importing from ID "abc123"...

Error: resource cloudflare_zone_settings_override doesn't support import
```

### Expected Behavior
It should import successfully.

**Comment by jacobbednarz** [comment]
I'm on the fence about this as the `cloudflare_zone_settings_override` isn't intended (as is) to manage all the zone settings available in a subscription; instead, it is meant to be for overriding the existing default configurations with your changes. This does, however, clash with the intent of managing all infrastructure as code via Terraform.

Something for the longer term, but perhaps the resource name and purpose needs to be changed to reflect being able to manage all settings and not just overridding defaults. I would entertain that discussion for 3.x milestone.

**Comment by kawikao** [comment]
This is a fatal error because when trying to delete the resource, it tries to update settings at Cloudflare marked as read-only which causes the delete to fail. So, I can't update a read-only setting with the existing value or null and I can't delete the resource. It's essentially a zombie resource that will never update or go away.

**Comment by billinghamj** [comment]
@jacobbednarz so what is the intended way to manage all the zone settings?

**Comment by jacobbednarz** [comment]
Closing this off as we won't be making `cloudflare_zone_settings_override` importable and any changes to manage all settings will likely be in a new resource.

**Comment by cofyc** [comment]
> Closing this off as we won't be making `cloudflare_zone_settings_override` importable and any changes to manage all settings will likely be in a new resource.

Out of curiosity, when will this new resource be available?

**Comment by gerbyzation** [comment]
@jacobbednarz 

> Something for the longer term, but perhaps the resource name and purpose needs to be changed to reflect being able to manage all settings and not just overriding defaults. I would entertain that discussion for 3.x milestone.

The provider is on version 4 now, but this doesn't seem to have changed. What are the prospects of having better support for these settings?

**Comment by nwalters512** [comment]
The first thing I did when I was setting up Cloudflare+Terraform just now was try to figure out how to disable email obfuscation. It seems like the only option for that is via the `cloudflare_zone_settings_override` resource, which to this day still isn't importable. Are there any improvements for this on the horizon?
