### ISSUE TITLE
Support Build Watch Path Config for pages

### ISSUE THREAD

**Issue by MiguelsPizza** [cloudflare/terraform-provider-cloudflare#3772]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

https://developers.cloudflare.com/pages/configuration/build-watch-paths#build-watch-paths

Build watch paths is not currently in the pages config schema while it exists in the UI. This is a really nice feature for monorepos so adding support would be great

### Affected resource(s)

<img width="854" alt="Screenshot 2024-08-23 at 10 10 48 PM" src="https://github.com/user-attachments/assets/f1b976c3-183e-43cb-8a05-54804f4f219a">

### Terraform configuration files

```hcl
'n/a'
```

### Link to debug output

https://github.com/cloudflare/terraform-provider-cloudflare/blob/fac029042358006df338fcd6cc749f99734d288d/internal/sdkv2provider/schema_cloudflare_pages_project.go#L12

### Panic output

'N/A'

### Expected output

'n/a'

### Actual output

'n/a'

### Steps to reproduce

'n/a'

### Additional factoids

```go
func resourceCloudflarePagesProjectSchema() map[string]*schema.Schema {
	buildConfig := schema.Resource{
		Schema: map[string]*schema.Schema{
			"build_caching": {
				Type:        schema.TypeBool,
				Description: "Enable build caching for the project.",
				Optional:    true,
			},
			"build_command": {
				Type:        schema.TypeString,
				Description: "Command used to build project.",
				Optional:    true,
			},
			"destination_dir": {
				Type:        schema.TypeString,
				Description: "Output directory of the build.",
				Optional:    true,
			},
			"root_dir": {
				Type:        schema.TypeString,
				Description: "Your project's root directory, where Cloudflare runs the build command. If your site is not in a subdirectory, leave this path value empty.",
				Optional:    true,
			},
			"web_analytics_tag": {
				Type:        schema.TypeString,
				Description: "The classifying tag for analytics.",
				Optional:    true,
			},
			"web_analytics_token": {
				Type:        schema.TypeString,
				Description: "The auth token for analytics.",
				Optional:    true,
			},
		},
		
		//should go here?
	}
```

**Comment by jacobbednarz** [comment]
closing as a feature request. please lodge these with your account team or support to use the existing feature request process.
