### ISSUE TITLE
cloudflare_zero_trust_access_xxx: migration from old resources to new resources

### ISSUE THREAD

**Issue by kgusarov** [cloudflare/terraform-provider-cloudflare#3899]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform - 1.8.5
Provider - 4.40.0

### Affected resource(s)

cloudflare_zero_trust_access_application
cloudflare_zero_trust_access_service_token
cloudflare_zero_trust_access_policy

### Terraform configuration files

```hcl
moved {
  from = cloudflare_access_service_token.token[0]
  to   = cloudflare_zero_trust_access_service_token.token[0]
}

moved {
  from = cloudflare_access_policy.policy[0]
  to   = cloudflare_zero_trust_access_policy.policy[0]
}

moved {
  from = cloudflare_access_application.access_application[0]
  to   = cloudflare_zero_trust_access_application.access_application[0]
}
```

### Link to debug output

N/A - not supported in corporate CI

### Expected output

Old resources migrated to new resource types

### Actual output

- The "cloudflare_zero_trust_access_policy" resource type does not support moving resource state across resource types.
- The "cloudflare_zero_trust_access_application" resource type does not support moving resource state across resource types.
- The "cloudflare_zero_trust_access_service_token" resource type does not support moving resource state across resource types.

### Steps to reproduce

1. Create deprecated access resources.
2. Migrate them to new types using `moved` keyword

### References

https://github.com/cloudflare/terraform-provider-cloudflare/pull/3584

**Comment by jacobbednarz** [comment]
moving resources between types is not supported in SDKv2 (framework only has support in 1.8+). while we may look at this for newer resources, it's not something that can be implemented today. i recommend following the Terraform guidance for moving/renames of resources in your configuration either by using a two phase approach or `state mv` directly.
