### ISSUE TITLE
Version v4.41.0 not published

### ISSUE THREAD

**Issue by nikolay** [cloudflare/terraform-provider-cloudflare#3910]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.9.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.40.0
```

### Terraform configuration files

```hcl
provider "cloudflare" {
  api_token = var.cloudflare_api_token
}

terraform {
  required_version = "1.9.5"
  cloud {
    organization = "[REDACTED]"
    workspaces {
      name = "[REDACTED]"
    }
  }
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.41.0"
    }
  }
}
```

### Expected output

```
$ terraform init -upgrade
Initializing HCP Terraform...
```

### Actual output

```
$ terraform init -upgrade
Initializing HCP Terraform...
Initializing provider plugins...
- Finding cloudflare/cloudflare versions matching "4.41.0"...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider cloudflare/cloudflare: no
│ available releases match the given constraints 4.41.0
╵
```

### Steps to reproduce

1. Bump provider version to `4.41.0` in `versions.tf`
2. Upgrade the provider in the `.terraform.lock.hcl` with `terraform init --upgrade`

### References

https://registry.terraform.io/providers/cloudflare/cloudflare/latest

**Comment by wookets** [comment]
I'm also experiencing this issue.

**Comment by jacobbednarz** [comment]
hashicorp are aware (and have been for some time now) and still investigating the cause.
