### ISSUE TITLE
`data {` attributes being deleted from MX records?

### ISSUE THREAD

**Issue by roy-work** [cloudflare/terraform-provider-cloudflare#3965]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.5.7
on darwin_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.38.0
```

(Note that it does reproduce on v4.41.0, but I am not readily able to upgrade to that as it deprecates `value`, and I need to change literally every `resource` to account for that.)

### Affected resource(s)

* `cloudflare_record`

### Terraform configuration files

```hcl
resource "cloudflare_record" "gem_mx" {
  for_each = local.gem_mx
  zone_id = data.cloudflare_zones.commure_com.zones[0].id
  name = "recruiting"
  type = "MX"
  value = each.value
  priority = 10
  # TODO: bump up, once the dust is settled.
  # ttl = 2 * 60 * 60  # 2 hr
  ttl = 5 * 60  # 5 min
}
```

### Link to debug output

https://example.com

### Expected output

No changes to plan.

### Actual output

We get a plan, where nothing has changed. See below.

### Steps to reproduce

We changed nothing. This record was already applied, and plans were generating "no changes" until recently. As we've also not upgraded the provider, this implies that CF's API responses have changed in a way that affects the TF provider.

This first showed up as:

```
  # cloudflare_record.gem_mx["a"] will be updated in-place
  ~ resource "cloudflare_record" "gem_mx" {
        id              = "[snip]"
        name            = "recruiting"
        tags            = []
        # (12 unchanged attributes hidden)

      - data {
          - algorithm      = 0 -> null
          - altitude       = 0 -> null
          - digest_type    = 0 -> null
          - key_tag        = 0 -> null
          - lat_degrees    = 0 -> null
          - lat_minutes    = 0 -> null
          - lat_seconds    = 0 -> null
          - long_degrees   = 0 -> null
          - long_minutes   = 0 -> null
          - long_seconds   = 0 -> null
          - matching_type  = 0 -> null
          - order          = 0 -> null
          - port           = 0 -> null
          - precision_horz = 0 -> null
          - precision_vert = 0 -> null
          - preference     = 0 -> null
          - priority       = 10 -> null
          - protocol       = 0 -> null
          - selector       = 0 -> null
          - size           = 0 -> null
          - target         = "mxa.mailgun.org" -> null
          - type           = 0 -> null
          - usage          = 0 -> null
          - weight         = 0 -> null
        }
    }
    
    # (also one for "b", similar)
```

Applying this is harmless (the record does not change), but the plan never converges.

I tried changing the resource to be,

```terraform
resource "cloudflare_record" "gem_mx" {
  for_each = local.gem_mx
  zone_id = data.cloudflare_zones.commure_com.zones[0].id
  name = "recruiting"
  type = "MX"
  data {
    target = each.value
    priority = 10
  }
  # TODO: bump up, once the dust is settled.
  # ttl = 2 * 60 * 60  # 2 hr
  ttl = 5 * 60  # 5 min
}
```

Figuring that, since I think that's closer to the format the API uses, maybe that'd make the provider happier. That _still_ results in a plan:

```
  # cloudflare_record.gem_mx["a"] will be updated in-place
  ~ resource "cloudflare_record" "gem_mx" {
        id              = "[snip]"
        name            = "recruiting"
      - priority        = 10 -> null
        tags            = []
        # (11 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
Again, a no-op but non-converging plan.

This:

```terraform
resource "cloudflare_record" "gem_mx" {
  for_each = local.gem_mx
  zone_id = data.cloudflare_zones.commure_com.zones[0].id
  name = "recruiting"
  type = "MX"
  data {
    target = each.value
    priority = 10
  }
  priority = 10  # See cloudflare/bugs.md
  # TODO: bump up, once the dust is settled.
  # ttl = 2 * 60 * 60  # 2 hr
  ttl = 5 * 60  # 5 min
}
```
Works (the plan immediately converges), but is ugly; I shouldn't need to specify `priority` twice like that.

### References

This smells similar to #3348

**Comment by jstewart612** [comment]
There is no version to which I could backport to address the concern and the comment https://github.com/cloudflare/terraform-provider-cloudflare/issues/3965#issue-2520442349 is correct about having to still have priority outside and then inside the data block (outside as a string and inside as a number).  So, to my mind, the actionable item here is why make us double tap on a field when it is known it must move under the data block?

Considering that version backporting failed, I am left to assume Cloudflare implemented breaking API change here.

**Comment by jacobbednarz** [comment]
this was an unintentional change on the service that lead to https://www.cloudflarestatus.com/incidents/79h1kvybmthk. this wasn't a change in the provider so you should be fine to re-run these and have the state rectified to the correct values again.

**Comment by ddesboroughv** [comment]
I just performed another plan and am still seeing the removal of the data block: 
```
      - data {
          - algorithm      = 0 -> null
          - altitude       = 0 -> null
          - digest_type    = 0 -> null
          - key_tag        = 0 -> null
          - lat_degrees    = 0 -> null
          - lat_minutes    = 0 -> null
          - lat_seconds    = 0 -> null
          - long_degrees   = 0 -> null
          - long_minutes   = 0 -> null
          - long_seconds   = 0 -> null
          - matching_type  = 0 -> null
            name           = null
          - order          = 0 -> null
          - port           = 0 -> null
          - precision_horz = 0 -> null
          - precision_vert = 0 -> null
          - preference     = 0 -> null
          - priority       = 5 -> null
          - protocol       = 0 -> null
          - selector       = 0 -> null
          - size           = 0 -> null
          - target         = "<redacted>" -> null
          - type           = 0 -> null
          - usage          = 0 -> null
          - weight         = 0 -> null
            # (14 unchanged attributes hidden)
        }
``` 
@jacobbednarz Are you saying we should apply this to reconcile things again?

**Comment by jacobbednarz** [comment]
yes - a plan does not update the state so that is expected not to do anything. you need to run the apply for the state to be reconciled.

**Comment by ddesboroughv** [comment]
To close the loop, as of this morning a plan no longer shows the removal of the data block. I didn't have to do anything.
