### ISSUE TITLE
Inconsistent/weird behavior of cloudflare_zero_trust_tunnel_cloudflared_config, Authentication Error (10000)

### ISSUE THREAD

**Issue by OctavioCore** [cloudflare/terraform-provider-cloudflare#4002]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v 1.9.4, Terraform v 1.9.5
Cloudflare Provider v 4.41.0

### Affected resource(s)

- cloudflare_zero_trust_tunnel_cloudflared_config
- cloudflare_zero_trust_tunnel_cloudflared

### Terraform configuration files

```hcl
data "cloudflare_zone" "this" {
  name = local.cloudflare_config["root_zone_name"]
}

resource "cloudflare_zero_trust_tunnel_cloudflared" "this" {
  account_id = data.cloudflare_zone.this.account_id
  name       = local.cloudflare_config.zero_trust_config.private_access_url_prefix
  secret     = base64encode(random_password.cf_tunnel_token.result)
  config_src = "cloudflare"
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "base_config" {
  account_id = data.cloudflare_zone.this.zone_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id

  config {
    warp_routing {
      enabled = false
    }

    ingress_rule {
      hostname = "${local.cloudflare_config.zero_trust_config.private_access_url_prefix}.${local.cloudflare_config["root_zone_name"]}"
      service  = "ssh://127.0.0.1"
    }

    origin_request {
      bastion_mode             = false
      disable_chunked_encoding = false
      http2_origin             = false
      keep_alive_connections   = 0
      no_happy_eyeballs        = false
      no_tls_verify            = false
      proxy_port               = 0
    }

    ingress_rule {
      service = "http_status:404"
    }
  }
}
```

### Link to debug output

https://gist.github.com/OctavioCore/821538eb1ccf4914c8ab63cdcfb33765

### Panic output

│ Error: error creating / updating tunnel config "<id of the tunnel>": Authentication error (10000)
│ 
│   with cloudflare_zero_trust_tunnel_cloudflared_config.base_config,
│   on cloudflare.tf line 69, in resource "cloudflare_zero_trust_tunnel_cloudflared_config" "base_config":
│   69: resource "cloudflare_zero_trust_tunnel_cloudflared_config" "base_config" {
│ 
 ╵

### Expected output

Config adjusted successfully for the provisioned tunnel.

### Actual output

The tunnel is provisioned succesfully, but the tunnel configuration resource apply fails with "Authentication error (10000)" regardless if it's being provisioned from scratch, or updated.

### Steps to reproduce

1. Use api token as your provider auth method
2. Use attached code
3. Run apply

### Additional factoids

I've thought that this might be due to errors in Terraform code on my part, so I've imported the config "clicked out" in the UI, then ran a `plan` to figure out discrepancies. Import went fine, the following `plan` has succeeded and shown some discrepancies I've reconciled into the code. 

After making those code changes, I ran `apply` action - but it failed at plan stage, with the Authentication Error (10000). I have destroyed the entire stack, ran `apply` again, and it fails with the Authentication Error (10000) as before.

I've checked the token used for authentication; It has all the necessary permissions to edit tunnels. I can also modify the config in the UI, so it's most probably not associated with permissions at all.

### References

Perhaps it is linked to https://github.com/cloudflare/terraform-provider-cloudflare/issues/3950 in some way/combines with this issue from the import part onwards?

**Comment by OctavioCore** [comment]
Attached whatever I could find about the resources in question. I won't be able to provide the full debug log - the Cloudflare config is just a small part of a bigger module with multiple providers.

**Comment by OctavioCore** [comment]
Nevermind, i've located the source of the issue, it was me all along ;)
There's a typo in the code, I've accidentally put `zone_id` in place of `account_id` - after fixing this goof, the config apply goes through. Closing this one, sorry for the mess!

**Comment by nijave** [comment]
> Nevermind, i've located the source of the issue, it was me all along ;) There's a typo in the code, I've accidentally put `zone_id` in place of `account_id` - after fixing this goof, the config apply goes through. Closing this one, sorry for the mess!

thanks for this! spent an awkward amount of time accidentally having `account_id` where `zone_id` was supposed to be 🤦
