### ISSUE TITLE
cloudflare_hostname_tls_setting available settings missing in documentation

### ISSUE THREAD

**Issue by alessiocreo** [cloudflare/terraform-provider-cloudflare#4112]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

v4.41.0

### Affected resource(s)

cloudflare_hostname_tls_setting

### Terraform configuration files

```hcl
resource "cloudflare_hostname_tls_setting" "example" {
  zone_id  = "0da42c8d2132a9ddaf714f9e7c920711"
  hostname = "sub.example.com"
  setting  = "zero_rtt"
  value    = "off"
}
```

### Link to debug output

n/A

### Expected output

We expecte to have all the available settings that we can configure

### Actual output

N/A

### Steps to reproduce

N/A

**Comment by jacobbednarz** [comment]
this isn't a bug but a request for enhancement of an existing resource. 

given v5 will be automatically using our schemas (and get these enums by default), we're unlikely to solve this in the near future so i'd recommend relying on the API schema documentation to see all possible combinations or values - https://developers.cloudflare.com/api/operations/per-hostname-tls-settings-list
