### ISSUE TITLE
cloudflare_turnstile_widget missing clearance_level

### ISSUE THREAD

**Issue by kamranayub** [cloudflare/terraform-provider-cloudflare#4126]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
OpenTofu v1.8.2
cloudflare/cloudflare v4.42.0
```

### Affected resource(s)

cloudflare_turnstile_widget

### Terraform configuration files

```hcl
resource "cloudflare_turnstile_widget" "example" {
    account_id      = var.cloudflare_account_id
    name            = "Example Widget"
    domains         = ["mydomain.com"]
    mode            = "managed"
    clearance_level = "managed"
}
```

### Link to debug output

https://gist.github.com/kamranayub/e5455d8dfcdfd397a3d31378a4b505ca

### Expected output

`clearance_level` should be set

### Actual output

```
╷
│ Error: Unsupported argument
│ 
│   on cloudflare.tf line 56, in resource "cloudflare_turnstile_widget" "ktomg_signup":
│   56:     clearance_level = "managed"
│ 
│ An argument named "clearance_level" is not expected here.
```

### Steps to reproduce

Try to add a turnstile widget with `clearance_level` set

### Additional factoids

This is available in 5.0 alpha, but not 4.x. Considering we are not supposed to upgrade for production workloads, there's no workaround for 4.x users.

### References

- 5.0-alpha docs: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/turnstile_widget#clearance_level

**Comment by jacobbednarz** [comment]
as this is a feature request, i'm going to close it off here and pass it internally to the team to triage as part of their backlog. if they deem they will do it before v5 stabilises, they will raise a PR with the support.
