### ISSUE TITLE
provider docs: resource cloudflare_api_token uses removed data.cloudflare_api_token_permission_groups in example

### ISSUE THREAD

**Issue by tom-futo** [cloudflare/terraform-provider-cloudflare#4171]
# data source cloudflare_api_token_permission_groups removed, referenced elsewhere in provider docs

### Affected resource(s)
[api_token](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/api_token)
maybe others

**Comment by tom-futo** [comment]
Might be worth adding a simpler issue template for minor doc things like this

**Comment by jacobbednarz** [comment]
you're viewing the v5 docs which are in alpha and not complete - this is still present in 4.x. 5.x documentation changes will be made at a later date.
