### ISSUE TITLE
Gritfile for provider version upgrade from 4.x to 5.x does not exist

### ISSUE THREAD

**Issue by fkonradmain** [cloudflare/terraform-provider-cloudflare#4214]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

5.0.0-alpha1

### Affected resource(s)

- cloudflare_record
- cloudflare_dns_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "mailcow_mx" {
    zone_id  = var.CLOUDFLARE_ZONE_ID
    name     = "@"
    content    = "${var.mail_subdomain}.${var.MAILCOW_DOMAIN}"
    type     = "MX"
    priority = 10
}
```

### Link to debug output

https://pastebin.com/982y2Ahy

### Expected output

`$ grit apply terraform_cloudflare_v5`

Processed 110 files and found 22 matches

`$ grit list --language hcl`
STANDARD LIBRARY PATTERNS

HCL patterns
  ✔ terraform_cloudflare_v5 (source: cloudflare/terraform-provider-cloudflare)
  ✔ cloudflare_record_deprecate_value_for_content (source: cloudflare/terraform-provider-cloudflare)
  ✔ cloudflare_zone_settings_override_deprecate_minify (source: cloudflare/terraform-provider-cloudflare)
  ✔ edit_module (source: getgrit/stdlib)
  ✔ kv_pair (source: getgrit/stdlib)

### Actual output

`$ grit apply terraform_cloudflare_v5`
```
ERROR (code: 200) - pattern definition not found: terraform_cloudflare_v5. Try running grit init.
```
`$ grit list --language hcl`
STANDARD LIBRARY PATTERNS

HCL patterns
  ✔ cloudflare_record_deprecate_value_for_content (source: cloudflare/terraform-provider-cloudflare)
  ✔ cloudflare_zone_settings_override_deprecate_minify (source: cloudflare/terraform-provider-cloudflare)
  ✔ edit_module (source: getgrit/stdlib)
  ✔ kv_pair (source: getgrit/stdlib)

### Steps to reproduce

In any directory run:
```bash
$ grit init
$ grit apply terraform_cloudflare_v5
```
Grit does not find this pattern even though it is documented here: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-5-upgrade#cloudflare_record. Even if this repo is imported (see yaml below), the pattern still won't exist.

### Additional factoids

for comparison, how the output looks like when using `cloudflare_record_deprecate_value`

`$ grit apply cloudflare_record_deprecate_value_for_content --dry-run`
```
...
     resource "cloudflare_record" "mailcow_mx" {
       zone_id  = var.CLOUDFLARE_ZONE_ID
       name     = "@"
    -  value    = "${var.mail_subdomain}.${var.MAILCOW_DOMAIN}"
    +  content = "${var.mail_subdomain}.${var.MAILCOW_DOMAIN}"
       type     = "MX"
       priority = 10
     }
...
```

content of `.grit/grit.yml`:

```yaml
version: 0.0.1
patterns:
  - name: github.com/getgrit/stdlib#*
  - name: github.com/cloudflare/terraform-provider-cloudflare#*
```

**Comment by jacobbednarz** [comment]
you need to reference the branch in the `apply` operation as it is not on master yet. 

the local apply definitely works (it's what rewrites the tests and you can confirm it works with `grit pattern test`). if you're having issues with it locally, you're probably hitting a bug in grit. i know in the past i had to perform a global init instead to resolve.
