### ISSUE TITLE
Datasource `cloudflare_dns_record` not supported even though documentation tells it should be

### ISSUE THREAD

**Issue by danidemi** [cloudflare/terraform-provider-cloudflare#4215]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
> terraform -v
Terraform v1.9.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.43.0
```

### Affected resource(s)

data "cloudflare_dns_record"

### Terraform configuration files

```hcl
terraform {
  required_version = ">= 0.12.6"
  required_providers {

    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 4"
    }

  }
}

provider "cloudflare" {
  api_token = "..."
}

output coderit-it-zone {
  value = data.cloudflare_zone.coderit-it
}
data "cloudflare_dns_record" "veikla-coderit-it" {
  zone_id  = data.cloudflare_zone.coderit-it.zone_id
  hostname = "veikla.coderit.it"
}
output veikla-coderit-it-record {
  value = data.cloudflare_dns_record.veikla-coderit-it
}

data "cloudflare_zone" "coderit-it" {
  name = "coderit.it"
}
```

### Link to debug output

https://gist.github.com/danidemi/74832c4794e8bed39a309af6a4e6843b

### Expected output

Data source `cloudflare_dns_record` should not raise any error and it should be supported, as documented here: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/dns_record

### Actual output

```powershell
> terraform plan
╷
│ Error: Invalid data source
│
│   on provider.tf line 21, in data "cloudflare_dns_record" "veikla-coderit-it":
│   21: data "cloudflare_dns_record" "veikla-coderit-it" {
│
│ The provider cloudflare/cloudflare does not support data source "cloudflare_dns_record".
╵
```

### Steps to reproduce

1. generate a cloudflare token 
2. just run `terraform init` and then `terraform plan` using the terraform attached to this bug using the token you've just created

### Additional factoids

I have a free account on cloudflare

**Comment by jacobbednarz** [comment]
you're referencing the 5.x documentation that is currently in alpha. 

you want to toggle the version to 4.x for the correct data source.

**Comment by danidemi** [comment]
thx @jacobbednarz, I didn't notice Terraform propose the user the latest version even when it is still in alpha. My bad, thx for your time.
