### ISSUE TITLE
`cloudflare_record` resource shows changes for SRV `data` block when no changes are made

### ISSUE THREAD

**Issue by waltervargas** [cloudflare/terraform-provider-cloudflare#4216]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
❯ terraform -v 
Terraform v1.9.5
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.43.0

Your version of Terraform is out of date! The latest version
is 1.9.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "terraform_managed_resource_2e8d68069b612c72a0b4ada8fab87d77" {
  name     = "_submissions._tcp"
  priority = 0
  proxied  = false
  ttl      = 3600
  type     = "SRV"
  zone_id  = local.zone_id
  data {
    name     = local.root_domain
    port     = 465
    priority = 0
    proto    = "_tcp"
    service  = "_submissions"
    target   = local.root_domain
    weight   = 1
  }
}
```

### Link to debug output

https://gist.github.com/waltervargas/8a576774c8daa95fc27da4e67e801a4d

### Expected output

No diff when using data block for cloudflare_record resource 

### Actual output

terraform show diff and changes to apply even when no code changes

### Steps to reproduce

1. apply a cloudflare_record resource with data block for a SRV type 
2. plan
3. see the diff

**Comment by waltervargas** [comment]
Should I invest time in implementing a fix or is this something you guys have already under your roadmap?

**Comment by jacobbednarz** [comment]
have you seen the deprecation notice for this? https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#2024-05-31

**Comment by jacobbednarz** [comment]
you haven't provided the actual diff you are seeing however i suspect this is the cause. in which case, this won't be changed as it is intentional.

**Comment by waltervargas** [comment]
> have you seen the deprecation notice for this? https://developers.cloudflare.com/fundamentals/api/reference/deprecations/#2024-05-31

No, I haven't seen it, but thanks for sharing.

**Comment by rquadling** [comment]
Why is this deprecation not being reported as part of terraform validation?
