### ISSUE TITLE
`cloudflare_record`: one of `content,data,value` must be specified

### ISSUE THREAD

**Issue by lorenx** [cloudflare/terraform-provider-cloudflare#4271]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.7
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.43.0
+ provider registry.terraform.io/hashicorp/google v6.6.0
+ provider registry.terraform.io/hashicorp/google-beta v6.6.0
+ provider registry.terraform.io/hashicorp/local v2.5.2

### Affected resource(s)

- cloudflare_record

### Terraform configuration files

```hcl
resource "cloudflare_record" "dns_records" {
  zone_id = var.my_dns_zone_id

  for_each = {
    for entry in var.dns_records:
      entry._id => entry
  }

  type = each.value.type
  name = each.value.name
  content = each.value.content
  priority = try(each.value.priority, null)
  proxied = false
  comment = each.value.comment
}
```

### Link to debug output

https://gist.github.com/lorenx/1da82e3a87fef0acb23e566cd5e97724

### Expected output

No output actually.
I just expect it to work by just silently doing nothing, with no errors of course.

### Actual output

Error: Invalid combination of arguments

  with module.cf.module.dns.cloudflare_record.dns_records["home"],
  on Cloudflare/DNS/main.tf line 16, in resource "cloudflare_record" "dns_records":
  16: resource "cloudflare_record" "dns_records" {

"data": one of `content,data,value` must be specified

Error: Invalid combination of arguments

  with module.cf.module.dns.cloudflare_record.dns_records["home"],
  on Cloudflare/DNS/main.tf line 16, in resource "cloudflare_record" "dns_records":
  16: resource "cloudflare_record" "dns_records" {

"value": one of `content,data,value` must be specified

Error: Invalid combination of arguments

  with module.cf.module.dns.cloudflare_record.dns_records["home"],
  on Cloudflare/DNS/main.tf line 26, in resource "cloudflare_record" "dns_records":
  26:   content = each.value.content

"content": one of `content,data,value` must be specified

### Steps to reproduce

I just changed `value` with `content` in my `cloudflare_record` resources.
If I try to put `value` back, it gives me the exact same error... but it also gives me the `value` deprecation warning.

**Comment by jacobbednarz** [comment]
do you get the issue if you don't use dynamics? i suspect this is a bug in either dynamic usage or terraform core because your foreach may have a nil value.

**Comment by lorenx** [comment]
Well, it seems you guessed right!

That entry has `content: null`, it's a dynamic A record and its IP is updated by a script.
I've always used it like that to make sure the record exists, without wiping its value.

But it seems that using `""` (empty string) works the same, without any error.
So thank you very for your intuition!

**Comment by jacobbednarz** [comment]
glad it hear it's sorted!
