### ISSUE TITLE
Misleading Resource Names in #3584

### ISSUE THREAD

**Issue by therealdwright** [cloudflare/terraform-provider-cloudflare#4379]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

In #3584 all resources are mistakenly named `clouflare` instead of `cloudflare` which is confusing for future onlookers. I tried to comment on the PR but it's locked to collaborators so raising a bug.

### Affected resource(s)

Zero Trust

### Terraform configuration files

```hcl
N/A
```

### Link to debug output

https://gist.github.com/therealdwright/dc829589ae80cf40be184e1c8dc5e2d0

### Expected output

N/A

### Actual output

N/A

### Steps to reproduce

N/A

### Additional factoids

N/A

### References

N/A

**Comment by jacobbednarz** [comment]
the spelling mistake you're referring to is only in the PR description. the resource names are correct in the provider and deprecation notes.

**Comment by therealdwright** [comment]
> the spelling mistake you're referring to is only in the PR description.

The spelling mistake in the PR description is what I was asking you to fix.
