### ISSUE TITLE
 .rules[0].logging: block count changed from 0 to 1.

### ISSUE THREAD

**Issue by VarshneyPrince** [cloudflare/terraform-provider-cloudflare#4442]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

latest 4.44.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "zone_custom_firewall_rules" {
  zone_id     = data.cloudflare_zone.zone_id.id
  name        = "tf-mid-global-custom-firewall-rules"
  description = "tf-mid-global-custom-firewall-rules"
  kind        = "zone"
  phase       = "http_request_firewall_custom"

  dynamic "rules" {
    for_each = var.AUTH_HEADERS_EXEMPTION
    iterator = prod_auth_header_rules
    content {
      action = "skip"
      action_parameters {
        phases = ["http_ratelimit"]
      }
      expression  = replace(local.exempt_auth_header_expression, "{AUTH_HEADER}", prod_auth_header_rules.value)
      description = "tf-mid-skip-auth-header-${prod_auth_header_rules.key}"
      
    }
  }
}
```

### Link to debug output

https://gist.github.com/VarshneyPrince/0796ef47344fd97e955da36b860e400d

### Panic output

Error: Provider produced inconsistent result after apply
When applying changes to module.cloudflare-rules-module.cloudflare_ruleset.zone_custom_firewall_rules, provider "module.cloudflare-rules-module.provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].logging: block count changed from 0 to 1.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Expected output

Resource gets created without any error.

### Actual output

Resource gets created but with error. 

Error: Provider produced inconsistent result after apply
When applying changes to module.cloudflare-rules-module.cloudflare_ruleset.zone_custom_firewall_rules, provider "module.cloudflare-rules-module.provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].logging: block count changed from 0 to 1.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to reproduce

1. Add this cloudflare_ruleset resource
2. Add multiple dynamic firewall rules
3. tf apply

**Comment by VarshneyPrince** [comment]
Already added the information there.

**Comment by sergeydi** [comment]
I have the same issue

**Comment by sergeydi** [comment]
Here it is simple configuration for clean CF zone WAF setup:

```
% ls
main.tf

% cat main.tf 
terraform {
  required_providers {
    cloudflare = {
      source  = "registry.terraform.io/cloudflare/cloudflare"
      version = "4.45.0"
    }
  }

  backend "http" {

  }
}

provider "cloudflare" {
  api_token = "API-TOKEN"
}

resource "cloudflare_ruleset" "custom_rules_builder" {
  name = "Custom rules"
  kind = "zone"
  description = "Zone custom rules created by Terraform"
  zone_id = "ZONE-ID"
  phase = "http_request_firewall_custom"

  rules {
    expression  = "(cf.bot_management.verified_bot)"
    description = "Verified Bots"
    action      = "skip"
    action_parameters {
      ruleset  = "current"
    }
  }
}

% terraform apply
cloudflare_ruleset.custom_rules_builder: Refreshing state... [id=ID-HIDEN]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_ruleset.custom_rules_builder will be created
  + resource "cloudflare_ruleset" "custom_rules_builder" {
      + description = "Zone custom rules created by Terraform"
      + id          = (known after apply)
      + kind        = "zone"
      + name        = "Custom rules"
      + phase       = "http_request_firewall_custom"
      + zone_id     = "ZONE-ID"

      + rules {
          + action       = "skip"
          + description  = "Verified Bots"
          + enabled      = true
          + expression   = "(cf.bot_management.verified_bot)"
          + id           = (known after apply)
          + last_updated = (known after apply)
          + ref          = (known after apply)
          + version      = (known after apply)

          + action_parameters {
              + ruleset = "current"
              + version = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

cloudflare_ruleset.custom_rules_builder: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cloudflare_ruleset.custom_rules_builder, provider
│ "provider[\"registry.terraform.io/cloudflare/cloudflare\"]" produced an unexpected new value: .rules[0].logging:
│ block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by thepoppingone** [comment]
any workarounds to this issue? v4.47 is still encountering the same error when adding new rules.

**Comment by jacobbednarz** [comment]
the `logging` field is only optional in the sense of the schema constraints. the service returns the `logging` value so you will need to provide it as part of your configuration - https://developers.cloudflare.com/waf/custom-rules/skip/api-examples/#skip-a-phase-and-do-not-log-matching-requests

**Comment by s-thom** [comment]
Would it be possible to get this added to the documentation somehow? I just came across the same issue and was left utterly confused as there is no mention of the logging configuration being required. 

It being returned by the API response feels more like an implementation detail which I'd expect the Terraform provider would take care of or would there would be a note that it's required in certain circumstances (with some examples of when).
