### ISSUE TITLE
provider crash during a resource import

### ISSUE THREAD

**Issue by dsmello** [cloudflare/terraform-provider-cloudflare#4479]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

TF version: 1.8.0
provider: v5.0.0-alpha1

### Affected resource(s)

- cloudflare_load_balancer

### Terraform configuration files

```hcl
resource "cloudflare_load_balancer" "mainnet-api" {
    name = "my.page.com"
    zone_id = "zone_id"
    default_pools = [
        "ID_1",
        "ID_2"
    ]
    fallback_pool = "ID_2"
    description = "API"
    proxied = true
    session_affinity = "cookie"
    session_affinity_ttl = 604800

    adaptive_routing = {
      failover_across_pools = true
    }

    random_steering = {
      steering_policy = "random"
    }
}
```

### Link to debug output

https://gist.githubusercontent.com/dsmello/22b4f1e1aaea3ce6c5f7ade6dc6ee741/raw/85c2bafaac0e671a19c72dcff28065316396aee5/gistfile1.txt

### Panic output

data.google_secret_manager_secret_version.cloudflare-apikey: Reading...
data.google_secret_manager_secret_version.cloudflare-apikey: Read complete after 0s [id=projects/171357058861/secrets/cloudflare-creds/versions/7]
cloudflare_load_balancer.mainnet-api: Importing from ID "ZONE_ID/LB_ID"...
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ImportResourceState call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-cloudflare_v5.0.0-alpha1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1142fc3]

goroutine 50 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/services/load_balancer.(*LoadBalancerResource).ImportState(0xc000fba060, {0x3393778, 0xc000e15680}, {{0xc000818e60?, 0x2f3c87d?}, {0x2d?}}, 0xc000bee9c0)
        github.com/cloudflare/terraform-provider-cloudflare/internal/services/load_balancer/resource.go:223 +0x203
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc000034f00, {0x3393778, 0xc000e15680}, 0xc000036230, 0xc000d39688)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_importresourcestate.go:136 +0x7d4
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc000034f00, {0x3393778?, 0xc000e15590?}, 0xc000e15530)
        github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_importresourcestate.go:47 +0x2a5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc00011ea00, {0x3393778?, 0xc000e14c00?}, 0xc00081a1e0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:896 +0x265
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x2e309a0, 0xc00011ea00}, {0x3393778, 0xc000e14c00}, 0xc0006f2700, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:536 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000153000, {0x3393778, 0xc000e14b70}, {0x33f8800, 0xc000bfa000}, 0xc000126b40, 0xc000775b90, 0x584e1d0, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000153000, {0x33f8800, 0xc000bfa000}, 0xc000126b40)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 20
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-cloudflare_v5.0.0-alpha1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

just to import the resource

### Actual output

panic

### Steps to reproduce

terraform import cloudflare_load_balancer.mainnet-api ZONE_ID/LB_ID

**Comment by jacobbednarz** [comment]
thanks. we're aware of the bugs here as it is intentionally not supported in alpha1. it will be in later releases.
