### ISSUE TITLE
panic when importing existing NS record

### ISSUE THREAD

**Issue by ZetaTwo** [cloudflare/terraform-provider-cloudflare#4546]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v5.0.0-alpha1
+ provider registry.terraform.io/hashicorp/google-beta v6.10.0

### Affected resource(s)

cloudflare_dns_record

### Terraform configuration files

```hcl
resource "cloudflare_dns_record" "ctftest1-ns1" {
  zone_id = var.cloudflare_zone_id
  name    = "ctftest1.zetatwo.dev"
  content   = "ns-cloud-c1.googledomains.com."
  type    = "NS"
  ttl     = 1
}
```

### Link to debug output

https://gist.github.com/ZetaTwo/23a23917108ab725283896054cec2e1e

### Panic output

tack trace from the terraform-provider-cloudflare_v5.0.0-alpha1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x101121e]

goroutine 23 [running]:
github.com/cloudflare/terraform-provider-cloudflare/internal/services/dns_record.(*DNSRecordResource).ImportState(0xc0001044e8, {0x3393778, 0xc000b7ea50}, {{0xc00015a960?, 0x2f3c87d?}, {0x2d?}}, 0xc000b11c80)
	github.com/cloudflare/terraform-provider-cloudflare/internal/services/dns_record/resource.go:231 +0x21e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ImportResourceState(0xc000972f00, {0x3393778, 0xc000b7ea50}, 0xc00016d0a0, 0xc000b07688)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_importresourcestate.go:136 +0x7d4
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ImportResourceState(0xc000972f00, {0x3393778?, 0xc000b7e960?}, 0xc000b7e900)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_importresourcestate.go:47 +0x2a5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ImportResourceState(0xc00094ea00, {0x3393778?, 0xc000b69f20?}, 0xc00014ebe0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:896 +0x265
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ImportResourceState_Handler({0x2e309a0, 0xc00094ea00}, {0x3393778, 0xc000b69f20}, 0xc000138e80, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:536 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000043000, {0x3393778, 0xc000b69e90}, {0x33f8800, 0xc000b24000}, 0xc000b798c0, 0xc000a29b90, 0x584e1d0, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000043000, {0x33f8800, 0xc000b24000}, 0xc000b798c0)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 22
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-cloudflare_v5.0.0-alpha1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected output

successful import or at least an error message telling me what I did wrong

### Actual output

panic and crash

### Steps to reproduce

1. Create an NS record in Cloudflare
2. Create terraform config with that NS record
3. Try to import the record to the terraform state

**Comment by jacobbednarz** [comment]
we're not taking issues for v5-alpha at the moment as these are known issues that will be addressed with later releases. you can also try the latest development branch if you'd like to potentially unblock yourself.

**Comment by ZetaTwo** [comment]
Oh, sorry about that. I just searched the terraform docs and used the latest provider that was available there. Didn't think about the alpha label. Anyway, that's great. As for my specific case, I ended up just deleting the records and let Terraform re-create them.

**Comment by jacobbednarz** [comment]
all good! the dev provider is moving quick squashing all the known things however the registry docs don't help convey the alpha status very well (known hashicorp thing).
