### ISSUE TITLE
cloudflare_zone_settings in documentation but doesn't exist - instead cloudflare_zone_settings_override exists

### ISSUE THREAD

**Issue by RichardoC** [cloudflare/terraform-provider-cloudflare#4547]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

$ tofu -v
OpenTofu v1.8.5
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.45.0

### Affected resource(s)

cloudflare_zone_settings

### Terraform configuration files

```hcl
# Doesn't exist

resource "cloudflare_zone_settings" "example_com" {
  zone_id    = cloudflare_zone.example_com.id
  id         = "ssl"
  setting_id = "value"
  value      = "strict"
}

# Does exist

resource "cloudflare_zone_settings_override" "example_com" {
  zone_id = cloudflare_zone.example_com.id
  settings {
    ssl = "strict"
  }
}
```

### Link to debug output

Cannot provide

### Expected output

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_setting_override should exist

### Actual output

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone_setting exists instead

### Steps to reproduce

Go to the official cloudflare provider documentation at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources and see that zone_setting is documented, and doesn't exist rather than zone_setting_override

**Comment by RichardoC** [comment]
In the 5.0.0-alpha1 docs cloudflare_zone_setting is documented but cloudflare_zone_settings_override isn't
In the 4.44.0/4.45.0 docs cloudflare_zone_settings_override is documented, but cloudflare_zone_settings isn't

This is very confusing, especially since cloudflare_zone_settings_override feels like the "better way" to do this.

**Comment by RichardoC** [comment]
I can't provide a log because this is a documentation issue not a provider code issue.

**Comment by jacobbednarz** [comment]
you're reading the documentation for v5.0.0-alpha1 but using 4.45.0. you'll need to toggle the documentation version to the correct version for the one you are using.
