### ISSUE TITLE
`cloudflare_record` don't yet support `settings` parameter

### ISSUE THREAD

**Issue by sosomuse** [cloudflare/terraform-provider-cloudflare#4595]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

```
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.46.0
```

### Affected resource(s)

- cloudflare v4.46.0
  - cloudflare_record
- cloudflare v5.0.0-alpha1
  - cloudflare_dns_record  

### Terraform configuration files

```hcl
resource "cloudflare_record" "example" {
  zone_id = var.zone_id
  name    = "name"
  content = "IP"
  type    = "A"
  ttl     = 1
  settings = jsonencode({"flatten_cname": true})
}
```

### Link to debug output

Probably not necessary here

### Expected output

It should accept "settings" here.

### Actual output

- v4.46.0

```
╷
│ Error: Unsupported argument
│ 
│   on cloudflare.tf line 30, in resource "cloudflare_record" "example":
│   30:   settings = jsonencode({"flatten_cname": true})
│ 
│ An argument named "settings" is not expected here.
╵
```

- v5.0.0-alpha1

```
│ Error: Invalid Configuration for Read-Only Attribute
│ 
│   with cloudflare_dns_record.example,
│   on cloudflare.tf line 30, in resource "cloudflare_dns_record" "example":
│   30:   settings = jsonencode({"flatten_cname": true})
│ 
│ Cannot set value for this attribute as the provider has marked it as read-only. Remove the configuration line
│ setting the value.
│ 
│ Refer to the provider documentation or contact the provider developers for additional information about
│ configurable and read-only attributes that are supported.
╵
```

### Steps to reproduce

1. Using 4.46.0 of terraform
2. Create a `cloudflare_record` object, and specify `settings` field
3. Receive error

or 

1. Using 5.0.0-alpha1 of terraform
2. Create a `cloudflare_dns_record` object, and specify `settings` field
3. Receive error

### Additional factoids

The Cloudflare API should be able to accept a `settings` object when creating or updating a `dns_record`.
https://developers.cloudflare.com/api/operations/dns-records-for-a-zone-create-dns-record

I tried to enable CNAME flattening, but I realized that the `settings` parameter was not valid.
https://developers.cloudflare.com/dns/cname-flattening/set-up-cname-flattening/#per-record

I'm happy to make the PR to fix it :)

**Comment by leonid-shevtsov** [comment]
Not stale. Waiting for this to be added.

**Comment by jacobbednarz** [comment]
given this is a feature request for v4, i'd recommend opening a support ticket to have it directed to the service team for triage.

v5 will automatically get this providing the schema is in place.

**Comment by leonid-shevtsov** [comment]
Thank you. Is there an ETA on v5?
