### ISSUE TITLE
Unable to fetch account id using data block "cloudflare_accounts" v4.46

### ISSUE THREAD

**Issue by xs2bharat** [cloudflare/terraform-provider-cloudflare#4607]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

4.46.0

### Affected resource(s)

cloudflare_accounts

### Terraform configuration files

```hcl
data "cloudflare_accounts" "example" {
  name = "example account"
}
```

### Link to debug output

NA

### Expected output

correct account id to be populated

### Actual output

getting some random account id

### Steps to reproduce

1. add block 
data "cloudflare_accounts" "example" {
  name = "example account"
}

**Comment by jacobbednarz** [comment]
how are you accessing the identifier?

**Comment by xs2bharat** [comment]
Found the issue. Should have been using  
data.cloudflare_accounts.account.accounts[0].id

Thanks @jacobbednarz for asking question which forced me re-read docs

**Comment by xs2bharat** [comment]
Found the issue. Should have been using
data.cloudflare_accounts.account.accounts[0].id

Thanks @jacobbednarz for asking question which forced me to re-read docs

**Comment by jacobbednarz** [comment]
correct - it is a plural resource so it can potentially return multiple results. glad you sorted it.
