### ISSUE TITLE
Make test on freshly-cloned repository fails

### ISSUE THREAD

**Issue by mrusso19** [cloudflare/terraform-provider-cloudflare#4635]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.7.4
on linux_amd64

### Affected resource(s)

- internal/framework/service/turnstile/resource.go
- internal/sdkv2provider/resource_cloudflare_teams_accounts.go

### Terraform configuration files

```hcl
Not important.
```

### Link to debug output

https://gist.github.com/mrusso19/0b6a01cbe965be4b966c9126a361eef3

### Expected output

I expect the test to run when using:
`make test`

### Actual output

```
# github.com/cloudflare/terraform-provider-cloudflare/internal/framework/service/turnstile
internal/framework/service/turnstile/resource.go:124:17: cannot use widget.OffLabel (variable of type bool) as *bool value in struct literal
internal/framework/service/turnstile/resource.go:125:17: cannot use widget.Name (variable of type string) as *string value in struct literal
internal/framework/service/turnstile/resource.go:126:17: cannot use widget.Domains (variable of type []string) as *[]string value in struct literal
internal/framework/service/turnstile/resource.go:127:17: cannot use widget.Mode (variable of type string) as *string value in struct literal
internal/framework/service/turnstile/resource.go:128:17: cannot use widget.BotFightMode (variable of type bool) as *bool value in struct literal
# github.com/cloudflare/terraform-provider-cloudflare/internal/sdkv2provider
internal/sdkv2provider/resource_cloudflare_teams_accounts.go:465:14: cannot use logSettings["redact_pii"].(bool) (comma, ok expression of type bool) as *bool value in struct literal
FAIL	github.com/cloudflare/terraform-provider-cloudflare [build failed]
make: *** [GNUmakefile:28: test] Error 1
```

### Steps to reproduce

1. Clone the repository
2. make test

### Additional factoids

From the error logs it seems clear that the problem is using bool and not *bool.

**Comment by jacobbednarz** [comment]
thanks for the heads up. this will occasionally happen as `master` is considered unstable. these issues are already being looked into and will be fixed in time. you can always use an earlier commit if you're after something that isn't yet released.

**Comment by jacobbednarz** [comment]
looks fine here 🤷 the changes you're referring to were not merged until after that release so i suspect something else is up if you're seeing that on the release commit.
