### ISSUE TITLE
Error: error creating cloudflare pages project

### ISSUE THREAD

**Issue by hkford** [cloudflare/terraform-provider-cloudflare#4729]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.10.0
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.47.0

Your version of Terraform is out of date! The latest version
is 1.10.1. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)

cloudflare_pages_project

### Terraform configuration files

```hcl
resource "cloudflare_pages_project" "from_terraform" {
  account_id        = var.account_id
  name              = "from-terraform"
  production_branch = "main"
  build_config {
    build_caching       = false
    build_command       = "hugo build"
    destination_dir     = "public"
  }
  deployment_configs {
    preview {
      always_use_latest_compatibility_date = false
      compatibility_date                   = "2024-12-06"
      compatibility_flags                  = []
      d1_databases                         = {}
      durable_object_namespaces            = {}
      environment_variables = {
        HUGO_VERSION = "0.139.0"
      }
      fail_open     = true
      kv_namespaces = {}
      r2_buckets    = {}
      secrets       = null # sensitive
      usage_model   = "standard"
    }
    production {
      always_use_latest_compatibility_date = false
      compatibility_date                   = "2024-12-06"
      compatibility_flags                  = []
      d1_databases                         = {}
      durable_object_namespaces            = {}
      environment_variables = {
        HUGO_VERSION = "0.139.0"
      }
      fail_open     = true
      kv_namespaces = {}
      r2_buckets    = {}
      secrets       = null # sensitive
      usage_model   = "standard"
    }
  }
  source {
    type = "github"
    config {
      deployments_enabled           = true
      owner                         = "hkford"
      pr_comments_enabled           = true
      preview_branch_excludes       = []
      preview_branch_includes       = ["*"]
      preview_deployment_setting    = "all"
      production_branch             = "main"
      production_deployment_enabled = true
      repo_name                     = "my-repo"
    }
  }
}
```

### Link to debug output

https://gist.github.com/hkford/ac852955a3abef09030faf38639266ef

### Expected output

Successfully create Cloudflare Pages project

### Actual output

Could not create Cloudflare Pages project

### Steps to reproduce

terraform apply

### Additional factoids

I created a Cloudflare Pages project from console and imported it into the Terraform configuration file using `terraform import`.

**Comment by hkford** [comment]
[TF_LOG=DEBUG output](https://gist.github.com/hkford/56da649447d7900ee3137df2c6ea67c9)

**Comment by taylorlee** [comment]
@hkford fyi there may be an issue creating projects with [Account Owned Tokens](https://developers.cloudflare.com/fundamentals/api/get-started/account-owned-tokens/). While we fix that, in the meantime you may be able to create your project using API Token Auth.

**Comment by hkford** [comment]
I'm using [API Token](https://developers.cloudflare.com/fundamentals/api/get-started/create-token/) and encountered this issue.

**Comment by taylorlee** [comment]
@hkford there was an issue with creating Pages projects using API Tokens that are owned by an account (as opposed to owned by a User). That issue has been fixed, so please let me know if you encounter any other issues!

**Comment by taylorlee** [comment]
@hkford there was an issue with creating Pages projects using API Tokens that are owned by an account (as opposed to owned by a User). That issue has been fixed, so please let us know if you encounter any other issues!

**Comment by hkford** [comment]
I confirmed I could successfully create Pages projects using API Tokens. Close the issue.
