### ISSUE TITLE
`cloudflare_ruleset`: An argument named "version" is not expected here.

### ISSUE THREAD

**Issue by robbert-nlo** [cloudflare/terraform-provider-cloudflare#4757]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform 1.10.2
cloudflare 4.48.0

### Affected resource(s)

cloudflare_ruleset

### Terraform configuration files

```hcl
resource "cloudflare_ruleset" "waf" {

(...)

  rules {
    action = "execute"
    action_parameters { 
      id      = local.cloudflare_managed_ruleset_id
      version = "latest"

(...)
```

### Link to debug output

n/a

### Panic output

│ Error: Unsupported argument
│ 
│   on modules/zone/managed_ruleset.tf line 115, in resource "cloudflare_ruleset" "waf":
│  115:       version = "latest"
│ 
│ An argument named "version" is not expected here.

### Expected output

A successful plan with a deprecation warning

### Actual output

Plan failed

### Steps to reproduce

1. Create a cloudflare_ruleset with a `rules.actionparameters` block containing a `version` argument.

### Additional factoids

Apparently the `version` parameter was removed from `rules.action_parameters` in 4.48.0 without any deprecation period. This wasn't mentioned in the release notes and also the documentation still mentions the argument as existing.

**Comment by jacobbednarz** [comment]
yes, it was called out in the release notes and CHANGELOG. the PR is #4697 if you would like to read more about it. 

there was no deprecation period as the field(s) don't actually do anything in the Terraform configuration nor could they be configured to do anything that would change the behaviour.

**Comment by robbert-nlo** [comment]
@jacobbednarz Hmm? I do not see anything about a removed `version` parameter in the release notes: https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v4.48.0. Would make sense to mention breaking changes there.

I applaud the PR, however it would also be nice to account for existing configurations of customers still including to-be-removed arguments, whether or not the argument was a no-op. But I guess this is also a way of getting there, just somewhat more harsh.

In any case, it should be removed from the docs if it doesn't exist anymore.

**Comment by jacobbednarz** [comment]
the source documentation has already been updated; see https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/ruleset.md. there is an ongoing issue we've been working with Hashicorp on for the registry documentation not always reflecting the correct version. in the meantime, the GitHub repository is the best place to read the latest version.
