### ISSUE TITLE
[resource_cloudflare_snippet] files is obfuscated when sensitive vars used

### ISSUE THREAD

**Issue by joshuamsager** [cloudflare/terraform-provider-cloudflare#4768]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.6.6
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.48.0

### Affected resource(s)

* snippet

### Terraform configuration files

```hcl
variable "signing_secret" {
  description = "Signing secret"
  type        = string
  sensitive   = true
}

variable "basic_auth_password" {
  description = "Password for basic auth"
  type        = string
  sensitive   = true
}

resource "cloudflare_snippet" "premium-fonts" {
  zone_id = "f1fe7d8092bf9aa7b5a6ca4c451d1fab"
  name    = "premium-fonts"

  main_module = "entrypoint.js"

  files {
    name = "entrypoint.js"
    content = "export default {async fetch(request) {return fetch(request)}};"
  }

  files {
    name = "secrets.js"
    content = templatefile("./config.js.tftpl", {
      basic_auth_user = "user"
      basic_auth_password = var.basic_auth_password
      signing_secret = var.signing_secret
    })
  }
}
```

### Link to debug output

N/A

### Expected output

Only `secrets.js`should be obfuscated in the `terraform plan`

```
  # cloudflare_snippet.premium-fonts will be created
  + resource "cloudflare_snippet" "premium-fonts" {
      + main_module = "entrypoint.js"
      + name        = "premium-fonts"
      + zone_id     = "f1fe7d8092bf9aa7b5a6ca4c451d1fab"

      + files {
          + content = "export default {async fetch(request) {return fetch(request)}};"
          + name    = "entrypoint.js"
        }
      + files {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }
```

### Actual output

Both files in the `terraform plan` is obfuscated

```
  # cloudflare_snippet.premium-fonts will be created
  + resource "cloudflare_snippet" "premium-fonts" {
      + main_module = "entrypoint.js"
      + name        = "premium-fonts"
      + zone_id     = "f1fe7d8092bf9aa7b5a6ca4c451d1fab"

      + files {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + files {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }
```

### Steps to reproduce

1. Copy configuration above
2. `terraform plan`

### Additional factoids

I believe its related to storing `files` as a [SetNestedBlock](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/framework/service/snippets/schema.go#L45)

and I think its resolved if switched to a `ListNestedBlock` instead.

The challenge with using a `ListNestedBlock` is that terraform enforces order. Cloudflare's Snippet API (undocumentedly) returns the files saved in their API in alphabetical order (based on filename) and not in the order that the user sent the files in.

**Comment by jacobbednarz** [comment]
as you note, swapping to a List from a Set is probably not possible here unless we enforce the order which would cause a lot of drift for folks using it as is today. given that 5.x is around the corner and we're not using the same semantics there, i'm hesitant to spend too much time investigating and rectifying this one given it works, just with some obscure schema handling caused by the plugin framework.
