### ISSUE TITLE
Cloudflare snippet rules are sorted by the rules' descriptions

### ISSUE THREAD

**Issue by troymjones** [cloudflare/terraform-provider-cloudflare#4788]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.10.2
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.48.0

### Affected resource(s)

cloudflare_snippet_rules

### Terraform configuration files

```hcl
resource "cloudflare_snippet" "snippet_robots" {
    zone_id = cloudflare_zone.zone["indeedflex.com"].id
    name    = "robots"
    files {
        name    = "robots.js"
        content = file("../snippets/robots.js")
    }
    main_module = "robots.js"
}

resource "cloudflare_snippet" "snippet_sitemap" {
    zone_id = cloudflare_zone.zone["indeedflex.com"].id
    name    = "sitemap"
    files {
        name    = "sitemap.js"
        content = file("../snippets/sitemap.js")
    }
    main_module = "sitemap.js"
}

resource "cloudflare_snippet" "snippet_redirect" {
    zone_id = cloudflare_zone.zone["indeedflex.com"].id
    name    = "redirect"
    files {
        name    = "redirect.js"
        content = file("../snippets/redirect.js")
    }
    main_module = "redirect.js"
  
}

resource "cloudflare_snippet" "snippet_lowercase" {
    zone_id = cloudflare_zone.zone["indeedflex.com"].id
    name    = "lowercase"
    files {
        name    = "lowercase.js"
        content = file("../snippets/lowercase.js")
    }
    main_module = "lowercase.js"
}

resource "cloudflare_snippet_rules" "rules_indeedflex" {
    zone_id = cloudflare_zone.zone["indeedflex.com"].id

    rules {
        enabled      = true
        expression   = "http.request.uri.path matches \"^/sitemap.xml$\""
        description  = "Transform sitemap request - rule #1"
        snippet_name = cloudflare_snippet.snippet_sitemap.name
    }
    rules {
        enabled      = true
        expression   = "http.request.uri.path matches \"^/robots.txt$\""
        description  = "Custom robots.txt - rule #2"
        snippet_name = cloudflare_snippet.snippet_robots.name
    }
    rules {
        enabled     = true
        expression  = "http.request.uri.path matches \"^/badpath/redirect$\""
        description = "Redirect bad path - rule #3"
        snippet_name = cloudflare_snippet.snippet_redirect.name
    }
    rules {
        enabled     = true
        expression  = "http.request.uri.path matches \"^/lowercase$\""
        description = "all lowercase letters are sorted last - rule #4"
        snippet_name = cloudflare_snippet.snippet_lowercase.name
    }
}
```

### Link to debug output

https://gist.github.com/troymjones/8e6d1f15560c18d70390569dac1f0b0e

### Expected output

The resource should respect the order of the list of rules OR at the very least provide a way to set a priority/order number. The only current way to do this dynamically that makes sense is to pad a number with zeros (due to lexicographical sorting) and prepend that to every description based upon the order.

### Actual output

List of rules was reordered based upon the lexicographical sorting of the description for each rule. 

### Steps to reproduce

See terraform configuration files for an example.

1. Add multiple snippets to a single zone
2. Reference those snippets in respective rules for the zone
3. Change the description to be out of order from the presented order of rules
4. Notice that on a plan/apply, the order of rules has changed to be alphabetically sorted based upon the rule description.

**Comment by jacobbednarz** [comment]
this isn't something we can control in the provider, sorry! you're best bet is to drop in a support ticket and have it routed to the correct team -- right now it is a set which is not ordered.
