### ISSUE TITLE
cloudflare_load_balancer "rules" attribute

### ISSUE THREAD

**Issue by gopurx** [cloudflare/terraform-provider-cloudflare#4789]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/cloudflare/cloudflare v4.48.0

### Affected resource(s)

cloudflare_load_balancer

### Terraform configuration files

```hcl
#4.48.0
resource "cloudflare_load_balancer" "load_balancer" {
  zone_id          = "0da42c8d2132a9ddaf714f9e7c920711"
  name             = "example-load-balancer.example.com"
  fallback_pool_id = cloudflare_load_balancer_pool.example.id
  default_pool_ids = [cloudflare_load_balancer_pool.example.id]
  description      = "example load balancer using geo-balancing"
  proxied          = true
  steering_policy  = "geo"
  adaptive_routing {
    failover_across_pools = true
  }
  rules {
    name      = "example rule"
    condition = "http.request.uri.path contains \"testing\""
    fixed_response {
      message_body = "hello"
      status_code  = 200
      content_type = "html"
      location     = "www.example.com"
    }
  }
}

#5.0.0-alpha1
resource "cloudflare_load_balancer" "example" {
  zone_id          = "0da42c8d2132a9ddaf714f9e7c920711"
  name             = "example-load-balancer.example.com"
  fallback_pool_id = cloudflare_load_balancer_pool.example.id
  default_pool_ids = [cloudflare_load_balancer_pool.example.id]
  description      = "example load balancer using geo-balancing"
  proxied          = true
  steering_policy  = "geo"
  adaptive_routing {
    failover_across_pools = true
  }
  rules = [{
    name      = "example rule"
    condition = "http.request.uri.path contains \"testing\""
    fixed_response = {
      message_body = "hello"
      status_code  = 200
      content_type = "html"
      location     = "www.example.com"
    }
  }]
}
```

### Link to debug output

NA

### Panic output

NA

### Expected output

NA

### Actual output

NA

### Steps to reproduce

NA

### Additional factoids

There seems good amount of differences between 4.48 vs 5.0.0, we are building load balancer and trying to find a better starting point to avoid surprises in near future for a major revamp with terraform config. Can you please suggest on which version to used as base?

Also, "rules" attribute is mentioned as beta in the documentation, checking when this will be GA or which version here is closest to be GA?

### References

Submitting this as a bug, did not found option to create it as a clarification?

**Comment by jacobbednarz** [comment]
v5.x is still doing alpha releases while v4.x is the stable main line. you can choose based on your appetite and risk which you'd like to pursue.

v4 to v5 is a major version and there will be breaking changes due to rearchitecting it.
