### ISSUE TITLE
Error while installing cloudflare/cloudflare v4.49.0: checksum list has unexpected SHA-256 hash

### ISSUE THREAD

**Issue by cheelim1** [cloudflare/terraform-provider-cloudflare#4818]
### Confirmation

- [X] This is a bug with an existing resource and is not a feature request or enhancement. Feature requests should be submitted with Cloudflare Support or your account team.
- [X] I have searched the issue tracker and my issue isn't already found.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Cloudflare provider version

terraform1.5.7

### Affected resource(s)

All resources.

### Terraform configuration files

```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4.0"
    }
  }
}

resource "cloudflare_dns_record" "example" {
  zone_id = var.cloudflare_zone_id
  name    = "terraform"
  value   = "192.0.2.1"
  type    = "A"
  ttl     = 3600
}
```

### Link to debug output

N/A

### Expected output

No errors and for it to work.

### Actual output

│ Error: Failed to install provider
│ 
│ Error while installing cloudflare/cloudflare v4.49.0: checksum list has
│ unexpected SHA-256 hash
│ 17e4acfc06f3f70a8d242a27441aab160db87295cf952733c741133ce4feae0f (expected
│ 69930ebc8c13c231a02c9a3bb608d45acd75f524413a9ffc72c17a78474dacb1)

### Steps to reproduce

1. Update cloudflare version to 4.49.0
2. terraform init

### References

I have to pin to the `4.48.0` version to temporary unblock on our end.
```
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.48.0" #temporary pinning version for a workaround
    }
  }
}
```

**Comment by olegbilovus** [comment]
I have the same issue. It happens with terraform and tofu when trying to install the 4.49.0 cloudflare provider.

I could replicate the issue with this simple main.tf:
```hcl
terraform {
  required_providers {
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.49.0"
    }
  }
}

```

Here is the DEBUG output:
```
terraform init                                             ─╯
2024-12-26T08:49:37.385+0100 [INFO]  Terraform version: 1.10.3
2024-12-26T08:49:37.386+0100 [DEBUG] using github.com/hashicorp/go-tfe v1.70.0
2024-12-26T08:49:37.386+0100 [DEBUG] using github.com/hashicorp/hcl/v2 v2.23.0
2024-12-26T08:49:37.386+0100 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-12-26T08:49:37.386+0100 [DEBUG] using github.com/zclconf/go-cty v1.15.1-0.20241111215639-63279be090d7
2024-12-26T08:49:37.386+0100 [INFO]  Go runtime version: go1.23.3
2024-12-26T08:49:37.386+0100 [INFO]  CLI args: []string{"terraform", "init"}
2024-12-26T08:49:37.386+0100 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2024-12-26T08:49:37.386+0100 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-12-26T08:49:37.387+0100 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-12-26T08:49:37.387+0100 [DEBUG] ignoring non-existing provider search directory /root/.terraform.d/plugins
2024-12-26T08:49:37.387+0100 [DEBUG] ignoring non-existing provider search directory /root/.local/share/terraform/plugins
2024-12-26T08:49:37.387+0100 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2024-12-26T08:49:37.387+0100 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2024-12-26T08:49:37.390+0100 [INFO]  CLI command args: []string{"init"}
Initializing the backend...
2024-12-26T08:49:37.394+0100 [DEBUG] checking for provisioner in "."
2024-12-26T08:49:37.460+0100 [DEBUG] checking for provisioner in "/usr/bin"
Initializing provider plugins...
- Finding cloudflare/cloudflare versions matching "4.49.0"...
2024-12-26T08:49:37.462+0100 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2024-12-26T08:49:37.947+0100 [DEBUG] GET https://registry.terraform.io/v1/providers/cloudflare/cloudflare/versions
2024-12-26T08:49:38.193+0100 [DEBUG] GET https://registry.terraform.io/v1/providers/cloudflare/cloudflare/4.49.0/download/linux/arm64
2024-12-26T08:49:38.413+0100 [DEBUG] GET https://github.com/cloudflare/terraform-provider-cloudflare/releases/download/v4.49.0/terraform-provider-cloudflare_4.49.0_SHA256SUMS
2024-12-26T08:49:39.344+0100 [DEBUG] GET https://github.com/cloudflare/terraform-provider-cloudflare/releases/download/v4.49.0/terraform-provider-cloudflare_4.49.0_SHA256SUMS.sig
- Installing cloudflare/cloudflare v4.49.0...
╷
│ Error: Failed to install provider
│
│ Error while installing cloudflare/cloudflare v4.49.0: checksum
│ list has unexpected SHA-256 hash
│ 689dc65b0eaf003eb8d55e7119c81abe466469ee7ad05a18ad4f72a87d81d000
│ (expected
│ 2f08c8243a0447814bda0678937f458c191bb9dad75818bacc485bed2896a1f9)
╵
```

**Comment by arafatkhan-optimizely** [comment]
Same Error, Checksum mismatch. All pipelines are failing, this is not any isolated event.


```
╷
│ Error: Failed to install provider
│ 
│ Error while installing cloudflare/cloudflare v4.49.0: checksum list has
│ unexpected SHA-256 hash
│ 17e4acfc06f3f70a8d242a27441aab160db87295cf952733c741133ce4feae0f (expected
│ 69930ebc8c13c231a02c9a3bb608d45acd75f524413a9ffc72c17a78474dacb1)
╵
Error: Process completed with exit code 1.

```

**Comment by lduparc** [comment]
Same error here. I also try older version starting 4.45 but same issue.
Blocking all CI provisioning plan

**Comment by VazquezAgustin** [comment]
Same error here

**Comment by kader-said-ratp** [comment]
same error here, temporary fixed it by fixing the version to 4.48.

**Comment by kader-said-ratp** [comment]
same error, had to fix it to 4.48

**Comment by iamcpdev** [comment]
Anyone have any solutions yet? This is a breaking issue for our team.

**Comment by romankydybets** [comment]
I find you how to by-pass this issue.
you need to find the last applied version to you infra.
In my case error were next
```
 Error: Failed to install provider
 
 Error while installing cloudflare/cloudflare v4.49.0: checksum list has
 unexpected SHA-256 hash
 17e4acfc06f3f70a8d242a27441aab160db87295cf952733c741133ce4feae0f (expected
 69930ebc8c13c231a02c9a3bb608d45acd75f524413a9ffc72c17a78474dacb1)
```
Last applied version were 4.48.0 
```
cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "4.48.0"
    }
```
I set it into versions.tf and it start working for me.

**Comment by lduparc** [comment]
> I find you how to by-pass this issue. you need to find the last applied version to you infra. In my case error were next
> 
> ```
>  Error: Failed to install provider
>  
>  Error while installing cloudflare/cloudflare v4.49.0: checksum list has
>  unexpected SHA-256 hash
>  17e4acfc06f3f70a8d242a27441aab160db87295cf952733c741133ce4feae0f (expected
>  69930ebc8c13c231a02c9a3bb608d45acd75f524413a9ffc72c17a78474dacb1)
> ```
> 
> Last applied version were 4.48.0
> 
> ```
> cloudflare = {
>       source  = "cloudflare/cloudflare"
>       version = "4.48.0"
>     }
> ```
> 
> I set it into versions.tf and it start working for me.

Yes -  Working workaround -  Thank you

**Comment by DemonICOLI** [comment]
Same here

**Comment by dggmsa** [comment]
same problem here!

**Comment by mariomartinez81** [comment]
Same here!

**Comment by DFanso** [comment]
still no solution??

**Comment by rkirby1** [comment]
Same problem. Provider 4.49.0 released 13 hrs have incorrect checksum.

**Comment by ebachle** [comment]
Friends... The solution is to pin your dependencies, it's in a comment above.  It was a bad release from under a day ago.  It'll be rolled back or fixed at some point coming up, but a reasonable solution is accessible and noted above.  You can update your required versions and that solves it.

If you commit your lock file as is standard best practice for all terraform this isn't an issue.

Let's be a little kinder to our colleagues at Cloudflare who were still working on shipping improvements on Christmas Day.

**Comment by sadminriley** [comment]
The solution is cloudflare fixing it with the correct SHA;tldr.

**Comment by ronballesteros** [comment]
> No need for the shoddy workarounds unless you _absolutely_ need the new provider version. The solution is cloudflare fixing the release with the correct SHA;tldr.

The above mentioned should be the fix.

**Comment by jacobbednarz** [comment]
please don't spam issues with "me too" comments. the issue description describes how to add your vote to the issue if you're impacted or interested in it. 

the checksum mismatch is due to the terraform registry receiving and caching an complete and failed build. the v4.49.0 release assets on GitHub are correct. already working with hashicorp to have it re-fetch the assets. failing that, i'll put out a no-op release to trigger the entire workflow again which may be easier given the holidays. 

in the meantime, you can pin to a previous version to unblock yourself.
