### ISSUE TITLE
Automate creation of certificates for tests

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/terraform-provider-cloudflare#524]
While doing some unrelated cleanup, I encountered the following failure.

```
=== RUN   TestAccCloudflareCustomSSL_Basic
=== PAUSE TestAccCloudflareCustomSSL_Basic
=== CONT  TestAccCloudflareCustomSSL_Basic
--- FAIL: TestAccCloudflareCustomSSL_Basic (0.28s)
    testing.go:569: Step 0 error: errors during apply:

        Error: Failed to create custom ssl cert: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":1206,\"message\":\"The certificate will expire within soon. Please supply a newer one\"}],\"messages\":[],\"result\":null}"

          on /opt/teamcity-agent/temp/buildTmp/tf-test656714404/main.tf line 2:
          (source code not available)
```

In one of our tests, we use a static TLS certificate (issued by Let's Encrypt) and it's expiry is approaching. I went ahead and generated a new one via #523 however it's not sustainable to keep doing this every N months. Instead, we should look to automate creation of these certificates during the test run so we never need to update this static reference again.

Something to consider is that this may be slow and error prone.

**Comment by patryk** [comment]
We could use [ACME provider](https://www.terraform.io/docs/providers/acme/index.html) to generate a new one, but I suppose the CI server does not provide a permanent storage. We could store it in e.g. [Google Cloud Storage](https://cloud.google.com/storage/).
