### ISSUE TITLE
Support organization and account level load balancer pools/monitors

### ISSUE THREAD

**Issue by solidDoWant** [cloudflare/terraform-provider-cloudflare#594]
It'd be great if the cloudflare_load_balancer_monitor and cloudflare_load_balancer_pool had a property to support for organization and account level monitors and pools. Here's the CloudFlare documentation:

- https://api.cloudflare.com/#organization-load-balancer-pools-create-pool
- https://api.cloudflare.com/#account-load-balancer-pools-create-pool
- https://api.cloudflare.com/#organization-load-balancer-monitors-create-monitor
- https://api.cloudflare.com/#account-load-balancer-pools-create-pool

Reviewing the documentation this (hopefully) would be somewhat simple. The key API difference between then is the endpoint - whether they use "user/load_balancers/..." vs "accounts/:account_identifier/load_balancers/..." or "organizations/:organization_identifier/load_balancers/...".

Maybe a block could be added that looks something like this:
```
type {
  name: 'user|account|organization'
  id: 'org/account ID required only for org/account'
}
```

This could be backwards compatible by defaulting the type block to user.

Does anybody know approximately how difficult this would be to implement? If it's as easy as it sounds/a good first issue I can probably create a PR this weekend.

**Comment by jacobbednarz** [comment]
> "organizations/:organization_identifier/load_balancers/...".

You don't need to use the `organizations` endpoint, `account` is the one you should be using and is completely compatible and isn't in the process of being deprecated.

In terms of how to trigger this in the provider, check out the documentation for [`account_id`](https://www.terraform.io/docs/providers/cloudflare/index.html#account_id) as this is already built in as a way to flag that you intend to use the account based resources.

https://github.com/terraform-providers/terraform-provider-cloudflare/blob/17ccdbf80402b0c82dd497100ed7aafce6552282/cloudflare/provider.go#L188-L193

The other thing you need to consider here is that you will first need to add support to the [`cloudflare-go` library](https://github.com/cloudflare/cloudflare-go) in order for it to have the underlying functionality here.

**Comment by jacobbednarz** [comment]
This functionality is already available by setting the `account_id` value in the provider configuration block which then forces the internals to use the account level endpoint.
