### ISSUE TITLE
Secondary zone support

### ISSUE THREAD

**Issue by sc0ttbeardsley** [cloudflare/terraform-provider-cloudflare#605]
### Terraform Version
any version

### Affected Resource(s)
- cloudflare_zone ?
- cloudflare_secondary_zone ?

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Should be able to configure a `secondary` zone according to [this documentation](https://support.cloudflare.com/hc/en-us/articles/360001356152-Configuring-Secondary-DNS)

### Actual Behavior
zones of type `secondary` are not allowed per [this code](https://github.com/terraform-providers/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_zone.go#L103)

This may need to be a new resource type...

### Important Factoids
n/a

### References
 - https://api.cloudflare.com/#secondary-dns-create-secondary-zone-configuration

**Comment by jacobbednarz** [comment]
This will first need to be added at https://github.com/cloudflare/cloudflare-go for the Terraform Provider to use it.

**Comment by oasys** [comment]
Thanks @jacobbednarz for implementing the upstream support!  I'm looking forward to using this in terraform.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.
