### ISSUE TITLE
Add support for Cloudflare Bot Management

### ISSUE THREAD

**Issue by LukasdeBoer** [cloudflare/terraform-provider-cloudflare#693]
Bot management is a service provided by CloudFlare that detects bots and exposes new variables you can use in custom firewall rules. For more information, see here: https://www.cloudflare.com/products/bot-management/

It is enabled/disabled in the Settings menu of a zone, but it is not exposed via the settings api so it can not be set using this provider at the moment.

I have made a feature request in the underlying cloudflare-go library: https://github.com/cloudflare/cloudflare-go/issues/467

**Comment by jacobbednarz** [comment]
See my response at https://github.com/cloudflare/cloudflare-go/issues/467#issuecomment-633705630

This needs public documentation before we will add support.

**Comment by thedotedge** [comment]
Hi, 
I think it's become relevant with https://blog.cloudflare.com/super-bot-fight-mode/?

**Comment by jacobbednarz** [comment]
Relevancy hasn’t been the issue here; there isn’t a public API to
support this yet. The support is still being worked out internally and
once available, will land upstream in cloudflare-go. I’d suggest
subscribing to the linked issue as well for any updates.

**Comment by thedotedge** [comment]
Thanks @jacobbednarz, my point was that it’s been 10 months since the original report, hopefully general availability would help to boost the priority of exposing BFM API endpoints.

**Comment by riveryc** [comment]
It's been nearly another year, not too sure the status of this one?

**Comment by LukasdeBoer** [comment]
The API was never finalized and Cloudflare has overhauled the entire setup. Bot management is now enabled by default, so I'm closing this issue.
