### ISSUE TITLE
cache_key_fields not working as expected

### ISSUE THREAD

**Issue by Arditc** [cloudflare/terraform-provider-cloudflare#740]
### Terraform Version
**version 0.12.26**

### Affected Resource(s)
Please list the resources as a list, for example:
 - "cloudflare_page_rule"
 - "gateway_rule"

### Debug Output
**Link to output**: https://gist.github.com/Arditc/87926506a494f1053426b802d7c04c50

### Expected Behavior
What should have happened?
So this is the clouldflare resource declared 

```
resource "cloudflare_page_rule" "gateway_rule" {
  zone_id  = cloudflare_zone.main.id
  target   = "${var.internal_subdomain}.${cloudflare_zone.main.zone}/"
  priority = 3

  actions {
    cache_level    = "cache_everything"
    edge_cache_ttl = 7200
    cache_key_fields {
      header {
        include = ["myHeader"]
      }
      cookie {}
      host {}
      query_string {}
      user {}
    }
  }
}
```

### Actual Behavior
What actually happened?
The plan was successful, however it failed with trying to apply the agreed plan.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Create a simple cloudflare tf resource as shown above and there seems to be an issue with the `cache_key_fields` section.
1. `terraform apply`

**Comment by Arditc** [comment]
I've done a work around to fix this issue by placing default values in places.

```
    cache_key_fields {
      header {
        include = ["myHeader"]
      }
      cookie {}
      host {
        resolved = false
      }
      query_string {}
      user {
        lang = false
      }
    }
```

**Comment by jacobbednarz** [comment]
Can you try without those empty blocks? You shouldn't be needing them if you're not using the inner structure.

**Comment by Arditc** [comment]
The only property I wanted to effect was the "include" header

**Comment by jacobbednarz** [comment]
Sorry, this was my misunderstanding. As the API returns what you send it plus any defaults (such as `host.resolved = false`) you pretty much always need to supply all fields 😞
