### ISSUE TITLE
cloudflare_records being recreated after v2 upgrade

### ISSUE THREAD

**Issue by c-ameron** [cloudflare/terraform-provider-cloudflare#742]
Hi there,

### Terraform Version
v0.12.28
CF provider 2.8.0, updating from v1.18.1

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_record

### Terraform Configuration Files
```hcl
resource "cloudflare_record" "foo" {
- domain = "example.com" 
+ zone_id = local.cloudflare_example_com_zone_id
  name    = "foo.example.com"
  type    = "CNAME"
  value   = "123.example.com"
  ttl     = 120
}

resource "cloudflare_record" "bar" {
- domain = "example.com" 
- name    = "bar.example.com"
+ zone_id = local.cloudflare_example_com_zone_id
+ name    = "bar"
  type    = "CNAME"
  value   = "test.example.com"
  ttl     = 120
}


```

### Debug Output
```
  # cloudflare_record.foo must be replaced
-/+ resource "cloudflare_record" "foo" {
      ~ created_on  = "2020-04-30T13:13:00.389029Z" -> (known after apply)
      - data        = {} -> null
      ~ hostname    = "foo.example.com" -> (known after apply)
      ~ id          = "xx123" -> (known after apply)
      ~ metadata    = {
          - "auto_added"             = "false"
          - "managed_by_apps"        = "false"
          - "managed_by_argo_tunnel" = "false"
          - "source"                 = "primary"
        } -> (known after apply)
      ~ modified_on = "2020-04-30T13:13:00.389029Z" -> (known after apply)
      ~ name        = "foo" -> "foo.example.com" # forces replacement
      - priority    = 0 -> null
      ~ proxiable   = true -> (known after apply)
        proxied     = false
        ttl         = 120
        type        = "CNAME"
        value       = "123.example.com"
        zone_id     = "yy"
    }

  # cloudflare_record.bar must be replaced
-/+ resource "cloudflare_record" "bar" {
      ~ created_on  = "2019-10-17T13:27:09.845112Z" -> (known after apply)
      - data        = {} -> null
      ~ hostname    = " bar.example.com" -> (known after apply)
      ~ id          = "xx345" -> (known after apply)
      ~ metadata    = {
          - "auto_added"             = "false"
          - "managed_by_apps"        = "false"
          - "managed_by_argo_tunnel" = "false"
          - "source"                 = "primary"
        } -> (known after apply)
      ~ modified_on = "2019-10-17T13:27:09.845112Z" -> (known after apply)
      ~ name        = "bar.example.com" -> "bar" # forces replacement
      - priority    = 0 -> null
      ~ proxiable   = true -> (known after apply)
        proxied     = true
        ttl         = 1
        type        = "CNAME"
        value       = "test.example.com"
        zone_id     = "yy"
    }

```
### Expected Behavior
It should ignore the zone domain at the end of the `name` record. It should not try and recreate the record, or if it does, it should be an update not a recreation

### Actual Behavior
It tries to recreate the record based on the name

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
- The record `cloudflare_record.foo` was an imported resource. To stop this recreation, I removed the `example.com` from the end of the `name`, and it would not recreate
- The `cloudflare_record.bar` was created via terraform. This was harder to fix. To remove the `example.com` from the `name`, I had to manually remove with `terraform state rm cloudflare_record.bar` and then reimport with `terraform import cloudflare_record.bar yy/xx345`

### References
It looks like the functionality to ignore the name diff in https://github.com/terraform-providers/terraform-provider-cloudflare/pull/151 was removed with the v2 upgrade in #460 see the removal of the `suppressNameDiff` function here https://github.com/terraform-providers/terraform-provider-cloudflare/commit/0995af450a63ec6d7a97cca38e22d65cb8fceff8#diff-3ae0c79a26074dff1a4c1eb1c2e059cbL601-L605

Was there a reason for this? Is the API only supposed to return the record now without the zone name at the end?

Luckily there's a workaround by either removing the zone for imported records, or manually removing and importing via state for records created via terraform. This works but the removal/importing is quite finicky.

Thanks!!

**Comment by jacobbednarz** [comment]
The change in #151 was intended as a stop-gap measure to get us to 2.x and remove the additional logic following the removal of `zone` as an attribute. Instead, the intended use was more aligned to the UI experience where you don't use the FQDN but only the label. It also paved the way for more sensible handling of aliases like `@`. 

An example of this migration was noted in the [v2 upgrade guide](https://www.terraform.io/docs/providers/cloudflare/guides/version-2-upgrade.html#cloudflare_record) for the `cloudflare_record` resource but I can see it's not explicitly called out so could be easily missed.
