### ISSUE TITLE
Page Rule Priority

### ISSUE THREAD

**Issue by virtuallytd** [cloudflare/terraform-provider-cloudflare#748]
Hi,

We have been creating a few page rules and have noticed that the "priority" flag seems to be the opposite in Cloudflare.

For example if I had 100 page rules all numbered 1 to 100. Rule 1 in Terraform would become rule 100 in Cloudflare and the last rule triggered where as with a priority of 1 I would expect it to be highest priority.

Is there a reason for this or is this by design?

**Comment by jacobbednarz** [comment]
The why (and a workaround) is discussed at https://github.com/cloudflare/terraform-provider-cloudflare/issues/187#issuecomment-450987683. Let me know if you have any follow up questions!
