### ISSUE TITLE
Page Rule modified_on and created_on information is missing in state

### ISSUE THREAD

**Issue by alexander-danilenko** [cloudflare/terraform-provider-cloudflare#756]
### Description

CloudFlare API returns `modified_on` and `created_on` page rule information ([according to API spec](https://api.cloudflare.com/#page-rules-for-a-zone-page-rule-details)). But this values are not stored in Terraform State after page rule creation/modification. 

For example for [record](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record) resources, these `modified_on` and `created_on` values goes to state and saved there. Is there any way to store these values in Terraform State for [page_rule](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule) resources?

Asking because my case requires to output these dates and compare them with dates that can be retrieved from CloudFlare API (for detecting changes applied manually thru Cloudflare UI).

### Terraform Version
```
Terraform v0.12.29
+ provider.cloudflare v2.9.0
```

### Affected Resource
- [page_rule](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule)

### Expected Behavior
`modified_on` and `created_on` attributes are saved to Terraform State for [page_rule](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule) resources

### Actual Behavior
`modified_on` and `created_on` attributes are **not** saved to Terraform State for [page_rule](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule) resources

### Steps to Reproduce

1. Add `cloudflare_page_rule` resource to main.tf file
   <details>
   <summary>example resource</summary>
   
   ```HCL
   locals {
     zone_id = "zone-id-here"
     redirects = {
       "somekey": {
         "status": "active",
         "from": "http://example.com/*",
         "to": "https://example.com/$1",
         "status_code": 301,
         "priority": 19
       },
       # More redirects here...
     }
   }
 
   resource "cloudflare_page_rule" "page_rules_redirects" {
     for_each = local.redirects
     zone_id  = local.zone_id
     target   = each.value.from
     status   = each.value.status
     priority = each.value.priority
     actions {
       forwarding_url {
         url         = each.value.to
         status_code = each.value.status_code
       }
     }
   }
   ```
   </details>

2. Run `terraform apply`
3. Actual result: Terraform State has no `modified_on` and `created_on` attributes
   <details>
   <summary>state dump</summary>
   
   ```JSON
    {
      "version": 4,
      "terraform_version": "0.12.29",
      "serial": 9,
      "lineage": "<SOME_UUID_GOES_HERE>",
      "resources": [
        {
          "mode": "managed",
          "type": "cloudflare_page_rule",
          "name": "page_rules_redirects",
          "each": "map",
          "provider": "provider.cloudflare",
          "instances": [
            {
              "index_key": "<KEY_GOES_HERE>",
              "schema_version": 0,
              "attributes": {
                "actions": [
                  {
                    # ...
                    "forwarding_url": [
                      {
                        "status_code": 301,
                        "url": "https://example.com/$1"
                      }
                    ],
                    # ...
                  }
                ],
                "id": "<PAGE_RULE_ID_GOES_HERE>",
                "priority": 1,
                "status": "active",
                "target": "http://example.com/*",
                "zone_id": "<ZONE_ID_GOES_HERE>"
              },
              "private": "some-private-key"
            }
          ]
        }
      ]
    }
   ```
   </details>

4. Expected result: Terraform State has `modified_on` and `created_on` attributes
   <details>
   <summary>state dump</summary>
   
   ```JSON
    {
      "version": 4,
      "terraform_version": "0.12.29",
      "serial": 9,
      "lineage": "<SOME_UUID_GOES_HERE>",
      "resources": [
        {
          "mode": "managed",
          "type": "cloudflare_page_rule",
          "name": "page_rules_redirects",
          "each": "map",
          "provider": "provider.cloudflare",
          "instances": [
            {
              "index_key": "<KEY_GOES_HERE>",
              "schema_version": 0,
              "attributes": {
                "actions": [
                  {
                    # ...
                    "forwarding_url": [
                      {
                        "status_code": 301,
                        "url": "https://example.com/$1"
                      }
                    ],
                    # ...
                  }
                ],
                "id": "<PAGE_RULE_ID_GOES_HERE>",
                "priority": 1,
                "status": "active",
                "target": "http://example.com/*",
                "zone_id": "<ZONE_ID_GOES_HERE>",
                "modified_on": "2014-01-01T05:20:00.12345Z",
                "created_on": "2014-01-01T05:20:00.12345Z",
              },
              "private": "some-private-key"
            }
          ]
        }
      ]
    }
   ```
   </details>

**Comment by jacobbednarz** [comment]
Are you able to explain the why behind your use case a little more as right now, I can't see a use as the API/UI timestamp will always match the Terraform state version and it will be updated on subsequent apply runs. 

Generally, you only put attributes into the schema which you would set (say, DNS record content) and output those generated by the remote API which you have no idea of the value and you intend to use them in other resources. I don't see where either of these would be applicable to the case you've mentioned above but I may be missing something.

**Comment by alexander-danilenko** [comment]
@jacobbednarz, my goal here is to detect any manual changes applied thru Cloudflare UI and if any changes were made after terraform latest update for that resource, just fail scheduled CI job with the only `terraform plan` command in it and highlight what resource was changed manually via UI, so we could start investigation who and why changed it even if now it has proper value.

Example:
- I'm adding via terraform page rule with 301 redirect.
- Once it's applied I manually change redirect target URL to different URL.
- After some time I'm changing it back, but a lot of users already got redirected to a wrong URL and 301 redirect cached in their browsers very aggressively.

Actual result:
- When I run `terraform plan` I have clear diff because redirect value has a proper value that was set manually via Cloudflare UI and I don't know about redirect change and a bunch of users who were redirected to wrong URL.

Expected result:
- Not clear diff, with only one item: Update Date change, which means that some changes to that resource were applied manually after it's applied by Terraform. Also, any manual changes applied for page rule record mean that some investigation should be done and detected reasons for that, because this change was not going thru the approval process in Terraform Cloud but added manually.

- - -

Is it something that can be achieved by Terraform at all?

Even if not, it's always nice to have that value in Terraform State, so it can be added to outputs (now there is no way to print it in outputs) and processed separately. Exactly this is already added in Record resource: it handles both `created_on` and `modified_on` in the state and it's easy to just output that values and use it. Is there any way to add these attributes to Page Rule resource's state as well?

**Comment by jacobbednarz** [comment]
Thanks for the clear explanation, it helps!

As for your use case, Terraform already does this out of the box. It maintains a known state and provides a diff when that state isn't what it has changed. This is the case that happens when a UI change is made outside of Terraform's state file. 

We use that exact process internally and it already works; the created/modified dates are superfluous as the `diff` will already show you what has changed. The other important piece here is the workflow. If you treat the Terraform state file as the golden source with version control, you have a pretty solid foundation. The bit that you may be missing is looking for resources only created in the UI that Terraform doesn't manage. We solve that by comparing API resource counts with Terraform resource counts and failing if they don't match.

**Comment by jacobbednarz** [comment]
If you're seeing a page rule condition **not showing** the full diff, please let me know as that is definitely a bug.
