### ISSUE TITLE
Requesting a data source corresponding to the cloudflare_access_group resource.

### ISSUE THREAD

**Issue by debayande** [cloudflare/terraform-provider-cloudflare#763]
It'd be nice to have a data source corresponding to the `cloudflare_access_group` resource as that'll make it easier to share Cloudflare Access groups across domains.

Thank you.

**Comment by jacobbednarz** [comment]
#754 goes more in depth but if you're looking to share access groups across zones, that will soon be possible as Access resources are account wide.

**Comment by jacobbednarz** [comment]
Closing as this use case is solved by cloudflare/cloudflare-go#486

**Comment by morremeyer** [comment]
@jacobbednarz Do I see it correctly that this does solve the issue when the `cloudflare_access_group` is managed in terraform, but not when it's managed outside of terraform? We do have a case where we do not configure the group, but need to set it. 

As far as I understand it, it is not possible right now to get the group by its name with a data source to find its ID. Is that correct?

We'll work around this by hard-coding for now, but if this is the case we might want to submit a PR to add a data source for access group(s).
