### ISSUE TITLE
page_rule ordering

### ISSUE THREAD

**Issue by ZebraFlesh** [cloudflare/terraform-provider-cloudflare#765]
How the heck are you supposed to order `page_rule` resources using terraform 0.13.0 and cloudflare provider 2.9.0? The solutions suggested in #187 don't work.

**Comment by ZebraFlesh** [comment]
I also don't see how `page_rule` resources can be maintained over time using terraform: if you have a list of n page rules and drop a new one in the middle, it seems like the Cloudflare API will always create it as priority = 1 regardless of any potential ordering solution.

**Comment by jacobbednarz** [comment]
The solution in #187 is still working for us between 50 and 110 page rules across ~ 30 domains.  I'd suggest re-reading the issue and providing a reproduction test case if you're continuing to have issues.
