### ISSUE TITLE
Support for updating cloudflare_custom_ssl in place

### ISSUE THREAD

**Issue by bas-papegaaij** [cloudflare/terraform-provider-cloudflare#784]
### Terraform Version
v0.12.29

### Affected Resource(s)
- cloudflare_custom_ssl

### Expected Behavior
cloudflare_custom_ssl resource is updated in place

### Actual Behavior
The resource is marked for destroy and recreate

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Make a change to a cloudflare_custom_ssl_resource
2. run terraform apply

The cloudflare_custom_ssl.custom_ssl_options is flagged with `ForceNew`, meaning it is impossible to update the resource in place. Presumably this is due to the fact that the Cloudflare API returns a new resource ID when PATCHing these settings. Is there any way to support in-place updates? Otherwise it is impossible to safely update a custom certificate without risking downtime unless we have more than one custom certificate slot.

**Comment by jacobbednarz** [comment]
Unfortunately not at this stage. Certificate changes (of any kind) end up recreating the resource on Cloudflare's end, hence the need for a replacement in Terraform. 

You can use Terraform's meta-argument for `lifecycle` however you still require N + 1 slots to handle the zero downtime rotation.

**Comment by avgerin0s** [comment]
Hello there, 

We recently noticed the same behavior. AFAICT, the [CF's API](https://api.cloudflare.com/#custom-ssl-for-a-zone-edit-ssl-configuration) allows in place updates, for some plans at least, though the provider does not.

Is there a technical limitation on not supporting in place updates in the provider?
