### ISSUE TITLE
Health checks are not able to see newly created DNS resources

### ISSUE THREAD

**Issue by ianbinder** [cloudflare/terraform-provider-cloudflare#786]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.28

### Affected Resource(s)
Please list the resources as a list, for example:
cloudflare_record
cloudflare_healthcheck

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
If I create a DNS record, and then want to create a health check for that site, it should create fine

### Actual Behavior
module.www-dns.cloudflare_record.record: Creating...
module.www-dns.cloudflare_record.record: Creation complete after 1s [id=056f8d5ef3f06a9a2ce4c0ed1299f15f]
module.www-dns.cloudflare_healthcheck.health_check: Creating...

Error: error creating standalone healthcheck: error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"lookup www.mysite.com on 10.32.0.10:53: no such host\"\n    }\n  ],\n  \"messages\": []\n}\n"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

resource "cloudflare_record" "record" {
  zone_id = lookup(data.cloudflare_zones.zone.zones[0], "id")
  name    = var.name
  value   = var.value
  type    = var.type
  proxied = var.proxy_enabled
}

resource "cloudflare_healthcheck" "health_check" {
  zone_id                      = lookup(data.cloudflare_zones.zone.zones[0], "id")
  name                         = "${var.env}-${var.name}"
  description                  = var.description
  address                      = cloudflare_record.record.hostname
  suspended                    = false
  check_regions                = ["WNAM","ENAM"]
  notification_suspended       = false
  notification_email_addresses = ["ibinder@binderworld.com"]
  type                         = "HTTPS"
  port                         = "443"
  method                       = "GET"
  path                         = "/"
  expected_codes               = ["2xx"]
  follow_redirects             = true
  allow_insecure               = false
  timeout                      = 10
  retries                      = 2
  interval                     = 60
  consecutive_fails            = 3
  consecutive_successes        = 2
}

**Comment by jacobbednarz** [comment]
Do you get the same issue if you wait a minute before applying the healthcheck to allow any DNS changes to propagate through Cloudflare's systems?

**Comment by ianbinder** [comment]
No, but there is no syntax you can use in Terraform to force a wait.

**Comment by ianbinder** [comment]
Maybe it would be possible to build some automatic retries into the
provider? It doesn't seem to take too long to propagate.

**Comment by jacobbednarz** [comment]
Thanks for confirming. As I'm sure you're aware at this point, the issue is that the dependant DNS system hadn't yet propagated the change and the healthcheck backend is failing to perform the lookup. I'm hesitant to retry on the exception provided ("no such host") as it's also possible the configuration is bad and by retrying, you end up with a longer feedback loop. As it boils down to DNS lookups, I'm unsure if we can catch only the cases where the record is propagating but exists compared to a busted configuration. My advice, for now, would be to create them in separate `apply`s and we can evaluate if this is a common issue and spend some more time on investigating other avenues of handling this scenario.

**Comment by ianbinder** [comment]
Separate applies are cool and all, but I was trying to make a template for
my team who has no idea how to set these up that does everything in one
place. Every time we create a record, I create the corresponding health
check. There is a lot of utility in that. It's a shame this is just getting
closed out.

**Comment by jacobbednarz** [comment]
> There is a lot of utility in that. It's a shame this is just getting closed out.

In this project, a closed issue isn't the end of the conversation. It merely means there isn't any further action required. Issues are also lightweight enough that we can continue the discussion and if there is new information or another approach suggested, we can reopen. It's far from a set and never change again status. 

While I agree it's a pain, you seem to be ignoring the other side of this request. If someone does manage to input an incorrect hostname and we retry, it takes the feedback cycle from ~ 1s to 30s. That is a significant workflow change and something we cannot take lightly given that we don't have insight into how everyone is using this resource.

I've put together #789 which adds the functionality and I'll ping a few others users of this provider to see whether it's something we can evaluate.
