### ISSUE TITLE
Custom Page Returns 504 Service Unavailable Despite Working

### ISSUE THREAD

**Issue by gstotts** [cloudflare/terraform-provider-cloudflare#805]
### Terraform Version
Terraform 11

### Affected Resource(s)
- cloudflare_custom_pages

### Terraform Configuration Files
```hcl
resource "cloudflare_custom_pages" "500_page" {
  zone_id = "${cloudflare_zone.myzone.id}"
  type    = "500_errors"
  url     = "https://myzone/500page"
  state   = "customized"
}
```

### Expected Behavior
Expected the resource to be created and state updated.

### Actual Behavior
Custom page was added on the Cloudflare Dashboard but the following error is presented in terraform and it continues to try and rebuild the resource each time CI is run:6
```hcl
Error: Error applying plan:

1 error(s) occurred:

* cloudflare_custom_pages.hy-vee_500_page: 1 error(s) occurred:

* cloudflare_custom_pages.hy-vee_500_page: failed to update '500_errors' custom page: error from makeRequest: HTTP status 504: service failure
```

### Steps to Reproduce
1. Create a new resource with a custom page listing for 500_errors.
2. Run `terraform apply`

### References
#260 

### Additional Information
Cloudflare Provider version 2.10.1

**Comment by jacobbednarz** [comment]
Can you please manually run this with `TF_LOG` debug attached? I'm unable to replicate the issue you've listed above.

Also, I'm unsure if you're using a `cloudflare_zone` resource but if you are, you're not referencing the `id` in your `zone_id` like you suspect you are; you'll be referencing the timestamp when the zone was fetched. The [example in the documentation](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/data-sources/zones#example-usage-with-other-resources) shows you how to correctly reference the ID.

**Comment by gstotts** [comment]
The zone is another resource I have referenced and not a data look up. I will run the debug when I get back to a machine.

**Comment by gstotts** [comment]
I should add that a `terraform plan` runs as expected... didn’t add that to the issue.

**Comment by jacobbednarz** [comment]
Using the following configuration, I haven't been able to reproduce this and the zone custom page is created and managed as expected.

```hcl
variable "cloudflare_zone_id" {}
variable "custom_page_url" {}

resource "cloudflare_custom_pages" "example_customised_custom_page" {
  zone_id = var.cloudflare_zone_id
  type    = "500_errors"
  url     = var.custom_page_url
  state   = "customized"
}
```

Running the `apply`

```
$ terraform init && terraform apply

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # cloudflare_custom_pages.example_customised_custom_page will be created
  + resource "cloudflare_custom_pages" "example_customised_custom_page" {
      + id      = (known after apply)
      + state   = "customized"
      + type    = "500_errors"
      + url     = "https://jacob-repro.s3.amazonaws.com/terraform-cloudflare-provider/gateway-timeout.html"
      + zone_id = "0da42c8d2132a9ddaf714f9e7c920711"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

And the state

```
$ terraform state show cloudflare_custom_pages.example_customised_custom_page
# cloudflare_custom_pages.example_customised_custom_page:
resource "cloudflare_custom_pages" "example_customised_custom_page" {
    id      = "9077e8f7c3cafd0f0d014e564895e65e"
    state   = "customized"
    type    = "500_errors"
    url     = "https://jacob-repro.s3.amazonaws.com/terraform-cloudflare-provider/gateway-timeout.html"
    zone_id = "0da42c8d2132a9ddaf714f9e7c920711"
}
```

I'm going to mark this one as not reproducible for now however I'd recommend checking your API token/key permissions and trying again to see if this was a transient issue.

I'd also advise you to upgrade to Terraform 0.12 if you haven't already as going forward much of the 0.11.x support in Terraform will be going away and providers will follow that version support too.
