### ISSUE TITLE
HTTP 403 when createing zone resource with sepcific plan

### ISSUE THREAD

**Issue by ep4sh** [cloudflare/terraform-provider-cloudflare#815]
### Terraform Version
Terraform v0.12.29
+ provider.cloudflare v2.11.0

### Affected Resource(s)
 - cloudflare_zone

### Terraform Configuration Files
```hcl
resource "cloudflare_zone" "qa" {
  zone = var.cloudflare_zone_name
  plan = "free"
}

```

### Debug Output
https://gist.github.com/ep4sh/b2c528997ea771920f0da735c23cb2ca

### Panic Output
https://gist.github.com/ep4sh/b2c528997ea771920f0da735c23cb2ca

### Expected Behavior
Zone resource is created with specific plan

### Actual Behavior
HTTP 403

### Steps to Reproduce
1. `terraform apply`

**Comment by jacobbednarz** [comment]
Can you please run the command again with `TF_LOG=DEBUG` and paste the output here (redacting any sensitive information)?

**Comment by ep4sh** [comment]
Hi @jacobbednarz 
Sure, it's here:

https://gist.github.com/ep4sh/e4d1be2583403e174737d523cece3635

Let me know if I can help with something

**Comment by jacobbednarz** [comment]
Using the following test case, I'm unable to reproduce the issue you've raised.

```hcl
variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "cloudflare_zone_id" {}
variable "cloudflare_account_id" {}
variable "cloudflare_zone" {}

provider "cloudflare" {
  email      = var.cloudflare_email 
  api_key    = var.cloudflare_api_key 
  account_id = var.cloudflare_account_id
}

resource "cloudflare_zone" "example" {
  zone = "gh-815.${var.cloudflare_zone}"
  plan = "free"
} 
```

I see you're using API tokens. Do you have the permissions correctly setup? Do you have the same issues when using an API key?

**Comment by jacobbednarz** [comment]
Closing due to lack of information. If you're still experiencing issues, please see https://github.com/cloudflare/terraform-provider-cloudflare/issues/815#issuecomment-713174141 for the outstanding questions to continue this issue investigation.

**Comment by agomezvidalee** [comment]
Same error described, using a token on cloudflare provider.
First iteration error and zone resource ends as "tinted"
Second iteration tries to delete and create the zone with error too.

**Comment by patryk** [comment]
@agomezvidalee Could you please provide a minimal .tf config file and how your API Token you use is configured?
