### ISSUE TITLE
403 for creating new firewall rules when CLOUDFLARE_API_TOKEN is set

### ISSUE THREAD

**Issue by upstart-swiss** [cloudflare/terraform-provider-cloudflare#816]
This is about the defaulting to using a token for auth without a fallback to using an API key. If this is a known issue, please point me in the right direction (I couldn't find it)

### Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/cloudflare/cloudflare v2.11.0

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudflare_firewall_rule
- cloudflare_filter

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl

resource "cloudflare_firewall_rule" "rule_example_1" {
  zone_id     = var.my_zone_id
  description = "example1"
  filter_id   = cloudflare_filter.filter_example_1.id
  action      = "block"
  priority    = 24000
}
resource "cloudflare_filter" "filter_example_1" {
  zone_id = var.my_zone_id
  description = "Example 2"
  expression = "ip.addr eq 1.2.3.4" //Fudged this, expression doesn't matter
} 

```

### Debug Output
Lots of sensitive information, important part is that it uses the Bearer token while the X-Auth-Key + X-Auth-Email is required as a token (403-ing)

### Expected Behavior
Creating the resource

### Actual Behavior
403

### Steps to Reproduce

1. Create new Firewall filters and rules
2. `terraform apply`

### Important Factoids
While I do not have a lot of expertise in Go, I think this may possibly be an issue better solved in cloudflare-go by forcing it to a different authType

* createFilters: https://github.com/cloudflare/cloudflare-go/blob/7bcc8b15e937ded86bdd66880c18548f25e5b7ea/filter.go#L117
* authType for requests: https://github.com/cloudflare/cloudflare-go/blob/fe9e1164c2c9b89406123221867ce3bf22678118/cloudflare.go#L179

This also _will work_ if you unset CLOUDFLARE_API_TOKEN and leave CLOUDFLARE_API_KEY declared.

**Comment by jacobbednarz** [comment]
Interesting, we use this resource internally with API tokens without
issue. Does the token have enough permissions. Would you be able to
screenshot them for me?

**Comment by upstart-swiss** [comment]
Absolutely - 
![image](https://user-images.githubusercontent.com/51336089/94979060-845a7d00-04d5-11eb-914c-8982e5edc294.png) I couldn't find any additional things to add that looked like they made sense.

Here's the 403 response ```
{
 "success": false,
 "errors": [
  {
   "code": 10000,
   "message": "Authentication error"
  }
 ]
}
```

**Comment by jacobbednarz** [comment]
I suspect you'll need some sort of account details level read. Could you bisect the permissions by adding all and then slowly combing them back until you get enough permissions to perform the operation?

**Comment by upstart-swiss** [comment]
![image](https://user-images.githubusercontent.com/51336089/95139253-e6f38900-0720-11eb-9467-1e2d12cca223.png)
Made a super token, still didn't work. Are you sure you aren't using CLOUDFLARE_EMAIL + CLOUDFLARE_API_KEY for your deploys?

**Comment by jacobbednarz** [comment]
Definitely using API tokens (curl examples below but `CLOUDFLARE_API_TOKEN` is picked up by the Terraform provider)

```
$ curl -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" https://api.cloudflare.com/client/v4/user/tokens/verify

{
  "result": {
    "id": "a40e4808a512df02a65492766e014852",
    "status": "active"
  },
  "success": true,
  "errors": [],
  "messages": [
    {
      "code": 10000,
      "message": "This API Token is valid and active",
      "type": null
    }
  ]
}
```

```
$ curl -sH "Authorization: Bearer $CLOUDFLARE_API_TOKEN" https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/firewall/rules | jq -r '.result_info.count'
7
```

Which request fails with the 403 for you?

**Comment by upstart-swiss** [comment]
GET requests work fine, only the POSTs to add new rules (and maybe modify, haven't tried that) fail:
```python
import requests

s = requests.session()
s.headers.update({'Authorization': f'Bearer {api_token}'})
filter_rule = [
    {
        "expression": "(cf.threat_score ge 10)",
        "paused": False,
        "description": "test1"
    }
]
r  = s.post(f"https://api.cloudflare.com/client/v4/zones/{zone_id}/filters", json=filter_rule)


```

**Comment by jacobbednarz** [comment]
I'm sorry, it still looks like something else is going on here as I can `curl` a payload without any issues.

```
$ curl -vs \
  -H "Content-Type: application/json" \ 
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  https://api.cloudflare.com/client/v4/zones/7b8373630de363bb741cfa712415c9e5/filters \
  -d '[{"expression":"ip.addr ne 172.16.22.155"}]'

*   Trying 104.19.192.29...
* TCP_NODELAY set
* Connected to api.cloudflare.com (104.19.192.29) port 443 (#0)
 .. snip
> POST /client/v4/zones/7b8373630de363bb741cfa712415c9e5/filters HTTP/2
> Host: api.cloudflare.com
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer [REDACTED]
> Content-Length: 43
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
* We are completely uploaded and fine
< HTTP/2 200
< date: Tue, 06 Oct 2020 21:27:34 GMT
< content-type: application/json; charset=UTF-8
<
{
  "result": [
    {
      "id": "f7faaf18492d42d39b700e4991bb2508",
      "paused": false,
      "expression": "ip.addr ne 172.16.22.155"
    }
  ],
  "success": true,
  "errors": [],
  "messages": []
}
```

Is the `zone_id` definitely correct? I know in the past I've pasted in the wrong account/zone ID and ended up with an authentication error which was kinda of misleading but still suitable.

**Comment by upstart-swiss** [comment]
Yeah, with this same code if I change it from 
```python
s.headers.update({'Authorization': f'Bearer {api_token}'})
```
 to 
```python
s.headers.update({
	'X-Auth-Email': f'{user_email}',
	'X-Auth-Key': f'{api_key}'})
```
it functions

**Comment by upstart-swiss** [comment]
Upon doing more testing, I can actually create the filter with my super token on the API today via code. I'll do some more testing on CF-TFN to see if it functions w/ the token now.

**Comment by upstart-swiss** [comment]
Found my issue... boy I feel dumb.

I had set the `CLOUDFLARE_API_TOKEN` in my environment earlier to a read-only token, and was changing a second environment variable called `CLOUDFLARE_TOKEN` to the highly privileged tokens. By switching the right environment variable, I've now got this working.

😬

**Comment by jacobbednarz** [comment]
glad to hear you got it working. bit of a shameless plug but https://github.com/jacobbednarz/cf-vault can help in managing profiles and avoid those type of issues by executing scripts in the context of the current profile and discard after use.

**Comment by upstart-swiss** [comment]
That looks great to use for me locally! I'll have me and my team set that up rather than have .env files living all over our machines.
