### ISSUE TITLE
X-Auth-Key vs Bearer access

### ISSUE THREAD

**Issue by knyttl** [cloudflare/terraform-provider-cloudflare#827]
### Terraform version
0.12.29

### Affected resource(s)
Cloudflare provider 2.11.0

### Description

Consider following config:

```
provider "cloudflare" {
  version    = "~> 2.0"
  email      = "***"
  api_key    = "***"
}
```
I want to authorize the plugin with email and api_key. When running locally, everything works correctly and I can see within the trace logging following:

```
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: ---[ REQUEST ]---------------------------------------
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: GET /client/v4/zones/*** HTTP/1.1
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: Host: api.cloudflare.com
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: User-Agent: HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.15.0 terraform-provider-cloudflare/2.11.0
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: X-Auth-Email: ***
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: X-Auth-Key: ***
```

However, when I run the same setup in CI, for some reasons, the requests look different as `Bearer` is used instead of `X-Auth-Key`:

```
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: ---[ REQUEST ]---------------------------------------
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: GET /client/v4/zones/*** HTTP/1.1
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: Host: api.cloudflare.com
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: User-Agent: HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.15.0 terraform-provider-cloudflare/2.11.0
[DEBUG] plugin.terraform-provider-cloudflare_v2.11.0: Authorization: Bearer ***
```

Notice the same version of both Terraform and Provider. However some of the requests with the Bearer are successful, but some of them don't – which is strange – it seems like it uses the `X-Auth-Key` to create the `Bearer`, but it does not assign enough rights to it.

- Where does the `Bearer` come from (as I don't use apiToken configuration)?
- Why does provider use the `Bearer` instead of `X-Auth-Key`?

### Expected behavior

In both settings I would expect it to use the `X-Auth-Key`.

### Actual behavior

Usage of `Bearer` rises from nowhere.

### Steps to reproduce

This is probably impossible to reproduce, I am not sure what causes this. I hope someone will know how does this work and help me debug this more.

**Comment by jacobbednarz** [comment]
The API token is triggered by setting the CLOUDFLARE_API_TOKEN environment variable (or `api_token` if you set it) and it takes precedent over the the API key configuration. 

You will either need to unset the variable or migrate to using API tokens which provides a finer grained permission model.

**Comment by knyttl** [comment]
Thanks. Maybe it would be great to log this as this is a bit unexpected as I was unaware of the fact we have this env var set.
