### ISSUE TITLE
invalid value for api_key (API key must only contain characters 0-9 and a-f (all lowercased))

### ISSUE THREAD

**Issue by IanMoroney** [cloudflare/terraform-provider-cloudflare#842]
### Terraform version
Terraform v0.13.0
+ provider registry.terraform.io/cloudflare/cloudflare v2.12.0

### Terraform configuration files

```hcl
provider "cloudflare" {
  version    = "2.12.0"
  email      = "email"
  api_key    = "api key with lowercase, numbers and uppercase (we have no control over the value of the api key)"
  account_id = "account id"
}
```

### Expected behavior

Cloudflare accepts the API key that it itself generated on the web portal.

### Actual behavior

The Cloudflare Terraform provider rejects the API key

### Steps to reproduce

Create any API key with lowercase, uppercase and numbers in it (i have also seen underscores in them)
add it to your providers config
run a terraform plan
### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
By the sounds of things, you're using an API _token_ not API _key_. Check out the documentation at https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#api_token for usage details.
