### ISSUE TITLE
Add verification of filter size 

### ISSUE THREAD

**Issue by dersoi** [cloudflare/terraform-provider-cloudflare#846]
### Current Terraform version

Terraform v0.13.4

### Description

The size of a filter is limited to 4096 chars on Cloudflare. This, however, is not checked by the plugin. This means that if you do a 4097 chars filter, it will tell you that it is OK, and proceed to crash at the _apply_ stage. 

### Use-cases

If you have an automated CI/Pipeline on Git, it is likely that as long as you are not on the master branch, you only do a _fmt, validate,_ and _plan_. These results are then used to determine if the new modifications can be merged to the master branch. If the filter is more than 4096 (which is frankly difficult to see with the naked eye), it passes all the tests. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
I'm on board with this to get earlier feedback in the change lifecycle 👍

We can use a `ValidateFunc` in the schema to call out to [`ValidateFilter`](https://github.com/cloudflare/cloudflare-go/blob/master/filter.go#L220) which will cover all the validations (not just size) and notify of any violations. This also ensures that we aren't duplicating the checks/logic of the Filters API in the Terraform provider. 

@dersoi Are you interested in taking a pass at putting up a PR for this one?

**Comment by dersoi** [comment]
@jacobbednarz I see you were faster than I. Thank you! Do you know when the next release wil be ?

**Comment by jacobbednarz** [comment]
Roughly monthly or when there is enough features/fixes to go out on it’s
own. We’re pretty early in the current cycle so maybe a couple of weeks
time depending on what else happens?

**Comment by dersoi** [comment]
Awesome thanks!

**Comment by jacobbednarz** [comment]
I've reverted #848 and this needs to wait until we API token support on that endpoint.

**Comment by jacobbednarz** [comment]
This is good to go again now the endpoint supports API tokens

**Comment by jacobbednarz** [comment]
closing this off as there isn't a great way to:

- reuse the existing HTTP client; and
- pull the credentials using `d.Get` from the schema validation in question.

may revisit in the future if the schema method recievers change.
