### ISSUE TITLE
Worker secret resources

### ISSUE THREAD

**Issue by helenatuominen** [cloudflare/terraform-provider-cloudflare#849]
### Current Terraform version
0.13.5

### Description
The cloudflare API and cloudflare-go both expose the capability of directly adding secrets to workers non-destructively, having this available in Terraform would bring parity and allow further flexibility around IaC and worker CI/CD pipelines. Currently terraform-provider-cloudflare only allows secrets to be added at time of provision, requiring the script to accompany the worker.
I'm personally happy to work on a PR for this.

### Use-cases
A good use case we have is routes, workers and secrets (ie. cloud access keys) provisioned via Terraform, then subsequent upload of scripts to workers via a separate build-push pipeline. An option immediately pops out:
1. Allow worker resources with empty or no script value; and optionally
2. A distinct Terraform resource for worker secrets

### Potential Terraform configuration
1.
```
resource "cloudflare_worker_script" "my_script" {
  name = "script_1" # Note the absence of a script file.

  secret_text_binding {
    name = "MY_EXAMPLE_SECRET_TEXT"
    text = var.secret_foo_value
  }
}
```
2.
```
resource "cloudflare_worker_script" "my_script" {
  name = "script_1"
}

resource "cloudflare_worker_secret" "my_script_secret" {
  script_name = "script_1"
  name = "MY_EXAMPLE_SECRET_TEXT"
  text = var.secret_foo_value
}
```

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by helenatuominen** [comment]
@jacobbednarz should I follow through with this PR?

**Comment by jacobbednarz** [comment]
@helenatuominen Apologies for not looking at this one sooner but digging into the Workers side of things with Terraform/cloudflare-go translation is always alot of context to carry on and I just haven't had time. 

Looking at the Terraform resources and the Cloudflare documentation, it hints using the resources as we currently model:

> Resource bindings allow you to attach resources, such as secrets, or KV namespaces to your Worker script. If you are including Resources in your Worker, you need to specify their Bindings as a part of your upload
>
> -- https://developers.cloudflare.com/workers/platform/scripts#resource-bindings

> Currently terraform-provider-cloudflare only allows secrets to be added at time of provision, requiring the script to accompany the worker.

I'm also not able to see where `cloudflare-go` is enabling uploading worker bindings outside the context of the script. All the calls I can see either:

- pass in the body as raw bytes; or
- use the `*Binding` structs to construct

I might be missing something here so could you point me to where you're seeing this capability?

Touching on the use cases directly.

> Allow worker resources with empty or no script value

This restriction is in place as the API has a validation that the value cannot be empty and is required. If you need to upload a script but not have it active, you can either write a pass through script or don't assign it to any routes.

> A distinct Terraform resource for worker secrets

The decision was made to match the existing Worker bindings and maintain the backwards compatibility with via #710. Given the recommended (and only way I can find) requires the bindings to be uploaded at creation time, I'm not sure if I'd create a new resource for this.

Could you explain more about your CI/CD process as I think I'm missing something. We use 100% IaC internally and haven't ever rubbed up against this so I'm keen to know more.

**Comment by helenatuominen** [comment]
Hi @jacobbednarz, thank you for your comprehensive response, I am being super cautious and want sure that any changes match with API intents.

> Currently terraform-provider-cloudflare only allows secrets to be added at time of provision, requiring the script to accompany the worker.

CF doco is out of sync with the REST API right now, however the cloudflare-go lib is in sync with the REST API, via the workers_secrets.go functions. I'm in process of a further write-up for this issue as after running checks with Postman against our account I can confirm Worker bindings can be Put and Deleted independently of the Worker itself.

**Comment by jacobbednarz** [comment]
Thanks @helenatuominen, appreciate it!

paging @jRiest who might be able to help with this one too

**Comment by helenatuominen** [comment]
@jacobbednarz 
Agreed - the provision of Workers must include a script, however the secrets can be applied at a subsequent time. Currently we manually create the Workers, then the CI/CD process uses a separate deploy directly against the Cloudflare REST API. This is likely to change in the future to be more consistent with Terraform intent, but for now this will suffice.

As such I won't require any change to the cloudflare_worker_script resource, but would like to move ahead with a new cloudflare_worker_secret resource as the cloudflare-go and REST APIs both permit this method. This would follow the example in 2. above :
```
resource "cloudflare_worker_secret" "my_script_secret" {
  script_name = "script_1"
  name = "MY_EXAMPLE_SECRET_TEXT"
  text = var.secret_foo_value
}
```

Would this be appropriate?

**Comment by trjstewart** [comment]
Hey @jacobbednarz.
Perhaps to just provide a little more context on our internal use case (@helenatuominen and I work together) and provide my thoughts.

We currently deploy Workers via the Wrangler CLI and not via Terraform, but we do use Terraform to manage the routes for these workers. The primary reason for this is we use TypeScript and Webpack and that workflow doesn't lend well to Terraform land from our experience. The workers are deployed out of band from our infrastructure and the CI/CD experience with Wrangler CLI is fantastic for this. Unfortunately what's not great with Wrangler CLI when it comes to CI/CD is getting any information from Terraform into Workers Secrets (understandably).

Our specific use case at the moment is wanting to provision an `aws_iam_access_key` and set `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as secrets based on that resource. This is irrelevant to the implementation of this feature, but hopefully provides some context.


I've taken a look with @helenatuominen and the existing API in cloudflare-go (specifically within [workers_secrets.go](https://github.com/cloudflare/cloudflare-go/blob/master/workers_secrets.go)) looks to support the listing (names, not values), setting, and deleting of secrets. I've also verified this behavior works as expected using Postman. I have also verified that after setting a secret via this API and then updating the Worker via the Wrangler CLI that the secret remains in place.

What we're looking to do here is follow a pattern similar to the `cloudflare_worker_route` resource and provide a new `cloudflare_worker_secret` resource to allow the management of an individual secret attached to a worker, without having to manage the worker itself.

**Comment by jacobbednarz** [comment]
> The primary reason for this is we use TypeScript and Webpack and that workflow doesn't lend well to Terraform land from our experience

Can definitely sympathasis here 😄 We currently have this exact flow but automated. A separate repository for the code itself and the Terraform `cloudflare_worker_script` just references the generated file in the repository.

Thanks for doing that dive into the code and I think I've just realised where my confusion with this was. It looks like `cloudflare-go` supports setting secrets as a worker binding _and_ individually but neither reuse the functionality 🤷‍♂️

After thinking about this (and demistifying my confusion), the new resource seems appropriate. The only thing I'd like to make sure we include is some sort of guidance that helps people determine whether to use the dedicated resource _or_ the binding attached to the worker script itself to avoid wondering why there are two ways of doing things. How does that sound?

**Comment by trjstewart** [comment]
That sounds perfect. I'll make sure we get some clear documentation written up as part of the PR. Cheers!

**Comment by helenatuominen** [comment]
Great, continuing work. Thanks @jacobbednarz and @trjstewart!

**Comment by helenatuominen** [comment]
Hi @jacobbednarz, I'll put through the changes to the resource itself, but I need to work on the usage in our Terraform plans for the next few work days, using a built dev version of the provider. I'll be taking a look this weekend into the test methodology to find a way to a pattern more consistent with the existing tests of the provider.
