### ISSUE TITLE
Do not always need credentials.

### ISSUE THREAD

**Issue by DingGGu** [cloudflare/terraform-provider-cloudflare#850]
### Current Terraform version
```
Terraform v0.13.5
+ provider registry.terraform.io/cloudflare/cloudflare v2.12.0
```

### Description
Currently, Using cloudflare providers needs credentials before using.
However, I don't think credential is required when using only cloudflare_ip_ranges.

It can visit https://api.cloudflare.com/client/v4/ips without credentials.
This API explained at https://api.cloudflare.com/#cloudflare-ips-properties

### Potential Terraform configuration

```hcl
# Copy-paste your Terraform configurations here.
provider "cloudflare" {
}

data "cloudflare_ip_ranges" "cloudflare" {}

terraform {
  required_version = ">= 0.13"
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "~> 2.12.0"
    }
  }
}
```

### References
https://api.cloudflare.com/#cloudflare-ips-properties

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
You're right that the endpoint doesn't require them (and we don't actually send them in the request) however that endpoint is the exception and all other endpoints require authentication. From a usability stand point, the provider is better off requiring authentication across the board to avoid tripping people up on whether or not they need to set it.

**Comment by kam1kaze** [comment]
I'm working on a terraform module where I need to get a list of Cloudflare IPs. Unfortunately, Cloudflare provider does not allow to do this without auth data :( So I make the following work-a-round:

```
data "http" "cloudflare_ips" {
  url = "https://api.cloudflare.com/client/v4/ips"
  request_headers = {
    Accept = "application/json"
  }
}
locals {
  cloudflare_ip_ranges = jsondecode(data.http.cloudflare_ips.body)
  whitelist_networks = join(",", concat(local.cloudflare_ip_ranges.result.ipv4_cidrs, local.cloudflare_ip_ranges.result.ipv6_cidrs))
}

```

**Comment by LordMike** [comment]
Can you at least update the docs to not say "optional" on all parameters - or at least describe somewhere that credentials **_are_** required. ?

https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs

:)

**Comment by philnichol** [comment]
Just popping these here in case they are any use to anyone, couple of other workarounds:
- As noted [here](https://github.com/skwashd/terraform-aws-cloudflare-ips-security-group#cloudflare-source-ips-aws-security-group-ingress), you can use `"YQSn-xWAQiiEh9qM58wZNnyQS7FUdoqGIUAbrh7T"` as the cloudflare api token, which is lifted from the Cloudflare docs and passes validation (at the time of writing)
- Use this [hacky provider](https://registry.terraform.io/providers/philnichol/commonips/latest/docs/data-sources/cloudflare) I wrote (The underlying code is copied from this provider).

**Comment by mattiasholm** [comment]
Using version *3.32.0*, I'm able to use the *cloudflare_ip_ranges* data source by simply providing any 40-digit string as the API token.

I figured using all zeros is more appropriate for a dummy value, instead of something that resembles an actual token.

```terraform
provider "cloudflare" {
  api_token = "0000000000000000000000000000000000000000"
}
```
