### ISSUE TITLE
Origin CA key usage is unclear

### ISSUE THREAD

**Issue by snypelife** [cloudflare/terraform-provider-cloudflare#851]
### Terraform version

Terraform v0.13.5

### Affected resource(s)

- provider.go
- cloudflare_origin_ca_certificate

### Terraform configuration files

```hcl
provider "cloudflare" {
  version = "~> 2"
  api_user_service_key = "<Origin CA Key>"
}
```

### Panic output

```
Error: credentials are not set correctly

  on providers.tf line 28, in provider "cloudflare":
  28: provider "cloudflare" {
```

### Expected behavior

To properly communicate with the Cloudflare API.

### Actual behavior

It errored complaining about `credentials not set properly`

### Steps to reproduce

1. `terraform plan` (affects apply too)

### Important factoids

So I am unsure if this behaviour is intended or not, but it seems currently you need to provide an `api_token` or `email+api_key` AND the `api_user_service_key` when working on resources such as `cloudflare_origin_ca_certificate`.

- If it is intended, I do feel the docs need to be modified in order to show that.
- If it is not intended, it appears that this conditional in the `provider.go` needs to be updated https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/provider.go#L183-L198

```go
	if v, ok := d.GetOk("api_token"); ok {
		config.APIToken = v.(string)
	} else if v, ok := d.GetOk("api_key"); ok {
		config.APIKey = v.(string)
		if v, ok = d.GetOk("email"); ok {
			config.Email = v.(string)
		} else {
			return nil, fmt.Errorf("email is not set correctly")
		}
	} else {
		return nil, fmt.Errorf("credentials are not set correctly")
	}

	if v, ok := d.GetOk("api_user_service_key"); ok {
		config.APIUserServiceKey = v.(string)
	}
```

I am more than happy to contribute to either, however I did just want to know the intention prior to doing anything.

Thanks!

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
Looking at the examples and use cases that I know of, I think the first is intended. When providing a service key, you also want the other credentials also set as the service key is a small subset of resources and can't be used across other resources whereas the others can. Imagine, `cloudflare_origin_ca_certificate` in combination with `cloudflare_records` where both sets of credentials are required to successful make resource changes.

👍 to updating the documentation however I'm unsure what you'd specifically change to clarify as the resource documentation just mentions it is required -- not that it is the *only* credential required and the overview page tells you it is optional.

**Comment by snypelife** [comment]
Yeah that's what I kind of figured 👍.

Regarding the docs, because of the naming of things like `api_key`, `api_token`, `api_user_service_key`, and the usage of `api_key` and `api_token` being mutually exclusive, without direction it seemed `api_user_service_key` was to be used in the same manner.

While I saw in the docs it said that the `api_user_service_key` was required to perform these operations, it seems like simply updating the messaging to say something like 

> This resource requires you use your Origin CA Key as the `api_user_service_key` in conjunction with an `api_token` or `email` and `api_key`.

Perhaps also including the configuration example, the usage of this:
```hcl
provider "cloudflare" {
  version = "~> 2.0"
  api_token = "${var.cloudflare_api_token}"
  api_user_service_key = "${var.cloudflare_api_user_service_key}"
}
```

However, this one kind of breaks the docs convention, so I'm not sold on it.

Perhaps including this messaging also in the provider docs:
```
api_user_service_key - (Optional) The Cloudflare API User Service Key. This can also be specified with the
CLOUDFLARE_API_USER_SERVICE_KEY shell environment variable. This is used for a specific set of endpoints, 
such as creating Origin CA certificates. To be used in conjunction with an `api_token`, or `email` and `api_key`.
```

Thanks for taking the time to respond, much appreciated! 💯

**Comment by jacobbednarz** [comment]
I can definitely see the confusion there, thanks for the write up! I think we can do better here; would you like to take a pass at this one?

**Comment by snypelife** [comment]
I'd be happy to 😄
