### ISSUE TITLE
Feature Request: Support Worker Cron Triggers

### ISSUE THREAD

**Issue by ldesgoui** [cloudflare/terraform-provider-cloudflare#853]
### Description

Cron Triggers are a recent addition to Workers, it would be nice to be able to control them via terraform

https://blog.cloudflare.com/introducing-cron-triggers-for-cloudflare-workers/
https://blog.cloudflare.com/cron-triggers-for-scheduled-workers/

### References

https://developers.cloudflare.com/workers/platform/cron-triggers
https://api.cloudflare.com/#worker-cron-trigger-properties
https://github.com/cloudflare/cloudflare-go/issues/549

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
This sounds good. It will be depending changes in the upstream cloudflare-go library so we'll wait for that.

**Comment by jacobbednarz** [comment]
`cloudflare-go` support is coming via cloudflare/cloudflare-go#570
