### ISSUE TITLE
Ability to create custom API tokens using terraform 

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#856]
### Current Terraform version

0.13.5

### Description

need ability to create API tokens using terraform provider 

### Use-cases

We are trying to create turnkey solution where zone and its respective API token are created via TF provider.
Currently we dont see an option to create an API token and assign permissions to it via TF CF provider.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
@vital4ik Are you interested in taking a crack at this one?

**Comment by UrosSimovic** [comment]
It is already prepared:
https://github.com/cloudflare/terraform-provider-cloudflare/pull/862

But waiting for upstream https://github.com/cloudflare/cloudflare-go to merge:
- https://github.com/cloudflare/cloudflare-go/pull/552
- https://github.com/cloudflare/cloudflare-go/pull/553

**Comment by UrosSimovic** [comment]
Upstream merged both of them. Waiting for `v0.13.5` release, then changing version in go.mod.

**Comment by jacobbednarz** [comment]
You don't need to change anything; the dependency PR will be raised and merged and then these can be merged in as is.
