### ISSUE TITLE
Need ability to use custom API token with the CF TF provider

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#857]
### Current Terraform version

0.13.5

### Description

We are trying to use the custom created API token to perform certain functions with cloudflare terraform provider. However, it seems that only GLOBAL API key is working with the provider. this leads us to believe that terraform provider uses the different headers that work only with global API keys. This is reproducible via using Curl command with either global or custom API keys.
please see attached file for the example. Question for how, how can we use terraform adapter with custom api token and not the global api key, given using global api key is a big security issue for us.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
Both API keys and API tokens are supported by the provider to interact with the API. Please consult the documentation for details on setting and defining them - https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs#argument-reference
