### ISSUE TITLE
Off by 1 bug in resource_cloudflare_authenticated_origin_pulls_* importing

### ISSUE THREAD

**Issue by dhaynespls** [cloudflare/terraform-provider-cloudflare#858]
These should be the number `3` as `len()` is not zero-indexed. 

https://github.com/cloudflare/terraform-provider-cloudflare/blob/8afde2993434ac929abdc6ce44bb21246ad1b1da/cloudflare/resource_cloudflare_authenticated_origin_pulls_certificate.go#L205

https://github.com/cloudflare/terraform-provider-cloudflare/blob/8afde2993434ac929abdc6ce44bb21246ad1b1da/cloudflare/resource_cloudflare_authenticated_origin_pulls.go#L158

**Comment by jacobbednarz** [comment]
Thanks for catching this one @dhaynespls 👏 Are you able to going to PR a fix for this one? If not, I can knock something together given the size of the fix.

**Comment by dhaynespls** [comment]
@jacobbednarz PR is incoming, though I'd appreciate if we'd be able to roll it into a point release sometime soon if there's other things that are ready to go

**Comment by jacobbednarz** [comment]
We've got a couple of [unreleased](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/CHANGELOG.md#unreleased) bug fixes and a new resource we can chuck into a new release if this is needed to be expedited.

**Comment by dhaynespls** [comment]
Up to y'all if it's not too much work! From my end, I can sit on this as a blocker until next week.

**Comment by jacobbednarz** [comment]
![](https://i.giphy.com/4WFEuV8V1BBxa8jU7M.gif)

**Comment by jacobbednarz** [comment]
v2.13.0 is in the pipeline now; should land in the registry within the next hour or so (the sync is on the Hashicorp side).
