### ISSUE TITLE
cloudflare_page_rule priority management

### ISSUE THREAD

**Issue by Jean-Mercier** [cloudflare/terraform-provider-cloudflare#867]
Hello,
(terraform 13.0 , cloudflare procider : 2.13.2)

On cloudflare_page_rule we try to manage priority but after apply it's alway propose change because when terraform set priority to 100 for exemple cloudflare recalculate thie priority in function of the number of page rules.

It's cause problem because it's very hard to maintain the page rules priority and when we insert a page rule we need to change all the other priority.

We need than when terraform set priority to 100 cloudflare maintain this priority on 100 and don't change it to be indempotent.

Thanks

**Comment by jacobbednarz** [comment]
Please see https://github.com/cloudflare/terraform-provider-cloudflare/issues/187#issuecomment-450987683 where I go into details on the cause and workaround for this one.

**Comment by Jean-Mercier** [comment]
Thanks but it's not a very pleasant way to manage our rule..

imagine i have 100 pages rule i want to insert one more i need to renumber all depend_on and all priority ...

is there a hope that cloudflare change their API to allow a fix priority ?

**Comment by jacobbednarz** [comment]
Being a customer myself using 115-120 of 125 page rules for at least 15 zones, I can definitely sympathise with you :)

I don't know of anything concrete to address it however the engineers and PMs are definitely well across the issues.

**Comment by Jean-Mercier** [comment]
Ok i found a better workarround for me

i change priority for make a priority +1 on each ressource
 like this i add the depend_on and the priority 

`resource "cloudflare_page_rule" "www_js" {
  zone_id  = data.cloudflare_zones.cf_zones.zones[0].id
  target   = "https://www${local.suffix}.${var.domain}/js/*"
  priority = cloudflare_page_rule.www_css.priority + 1
  status   = var.page_rules_conf.www_js.status

  actions {
    browser_cache_ttl = 60
    cache_level       = "basic"
    edge_cache_ttl    = 7200
    cache_ttl_by_status {
      codes = "300-599"
      ttl   = 0
    }
  }
}

resource "cloudflare_page_rule" "www_css" {
  zone_id  = data.cloudflare_zones.cf_zones.zones[0].id
  target   = "https://www${local.suffix}.${var.domain}/css/*"
  priority =  1
  status   = var.page_rules_conf.www_css.status

  actions {
    browser_cache_ttl = 60
    cache_level       = "basic"
    edge_cache_ttl    = 7200
    cache_ttl_by_status {
      codes = "300-599"
      ttl   = 0
    }
  }
}`

nb : i have different environnement so i get the starting priority from an env from a terraform remote state
