### ISSUE TITLE
Error 1002 while trying to create a TCP monitor

### ISSUE THREAD

**Issue by thecodeassassin** [cloudflare/terraform-provider-cloudflare#871]
### Terraform configuration files

```hcl
resource "cloudflare_load_balancer_monitor" "tcp_monitor" {
  type = "tcp"
  method = "connection_established"
  timeout = 7
  interval = 60
  retries = 5
  description = "example tcp load balancer"
}
```

### Debug output

https://gist.github.com/thecodeassassin/0aa038f39e96562046ab22f22a6eb83f

### Expected behavior

Monitor should have been created

### Actual behavior

```json
Error: error creating load balancer monitor: error from makeRequest: HTTP status 400: content "{\n  \"result\": null,\n  \"success\": false,\n  \"errors\": [\n    {\n      \"code\": 1002,\n      \"message\": \"interval is not in range [0, 0]: validation failed\"\n    }\n  ],\n  \"messages\": []\n}\n"
 ```

### Steps to reproduce

1. Make a clean TF file like this:

```hcl
provider "cloudflare" {
  email   = ""
  api_key = ""
}


resource "cloudflare_load_balancer_monitor" "tcp_monitor" {
  type = "tcp"
  method = "connection_established"
  timeout = 7
  interval = 60
  retries = 5
  description = "example tcp load balancer"
}
```

^^^ This comes from the documentation here => https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/load_balancer_monitor

terraform init
terraform plan
terraform apply

**Comment by jacobbednarz** [comment]
@thecodeassassin Are you able to provide a full reproduction test case as well as a full `TF_LOG=DEBUG` output? The resource and reproduction case you've provided don't match up. One is for `cloudflare_load_balancer_monitor` but the gist is for a failed spectrum application.

**Comment by thecodeassassin** [comment]
@jacobbednarz I updated the gist, these are logs from a clean terraform file as described above. All I did was copy paste the example and I was able to reproduce the issue.

**Comment by jacobbednarz** [comment]
Looking at that gist, the API response seems to erroneous as the validation field is looking for a range of 0,0 despite the [API documentation allowing integers](https://api.cloudflare.com/#load-balancer-monitors-create-monitor). Would you mind opening a support ticket and posting the # back here to track it?

**Comment by thecodeassassin** [comment]
@jacobbednarz the ticket number is  #2029359.

**Comment by thecodeassassin** [comment]
@jacobbednarz 

The bug is fixed when you specify "account_id" in the provider config.

Also `port` is required but it's not mentioned in the docs at all.

**Comment by jacobbednarz** [comment]
> The bug is fixed when you specify "account_id" in the provider config.

Oh, that is very surprising! The [`userBase`](https://github.com/cloudflare/cloudflare-go/blob/e60da8b667c90310431af0ba6686443476df48c8/cloudflare.go#L335-L340) method is responsible for this one and handles it behind the scenes if the account ID is defined.

> Also port is required but it's not mentioned in the docs at all.

Do you mean the Cloudflare API docs? Or the Terraform resource docs? If it's the latter, you're welcome to raise a PR to address it.

**Comment by thecodeassassin** [comment]
> > The bug is fixed when you specify "account_id" in the provider config.
> 
> Oh, that is very surprising! The [`userBase`](https://github.com/cloudflare/cloudflare-go/blob/e60da8b667c90310431af0ba6686443476df48c8/cloudflare.go#L335-L340) method is responsible for this one and handles it behind the scenes if the account ID is defined (which is news to me as well!).
> 
> > Also port is required but it's not mentioned in the docs at all.
> 
> Do you mean the Cloudflare API docs? Or the Terraform resource docs? If it's the latter, you're welcome to raise a PR to address it.

The Terraform resource docs, I'll make a PR to address it. 

The CF docs:

```
Port number to connect to for the health check. Required for TCP checks. HTTP and HTTPS checks should only define the port when using a non-standard port (HTTP: default 80, HTTPS: default 443).
```

**Comment by jacobbednarz** [comment]
@thecodeassassin are you still interested in putting up a PR for this one?

**Comment by thecodeassassin** [comment]
@jacobbednarz I opened a PR to address this

**Comment by Nmishin** [comment]
For anyone who finds this issue in the future:
This is strange, but this error also can be produced if you don't have a Load Balancer feature in your account subscription.

**Comment by jerem991** [comment]
Had this error message when trying to create a Load Balancer related resources, setting the optional `account_id` on these resources fixed the error.
```
Note:
When creating a monitor, you have to pass `account_id `to the provider configuration in order to create account level resources. Otherwise, by default, it will be a user level resource.
```
