### ISSUE TITLE
Expose cloudflare_record as data source

### ISSUE THREAD

**Issue by gmile** [cloudflare/terraform-provider-cloudflare#874]
### Current Terraform version

0.13.5

### Description

Expose `cloudflare_record` as a `data` source.

### Use-cases

I am working on a piece of infrastructure that shares DNS zone with a larger infra. The DNS table contains, among other records, an SPF TXT record.

My piece of infra, all described in terraform, needs to have its own value added to this pre-existing SPF TXT record. Ideally, I'd like to be able to read existing SPF TXT record, push my value to the list of mechanisms, then update the DNS record.

### Potential Terraform configuration

```terraform
data "cloudflare_record" "spf" {
  filter {
    name        = "mydomain.com"
    lookup_type = "contains"
    match       = "^v=spf1"
  }
}

resource "cloudflare_record" "spf" {
  name    = "mydomain.com"
  value   = custom_put(data.cloudflare_record.spf.0.value, var.extra_value)
  type    = "TXT"
  ttl     = 1
  proxied = false
}
```

(I am using to `custom_put` function here for brevity; it's actual implementation is out of scope of current request)

### References

...

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jacobbednarz** [comment]
Being able to lookup a record isn't really usable by ID and may introduce a circular dependency. Generally, to use data sources like this there is some sort of filtering mechanism (name, type, etc) which returns an enumerable set to reference. 

If you already have these records in Terraform, is there a reason why this couldn't be an [attribute](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/record#attributes-reference) on the resource you intend to use in other resources?

**Comment by gmile** [comment]
> Being able to lookup a record isn't really usable by ID and may introduce a circular dependency. Generally, to use data sources like this there is some sort of filtering mechanism (name, type, etc) which returns an enumerable set to reference.

@jacobbednarz That's a valid point. I've updated the "Potential Terraform configuration" to use filtering instead of a static ID. Thanks!

> If you already have these records in Terraform

To clarify, I do not have the larger infra, and the DNS records in particular, written down as Terraform configs. The project I am working on is a set o TF configs isolated from the rest of infra (which remains to be managed manually). My project needs to register itself on the DNS table that belongs to a larger infra.

> is there a reason why this couldn't be an attribute on the resource you intend to use in other resources?

I've never used `data` attributes, and I am not sure I am following the question. Can you clarify, possibly with example, what `data` attribute is used for, and how it could be applied for the case described above?

What I am trying to do, is to go from this:

```
v=spf1 include:abc.com -all
```

To this:

```
v=spf1 include:abc.com include:xyz.com -all
```

Without the need of copy-pasting existing SPF value in it's entirety to my TF values.

**Comment by jacobbednarz** [comment]
Resource attributes are properties of a resource which are exported and available for reference in other resources. You can check out the full documentation at https://www.terraform.io/docs/configuration/expressions.html#references-to-resource-attributes. There is an example on the documentation page, however the gist is this.

```hcl
resource "cloudflare_record" "mail_server" {
  name    = "mail.example.com"
  value   = "203.0.113.1"
  type    = "MX"
  ttl     = 60
  proxied = "false"
}

resource "cloudflare_record" "spf" {
  name    = "@"
  type    = "TXT"
  value  = "v=spf1 include:abc.com include:${cloudflare_record.mail_server.value} -all"
  ttl     = 60
  proxied = "false"
}
```

In the above, we are creating two `cloudflare_record` resources, the latter references the value from the former in its own value. This does require the Terraform resources to be accessible to one another though.

As for your example Terraform configuration, let's stick to what is available through the [API](https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records) to avoid filtering on the client end. This would boil down to things like `name`, `content`, `type` and `proxied` to be filters without any regexes.

**Comment by jacobbednarz** [comment]
Closing this due to lack of information and going stale. Happy to revisit should we wish to continue this conversation with another use case.
