### ISSUE TITLE
Expose cloudflare_ip_list as data source

### ISSUE THREAD

**Issue by ngnix** [cloudflare/terraform-provider-cloudflare#877]
### Current Terraform version
Terraform v0.13.3
+ provider registry.terraform.io/cloudflare/cloudflare v2.12.0

I want to show a somewhat illogical behavior regarding ip-list.
The best terraform practices suggest splitting state files by logical purpose and store state files in separated directories.
This approach allows you to reduce the area of infrastructure management and reduce the number of calls to the provider.
When using the cloudflare provider, it seems logical to use this approach to splitting state files:

+ account level ( state file )
    * zone_one level ( state file )
    * zone_two level ( state file )
    * zone_three level ( state file )

But some cloudflare object located at account level need to be used at zone level. 
For example it's cloudflare_ip_list  located at  account level. We need use cloudflare_ip_list  inside cloudflare_filter, but cloudflare_filter it's zone level object located inside another state file. In such a situation, we must use cloudflare_ip_list at the zone level. This makes it harder to manage cloudflare_ip_list, since most of our ip-lists are the same for all zones and we cannot reuse existing ip-list. 

The way out of this situation is to add data source cloudflare_ip_list with text filter (like aws [vpc](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpc#filter)).
```terraform
data "cloudflare_ip_list" "example" {
 filter {
        name = var.ip-list-name
   }
}
```
This approach would allow reuse of existing ip-lists without the import procedure.
You can improve this mechanism by adding a regular expression filter (by ip-lists name field) and return many ip-lists names as list/map:
```terraform
data "cloudflare_ip_list" "list-of-ip-lists" {
 filter {
         regexp = "whitelist_*"
   }
}
```
Thanks.

**Comment by jacobbednarz** [comment]
If I understand your use case, you don't actually need a data source for this as the account level IP List is already available to zone level firewall filters using a variable in the expression itself. 

Check out the documentation at https://developers.cloudflare.com/firewall/cf-firewall-language/values#rules-lists and let me know if this solves your intended use case.

**Comment by ngnix** [comment]
Hello, @jacobbednarz !
Yes, it's works correctly.
Thanks for your help!
