### ISSUE TITLE
Terraform resource for uploading Access Mutual TLS Root Certificates

### ISSUE THREAD

**Issue by jonathanjuursema** [cloudflare/terraform-provider-cloudflare#878]
### Current Terraform version

`0.12.29` at the time of writing, but we're going to upgrade to `0.13.x` as soon as we can. :)

### Description

As far as I can tell (and please do tell me if I've missed something) there is no support for uploading Mutual TLS Root Certificates even though there seem to be [API endpoint](https://api.cloudflare.com/#zone-level-access-mutual-tls-authentication-properties) for doing so.

Are there plans for supporting a `cloudflare_access_mutual_tls_root_certificate` resource? Or a reason I've overlooked for why this would be hard to achieve?

### Use-cases

I'm developing on an in-house deployment pipeline where internal teams can deploy infrastructure (mainly AWS, Cloudflare) using off-the-shelve "modules" we developed. These modules consist mainly of CloudFormation, Terraform and Kubernetes templates.

We already have a "module" that helps teams to deploy most of their Access configuration on Cloudflare. However, we have several customers that require us to support Mutual TLS. Right now, uploading Mututal TLS Root Certificates (for use in conjunction with `cloudflare_access_policy` resources) is a manual action in the Cloudflare dashboard that we would love for our teams to be able to do themselves. (Teams have read-only permission in the Cloudflare dashboard, and are supposed to deploy all their infrastructure via this pipeline.)

### Potential Terraform configuration

Something like this would do the job just fine for us:

```hcl
resource "cloudflare_access_mutual_tls_root_certificate" "some_certificate" {
  zone_id              = "9a7806061c88ada191ed06f989cc3dac"
  name                 = "Some mTLS Root Certificate"
  certificate          = "-----BEGIN CERTIFICATE-----\nMIIGAjCCA+qgAwIBAgIJAI7kymlF7CWT...N4RI7KKB7nikiuUf8vhULKy5IX10\nDrUtmu/B\n-----END CERTIFICATE-----"
  associated_hostnames = [
    "mtls.example.com"
  ]
}
```

### References

I've tried looking for similar feature requests but couldn't find any. My apologies if I overlooked some.

Cloudflare API: https://api.cloudflare.com/#zone-level-access-mutual-tls-authentication-properties

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
You're correct, there isn't currently support in either `coudflare-go` or the provider for this. You can configure the Accesss group (https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_group#certificate) however that isn't the certificate itself.

Best guess as to why this hasn't already got support is that no one has wanted it enough yet to either start adding support or raise a feature request for it 😄 I'm 👍 to adding it. This will first need to be added to `cloudflare-go` and then the provider. Would you care to take a pass at this one?

**Comment by jonathanjuursema** [comment]
I've taken the liberty to open an issue there:
- https://github.com/cloudflare/cloudflare-go/issues/559

I'd love to make a PR but I'm currently familiar with neither Go nor Terraform providers. I might try picking this up in my free time but for now I'll have to resort to opening feature requests. :(

**Comment by Justin-Holmes** [comment]
I'll create a PR for this! I'm hoping to have something by tomorrow.

**Comment by jacobbednarz** [comment]
awesome, thanks @Justin-Holmes :) i've just cut a release of `cloudflare-go` which includes the support there and should be merged into here in the coming hours.

**Comment by aviskarkc10** [comment]
@jacobbednarz Kinda stuck on this issue and didn't really know where to ask. What are the api token permissions I need to set in order to use this resource `cloudflare_access_mutual_tls_certificate`?

I get a `403: Unauthenticated Error` when trying this:

```
resource "cloudflare_access_mutual_tls_certificate" "<name>" {
  zone_id              = <zone_id>
  name                 = "Mutual TLS Certificate"
  certificate          = <cert>
  associated_hostnames = [<host_name>]
}
```

My token permissions:

![image](https://user-images.githubusercontent.com/13309631/153247808-b7f19972-b0a6-489c-a461-79db642e1528.png)
