### ISSUE TITLE
Load Balancer Session Affinity TTL

### ISSUE THREAD

**Issue by stefanstrydom** [cloudflare/terraform-provider-cloudflare#881]
### Current Terraform version
N/A

### Description

Hi guys, the provider doesnt seem to support adding the Session affinity TTL when setting the load balancer persistence to "cookie" mode. This is kind of critical to the functionality.  I suppose to add the drain duration would also be useful as I see its not added.  

Looking at the API docs, it does look like it is possible!
https://api.cloudflare.com/#load-balancers-create-load-balancer

I have no clue how to add the functionality into the provider, so hoping somebody can help us out!

### Use-cases
Ability to control how long sessions are persistent to a specific Origin.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
Seems reasonable. This will need to be added upstream in `cloudflare-go` before the Terraform provider can configure it.

**Comment by jacobbednarz** [comment]
Actually, looks we're already good to go so no need to wait for it.
