### ISSUE TITLE
Custom Cache Keys always responding with changes

### ISSUE THREAD

**Issue by dungtong** [cloudflare/terraform-provider-cloudflare#890]
### Terraform version
Terraform v0.13.5

### Affected resource(s)
+ provider registry.terraform.io/cloudflare/cloudflare v2.13.2

- cloudflare_page_rule

### Terraform configuration files

```hcl
resource "cloudflare_page_rule" "page_rule_test" {
  zone_id = var.cloudflare_zone_id

  target = "*${var.cloudflare_zone}/test*"

  priority = 70
  status = "active"
  actions {
    cache_key_fields {
      header {}
      cookie {
        include = [
          "test.anothertest",
          "test.regiontest",
          "test.devicetest",
          "test.testthis",
          "test.hello",
          "test.segmenttest",
          "test.usertype"]
      }
      query_string {}
      user {}
      host {}
    }
  }
}

```

### Debug output
Can be provided when requested as scrubbing is needed

### Panic output
N/A

### Expected behavior
Terraform apply will initially create the resource
Succeeding Terraform plan should show no change

### Actual behavior

Terraform plan is showing that there are changes to cache key fields.
![image](https://user-images.githubusercontent.com/70619002/101731579-efe14c00-3b0f-11eb-9a68-242d6348bf67.png)

### Steps to reproduce
Execute `terraform plan` - Should show that 1 resource will be added
Execute `terraform apply` - This will create the resource

Re-Execute `terraform plan` - Will now show that 1 resource will be changed
Re-Execute `terraform apply` - Will show that 1 resource was changed

### Important factoids
N/A

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
I've managed to replicate this using the following test case.

```hcl
terraform {
  required_providers {
    cloudflare = {
      source = "cloudflare/cloudflare"
      version = "2.17.0"
    }
  }
}

provider "cloudflare" {
  version = "2.17.0"
  email   = var.cloudflare_email
  api_key = var.cloudflare_api_key
}

variable "cloudflare_email" {}
variable "cloudflare_api_key" {}
variable "cloudflare_zone_id" {}
variable "cloudflare_zone" {}

resource "cloudflare_page_rule" "example" {
  zone_id = var.cloudflare_zone_id
  target = "*${var.cloudflare_zone}/test*"
  priority = 1
  status = "active"

  actions {
    cache_key_fields {
      header {}
      cookie {
        include = [
          "test.anothertest",
          "test.regiontest",
          "test.devicetest",
          "test.testthis",
          "test.hello",
          "test.segmenttest",
          "test.usertype"
        ]
      }
      query_string {}
      user {}
      host {}
    }
  }
}
```

Digging into the HTTP request/responses show that the API isn't returning these in the same order we are sending them which is throwing out the ordered nature of `TypeList`. Internally, we can swap this to `TypeSet` and it becomes an unordered list instead which prevents the flapping of the values. I'll take a pass at changing this for all the cache key fields as I suspect it will be the same for all.
