### ISSUE TITLE
data "cloudflare_zones" does not work without name or if name is just .com 

### ISSUE THREAD

**Issue by vital4ik** [cloudflare/terraform-provider-cloudflare#906]
clouflare dasource does not work as expected when name is omitted or short like .com or com. unable to pull all active zones in the account

### Terraform version

0.14.3
### Affected resource(s)
datasource  cloudflare_zones

### Expected behavior
Terraform pulls all active zones in the account
note: this works if i put example.com or test.com, I have test1, test2, test3 and example1, example2, example3.
if i put name ="test" it pulls all test zones, if i put name "example" it pulls all example zones
however if i comment the name out or put ".com" or "com" or "*", i get the error below

### Actual behavior

Error: error listing Zone: error from makeRequest: HTTP status 403: Actor 'com.cloudflare.api.token.yourtokenhere' requires permission 'com.cloudflare.api.account.zone.list' to list zones

### Steps to reproduce
in the datasource change name to "com"

### Important factoids
the token used has the following permissions plus all zones in the account permission
![image](https://user-images.githubusercontent.com/7430707/103801982-78beab00-501c-11eb-887d-339e74f56dfc.png)
![image](https://user-images.githubusercontent.com/7430707/103802091-a277d200-501c-11eb-89a1-ab5bd46c6980.png)

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
What happens if you try with an API key, not token? I suspect this is an issue with permissions not the provider.

**Comment by vital4ik** [comment]
Hi Jacob, looks like its not a permissions issue as it worked if i put full domain name but...
actually i think i figured it out, if i comment out lookup type and just leave 
data "cloudflare_zones" "zoneinfo" {
  filter {
    status = "active"
    paused = false
  }
}

it works. 
I think a slight  update the documentation that if you want all zones, just remove the name and lookup_type would be helpful

**Comment by jacobbednarz** [comment]
Depending on what attributes you pass in, it [changes the URL used](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/data_source_zones.go#L79-L88) which in turn, can change the permissions required. Using an API key will verify whether or not it's a token permission issue on either the setup or the service end.

> I think a slight update the documentation that if you want all zones, just remove the name and lookup_type would be helpful

I'm hesitant to do this at the moment as providing `com` or `.com` works with an API key; we have a [test](https://github.com/cloudflare/terraform-provider-cloudflare/blob/d8fe659584c76d896bcf95dcf3e1f2ffbf5cb5b0/cloudflare/data_source_zones_test.go#L107) for it.
