### ISSUE TITLE
cloudflare_api_token does not support nested resources

### ISSUE THREAD

**Issue by jstachowiak** [cloudflare/terraform-provider-cloudflare#908]
### Terraform version

v0.14.3

### Affected resource(s)

- cloudflare_api_token

### Terraform configuration files

```terraform
data "cloudflare_api_token_permission_groups" "all" {}

resource "cloudflare_api_token" "example" {
  name = "example"

  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["Zone Write"],
      data.cloudflare_api_token_permission_groups.all.permissions["DNS Write"]
    ]

    resources = {
      "com.cloudflare.api.account.${var.account_id}" = {
        "com.cloudflare.api.account.zone.*" = "*"
      }
    }
  }
}
```

### Expected behavior

Zone permissions should be applied to all zones from the account.

### Actual behavior

```
Inappropriate value for attribute "resources": element "com.cloudflare.api.account.XXX": string required.
```

### Steps to reproduce

1. `terraform apply -auto-approve`

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
Moving from a bug as this is newer functionality that wasn't present in the initial rollout. 

Support will need to be present in cloudflare/cloudflare-go first.

**Comment by OJFord** [comment]
Would this in theory also then allow granting permission to write only a specific DNS record, or record type?
```
  policy {
    permission_groups = [
      data.cloudflare_api_token_permission_groups.all.permissions["DNS Write"],
    ]
    resources = {
      "com.cloudflare.api.account.zone.${var.zone_id}" = "*"
    }
  }
  ```
  
 I believe `"*"` is presently the only valid value? Which I found a bit confusing itself looking at the docs trying to understand how to use this; the terraform docs are actually more detailed than the API docs, but still don't really explain - just all the examples are wildcards.
 
 This would be nice for example for configuring the [caddy plugin](https://github.com/caddy-dns/cloudflare) - allowing it _only_ to write  to the `_acme-challenge` TXT record.

**Comment by hussain-yekta** [comment]
Hi all
I have upgraded to terraform version 1.5.4 and cloudflare version 4.10.0 and tried to create resource "cloudflare_api_token" (exactly the same way you see here and in documentations, but got the following warning and couldn't find any solution.
 is there any thoughts on this?
 Warning: Deprecated attribute
│ 
│   on cloudflare.tf line 49, in resource "cloudflare_api_token" "this":
│   49:       data.cloudflare_api_token_permission_groups.all.permissions["DNS Write"],
│ 
│ The attribute "permissions" is deprecated. Refer to the provider documentation for details.
│ 
│ (and one more similar warning elsewhere)

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by jacobbednarz** [comment]
This issue has been closed as we are now tracking this internally with service teams directly. If you would like an update or to be notified when/if the product ships with this change, please reach out to Cloudflare Support or your account team who can watch the internal feature request for you.

**Comment by elopsod** [comment]
@jstachowiak hi
this works for me 
```
resource "cloudflare_api_token" "token" {
  name = "exporter"
  policy {
    permission_groups = local.permission_groups
    resources = {
      "com.cloudflare.api.account.11111111111111111111111111111111" : jsonencode({
        "com.cloudflare.api.account.zone.*" : "*"
      })
    }
  }
}
```

**Comment by OJFord** [comment]
That's exactly what OP had, so I guess that secret internal issue is resolved and this works now? :shrug:
