### ISSUE TITLE
cloudflare_record resource tries to use hashicorp/cloudflare provider

### ISSUE THREAD

**Issue by purvesta** [cloudflare/terraform-provider-cloudflare#920]
### Terraform version
Terraform v0.14.1
+ provider registry.terraform.io/cloudflare/cloudflare v2.17.0
+ provider registry.terraform.io/hashicorp/aws v3.9.0

### Affected resource(s)
cloudflare_record

### Expected behavior
It should have attempted to create the cloudflare record.

### Actual behavior
```
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/cloudflare versions matching "2.17.0"...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v3.9.0...
- Installed hashicorp/aws v3.9.0 (signed by HashiCorp)

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/cloudflare: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/cloudflare
```
### Steps to reproduce
1. Add cloudflare as a provider
2. Add a cloudflare_record block to create a record
3. Run `terraform init`

**Comment by purvesta** [comment]
It seems after further testing that by simply having the provider "cloudflare" block, I run into this issue.

**Comment by jacobbednarz** [comment]
This is a side effect of upgrading to Terraform 0.13, not a specific provider. Check out the documentation at https://www.terraform.io/upgrade-guides/0-13.html#explicit-provider-source-locations for the change and what you need to do in order to resolve it.
