### ISSUE TITLE
terraform import of zone specific access policy does not work

### ISSUE THREAD

**Issue by iserko** [cloudflare/terraform-provider-cloudflare#929]
### Terraform version

0.13.5

Cloudflare provider version 2.14.0

### Affected resource(s)

- cloudflare_access_policy

### Terraform configuration files

```hcl
resource "cloudflare_access_policy" "allow_policy" {
  application_id = cloudflare_access_application.my_app.id
  decision       = "allow"
  zone_id        = var.cf_zone_id
  name           = "Name of policy"
  precedence     = "1"

  include {
    group = [
      cloudflare_access_group.my_group.id
    ]
  }
}
```

### Debug output

https://gist.github.com/iserko/f45ea0153f2c913a8cd4bd68ff6dce0b

### Panic output

No panic

### Expected behavior

```
terraform import cloudflare_access_policy.allow_policy ZONE_ID/APPLICATION_ID/POLICY_ID
```

should work as described in https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_policy#import

> Access Policies can be imported using a composite ID formed of zone ID, application ID and policy ID.

### Actual behavior

Terraform provider attempts to import `ACCOUNT_ID/APPLICATION_ID/POLICY_ID` and fails doing so as that POLICY_ID does not exist in the account, only in the zone.

### Steps to reproduce

1. create an access policy in a zone
2. attempt to import it

### Important factoids

n/a

### References

n/a

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by mdolinin** [comment]
Was on my way to open similar bug. That doc needs to be fixed, import works for me only with `ACCOUNT_ID/APPLICATION_ID/POLICY_ID`. But my policy was created via UI few months ago.

**Comment by jacobbednarz** [comment]
Looks to be left over from when we attempted to move to account only access policies. To fix this, we'll need to update the identifier to include "zone" or "account". 

@iserko are you interested in submitting a PR for this?
