### ISSUE TITLE
Read provider credentails from file

### ISSUE THREAD

**Issue by markwellis** [cloudflare/terraform-provider-cloudflare#938]
### Current Terraform version

Terraform v0.14.5

### Description

Load credentials from a file

### Use-cases

I don't want to set credentials in the .tf files, but I don't want to have the credentials in my `env` all the time either for security reasons.

Would be great if these could be read from a file as well as env vars/hardcoded.

I currently use this alias to emulate this feature, but it's a problem when using scripts as i have to `export -f terraform` to have it work

```bash
terraform(){
    source ~/.cloudflare_keys
    command terraform $@
}
```

and my ~/.cloudflare_keys looks like this
```
export CLOUDFLARE_EMAIL="my@email"    
export CLOUDFLARE_TOKEN="MYCFTOKEN"    
export CLOUDFLARE_ORG_ID="MYCFORGID"    
    
#for TF provider version 2    
export CLOUDFLARE_API_KEY="MYCFTOKEN"    
export CLOUDFLARE_ACCOUNT_ID="MYCFORGID"
```

### Potential Terraform configuration

```hcl
provider "cloudflare" {
#keys are read from $ENV or ~/.cloudflare_keys (or somewhere)
}

```

### References

the aws provider works like this, using $AWS_PROFILE to read the right profile

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
For security reasons, I'm a pretty strong no to this one unless we have a really good use case. Instead, I'd recommend using something like https://github.com/jacobbednarz/cf-vault locally.

**Comment by jacobbednarz** [comment]
If you want a Terraform specific fix, you can also look at using a `.tfvars` (https://www.terraform.io/docs/language/values/variables.html)

**Comment by markwellis** [comment]
> For security reasons, I'm a pretty strong no to this one unless we have a really good use case. Instead, I'd recommend using something like https://github.com/jacobbednarz/cf-vault locally.

How is a file more of a security risk than having them in them as environment variables? Why is it a risk to have CF token in a file, but not aws creds?

> If you want a Terraform specific fix, you can also look at using a `.tfvars` (https://www.terraform.io/docs/language/values/variables.html)

No because I don't want the credentials in the tf directory.

**Comment by jacobbednarz** [comment]
> How is a file more of a security risk than having them in them as environment variables? 

It comes down to things like:

- files are harder to secure from other users. even well permissioned files can be inadvertently accessed by users that shouldn't be able to. 
- environment variables can be scoped to the context in which you needing to access them. I.e a single script run or a sub shell/process. there are also some hardening options in 
- you also run the risk of checking those credentials into source control by accident. 

There are other benefits however I won't expand on them all here -- you're welcome to investigate these if you're interested to find out more. It is up to your personal threat model but it isn't something I'm open to adding without a good reason and as it stands, this isn't it when there are better approaches available. 

> Why is it a risk to have CF token in a file, but not aws creds?

It's not a matter of which tool is storing credentials in files, it's about the principle itself. And yes, if you're storing your AWS credentials in a file it is definitely less than ideal. It's also the reason tools like aws-vault (which cf-vault is modelled after) to secure the use/storage of credentials.
