### ISSUE TITLE
Unable to create MX records with priority 0

### ISSUE THREAD

**Issue by AlessioCasco** [cloudflare/terraform-provider-cloudflare#943]
Hi there,

It seems that the Cloudflare provider is not passing the priority value when set to 0 or omitted for MX records. 
If the value is >= 1 the apply works.

Probably the issue is on the API side where it should default to 0 if ommited as stated here: https://api.cloudflare.com/#dns-records-for-a-zone-create-dns-record

### Terraform version

Terraform v0.14.6
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0

### Affected resource(s)

- cloudflare_record

### Terraform configuration files
```hcl
resource "cloudflare_record" "mx" {
  zone_id  = var.zone_id
  name     = "example.com"
  value    = "example.com"
  priority = 0
  type     = "MX"
  proxied  = false
}
```
```hcl
resource "cloudflare_record" "mx" {
  zone_id  = var.zone_id
  name     = "example.com"
  value    = "example.com"
  type     = "MX"
  proxied  = false
}
```
### Debug output
https://gist.github.com/AlessioCasco/44221fc76c65d8ad6227bb93e51921c5

### Expected behaviour
The MX record should be created with priority 0

### Actual behaviour

```bash
Error: failed to create DNS record: error from makeRequest: HTTP status 400: content "{\"result\":null,\"success\":false,\"errors\":[{\"code\":1004,\"message\":\"DNS Validation Error\",\"error_chain\":[{\"code\":9100,\"message\":\"priority is a required field.\"}]}],\"messages\":[]}"
  on ../../modules/cloudflare/zone/main.tf line 98, in resource "cloudflare_record" "mx":
  98: resource "cloudflare_record" "mx" {
```

### Steps to reproduce

1. `terraform apply`

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
cloudflare/cloudflare-go#588 is addressing the underlying library so that should allow is to address this.

**Comment by tomelfring** [comment]
I'm was already able to create a "NULL MX" record through terraform using version 2.10.1 and terraform version 0.12.29 (I know, it's outdated, already updated, but it was the version used to create it :) ).

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ***** will be created
  + resource "cloudflare_record" "cloudflare_dns_record_dns-records_*****" {
      + created_on  = (known after apply)
      + hostname    = (known after apply)
      + id          = (known after apply)
      + metadata    = (known after apply)
      + modified_on = (known after apply)
      + name        = "@"
      + priority    = 0
      + proxiable   = (known after apply)
      + proxied     = false
      + ttl         = 1
      + type        = "MX"
      + value       = "."
      + zone_id     = "*****"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "tfplan"

Terraform operation done.
Terraform APPLY [*****]
*****: Creating...
*****: Creation complete after 3s [id=*****]
```
