### ISSUE TITLE
logpush job for firewall_event is not working.

### ISSUE THREAD

**Issue by renaudhager** [cloudflare/terraform-provider-cloudflare#946]
### Terraform version

```
tf_0.12.26 -v
Terraform v0.12.26
+ provider.aws v3.26.0
+ provider.cloudflare v2.17.0

Your version of Terraform is out of date! The latest version
is 0.14.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected resource(s)

```
cloudflare_logpush_job
```

### Terraform configuration files

```hcl
resource "cloudflare_logpush_ownership_challenge" "ownership_firewall_challenge" {
  count = var.enable_global_config ? 1 : 0

  zone_id          = data.cloudflare_zones.default.zones[0].id
  destination_conf = "s3://<redacted>-${var.environment}-os-cdn-firewall-logs?region=${var.region}"
}

data "aws_s3_bucket_object" "challenge_firewall_file" {
  count = var.enable_global_config ? 1 : 0

  bucket = "<redacted>-${var.environment}-os-cdn-firewall-logs"
  key    = cloudflare_logpush_ownership_challenge.ownership_firewall_challenge[0].ownership_challenge_filename
}

resource "cloudflare_logpush_job" "firewall_to_s3" {
  count = var.enable_global_config ? 1 : 0

  enabled             = var.enable_cloudflare_firewall_logpush_job
  zone_id             = data.cloudflare_zones.default.zones[0].id
  name                = "os-firewall-logs-to-s3"
  logpull_options     = var.cloudflare_firewall_logpush_options
  destination_conf    = "s3://<redacted>-${var.environment}-os-cdn-firewall-logs?region=${var.region}"
  ownership_challenge = data.aws_s3_bucket_object.challenge_firewall_file[0].body
  dataset             = "firewall_events"
}
```

### Expected behavior
This should create a working logpush job for firewall event. A job that pushes event to the bucket.

### Actual behavior
This actually create the logpush job, everything seems ok, but no event are pushed to S3.
This behaviour only happen when the dataset is set to `firewall_event`.

### Steps to reproduce

1. `terraform apply`

### Important factoids
I have open a ticket with cloudflare support (#2080952) about this.
Using a similar snippet I successfully created a logpush job for http_requests, which works perfectly fine.

According to the support the firewall_event dataset is in beta.
From Terraform point of view, when the dataset is firewall_event, everything is ok, but nothing is sent to S3.

When we look at the resource, it looks fine and similar to logpush job with dataset configured to http_requests:

```
# cloudflare_logpush_job.firewall_to_s3[0]:
resource "cloudflare_logpush_job" "firewall_to_s3" {
    dataset             = "firewall_events"
    destination_conf    = "s3://<redacted>-dev-os-cdn-firewall-logs?region=eu-west-1"
    enabled             = true
    id                  = "26606"
    logpull_options     = "fields=RayID,ClientIP,ClientRequestHost,ClientRequestPath,ClientRequestUserAgent&timestamps=rfc3339"
    name                = "os-firewall-logs-to-s3"
    ownership_challenge = "<redacted>"
    zone_id             = "<redacted>"
}
```

But when we query cloudflare API, we can see a difference between the 2 dataset http_requests and firewall_event:

```
{
      "id": 26559,
      "dataset": "http_requests",
      "logstream": true,
      "enabled": true,
      "name": "os-http-logs-to-s3",
      "logpull_options": "fields=RayID,ClientIP,ClientRequestHost,ClientRequestPath,ClientRequestUserAgent,EdgeStartTimestamp,WAFAction,WAFRuleID&timestamps=rfc3339",
      "destination_conf": "s3://<redacted>-os-cdn-http-logs?region=eu-west-1",
      "last_complete": "2021-02-09T17:17:10Z",
      "last_error": null,
      "error_message": null
    }
```

```
{
    "id": 26606,
    "dataset": "firewall_events",
    "enabled": true,
    "name": "os-firewall-logs-to-s3",
    "logpull_options": "fields=RayID,ClientIP,ClientRequestHost,ClientRequestPath,ClientRequestUserAgent&timestamps=rfc3339",
    "destination_conf": "s3://<redacted>-os-cdn-firewall-logs?region=eu-west-1",
    "last_complete": null,
    "last_error": null,
    "error_message": null
}
```

The logstream field is not set for the firewall_event, I guess the issue is more on the side of the cloudflare SDK but I thought it would be worth to open issue about since the firewall_event seems to be supported by the provider and it's mentionned in the documentation.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
> I guess the issue is more on the side of the cloudflare SDK

I'm not sure I follow. The response is generated by the Cloudflare API and the SDK only handles parsing it so the SDK shouldn't be at fault here if it is working for another similar request. Can you please provide the full `TF_LOG=DEBUG` output? I suspect the API isn't exposing this and it's an internal issue to be addressed.

**Comment by jacobbednarz** [comment]
closing due to lack of information follow up. if more information is available, we can revisit.
