### ISSUE TITLE
logpush_job failing on ownership_challenge

### ISSUE THREAD

**Issue by all0ysius** [cloudflare/terraform-provider-cloudflare#954]
### Terraform version
Terraform v0.13.2
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0
+ provider registry.terraform.io/hashicorp/google v3.56.0
+ provider registry.terraform.io/hashicorp/google-beta v3.56.0

Your version of Terraform is out of date! The latest version
is 0.14.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected resource(s)
- cloudflare_logpush_job

### Terraform configuration files

resource "cloudflare_logpush_ownership_challenge" "bstock_beta" {
  zone_id = lookup(data.cloudflare_zones.test.zones[0], "id")
  destination_conf = "gs://bstock-beta-cf-logs"
}

data "google_storage_bucket_object_content" "challenge_file" {
  name   = cloudflare_logpush_ownership_challenge.bstock_beta.ownership_challenge_filename
  bucket = "bstock-beta-cf-logs"
}

resource "cloudflare_logpush_job" "logpush_job" {
  enabled = true
  zone_id = lookup(data.cloudflare_zones.test.zones[0], "id")
  name = "B-Stock-beta-job"
  destination_conf = "gs://bstock-beta-cf-logs"
  ownership_challenge = data.google_storage_bucket_object_content.challenge_file.content
  dataset = "http_requests"
  }

output "cf_challenge" {
  value = data.google_storage_bucket_object_content.challenge_file.content
}

### Expected behavior
A logpush job should be created. I followed the documentation, except I am using Google Storage instead of AWS.

### Actual behavior

I run terraform plan and it gives me an error regarding the ownership challenge. 
2021/02/10 16:54:32 [INFO] backend/local: plan operation completed

Error: "ownership_challenge": required field is not set

  on logs.tf line 49, in resource "cloudflare_logpush_job" "logpush_job":
  49: resource "cloudflare_logpush_job" "logpush_job" {

I verified that the data.google_storage_bucket_object_content.challenge_file.content is valid by doing the following
I commented out the cloudflare_logpush_job resource. Only the ownership challenge and data statements were there. The data output looked good, you can see below.

resource "cloudflare_logpush_ownership_challenge" "bstock_beta" {
  zone_id = lookup(data.cloudflare_zones.test.zones[0], "id")
  destination_conf = "gs://bstock-beta-cf-logs"
}

data "google_storage_bucket_object_content" "challenge_file" {
  name   = cloudflare_logpush_ownership_challenge.bstock_beta.ownership_challenge_filename
  bucket = "bstock-beta-cf-logs"
}

output "cf_challenge" {
  value = data.google_storage_bucket_object_content.challenge_file.content
}

I can apply this and see the output

cf_challenge = eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4R0NNIiwidHlwIjoiSldUIn0..b-nwtmlKINjPtSBZ.yw3QA3MPK8rPyxmN4VoypyIF1fclKCnD-tjeFfu0X0iE5yEMR_n0n_JXhlOz-IOk5DqRqnAUhpRdrQeaABawJh9hOXcnsDAGJCREF21tsHNQ-62j3UAUOm-kLdOL4aoky36pyJP4XmBy2S5eaX5Buw9KfV1qp8yq3gr11CQSKfAG5yCMErLSxuSzVL0AqZUlMIqqkDk0I-49AKEGJFRuHq1hPFwxxwtkrZP6qRSg8yvjxiC4uahdQgi5_cFd_igO1nATGgqIPlOjlZNFnzn3FXpvGYuxrouFw7fDiCXFJl8z9Z0.baLj-zN3kblhvr3Tn7Fwxg

The file is created and is in the gs bucket.

If I uncomment the 'cloudflare_logpush_job' now and run terraform apply it works.

The issues is if I run all the ownership_challenge, google_storage_bucket_object_content and the cloudflare_logpush_job  in a new zone (create the zone from scratch and configure it with terraform) then I get the error about the ownership challenge. I get this error during 'terraform plan'. I would think it would say that the 'ownership_challenge' would be known after apply, but instead it errors out.

### Steps to reproduce
1. have a zone in cloudflare
2.  have a storage bucket in GCP
3. add the terraform configs I have above
4. run terrafom plan or apply

**Comment by jacobbednarz** [comment]
the resources themselves are correct however this looks to be an issue in Terraform itself as the dependency chain isn't being evaluated and showing as the `ownership_challenge` having an evaluated value.

i'll raise this with the Terraform team however in the mean time, you'll need to apply `cloudflare_logpush_ownership_challenge` on it's own and then the other two.

**Comment by vital4ik** [comment]
i was able to work around this issue by putting the challenge creation into a submodule
```terraform
module "logpushprep" {
  source = "./modules/logpushprep/"
  zoneid = var.zoneid
  logpush-schemas = var.logpush-schemas
  global_zonename = var.global_zonename
  gcp-project = var.gcp-project
}

data "google_storage_bucket_object_content" "challenge_data_logpush" {
  depends_on = [module.logpushprep]
  for_each = var.logpush-schemas
  bucket = lookup(module.logpushprep.buckets,each.key)
  name = lookup(module.logpushprep.challenge,each.key,"")
}
```
where above submodule produces outputs like this:
```terraform 
output "buckets" {
  value = {for k,v in google_storage_bucket.log-storage:  k => v.name}
}
output "challenge" {
  value = tomap({for k,v in cloudflare_logpush_ownership_challenge.ownership_challenge_logpush:  k => v.ownership_challenge_filename})
}```

**Comment by vital4ik** [comment]
submodule code, I am using it with GCP so its GCS related
```terraform
//creating separate 3 buckers for each log type
resource "google_storage_bucket" "log-storage" {
  for_each = var.logpush-schemas
  project       = var.gcp-project
  name          = "${replace(var.global_zonename,".","-")}-${each.key}"
  location      = "US"
  force_destroy = true
  lifecycle_rule {
    condition {
      age = 365
    }
    action {
      type = "SetStorageClass"
      storage_class = "COLDLINE"
    }
  }
}
//setting up iam for access to storage buckets
resource "google_project_iam_binding" "cf-storageadmin" {
  project                                = var.gcp-project
  role                                   = "roles/storage.objectAdmin"
  members = [
                                         "serviceAccount:logpush@cloudflare-data.iam.gserviceaccount.com",
  ]
}
data "google_iam_policy" "cf-storageadmin" {
  depends_on = [google_project_iam_binding.cf-storageadmin]
  binding {
    role = "roles/storage.objectAdmin"
    members = [
      "serviceAccount:logpush@cloudflare-data.iam.gserviceaccount.com",
    ]
  }
}
resource "google_storage_bucket_iam_policy" "add-cf-storage-admin" {
  for_each = var.logpush-schemas
  bucket = google_storage_bucket.log-storage[each.key].name
  policy_data = data.google_iam_policy.cf-storageadmin.policy_data
}
resource "cloudflare_logpush_ownership_challenge" "ownership_challenge_logpush" {
  depends_on = [google_storage_bucket_iam_policy.add-cf-storage-admin]
  for_each = var.logpush-schemas
  zone_id = var.zoneid
  destination_conf = "gs://${replace(var.global_zonename,".","-")}-${each.key}"
} ```

**Comment by jacobbednarz** [comment]
I've been playing with this in #1019 and it looks to be working now using Terraform 0.14.9 and 2.19.2. @all0ysius do you want to try again?

**Comment by vital4ik** [comment]
@jacobbednarz i tried few times yesterday, it is still not working for me. I can paste my code if required

**Comment by jacobbednarz** [comment]
Did you try with the latest version of Terraform?

**Comment by vital4ik** [comment]
yep, I am on latest versions of both TF and CF provider.

**Comment by vital4ik** [comment]
based on what i see, the original issue here was opened for GCS as well. did @jacobbednarz or @all0ysius get it to work with GCS bucket?
