### ISSUE TITLE
changing proxied true -> false stops working at v2.16

### ISSUE THREAD

**Issue by georgekaz** [cloudflare/terraform-provider-cloudflare#959]
Despite the terraform plan and apply indicating success, there is regression between v2.15 and 2.16 of the provider where when you change a `proxied` value on a `cloudflare_record` from `true` to `false`, it does not actually update in cloudflare. Changing from `false` to `true` does work, which indicates to me that false is being considered as a null value or suchlike rather than an explicit `false`.

I've tested this from 2.14 through to 2.18 and found it works fine until 2.15 but fails in 2.16-2.18.

**Comment by georgekaz** [comment]
I can't seen anything in this compare that relates to this issue, but it's definitely real for us.

https://github.com/cloudflare/terraform-provider-cloudflare/compare/v2.15.0...v2.16.0

**Comment by ricog** [comment]
I can confirm it is an issue in v2.18.0 on Terraform v0.14.6.

Using `TF_LOG=DEBUG` it is possible to see that the `proxied` property is missing in the PATCH request to Cloudflare and then TF reports:
```2021/02/17 14:40:10 [WARN] Provider "registry.terraform.io/cloudflare/cloudflare" produced an unexpected new value for cloudflare_record.record[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .proxied: was cty.False, but now cty.True```

**Comment by ricog** [comment]
Digging in, it was a change to the cloudflare/cloudflare-go library version.

https://github.com/cloudflare/terraform-provider-cloudflare/compare/v2.15.0...v2.16.0#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R6

This commit in that library appears to be the breaking change.

https://github.com/cloudflare/cloudflare-go/commit/03f3015baa9b4212d2ef8138a0e2c6a1ac306903

**Comment by georgekaz** [comment]
Thanks for confirming @ricog . We're still using TF 0.12.30 but it should be working.

**Comment by georgekaz** [comment]
Just looked at the cloudflare-go code and yes, it must be treating false as empty

**Comment by jacobbednarz** [comment]
this issue is being tracked at cloudflare/cloudflare-go#568 and once fixed will be automatically pulled into the next provider release.
