### ISSUE TITLE
image_resizing for cloudflare_zone_settings_override doesn't make changes

### ISSUE THREAD

**Issue by ChristophShyper** [cloudflare/terraform-provider-cloudflare#961]
### Terraform version

Terraform v0.14.5

### Affected resource(s)

`cloudflare_zone_settings_override`

### Terraform configuration files

```terraform
resource "cloudflare_zone_settings_override" "config_override" {
  zone_id = cloudflare_zone.this.id

  settings {
   (...)
   image_resizing  = "on"
   (...)
  }
}
```

### Debug output

```
Error: invalid zone setting "image_resizing" (value: ) found - cannot be set as it is read only
```

### Expected behavior

Image resizing option should be enabled.

### Actual behavior

Image resizing is still off.

### Steps to reproduce

1. Create zone with image resizing turned off
2. Add `cloudflare_zone_settings_override` to your terraform with current values
3. `terraform apply` works
4. Change `image_resizing` to `off`

We have Enterprise plan, so it's possible to set it.
Setting it manually in Cloudflare solves the error, but we want to control it from code.

### References

- https://github.com/cloudflare/terraform-provider-cloudflare/issues/808

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by olenm** [comment]
On a new hosted-zone and on attempting to enable the "override" settings for the first time - I have image_resizing off in TF (and it is certainly off in the web-ui) and I too, get the read-only error.

**Comment by alxsbn** [comment]
I have the same behavior with webp and http2
```
Cloudflare_zone_settings_override.settings: Creating...

Error: invalid zone setting "http2" (value: off) found - cannot be set as it is read only
```

TF try to destroy then create a new zone settings override but some parameters seems blocked as they're flagged as 'read only'. I also have the same error with webp.

**Comment by vital4ik** [comment]
I get this too, works on some zones but not others with different values

**Comment by jacobbednarz** [comment]
i've found an internal reference stating this has been addressed. @alxsbn can you please confirm if you're still seeing the issue?

**Comment by kawikao** [comment]
I have this problem too. I'm on the free plan and I notice some of the read-only settings that error are only available on the Cloudflare enterprise plan or for a service I don't have enabled.

**Comment by kawikao** [comment]
I upgraded my Cloudflare zone to Enterprise and a whole slew of read-only settings went away except paid services like Image Resizing, DDOS and AST.

This is a definite bug. The provider should not be trying to update a Cloudflare service that the zone is not subscribed too. The request will be blocked.

**Comment by jacobbednarz** [comment]
No @kawikao, yours is not a bug. The resource is intended as an **override** to the defaults and if you do not have entitlements, the resource is not aware of it. It is not a resource intended to manage all resources irrespective of the entitlements.

**Comment by kawikao** [comment]
@jacobbednarz Thank you for replying. image_resizing is set to "off" in the terraform state. When I try to set the value to `null` or delete the resource entirely, I get the read only error. If it's not a bug then something else is wrong. If you have any tips to fix the issue, I'd appreciate it. Cheers.

**Comment by kawikao** [comment]
From the docs.
```
Provides a resource which customizes Cloudflare zone settings. Note that after destroying this resource Zone Settings will be reset to their initial values.
```

I took it to mean, the provider tries to reset the initial values at Cloudflare. Since, many settings are read-only, it doesn't appear to even try to reset the values and aborts destroying the resource. It's a catch-22. I just `terraform rm` and won't use the resource until this issue is resolved.
