### ISSUE TITLE
Expose "Enable automatic cloudflared authentication" setting to Terraform

### ISSUE THREAD

**Issue by ideologysec** [cloudflare/terraform-provider-cloudflare#963]
### Current Terraform version
```bash
$ terraform --version
Terraform v0.14.7
+ provider registry.terraform.io/cloudflare/cloudflare v2.18.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Description

I'd like to be able to toggle the "Enable automatic cloudflared authentication" switch via Terraform for created applications; when creating several dozen apps, being able to flip this switch programmatically would be great.

### Use-cases
The end goal is, as mentioned, being able to set the state of cloudflared automatic authentication for multiple Cloudflare Access applications at the same time; we use lots and lots of hosts and toggling this manually (or writing a bash script to do it programmatically after the fact) is both time-consuming and doesn't capture the state of cloudflare infrastructure in code. 
-->

### Potential Terraform configuration
here's a snippet for the code portion of the provider:
```go
"automatic_cloudflared_authentication": {
    Type:     schema.TypeBool,
    Optional: true,
    Default:  false,
}
```
and how it might look in terraform:
```hcl
resource "cloudflare_access_application" "example_app" {
  zone_id          = var.cloudflare_zone_id
  name             = "Example SSH App"
  domain           = join(".", ["example", var.cloudflare_domain])
  session_duration = "6h"
  auto_redirect_to_identity = true
  automatic_cloudflared_authentication = true
}
```
-->

### References
I have not found any other issues for this, but I have searched.

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by ideologysec** [comment]
The v4 API isn't documented as supporting setting this property, though it does return it if created; it's called `skip_interstitial` in the json blob returned when curling for Access apps.

**Comment by jacobbednarz** [comment]
This will need to be added to `cloudflare-go` and the public documentation before we add it to Terraform.

**Comment by ideologysec** [comment]
One additional issue is that if you manually flip the switch in the Cloudflare access dashboard, Terraform believes that the app is gone and tries to recreate it, which fails because the app already exists. 👎

**Comment by jacobbednarz** [comment]
I'll have to confirm however Access Policies operate in a similar fashion where updating via the dashboard doesn't perform an in place update but a new resource that looks very similar. My advice is to manage your resources in one way and don't jump between UI and managing as code because it can (and will!) introduce headaches for you.

**Comment by jacobbednarz** [comment]
@Justin-Holmes is this something that is coming to a public API any time soon?

**Comment by Justin-Holmes** [comment]
Yep! This will be coming to the public API in the near future. We'll probably use `automatic_cloudflared_authentication ` over `skip_interstitial` so the name is consistent with the UI.

**Comment by jacobbednarz** [comment]
thanks! i'll keep an eye out and link this when it comes about.

**Comment by ideologysec** [comment]
Following up on this - has it been added to the upstream library or the terraform provider?

**Comment by Justin-Holmes** [comment]
Yes, this is available as the `skip_interstitial` field: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_application#skip_interstitial

@jacobbednarz we can close this ticket if you'd like!
