### ISSUE TITLE
custom page rules query_string option "ignore" is not working

### ISSUE THREAD

**Issue by svesve** [cloudflare/terraform-provider-cloudflare#967]
### Terraform version
Terraform v0.13.6

### Affected resource(s)
cloudflare_page_rule

cloudflare v. 2.18.0

### Terraform configuration files
```
resource "cloudflare_page_rule" "page_rule" {
    zone_id = lookup(data.cloudflare_zones.cf_zone_id.zones[0], "id")
    target = "https://example.com"
    priority = 5
    status = "active"
    actions {
        cache_level = "cache_everything"
        cache_key_fields {
                cookie {}
                header {}
                host {
                    resolved = false
                }
                query_string {
                    ignore = true
                }
                user {
                    device_type = false
                    geo = true
                    lang = false
                }
        }
    }
}
```

### Expected behavior
Page rule must be created with "Ignore query string" option enabled

### Actual behavior
Page rule created with parameter - exclude = "*"
Ignore query string parameter is ignored

### Steps to reproduce
Create page rule within terraform with query_string ignore = true
Check page rule in CloudFlare web interface

### References
It seems that that ignore = true is not supported by api or this bug in terraform cloudflare module version 2.18.0
in 2.17.0 this bug is not reproduced

https://support.cloudflare.com/hc/en-us/articles/115004290387-Creating-Cache-Keys

```
  "query_string": {
    "include": String array || "*", 
    "exclude": String array || "*"
  },
```

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by svesve** [comment]
probably this bug is in terraform cloudflare module version 2.18.0
in 2.17.0 this is not reproduced

**Comment by jacobbednarz** [comment]
> It seems that that ignore = true is not supported by api or this bug in terraform cloudflare module

`ignore` is syntactic sugar for `exclude = "*"` - see https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule#cache-key-fields and https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/cloudflare/resource_cloudflare_page_rule.go#L889-L891.

are you seeing caching incorrectly? or just the UI option not being selected?

**Comment by jacobbednarz** [comment]
💡 it looks like there is a very subtle difference in the requests here which change the behaviour. `exclude = "*"` sets the ignore all option whereas `exclude = ["*"]` ignores only that single option. looks like this was either a regression or being swallowed in previous versions as the test cases for these were/are all passing.
