### ISSUE TITLE
creating secondary zone with Terraform

### ISSUE THREAD

**Issue by dlavrichev** [cloudflare/terraform-provider-cloudflare#968]
My apologies if this was discussed before...
Is it possible to create a secondary zone using terraform? Current documentation doesn't reveal this as an option: https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/zone
If it is not yet possible can you add it as a feature request?

Thank you!

**Comment by jacobbednarz** [comment]
You current cannot. There is a feature request pending someone to pick it up in #605. 

I'll close this off and we can chat about it in the one issue.
