### ISSUE TITLE
cloudflare_healthcheck make terraform crash

### ISSUE THREAD

**Issue by sveronese** [cloudflare/terraform-provider-cloudflare#972]
### Terraform version
Terraform v0.12.26
+ provider.cloudflare v2.15.0
and 
+ provider.cloudflare v2.18.0

### Affected resource(s)
- cloudflare_healthcheck

### Debug output
https://gist.github.com/sveronese/c283c37f71a635c5e7b5760935d6e438

### Panic output
https://gist.github.com/sveronese/2c08bec145b73e21a7bc23d637420c31

### Expected behavior
After apply, resource should be created

### Actual behavior
Terraform crash.

### Steps to reproduce
Add a resource like this

```
resource "cloudflare_healthcheck" "test_origin_DE" {
  zone_id                      = "af188d90b82139f733a914e2335892f4"
  name                         = "test-origin-DE"
  description                  = "www.xxxxxxx.fr to Origin DE"
  address                      = "myorigin.net"
  suspended                    = false
  check_regions                = ["WEU", "EEU"]
  notification_suspended       = true
  notification_email_addresses = [""]
  type                         = "HTTPS"
  port                         = "443"
  method                       = "GET"
  path                         = "/ping"
  expected_body                = ""
  expected_codes               = ["200"]
  follow_redirects             = true
  allow_insecure               = false
  header {
    header = "Host"
    values = ["www.xxxxxxx.fr"]
  }
  //timeout               = var.timeout
  //retries               = var.retries
  //interval              = var.interval
  //consecutive_fails     = var.consecutive_fails
  //consecutive_successes = var.consecutive_successes
}
```
terraform apply

### Important factoids
N/A

### References
N/A

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
@sveronese why are you setting `notification_email_addresses` to `[""]`? if you don't want it, shouldn't it be omitted?

**Comment by jacobbednarz** [comment]
closing due to lack of information provided. feel free to respond with your use case and we can chat about it some more, .
