### ISSUE TITLE
Expose "default_mode" of WAF Rule through cloudflare_waf_rules data source

### ISSUE THREAD

**Issue by JoseRoman** [cloudflare/terraform-provider-cloudflare#979]
### Current Terraform version
```
Terraform v0.14.5
cloudflare v2.18.0
```

### Description

I would like to have access to the default mode of a WAF rule via the cloudflare_waf_rules data source.

### Use-cases
Being able to modify the mode of 100+ rules via Terraform and leaving the ones that default to "Disabled" untouched requires having visibility into the "default_mode" of each rule through the data source.

### References

I have not found any other issues similar to this. 

I did notice that this is currently available in the cloudflare-go library
https://github.com/cloudflare/cloudflare-go/blob/master/waf.go#L81

### Community note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

**Comment by jacobbednarz** [comment]
please check out #1079 for this one. i've put up the PR and i'd recommend you build the provider locally (docs https://github.com/cloudflare/terraform-provider-cloudflare#building-the-provider) and test it out before it is merged.
